<?php
if(isset($countryId) && trim($countryId)!=''){
    $link = "/facility/".base64_encode($countryId);
}else{
    $link = "/facility";
}
?>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Edit Lab</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="<?php echo $link; ?>" class="breadcrumb">Labs</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Edit Lab</a>
        </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="editLabForm" name="editLabForm" method="post" action="<?php echo $this->url('edit-facility',array('action'=>'edit')); ?>">
        <div class="card">
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">person_pin</i>
                        <input id="facilityName" name="facilityName" type="text" class="validate isRequired" title="Please enter lab name" value="<?php echo $row->facility_name; ?>">
                        <label for="facilityName" class="">Lab Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">code</i>
                        <input id="facilityCode" name="facilityCode" type="text" class="validate isRequired" title="Please enter lab code" value="<?php echo $row->facility_code; ?>" onblur="checkNameValidation('facility', 'facility_code', this, '<?php echo "facility_id##" .$row->facility_id; ?>','The lab code that you entered already exist. Please enter different code')">
                        <label for="facilityCode" class="">Lab Code *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">done</i>
                        <select class="material-select isRequired" id="facilityType" name="facilityType" title="Please select facility type">
                            <?php
                            foreach($facilityTypes as $facilityType){
                                if($facilityType['facility_type_id'] == 2){
                                ?>
                                  <option value="<?php echo base64_encode($facilityType['facility_type_id']);?>" <?php echo($row->facility_type == $facilityType['facility_type_id'])?'selected="selected"':''; ?>><?php echo ucwords($facilityType['facility_type_name']);?></option>
                                <?php
                                }
                            }
                            ?>
                        </select>
                        <label for="facilityType" class="">Facility Type *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">email</i>
                        <input id="email" name="email" type="text" class="validate isRequired" placeholder="eg-user1@gmail.com,user2@gmail.com" title="Please enter email-id" value="<?php echo $row->email; ?>">
                        <label for="email" class="">Email(s) *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">contacts</i>
                        <input id="contactPerson" name="contactPerson" type="text" class="validate isRequired" title="Please enter contact person name" value="<?php echo $row->contact_person; ?>">
                        <label for="contactPerson" class="">Contact Person *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="mobile" name="mobile" type="text" class="validate checkNum isRequired" title="Please enter contact number" value="<?php echo $row->phone_number; ?>" onblur="checkNameValidation('facility', 'phone_number', this, '<?php echo "facility_id##" .$row->facility_id; ?>','The lab contact no. that you entered already exist. Please enter different contact no')">
                        <label for="mobile" class="">Contact Number *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                 <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">room</i>
                        <select class="material-select isRequired" id="country" name="country" title="Please select country">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($countries as $country){
                                ?>
                                <option value="<?php echo base64_encode($country['country_id']);?>" <?php echo($row->country == $country['country_id'])?'selected="selected"':''; ?>><?php echo ucwords($country['country_name']);?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <label for="country" class="">Country *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10 ajaxProvince">
                        <i class="material-icons prefix">room</i>
                        <select class="material-select validate isRequired" id="province" name="province" title="Please select province" onchange="checkProvince(this.value);">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($provinces as $province){
                                ?>
                                <option value="<?php echo base64_encode($province['location_id']);?>" <?php echo($row->province == $province['location_id'])?'selected="selected"':''; ?>><?php echo ucwords($province['location_name']);?></option>
                                <?php
                            }
                            ?>
                            <option value="other">Other</option>
                        </select>
                        <label for="province" class="">Province *</label>
                        <input type="text" id="provinceNew" name="provinceNew" placeholder="Enter Province" title="Please enter province name" class="validate" style="display:none;"/>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10 ajaxDistrict">
                        <i class="material-icons prefix">room</i>
                        <select class="material-select validate isRequired" id="district" name="district" title="Please select district" onchange="checkDistrict(this.value);">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($districts as $district){
                                ?>
                                <option value="<?php echo base64_encode($district['location_id']);?>" <?php echo($row->district == $district['location_id'])?'selected="selected"':''; ?>><?php echo ucwords($district['location_name']);?></option>
                                <?php
                            }
                            ?>
                            <option value="other">Other</option>
                        </select>
                        <label for="district" class="">District *</label>
                        <input type="text" id="districtNew" name="districtNew" placeholder="Enter District" title="Please enter district name" class="validate" style="display:none;"/>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <textarea id="address" name="address" class="materialize-textarea"><?php echo $row->address; ?></textarea>
                        <label for="address">Address</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">navigation</i>
                        <input id="latitude" name="latitude" type="text" class="validate checkNum" title="Please enter latitude" value="<?php echo $row->latitude; ?>">
                        <label for="latitude" class="">Latitude </label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">navigation</i>
                        <input id="longitude" name="longitude" type="text" class="validate checkNum" title="Please enter longitude" value="<?php echo $row->longitude; ?>">
                        <label for="longitude" class="">Longitude </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <textarea id="comments" name="comments" class="materialize-textarea"><?php echo $row->comments; ?></textarea>
                        <label for="comments">Comments</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <select id="facilityStatus" name="facilityStatus" class="material-select">
                            <option value="active" <?php echo($row->status == "active")?'selected="selected"':'';  ?>>Active</option>
                            <option value="inactive" <?php echo($row->status == "inactive")?'selected="selected"':'';  ?>>Inactive</option>
                        </select>
                        <label for="facilityStatus">Lab Status</label>
                    </div>
                </div>
            </div>
            <div class="col s6">
                <input type="hidden" name="redirectUrl" value="<?php echo $link; ?>"/>
                <input id="facilityId" name="facilityId" type="hidden" value="<?php echo base64_encode($row->facility_id); ?>"/>
                <a href="<?php echo $link; ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="updateLab();">UPDATE</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script>
    function checkProvince(val){
        if(val == 'other'){
            $('#provinceNew').show();
            $('#provinceNew').addClass('isRequired');
        }else{
            $('#provinceNew').hide();
            $('#provinceNew').val('');
            $('#provinceNew').removeClass('isRequired');
        } 
    }
    
    function checkDistrict(val){
       if(val == 'other'){
            $('#districtNew').show();
            $('#districtNew').addClass('isRequired');
        }else{
            $('#districtNew').hide();
            $('#districtNew').val('');
            $('#districtNew').removeClass('isRequired');
        }  
    }
    
    $('#country').on('change',function(){
        $.post("<?php echo $this->url('country', array('action' => 'get-country-provinces')); ?>", {country: this.value},
        function(data) {
            $('.ajaxProvince').html(data);
            $('#province').material_select();
            $('div').removeClass('isRequired');
        });
    });
    
    $('#province').on('change',function(){
        if(this.value!= 'other'){
            $.post("<?php echo $this->url('country', array('action' => 'get-province-districts')); ?>", {province: this.value},
            function(data) {
                $('.ajaxDistrict').html(data);
                $('#district').material_select();
                $('div').removeClass('isRequired');
            });
        }else{
            $districts = '';
            $districts+= '<i class="material-icons prefix">room</i>';
            $districts+='<select class="material-select validate isRequired" id="district" name="district" title="Please select district" onchange="checkDistrict(this.value);"><option value=""> -- Select -- </option><option value="other">Other</option></select>';
            $districts+='<label for="district" class="">District *</label>';
            $districts+='<input type="text" id="districtNew" name="districtNew" placeholder="Enter District" title="Please enter district name" class="validate" style="display:none;"/>';
            $('.ajaxDistrict').html($districts);
            $('#district').material_select();
            $('div').removeClass('isRequired');
        }
    });
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if($.trim(checkValue)!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
    
    duplicateName = true;
    function updateLab(){
        flag = deforayValidator.init({
            formId: 'editLabForm'
        });
        
        if(flag){
            document.getElementById('editLabForm').submit();
        }
    }
</script>