<?php
if(trim($countryId)!= ''){
    $link = "/clinic/risk-assessment/".base64_encode($countryId);
}else{
   $link = "/clinic/risk-assessment"; 
}
?>
<style>
    .highlightedTxt{
	text-decoration:underline;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Add Risk Assessment</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="/clinic/risk-assessment/<?php echo base64_encode($countryId); ?>" class="breadcrumb">Risk Assessment Form</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Add Risk Assessment</a>
       </div>
    </div>
    <div class="formContainer row dashboard-wrapper content-container" style="margin-bottom:20px;">
        <form id="addRiskAssessmentForm" name="addRiskAssessmentForm" method="post" action="<?php echo $this->url('add-clinic-risk-assessment',array('action'=>'add')); ?>">
        <div class="card">
            <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Sample Particpant Risk Questionnaire</strong></h6>
            <fieldset style="border-color:#2196F3;border-style:solid;">
                <?php
                if(trim($countryId) == ''){
                ?>
                    <div class="row" style="margin-bottom:0;">
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <select id="country" name="country" class="material-select isRequired" title="Please select country" onchange="getCountriesLabAnc();generateSurveillanceID(this);checkPatientRecord();">
                                    <option value=""> -- Select -- </option>
                                    <?php
                                    foreach($countries as $country){
                                    ?>
                                      <option data-code="<?php echo $country['country_code']; ?>" value="<?php echo base64_encode($country['country_id']); ?>"><?php echo ucwords($country['country_name']); ?></option>
                                    <?php } ?>
                                </select>
                                <label for="country">Country *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <select id="ancSite" name="ancSite" class="material-select isRequired" title="Please select ANC Site">
                                    <option value=""> -- Select -- </option>
                                    <?php
				    foreach($ancSites as $anc){
				    ?>
				      <option value="<?php echo base64_encode($anc['anc_site_id']); ?>"><?php echo $anc['anc_site_code'].' - '.ucwords($anc['anc_site_name']); ?></option>
				    <?php } ?>
                                </select>
                                <label for="ancSite">ANC Site *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="patientBarcodeId" name="patientBarcodeId" type="text" class="validate isRequired" title="Please enter patient barcode id" onblur="checkPatientRecord();">
                                <label for="patientBarcodeId" class="">Patient Barcode ID *</label>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="margin-bottom:0;">
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="interviewerName" name="interviewerName" type="text" class="validate isRequired" title="Please enter interviewer name">
                                <label for="interviewerName" class="">Interviewer Name *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="ancPatientId" name="ancPatientId" type="text" class="validate isRequired" title="Please enter anc patient ID">
                                <label for="ancPatientId" class="">ANC Patient ID *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="interviewDate" name="interviewDate" type="text" class="validate isRequired datepicker" title="Please enter interview date">
                                <label for="interviewDate" class="">Interview Date *</label>
                            </div>
                        </div>
                    </div>
		    <div class="row" style="margin-bottom:0;">
			<div class="col s4">
			    <div class="input-field col m12 s12">
			    Has participant received DREAMS services ? (Optional)<br><br>	
			    <input id="hasParticipantReceivedDreamsServicesYes" class="with-gap" name="hasParticipantReceivedDreamsServices" title="Please select paricipant-dreams services received status" value="yes" type="radio">
			    <label for="hasParticipantReceivedDreamsServicesYes" class="active">Yes </label>&nbsp;&nbsp;
			    <input id="hasParticipantReceivedDreamsServicesNo" class="with-gap" name="hasParticipantReceivedDreamsServices" value="no" type="radio">
			    <label for="hasParticipantReceivedDreamsServicesNo" class="active">No </label>&nbsp;&nbsp;
			    </div>
			</div>
		    </div>
                <?php } else { ?>
                    <div class="row" style="margin-bottom:0;">
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                            <select id="ancSite" name="ancSite" class="material-select isRequired" title="Please select ANC Site">
                            <option value=""> -- Select -- </option>
                            <?php
                                foreach($ancSites as $anc){
                                ?>
                                <option value="<?php echo base64_encode($anc['anc_site_id']); ?>"><?php echo $anc['anc_site_code'].' - '.ucwords($anc['anc_site_name']); ?></option>
                                <?php } ?>
                            </select>
                                <label for="ancSite">ANC Site *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="patientBarcodeId" name="patientBarcodeId" type="text" class="validate isRequired" title="Please enter patient barcode id" onblur="checkPatientRecord();">
                                <label for="patientBarcodeId" class="">Patient Barcode ID *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="interviewerName" name="interviewerName" type="text" class="validate isRequired" title="Please enter interviewer name">
                                <label for="interviewerName" class="">Interviewer Name *</label>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="margin-bottom:0;">
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="ancPatientId" name="ancPatientId" type="text" class="validate isRequired" title="Please enter anc patient ID" onblur="checkPatientRecord();">
                                <label for="ancPatientId" class="">ANC Patient ID *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="interviewDate" name="interviewDate" type="text" class="validate isRequired datepicker" title="Please enter interview date">
                                <label for="interviewDate" class="">Interview Date *</label>
                            </div>
                        </div>
			<div class="col s4">
			    <div class="input-field col m12 s12">
			    Has Participant received DREAMS services ? (Optional)<br><br>
			    <input id="hasParticipantReceivedDreamsServicesYes" class="with-gap" name="hasParticipantReceivedDreamsServices" title="Please select participant-dreams services received status" value="yes" type="radio">
			    <label for="hasParticipantReceivedDreamsServicesYes" class="active">Yes </label>&nbsp;&nbsp;
			    <input id="hasParticipantReceivedDreamsServicesNo" class="with-gap" name="hasParticipantReceivedDreamsServices" value="no" type="radio">
			    <label for="hasParticipantReceivedDreamsServicesNo" class="active">No </label>
			    </div>
			</div>
                    </div>
                <?php } ?>
            </fieldset>
	    <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Recency Test Result</strong></h6>
	    <fieldset id="rtrSection" style="height:90px;border-color:#F44336;border-style:solid;">
		<div class="row" style="margin-bottom:0;">
		    <div class="col s4">
			<div class="input-field col m12 s12">
			Rapid Recency Result *<br><br>
			<input id="hasPatientHadRapidRecencyTestYes" class="with-gap isRequired" name="hasPatientHadRapidRecencyTest" title="Please select patient rapid recency test status" value="done" type="radio">
			<label for="hasPatientHadRapidRecencyTestYes" class="active">Done </label>&nbsp;&nbsp;
			<input id="hasPatientHadRapidRecencyTestNo" class="with-gap" name="hasPatientHadRapidRecencyTest" value="not done" type="radio">
			<label for="hasPatientHadRapidRecencyTestNo" class="active">Not Done </label>&nbsp;&nbsp;
			</div>
		    </div>
		    <div class="col s4 rrrSection" style="display:none;">
			<div class="input-field col m12 s12">
			<select id="rrrHIVDiagnostic" name="rrrHIVDiagnostic" class="material-select" title="Please select HIV diagnostic line">
                            <option value=""> -- Select -- </option>
			    <option value="positive">Positive</option>
			    <option value="negative">Negative</option>
			    <option value="invalid">Invalid</option>
                        </select>
                        <label for="rrrHIVDiagnostic">HIV Diagnostic Line </label>
			</div>
		    </div>
		    <div class="col s4 rrrRecency rrrSection" style="display:none;">
			<div class="input-field col m12 s12">
			<select id="rrrRecency" name="rrrRecency" class="material-select" title="Please select recency line">
                            <option value=""> -- Select -- </option>
			    <option value="recent">Recent</option>
			    <option value="long term">Long Term</option>
			    <option value="invalid">Invalid</option>
                        </select>
                        <label for="rrrRecency">Recency Line </label>
			</div>
		    </div>
		</div>
	    </fieldset>
            <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Demographic Characteristics</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q1. What kind of work/occupation do you do most of the time? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="occupation" name="occupation" class="material-select isRequired" title="Don't leave 1st question">
                        <option value=""> -- Select -- </option>
                        <?php
			foreach($occupationTypes as $occupation){
			?>
                           <option value="<?php echo base64_encode($occupation['occupation_id']); ?>"><?php echo ucwords($occupation['occupation']); ?></option>
			<?php } ?>
                        <option value="other">Other</option>
                    </select>
                </div>
		<div class="col s4 occupationNew" style="display:none;">
		    <input id="occupationNew" name="occupationNew" type="text" class="validate" placeholder="Occupation" title="Please enter occupation" onblur="checkNameValidation('occupation_type', 'occupation', this, null,'The occupation that you entered already listed. Please enter different occupation');">
		</div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q2. Have you ever attended school? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s8">
                    <input id="hasPatientEverAttendedSchoolYes" class="with-gap isRequired" name="hasPatientEverAttendedSchool" title="Don't leave 2nd question" value="yes" type="radio">
		    <label for="hasPatientEverAttendedSchoolYes" class="active">Yes </label>&nbsp;&nbsp;
                    <input id="hasPatientEverAttendedSchoolNo" class="with-gap" name="hasPatientEverAttendedSchool" value="no" type="radio">
		    <label for="hasPatientEverAttendedSchoolNo" class="active">No </label>&nbsp;&nbsp;
		    <input id="hasPatientEverAttendedSchoolDK" class="with-gap" name="hasPatientEverAttendedSchool" value="dontknow" type="radio">
		    <label for="hasPatientEverAttendedSchoolDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="hasPatientEverAttendedSchoolR" class="with-gap" name="hasPatientEverAttendedSchool" value="refused" type="radio">
		    <label for="hasPatientEverAttendedSchoolR" class="active">Refused </label>&nbsp;&nbsp;
		    <input id="hasPatientEverAttendedSchoolRNA" class="with-gap" name="hasPatientEverAttendedSchool" value="response not available" type="radio">
		    <label for="hasPatientEverAttendedSchoolRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row degreeSection" style="margin-bottom:0;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q2A. What was the highest level of education that you completed or are attending now?<span class="degreeSectionRequired">*</span>
                </div>
            </div>
            <div class="row degreeSection" style="margin-bottom:10px;">
                <div class="col s4 degree" style="padding-left:3%;">
                    <select id="degree" name="degree" class="material-select isRequired" title="Don't leave 2nd question partially">
                        <option value=""> -- Select -- </option>
                        <option value="primary">Primary/Vocational</option>
                        <option value="secondary">Secondary</option>
                        <option value="university">University/College</option>
			<option value="dontknow">Don't know</option>
			<option value="refused">Refused</option>
			<option value="response not available">Response Not Available</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q3. Have you <span class="highlightedTxt">ever</span> been married or lived with a partner in a union as if married? * &nbsp;(If no, go to question 7)
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s8">
                    <input id="everBeenMarriedYes" class="with-gap isRequired" name="everBeenMarried" title="Don't leave 3rd question" value="yes" type="radio">
		    <label for="everBeenMarriedYes" class="active">Yes </label>&nbsp;&nbsp;
                    <input id="everBeenMarriedNo" class="with-gap" name="everBeenMarried" value="no" type="radio">
		    <label for="everBeenMarriedNo" class="active">No </label>&nbsp;&nbsp;
		    <input id="everBeenMarriedRNA" class="with-gap" name="everBeenMarried" value="response not available" type="radio">
		    <label for="everBeenMarriedRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    4. How old were you when you <span class="highlightedTxt">first</span> got married or lived with a partner in a union? <span class="everBeenMarriedSectionRequired">*</span>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:10px;">
                <div class="col s8">
                    <input id="ageAtFirstMarriageInYears" name="ageAtFirstMarriageInYears" type="text" class="validate years checkNum isRequired" title="Please enter years" style="width:10%;"> Years&nbsp;
                    <input id="ageAtFirstMarriageDK" class="with-gap" name="ageAtFirstMarriage" value="dontknow" type="radio">
		    <label for="ageAtFirstMarriageDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="ageAtFirstMarriageR" class="with-gap" name="ageAtFirstMarriage" value="refused" type="radio">
		    <label for="ageAtFirstMarriageR" class="active">Refused </label>&nbsp;&nbsp;
		    <input id="ageAtFirstMarriageRNA" class="with-gap" name="ageAtFirstMarriage" value="response not available" type="radio">
		    <label for="ageAtFirstMarriageRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:0;">
                <div class="col s12">
                    5. Have you <span class="highlightedTxt">ever</span> been widowed? That is, did a spouse ever pass away while you were still married or living with them? <span class="everBeenMarriedSectionRequired">*</span>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:10px;">
                <div class="col s8">
                    <input id="everBeenWidowedYes" class="with-gap isRequired" name="everBeenWidowed" title="Don't leave 5th question" value="yes" type="radio">
		    <label for="everBeenWidowedYes" class="active">Yes </label>&nbsp;&nbsp;
                    <input id="everBeenWidowedNo" class="with-gap" name="everBeenWidowed" value="no" type="radio">
		    <label for="everBeenWidowedNo" class="active">No </label>&nbsp;&nbsp;
                    <input id="everBeenWidowedDK" class="with-gap" name="everBeenWidowed" value="dontknow" type="radio">
		    <label for="everBeenWidowedDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="everBeenWidowedR" class="with-gap" name="everBeenWidowed" value="refused" type="radio">
		    <label for="everBeenWidowedR" class="active">Refused </label>&nbsp;&nbsp;
		    <input id="everBeenWidowedRNA" class="with-gap" name="everBeenWidowed" value="response not available" type="radio">
		    <label for="everBeenWidowedRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    6. What is your marital status <span class="highlightedTxt">now</span>? <span class="everBeenMarriedSectionRequired">*</span>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:10px;">
                <div class="col s4 currentMaritalStatus">
                    <select id="currentMaritalStatus" name="currentMaritalStatus" class="material-select isRequired" title="Don't leave 6th question">
                        <option value=""> -- Select -- </option>
                        <option value="married">Married/Cohabiting</option>
                        <option value="nevermarried">Never Married/Cohabiting</option>
                        <option value="widowed">widowed</option>
                        <option value="separated">Separated</option>
                        <option value="divorced">Divorced</option>
                        <option value="dontknow">Don't Know</option>
                        <option value="refused">Refused</option>
			<option value="response not available">Response Not Available</option>
                    </select>
                </div>
            </div>
            <h6 style="padding:0px 0px 10px 6px;font-size:16px;"><strong>HIV Testing History</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    7. When was the <span class="highlightedTxt">most recent</span> time you were tested for HIV? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="timeOfLastHIVTest" name="timeOfLastHIVTest" class="material-select isRequired" title="Don't leave 7th question">
                        <option value=""> -- Select -- </option>
                        <option value="nevertested">Never Tested</option>
                        <option value="lt3months">< 3 Months Ago</option>
                        <option value="3to6months">3-6 Months Ago</option>
                        <option value="7to12months">7-12 Months Ago</option>
                        <option value="gt12months"> > 12 months</option>
                        <option value="dontknow">Don't Know</option>
                        <option value="refused">Refused</option>
			<option value="response not available">Response Not Available</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    8. What was the result of that HIV test? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="lastHIVTestStatus" name="lastHIVTestStatus" class="material-select isRequired" title="Don't leave 8th question">
                        <option value=""> -- Select -- </option>
                        <option value="didnotreceive">I Did Not Receive Result</option>
                        <option value="hivpos">HIV+</option>
                        <option value="hivneg">HIV-</option>
                        <option value="indeterminate">Indeterminate</option>
                        <option value="dontknow">Don't Know</option>
                        <option value="refused">Refused</option>
			<option value="response not available">Response Not Available</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    9. What is your <span class="highlightedTxt">spouse/main</span> sexual partner's HIV status? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="partnerHIVTestStatus" name="partnerHIVTestStatus" class="material-select isRequired" title="Don't leave 9th question">
                        <option value=""> -- Select -- </option>
                        <option value="hivpos">HIV+</option>
                        <option value="hivneg">HIV-</option>
                        <option value="idonotknow">I Do Not Know</option>
                        <option value="refused">Refused</option>
			<option value="response not available">Response Not Available</option>
                    </select>
                </div>
            </div>
            <h6 style="padding:0px 0px 10px 6px;font-size:16px;"><strong>Sexual Activity and History of Sexually Transmitted Infections</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    10. How old were you when you had sexual intercourse for the very <span class="highlightedTxt">first</span> time? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s6">
                    <input id="ageAtVeryFirstSex" name="ageAtVeryFirstSex" type="text" class="validate isRequired years checkNum" title="Please enter years" style="width:20%;"> Years &nbsp;&nbsp;
		    <input id="ageAtVeryFirstSexRNA" class="with-gap" name="ageAtVeryFirstSexRNA" value="NA" type="checkbox">
		    <label for="ageAtVeryFirstSexRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    11. The <span class="highlightedTxt">first</span> time you had sex, was it because you wanted to or because you were forced to? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s10">
                    <input id="reasonForVeryFirstSexWT" class="with-gap isRequired" name="reasonForVeryFirstSex" title="Don't leave 11th question" value="wantedto" type="radio">
		    <label for="reasonForVeryFirstSexWT" class="active">Wanted To </label>&nbsp;&nbsp;
                    <input id="reasonForVeryFirstSexFT" class="with-gap" name="reasonForVeryFirstSex" value="forcedto" type="radio">
		    <label for="reasonForVeryFirstSexFT" class="active">Forced To </label>&nbsp;&nbsp;
                    <input id="reasonForVeryFirstSexDK" class="with-gap" name="reasonForVeryFirstSex" value="dontknow" type="radio">
		    <label for="reasonForVeryFirstSexDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="reasonForVeryFirstSexR" class="with-gap" name="reasonForVeryFirstSex" value="refused" type="radio">
		    <label for="reasonForVeryFirstSexR" class="active">Refused </label>&nbsp;&nbsp;
		    <input id="reasonForVeryFirstSexRNA" class="with-gap" name="reasonForVeryFirstSex" value="response not available" type="radio">
		    <label for="reasonForVeryFirstSexRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    12. How many different people have you had sexual intercourse with <span class="highlightedTxt">in your entire life</span>? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s8">
                    <input id="noOfSexualPartnersInNumbers" name="noOfSexualPartnersInNumbers" type="text" class="validate persons checkNum isRequired" title="Please enter no. of persons" style="width:13%;"> Persons&nbsp;
                    <input id="noOfSexualPartnersDK" class="with-gap" name="noOfSexualPartners" value="dontknow" type="radio">
		    <label for="noOfSexualPartnersDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="noOfSexualPartnersR" class="with-gap" name="noOfSexualPartners" value="refused" type="radio">
		    <label for="noOfSexualPartnersR" class="active">Refused </label>&nbsp;&nbsp;
		    <input id="noOfSexualPartnersRNA" class="with-gap" name="noOfSexualPartners" value="response not available" type="radio">
		    <label for="noOfSexualPartnersRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    13. How many different people have you had sex with in the last 6 months? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s8">
                    <input id="noOfSexualPartnersInLastSixMonthsInNumbers" name="noOfSexualPartnersInLastSixMonthsInNumbers" type="text" class="validate persons checkNum isRequired" title="Please enter no. of persons" style="width:13%;"> Persons&nbsp;
                    <input id="noOfSexualPartnersInLastSixMonthsDK" class="with-gap" name="noOfSexualPartnersInLastSixMonths" value="dontknow" type="radio">
		    <label for="noOfSexualPartnersInLastSixMonthsDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="noOfSexualPartnersInLastSixMonthsR" class="with-gap" name="noOfSexualPartnersInLastSixMonths" value="refused" type="radio">
		    <label for="noOfSexualPartnersInLastSixMonthsR" class="active">Refused </label>&nbsp;&nbsp;
		    <input id="noOfSexualPartnersInLastSixMonthsRNA" class="with-gap" name="noOfSexualPartnersInLastSixMonths" value="response not available" type="radio">
		    <label for="noOfSexualPartnersInLastSixMonthsRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    14. How old was your <span class="highlightedTxt">main</span> sexual partner on his last birthday? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s8">
                    <input id="ageOfMainSexualPartnerAtLastBirthdayInYears" name="ageOfMainSexualPartnerAtLastBirthdayInYears" type="text" class="validate isRequired years checkNum" title="Please enter years" style="width:13%;"> Years&nbsp;
                    <input id="ageOfMainSexualPartnerAtLastBirthdayDK" class="with-gap" name="ageOfMainSexualPartnerAtLastBirthday" value="dontknow" type="radio">
		    <label for="ageOfMainSexualPartnerAtLastBirthdayDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="ageOfMainSexualPartnerAtLastBirthdayR" class="with-gap" name="ageOfMainSexualPartnerAtLastBirthday" value="refused" type="radio">
		    <label for="ageOfMainSexualPartnerAtLastBirthdayR" class="active">Refused </label>&nbsp;&nbsp;
		    <input id="ageOfMainSexualPartnerAtLastBirthdayRNA" class="with-gap" name="ageOfMainSexualPartnerAtLastBirthday" value="response not available" type="radio">
		    <label for="ageOfMainSexualPartnerAtLastBirthdayRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    15. Is the age of your main sexual partner older, younger, or the same age as you? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="ageDiffOfMainSexualPartner" name="ageDiffOfMainSexualPartner" class="material-select isRequired" title="Don't leave 15th question">
                        <option value=""> -- Select -- </option>
                        <option value="lt5yearolder"> < 5 Years Older</option>
                        <option value="5to10yearolder"> 5-10 Years Older</option>
                        <option value="10yearsolder"> >10 Years Older</option>
                        <option value="sameage">Same Age</option>
                        <option value="lt5yearyounger"> < 5 Years Younger</option>
                        <option value="5to10yearyounger">5-10 Years Younger</option>
                        <option value="gt10yearyounger"> >10 Years Younger</option>
                        <option value="dontknow">Don't Know</option>
                        <option value="refused">Refused</option>
			<option value="response not available">Response Not Available</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    16. Is your <span class="highlightedTxt">main</span> sexual partner circumcised? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s8">
                    <input id="isPartnerCircumcisedYes" class="with-gap isRequired" name="isPartnerCircumcised" title="Don't leave 16th question" value="yes" type="radio">
		    <label for="isPartnerCircumcisedYes" class="active">Yes </label>&nbsp;&nbsp;
                    <input id="isPartnerCircumcisedNo" class="with-gap" name="isPartnerCircumcised" value="no" type="radio">
		    <label for="isPartnerCircumcisedNo" class="active">No </label>&nbsp;&nbsp;
                    <input id="isPartnerCircumcisedDK" class="with-gap" name="isPartnerCircumcised" value="dontknow" type="radio">
		    <label for="isPartnerCircumcisedDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="isPartnerCircumcisedR" class="with-gap" name="isPartnerCircumcised" value="refused" type="radio">
		    <label for="isPartnerCircumcisedR" class="active">Refused </label>&nbsp;&nbsp;
		    <input id="isPartnerCircumcisedRNA" class="with-gap" name="isPartnerCircumcised" value="response not available" type="radio">
		    <label for="isPartnerCircumcisedRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    17. When did you last receive money/gifts in exchange for sex? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="lastTimeOfReceivingGiftForSex" name="lastTimeOfReceivingGiftForSex" class="material-select isRequired" title="Don't leave 17th question">
                        <option value=""> -- Select -- </option>
                        <option value="never"> Never</option>
                        <option value="lt6months"> < 6 Months Ago</option>
                        <option value="6to12months"> 6-12 Months Ago</option>
                        <option value="gt12months"> > 12 Months Ago</option>
                        <option value="dontknow">Don't Know</option>
                        <option value="refused">Refused</option>
			<option value="response not available">Response Not Available</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    18. How many times have you been pregnant? * (including this pregnancy)
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s6">
                    <input id="noOfTimesBeenPregnant" name="noOfTimesBeenPregnant" type="text" class="validate times checkNum isRequired" title="Don't leave 18th question" style="width:20%;"> Times &nbsp;&nbsp;
		    <input id="noOfTimesBeenPregnantRNA" class="with-gap" name="noOfTimesBeenPregnantRNA" value="NA" type="checkbox">
		    <label for="noOfTimesBeenPregnantRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    19. Before becoming pregnant this time, in the past year how frequently did you use a condom when having sexual intercourse? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s10">
                    <input id="noOfTimesCondomUsedBeforePregnancyA" class="with-gap isRequired" name="noOfTimesCondomUsedBeforePregnancy" title="Don't leave 19th question" value="always" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyA" class="active">Always </label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedBeforePregnancyS" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="sometimes" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyS" class="active">Sometimes </label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedBeforePregnancyN" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="never" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyN" class="active">Never </label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedBeforePregnancyDK" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="dontknow" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedBeforePregnancyR" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="refused" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyR" class="active">Refused </label>&nbsp;&nbsp;
		    <input id="noOfTimesCondomUsedBeforePregnancyRNA" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="response not available" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    20. Since becoming pregnant this time, how frequently have you used a condom when having sexual intercourse? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s10">
                    <input id="noOfTimesCondomUsedAfterPregnancyA" class="with-gap isRequired" name="noOfTimesCondomUsedAfterPregnancy" title="Don't leave 20th question" value="always" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyA" class="active">Always </label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedAfterPregnancyS" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="sometimes" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyS" class="active">Sometimes </label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedAfterPregnancyN" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="never" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyN" class="active">Never </label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedAfterPregnancyDK" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="dontknow" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedAfterPregnancyR" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="refused" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyR" class="active">Refused </label>&nbsp;&nbsp;
		    <input id="noOfTimesCondomUsedAfterPregnancyRNA" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="response not available" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    21. In the past year, did you have symptoms such as genital discharge, sores in your genital area, pain during urination, or pain in your lower abdomen? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s8">
                    <input id="hasPatientHadPainInLowerAbdomenYes" class="with-gap isRequired" name="hasPatientHadPainInLowerAbdomen" title="Don't leave 21st question" value="yes" type="radio">
		    <label for="hasPatientHadPainInLowerAbdomenYes" class="active">Yes </label>&nbsp;&nbsp;
                    <input id="hasPatientHadPainInLowerAbdomenNo" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="no" type="radio">
		    <label for="hasPatientHadPainInLowerAbdomenNo" class="active">No </label>&nbsp;&nbsp;
                    <input id="hasPatientHadPainInLowerAbdomenDK" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="dontknow" type="radio">
		    <label for="hasPatientHadPainInLowerAbdomenDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="hasPatientHadPainInLowerAbdomenR" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="refused" type="radio">
		    <label for="hasPatientHadPainInLowerAbdomenR" class="active">Refused </label>&nbsp;&nbsp;
		    <input id="hasPatientHadPainInLowerAbdomenRNA" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="response not available" type="radio">
		    <label for="hasPatientHadPainInLowerAbdomenRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    22. If yes, were you treated for these symptoms? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s8">
                    <input id="hasPatientBeenTreatedForLowerAbdomenPainYes" class="with-gap isRequired" name="hasPatientBeenTreatedForLowerAbdomenPain" title="Don't leave 22nd question" value="yes" type="radio">
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainYes" class="active">Yes </label>&nbsp;&nbsp;
                    <input id="hasPatientBeenTreatedForLowerAbdomenPainNo" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="no" type="radio">
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainNo" class="active">No </label>&nbsp;&nbsp;
                    <input id="hasPatientBeenTreatedForLowerAbdomenPainDK" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="dontknow" type="radio">
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="hasPatientBeenTreatedForLowerAbdomenPainR" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="refused" type="radio">
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainR" class="active">Refused </label>&nbsp;&nbsp;
		    <input id="hasPatientBeenTreatedForLowerAbdomenPainRNA" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="response not available" type="radio">
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    23. Have you <span class="highlightedTxt">ever</span> been diagnosed or treated for syphilis? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s8">
                    <input id="hasPatientEverBeenTreatedForSyphilisYes" class="with-gap isRequired" name="hasPatientEverBeenTreatedForSyphilis" title="Don't leave 23rd question" value="yes" type="radio">
		    <label for="hasPatientEverBeenTreatedForSyphilisYes" class="active">Yes </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenTreatedForSyphilisNo" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="no" type="radio">
		    <label for="hasPatientEverBeenTreatedForSyphilisNo" class="active">No </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenTreatedForSyphilisDK" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="dontknow" type="radio">
		    <label for="hasPatientEverBeenTreatedForSyphilisDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenTreatedForSyphilisR" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="refused" type="radio">
		    <label for="hasPatientEverBeenTreatedForSyphilisR" class="active">Refused </label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenTreatedForSyphilisRNA" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="response not available" type="radio">
		    <label for="hasPatientEverBeenTreatedForSyphilisRNA" class="active">Response Not Available </label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    24. Have you ever received a vaccine to prevent human papillomavirus (HPV), a common virus that be passed through sexual contact? *
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s8">
                    <input id="hasPatientEverReceivedVaccineToPreventHPVYes" class="with-gap isRequired" name="hasPatientEverReceivedVaccineToPreventHPV" title="Don't leave 24th question" value="yes" type="radio">
		    <label for="hasPatientEverReceivedVaccineToPreventHPVYes" class="active">Yes </label>&nbsp;&nbsp;
                    <input id="hasPatientEverReceivedVaccineToPreventHPVNo" class="with-gap" name="hasPatientEverReceivedVaccineToPreventHPV" value="no" type="radio">
		    <label for="hasPatientEverReceivedVaccineToPreventHPVNo" class="active">No </label>&nbsp;&nbsp;
                    <input id="hasPatientEverReceivedVaccineToPreventHPVDK" class="with-gap" name="hasPatientEverReceivedVaccineToPreventHPV" value="dontknow" type="radio">
		    <label for="hasPatientEverReceivedVaccineToPreventHPVDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="hasPatientEverReceivedVaccineToPreventHPVR" class="with-gap" name="hasPatientEverReceivedVaccineToPreventHPV" value="refused" type="radio">
		    <label for="hasPatientEverReceivedVaccineToPreventHPVR" class="active">Refused </label>&nbsp;&nbsp;
		    <input id="hasPatientEverReceivedVaccineToPreventHPVRNA" class="with-gap" name="hasPatientEverReceivedVaccineToPreventHPV" value="response not available" type="radio">
		    <label for="hasPatientEverReceivedVaccineToPreventHPVRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Alcohol and drug use</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    25. During the past 6 months, on how many days did you have at least one drink containing alcohol? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s10">
                    <input id="hasPatientHadDrinkWithAlcoholInLastSixMonthsInDays" name="hasPatientHadDrinkWithAlcoholInLastSixMonthsInDays" type="text" class="validate days checkNum isRequired" title="Please enter no. of days" style="width:10%;"> Days&nbsp;
                    <input id="hasPatientHadDrinkWithAlcoholInLastSixMonthsNot" class="with-gap" name="hasPatientHadDrinkWithAlcoholInLastSixMonths" value="havenotdrink" type="radio">
		    <label for="hasPatientHadDrinkWithAlcoholInLastSixMonthsNot" class="active">Haven't Had a Drink </label>&nbsp;&nbsp;
                    <input id="hasPatientHadDrinkWithAlcoholInLastSixMonthsDK" class="with-gap" name="hasPatientHadDrinkWithAlcoholInLastSixMonths" value="dontknow" type="radio">
		    <label for="hasPatientHadDrinkWithAlcoholInLastSixMonthsDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="hasPatientHadDrinkWithAlcoholInLastSixMonthsR" class="with-gap" name="hasPatientHadDrinkWithAlcoholInLastSixMonths" value="refusedtoanswer" type="radio">
		    <label for="hasPatientHadDrinkWithAlcoholInLastSixMonthsR" class="active">Refused To Answer</label>&nbsp;&nbsp;
		    <input id="hasPatientHadDrinkWithAlcoholInLastSixMonthsRNA" class="with-gap" name="hasPatientHadDrinkWithAlcoholInLastSixMonths" value="response not available" type="radio">
		    <label for="hasPatientHadDrinkWithAlcoholInLastSixMonthsRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    26. How often do you have 4 or more drinks with alcohol on one occasion? * (e.g. within 2 hours)
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="hasPatientOftenHad4rmoreDrinksWithAlcoholOnOneOccasion" name="hasPatientOftenHad4rmoreDrinksWithAlcoholOnOneOccasion" class="material-select isRequired" title="Don't leave 26th question">
                        <option value=""> -- Select -- </option>
                        <option value="never">Never</option>
                        <option value="monthly">Monthly</option>
                        <option value="weekly">Weekly</option>
                        <option value="daily">Daily or On Most Days of The Week</option>
                        <option value="dontknow">Don't Know</option>
                        <option value="refused">Refused</option>
			<option value="response not available">Response Not Available</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    27. Have you <span class="highlightedTxt">ever</span> tried recreational drugs? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s8">
                    <input id="hasPatientEverTriedRecreationalDrugsYes" class="with-gap isRequired" name="hasPatientEverTriedRecreationalDrugs" title="Don't leave 27th question" value="yes" type="radio">
		    <label for="hasPatientEverTriedRecreationalDrugsYes" class="active">Yes </label>&nbsp;&nbsp;
                    <input id="hasPatientEverTriedRecreationalDrugsNo" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="no" type="radio">
		    <label for="hasPatientEverTriedRecreationalDrugsNo" class="active">No </label>&nbsp;&nbsp;
                    <input id="hasPatientEverTriedRecreationalDrugsDK" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="dontknow" type="radio">
		    <label for="hasPatientEverTriedRecreationalDrugsDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="hasPatientEverTriedRecreationalDrugsR" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="refused" type="radio">
		    <label for="hasPatientEverTriedRecreationalDrugsR" class="active">Refused</label>&nbsp;&nbsp;
		    <input id="hasPatientEverTriedRecreationalDrugsRNA" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="response not available" type="radio">
		    <label for="hasPatientEverTriedRecreationalDrugsRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    28. In the <span class="highlightedTxt">last 6 months</span>, have you taken any recreational drugs? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsYes" class="with-gap isRequired" name="hasPatientHadRecreationalDrugsInLastSixMonths" title="Don't leave 28th question" value="yes" type="radio">
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsYes" class="active">Yes </label>&nbsp;&nbsp;
                    <span class="recreationalDrugs" style="display:none;">Specify Drug(s) <input id="recreationalDrugs" name="recreationalDrugs" type="text" class="validate" title="Please enter recreational drugs" style="width:30%;">&nbsp;</span>
                    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsNo" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="no" type="radio">
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsNo" class="active">No </label>&nbsp;&nbsp;
                    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsDK" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="dontknow" type="radio">
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsR" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="refused" type="radio">
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsR" class="active">Refused</label>&nbsp;&nbsp;
		    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsRNA" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="response not available" type="radio">
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsRNA" class="active">Response Not Available </label>
                </div>
            </div>
	    <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Abuse</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    29. Have you ever been emotionally or physically abused by your partner or someone important to you? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12" style="margin-bottom:20px;">
                    <input id="hasPatientEverBeenAbusedBySomeoneYes" class="with-gap isRequired" name="hasPatientEverBeenAbusedBySomeone" title="Don't leave 29th question" value="yes" type="radio">
		    <label for="hasPatientEverBeenAbusedBySomeoneYes" class="active">Yes </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenAbusedBySomeoneNo" class="with-gap" name="hasPatientEverBeenAbusedBySomeone" value="no" type="radio">
		    <label for="hasPatientEverBeenAbusedBySomeoneNo" class="active">No </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenAbusedBySomeoneDK" class="with-gap" name="hasPatientEverBeenAbusedBySomeone" value="dontknow" type="radio">
		    <label for="hasPatientEverBeenAbusedBySomeoneDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenAbusedBySomeoneR" class="with-gap" name="hasPatientEverBeenAbusedBySomeone" value="refused" type="radio">
		    <label for="hasPatientEverBeenAbusedBySomeoneR" class="active">Refused</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenAbusedBySomeoneRNA" class="with-gap" name="hasPatientEverBeenAbusedBySomeone" value="response not available" type="radio">
		    <label for="hasPatientEverBeenAbusedBySomeoneRNA" class="active">Response Not Available </label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    30. Within the last year, have you ever been hit, slapped, kicked, or otherwise physically hurt by someone? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12" style="margin-bottom:20px;">
                    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearYes" class="with-gap isRequired" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" title="Don't leave 30th question" value="yes" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearYes" class="active">Yes </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearNo" class="with-gap" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" value="no" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearNo" class="active">No </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearDK" class="with-gap" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" value="dontknow" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearR" class="with-gap" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" value="refused" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearR" class="active">Refused</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearRNA" class="with-gap" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" value="response not available" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearRNA" class="active">Response Not Available </label>
                </div>
            </div>
	    <div class="row patientHurtBySomeoneWithinLastYear" style="margin-bottom:0;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If YES, who
                </div>
            </div>
	    <div class="row patientHurtBySomeoneWithinLastYear" style="margin-bottom:10px;display:none;">
                <div class="col s12" style="margin-bottom:20px;">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="patientHurtBySomeoneWithinLastYearH" class="with-gap" name="patientHurtBySomeoneWithinLastYear" title="Don't leave 30th question partially" value="husband" type="radio">
		    <label for="patientHurtBySomeoneWithinLastYearH" class="active">Husband </label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneWithinLastYearExH" class="with-gap" name="patientHurtBySomeoneWithinLastYear" value="ex-husband" type="radio">
		    <label for="patientHurtBySomeoneWithinLastYearExH" class="active">Ex-Husband </label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneWithinLastYearBf" class="with-gap" name="patientHurtBySomeoneWithinLastYear" value="boyfriend" type="radio">
		    <label for="patientHurtBySomeoneWithinLastYearBf" class="active">Boyfriend </label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneWithinLastYearS" class="with-gap" name="patientHurtBySomeoneWithinLastYear" value="stranger" type="radio">
		    <label for="patientHurtBySomeoneWithinLastYearS" class="active">Stranger</label>
		    <input id="patientHurtBySomeoneWithinLastYearO" class="with-gap" name="patientHurtBySomeoneWithinLastYear" value="other" type="radio">
		    <label for="patientHurtBySomeoneWithinLastYearO" class="active">Other</label>
		    <input id="patientHurtBySomeoneWithinLastYearM" class="with-gap" name="patientHurtBySomeoneWithinLastYear" value="multiple" type="radio">
		    <label for="patientHurtBySomeoneWithinLastYearM" class="active">Multiple</label>&nbsp;&nbsp;&nbsp;&nbsp;
		    <input id="patientHurtBySomeoneWithinLastYearInNoofTimes" name="patientHurtBySomeoneWithinLastYearInNoofTimes" type="text" class="validate nooftimes checkNum" placeholder="Total no.of times" title="Please enter no. of times" style="width:12%;"> Times
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    31. Since you've been pregnant have you been slapped, kicked or otherwise physically hurt by someone? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12" style="margin-bottom:20px;">
                    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyYes" class="with-gap isRequired" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" title="Don't leave 31st question" value="yes" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyYes" class="active">Yes </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyNo" class="with-gap" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" value="no" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyNo" class="active">No </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyDK" class="with-gap" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" value="dontknow" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyR" class="with-gap" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" value="refused" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyR" class="active">Refused</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyRNA" class="with-gap" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" value="response not available" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyRNA" class="active">Response Not Available </label>
                </div>
            </div>
	    <div class="row patientHurtBySomeoneDuringPregnancy" style="margin-bottom:0;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If YES, who
                </div>
            </div>
	    <div class="row patientHurtBySomeoneDuringPregnancy" style="margin-bottom:10px;display:none;">
                <div class="col s12" style="margin-bottom:20px;">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="patientHurtBySomeoneDuringPregnancyH" class="with-gap" name="patientHurtBySomeoneDuringPregnancy" title="Don't leave 31st question partially" value="husband" type="radio">
		    <label for="patientHurtBySomeoneDuringPregnancyH" class="active">Husband </label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneDuringPregnancyExH" class="with-gap" name="patientHurtBySomeoneDuringPregnancy" value="ex-husband" type="radio">
		    <label for="patientHurtBySomeoneDuringPregnancyExH" class="active">Ex-Husband </label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneDuringPregnancyBf" class="with-gap" name="patientHurtBySomeoneDuringPregnancy" value="boyfriend" type="radio">
		    <label for="patientHurtBySomeoneDuringPregnancyBf" class="active">Boyfriend </label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneDuringPregnancyS" class="with-gap" name="patientHurtBySomeoneDuringPregnancy" value="stranger" type="radio">
		    <label for="patientHurtBySomeoneDuringPregnancyS" class="active">Stranger</label>
		    <input id="patientHurtBySomeoneDuringPregnancyO" class="with-gap" name="patientHurtBySomeoneDuringPregnancy" value="other" type="radio">
		    <label for="patientHurtBySomeoneDuringPregnancyO" class="active">Other</label>
		    <input id="patientHurtBySomeoneDuringPregnancyM" class="with-gap" name="patientHurtBySomeoneDuringPregnancy" value="multiple" type="radio">
		    <label for="patientHurtBySomeoneDuringPregnancyM" class="active">Multiple</label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    32. Within the last year, has anyone forced you to have sexual activities? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12" style="margin-bottom:20px;">
                    <input id="hasPatientEverBeenForcedForSexWithinLastYearYes" class="with-gap isRequired" name="hasPatientEverBeenForcedForSexWithinLastYear" title="Don't leave 32nd question" value="yes" type="radio">
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearYes" class="active">Yes </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenForcedForSexWithinLastYearNo" class="with-gap" name="hasPatientEverBeenForcedForSexWithinLastYear" value="no" type="radio">
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearNo" class="active">No </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenForcedForSexWithinLastYearDK" class="with-gap" name="hasPatientEverBeenForcedForSexWithinLastYear" value="dontknow" type="radio">
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenForcedForSexWithinLastYearR" class="with-gap" name="hasPatientEverBeenForcedForSexWithinLastYear" value="refused" type="radio">
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearR" class="active">Refused</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenForcedForSexWithinLastYearRNA" class="with-gap" name="hasPatientEverBeenForcedForSexWithinLastYear" value="response not available" type="radio">
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearRNA" class="active">Response Not Available </label>
                </div>
            </div>
	    <div class="row patientForcedForSexWithinLastYear" style="margin-bottom:0;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If YES, who
                </div>
            </div>
	    <div class="row patientForcedForSexWithinLastYear" style="margin-bottom:10px;display:none;">
                <div class="col s12" style="margin-bottom:20px;">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="patientForcedForSexWithinLastYearH" class="with-gap" name="patientForcedForSexWithinLastYear" title="Don't leave 32nd question partially" value="husband" type="radio">
		    <label for="patientForcedForSexWithinLastYearH" class="active">Husband </label>&nbsp;&nbsp;
                    <input id="patientForcedForSexWithinLastYearExH" class="with-gap" name="patientForcedForSexWithinLastYear" value="ex-husband" type="radio">
		    <label for="patientForcedForSexWithinLastYearExH" class="active">Ex-Husband </label>&nbsp;&nbsp;
                    <input id="patientForcedForSexWithinLastYearBf" class="with-gap" name="patientForcedForSexWithinLastYear" value="boyfriend" type="radio">
		    <label for="patientForcedForSexWithinLastYearBf" class="active">Boyfriend </label>&nbsp;&nbsp;
                    <input id="patientForcedForSexWithinLastYearS" class="with-gap" name="patientForcedForSexWithinLastYear" value="stranger" type="radio">
		    <label for="patientForcedForSexWithinLastYearS" class="active">Stranger</label>
		    <input id="patientForcedForSexWithinLastYearO" class="with-gap" name="patientForcedForSexWithinLastYear" value="other" type="radio">
		    <label for="patientForcedForSexWithinLastYearO" class="active">Other</label>
		    <input id="patientForcedForSexWithinLastYearM" class="with-gap" name="patientForcedForSexWithinLastYear" value="multiple" type="radio">
		    <label for="patientForcedForSexWithinLastYearM" class="active">Multiple</label>&nbsp;&nbsp;&nbsp;&nbsp;
		    <input id="patientForcedForSexWithinLastYearInNoofTimes" name="patientForcedForSexWithinLastYearInNoofTimes" type="text" class="validate nooftimes checkNum" placeholder="Total no.of times" title="Please enter no. of times" style="width:12%;"> Times
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    33. Are you afraid of your partner or anyone listed above? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="isPatientAfraidOfAnyoneYes" class="with-gap isRequired" name="isPatientAfraidOfAnyone" title="Don't leave 33rd question" value="yes" type="radio">
		    <label for="isPatientAfraidOfAnyoneYes" class="active">Yes </label>&nbsp;&nbsp;
                    <input id="isPatientAfraidOfAnyoneNo" class="with-gap" name="isPatientAfraidOfAnyone" value="no" type="radio">
		    <label for="isPatientAfraidOfAnyoneNo" class="active">No </label>&nbsp;&nbsp;
                    <input id="isPatientAfraidOfAnyoneDK" class="with-gap" name="isPatientAfraidOfAnyone" value="dontknow" type="radio">
		    <label for="isPatientAfraidOfAnyoneDK" class="active">Don't Know </label>&nbsp;&nbsp;
                    <input id="isPatientAfraidOfAnyoneR" class="with-gap" name="isPatientAfraidOfAnyone" value="refused" type="radio">
		    <label for="isPatientAfraidOfAnyoneR" class="active">Refused</label>&nbsp;&nbsp;
		    <input id="isPatientAfraidOfAnyoneRNA" class="with-gap" name="isPatientAfraidOfAnyone" value="response not available" type="radio">
		    <label for="isPatientAfraidOfAnyoneRNA" class="active">Response Not Available </label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:10px;">
                <div class="input-field col s6">
                    <textarea id="comment" name="comment" class="materialize-textarea" title="Please enter comments"></textarea>
                    <label for="comment">Comments </label>
                </div>
            </div>
            <div class="col s12" style="margin-top:10px;">
                <input type="hidden" name="chosenCountry" id="chosenCountry" value="<?php echo base64_encode($countryId);?>"/>
                <input type="hidden" name="redirectUrl" id="redirectUrl" value="<?php echo $link;?>"/>
                <a href="<?php echo $link;?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addRiskAssessment();">ADD</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/moment.min.js' ?>"></script>
<script>
    $(document).ready(function(){
       $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 15, // Creates a dropdown of 15 years to control year
            format: 'dd/mm/yyyy',
	    max: new Date('Today'),
	    onSet: function(e){
		$('.picker__close').click();
	    }
        });
    });
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if($.trim(checkValue)!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
    
    //set occupation
    $('#occupation').on('change',function(){
	if(this.value == 'other'){
	    $('.occupationNew').show();
	    $('#occupationNew').addClass('isRequired');
	    $('#occupationNew').focus();
	}else{
	   $('.occupationNew').hide();
	   $('#occupationNew').removeClass('isRequired'); 
	}
    });
    
    //set age at first marriage
    $('#ageAtFirstMarriageInYears').on('change',function() {
	setAgeAtFirstMarriage('txt');
    });
    $('input:radio[name=ageAtFirstMarriage]').change(function () {
	setAgeAtFirstMarriage('rd');
    });
    
    function setAgeAtFirstMarriage(fromSource){
	if(fromSource == 'txt'){
	    if($('#ageAtFirstMarriageInYears').val()!= ''){
		$('#ageAtFirstMarriageDK').prop('checked',false);
		$('#ageAtFirstMarriageR').prop('checked',false);
		$('#ageAtFirstMarriageRNA').prop('checked',false);
	    }
	    $('#ageAtFirstMarriageInYears').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#ageAtFirstMarriageInYears').val('');
	   $('#ageAtFirstMarriageInYears').removeClass('isRequired');
	}
    }
    
    //set no.of sexual partners
    $('#noOfSexualPartnersInNumbers').on('change',function() {
	setNoOfSexualPartners('txt');
    });
    $('input:radio[name=noOfSexualPartners]').change(function () {
	setNoOfSexualPartners('rd');
    });
    function setNoOfSexualPartners(fromSource){
	if(fromSource == 'txt'){
	    if($('#noOfSexualPartnersInNumbers').val()!= ''){
		$('#noOfSexualPartnersDK').prop('checked',false);
		$('#noOfSexualPartnersR').prop('checked',false);
		$('#noOfSexualPartnersRNA').prop('checked',false);
	    }
	    $('#noOfSexualPartnersInNumbers').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#noOfSexualPartnersInNumbers').val('');
	   $('#noOfSexualPartnersInNumbers').removeClass('isRequired');
	}
    }
    
    //set no.of sexual partners in last six months
    $('#noOfSexualPartnersInLastSixMonthsInNumbers').on('change',function() {
	setNoOfSexualPartnersInLastSixMonths('txt');
    });
    $('input:radio[name=noOfSexualPartnersInLastSixMonths]').change(function () {
	setNoOfSexualPartnersInLastSixMonths('rd');
    });
    function setNoOfSexualPartnersInLastSixMonths(fromSource){
	if(fromSource == 'txt'){
	    if($('#noOfSexualPartnersInLastSixMonthsInNumbers').val()!= ''){
		$('#noOfSexualPartnersInLastSixMonthsDK').prop('checked',false);
		$('#noOfSexualPartnersInLastSixMonthsR').prop('checked',false);
		$('#noOfSexualPartnersInLastSixMonthsRNA').prop('checked',false);
	    }
	    $('#noOfSexualPartnersInLastSixMonthsInNumbers').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#noOfSexualPartnersInLastSixMonthsInNumbers').val('');
	   $('#noOfSexualPartnersInLastSixMonthsInNumbers').removeClass('isRequired');
	}
    }
    
    //set main sexual partner age at last birthday
    $('#ageOfMainSexualPartnerAtLastBirthdayInYears').on('change',function() {
	mainSexualPartnerAgeAtLastBirthday('txt');
    });
    $('input:radio[name=ageOfMainSexualPartnerAtLastBirthday]').change(function () {
	mainSexualPartnerAgeAtLastBirthday('rd');
    });
    function mainSexualPartnerAgeAtLastBirthday(fromSource){
	if(fromSource == 'txt'){
	    if($('#ageOfMainSexualPartnerAtLastBirthdayInYears').val()!= ''){
		$('#ageOfMainSexualPartnerAtLastBirthdayDK').prop('checked',false);
		$('#ageOfMainSexualPartnerAtLastBirthdayR').prop('checked',false);
		$('#ageOfMainSexualPartnerAtLastBirthdayRNA').prop('checked',false);
	    }
	    $('#ageOfMainSexualPartnerAtLastBirthdayInYears').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#ageOfMainSexualPartnerAtLastBirthdayInYears').val('');
	   $('#ageOfMainSexualPartnerAtLastBirthdayInYears').removeClass('isRequired');
	}
    }
    
    //set no.of days in last six months
    $('#hasPatientHadDrinkWithAlcoholInLastSixMonthsInDays').on('change',function() {
        noOfDaysHadDrinkInLastSixMonth('txt');
    });
    $('input:radio[name=hasPatientHadDrinkWithAlcoholInLastSixMonths]').change(function () {
	noOfDaysHadDrinkInLastSixMonth('rd');
    });
    function noOfDaysHadDrinkInLastSixMonth(fromSource){
	if(fromSource == 'txt'){
	    if($('#hasPatientHadDrinkWithAlcoholInLastSixMonthsInDays').val()!= ''){
		$('#hasPatientHadDrinkWithAlcoholInLastSixMonthsNot').prop('checked',false);
		$('#hasPatientHadDrinkWithAlcoholInLastSixMonthsDK').prop('checked',false);
		$('#hasPatientHadDrinkWithAlcoholInLastSixMonthsR').prop('checked',false);
		$('#hasPatientHadDrinkWithAlcoholInLastSixMonthsRNA').prop('checked',false);
	    }
	    $('#hasPatientHadDrinkWithAlcoholInLastSixMonthsInDays').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#hasPatientHadDrinkWithAlcoholInLastSixMonthsInDays').val('');
	   $('#hasPatientHadDrinkWithAlcoholInLastSixMonthsInDays').removeClass('isRequired');
	}
    }
    
    //set recreational drugs
    $('input:radio[name=hasPatientHadRecreationalDrugsInLastSixMonths]').change(function () {
	if ($("input[name='hasPatientHadRecreationalDrugsInLastSixMonths']:checked").val() == 'yes') {
            $('.recreationalDrugs').show();
            $('#recreationalDrugs').addClass('isRequired');
            $('#recreationalDrugs').focus();
        }else{
           $('.recreationalDrugs').hide();
           $('#recreationalDrugs').val('');
           $('#recreationalDrugs').removeClass('isRequired');
        }
    });
    
    //set patient abused by
    $('input:radio[name=hasPatientEverBeenHurtBySomeoneWithinLastYear]').change(function () {
        if ($("input[name='hasPatientEverBeenHurtBySomeoneWithinLastYear']:checked").val() == 'yes') {  
	    $('.patientHurtBySomeoneWithinLastYear').show();
	    $('#patientHurtBySomeoneWithinLastYearH').addClass('isRequired');
	}else{
	  $('.patientHurtBySomeoneWithinLastYear').hide();
	  $('#patientHurtBySomeoneWithinLastYearH').removeClass('isRequired');
	  $('#patientHurtBySomeoneWithinLastYearH').prop('checked',false);
	  $('#patientHurtBySomeoneWithinLastYearExH').prop('checked',false);
	  $('#patientHurtBySomeoneWithinLastYearBf').prop('checked',false);
	  $('#patientHurtBySomeoneWithinLastYearS').prop('checked',false);
	  $('#patientHurtBySomeoneWithinLastYearO').prop('checked',false);
	  $('#patientHurtBySomeoneWithinLastYearM').prop('checked',false);
	  $('#patientHurtBySomeoneWithinLastYearInNoofTimes').val('');	    
	}
    });
    
    //set patient hurt by someone during pregnancy
    $('input:radio[name=hasPatientEverBeenHurtBySomeoneDuringPregnancy]').change(function () {
        if ($("input[name='hasPatientEverBeenHurtBySomeoneDuringPregnancy']:checked").val() == 'yes') {  
	    $('.patientHurtBySomeoneDuringPregnancy').show();
	    $('#patientHurtBySomeoneDuringPregnancyH').addClass('isRequired');
	}else{
	  $('.patientHurtBySomeoneDuringPregnancy').hide();
	  $('#patientHurtBySomeoneDuringPregnancyH').removeClass('isRequired');
	  $('#patientHurtBySomeoneDuringPregnancyH').prop('checked',false);
	  $('#patientHurtBySomeoneDuringPregnancyExH').prop('checked',false);
	  $('#patientHurtBySomeoneDuringPregnancyBf').prop('checked',false);
	  $('#patientHurtBySomeoneDuringPregnancyS').prop('checked',false);
	  $('#patientHurtBySomeoneDuringPregnancyO').prop('checked',false);
	  $('#patientHurtBySomeoneDuringPregnancyM').prop('checked',false);    
	}
    });
    
    //set forced for sex within last year
    $('input:radio[name=hasPatientEverBeenForcedForSexWithinLastYear]').change(function () {
        if ($("input[name='hasPatientEverBeenForcedForSexWithinLastYear']:checked").val() == 'yes') {  
	    $('.patientForcedForSexWithinLastYear').show();
	    $('#patientForcedForSexWithinLastYearH').addClass('isRequired');
	}else{
	  $('.patientForcedForSexWithinLastYear').hide();
	  $('#patientForcedForSexWithinLastYearH').removeClass('isRequired');
	  $('#patientForcedForSexWithinLastYearH').prop('checked',false);
	  $('#patientForcedForSexWithinLastYearExH').prop('checked',false);
	  $('#patientForcedForSexWithinLastYearBf').prop('checked',false);
	  $('#patientForcedForSexWithinLastYearS').prop('checked',false);
	  $('#patientForcedForSexWithinLastYearO').prop('checked',false);
	  $('#patientForcedForSexWithinLastYearM').prop('checked',false);
	  $('#patientForcedForSexWithinLastYearInNoofTimes').val('');	    
	}
    });
    
    //set patient recency test status
    $('input:radio[name=hasPatientHadRapidRecencyTest]').change(function () {
	if ($("input[name='hasPatientHadRapidRecencyTest']:checked").val() == 'done') {
	    $('#rtrSection').css('height','auto');
	    $('.rrrSection').show();
	}else{
	   $('#rtrSection').css('height','90px');
	   $('.rrrSection').hide();
	   //$('#rrrHIVDiagnostic option:first').prop('selected', true);
	   //$('#rrrRecency option:first').prop('selected', true);
	}
    });
    
    //recency show/hide based on HIV diagostic
    $('#rrrHIVDiagnostic').on('change',function () {
	if ($('#rrrHIVDiagnostic').val() == 'negative') {
	    $('.rrrRecency').hide();
	}else{
	    $('.rrrRecency').show();
	}
    });
    
    //enable/disable Demographic Characteristics fields based on q.2
    $('input:radio[name=hasPatientEverAttendedSchool]').change(function () {
	if ($("input[name='hasPatientEverAttendedSchool']:checked").val()!= 'yes') {
	    //css section
	    $(".degreeSectionRequired").css("visibility","hidden");
	    $(".degreeSection").css("color","rgba(0,0,0,0.26)");
	    $(".degree").css("pointer-events","none");
	    //validate/content section
	    $("#degree").removeClass("isRequired");
	}else{
	    //css section
	    $(".degreeSectionRequired").css("visibility","visible");
	    $(".degreeSection").css("color","");
	    $(".degree").css("pointer-events","auto");
	    //validate/content section
	    $("#degree").addClass("isRequired");
	}
    });
    //enable/disable Demographic Characteristics fields based on q.3
    $('input:radio[name=everBeenMarried]').change(function () {
	if ($("input[name='everBeenMarried']:checked").val() == 'no' || $("input[name='everBeenMarried']:checked").val() == 'response not available') {
	    //css section
	    $(".everBeenMarriedSectionRequired").css("visibility","hidden");
	    $(".everBeenMarriedSection").css("color","rgba(0,0,0,0.26)");
	    $('#ageAtFirstMarriageInYears').css("pointer-events","none");
	    $("input[name='ageAtFirstMarriage']").attr("disabled","disabled");
	    $("input[name='everBeenWidowed']").attr("disabled","disabled");
	    $(".currentMaritalStatus").css("pointer-events","none");
	    //validate/content section
	    $("#ageAtFirstMarriageInYears").val("");
	    $("#ageAtFirstMarriageDK").prop('checked',false);
	    $("#ageAtFirstMarriageR").prop('checked',false);
	    $("#ageAtFirstMarriageRNA").prop('checked',false);
	    $("#ageAtFirstMarriageInYears,#currentMaritalStatus").removeClass("isRequired");
	    $("input[name='ageAtFirstMarriage']").removeClass("isRequired");
	    $("input[name='everBeenWidowed']").removeClass("isRequired");
	}else{
	    //css section
	    $(".everBeenMarriedSectionRequired").css("visibility","visible");
	    $(".everBeenMarriedSection").css("color","");
	    $('#ageAtFirstMarriageInYears').css("pointer-events","auto");
	    $("input[name='ageAtFirstMarriage']").removeAttr("disabled");
	    $("input[name='everBeenWidowed']").removeAttr("disabled");
	    $(".currentMaritalStatus").css("pointer-events","auto");
	    //validate/content section
	    if($("#ageAtFirstMarriageInYears").val()!= '') { $("#ageAtFirstMarriageInYears").addClass("isRequired"); }
	    $("#currentMaritalStatus").addClass("isRequired");
	    $("input[name='everBeenWidowed']").addClass("isRequired");
	}
    });
    
    $('#ageAtVeryFirstSexRNA').change(function () {
	if($(this).is(":checked")) {
	    $("#ageAtVeryFirstSex").val("Response Not Available");
	    $("#ageAtVeryFirstSex").prop("readonly",true);
	}else{
	   $("#ageAtVeryFirstSex").val("");
	   $("#ageAtVeryFirstSex").prop("readonly",false);
	}
    });
    
    $('#noOfTimesBeenPregnantRNA').change(function () {
	if($(this).is(":checked")) {
	    $("#noOfTimesBeenPregnant").val("Response Not Available");
	    $("#noOfTimesBeenPregnant").prop("readonly",true);
	}else{
	   $("#noOfTimesBeenPregnant").val("");
	   $("#noOfTimesBeenPregnant").prop("readonly",false);
	}
    });
    
    //age range validation
    $('.years').on('change',function() {
	var years = $('#'+this.id).val();
	if(parseInt(years) < 1 || parseInt(years) > 100) { alert('Age range should be 1-100'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    //person range validation
    $('.persons').on('change',function() {
	var persons = $('#'+this.id).val();
	if(parseInt(persons) > 10000) { alert('Person range should be 0-10,000'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    //pregnancy range validation
    $('.times').on('change',function() {
	var times = $('#'+this.id).val();
	if(parseInt(times) > 15) { alert('Pregnancy range should be 0-15'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    //alcohol days range validation
    $('.days').on('change',function() {
	var days = $('#'+this.id).val();
	if(parseInt(days) > 185) { alert('Days can\'t be more than 185'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    //patient hurt/forced to have sex range validation
    $('.nooftimes').on('change',function() {
	var nooftimes = $('#'+this.id).val();
	if(parseInt(nooftimes) > 10000) { alert('No.of times range should be 0-10,000'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    function checkPatientRecord(){
	checkPatientBarcodeId();
    }
    
    function checkPatientBarcodeId(){
	var patientBarcodeId = $('#patientBarcodeId').val();
	var countryId = $('#chosenCountry').val();
        var optCountryId = ($('#country').length) ? $('#country').val():'';
	if($.trim(patientBarcodeId)!= '' && ($.trim(countryId)!= '' || $.trim(optCountryId)!= '')){
            $.post("<?php echo $this->url('check-patient-record'); ?>", {patientBarcodeId: patientBarcodeId,countryId:countryId,optCountryId:optCountryId,type:'clinic'},
            function(data) {
                if ($.trim(data)!= '') { $.blockUI(); document.location.href = data; }
            });
        }
    }
    
    function addRiskAssessment(){
        flag = deforayValidator.init({
            formId: 'addRiskAssessmentForm'
        });
	
        if(flag){
            document.getElementById('addRiskAssessmentForm').submit();
        }
    }
</script>