<?php
if(trim($countryId)!= ''){
    $link = "/clinic/risk-assessment/".base64_encode($countryId);
}else{
   $link = "/clinic/risk-assessment"; 
}
?>
<style>
    .highlightedTxt{
	text-decoration:underline;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Add Risk Assessment</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="/clinic/risk-assessment/<?php echo base64_encode($countryId); ?>" class="breadcrumb">Risk Assessment Form</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Add Risk Assessment</a>
       </div>
    </div>
    <div class="formContainer row dashboard-wrapper content-container" style="margin-bottom:20px;">
        <form id="addRiskAssessmentForm" name="addRiskAssessmentForm" method="post" action="<?php echo $this->url('add-clinic-risk-assessment',array('action'=>'add')); ?>">
        <div class="card">
            <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Sample Particpant Risk Questionnaire</strong></h6>
            <fieldset style="border-color:#2196F3;border-style:solid;">
                <?php
                if(trim($countryId) == ''){
                ?>
                    <div class="row" style="margin-bottom:0;">
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <select id="country" name="country" class="material-select isRequired" title="Please select country" onchange="getCountriesLabAnc();generateSurveillanceID(this);checkPatientRecord();">
                                    <option value=""> -- Select -- </option>
                                    <?php
                                    foreach($countries as $country){
                                    ?>
                                      <option data-code="<?php echo $country['country_code']; ?>" value="<?php echo base64_encode($country['country_id']); ?>"><?php echo ucwords($country['country_name']); ?></option>
                                    <?php } ?>
                                </select>
                                <label for="country">Country *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <select id="ancSite" name="ancSite" class="material-select isRequired" title="Please select ANC Site">
                                    <option value=""> -- Select -- </option>
                                    <?php
				    foreach($ancSites as $anc){
				    ?>
				      <option value="<?php echo base64_encode($anc['anc_site_id']); ?>"><?php echo $anc['anc_site_code'].' - '.ucwords($anc['anc_site_name']); ?></option>
				    <?php } ?>
                                </select>
                                <label for="ancSite">ANC Site *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="patientBarcodeId" name="patientBarcodeId" type="text" class="validate isRequired" title="Please enter patient barcode id" onblur="checkPatientRecord();">
                                <label for="patientBarcodeId" class="">Patient Barcode ID *</label>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="margin-bottom:0;">
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="interviewerName" name="interviewerName" type="text" class="validate isRequired" title="Please enter interviewer name">
                                <label for="interviewerName" class="">Interviewer Name *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="ancPatientId" name="ancPatientId" type="text" class="validate isRequired" title="Please enter anc patient ID">
                                <label for="ancPatientId" class="">ANC Patient ID *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="interviewDate" name="interviewDate" type="text" class="validate isRequired datepicker" title="Please enter interview date">
                                <label for="interviewDate" class="">Interview Date *</label>
                            </div>
                        </div>
                    </div>
		    <!--<div class="row" style="margin-bottom:0;">
			<div class="col s4">
			    <div class="input-field col m12 s12">
			    Has participant received DREAMS services ? (Optional)<br><br>	
			    <input id="hasParticipantReceivedDreamsServicesYes" class="with-gap" name="hasParticipantReceivedDreamsServices" title="Please select paricipant-dreams services received status" value="yes" type="radio">
			    <label for="hasParticipantReceivedDreamsServicesYes" class="active">Yes </label>&nbsp;&nbsp;
			    <input id="hasParticipantReceivedDreamsServicesNo" class="with-gap" name="hasParticipantReceivedDreamsServices" value="no" type="radio">
			    <label for="hasParticipantReceivedDreamsServicesNo" class="active">No </label>&nbsp;&nbsp;
			    </div>
			</div>
		    </div>-->
                <?php } else { ?>
                    <div class="row" style="margin-bottom:0;">
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                            <select id="ancSite" name="ancSite" class="material-select isRequired" title="Please select ANC Site">
                            <option value=""> -- Select -- </option>
                            <?php
                                foreach($ancSites as $anc){
                                ?>
                                <option value="<?php echo base64_encode($anc['anc_site_id']); ?>"><?php echo $anc['anc_site_code'].' - '.ucwords($anc['anc_site_name']); ?></option>
                                <?php } ?>
                            </select>
                                <label for="ancSite">ANC Site *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="patientBarcodeId" name="patientBarcodeId" type="text" class="validate isRequired" title="Please enter patient barcode id" onblur="checkPatientRecord();">
                                <label for="patientBarcodeId" class="">Patient Barcode ID *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="interviewerName" name="interviewerName" type="text" class="validate isRequired" title="Please enter interviewer name">
                                <label for="interviewerName" class="">Interviewer Name *</label>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="margin-bottom:0;">
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="ancPatientId" name="ancPatientId" type="text" class="validate isRequired" title="Please enter anc patient ID" onblur="checkPatientRecord();">
                                <label for="ancPatientId" class="">ANC Patient ID *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="interviewDate" name="interviewDate" type="text" class="validate isRequired datepicker" title="Please enter interview date">
                                <label for="interviewDate" class="">Interview Date *</label>
                            </div>
                        </div>
			<!--<div class="col s4">
			    <div class="input-field col m12 s12">
			    Has Participant received DREAMS services ? (Optional)<br><br>
			    <input id="hasParticipantReceivedDreamsServicesYes" class="with-gap" name="hasParticipantReceivedDreamsServices" title="Please select participant-dreams services received status" value="yes" type="radio">
			    <label for="hasParticipantReceivedDreamsServicesYes" class="active">Yes </label>&nbsp;&nbsp;
			    <input id="hasParticipantReceivedDreamsServicesNo" class="with-gap" name="hasParticipantReceivedDreamsServices" value="no" type="radio">
			    <label for="hasParticipantReceivedDreamsServicesNo" class="active">No </label>
			    </div>
			</div>-->
                    </div>
                <?php } ?>
            </fieldset>
	    <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Recency Test Result</strong></h6>
	    <fieldset id="rtrSection" style="height:90px;border-color:#F44336;border-style:solid;">
		<div class="row" style="margin-bottom:0;">
		    <div class="col s4">
			<div class="input-field col m12 s12">
			Rapid Recency Result *<br><br>
			<input id="hasPatientHadRapidRecencyTestYes" class="with-gap isRequired" name="hasPatientHadRapidRecencyTest" title="Please select patient rapid recency test status" value="done" type="radio">
			<label for="hasPatientHadRapidRecencyTestYes" class="active">Done </label>&nbsp;&nbsp;
			<input id="hasPatientHadRapidRecencyTestNo" class="with-gap" name="hasPatientHadRapidRecencyTest" value="not done" type="radio">
			<label for="hasPatientHadRapidRecencyTestNo" class="active">Not Done </label>&nbsp;&nbsp;
			</div>
		    </div>
		    <div class="col s4 rrrSection" style="display:none;">
			<div class="input-field col m12 s12">
			<select id="rrrHIVDiagnostic" name="rrrHIVDiagnostic" class="material-select" title="Please select HIV diagnostic line">
                            <option value=""> -- Select -- </option>
			    <option value="positive">P (Positive)</option>
			    <option value="negative">N (Negative)</option>
			    <option value="invalid">Invalid</option>
                        </select>
                        <label for="rrrHIVDiagnostic">Positive Verification (Diagnostic) Line </label>
			</div>
		    </div>
		    <div class="col s4 rrrRecency rrrSection" style="display:none;">
			<div class="input-field col m12 s12">
			<select id="rrrRecency" name="rrrRecency" class="material-select" title="Please select recency line">
                            <option value=""> -- Select -- </option>
			    <option value="recent">R (Recent)</option>
			    <option value="long term">LT (Long Term)</option>
			    <option value="invalid">Invalid</option>
                        </select>
                        <label for="rrrRecency">Long Term (Recency) Line </label>
			</div>
		    </div>
		</div>
	    </fieldset>
            <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Demographic Characteristics</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q1. What kind of work/occupation do you do most of the time? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="occupation" name="occupation" class="material-select isRequired" title="Don't leave Q1">
                        <option value=""> -- Select -- </option>
                        <?php
			foreach($occupationTypes as $occupation){
			?>
                           <option value="<?php echo base64_encode($occupation['occupation_id']); ?>"><?php echo ucwords($occupation['occupation']).' - '.$occupation['occupation_code']; ?></option>
			<?php } ?>
                        <option value="1111">Other - 1111</option>
                    </select>
                </div>
		<div class="col s4 occupationNew" style="display:none;">
		    <input id="occupationNew" name="occupationNew" type="text" class="validate" placeholder="Occupation" title="Please enter occupation" onblur="checkNameValidation('occupation_type', 'occupation', this, null,'The occupation that you entered already listed. Please enter different occupation');">
		</div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q2. Have you ever attended school? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="hasPatientEverAttendedSchoolYes" class="with-gap isRequired" name="hasPatientEverAttendedSchool" title="Don't leave Q2" value="1" type="radio">
		    <label for="hasPatientEverAttendedSchoolYes" class="active">Yes - 1 </label>&nbsp;&nbsp;
                    <input id="hasPatientEverAttendedSchoolNo" class="with-gap" name="hasPatientEverAttendedSchool" value="2" type="radio">
		    <label for="hasPatientEverAttendedSchoolNo" class="active">No - 2 </label>&nbsp;&nbsp;
		    <input id="hasPatientEverAttendedSchoolDK" class="with-gap" name="hasPatientEverAttendedSchool" value="88" type="radio">
		    <label for="hasPatientEverAttendedSchoolDK" class="active">Don't Know - 88 </label>&nbsp;&nbsp;
                    <input id="hasPatientEverAttendedSchoolR" class="with-gap" name="hasPatientEverAttendedSchool" value="99" type="radio">
		    <label for="hasPatientEverAttendedSchoolR" class="active">Refused - 99 </label>&nbsp;&nbsp;
		    <input id="hasPatientEverAttendedSchoolRNA" class="with-gap" name="hasPatientEverAttendedSchool" value="2222" type="radio">
		    <label for="hasPatientEverAttendedSchoolRNA" class="active">Response Not Available - 2222 </label>
                </div>
            </div>
            <div class="row degreeSection" style="margin-bottom:0;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q2A. What was the highest level of education that you completed or are attending now?<span class="degreeSectionRequired">*</span>
                </div>
            </div>
            <div class="row degreeSection" style="margin-bottom:10px;">
                <div class="col s4 degree" style="padding-left:3%;">
                    <select id="degree" name="degree" class="material-select isRequired" title="Don't leave Q2A">
                        <option value=""> -- Select -- </option>
                        <option value="1">Primary/Vocational - 1</option>
                        <option value="2">Secondary - 2</option>
                        <option value="3">University/College - 3</option>
			<option value="88">Don't know - 88</option>
			<option value="99">Refused - 99</option>
			<option value="2222">Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q3. Have you <span class="highlightedTxt">ever</span> been married or lived with a partner in a union as if married? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="everBeenMarriedYes" class="with-gap isRequired" name="everBeenMarried" title="Don't leave Q3" value="1" type="radio">
		    <label for="everBeenMarriedYes" class="active">Yes - 1 </label>&nbsp;&nbsp;
                    <input id="everBeenMarriedNo" class="with-gap" name="everBeenMarried" value="2" type="radio">
		    <label for="everBeenMarriedNo" class="active">No - 2 </label>&nbsp;&nbsp;
		    <input id="everBeenMarriedDK" class="with-gap isRequired" name="everBeenMarried" value="88" type="radio">
		    <label for="everBeenMarriedDK" class="active">Don't Know - 88 </label>&nbsp;&nbsp;
                    <input id="everBeenMarriedR" class="with-gap" name="everBeenMarried" value="99" type="radio">
		    <label for="everBeenMarriedR" class="active">Refused - 99 </label>&nbsp;&nbsp;
		    <input id="everBeenMarriedRNA" class="with-gap" name="everBeenMarried" value="2222" type="radio">
		    <label for="everBeenMarriedRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q3A. How old were you when you <span class="highlightedTxt">first</span> got married or lived with a partner in a union? <span class="everBeenMarriedSectionRequired">*</span>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:10px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="ageAtFirstMarriageInYears" name="ageAtFirstMarriageInYears" type="text" class="validate years checkNum isRequired" title="Don't leave Q3A" style="width:10%;"> Years&nbsp;
                    <input id="ageAtFirstMarriageDK" class="with-gap" name="ageAtFirstMarriage" value="88" title="Don't leave Q3A" type="radio">
		    <label for="ageAtFirstMarriageDK" class="active">Don't Know - 88 </label>&nbsp;&nbsp;
                    <input id="ageAtFirstMarriageR" class="with-gap" name="ageAtFirstMarriage" value="99" type="radio">
		    <label for="ageAtFirstMarriageR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="ageAtFirstMarriageRNA" class="with-gap" name="ageAtFirstMarriage" value="2222" type="radio">
		    <label for="ageAtFirstMarriageRNA" class="active">Response Not Available - 2222 </label>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:0;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q3B. Have you <span class="highlightedTxt">ever</span> been widowed? That is, did a spouse ever pass away while you were still married or living with them? <span class="everBeenMarriedSectionRequired">*</span>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:10px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="everBeenWidowedYes" class="with-gap isRequired" name="everBeenWidowed" title="Don't leave Q3B" value="1" type="radio">
		    <label for="everBeenWidowedYes" class="active">Yes - 1 </label>&nbsp;&nbsp;
                    <input id="everBeenWidowedNo" class="with-gap" name="everBeenWidowed" value="2" type="radio">
		    <label for="everBeenWidowedNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="everBeenWidowedDK" class="with-gap" name="everBeenWidowed" value="88" type="radio">
		    <label for="everBeenWidowedDK" class="active">Don't Know - 88 </label>&nbsp;&nbsp;
                    <input id="everBeenWidowedR" class="with-gap" name="everBeenWidowed" value="99" type="radio">
		    <label for="everBeenWidowedR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="everBeenWidowedRNA" class="with-gap" name="everBeenWidowed" value="2222" type="radio">
		    <label for="everBeenWidowedRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q3C. What is your marital status <span class="highlightedTxt">now</span>? <span class="everBeenMarriedSectionRequired">*</span>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:10px;">
                <div class="col s4 currentMaritalStatus" style="padding-left:3%;">
                    <select id="currentMaritalStatus" name="currentMaritalStatus" class="material-select isRequired" title="Don't leave Q3C">
                        <option value=""> -- Select -- </option>
                        <option value="1">Married/Cohabiting - 1</option>
                        <option value="2">Never Married/Cohabiting - 2</option>
                        <option value="3">Widowed - 3</option>
                        <option value="4">Separated - 4</option>
                        <option value="5">Divorced - 5</option>
                        <option value="88">Don't Know - 88</option>
                        <option value="99">Refused - 99</option>
			<option value="2222">Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <h6 style="padding:0px 0px 10px 6px;font-size:16px;"><strong>HIV Testing History</strong></h6>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q4. Have you ever been tested for HIV? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="hasPatientEverBeenTestedforHIVYes" class="with-gap isRequired" name="hasPatientEverBeenTestedforHIV" value="1" type="radio" title="Don't leave Q4">
		    <label for="hasPatientEverBeenTestedforHIVYes" class="active">Yes - 1 </label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenTestedforHIVNo" class="with-gap" name="hasPatientEverBeenTestedforHIV" value="2" type="radio">
		    <label for="hasPatientEverBeenTestedforHIVNo" class="active">No - 2 </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenTestedforHIVDK" class="with-gap" name="hasPatientEverBeenTestedforHIV" value="88" type="radio">
		    <label for="hasPatientEverBeenTestedforHIVDK" class="active">Don't Know - 88 </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenTestedforHIVR" class="with-gap" name="hasPatientEverBeenTestedforHIV" value="99" type="radio">
		    <label for="hasPatientEverBeenTestedforHIVR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenTestedforHIVRNA" class="with-gap" name="hasPatientEverBeenTestedforHIV" value="2222" type="radio">
		    <label for="hasPatientEverBeenTestedforHIVRNA" class="active">Response Not Available - 2222 </label>
                </div>
            </div>
            <div class="row everBeenTestedforHIVSection" style="margin-bottom:0;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q4A. When was the <span class="highlightedTxt">most recent</span> time you were tested for HIV? <span class="everBeenTestedforHIVSectionRequired">*</span>
                </div>
            </div>
            <div class="row everBeenTestedforHIVSection" style="margin-bottom:10px;">
                <div class="col s4 timeOfLastHIVTest" style="padding-left:3%;">
                    <select id="timeOfLastHIVTest" name="timeOfLastHIVTest" class="material-select isRequired" title="Don't leave Q4A">
                        <option value=""> -- Select -- </option>
                        <option value="1">< 3 Months Ago - 1</option>
                        <option value="2">3-6 Months Ago - 2</option>
                        <option value="3">7-12 Months Ago - 3</option>
                        <option value="4"> > 12 months - 4</option>
                        <option value="88">Don't Know - 88</option>
                        <option value="99">Refused - 99</option>
			<option value="2222">Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <div class="row everBeenTestedforHIVSection" style="margin-bottom:0;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q4B. What was the result of that HIV test? <span class="everBeenTestedforHIVSectionRequired">*</span>
                </div>
            </div>
            <div class="row everBeenTestedforHIVSection" style="margin-bottom:10px;">
                <div class="col s4 lastHIVTestStatus" style="padding-left:3%;">
                    <select id="lastHIVTestStatus" name="lastHIVTestStatus" class="material-select isRequired" title="Don't leave Q4B">
                        <option value=""> -- Select -- </option>
                        <option value="1">I Did Not Receive Result - 1</option>
                        <option value="2">HIV Positive - 2</option>
                        <option value="3">HIV Negative - 3</option>
                        <option value="4">Indeterminate - 4</option>
                        <option value="88">Don't Know - 88</option>
                        <option value="99">Refused - 99</option>
			<option value="2222">Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <h6 style="padding:0px 0px 10px 6px;font-size:16px;"><strong>Sexual Activity and History of Sexually Transmitted Infections</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q5. How old were you when you had sexual intercourse for the very <span class="highlightedTxt">first</span> time? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="ageAtVeryFirstSexInNumbers" name="ageAtVeryFirstSexInNumbers" type="text" class="validate isRequired years checkNum" title="Don't leave Q5" style="width:10%;"> Years &nbsp;&nbsp;
		    <input id="ageAtVeryFirstSexDK" class="with-gap" name="ageAtVeryFirstSex" value="88" type="radio">
		    <label for="ageAtVeryFirstSexDK" class="active">Don't Know - 88 </label>&nbsp;&nbsp;
		    <input id="ageAtVeryFirstSexR" class="with-gap" name="ageAtVeryFirstSex" value="99" type="radio">
		    <label for="ageAtVeryFirstSexR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="ageAtVeryFirstSexRNA" class="with-gap" name="ageAtVeryFirstSex" value="2222" type="radio">
		    <label for="ageAtVeryFirstSexRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q6. The <span class="highlightedTxt">first</span> time you had sex, was it because you wanted to or because you were forced to? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="reasonForVeryFirstSexWT" class="with-gap isRequired" name="reasonForVeryFirstSex" title="Don't leave Q6" value="1" type="radio">
		    <label for="reasonForVeryFirstSexWT" class="active">Wanted To - 1</label>&nbsp;&nbsp;
                    <input id="reasonForVeryFirstSexFT" class="with-gap" name="reasonForVeryFirstSex" value="2" type="radio">
		    <label for="reasonForVeryFirstSexFT" class="active">Forced To - 2</label>&nbsp;&nbsp;
                    <input id="reasonForVeryFirstSexDK" class="with-gap" name="reasonForVeryFirstSex" value="88" type="radio">
		    <label for="reasonForVeryFirstSexDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="reasonForVeryFirstSexR" class="with-gap" name="reasonForVeryFirstSex" value="99" type="radio">
		    <label for="reasonForVeryFirstSexR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="reasonForVeryFirstSexRNA" class="with-gap" name="reasonForVeryFirstSex" value="2222" type="radio">
		    <label for="reasonForVeryFirstSexRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    Q7. How many different people have you had sexual intercourse with <span class="highlightedTxt">in your entire life</span>? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="noOfSexualPartnersInNumbers" name="noOfSexualPartnersInNumbers" type="text" class="validate persons checkNum isRequired" title="Don't leave Q7" style="width:10%;"> Persons&nbsp;
                    <input id="noOfSexualPartnersDK" class="with-gap" name="noOfSexualPartners" value="88" type="radio">
		    <label for="noOfSexualPartnersDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="noOfSexualPartnersR" class="with-gap" name="noOfSexualPartners" value="99" type="radio">
		    <label for="noOfSexualPartnersR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="noOfSexualPartnersRNA" class="with-gap" name="noOfSexualPartners" value="2222" type="radio">
		    <label for="noOfSexualPartnersRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q8. How many different people have you had sex with in the last 6 months? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="noOfSexualPartnersInLastSixMonthsInNumbers" name="noOfSexualPartnersInLastSixMonthsInNumbers" type="text" class="validate persons checkNum isRequired" title="Don't leave Q8" style="width:10%;"> Persons&nbsp;
                    <input id="noOfSexualPartnersInLastSixMonthsDK" class="with-gap" name="noOfSexualPartnersInLastSixMonths" value="88" type="radio">
		    <label for="noOfSexualPartnersInLastSixMonthsDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="noOfSexualPartnersInLastSixMonthsR" class="with-gap" name="noOfSexualPartnersInLastSixMonths" value="99" type="radio">
		    <label for="noOfSexualPartnersInLastSixMonthsR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="noOfSexualPartnersInLastSixMonthsRNA" class="with-gap" name="noOfSexualPartnersInLastSixMonths" value="2222" type="radio">
		    <label for="noOfSexualPartnersInLastSixMonthsRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
		    Q9. What is the HIV status of your <span class="highlightedTxt">spouse/main</span> sexual partner's (person with whom you have sexual intercourse most frequently)? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="partnerHIVTestStatus" name="partnerHIVTestStatus" class="material-select isRequired" title="Don't leave Q9">
                        <option value=""> -- Select -- </option>
                        <option value="1">HIV Positive - 1</option>
                        <option value="2">HIV Negative - 2</option>
			 <option value="3">No Main Sexual Partner - 3</option>
                        <option value="88">Don't Know - 88</option>
                        <option value="99">Refused - 99</option>
                        <option value="2222">Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <div class="row mainSexualPartnerSection" style="margin-bottom:0;">
                <div class="col s12">
                    Q10. How old was your <span class="highlightedTxt">spouse/main</span> sexual partner on his last birthday? <span class="mainSexualPartnerSectionRequired">*</span>
                </div>
            </div>
            <div class="row mainSexualPartnerSection" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="ageOfMainSexualPartnerAtLastBirthdayInYears" name="ageOfMainSexualPartnerAtLastBirthdayInYears" type="text" class="validate isRequired years checkNum" title="Don't leave Q10" style="width:13%;"> Years&nbsp;
                    <input id="ageOfMainSexualPartnerAtLastBirthdayDK" class="with-gap" name="ageOfMainSexualPartnerAtLastBirthday" value="88" type="radio">
		    <label for="ageOfMainSexualPartnerAtLastBirthdayDK" class="active">Don't Know - 88 </label>&nbsp;&nbsp;
                    <input id="ageOfMainSexualPartnerAtLastBirthdayR" class="with-gap" name="ageOfMainSexualPartnerAtLastBirthday" value="99" type="radio">
		    <label for="ageOfMainSexualPartnerAtLastBirthdayR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="ageOfMainSexualPartnerAtLastBirthdayRNA" class="with-gap" name="ageOfMainSexualPartnerAtLastBirthday" value="2222" type="radio">
		    <label for="ageOfMainSexualPartnerAtLastBirthdayRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row mainSexualPartnerSection mainSexualPartnerAgeSection" style="margin-bottom:0;">
                <div class="col s12">
                    Q11. Is the age of your <span class="highlightedTxt">spouse/main</span> sexual partner older, younger, or the same age as you? <span class="mainSexualPartnerSectionRequired mainSexualPartnerAgeSectionRequired">*</span>
                </div>
            </div>
            <div class="row mainSexualPartnerSection mainSexualPartnerAgeSection" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="ageDiffOfMainSexualPartner" name="ageDiffOfMainSexualPartner" class="material-select isRequired" title="Don't leave Q11">
                        <option value=""> -- Select -- </option>
                        <option value="1"> < 5 Years Older - 1</option>
                        <option value="2"> 5-10 Years Older - 2</option>
                        <option value="3"> >10 Years Older - 3</option>
                        <option value="4">Same Age - 4</option>
                        <option value="5"> < 5 Years Younger - 5</option>
                        <option value="6">5-10 Years Younger - 6</option>
                        <option value="7"> >10 Years Younger - 7</option>
                        <option value="88">Don't Know - 88</option>
                        <option value="99">Refused - 99</option>
			<option value="2222">Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <div class="row mainSexualPartnerSection" style="margin-bottom:0;">
                <div class="col s12">
                    Q12. Is your <span class="highlightedTxt">spouse/main</span> sexual partner circumcised? <span class="mainSexualPartnerSectionRequired">*</span>
                </div>
            </div>
            <div class="row mainSexualPartnerSection" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="isPartnerCircumcisedYes" class="with-gap isRequired" name="isPartnerCircumcised" title="Don't leave Q12" value="1" type="radio">
		    <label for="isPartnerCircumcisedYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="isPartnerCircumcisedNo" class="with-gap" name="isPartnerCircumcised" value="2" type="radio">
		    <label for="isPartnerCircumcisedNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="isPartnerCircumcisedDK" class="with-gap" name="isPartnerCircumcised" value="88" type="radio">
		    <label for="isPartnerCircumcisedDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="isPartnerCircumcisedR" class="with-gap" name="isPartnerCircumcised" value="99" type="radio">
		    <label for="isPartnerCircumcisedR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="isPartnerCircumcisedRNA" class="with-gap" name="isPartnerCircumcised" value="2222" type="radio">
		    <label for="isPartnerCircumcisedRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row mainSexualPartnerSection circumcisionSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q12A. What type of circumcision? <span class="mainSexualPartnerSectionRequired circumcisionSectionRequired">*</span>
                </div>
            </div>
            <div class="row mainSexualPartnerSection circumcisionSection" style="margin-bottom:10px;">
                <div class="col s4" style="padding-left:3%;">
                    <select id="circumcision" name="circumcision" class="material-select isRequired" title="Don't leave Q12A">
                        <option value=""> -- Select -- </option>
                        <option value="1"> Medical Circumcision - 1</option>
                        <option value="2"> Traditional Circumcision - 2</option>
                        <option value="88">Don't Know - 88</option>
                        <option value="99">Refused - 99</option>
			<option value="2222">Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
	    <div class="row mainSexualPartnerSection" style="margin-bottom:0;">
                <div class="col s12">
                    Q13. Have you ever received money/gifts in exchange for sex? <span class="mainSexualPartnerSectionRequired">*</span>
                </div>
            </div>
            <div class="row mainSexualPartnerSection" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="hasPatinetEverReceivedGiftForSexYes" class="with-gap isRequired" name="hasPatinetEverReceivedGiftForSex" title="Don't leave Q13" value="1" type="radio">
		    <label for="hasPatinetEverReceivedGiftForSexYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatinetEverReceivedGiftForSexNo" class="with-gap" name="hasPatinetEverReceivedGiftForSex" value="2" type="radio">
		    <label for="hasPatinetEverReceivedGiftForSexNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatinetEverReceivedGiftForSexDK" class="with-gap" name="hasPatinetEverReceivedGiftForSex" value="88" type="radio">
		    <label for="hasPatinetEverReceivedGiftForSexDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatinetEverReceivedGiftForSexR" class="with-gap" name="hasPatinetEverReceivedGiftForSex" value="99" type="radio">
		    <label for="hasPatinetEverReceivedGiftForSexR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatinetEverReceivedGiftForSexRNA" class="with-gap" name="hasPatinetEverReceivedGiftForSex" value="2222" type="radio">
		    <label for="hasPatinetEverReceivedGiftForSexRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row mainSexualPartnerSection patinetReceivedGiftForSexSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q13A. When did you last receive money/gifts in exchange for sex? <span class="mainSexualPartnerSectionRequired patinetReceivedGiftForSexSectionRequired">*</span>
                </div>
            </div>
            <div class="row mainSexualPartnerSection patinetReceivedGiftForSexSection" style="margin-bottom:10px;">
                <div class="col s4" style="padding-left:3%;">
                    <select id="lastTimeOfReceivingGiftForSex" name="lastTimeOfReceivingGiftForSex" class="material-select isRequired" title="Don't leave Q13A">
                        <option value=""> -- Select -- </option>
                        <option value="1"> < 6 Months Ago - 1</option>
                        <option value="2"> 6-12 Months Ago - 2</option>
                        <option value="3"> > 12 Months Ago - 3</option>
                        <option value="88">Don't Know - 88</option>
                        <option value="99">Refused - 99</option>
			<option value="2222">Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <div class="row mainSexualPartnerSection" style="margin-bottom:0;">
                <div class="col s12">
                    Q14. How many times have you been pregnant? <span class="mainSexualPartnerSectionRequired">*</span> (including this pregnancy)
                </div>
            </div>
            <div class="row mainSexualPartnerSection" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="noOfTimesBeenPregnantInNumbers" name="noOfTimesBeenPregnantInNumbers" type="text" class="validate times checkNum isRequired" title="Don't leave Q14" style="width:20%;"> Times &nbsp;&nbsp;
		    <input id="noOfTimesBeenPregnantDK" class="with-gap" name="noOfTimesBeenPregnant" value="88" type="radio">
		    <label for="noOfTimesBeenPregnantDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="noOfTimesBeenPregnantR" class="with-gap" name="noOfTimesBeenPregnant" value="99" type="radio">
		    <label for="noOfTimesBeenPregnantR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="noOfTimesBeenPregnantRNA" class="with-gap" name="noOfTimesBeenPregnant" value="2222" type="radio">
		    <label for="noOfTimesBeenPregnantRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row mainSexualPartnerSection" style="margin-bottom:0;">
                <div class="col s12">
                    Q15. Before becoming pregnant this time, in the past year how frequently did you use a condom when having sexual intercourse? <span class="mainSexualPartnerSectionRequired">*</span>
                </div>
            </div>
            <div class="row mainSexualPartnerSection" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="noOfTimesCondomUsedBeforePregnancyA" class="with-gap isRequired" name="noOfTimesCondomUsedBeforePregnancy" title="Don't leave Q15" value="1" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyA" class="active">Always - 1</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedBeforePregnancyS" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="2" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyS" class="active">Sometimes - 2</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedBeforePregnancyN" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="3" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyN" class="active">Never - 3</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedBeforePregnancyDK" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="88" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedBeforePregnancyR" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="99" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="noOfTimesCondomUsedBeforePregnancyRNA" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="2222" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row mainSexualPartnerSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    Q16. Since becoming pregnant this time, how frequently have you used a condom when having sexual intercourse? <span class="mainSexualPartnerSectionRequired">*</span>
                </div>
            </div>
            <div class="row mainSexualPartnerSection" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="noOfTimesCondomUsedAfterPregnancyA" class="with-gap isRequired" name="noOfTimesCondomUsedAfterPregnancy" title="Don't leave Q16" value="1" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyA" class="active">Always - 1</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedAfterPregnancyS" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="2" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyS" class="active">Sometimes - 2</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedAfterPregnancyN" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="3" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyN" class="active">Never - 3</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedAfterPregnancyDK" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="88" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedAfterPregnancyR" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="99" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="noOfTimesCondomUsedAfterPregnancyRNA" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="2222" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    Q17. In the past year, did you have symptoms such as genital discharge, sores in your genital area, pain during urination, or pain in your lower abdomen? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="hasPatientHadPainInLowerAbdomenYes" class="with-gap isRequired" name="hasPatientHadPainInLowerAbdomen" title="Don't leave Q17" value="1" type="radio">
		    <label for="hasPatientHadPainInLowerAbdomenYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientHadPainInLowerAbdomenNo" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="2" type="radio">
		    <label for="hasPatientHadPainInLowerAbdomenNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientHadPainInLowerAbdomenDK" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="88" type="radio">
		    <label for="hasPatientHadPainInLowerAbdomenDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientHadPainInLowerAbdomenR" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="99" type="radio">
		    <label for="hasPatientHadPainInLowerAbdomenR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientHadPainInLowerAbdomenRNA" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="2222" type="radio">
		    <label for="hasPatientHadPainInLowerAbdomenRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row symptomsSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q17A. Were you treated for these symptoms? <span class="symptomsSectionRequired">*</span>
                </div>
            </div>
            <div class="row symptomsSection" style="margin-bottom:0;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="hasPatientBeenTreatedForLowerAbdomenPainYes" class="with-gap isRequired" name="hasPatientBeenTreatedForLowerAbdomenPain" title="Don't leave Q17A" value="1" type="radio">
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientBeenTreatedForLowerAbdomenPainNo" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="2" type="radio">
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientBeenTreatedForLowerAbdomenPainDK" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="88" type="radio">
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientBeenTreatedForLowerAbdomenPainR" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="99" type="radio">
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientBeenTreatedForLowerAbdomenPainRNA" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="2222" type="radio">
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    Q18. Have you <span class="highlightedTxt">ever</span> been diagnosed or treated for syphilis? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="hasPatientEverBeenTreatedForSyphilisYes" class="with-gap isRequired" name="hasPatientEverBeenTreatedForSyphilis" title="Don't leave Q18" value="1" type="radio">
		    <label for="hasPatientEverBeenTreatedForSyphilisYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenTreatedForSyphilisNo" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="2" type="radio">
		    <label for="hasPatientEverBeenTreatedForSyphilisNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenTreatedForSyphilisDK" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="88" type="radio">
		    <label for="hasPatientEverBeenTreatedForSyphilisDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenTreatedForSyphilisR" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="99" type="radio">
		    <label for="hasPatientEverBeenTreatedForSyphilisR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenTreatedForSyphilisRNA" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="2222" type="radio">
		    <label for="hasPatientEverBeenTreatedForSyphilisRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
		    Q19. Have you ever received a vaccine (HPV vaccine) to prevent cervical cancer, which is caused by a common virus that can be passed through sexual contact?
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="hasPatientEverReceivedVaccineToPreventCervicalCancerYes" class="with-gap isRequired" name="hasPatientEverReceivedVaccineToPreventCervicalCancer" title="Don't leave Q19" value="1" type="radio">
		    <label for="hasPatientEverReceivedVaccineToPreventCervicalCancerYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverReceivedVaccineToPreventCervicalCancerNo" class="with-gap" name="hasPatientEverReceivedVaccineToPreventCervicalCancer" value="2" type="radio">
		    <label for="hasPatientEverReceivedVaccineToPreventCervicalCancerNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverReceivedVaccineToPreventCervicalCancerDK" class="with-gap" name="hasPatientEverReceivedVaccineToPreventCervicalCancer" value="88" type="radio">
		    <label for="hasPatientEverReceivedVaccineToPreventCervicalCancerDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverReceivedVaccineToPreventCervicalCancerR" class="with-gap" name="hasPatientEverReceivedVaccineToPreventCervicalCancer" value="99" type="radio">
		    <label for="hasPatientEverReceivedVaccineToPreventCervicalCancerR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverReceivedVaccineToPreventCervicalCancerRNA" class="with-gap" name="hasPatientEverReceivedVaccineToPreventCervicalCancer" value="2222" type="radio">
		    <label for="hasPatientEverReceivedVaccineToPreventCervicalCancerRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Alcohol and drug use</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q20. During the past 6 months, on how many days did you have at least one drink containing alcohol? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="patientHadDrinkWithAlcoholInLastSixMonthsInDays" name="patientHadDrinkWithAlcoholInLastSixMonthsInDays" type="text" class="validate days checkNum isRequired" title="Don't leave Q20" style="width:10%;"> Days&nbsp;
                    <input id="patientHadDrinkWithAlcoholInLastSixMonthsDK" class="with-gap" name="patientHadDrinkWithAlcoholInLastSixMonths" value="88" type="radio">
		    <label for="patientHadDrinkWithAlcoholInLastSixMonthsDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientHadDrinkWithAlcoholInLastSixMonthsR" class="with-gap" name="patientHadDrinkWithAlcoholInLastSixMonths" value="99" type="radio">
		    <label for="patientHadDrinkWithAlcoholInLastSixMonthsR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientHadDrinkWithAlcoholInLastSixMonthsRNA" class="with-gap" name="patientHadDrinkWithAlcoholInLastSixMonths" value="2222" type="radio">
		    <label for="patientHadDrinkWithAlcoholInLastSixMonthsRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q21. How often do you have 4 or more drinks with alcohol on one occasion? * (e.g. within 2 hours)
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="hasPatientOftenHad4rmoreDrinksWithAlcoholOnOneOccasion" name="hasPatientOftenHad4rmoreDrinksWithAlcoholOnOneOccasion" class="material-select isRequired" title="Don't leave Q21">
                        <option value=""> -- Select -- </option>
                        <option value="1">Never - 1</option>
                        <option value="2">Monthly - 2</option>
                        <option value="3">Weekly - 3</option>
                        <option value="4">Daily or On Most Days of The Week - 4</option>
                        <option value="88">Don't Know - 88</option>
                        <option value="99">Refused - 99</option>
			<option value="2222">Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q22. Have you <span class="highlightedTxt">ever</span> tried recreational drugs? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="hasPatientEverTriedRecreationalDrugsYes" class="with-gap isRequired" name="hasPatientEverTriedRecreationalDrugs" title="Don't leave Q22" value="1" type="radio">
		    <label for="hasPatientEverTriedRecreationalDrugsYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverTriedRecreationalDrugsNo" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="2" type="radio">
		    <label for="hasPatientEverTriedRecreationalDrugsNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverTriedRecreationalDrugsDK" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="88" type="radio">
		    <label for="hasPatientEverTriedRecreationalDrugsDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverTriedRecreationalDrugsR" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="99" type="radio">
		    <label for="hasPatientEverTriedRecreationalDrugsR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverTriedRecreationalDrugsRNA" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="2222" type="radio">
		    <label for="hasPatientEverTriedRecreationalDrugsRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row recreationalDrugSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q22A. In the <span class="highlightedTxt">last 6 months</span>, have you taken any recreational drugs? <span class="recreationalDrugSectionRequired">*</span>
                </div>
            </div>
            <div class="row recreationalDrugSection" style="margin-bottom:0;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="hasPatientHadRecreationalDrugsInLastSixMonthsYes" class="with-gap isRequired" name="hasPatientHadRecreationalDrugsInLastSixMonths" title="Don't leave Q22A" value="1" type="radio">
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsNo" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="2" type="radio">
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsDK" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="88" type="radio">
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsR" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="99" type="radio">
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsRNA" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="2222" type="radio">
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row recreationalDrugSection recreationalDrugs" style="margin-bottom:0;margin-top:16px;display:none;">
	        &nbsp;&nbsp;&nbsp;&nbsp;Specify Drug(s) <span class="recreationalDrugSectionRequired recreationalDrugsRequired">*</span> <input id="recreationalDrugs" name="recreationalDrugs" type="text" class="validate" title="Please enter recreational drugs" style="width:40%;">
	    </div>
	    <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Abuse</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q23. Have you ever been emotionally or physically abused by your partner or your loved one? *
                </div>
            </div>
            <div class="row" style="margin-bottom:20px;">
                <div class="col s12" style="margin-bottom:0px;">
                    <input id="hasPatientEverBeenAbusedBySomeoneYes" class="with-gap isRequired" name="hasPatientEverBeenAbusedBySomeone" title="Don't leave Q23" value="1" type="radio">
		    <label for="hasPatientEverBeenAbusedBySomeoneYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenAbusedBySomeoneNo" class="with-gap" name="hasPatientEverBeenAbusedBySomeone" value="2" type="radio">
		    <label for="hasPatientEverBeenAbusedBySomeoneNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenAbusedBySomeoneDK" class="with-gap" name="hasPatientEverBeenAbusedBySomeone" value="88" type="radio">
		    <label for="hasPatientEverBeenAbusedBySomeoneDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenAbusedBySomeoneR" class="with-gap" name="hasPatientEverBeenAbusedBySomeone" value="99" type="radio">
		    <label for="hasPatientEverBeenAbusedBySomeoneR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenAbusedBySomeoneRNA" class="with-gap" name="hasPatientEverBeenAbusedBySomeone" value="2222" type="radio">
		    <label for="hasPatientEverBeenAbusedBySomeoneRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row patientAbusedBySomeone" style="margin-bottom:5px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q23A. Who abused you? *
                </div>
            </div>
	    <div class="row patientAbusedBySomeone" style="margin-bottom:10px;display:none;">
                <div class="col s12" style="margin-bottom:0px;padding-left:4%;">
                    <input id="patientAbusedByH" class="with-gap" name="patientAbusedBy[]" title="Don't leave Q23A" value="1" type="checkbox" onchange="setAbusedBy(this);">
		    <label for="patientAbusedByH" class="active">Husband - 1</label>&nbsp;&nbsp;
                    <input id="patientAbusedByExH" class="with-gap" name="patientAbusedBy[]" value="2" type="checkbox" onchange="setAbusedBy(this);">
		    <label for="patientAbusedByExH" class="active">Ex-Husband - 2</label>&nbsp;&nbsp;
                    <input id="patientAbusedByBf" class="with-gap" name="patientAbusedBy[]" value="3" type="checkbox" onchange="setAbusedBy(this);">
		    <label for="patientAbusedByBf" class="active">Boyfriend - 3</label>&nbsp;&nbsp;
                    <input id="patientAbusedByS" class="with-gap" name="patientAbusedBy[]" value="4" type="checkbox" onchange="setAbusedBy(this);">
		    <label for="patientAbusedByS" class="active">Stranger - 4</label>&nbsp;&nbsp;
		    <input id="patientAbusedByDK" class="with-gap" name="patientAbusedBy[]" value="88" type="checkbox" onchange="setAbusedBy(this);">
		    <label for="patientAbusedByDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientAbusedByR" class="with-gap" name="patientAbusedBy[]" value="99" type="checkbox" onchange="setAbusedBy(this);">
		    <label for="patientAbusedByR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientAbusedByRNA" class="with-gap" name="patientAbusedBy[]" value="2222" type="checkbox" onchange="setAbusedBy(this);">
		    <label for="patientAbusedByRNA" class="active">Response Not Available - 2222</label>&nbsp;&nbsp;
		    Other <input id="patientAbusedByOther" name="patientAbusedByOther" type="text" class="validate" style="width:20%;">
                </div>
            </div>
	    <div class="row patientAbusedBySomeone" style="margin-bottom:0;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q23B. How many times were you abused? *
                </div>
            </div>
            <div class="row patientAbusedBySomeone" style="margin-bottom:10px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="patientAbusedBySomeoneInNoofTimes" name="patientAbusedBySomeoneInNoofTimes" type="text" class="validate nooftimes checkNum" title="Don't leave Q23B" style="width:10%;"> Times&nbsp;
                    <input id="patientAbusedByNoofTimesDK" class="with-gap" name="patientAbusedByNoofTimes" value="88" type="radio">
		    <label for="patientAbusedByNoofTimesDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientAbusedByNoofTimesR" class="with-gap" name="patientAbusedByNoofTimes" value="99" type="radio">
		    <label for="patientAbusedByNoofTimesR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientAbusedByNoofTimesRNA" class="with-gap" name="patientAbusedByNoofTimes" value="2222" type="radio">
		    <label for="patientAbusedByNoofTimesRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q24. Within the last year, have you ever been hit, slapped, kicked, or otherwise physically hurt by someone? *
                </div>
            </div>
            <div class="row" style="margin-bottom:20px;">
                <div class="col s12" style="margin-bottom:0px;">
                    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearYes" class="with-gap isRequired" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" title="Don't leave Q24" value="1" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearNo" class="with-gap" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" value="2" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearDK" class="with-gap" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" value="88" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearR" class="with-gap" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" value="99" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearRNA" class="with-gap" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" value="2222" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row patientHurtBySomeoneWithinLastYear" style="margin-bottom:5px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q24A. Who hurt you? *
                </div>
            </div>
	    <div class="row patientHurtBySomeoneWithinLastYear" style="margin-bottom:10px;display:none;">
                <div class="col s12" style="margin-bottom:0px;padding-left:4%;">
                    <input id="patientHurtBySomeoneWithinLastYearH" class="with-gap" name="patientHurtBySomeoneWithinLastYear[]" title="Don't leave Q24A" value="1" type="checkbox" onchange="setHurtBy(this);">
		    <label for="patientHurtBySomeoneWithinLastYearH" class="active">Husband - 1</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneWithinLastYearExH" class="with-gap" name="patientHurtBySomeoneWithinLastYear[]" value="2" type="checkbox" onchange="setHurtBy(this);">
		    <label for="patientHurtBySomeoneWithinLastYearExH" class="active">Ex-Husband - 2</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneWithinLastYearBf" class="with-gap" name="patientHurtBySomeoneWithinLastYear[]" value="3" type="checkbox" onchange="setHurtBy(this);">
		    <label for="patientHurtBySomeoneWithinLastYearBf" class="active">Boyfriend - 3</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneWithinLastYearS" class="with-gap" name="patientHurtBySomeoneWithinLastYear[]" value="4" type="checkbox" onchange="setHurtBy(this);">
		    <label for="patientHurtBySomeoneWithinLastYearS" class="active">Stranger - 4</label>&nbsp;&nbsp;
		    <input id="patientHurtBySomeoneWithinLastYearDK" class="with-gap" name="patientHurtBySomeoneWithinLastYear[]" value="88" type="checkbox" onchange="setHurtBy(this);">
		    <label for="patientHurtBySomeoneWithinLastYearDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneWithinLastYearR" class="with-gap" name="patientHurtBySomeoneWithinLastYear[]" value="99" type="checkbox" onchange="setHurtBy(this);">
		    <label for="patientHurtBySomeoneWithinLastYearR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientHurtBySomeoneWithinLastYearRNA" class="with-gap" name="patientHurtBySomeoneWithinLastYear[]" value="2222" type="checkbox" onchange="setHurtBy(this);">
		    <label for="patientHurtBySomeoneWithinLastYearRNA" class="active">Response Not Available - 2222</label>&nbsp;&nbsp;
		    Other <input id="patientHurtByOther" name="patientHurtByOther" type="text" class="validate" style="width:20%;">
                </div>
            </div>
	    <div class="row patientHurtBySomeoneWithinLastYear" style="margin-bottom:0;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q24B. How many times were you hurt? *
                </div>
            </div>
            <div class="row patientHurtBySomeoneWithinLastYear" style="margin-bottom:10px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="patientHurtBySomeoneInNoofTimes" name="patientHurtBySomeoneInNoofTimes" type="text" class="validate nooftimes checkNum" title="Don't leave Q24B" style="width:10%;"> Times&nbsp;
                    <input id="patientHurtByNoofTimesDK" class="with-gap" name="patientHurtByNoofTimes" value="88" type="radio">
		    <label for="patientHurtByNoofTimesDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientHurtByNoofTimesR" class="with-gap" name="patientHurtByNoofTimes" value="99" type="radio">
		    <label for="patientHurtByNoofTimesR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientHurtByNoofTimesRNA" class="with-gap" name="patientHurtByNoofTimes" value="2222" type="radio">
		    <label for="patientHurtByNoofTimesRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row patientHurtBySomeoneDuringPregnancySection" style="margin-bottom:0;">
                <div class="col s12">
                    Q25. Since you've been pregnant have you been slapped, kicked or otherwise physically hurt by someone? <span class="patientHurtBySomeoneDuringPregnancySectionRequired">*</span>
                </div>
            </div>
            <div class="row patientHurtBySomeoneDuringPregnancySection" style="margin-bottom:20px;">
                <div class="col s12" style="margin-bottom:0px;">
                    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyYes" class="with-gap isRequired" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" title="Don't leave Q25" value="1" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyNo" class="with-gap" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" value="2" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyDK" class="with-gap" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" value="88" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyR" class="with-gap" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" value="99" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyRNA" class="with-gap" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" value="2222" type="radio">
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row patientHurtBySomeoneDuringPregnancy" style="margin-bottom:5px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q25A. Who hurt you? *
                </div>
            </div>
	    <div class="row patientHurtBySomeoneDuringPregnancy" style="margin-bottom:10px;display:none;">
                <div class="col s12" style="margin-bottom:0px;padding-left:4%;">
                    <input id="patientHurtBySomeoneDuringPregnancyH" class="with-gap" name="patientHurtBySomeoneDuringPregnancy[]" title="Don't leave Q25A" value="1" type="checkbox" onchange="setHurtBySomoneDuringPregnancy(this);">
		    <label for="patientHurtBySomeoneDuringPregnancyH" class="active">Husband - 1</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneDuringPregnancyExH" class="with-gap" name="patientHurtBySomeoneDuringPregnancy[]" value="2" type="checkbox" onchange="setHurtBySomoneDuringPregnancy(this);">
		    <label for="patientHurtBySomeoneDuringPregnancyExH" class="active">Ex-Husband - 2</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneDuringPregnancyBf" class="with-gap" name="patientHurtBySomeoneDuringPregnancy[]" value="3" type="checkbox" onchange="setHurtBySomoneDuringPregnancy(this);">
		    <label for="patientHurtBySomeoneDuringPregnancyBf" class="active">Boyfriend - 3</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneDuringPregnancyS" class="with-gap" name="patientHurtBySomeoneDuringPregnancy[]" value="4" type="checkbox" onchange="setHurtBySomoneDuringPregnancy(this);">
		    <label for="patientHurtBySomeoneDuringPregnancyS" class="active">Stranger - 4</label>&nbsp;&nbsp;
		    <input id="patientHurtBySomeoneDuringPregnancyDK" class="with-gap" name="patientHurtBySomeoneDuringPregnancy[]" value="88" type="checkbox" onchange="setHurtBySomoneDuringPregnancy(this);">
		    <label for="patientHurtBySomeoneDuringPregnancyDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneDuringPregnancyR" class="with-gap" name="patientHurtBySomeoneDuringPregnancy[]" value="99" type="checkbox" onchange="setHurtBySomoneDuringPregnancy(this);">
		    <label for="patientHurtBySomeoneDuringPregnancyR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientHurtBySomeoneDuringPregnancyRNA" class="with-gap" name="patientHurtBySomeoneDuringPregnancy[]" value="2222" type="checkbox" onchange="setHurtBySomoneDuringPregnancy(this);">
		    <label for="patientHurtBySomeoneDuringPregnancyRNA" class="active">Response Not Available - 2222</label>&nbsp;&nbsp;
		    Other <input id="patientHurtByOtherDuringPregnancy" name="patientHurtByOtherDuringPregnancy" type="text" class="validate" style="width:20%;">
                </div>
            </div>
	    <div class="row patientHurtBySomeoneDuringPregnancy" style="margin-bottom:0;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q25B. How many times were you hurt? *
                </div>
            </div>
            <div class="row patientHurtBySomeoneDuringPregnancy" style="margin-bottom:10px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="patientHurtBySomeoneDuringPregnancyInNoofTimes" name="patientHurtBySomeoneDuringPregnancyInNoofTimes" type="text" class="validate nooftimes checkNum" title="Don't leave Q25B" style="width:10%;"> Times&nbsp;
                    <input id="patientHurtByDuringPregnancyNoofTimesDK" class="with-gap" name="patientHurtByDuringPregnancyNoofTimes" value="88" type="radio">
		    <label for="patientHurtByDuringPregnancyNoofTimesDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientHurtByDuringPregnancyNoofTimesR" class="with-gap" name="patientHurtByDuringPregnancyNoofTimes" value="99" type="radio">
		    <label for="patientHurtByDuringPregnancyNoofTimesR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientHurtByDuringPregnancyNoofTimesRNA" class="with-gap" name="patientHurtByDuringPregnancyNoofTimes" value="2222" type="radio">
		    <label for="patientHurtByDuringPregnancyNoofTimesRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q26. Within the last year, has anyone forced you to have sexual activities? *
                </div>
            </div>
            <div class="row" style="margin-bottom:20px;">
                <div class="col s12" style="margin-bottom:0px;">
                    <input id="hasPatientEverBeenForcedForSexWithinLastYearYes" class="with-gap isRequired" name="hasPatientEverBeenForcedForSexWithinLastYear" title="Don't leave Q26" value="1" type="radio">
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenForcedForSexWithinLastYearNo" class="with-gap" name="hasPatientEverBeenForcedForSexWithinLastYear" value="2" type="radio">
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenForcedForSexWithinLastYearDK" class="with-gap" name="hasPatientEverBeenForcedForSexWithinLastYear" value="88" type="radio">
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenForcedForSexWithinLastYearR" class="with-gap" name="hasPatientEverBeenForcedForSexWithinLastYear" value="99" type="radio">
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenForcedForSexWithinLastYearRNA" class="with-gap" name="hasPatientEverBeenForcedForSexWithinLastYear" value="2222" type="radio">
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row patientForcedForSexWithinLastYear" style="margin-bottom:5px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q26A. Who forced you? *
                </div>
            </div>
	    <div class="row patientForcedForSexWithinLastYear" style="margin-bottom:10px;display:none;">
                <div class="col s12" style="margin-bottom:0px;padding-left:4%;">
                    <input id="patientForcedForSexWithinLastYearH" class="with-gap" name="patientForcedForSexWithinLastYear[]" title="Don't leave Q26A" value="1" type="checkbox" onchange="setPatientForcedforSexWithinLastYear(this);">
		    <label for="patientForcedForSexWithinLastYearH" class="active">Husband </label>&nbsp;&nbsp;
                    <input id="patientForcedForSexWithinLastYearExH" class="with-gap" name="patientForcedForSexWithinLastYear[]" value="2" type="checkbox" onchange="setPatientForcedforSexWithinLastYear(this);">
		    <label for="patientForcedForSexWithinLastYearExH" class="active">Ex-Husband </label>&nbsp;&nbsp;
                    <input id="patientForcedForSexWithinLastYearBf" class="with-gap" name="patientForcedForSexWithinLastYear[]" value="3" type="checkbox" onchange="setPatientForcedforSexWithinLastYear(this);">
		    <label for="patientForcedForSexWithinLastYearBf" class="active">Boyfriend </label>&nbsp;&nbsp;
                    <input id="patientForcedForSexWithinLastYearS" class="with-gap" name="patientForcedForSexWithinLastYear[]" value="4" type="checkbox" onchange="setPatientForcedforSexWithinLastYear(this);">
		    <label for="patientForcedForSexWithinLastYearS" class="active">Stranger</label>&nbsp;&nbsp;
		    <input id="patientForcedForSexWithinLastYearDK" class="with-gap" name="patientForcedForSexWithinLastYear[]" value="88" type="checkbox" onchange="setPatientForcedforSexWithinLastYear(this);">
		    <label for="patientForcedForSexWithinLastYearDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientForcedForSexWithinLastYearR" class="with-gap" name="patientForcedForSexWithinLastYear[]" value="99" type="checkbox" onchange="setPatientForcedforSexWithinLastYear(this);">
		    <label for="patientForcedForSexWithinLastYearR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientForcedForSexWithinLastYearRNA" class="with-gap" name="patientForcedForSexWithinLastYear[]" value="2222" type="checkbox" onchange="setPatientForcedforSexWithinLastYear(this);">
		    <label for="patientForcedForSexWithinLastYearRNA" class="active">Response Not Available - 2222</label>&nbsp;&nbsp;
		    Other <input id="patientForcedForSexByOtherWithinLastYear" name="patientForcedForSexByOtherWithinLastYear" type="text" class="validate" style="width:20%;">
                </div>
            </div>
	    <div class="row patientForcedForSexWithinLastYear" style="margin-bottom:0;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q26B. How many times were you forced? *
                </div>
            </div>
            <div class="row patientForcedForSexWithinLastYear" style="margin-bottom:10px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="patientForcedForSexInNoofTimes" name="patientForcedForSexInNoofTimes" type="text" class="validate nooftimes checkNum" title="Don't leave Q26B" style="width:10%;"> Times&nbsp;
                    <input id="patientForcedForSexNoofTimesDK" class="with-gap" name="patientForcedForSexNoofTimes" value="88" type="radio">
		    <label for="patientForcedForSexNoofTimesDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientForcedForSexNoofTimesR" class="with-gap" name="patientForcedForSexNoofTimes" value="99" type="radio">
		    <label for="patientForcedForSexNoofTimesR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientForcedForSexNoofTimesRNA" class="with-gap" name="patientForcedForSexNoofTimes" value="2222" type="radio">
		    <label for="patientForcedForSexNoofTimesRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q27. Are you afraid of your partner or anyone listed above? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="isPatientAfraidOfAnyoneYes" class="with-gap isRequired" name="isPatientAfraidOfAnyone" title="Don't leave Q27" value="1" type="radio">
		    <label for="isPatientAfraidOfAnyoneYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="isPatientAfraidOfAnyoneNo" class="with-gap" name="isPatientAfraidOfAnyone" value="2" type="radio">
		    <label for="isPatientAfraidOfAnyoneNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="isPatientAfraidOfAnyoneDK" class="with-gap" name="isPatientAfraidOfAnyone" value="88" type="radio">
		    <label for="isPatientAfraidOfAnyoneDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="isPatientAfraidOfAnyoneR" class="with-gap" name="isPatientAfraidOfAnyone" value="99" type="radio">
		    <label for="isPatientAfraidOfAnyoneR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="isPatientAfraidOfAnyoneRNA" class="with-gap" name="isPatientAfraidOfAnyone" value="2222" type="radio">
		    <label for="isPatientAfraidOfAnyoneRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:10px;">
                <div class="input-field col s6">
                    <textarea id="comment" name="comment" class="materialize-textarea" title="Please enter comments"></textarea>
                    <label for="comment">Comments </label>
                </div>
            </div>
            <div class="col s12" style="margin-top:10px;">
                <input type="hidden" name="chosenCountry" id="chosenCountry" value="<?php echo base64_encode($countryId);?>"/>
                <input type="hidden" name="redirectUrl" id="redirectUrl" value="<?php echo $link;?>"/>
                <a href="<?php echo $link;?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addRiskAssessment();">ADD</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/moment.min.js' ?>"></script>
<script>
    $(document).ready(function(){
       $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 15, // Creates a dropdown of 15 years to control year
            format: 'dd/mm/yyyy',
	    max: new Date('Today'),
	    onSet: function(e){
		$('.picker__close').click();
	    }
        });
    });
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if($.trim(checkValue)!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
    
    //set occupation
    $('#occupation').on('change',function(){
	if(this.value == 1111){
	    $('.occupationNew').show();
	    $('#occupationNew').addClass('isRequired');
	    $('#occupationNew').focus();
	}else{
	   $('.occupationNew').hide();
	   $('#occupationNew').removeClass('isRequired'); 
	}
    });
    
    //set age at first marriage
    $('#ageAtFirstMarriageInYears').on('change',function() {
	setAgeAtFirstMarriage('txt');
    });
    $('input:radio[name=ageAtFirstMarriage]').change(function () {
	setAgeAtFirstMarriage('rd');
    });
    
    function setAgeAtFirstMarriage(fromSource){
	if(fromSource == 'txt'){
	    if($('#ageAtFirstMarriageInYears').val()!= ''){
		$('input[name="ageAtFirstMarriage"]:radio').prop('checked',false);
	    }
	    $('#ageAtFirstMarriageInYears').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#ageAtFirstMarriageInYears').val('');
	   $('#ageAtFirstMarriageInYears').removeClass('isRequired');
	}
    }
    
    //set no.of sexual partners
    $('#noOfSexualPartnersInNumbers').on('change',function() {
	setNoOfSexualPartners('txt');
    });
    $('input:radio[name=noOfSexualPartners]').change(function () {
	setNoOfSexualPartners('rd');
    });
    function setNoOfSexualPartners(fromSource){
	if(fromSource == 'txt'){
	    if($('#noOfSexualPartnersInNumbers').val()!= ''){
		$('input[name="noOfSexualPartners"]:radio').prop('checked',false);
	    }
	    $('#noOfSexualPartnersInNumbers').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#noOfSexualPartnersInNumbers').val('');
	   $('#noOfSexualPartnersInNumbers').removeClass('isRequired');
	}
    }
    
    //set no.of sexual partners in last six months
    $('#noOfSexualPartnersInLastSixMonthsInNumbers').on('change',function() {
	setNoOfSexualPartnersInLastSixMonths('txt');
    });
    $('input:radio[name=noOfSexualPartnersInLastSixMonths]').change(function () {
	setNoOfSexualPartnersInLastSixMonths('rd');
    });
    function setNoOfSexualPartnersInLastSixMonths(fromSource){
	if(fromSource == 'txt'){
	    if($('#noOfSexualPartnersInLastSixMonthsInNumbers').val()!= ''){
		$('input[name="noOfSexualPartnersInLastSixMonths"]:radio').prop('checked',false);
	    }
	    $('#noOfSexualPartnersInLastSixMonthsInNumbers').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#noOfSexualPartnersInLastSixMonthsInNumbers').val('');
	   $('#noOfSexualPartnersInLastSixMonthsInNumbers').removeClass('isRequired');
	}
    }
    
    //set main sexual partner age at last birthday
    $('#ageOfMainSexualPartnerAtLastBirthdayInYears').on('change',function() {
	mainSexualPartnerAgeAtLastBirthday('txt');
    });
    $('input:radio[name=ageOfMainSexualPartnerAtLastBirthday]').change(function () {
	mainSexualPartnerAgeAtLastBirthday('rd');
    });
    function mainSexualPartnerAgeAtLastBirthday(fromSource){
	if(fromSource == 'txt'){
	    if($('#ageOfMainSexualPartnerAtLastBirthdayInYears').val()!= ''){
		$('.mainSexualPartnerAgeSectionRequired').css('visibility','hidden');
		$('.mainSexualPartnerAgeSection').css('color','rgba(0,0,0,0.26)');
		$('.mainSexualPartnerAgeSection').css('pointer-events','none');
		$('input[name="ageOfMainSexualPartnerAtLastBirthday"]:radio').prop('checked',false);
		$('#ageDiffOfMainSexualPartner').removeClass('isRequired');
	    }else{
		$('.mainSexualPartnerAgeSectionRequired').css('visibility','visible');
		$('.mainSexualPartnerAgeSection').css('color','');
		$('.mainSexualPartnerAgeSection').css('pointer-events','auto');
		$('#ageDiffOfMainSexualPartner').addClass('isRequired');
	    }
	    $('#ageOfMainSexualPartnerAtLastBirthdayInYears').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('.mainSexualPartnerAgeSectionRequired').css('visibility','visible');
	   $('.mainSexualPartnerAgeSection').css('color','');
	   $('.mainSexualPartnerAgeSection').css('pointer-events','auto');
	   $('#ageOfMainSexualPartnerAtLastBirthdayInYears').val('');
	   $('#ageOfMainSexualPartnerAtLastBirthdayInYears').removeClass('isRequired');
	   $('#ageDiffOfMainSexualPartner').addClass('isRequired');
	}
    }
    
    //set no.of days in last six months
    $('#patientHadDrinkWithAlcoholInLastSixMonthsInDays').on('change',function() {
        noOfDaysHadDrinkInLastSixMonth('txt');
    });
    $('input:radio[name=patientHadDrinkWithAlcoholInLastSixMonths]').change(function () {
	noOfDaysHadDrinkInLastSixMonth('rd');
    });
    function noOfDaysHadDrinkInLastSixMonth(fromSource){
	if(fromSource == 'txt'){
	    if($('#patientHadDrinkWithAlcoholInLastSixMonthsInDays').val()!= ''){
		$('input[name="patientHadDrinkWithAlcoholInLastSixMonths"]:radio').prop('checked',false);
	    }
	    $('#patientHadDrinkWithAlcoholInLastSixMonthsInDays').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#patientHadDrinkWithAlcoholInLastSixMonthsInDays').val('');
	   $('#patientHadDrinkWithAlcoholInLastSixMonthsInDays').removeClass('isRequired');
	}
    }
    
    //set patient abused by
    $('input:radio[name=hasPatientEverBeenAbusedBySomeone]').change(function () {
        if ($("input[name='hasPatientEverBeenAbusedBySomeone']:checked").val() == 1) {
	    $('.patientAbusedBySomeone').show();
	    $('#patientAbusedByH,#patientAbusedBySomeoneInNoofTimes').addClass('isRequired');
	}else{
	  $('.patientAbusedBySomeone').hide();
	  $('input[name="patientAbusedBy[]"]:checkbox').prop('checked',false);
	  $('input[name="patientAbusedByNoofTimes"]:radio').prop('checked',false);
	  $('#patientAbusedByH,#patientAbusedBySomeoneInNoofTimes').removeClass('isRequired');
	  $('#patientAbusedBySomeoneInNoofTimes').val('');
	  resetPatientAbusedBySection();
	}
    });
    
    abusedBy = [];
    abusedByGroup = [1,2,3,4];
    notAbusedByGroup = [88,99,2222];
    function setAbusedBy(obj){
	if($(obj).is(":checked")) {
	    abusedBy.push(obj.value);
	}else{
	   abusedBy.splice(abusedBy.indexOf(obj.value), 1);
	}
	hasAbusedBy = false;
	hasNotAbusedBy = false;
	for(var i = 0;i < abusedBy.length; i++){
	    if(abusedByGroup.indexOf(parseInt(abusedBy[i]))!= -1){
		hasAbusedBy = true;
	    } if(notAbusedByGroup.indexOf(parseInt(abusedBy[i]))!= -1){
		hasNotAbusedBy = true;
	    }
	}
	if(hasAbusedBy){
	    $('#patientAbusedByDK,#patientAbusedByR,#patientAbusedByRNA').prop('checked',false);
	    $('label[for="patientAbusedByDK"]').css('pointer-events','none');
	    $('label[for="patientAbusedByR"]').css('pointer-events','none');
	    $('label[for="patientAbusedByRNA"]').css('pointer-events','none');
	    $('#patientAbusedByOther').css('pointer-events','none');
	    $('#patientAbusedByOther').val('');
	}else if(hasNotAbusedBy){
	    $('label[for="patientAbusedByH"]').css('pointer-events','none');
	    $('label[for="patientAbusedByExH"]').css('pointer-events','none');
	    $('label[for="patientAbusedByBf"]').css('pointer-events','none');
	    $('label[for="patientAbusedByS"]').css('pointer-events','none');
	    $('#patientAbusedByOther').css('pointer-events','none');
	    $('#patientAbusedByOther').val('');
	    if(obj.value == 88){
		$('#patientAbusedByH,#patientAbusedByExH,#patientAbusedByBf,#patientAbusedByS,#patientAbusedByR,#patientAbusedByRNA').prop('checked',false);
		$('label[for="patientAbusedByR"]').css('pointer-events','none');
		$('label[for="patientAbusedByRNA"]').css('pointer-events','none');
	    }else if(obj.value == 99){
		$('#patientAbusedByH,#patientAbusedByExH,#patientAbusedByBf,#patientAbusedByS,#patientAbusedByDK,#patientAbusedByRNA').prop('checked',false);
		$('label[for="patientAbusedByDK"]').css('pointer-events','none');
		$('label[for="patientAbusedByRNA"]').css('pointer-events','none');
	    }else if(obj.value == 2222){
		$('#patientAbusedByH,#patientAbusedByExH,#patientAbusedByBf,#patientAbusedByS,#patientAbusedByDK,#patientAbusedByR').prop('checked',false);
		$('label[for="patientAbusedByDK"]').css('pointer-events','none');
		$('label[for="patientAbusedByR"]').css('pointer-events','none');
	    }
	    
	}else{
	    resetPatientAbusedBySection();
	}
    }
    
    $('#patientAbusedByOther').on('change',function() {
	if($.trim($('#patientAbusedByOther').val())!= ''){
	    $('#patientAbusedByH').removeClass('isRequired');
	    $('#patientAbusedByH,#patientAbusedByExH,#patientAbusedByBf,#patientAbusedByS,#patientAbusedByDK,#patientAbusedByR,#patientAbusedByRNA').prop('checked',false);
	    $('label[for="patientAbusedByH"]').css('pointer-events','none');
	    $('label[for="patientAbusedByExH"]').css('pointer-events','none');
	    $('label[for="patientAbusedByBf"]').css('pointer-events','none');
	    $('label[for="patientAbusedByS"]').css('pointer-events','none');
	    $('label[for="patientAbusedByDK"]').css('pointer-events','none');
	    $('label[for="patientAbusedByR"]').css('pointer-events','none');
	    $('label[for="patientAbusedByRNA"]').css('pointer-events','none');
	}else{
	    $('#patientAbusedByH').addClass('isRequired');
	    resetPatientAbusedBySection();
	}
    });
    
    $('#patientAbusedBySomeoneInNoofTimes').on('change',function() {
        patientAbusedBySomeoneinNumbers('txt');
    });
    $('input:radio[name=patientAbusedByNoofTimes]').change(function () {
	patientAbusedBySomeoneinNumbers('rd');
    });
    function patientAbusedBySomeoneinNumbers(fromSource){
	if(fromSource == 'txt'){
	    if($('#patientAbusedBySomeoneInNoofTimes').val()!= ''){
		$('#patientAbusedByNoofTimesDK,#patientAbusedByNoofTimesR,#patientAbusedByNoofTimesRNA').prop('checked',false);
	    }
	    $('#patientAbusedBySomeoneInNoofTimes').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#patientAbusedBySomeoneInNoofTimes').val('');
	   $('#patientAbusedBySomeoneInNoofTimes').removeClass('isRequired');
	}
    }
    
    function resetPatientAbusedBySection(){
	$('label[for="patientAbusedByH"]').css('pointer-events','auto');
	$('label[for="patientAbusedByExH"]').css('pointer-events','auto');
	$('label[for="patientAbusedByBf"]').css('pointer-events','auto');
	$('label[for="patientAbusedByS"]').css('pointer-events','auto');
	$('label[for="patientAbusedByDK"]').css('pointer-events','auto');
	$('label[for="patientAbusedByR"]').css('pointer-events','auto');
	$('label[for="patientAbusedByRNA"]').css('pointer-events','auto');
	$('#patientAbusedByOther').css('pointer-events','auto');
	$('#patientAbusedByOther').val('');
    }
    
    //set patient hurt by some within last year
    $('input:radio[name=hasPatientEverBeenHurtBySomeoneWithinLastYear]').change(function () {
	skipToQ26($("input[name='hasPatientEverBeenHurtBySomeoneWithinLastYear']:checked").val());
        if ($("input[name='hasPatientEverBeenHurtBySomeoneWithinLastYear']:checked").val() == 1) {
	    $('.patientHurtBySomeoneWithinLastYear').show();
	    $('#patientHurtBySomeoneWithinLastYearH,#patientHurtBySomeoneInNoofTimes').addClass('isRequired');
	}else{
	    $('.patientHurtBySomeoneWithinLastYear').hide();
	    $('input[name="patientHurtBySomeoneWithinLastYear[]"]:checkbox').prop('checked',false);
	    $('input[name="patientHurtByNoofTimes"]:radio').prop('checked',false);
	    $('#patientHurtBySomeoneWithinLastYearH,#patientHurtBySomeoneInNoofTimes').removeClass('isRequired');
	    $('#patientHurtBySomeoneInNoofTimes').val('');
	    resetPatientHurtBySection();
	}
    });
    
    hurtBy = [];
    hurtByGroup = [1,2,3,4];
    notHurtByGroup = [88,99,2222];
    function setHurtBy(obj){
	if($(obj).is(":checked")) {
	    hurtBy.push(obj.value);
	}else{
	   hurtBy.splice(hurtBy.indexOf(obj.value), 1);
	}
	hasHurtBy = false;
	hasNotHurtBy = false;
	for(var i = 0;i < hurtBy.length; i++){
	    if(hurtByGroup.indexOf(parseInt(hurtBy[i]))!= -1){
		hasHurtBy = true;
	    } if(notHurtByGroup.indexOf(parseInt(hurtBy[i]))!= -1){
		hasNotHurtBy = true;
	    }
	}
	if(hasHurtBy){
	    $('#patientHurtBySomeoneWithinLastYearDK,#patientHurtBySomeoneWithinLastYearR,#patientHurtBySomeoneWithinLastYearRNA').prop('checked',false);
	    $('label[for="patientHurtBySomeoneWithinLastYearDK"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearR"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearRNA"]').css('pointer-events','none');
	    $('#patientHurtByOther').css('pointer-events','none');
	    $('#patientHurtByOther').val('');
	}else if(hasNotHurtBy){
	    $('label[for="patientHurtBySomeoneWithinLastYearH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearExH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearBf"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearS"]').css('pointer-events','none');
	    $('#patientHurtByOther').css('pointer-events','none');
	    $('#patientHurtByOther').val('');
	    if(obj.value == 88){
		$('#patientHurtBySomeoneWithinLastYearH,#patientHurtBySomeoneWithinLastYearExH,#patientHurtBySomeoneWithinLastYearBf,#patientHurtBySomeoneWithinLastYearS,#patientHurtBySomeoneWithinLastYearR,#patientHurtBySomeoneWithinLastYearRNA').prop('checked',false);
		$('label[for="patientHurtBySomeoneWithinLastYearR"]').css('pointer-events','none');
		$('label[for="patientHurtBySomeoneWithinLastYearRNA"]').css('pointer-events','none');
	    }else if(obj.value == 99){
		$('#patientHurtBySomeoneWithinLastYearH,#patientHurtBySomeoneWithinLastYearExH,#patientHurtBySomeoneWithinLastYearBf,#patientHurtBySomeoneWithinLastYearS,#patientHurtBySomeoneWithinLastYearDK,#patientHurtBySomeoneWithinLastYearRNA').prop('checked',false);
		$('label[for="patientHurtBySomeoneWithinLastYearDK"]').css('pointer-events','none');
		$('label[for="patientHurtBySomeoneWithinLastYearRNA"]').css('pointer-events','none');
	    }else if(obj.value == 2222){
		$('#patientHurtBySomeoneWithinLastYearH,#patientHurtBySomeoneWithinLastYearExH,#patientHurtBySomeoneWithinLastYearBf,#patientHurtBySomeoneWithinLastYearS,#patientHurtBySomeoneWithinLastYearDK,#patientHurtBySomeoneWithinLastYearR').prop('checked',false);
		$('label[for="patientHurtBySomeoneWithinLastYearDK"]').css('pointer-events','none');
		$('label[for="patientHurtBySomeoneWithinLastYearR"]').css('pointer-events','none');
	    }
	    
	}else{
	    resetPatientHurtBySection();
	}
    }
    
    $('#patientHurtByOther').on('change',function() {
	if($.trim($('#patientHurtByOther').val())!= ''){
	    $('#patientHurtBySomeoneWithinLastYearH').removeClass('isRequired');
	    $('#patientHurtBySomeoneWithinLastYearH,#patientHurtBySomeoneWithinLastYearExH,#patientHurtBySomeoneWithinLastYearBf,#patientHurtBySomeoneWithinLastYearS,#patientHurtBySomeoneWithinLastYearDK,#patientHurtBySomeoneWithinLastYearR,#patientHurtBySomeoneWithinLastYearRNA').prop('checked',false);
	    $('label[for="patientHurtBySomeoneWithinLastYearH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearExH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearBf"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearS"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearDK"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearR"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearRNA"]').css('pointer-events','none');
	}else{
	    $('#patientHurtBySomeoneWithinLastYearH').addClass('isRequired');
	    resetPatientHurtBySection();
	}
    });
    
    $('#patientHurtBySomeoneInNoofTimes').on('change',function() {
        patientHurtBySomeoneinNumbers('txt');
    });
    $('input:radio[name=patientHurtByNoofTimes]').change(function () {
	patientHurtBySomeoneinNumbers('rd');
    });
    function patientHurtBySomeoneinNumbers(fromSource){
	if(fromSource == 'txt'){
	    if($('#patientHurtBySomeoneInNoofTimes').val()!= ''){
		$('#patientHurtByNoofTimesDK,#patientHurtByNoofTimesR,#patientHurtByNoofTimesRNA').prop('checked',false);
	    }
	    $('#patientHurtBySomeoneInNoofTimes').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#patientHurtBySomeoneInNoofTimes').val('');
	   $('#patientHurtBySomeoneInNoofTimes').removeClass('isRequired');
	}
    }
    
    function resetPatientHurtBySection(){
	$('label[for="patientHurtBySomeoneWithinLastYearH"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneWithinLastYearExH"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneWithinLastYearBf"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneWithinLastYearS"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneWithinLastYearDK"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneWithinLastYearR"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneWithinLastYearRNA"]').css('pointer-events','auto');
	$('#patientHurtByOther').css('pointer-events','auto');
	$('#patientAbusedByOther').val('');
    }
    
    //set patient hurt by someone during pregnancy
    $('input:radio[name=hasPatientEverBeenHurtBySomeoneDuringPregnancy]').change(function () {
        if ($("input[name='hasPatientEverBeenHurtBySomeoneDuringPregnancy']:checked").val() == 1) {
	    $('.patientHurtBySomeoneDuringPregnancy').show();
	    $('#patientHurtBySomeoneDuringPregnancyH,#patientHurtBySomeoneDuringPregnancyInNoofTimes').addClass('isRequired');
	}else{
	  $('.patientHurtBySomeoneDuringPregnancy').hide();
	  $('input[name="patientHurtBySomeoneDuringPregnancy[]"]:checkbox').prop('checked',false);
	  $('input[name="patientHurtByDuringPregnancyNoofTimes"]:radio').prop('checked',false);
	  $('#patientHurtBySomeoneDuringPregnancyH,#patientHurtBySomeoneDuringPregnancyInNoofTimes').removeClass('isRequired');
	  $('#patientHurtBySomeoneDuringPregnancyInNoofTimes').val('');
	  resetPatientHurtByDuringPregnancySection();
	}
    });
    
    hurtByDuringPregnancy = [];
    hurtByDuringPregnancyGroup = [1,2,3,4];
    notHurtByDuringPregnancyGroup = [88,99,2222];
    function setHurtBySomoneDuringPregnancy(obj){
	if($(obj).is(":checked")) {
	    hurtByDuringPregnancy.push(obj.value);
	}else{
	   hurtByDuringPregnancy.splice(hurtByDuringPregnancy.indexOf(obj.value), 1);
	}
	hasHurtByDuringPregnancy = false;
	hasNotHurtByDuringPregnancy = false;
	for(var i = 0;i < hurtByDuringPregnancy.length; i++){
	    if(hurtByDuringPregnancyGroup.indexOf(parseInt(hurtByDuringPregnancy[i]))!= -1){
		hasHurtByDuringPregnancy = true;
	    } if(notHurtByDuringPregnancyGroup.indexOf(parseInt(hurtByDuringPregnancy[i]))!= -1){
		hasNotHurtByDuringPregnancy = true;
	    }
	}
	if(hasHurtByDuringPregnancy){
	    $('#patientHurtBySomeoneDuringPregnancyDK,#patientHurtBySomeoneDuringPregnancyR,#patientHurtBySomeoneDuringPregnancyRNA').prop('checked',false);
	    $('label[for="patientHurtBySomeoneDuringPregnancyDK"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyR"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyRNA"]').css('pointer-events','none');
	    $('#patientHurtByOtherDuringPregnancy').css('pointer-events','none');
	    $('#patientHurtByOtherDuringPregnancy').val('');
	}else if(hasNotHurtByDuringPregnancy){
	    $('label[for="patientHurtBySomeoneDuringPregnancyH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyExH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyBf"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyS"]').css('pointer-events','none');
	    $('#patientHurtByOtherDuringPregnancy').css('pointer-events','none');
	    $('#patientHurtByOtherDuringPregnancy').val('');
	    if(obj.value == 88){
		$('#patientHurtBySomeoneDuringPregnancyH,#patientHurtBySomeoneDuringPregnancyExH,#patientHurtBySomeoneDuringPregnancyBf,#patientHurtBySomeoneDuringPregnancyS,#patientHurtBySomeoneDuringPregnancyR,#patientHurtBySomeoneDuringPregnancyRNA').prop('checked',false);
		$('label[for="patientHurtBySomeoneDuringPregnancyR"]').css('pointer-events','none');
		$('label[for="patientHurtBySomeoneDuringPregnancyRNA"]').css('pointer-events','none');
	    }else if(obj.value == 99){
		$('#patientHurtBySomeoneDuringPregnancyH,#patientHurtBySomeoneDuringPregnancyExH,#patientHurtBySomeoneDuringPregnancyBf,#patientHurtBySomeoneDuringPregnancyS,#patientHurtBySomeoneDuringPregnancyDK,#patientHurtBySomeoneDuringPregnancyRNA').prop('checked',false);
		$('label[for="patientHurtBySomeoneDuringPregnancyDK"]').css('pointer-events','none');
		$('label[for="patientHurtBySomeoneDuringPregnancyRNA"]').css('pointer-events','none');
	    }else if(obj.value == 2222){
		$('#patientHurtBySomeoneDuringPregnancyH,#patientHurtBySomeoneDuringPregnancyExH,#patientHurtBySomeoneDuringPregnancyBf,#patientHurtBySomeoneDuringPregnancyS,#patientHurtBySomeoneDuringPregnancyDK,#patientHurtBySomeoneDuringPregnancyR').prop('checked',false);
		$('label[for="patientHurtBySomeoneDuringPregnancyDK"]').css('pointer-events','none');
		$('label[for="patientHurtBySomeoneDuringPregnancyR"]').css('pointer-events','none');
	    }
	    
	}else{
	    resetPatientHurtByDuringPregnancySection();
	}
    }
    
    $('#patientHurtByOtherDuringPregnancy').on('change',function() {
	if($.trim($('#patientHurtByOtherDuringPregnancy').val())!= ''){
	    $('#patientHurtBySomeoneDuringPregnancyH').removeClass('isRequired');
	    $('#patientHurtBySomeoneDuringPregnancyH,#patientHurtBySomeoneDuringPregnancyExH,#patientHurtBySomeoneDuringPregnancyBf,#patientHurtBySomeoneDuringPregnancyS,#patientHurtBySomeoneDuringPregnancyDK,#patientHurtBySomeoneDuringPregnancyR,#patientHurtBySomeoneDuringPregnancyRNA').prop('checked',false);
	    $('label[for="patientHurtBySomeoneDuringPregnancyH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyExH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyBf"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyS"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyDK"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyR"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyRNA"]').css('pointer-events','none');
	}else{
	    $('#patientHurtBySomeoneDuringPregnancyH').addClass('isRequired');
	    resetPatientHurtByDuringPregnancySection();
	}
    });
    
    $('#patientHurtBySomeoneDuringPregnancyInNoofTimes').on('change',function() {
        patientHurtBySomeoneDuringPrenancyinNumbers('txt');
    });
    $('input:radio[name=patientHurtByDuringPregnancyNoofTimes]').change(function () {
	patientHurtBySomeoneDuringPrenancyinNumbers('rd');
    });
    function patientHurtBySomeoneDuringPrenancyinNumbers(fromSource){
	if(fromSource == 'txt'){
	    if($('#patientHurtBySomeoneDuringPregnancyInNoofTimes').val()!= ''){
		$('#patientHurtByDuringPregnancyNoofTimesDK,#patientHurtByDuringPregnancyNoofTimesR,#patientHurtByDuringPregnancyNoofTimesRNA').prop('checked',false);
	    }
	    $('#patientHurtBySomeoneDuringPregnancyInNoofTimes').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#patientHurtBySomeoneDuringPregnancyInNoofTimes').val('');
	   $('#patientHurtBySomeoneDuringPregnancyInNoofTimes').removeClass('isRequired');
	}
    }
    
    function resetPatientHurtByDuringPregnancySection(){
	$('label[for="patientHurtBySomeoneDuringPregnancyH"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneDuringPregnancyExH"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneDuringPregnancyBf"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneDuringPregnancyS"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneDuringPregnancyDK"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneDuringPregnancyR"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneDuringPregnancyRNA"]').css('pointer-events','auto');
	$('#patientHurtByOtherDuringPregnancy').css('pointer-events','auto');
	$('#patientHurtByOtherDuringPregnancy').val('');
    }
    
    //set patient forced for sex within last year
    $('input:radio[name=hasPatientEverBeenForcedForSexWithinLastYear]').change(function () {
        if ($("input[name='hasPatientEverBeenForcedForSexWithinLastYear']:checked").val() == 1) {
	    $('.patientForcedForSexWithinLastYear').show();
	    $('#patientForcedForSexWithinLastYearH,#patientForcedForSexInNoofTimes').addClass('isRequired');
	}else{
	  $('.patientForcedForSexWithinLastYear').hide();
	  $('input[name="patientForcedForSexWithinLastYear[]"]:checkbox').prop('checked',false);
	  $('input[name="patientForcedForSexNoofTimes"]:radio').prop('checked',false);
	  $('#patientForcedForSexWithinLastYearH,#patientForcedForSexInNoofTimes').removeClass('isRequired');
	  $('#patientForcedForSexInNoofTimes').val('');
	  resetPatientForcedforSexWithinLastYearSection();
	}
    });
    
    forcedforSexBy = [];
    forcedforSexByGroup = [1,2,3,4];
    notForcedforSexByGroup = [88,99,2222];
    function setPatientForcedforSexWithinLastYear(obj){
	if($(obj).is(":checked")) {
	    forcedforSexBy.push(obj.value);
	}else{
	   forcedforSexBy.splice(forcedforSexBy.indexOf(obj.value), 1);
	}
	hasForcedforSexBy = false;
	hasNotForcedforSexBy = false;
	for(var i = 0;i < forcedforSexBy.length; i++){
	    if(forcedforSexByGroup.indexOf(parseInt(forcedforSexBy[i]))!= -1){
		hasForcedforSexBy = true;
	    } if(notForcedforSexByGroup.indexOf(parseInt(forcedforSexBy[i]))!= -1){
		hasNotForcedforSexBy = true;
	    }
	}
	if(hasForcedforSexBy){
	    $('#patientForcedForSexWithinLastYearDK,#patientForcedForSexWithinLastYearR,#patientForcedForSexWithinLastYearRNA').prop('checked',false);
	    $('label[for="patientForcedForSexWithinLastYearDK"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearR"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearRNA"]').css('pointer-events','none');
	    $('#patientForcedForSexByOtherWithinLastYear').css('pointer-events','none');
	    $('#patientForcedForSexByOtherWithinLastYear').val('');
	}else if(hasNotForcedforSexBy){
	    $('label[for="patientForcedForSexWithinLastYearH"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearExH"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearBf"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearS"]').css('pointer-events','none');
	    $('#patientForcedForSexByOtherWithinLastYear').css('pointer-events','none');
	    $('#patientForcedForSexByOtherWithinLastYear').val('');
	    if(obj.value == 88){
		$('#patientForcedForSexWithinLastYearH,#patientForcedForSexWithinLastYearExH,#patientForcedForSexWithinLastYearBf,#patientForcedForSexWithinLastYearS,#patientForcedForSexWithinLastYearR,#patientForcedForSexWithinLastYearRNA').prop('checked',false);
		$('label[for="patientForcedForSexWithinLastYearR"]').css('pointer-events','none');
		$('label[for="patientForcedForSexWithinLastYearRNA"]').css('pointer-events','none');
	    }else if(obj.value == 99){
		$('#patientForcedForSexWithinLastYearH,#patientForcedForSexWithinLastYearExH,#patientForcedForSexWithinLastYearBf,#patientForcedForSexWithinLastYearS,#patientForcedForSexWithinLastYearDK,#patientForcedForSexWithinLastYearRNA').prop('checked',false);
		$('label[for="patientForcedForSexWithinLastYearDK"]').css('pointer-events','none');
		$('label[for="patientForcedForSexWithinLastYearRNA"]').css('pointer-events','none');
	    }else if(obj.value == 2222){
		$('#patientForcedForSexWithinLastYearH,#patientForcedForSexWithinLastYearExH,#patientForcedForSexWithinLastYearBf,#patientForcedForSexWithinLastYearS,#patientForcedForSexWithinLastYearDK,#patientForcedForSexWithinLastYearR').prop('checked',false);
		$('label[for="patientForcedForSexWithinLastYearDK"]').css('pointer-events','none');
		$('label[for="patientForcedForSexWithinLastYearR"]').css('pointer-events','none');
	    }
	    
	}else{
	    resetPatientForcedforSexWithinLastYearSection();
	}
    }
    
    $('#patientForcedForSexByOtherWithinLastYear').on('change',function() {
	if($.trim($('#patientForcedForSexByOtherWithinLastYear').val())!= ''){
	    $('#patientForcedForSexWithinLastYearH').removeClass('isRequired');
	    $('#patientForcedForSexWithinLastYearH,#patientForcedForSexWithinLastYearExH,#patientForcedForSexWithinLastYearBf,#patientForcedForSexWithinLastYearS,#patientForcedForSexWithinLastYearDK,#patientForcedForSexWithinLastYearR,#patientForcedForSexWithinLastYearRNA').prop('checked',false);
	    $('label[for="patientForcedForSexWithinLastYearH"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearExH"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearBf"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearS"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearDK"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearR"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearRNA"]').css('pointer-events','none');
	}else{
	    $('#patientForcedForSexWithinLastYearH').addClass('isRequired');
	    resetPatientForcedforSexWithinLastYearSection();
	}
    });
    
    $('#patientForcedForSexInNoofTimes').on('change',function() {
        patientForcedforSexWithinLastYearinNumbers('txt');
    });
    $('input:radio[name=patientForcedForSexNoofTimes]').change(function () {
	patientForcedforSexWithinLastYearinNumbers('rd');
    });
    function patientForcedforSexWithinLastYearinNumbers(fromSource){
	if(fromSource == 'txt'){
	    if($('#patientForcedForSexInNoofTimes').val()!= ''){
		$('#patientForcedForSexNoofTimesDK,#patientForcedForSexNoofTimesR,#patientForcedForSexNoofTimesRNA').prop('checked',false);
	    }
	    $('#patientForcedForSexInNoofTimes').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#patientForcedForSexInNoofTimes').val('');
	   $('#patientForcedForSexInNoofTimes').removeClass('isRequired');
	}
    }
    
    function resetPatientForcedforSexWithinLastYearSection(){
	$('label[for="patientForcedForSexWithinLastYearH"]').css('pointer-events','auto');
	$('label[for="patientForcedForSexWithinLastYearExH"]').css('pointer-events','auto');
	$('label[for="patientForcedForSexWithinLastYearBf"]').css('pointer-events','auto');
	$('label[for="patientForcedForSexWithinLastYearS"]').css('pointer-events','auto');
	$('label[for="patientForcedForSexWithinLastYearDK"]').css('pointer-events','auto');
	$('label[for="patientForcedForSexWithinLastYearR"]').css('pointer-events','auto');
	$('label[for="patientForcedForSexWithinLastYearRNA"]').css('pointer-events','auto');
	$('#patientForcedForSexByOtherWithinLastYear').css('pointer-events','auto');
	$('#patientForcedForSexByOtherWithinLastYear').val('');
    }
    
    function skipToQ26(val){
	if(val!= 1){
	   $('.patientHurtBySomeoneDuringPregnancySectionRequired').css('visibility','hidden');
	   $('.patientHurtBySomeoneDuringPregnancySection').css('color','rgba(0,0,0,0.26)');
	   $('.patientHurtBySomeoneDuringPregnancySection').css('pointer-events','none');
	   $('input[name="hasPatientEverBeenHurtBySomeoneDuringPregnancy"]:radio').prop('checked',false);
	   $('.patientHurtBySomeoneDuringPregnancy').hide();
	   $('input[name="patientHurtBySomeoneDuringPregnancy[]"]:checkbox').prop('checked',false);
	   $('input[name="patientHurtByDuringPregnancyNoofTimes"]:radio').prop('checked',false);
	   $('#hasPatientEverBeenHurtBySomeoneDuringPregnancyYes,#patientHurtBySomeoneDuringPregnancyH,#patientHurtBySomeoneDuringPregnancyInNoofTimes').removeClass('isRequired');
	   $('#patientHurtBySomeoneDuringPregnancyInNoofTimes').val('');
	   resetPatientHurtByDuringPregnancySection();
	}else{
	   $('.patientHurtBySomeoneDuringPregnancySectionRequired').css('visibility','visible');
	   $(".patientHurtBySomeoneDuringPregnancySection").css("color","");
	   $('.patientHurtBySomeoneDuringPregnancySection').css('pointer-events','auto');
	   $('#hasPatientEverBeenHurtBySomeoneDuringPregnancyYes').addClass('isRequired');
	}
    }
    
    //set patient recency test status
    $('input:radio[name=hasPatientHadRapidRecencyTest]').change(function () {
	if ($("input[name='hasPatientHadRapidRecencyTest']:checked").val() == 'done') {
	    $('#rtrSection').css('height','auto');
	    $('.rrrSection').show();
	}else{
	   $('#rtrSection').css('height','90px');
	   $('.rrrSection').hide();
	   //$('#rrrHIVDiagnostic option:first').prop('selected', true);
	   //$('#rrrRecency option:first').prop('selected', true);
	}
    });
    
    //recency show/hide based on HIV diagostic
    $('#rrrHIVDiagnostic').on('change',function () {
	if ($('#rrrHIVDiagnostic').val() == 'negative') {
	    $('.rrrRecency').hide();
	}else{
	    $('.rrrRecency').show();
	}
    });
    
    //enable/disable Demographic Characteristics fields based on q.2
    $('input:radio[name=hasPatientEverAttendedSchool]').change(function () {
	if ($("input[name='hasPatientEverAttendedSchool']:checked").val()!= 1) {
	    //css section
	    $(".degreeSectionRequired").css("visibility","hidden");
	    $(".degreeSection").css("color","rgba(0,0,0,0.26)");
	    $(".degree").css("pointer-events","none");
	    //validate/content section
	    $("#degree").removeClass("isRequired");
	}else{
	    //css section
	    $(".degreeSectionRequired").css("visibility","visible");
	    $(".degreeSection").css("color","");
	    $(".degree").css("pointer-events","auto");
	    //validate/content section
	    $("#degree").addClass("isRequired");
	}
    });
    //enable/disable Demographic Characteristics fields based on q.3
    $('input:radio[name=everBeenMarried]').change(function () {
	if ($("input[name='everBeenMarried']:checked").val() != 1) {
	    //css section
	    $(".everBeenMarriedSectionRequired").css("visibility","hidden");
	    $(".everBeenMarriedSection").css("color","rgba(0,0,0,0.26)");
	    $('#ageAtFirstMarriageInYears').css("pointer-events","none");
	    $("input[name='ageAtFirstMarriage']").attr("disabled","disabled");
	    $("input[name='everBeenWidowed']").attr("disabled","disabled");
	    $(".currentMaritalStatus").css("pointer-events","none");
	    //validate/content section
	    $("#ageAtFirstMarriageInYears").val("");
	    $('input[name="ageAtFirstMarriage"]:radio').prop('checked',false);
	    $('input[name="everBeenWidowed"]:radio').prop('checked',false);
	    $("#ageAtFirstMarriageInYears,#currentMaritalStatus").removeClass("isRequired");
	    $("input[name='ageAtFirstMarriage']").removeClass("isRequired");
	    $("input[name='everBeenWidowed']").removeClass("isRequired");
	}else{
	    //css section
	    $(".everBeenMarriedSectionRequired").css("visibility","visible");
	    $(".everBeenMarriedSection").css("color","");
	    $('#ageAtFirstMarriageInYears').css("pointer-events","auto");
	    $("input[name='ageAtFirstMarriage']").removeAttr("disabled");
	    $("input[name='everBeenWidowed']").removeAttr("disabled");
	    $(".currentMaritalStatus").css("pointer-events","auto");
	    //validate/content section
	    if($.trim($("#ageAtFirstMarriageInYears").val()) == '') { $("#ageAtFirstMarriageDK").addClass("isRequired"); }
	    $("#currentMaritalStatus").addClass("isRequired");
	    $("input[name='everBeenWidowed']").addClass("isRequired");
	}
    });
    
    //enable/disable Demographic Characteristics fields based on q.4
    $('input:radio[name=hasPatientEverBeenTestedforHIV]').change(function () {
	if ($("input[name='hasPatientEverBeenTestedforHIV']:checked").val() != 1) {
	    //css section
	    $(".everBeenTestedforHIVSectionRequired").css("visibility","hidden");
	    $(".everBeenTestedforHIVSection").css("color","rgba(0,0,0,0.26)");
	    $(".timeOfLastHIVTest").css("pointer-events","none");
	    $(".lastHIVTestStatus").css("pointer-events","none");
	    //validate/content section
	    $("#timeOfLastHIVTest,#lastHIVTestStatus").removeClass("isRequired");
	}else{
	    //css section
	    $(".everBeenTestedforHIVSectionRequired").css("visibility","visible");
	    $(".everBeenTestedforHIVSection").css("color","");
	    $(".timeOfLastHIVTest").css("pointer-events","auto");
	    $(".lastHIVTestStatus").css("pointer-events","auto");
	    //validate/content section
	    $("#timeOfLastHIVTest,#lastHIVTestStatus").addClass("isRequired");
	}
    });
    
    //partner HIV status
    $('#partnerHIVTestStatus').on('change',function() {
	if($.trim($('#partnerHIVTestStatus').val()) == 3){
	    $(".mainSexualPartnerSectionRequired").css("visibility","hidden");
	    $(".mainSexualPartnerSection").css("color","rgba(0,0,0,0.26)");
	    $(".mainSexualPartnerSection").css("pointer-events","none");
	    $('#ageOfMainSexualPartnerAtLastBirthdayInYears,#noOfTimesBeenPregnantInNumbers').val("");
	    $('input[name="ageOfMainSexualPartnerAtLastBirthday"]:radio').prop('checked',false);
	    $('input[name="isPartnerCircumcised"]:radio').prop('checked',false);
	    $('input[name="hasPatinetEverReceivedGiftForSex"]:radio').prop('checked',false);
	    $('input[name="noOfTimesBeenPregnant"]:radio').prop('checked',false);
	    $('input[name="noOfTimesCondomUsedBeforePregnancy"]:radio').prop('checked',false);
	    $('input[name="noOfTimesCondomUsedAfterPregnancy"]:radio').prop('checked',false);
	    $('#ageOfMainSexualPartnerAtLastBirthdayInYears,#ageDiffOfMainSexualPartner,#isPartnerCircumcisedYes,#circumcision,#hasPatinetEverReceivedGiftForSexYes,#lastTimeOfReceivingGiftForSex,#noOfTimesBeenPregnantInNumbers,#noOfTimesCondomUsedBeforePregnancyA,#noOfTimesCondomUsedAfterPregnancyA').removeClass("isRequired");
	}else{
	   $(".mainSexualPartnerSectionRequired").css("visibility","visible");
	   $(".mainSexualPartnerSection").css("color","");
	   $(".mainSexualPartnerSection").css("pointer-events","auto");
	   $('#ageOfMainSexualPartnerAtLastBirthdayInYears,#ageDiffOfMainSexualPartner,#isPartnerCircumcisedYes,#circumcision,#hasPatinetEverReceivedGiftForSexYes,#lastTimeOfReceivingGiftForSex,#noOfTimesBeenPregnantInNumbers,#noOfTimesCondomUsedBeforePregnancyA,#noOfTimesCondomUsedAfterPregnancyA').addClass("isRequired");
	}
    });
    
    //patient circumcision status
    $('input:radio[name=isPartnerCircumcised]').change(function () {
	if ($("input[name='isPartnerCircumcised']:checked").val() != 1) {
	    $(".circumcisionSectionRequired").css("visibility","hidden");
	    $(".circumcisionSection").css("color","rgba(0,0,0,0.26)");
	    $(".circumcisionSection").css("pointer-events","none");
	    $("#circumcision").removeClass("isRequired");
	}else{
	   $(".circumcisionSectionRequired").css("visibility","visible");
	   $(".circumcisionSection").css("color","");
	   $(".circumcisionSection").css("pointer-events","auto");
	   $("#circumcision").addClass("isRequired");
	}
    });
    
    //patient received gift for sex
    $('input:radio[name=hasPatinetEverReceivedGiftForSex]').change(function () {
	if ($("input[name='hasPatinetEverReceivedGiftForSex']:checked").val() != 1) {
	    $(".patinetReceivedGiftForSexSectionRequired").css("visibility","hidden");
	    $(".patinetReceivedGiftForSexSection").css("color","rgba(0,0,0,0.26)");
	    $(".patinetReceivedGiftForSexSection").css("pointer-events","none");
	    $("#lastTimeOfReceivingGiftForSex").removeClass("isRequired");
	}else{
	   $(".patinetReceivedGiftForSexSectionRequired").css("visibility","visible");
	   $(".patinetReceivedGiftForSexSection").css("color","");
	   $(".patinetReceivedGiftForSexSection").css("pointer-events","auto");
	   $("#lastTimeOfReceivingGiftForSex").addClass("isRequired");
	}
    });
    
    //treated for symptoms
    $('input:radio[name=hasPatientHadPainInLowerAbdomen]').change(function () {
	if ($("input[name='hasPatientHadPainInLowerAbdomen']:checked").val() != 1) {
	    $(".symptomsSectionRequired").css("visibility","hidden");
	    $(".symptomsSection").css("color","rgba(0,0,0,0.26)");
	    $(".symptomsSection").css("pointer-events","none");
	    $('input[name="hasPatientBeenTreatedForLowerAbdomenPain"]:radio').prop('checked',false);
	    $("#hasPatientBeenTreatedForLowerAbdomenPainYes").removeClass("isRequired");
	}else{
	    $(".symptomsSectionRequired").css("visibility","visible");
	    $(".symptomsSection").css("color","");
	    $(".symptomsSection").css("pointer-events","auto");
	    $("#hasPatientBeenTreatedForLowerAbdomenPainYes").addClass("isRequired");
	}
    });
    
    //recerational drugs
    $('input:radio[name=hasPatientEverTriedRecreationalDrugs]').change(function () {
	if ($("input[name='hasPatientEverTriedRecreationalDrugs']:checked").val() != 1) {
	    $(".recreationalDrugSectionRequired").css("visibility","hidden");
	    $(".recreationalDrugSection").css("color","rgba(0,0,0,0.26)");
	    $(".recreationalDrugSection").css("pointer-events","none");
	    $('input[name="hasPatientHadRecreationalDrugsInLastSixMonths"]:radio').prop('checked',false);
	    $("#hasPatientHadRecreationalDrugsInLastSixMonthsYes").removeClass("isRequired");
	}else{
	    $(".recreationalDrugSectionRequired").css("visibility","visible");
	    $(".recreationalDrugSection").css("color","");
	    $(".recreationalDrugSection").css("pointer-events","auto");
	    $("#hasPatientHadRecreationalDrugsInLastSixMonthsYes").addClass("isRequired");
	}
	setRecreationalDrugs();
    });
    
    $('input:radio[name=hasPatientHadRecreationalDrugsInLastSixMonths]').change(function () {
	setRecreationalDrugs();
    });
    
    function setRecreationalDrugs(){
	if ($("input[name='hasPatientHadRecreationalDrugsInLastSixMonths']:checked").val() == 1) {
            $('.recreationalDrugs').show();
            $('#recreationalDrugs').addClass('isRequired');
            $('#recreationalDrugs').focus();
        }else{
           $('.recreationalDrugs').hide();
           $('#recreationalDrugs').val('');
           $('#recreationalDrugs').removeClass('isRequired');
        }
    }
    
    //set age at very first sex
    $('#ageAtVeryFirstSexInNumbers').on('change',function() {
        ageAtVeryFirstSex('txt');
    });
    $('input:radio[name=ageAtVeryFirstSex]').change(function () {
	ageAtVeryFirstSex('rd');
    });
    function ageAtVeryFirstSex(fromSource){
	if(fromSource == 'txt'){
	    if($('#ageAtVeryFirstSexInNumbers').val()!= ''){
		$('input[name="ageAtVeryFirstSex"]:radio').prop('checked',false);
	    }
	    $('#ageAtVeryFirstSexInNumbers').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#ageAtVeryFirstSexInNumbers').val('');
	   $('#ageAtVeryFirstSexInNumbers').removeClass('isRequired');
	}
    }
    
    //set no.of times been pregnant
    $('#noOfTimesBeenPregnantInNumbers').on('change',function() {
        totalNoofPregnancy('txt');
    });
    $('input:radio[name=noOfTimesBeenPregnant]').change(function () {
	totalNoofPregnancy('rd');
    });
    function totalNoofPregnancy(fromSource){
	if(fromSource == 'txt'){
	    if($('#noOfTimesBeenPregnantInNumbers').val()!= ''){
		$('input[name="noOfTimesBeenPregnant"]:radio').prop('checked',false);
	    }
	    $('#noOfTimesBeenPregnantInNumbers').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#noOfTimesBeenPregnantInNumbers').val('');
	   $('#noOfTimesBeenPregnantInNumbers').removeClass('isRequired');
	}
    }
    
    //age range validation
    $('.years').on('change',function() {
	var years = $('#'+this.id).val();
	if(parseInt(years) < 1 || parseInt(years) > 100) { alert('Age range should be 1-100'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    //person range validation
    $('.persons').on('change',function() {
	var persons = $('#'+this.id).val();
	if(parseInt(persons) > 10000) { alert('Person range should be 0-10,000'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    //pregnancy range validation
    $('.times').on('change',function() {
	var times = $('#'+this.id).val();
	if(parseInt(times) > 15) { alert('Pregnancy range should be 0-15'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    //alcohol days range validation
    $('.days').on('change',function() {
	var days = $('#'+this.id).val();
	if(parseInt(days) > 185) { alert('Days can\'t be more than 185'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    //patient hurt/forced to have sex range validation
    $('.nooftimes').on('change',function() {
	var nooftimes = $('#'+this.id).val();
	if(parseInt(nooftimes) > 10000) { alert('No.of times range should be 0-10,000'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    function checkPatientRecord(){
	checkPatientBarcodeId();
    }
    
    function checkPatientBarcodeId(){
	var patientBarcodeId = $('#patientBarcodeId').val();
	var countryId = $('#chosenCountry').val();
        var optCountryId = ($('#country').length) ? $('#country').val():'';
	if($.trim(patientBarcodeId)!= '' && ($.trim(countryId)!= '' || $.trim(optCountryId)!= '')){
            $.post("<?php echo $this->url('check-patient-record'); ?>", {patientBarcodeId: patientBarcodeId,countryId:countryId,optCountryId:optCountryId,type:'clinic'},
            function(data) {
                if ($.trim(data)!= '') { $.blockUI(); document.location.href = data; }
            });
        }
    }
    
    function addRiskAssessment(){
        flag = deforayValidator.init({
            formId: 'addRiskAssessmentForm'
        });
	
        if(flag){
            document.getElementById('addRiskAssessmentForm').submit();
        }
    }
</script>