<?php
if(!isset($countryId) || trim($countryId)== ''){
    $countryId = '';
    $link = "/clinic/risk-assessment";
}else{
    $link = "/clinic/risk-assessment/".base64_encode($countryId);
}
?>
<style>
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        background-color: #eaeaea;
        border-bottom: 1px solid #ccc;
        padding: 10px 20px;
    }
    pre {
        max-height: 596px;
    }
    table.dataTable tbody td {
        padding: 8px 18px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        /*left: -184px*/
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Add Risk Assessment</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="/clinic/risk-assessment/<?php echo base64_encode($countryId); ?>" class="breadcrumb">Risk Assessment Form</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Add Risk Assessment</a>
       </div>
    </div>
    <div class="formContainer row dashboard-wrapper content-container" style="margin-bottom:20px;">
        <form id="addRiskAssessmentForm" name="addRiskAssessmentForm" method="post" action="<?php echo $this->url('add-clinic-risk-assessment',array('action'=>'add')); ?>">
        <div class="card">
            <h6 style="padding:10px 0px 10px 6px;"><strong>Sample Particpant Risk Questionnaire</strong></h6>
            <fieldset style="border-color:#2196F3;border-style:solid;">
                <?php
                if(trim($countryId) ==''){
                ?>
                    <div class="row" style="margin-bottom:0;">
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <select id="country" name="country" class="material-select isRequired" title="Please select country" onchange="getCountriesLabAnc();generateSurveillanceID(this);">
                                    <option value=""> -- Select -- </option>
                                    <?php
                                    foreach($countries as $country){
                                    ?>
                                      <option data-code="<?php echo $country['country_code']; ?>" value="<?php echo base64_encode($country['country_id']); ?>"><?php echo ucwords($country['country_name']); ?></option>
                                    <?php } ?>
                                </select>
                                <label for="country">Country *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <select id="lab" name="lab" class="material-select isRequired" title="Please select facility">
                                    <option value=""> -- Select -- </option>
                                    <?php
				    foreach($facilities as $facility){
				    ?>
				      <option value="<?php echo base64_encode($facility['facility_id']); ?>"><?php echo $facility['facility_code'].' - '.ucwords($facility['facility_name']); ?></option>
				    <?php } ?>
                                </select>
                                <label for="lab">Name of Facility *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="studyId" name="studyId" type="text" class="validate isRequired" title="Please enter study ID">
                                <label for="studyId" class="">Study ID *</label>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="margin-bottom:0;">
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="interviewerName" name="interviewerName" type="text" class="validate isRequired" title="Please enter interviewer name">
                                <label for="interviewerName" class="">Interviewer Name *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="ancPatientId" name="ancPatientId" type="text" class="validate isRequired" title="Please enter anc patient ID" onblur="checkPatientRecord()">
                                <label for="ancPatientId" class="">ANC Patient ID *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="interviewDate" name="interviewDate" type="text" class="validate isRequired datepicker" title="Please enter interview date">
                                <label for="interviewDate" class="">Interview Date *</label>
                            </div>
                        </div>
                    </div>
                <?php } else { ?>
                    <div class="row" style="margin-bottom:0;">
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <select id="lab" name="lab" class="material-select isRequired" title="Please select facility">
                                    <option value=""> -- Select -- </option>
                                    <?php
				    foreach($facilities as $facility){
				    ?>
				      <option value="<?php echo base64_encode($facility['facility_id']); ?>"><?php echo $facility['facility_code'].' - '.ucwords($facility['facility_name']); ?></option>
				    <?php } ?>
                                </select>
                                <label for="ancSite">Name of Facility *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="studyId" name="studyId" type="text" class="validate isRequired" title="Please enter study ID">
                                <label for="studyId" class="">Study ID *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="interviewerName" name="interviewerName" type="text" class="validate isRequired" title="Please enter interviewer name">
                                <label for="interviewerName" class="">Interviewer Name *</label>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="margin-bottom:0;">
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="ancPatientId" name="ancPatientId" type="text" class="validate isRequired" title="Please enter anc patient ID" onblur="checkPatientRecord()">
                                <label for="ancPatientId" class="">ANC Patient ID *</label>
                            </div>
                        </div>
                        <div class="col s4">
                            <div class="input-field col m12 s12">
                                <input id="interviewDate" name="interviewDate" type="text" class="validate isRequired datepicker" title="Please enter interview date">
                                <label for="interviewDate" class="">Interview Date *</label>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </fieldset>
            <h6 style="padding:10px 0px 10px 6px;"><strong>Demographic Characteristics</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    1. What kind of work/occupation do you do most of the time? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="occupation" name="occupation" class="material-select isRequired" title="Don't leave 1st question">
                        <option value=""> -- Select -- </option>
                        <?php
			foreach($occupationTypes as $occupation){
			?>
                           <option value="<?php echo base64_encode($occupation['occupation_id']); ?>"><?php echo ucwords($occupation['occupation']); ?></option>
			<?php } ?>
                        <option value="other">Other</option>
                    </select>
                </div>
		<div class="col s4 occupationNew" style="display:none;">
		    <input id="occupationNew" name="occupationNew" type="text" class="validate" placeholder="Occupation" title="Please enter occupation" onblur="checkNameValidation('occupation_type', 'occupation', this, null,'The occupation that you entered already listed. Please enter different occupation');">
		</div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    2. What was the highest level of school that you completed or are attending now? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="degree" name="degree" class="material-select isRequired" title="Don't leave 2nd question">
                        <option value=""> -- Select -- </option>
                        <option value="noedu">No Education</option>
                        <option value="primary">Primary/Post-Primary/Vocational</option>
                        <option value="secondary">Secondary/Post-Secondary</option>
                        <option value="university">University/College</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    3. Have you ever been married or lived with a partner in a union as if married? * &nbsp;(If no, go to question 7)
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s4">
                    <input id="areMarriedYes" class="with-gap isRequired" name="areMarried" title="Don't leave 3rd question" value="yes" type="radio">
		    <label for="areMarriedYes" class="active">Yes </label>&nbsp&nbsp
                    <input id="areMarriedNo" class="with-gap" name="areMarried" value="no" type="radio">
		    <label for="areMarriedNo" class="active">No </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    4. How old were you when you first got married or lived with a partner in a union? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s8">
                    <input id="ageAtFirstMarriageInYears" name="ageAtFirstMarriageInYears" type="text" class="validate isRequired checkNum" title="Please enter years" style="width:10%;"> Years&nbsp;
                    <input id="ageAtFirstMarriageDK" class="with-gap" name="ageAtFirstMarriage" value="dontknow" type="radio">
		    <label for="ageAtFirstMarriageDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="ageAtFirstMarriageR" class="with-gap" name="ageAtFirstMarriage" value="refused" type="radio">
		    <label for="ageAtFirstMarriageR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    5. Have you ever been widowed? That is, did a spouse ever pass away while you were still married or living with them? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s6">
                    <input id="haveEverBeenWidowedYes" class="with-gap isRequired" name="haveEverBeenWidowed" title="Don't leave 5th question" value="yes" type="radio">
		    <label for="haveEverBeenWidowedYes" class="active">Yes </label>&nbsp&nbsp
                    <input id="haveEverBeenWidowedNo" class="with-gap" name="haveEverBeenWidowed" value="no" type="radio">
		    <label for="haveEverBeenWidowedNo" class="active">No </label>&nbsp&nbsp
                    <input id="haveEverBeenWidowedDK" class="with-gap" name="haveEverBeenWidowed" value="dontknow" type="radio">
		    <label for="haveEverBeenWidowedDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="haveEverBeenWidowedR" class="with-gap" name="haveEverBeenWidowed" value="refused" type="radio">
		    <label for="haveEverBeenWidowedR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    6. What is your marital status now? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="currentMaritalStatus" name="currentMaritalStatus" class="material-select isRequired" title="Don't leave 6th question">
                        <option value=""> -- Select -- </option>
                        <option value="married">Married/Cohabiting</option>
                        <option value="nevermarried">Never Married/Cohabiting</option>
                        <option value="widowed">widowed</option>
                        <option value="separated">Separated</option>
                        <option value="divorced">Divorced</option>
                        <option value="dontknow">Don't Know</option>
                        <option value="refused">Refused</option>
                    </select>
                </div>
            </div>
            <h6 style="padding:0px 0px 10px 6px;"><strong>HIV Testing History</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    7. When was the most recent time you were tested for HIV? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="timeOfLastHIVTest" name="timeOfLastHIVTest" class="material-select isRequired" title="Don't leave 7th question">
                        <option value=""> -- Select -- </option>
                        <option value="nevertested">Never Tested</option>
                        <option value="lt3months">< 3 Months Ago</option>
                        <option value="3to6months">3-6 Months Ago</option>
                        <option value="7to12months">7-12 Months Ago</option>
                        <option value="gt12months"> > 12 months</option>
                        <option value="dontknow">Don't Know</option>
                        <option value="refused">Refused</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    8. What was the result of that HIV test? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="lastHIVTestStatus" name="lastHIVTestStatus" class="material-select isRequired" title="Don't leave 8th question">
                        <option value=""> -- Select -- </option>
                        <option value="didnotreceive">I Did Not Receive Result</option>
                        <option value="hivplus">HIV+</option>
                        <option value="hivminus">HIV-</option>
                        <option value="indeterminate">Indeterminate</option>
                        <option value="dontknow">Don't Know</option>
                        <option value="refused">Refused</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    9. What is your spouse/main sexual partner's HIV status? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="partnerHIVTestStatus" name="partnerHIVTestStatus" class="material-select isRequired" title="Don't leave 9th question">
                        <option value=""> -- Select -- </option>
                        <option value="hivplus">HIV+</option>
                        <option value="hivminus">HIV-</option>
                        <option value="idonotknow">I Do Not Know</option>
                        <option value="refused">Refused</option>
                    </select>
                </div>
            </div>
            <h6 style="padding:0px 0px 10px 6px;"><strong>Sexual Activity and History of Sexually Transmitted Infections</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    10. How old were you when you had sexual intercourse for the very first time? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <input id="ageAtVeryFirstSex" name="ageAtVeryFirstSex" type="text" class="validate isRequired checkNum" title="Please enter years" style="width:20%;"> Years
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    11. The first time you had sex, was it because you wanted to or because you were forced to? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s6">
                    <input id="reasonForVeryFirstSexWT" class="with-gap isRequired" name="reasonForVeryFirstSex" title="Don't leave 11th question" value="wantedto" type="radio">
		    <label for="reasonForVeryFirstSexWT" class="active">Wanted To </label>&nbsp&nbsp
                    <input id="reasonForVeryFirstSexFT" class="with-gap" name="reasonForVeryFirstSex" value="forcedto" type="radio">
		    <label for="reasonForVeryFirstSexFT" class="active">Forced To </label>&nbsp&nbsp
                    <input id="reasonForVeryFirstSexDK" class="with-gap" name="reasonForVeryFirstSex" value="dontknow" type="radio">
		    <label for="reasonForVeryFirstSexDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="reasonForVeryFirstSexR" class="with-gap" name="reasonForVeryFirstSex" value="refused" type="radio">
		    <label for="reasonForVeryFirstSexR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    12. How many different people have you had sexual intercourse with in your entire life? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s6">
                    <input id="noOfSexualPartnersInNumbers" name="noOfSexualPartnersInNumbers" type="text" class="validate isRequired checkNum" title="Please enter no. of persons" style="width:10%;"> Persons&nbsp;
                    <input id="noOfSexualPartnersDK" class="with-gap" name="noOfSexualPartners" value="dontknow" type="radio">
		    <label for="noOfSexualPartnersDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="noOfSexualPartnersR" class="with-gap" name="noOfSexualPartners" value="refused" type="radio">
		    <label for="noOfSexualPartnersR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    13. How many different people have you had sex with in the last 6 months? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s6">
                    <input id="noOfSexualPartnersInLastSixMonthsInNumbers" name="noOfSexualPartnersInLastSixMonthsInNumbers" type="text" class="validate isRequired checkNum" title="Please enter no. of persons" style="width:10%;"> Persons&nbsp;
                    <input id="noOfSexualPartnersInLastSixMonthsDK" class="with-gap" name="noOfSexualPartnersInLastSixMonths" value="dontknow" type="radio">
		    <label for="noOfSexualPartnersInLastSixMonthsDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="noOfSexualPartnersInLastSixMonthsR" class="with-gap" name="noOfSexualPartnersInLastSixMonths" value="refused" type="radio">
		    <label for="noOfSexualPartnersInLastSixMonthsR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    14. How old was your main sexual partner on his last birthday? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s6">
                    <input id="ageOfMainSexualPartnerAtLastBirthdayInYears" name="ageOfMainSexualPartnerAtLastBirthdayInYears" type="text" class="validate isRequired checkNum" title="Please enter years" style="width:10%;"> Years&nbsp;
                    <input id="ageOfMainSexualPartnerAtLastBirthdayDK" class="with-gap" name="ageOfMainSexualPartnerAtLastBirthday" value="dontknow" type="radio">
		    <label for="ageOfMainSexualPartnerAtLastBirthdayDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="ageOfMainSexualPartnerAtLastBirthdayR" class="with-gap" name="ageOfMainSexualPartnerAtLastBirthday" value="refused" type="radio">
		    <label for="ageOfMainSexualPartnerAtLastBirthdayR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    15. Is the age of your main sexual partner older, younger, or the same age as you? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="ageDiffOfMainSexualPartner" name="ageDiffOfMainSexualPartner" class="material-select isRequired" title="Don't leave 15th question">
                        <option value=""> -- Select -- </option>
                        <option value="lt5yearolder"> < 5 Years Older</option>
                        <option value="5to10yearolder"> 5-10 Years Older</option>
                        <option value="10yearsolder"> >10 Years Older</option>
                        <option value="sameage">Same Age</option>
                        <option value="lt5yearyounger"> < 5 Years Younger</option>
                        <option value="5to10yearyounger">5-10 Years Younger</option>
                        <option value="gt10yearyounger"> >10 Years Younger</option>
                        <option value="dontknow">Don't Know</option>
                        <option value="refused">Refused</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    16. Is your main sexual partner circumcised? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s6">
                    <input id="isPartnerCircumcisedYes" class="with-gap isRequired" name="isPartnerCircumcised" title="Don't leave 16th question" value="yes" type="radio">
		    <label for="isPartnerCircumcisedYes" class="active">Yes </label>&nbsp&nbsp
                    <input id="isPartnerCircumcisedNo" class="with-gap" name="isPartnerCircumcised" value="no" type="radio">
		    <label for="isPartnerCircumcisedNo" class="active">No </label>&nbsp&nbsp
                    <input id="isPartnerCircumcisedDK" class="with-gap" name="isPartnerCircumcised" value="dontknow" type="radio">
		    <label for="isPartnerCircumcisedDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="isPartnerCircumcisedR" class="with-gap" name="isPartnerCircumcised" value="refused" type="radio">
		    <label for="isPartnerCircumcisedR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    17. When did you last receive money/gifts in exchange for sex? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="lastTimeOfReceivingMoneyForSex" name="lastTimeOfReceivingMoneyForSex" class="material-select isRequired" title="Don't leave 17th question">
                        <option value=""> -- Select -- </option>
                        <option value="never"> Never</option>
                        <option value="lt6months"> < 6 Months Ago</option>
                        <option value="6to12months"> 6-12 Months Ago</option>
                        <option value="gt12months"> > 12 Months Ago</option>
                        <option value="dontknow">Don't Know</option>
                        <option value="refused">Refused</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    18. How many times have you been pregnant? * (including this pregnancy)
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <input id="noOfTimesBeenPregnant" name="noOfTimesBeenPregnant" type="text" class="validate isRequired checkNum" title="Don't leave 18th question" style="width:20%;"> Times
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    19. Before becoming pregnant this time, in the past year how frequently did you use a condom when having sexual intercourse? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s8">
                    <input id="noOfTimesCondomUsedBeforePregnancyA" class="with-gap isRequired" name="noOfTimesCondomUsedBeforePregnancy" title="Don't leave 19th question" value="always" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyA" class="active">Always </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedBeforePregnancyS" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="sometimes" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyS" class="active">Sometimes </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedBeforePregnancyN" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="never" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyN" class="active">Never </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedBeforePregnancyDK" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="dontknow" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedBeforePregnancyR" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="refused" type="radio">
		    <label for="noOfTimesCondomUsedBeforePregnancyR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    20. Since becoming pregnant this time, how frequently have you used a condom when having sexual intercourse? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s8">
                    <input id="noOfTimesCondomUsedAfterPregnancyA" class="with-gap isRequired" name="noOfTimesCondomUsedAfterPregnancy" title="Don't leave 20th question" value="always" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyA" class="active">Always </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedAfterPregnancyS" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="sometimes" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyS" class="active">Sometimes </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedAfterPregnancyN" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="never" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyN" class="active">Never </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedAfterPregnancyDK" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="dontknow" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedAfterPregnancyR" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="refused" type="radio">
		    <label for="noOfTimesCondomUsedAfterPregnancyR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    21. In the past year, did you have symptoms such as genital discharge, sores in your genital area, pain during urination, or pain in your lower abdomen? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s6">
                    <input id="havePainInLowerAbdomenYes" class="with-gap isRequired" name="havePainInLowerAbdomen" title="Don't leave 21st question" value="yes" type="radio">
		    <label for="havePainInLowerAbdomenYes" class="active">Yes </label>&nbsp&nbsp
                    <input id="havePainInLowerAbdomenNo" class="with-gap" name="havePainInLowerAbdomen" value="no" type="radio">
		    <label for="havePainInLowerAbdomenNo" class="active">No </label>&nbsp&nbsp
                    <input id="havePainInLowerAbdomenDK" class="with-gap" name="havePainInLowerAbdomen" value="dontknow" type="radio">
		    <label for="havePainInLowerAbdomenDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="havePainInLowerAbdomenR" class="with-gap" name="havePainInLowerAbdomen" value="refused" type="radio">
		    <label for="havePainInLowerAbdomenR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    22. If yes, were you treated for these symptoms? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s6">
                    <input id="haveTreatedForLowerAbdomenPainYes" class="with-gap isRequired" name="haveTreatedForLowerAbdomenPain" title="Don't leave 22nd question" value="yes" type="radio">
		    <label for="haveTreatedForLowerAbdomenPainYes" class="active">Yes </label>&nbsp&nbsp
                    <input id="haveTreatedForLowerAbdomenPainNo" class="with-gap" name="haveTreatedForLowerAbdomenPain" value="no" type="radio">
		    <label for="haveTreatedForLowerAbdomenPainNo" class="active">No </label>&nbsp&nbsp
                    <input id="haveTreatedForLowerAbdomenPainDK" class="with-gap" name="haveTreatedForLowerAbdomenPain" value="dontknow" type="radio">
		    <label for="haveTreatedForLowerAbdomenPainDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="haveTreatedForLowerAbdomenPainR" class="with-gap" name="haveTreatedForLowerAbdomenPain" value="refused" type="radio">
		    <label for="haveTreatedForLowerAbdomenPainR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    23. Have you ever been diagnosed or treated for syphilis? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s6">
                    <input id="haveTreatedForSyphilisyes" class="with-gap isRequired" name="haveTreatedForSyphilis" title="Don't leave 23rd question" value="yes" type="radio">
		    <label for="haveTreatedForSyphilisYes" class="active">Yes </label>&nbsp&nbsp
                    <input id="haveTreatedForSyphilisNo" class="with-gap" name="haveTreatedForSyphilis" value="no" type="radio">
		    <label for="haveTreatedForSyphilisNo" class="active">No </label>&nbsp&nbsp
                    <input id="haveTreatedForSyphilisDK" class="with-gap" name="haveTreatedForSyphilis" value="dontknow" type="radio">
		    <label for="haveTreatedForSyphilisDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="haveTreatedForSyphilisR" class="with-gap" name="haveTreatedForSyphilis" value="refused" type="radio">
		    <label for="haveTreatedForSyphilisR" class="active">Refused </label>
                </div>
            </div>
            <h6 style="padding:10px 0px 10px 6px;"><strong>Alcohol and drug use</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    24. During the past 6 months, on how many days did you have at least one drink containing alcohol? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s8">
                    <input id="noOfDaysHadDrinkInLastSixMonthsInDays" name="noOfDaysHadDrinkInLastSixMonthsInDays" type="text" class="validate isRequired checkNum" title="Please enter no. of days" style="width:10%;"> Days&nbsp;
                    <input id="noOfDaysHadDrinkInLastSixMonthsNot" class="with-gap" name="noOfDaysHadDrinkInLastSixMonths" value="havenotdrink" type="radio">
		    <label for="noOfDaysHadDrinkInLastSixMonthsNot" class="active">Haven't Had a Drink </label>&nbsp&nbsp
                    <input id="noOfDaysHadDrinkInLastSixMonthsDK" class="with-gap" name="noOfDaysHadDrinkInLastSixMonths" value="dontknow" type="radio">
		    <label for="noOfDaysHadDrinkInLastSixMonthsDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="noOfDaysHadDrinkInLastSixMonthsR" class="with-gap" name="noOfDaysHadDrinkInLastSixMonths" value="refusedtoanswer" type="radio">
		    <label for="noOfDaysHadDrinkInLastSixMonthsR" class="active">Refused To Answer</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    25. How often do you have 4 or more drinks with alcohol on one occasion * (e.g. within 2 hours)?
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="doHaveMoreDrinksOnOneOccasion" name="doHaveMoreDrinksOnOneOccasion" class="material-select isRequired" title="Don't leave 25th question">
                        <option value=""> -- Select -- </option>
                        <option value="never">Never</option>
                        <option value="monthly">Monthly</option>
                        <option value="weekly">Weekly</option>
                        <option value="daily">Daily or On Most Days of The Week</option>
                        <option value="dontknow">Don't Know</option>
                        <option value="refused">Refused</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    26. Have you ever tried recreational drugs? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s8">
                    <input id="haveTriedRecreationalDrugsYes" class="with-gap isRequired" name="haveTriedRecreationalDrugs" title="Don't leave 26th question" value="yes" type="radio">
		    <label for="haveTriedRecreationalDrugsYes" class="active">Yes </label>&nbsp&nbsp
                    <input id="haveTriedRecreationalDrugsNo" class="with-gap" name="haveTriedRecreationalDrugs" value="no" type="radio">
		    <label for="haveTriedRecreationalDrugsNo" class="active">No </label>&nbsp&nbsp
                    <input id="haveTriedRecreationalDrugsDK" class="with-gap" name="haveTriedRecreationalDrugs" value="dontknow" type="radio">
		    <label for="haveTriedRecreationalDrugsDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="haveTriedRecreationalDrugsR" class="with-gap" name="haveTriedRecreationalDrugs" value="refused" type="radio">
		    <label for="haveTriedRecreationalDrugsR" class="active">Refused</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    27. In the last 6 months, have you taken any recreational drugs? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12" style="margin-bottom:20px;">
                    <input id="hadRecreationalDrugsInLastSixMonthsYes" class="with-gap isRequired" name="hadRecreationalDrugsInLastSixMonths" title="Don't leave 27th question" value="yes" type="radio">
		    <label for="hadRecreationalDrugsInLastSixMonthsYes" class="active">Yes </label>&nbsp&nbsp
                    <span class="recreationalDrugs" style="display:none;">Specify Drug(s) <input id="recreationalDrugs" name="recreationalDrugs" type="text" class="validate" title="Please enter recreational drugs" style="width:30%;">&nbsp;</span>
                    <input id="hadRecreationalDrugsInLastSixMonthsNo" class="with-gap" name="hadRecreationalDrugsInLastSixMonths" value="no" type="radio">
		    <label for="hadRecreationalDrugsInLastSixMonthsNo" class="active">No </label>&nbsp&nbsp
                    <input id="hadRecreationalDrugsInLastSixMonthsDK" class="with-gap" name="hadRecreationalDrugsInLastSixMonths" value="dontknow" type="radio">
		    <label for="hadRecreationalDrugsInLastSixMonthsDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="hadRecreationalDrugsInLastSixMonthsR" class="with-gap" name="hadRecreationalDrugsInLastSixMonths" value="refused" type="radio">
		    <label for="hadRecreationalDrugsInLastSixMonthsR" class="active">Refused</label>
                </div>
            </div>
            <div class="col s12" style="margin-top:20px;">
                <input type="hidden" name="chosenCountry" id="chosenCountry" value="<?php echo base64_encode($countryId);?>"/>
                <input type="hidden" name="redirectUrl" id="redirectUrl" value="<?php echo $link;?>"/>
                <a href="<?php echo $link;?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addRiskAssessment();">ADD</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/moment.min.js' ?>"></script>
<script>
    $(document).ready(function(){
       $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 15, // Creates a dropdown of 15 years to control year
            format: 'dd/mm/yyyy',
	    max: new Date('Today')
        });
    });
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if(checkValue!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
    
    //occupation
    $('#occupation').on('change',function(){
	if(this.value == 'other'){
	    $('.occupationNew').show();
	    $('#occupationNew').addClass('isRequired');
	    $('#occupationNew').focus();
	}else{
	   $('.occupationNew').hide();
	   $('#occupationNew').removeClass('isRequired'); 
	}
    });
    
    //age at first marriage
    $('#ageAtFirstMarriageInYears').on('change',function() {
	setAgeAtFirstMarriage('txt');
    });
    $('input:radio[name=ageAtFirstMarriage]').change(function () {
	setAgeAtFirstMarriage('rd');
    });
    
    function setAgeAtFirstMarriage(fromSource){
	if(fromSource == 'txt'){
	    if($('#ageAtFirstMarriageInYears').val()!= ''){
		$('#ageAtFirstMarriageDK').prop('checked',false);
		$('#ageAtFirstMarriageR').prop('checked',false);
	    }
	    $('#ageAtFirstMarriageInYears').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#ageAtFirstMarriageInYears').val('');
	   $('#ageAtFirstMarriageInYears').removeClass('isRequired');
	}
    }
    
    //no.of sexual partners
    $('#noOfSexualPartnersInNumbers').on('change',function() {
	setNoOfSexualPartners('txt');
    });
    $('input:radio[name=noOfSexualPartners]').change(function () {
	setNoOfSexualPartners('rd');
    });
    function setNoOfSexualPartners(fromSource){
	if(fromSource == 'txt'){
	    if($('#noOfSexualPartnersInNumbers').val()!= ''){
		$('#noOfSexualPartnersDK').prop('checked',false);
		$('#noOfSexualPartnersR').prop('checked',false);
	    }
	    $('#noOfSexualPartnersInNumbers').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#noOfSexualPartnersInNumbers').val('');
	   $('#noOfSexualPartnersInNumbers').removeClass('isRequired');
	}
    }
    
    //no.of sexual partners in last six months
    $('#noOfSexualPartnersInLastSixMonthsInNumbers').on('change',function() {
	setNoOfSexualPartnersInLastSixMonths('txt');
    });
    $('input:radio[name=noOfSexualPartnersInLastSixMonths]').change(function () {
	setNoOfSexualPartnersInLastSixMonths('rd');
    });
    function setNoOfSexualPartnersInLastSixMonths(fromSource){
	if(fromSource == 'txt'){
	    if($('#noOfSexualPartnersInLastSixMonthsInNumbers').val()!= ''){
		$('#noOfSexualPartnersInLastSixMonthsDK').prop('checked',false);
		$('#noOfSexualPartnersInLastSixMonthsR').prop('checked',false);
	    }
	    $('#noOfSexualPartnersInLastSixMonthsInNumbers').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#noOfSexualPartnersInLastSixMonthsInNumbers').val('');
	   $('#noOfSexualPartnersInLastSixMonthsInNumbers').removeClass('isRequired');
	}
    }
    
    //main sexual partner age at last birthday
    $('#ageOfMainSexualPartnerAtLastBirthdayInYears').on('change',function() {
	mainSexualPartnerAgeAtLastBirthday('txt');
    });
    $('input:radio[name=ageOfMainSexualPartnerAtLastBirthday]').change(function () {
	mainSexualPartnerAgeAtLastBirthday('rd');
    });
    function mainSexualPartnerAgeAtLastBirthday(fromSource){
	if(fromSource == 'txt'){
	    if($('#ageOfMainSexualPartnerAtLastBirthdayInYears').val()!= ''){
		$('#ageOfMainSexualPartnerAtLastBirthdayDK').prop('checked',false);
		$('#ageOfMainSexualPartnerAtLastBirthdayR').prop('checked',false);
	    }
	    $('#ageOfMainSexualPartnerAtLastBirthdayInYears').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#ageOfMainSexualPartnerAtLastBirthdayInYears').val('');
	   $('#ageOfMainSexualPartnerAtLastBirthdayInYears').removeClass('isRequired');
	}
    }
    
    //no.of days had drinks in last six month
    $('#noOfDaysHadDrinkInLastSixMonthsInDays').on('change',function() {
        noOfDaysHadDrinkInLastSixMonth('txt');
    });
    $('input:radio[name=noOfDaysHadDrinkInLastSixMonths]').change(function () {
	noOfDaysHadDrinkInLastSixMonth('rd');
    });
    function noOfDaysHadDrinkInLastSixMonth(fromSource){
	if(fromSource == 'txt'){
	    if($('#noOfDaysHadDrinkInLastSixMonthsInDays').val()!= ''){
		$('#noOfDaysHadDrinkInLastSixMonthsNot').prop('checked',false);
		$('#noOfDaysHadDrinkInLastSixMonthsDK').prop('checked',false);
		$('#noOfDaysHadDrinkInLastSixMonthsR').prop('checked',false);
	    }
	    $('#noOfDaysHadDrinkInLastSixMonthsInDays').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#noOfDaysHadDrinkInLastSixMonthsInDays').val('');
	   $('#noOfDaysHadDrinkInLastSixMonthsInDays').removeClass('isRequired');
	}
    }
    
    //had drugs in last six months
    $('input:radio[name=hadRecreationalDrugsInLastSixMonths]').change(function () {
	if ($("input[name='hadRecreationalDrugsInLastSixMonths']:checked").val() == 'yes') {
            $('.recreationalDrugs').show();
            $('#recreationalDrugs').addClass('isRequired');
            $('#recreationalDrugs').focus();
        }else{
           $('.recreationalDrugs').hide();
           $('#recreationalDrugs').val('');
           $('#recreationalDrugs').removeClass('isRequired');
        }
    });
    
    function addRiskAssessment(){
        flag = deforayValidator.init({
            formId: 'addRiskAssessmentForm'
        });
	
        if(flag){
            document.getElementById('addRiskAssessmentForm').submit();
        }
    }
	function checkPatientRecord(){
        var patientId = $('#ancPatientId').val();
		var countryId = $('#chosenCountry').val();
        var dbCountryId = ($('#country').length) ? $('#country').val():'';
        if($.trim(patientId)!=''){
            $.post("<?php echo $this->url('check-patient-record'); ?>", {patientId: patientId,countryId:countryId,dbCountryId:dbCountryId,clinic:'clinic'},
            function(data) {
                if (data!= '') {
					conf = confirm("This Patient "+$('#ancPatientId').val()+" already has risk assessment form submitted. Please click OK if you want to continue editing for this particular patient");
					(conf)?document.location.href=data:$('#ancPatientId').val('');
                }
            });
        }
    }
</script>