<?php
use Application\Service\CommonService;
$common = new CommonService();
if(trim($countryId)!= ''){
    $link = "/clinic/risk-assessment/".base64_encode($countryId);
}else{
   $link = "/clinic/risk-assessment";
}
$interviewDate = '';
if($row->interview_date!= null && trim($row->interview_date)!= '' && $row->interview_date!= '0000-00-00'){
    $interviewDate = $common->viewDateFormat($row->interview_date);
}
//recreational drugs
$hasPatientHadRecreationalDrugsInLastSixMonths = '';
$recreationalDrugs = '';
if($row->has_patient_had_recreational_drugs_in_last_six_months!= null && trim($row->has_patient_had_recreational_drugs_in_last_six_months)!= ''){
    $recreationaldata = json_decode($row->has_patient_had_recreational_drugs_in_last_six_months,true);
    $hasPatientHadRecreationalDrugsInLastSixMonths = (isset($recreationaldata['has_had_in_last_six_months']))?$recreationaldata['has_had_in_last_six_months']:'';
    $recreationalDrugs = (isset($recreationaldata['drugs']))?$recreationaldata['drugs']:'';
}
//patient abused by
$hasPatientAbusedBy = '';
$patientAbusedBy = array();
$patientAbusedByOther = '';
$patientAbusedByInNoofTimes = '';
if($row->has_patient_ever_been_abused_by_someone!= null && trim($row->has_patient_ever_been_abused_by_someone)!= ''){
    $patientAbusedBydata = json_decode($row->has_patient_ever_been_abused_by_someone,true);
    $hasPatientAbusedBy = (isset($patientAbusedBydata['ever_abused']))?(int)$patientAbusedBydata['ever_abused']:'';
    $patientAbusedByInNoofTimes = (isset($patientAbusedBydata['no_of_times']))?$patientAbusedBydata['no_of_times']:'';
    if(isset($patientAbusedBydata['who_abused']) && trim($patientAbusedBydata['who_abused'])!= '' && $patientAbusedBydata['who_abused'][0] == '@'){
        $patientAbusedByOther = substr($patientAbusedBydata['who_abused'],1);
    }else if(isset($patientAbusedBydata['who_abused']) && trim($patientAbusedBydata['who_abused'])!= ''){
        $patientAbusedBy = explode(',',$patientAbusedBydata['who_abused']);
    }
}
//patient hurt by someone within last year
$hasPatientHurtByWithinLastYear = '';
$patientHurtByWithinLastYear = array();
$patientHurtByOtherWithinLastYear = '';
$patientHurtByInNoofTimes = '';
if($row->has_patient_ever_been_hurt_by_someone_within_last_year!= null && trim($row->has_patient_ever_been_hurt_by_someone_within_last_year)!= ''){
    $patientHurtBydata = json_decode($row->has_patient_ever_been_hurt_by_someone_within_last_year,true);
    $hasPatientHurtByWithinLastYear = (isset($patientHurtBydata['ever_hurt']))?(int)$patientHurtBydata['ever_hurt']:'';
    $patientHurtByInNoofTimes = (isset($patientHurtBydata['no_of_times']))?$patientHurtBydata['no_of_times']:'';
    if(isset($patientHurtBydata['who_hurt']) && trim($patientHurtBydata['who_hurt'])!= '' && $patientHurtBydata['who_hurt'][0] == '@'){
        $patientHurtByOtherWithinLastYear = substr($patientHurtBydata['who_hurt'],1);
    }else if(isset($patientHurtBydata['who_hurt']) && trim($patientHurtBydata['who_hurt'])!= ''){
        $patientHurtByWithinLastYear = explode(',',$patientHurtBydata['who_hurt']);
    }
}
//patient hurt by someone during pregnancy
$hasPatientHurtByDuringPregnancy = '';
$patientHurtByDuringPregnancy = array();
$patientHurtByOtherDuringPregnancy = '';
$patientHurtByDuringPregnancyInNoofTimes = '';
if(trim($hasPatientHurtByWithinLastYear) == 1 && $row->has_patient_ever_been_hurt_by_someone_during_pregnancy!= null && trim($row->has_patient_ever_been_hurt_by_someone_during_pregnancy)!= ''){
    $patientHurtByDuringPregnancydata = json_decode($row->has_patient_ever_been_hurt_by_someone_during_pregnancy,true);
    $hasPatientHurtByDuringPregnancy = (isset($patientHurtByDuringPregnancydata['ever_hurt_by_during_pregnancy']))?(int)$patientHurtByDuringPregnancydata['ever_hurt_by_during_pregnancy']:'';
    $patientHurtByDuringPregnancyInNoofTimes = (isset($patientHurtByDuringPregnancydata['no_of_times']))?$patientHurtByDuringPregnancydata['no_of_times']:'';
    if(isset($patientHurtByDuringPregnancydata['who_hurt']) && trim($patientHurtByDuringPregnancydata['who_hurt'])!= '' && $patientHurtByDuringPregnancydata['who_hurt'][0] == '@'){
        $patientHurtByOtherDuringPregnancy = substr($patientHurtByDuringPregnancydata['who_hurt'],1);
    }else if(isset($patientHurtByDuringPregnancydata['who_hurt']) && trim($patientHurtByDuringPregnancydata['who_hurt'])!= ''){
        $patientHurtByDuringPregnancy = explode(',',$patientHurtByDuringPregnancydata['who_hurt']);
    }
}
//patient forced for sex within last year
$hasPatientForcedforSexWithinLastYear = '';
$patientForcedforSexBy = array();
$patientForcedforSexByOther = '';
$patientForcedforSexInNoofTimes = '';
if($row->has_patient_ever_been_forced_for_sex_within_last_year!= null && trim($row->has_patient_ever_been_forced_for_sex_within_last_year)!= ''){
    $patientForcedforSexdata = json_decode($row->has_patient_ever_been_forced_for_sex_within_last_year,true);
    $hasPatientForcedforSexWithinLastYear = (isset($patientForcedforSexdata['ever_forced_for_sex']))?(int)$patientForcedforSexdata['ever_forced_for_sex']:'';
    $patientForcedforSexInNoofTimes = (isset($patientForcedforSexdata['no_of_times']))?$patientForcedforSexdata['no_of_times']:'';
    if(isset($patientForcedforSexdata['who_forced']) && trim($patientForcedforSexdata['who_forced'])!= '' && $patientForcedforSexdata['who_forced'][0] == '@'){
        $patientForcedforSexByOther = substr($patientForcedforSexdata['who_forced'],1);
    }else if(isset($patientForcedforSexdata['who_forced']) && trim($patientForcedforSexdata['who_forced'])!= ''){
        $patientForcedforSexBy = explode(',',$patientForcedforSexdata['who_forced']);
    }
}
?>
<style>
    .highlightedTxt{
	text-decoration:underline;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Edit Risk Assessment</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="/" class="breadcrumb">Home</a>
            <a href="/clinic/risk-assessment/<?php echo base64_encode($countryId); ?>" class="breadcrumb">Risk Assessment Form</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Edit Risk Assessment</a>
       </div>
    </div>
    <div class="formContainer row content-container" style="margin-bottom:20px;padding: 0 20px;">
        <form id="editRiskAssessmentForm" name="editRiskAssessmentForm" method="post" action="<?php echo $this->url('edit-clinic-risk-assessment'); ?>">
        <div class="card">
            <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Sample Particpant Risk Questionnaire</strong></h6>
            <fieldset style="border-color:#2196F3;border-style:solid;">
                <div class="row" style="margin-bottom:0;">
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                        <select id="ancSite" name="ancSite" class="material-select isRequired" title="Please select ANC Site">
                           <option value=""> -- Select -- </option>
                           <?php
                            foreach($ancSites as $anc){
                            ?>
                            <option value="<?php echo base64_encode($anc['anc_site_id']); ?>" <?php echo ($anc['anc_site_id'] == $row->anc)?'selected="selected"':''; ?>><?php echo $anc['anc_site_code'].' - '.ucwords($anc['anc_site_name']); ?></option>
                            <?php } ?>
                        </select>
                            <label for="ancSite">ANC Site *</label>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <input id="patientBarcodeId" name="patientBarcodeId" type="text" class="validate isRequired" title="Please enter patient barcode id" value="<?php echo $row->patient_barcode_id; ?>" onblur="checkPatientRecord();">
                            <label for="patientBarcodeId" class="">Patient Barcode ID *</label>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <input id="interviewerName" name="interviewerName" type="text" class="validate isRequired" title="Please enter interviewer name" value="<?php echo $row->interviewer_name; ?>">
                            <label for="interviewerName" class="">Interviewer Name *</label>
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-bottom:0;">
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <input id="ancPatientId" name="ancPatientId" type="text" class="validate isRequired" title="Please enter anc patient ID" value="<?php echo $row->anc_patient_id; ?>">
                            <label for="ancPatientId" class="">ANC Patient ID *</label>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <input id="interviewDate" name="interviewDate" type="text" class="validate isRequired datepicker" title="Please enter interview date" value="<?php echo $interviewDate; ?>">
                            <label for="interviewDate" class="">Interview Date *</label>
                        </div>
                    </div>
                    <!--<div class="col s4">
                        <div class="input-field col m12 s12">
                        Has participant received DREAMS services ? (Optional)<br><br>
                        <input id="hasParticipantReceivedDreamsServicesYes" class="with-gap" name="hasParticipantReceivedDreamsServices" title="Please select participant-dreams services received status" value="yes" type="radio" < ?php echo ($row->has_participant_received_dreams_services == 'yes')?'checked="checked"':''; ?>>
                        <label for="hasParticipantReceivedDreamsServicesYes" class="active">Yes </label>&nbsp;&nbsp;
                        <input id="hasParticipantReceivedDreamsServicesNo" class="with-gap" name="hasParticipantReceivedDreamsServices" value="no" type="radio" < ?php echo ($row->has_participant_received_dreams_services == 'no')?'checked="checked"':''; ?>>
                        <label for="hasParticipantReceivedDreamsServicesNo" class="active">No </label>
                        </div>
                    </div>-->
                </div>
            </fieldset>
            <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Recency Test Result</strong></h6>
            <fieldset id="rtrSection" style="height:<?php echo (isset($row->has_patient_had_rapid_recency_test) && $row->has_patient_had_rapid_recency_test == 'done')?'auto':'90px'; ?>;border-color:#F44336;border-style:solid;">
		<div class="row" style="margin-bottom:0;">
		    <div class="col s3">
			<div class="input-field col m12 s12">
			Rapid Recency Result *<br><br>
			<input id="hasPatientHadRapidRecencyTestYes" class="with-gap isRequired" name="hasPatientHadRapidRecencyTest" title="Please select patient rapid recency test status" value="done" type="radio" <?php echo (isset($row->has_patient_had_rapid_recency_test) && $row->has_patient_had_rapid_recency_test == 'done')?'checked="checked"':''; ?>>
			<label for="hasPatientHadRapidRecencyTestYes" class="active">Done </label>&nbsp;&nbsp;
			<input id="hasPatientHadRapidRecencyTestNo" class="with-gap" name="hasPatientHadRapidRecencyTest" value="not done" type="radio" <?php echo (isset($row->has_patient_had_rapid_recency_test) && $row->has_patient_had_rapid_recency_test == 'not done')?'checked="checked"':''; ?>>
			<label for="hasPatientHadRapidRecencyTestNo" class="active">Not Done </label>&nbsp;&nbsp;
			</div>
		    </div>
		    <div class="col s3 rrrSection" style="display:<?php echo (isset($row->has_patient_had_rapid_recency_test) && $row->has_patient_had_rapid_recency_test == 'done')?'':'none;'; ?>;">
			<div class="input-field col m12 s12">
			<select id="rrrControl" name="rrrControl" class="material-select <?php echo (isset($row->has_patient_had_rapid_recency_test) && $row->has_patient_had_rapid_recency_test == 'done')?'isRequired':''; ?>" title="Please select control line">
                            <option value=""> -- Select -- </option>
			    <option value="positive" <?php echo (isset($row->control_line) && $row->control_line == 'positive')?'selected="selected"':''; ?>>Present (Positive/P)</option>
			    <option value="negative" <?php echo (isset($row->control_line) && $row->control_line == 'negative')?'selected="selected"':''; ?>>Absent (Negative/N)</option>
			    <option value="invalid" <?php echo (isset($row->control_line) && $row->control_line == 'invalid')?'selected="selected"':''; ?>>Invalid</option>
			    <option value="result-not-available" <?php echo (isset($row->control_line) && $row->control_line == 'result-not-available')?'selected="selected"':''; ?>>Result not available</option>
                        </select>
                        <label for="rrrControl">Control Line *</label>
			</div>
		    </div>
		    <div class="col s3 rrrSection" style="display:<?php echo (isset($row->has_patient_had_rapid_recency_test) && $row->has_patient_had_rapid_recency_test == 'done')?'':'none;'; ?>;">
			<div class="input-field col m12 s12">
			<select id="rrrHIVDiagnostic" name="rrrHIVDiagnostic" class="material-select <?php echo (isset($row->has_patient_had_rapid_recency_test) && $row->has_patient_had_rapid_recency_test == 'done')?'isRequired':''; ?>" title="Please select positive verfication line">
                            <option value=""> -- Select -- </option>
			    <option value="positive" <?php echo (isset($row->HIV_diagnostic_line) && $row->HIV_diagnostic_line == 'positive')?'selected="selected"':''; ?>>Present (Positive/P)</option>
			    <option value="negative" <?php echo (isset($row->HIV_diagnostic_line) && $row->HIV_diagnostic_line == 'negative')?'selected="selected"':''; ?>>Absent (Negative/N)</option>
			    <option value="invalid" <?php echo (isset($row->HIV_diagnostic_line) && $row->HIV_diagnostic_line == 'invalid')?'selected="selected"':''; ?>>Invalid</option>
			    <option value="result-not-available" <?php echo (isset($row->HIV_diagnostic_line) && $row->HIV_diagnostic_line == 'result-not-available')?'selected="selected"':''; ?>>Result not available</option>
                        </select>
                        <label for="rrrHIVDiagnostic">Positive Verification Line *</label>
			</div>
		    </div>
		    <div class="col s3 rrrRecency rrrSection" style="display:<?php echo ((isset($row->has_patient_had_rapid_recency_test) && $row->has_patient_had_rapid_recency_test == 'done') && (!isset($row->HIV_diagnostic_line) || (isset($row->HIV_diagnostic_line) && $row->HIV_diagnostic_line !='negative')))?'':'none;'; ?>">
			<div class="input-field col m12 s12">
			<select id="rrrRecency" name="rrrRecency" class="material-select <?php echo ((isset($row->has_patient_had_rapid_recency_test) && $row->has_patient_had_rapid_recency_test == 'done') && (!isset($row->HIV_diagnostic_line) || (isset($row->HIV_diagnostic_line) && $row->HIV_diagnostic_line !='negative')))?'isRequired':''; ?>" title="Please select long term (recency) line">
                            <option value=""> -- Select -- </option>
			    <option value="long term" <?php echo (isset($row->recency_line) && $row->recency_line == 'long term')?'selected="selected"':''; ?>>Present(Long Term/LT)</option>
			    <option value="recent" <?php echo (isset($row->recency_line) && $row->recency_line == 'recent')?'selected="selected"':''; ?>>Absent (Recent/R)</option>
			    <option value="invalid" <?php echo (isset($row->recency_line) && $row->recency_line == 'invalid')?'selected="selected"':''; ?>>Invalid</option>
			    <option value="result-not-available" <?php echo (isset($row->recency_line) && $row->recency_line == 'result-not-available')?'selected="selected"':''; ?>>Result not available</option>
                        </select>
                        <label for="rrrRecency">Long Term (Recency) Line *</label>
			</div>
		    </div>
		</div>
	    </fieldset>
            <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Demographic Characteristics</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q1. What kind of work/occupation do you do most of the time? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="occupation" name="occupation" class="material-select isRequired" title="Please enter response for Q1">
                        <option value=""> -- Select -- </option>
                        <?php
			foreach($occupationTypes as $occupation){
			?>
                           <option value="<?php echo base64_encode($occupation['occupation_id']); ?>" <?php echo ($row->patient_occupation == $occupation['occupation_id'])?'selected="selected"':''; ?>><?php echo ucwords($occupation['occupation']).' - '.$occupation['occupation_code']; ?></option>
			<?php } ?>
                        <option value="1111">Other - 1111</option>
                    </select>
                </div>
		<div class="col s4 occupationNew" style="display:none;">
		    <input id="occupationNew" name="occupationNew" type="text" class="validate" placeholder="Occupation" title="Please enter occupation" onblur="checkNameValidation('occupation_type', 'occupation', this, null,'The occupation that you entered already listed. Please enter different occupation');">
		</div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q2. Have you ever attended school? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="hasPatientEverAttendedSchoolYes" class="with-gap isRequired" name="hasPatientEverAttendedSchool" title="Please enter response for Q2" value="1" type="radio" onchange="manageQ2();" <?php echo ($row->has_patient_ever_attended_school == 1)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverAttendedSchoolYes" class="active">Yes - 1 </label>&nbsp;&nbsp;
                    <input id="hasPatientEverAttendedSchoolNo" class="with-gap" name="hasPatientEverAttendedSchool" value="2" type="radio" onchange="manageQ2();" <?php echo ($row->has_patient_ever_attended_school == 2)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverAttendedSchoolNo" class="active">No - 2 </label>&nbsp;&nbsp;
		    <input id="hasPatientEverAttendedSchoolDK" class="with-gap" name="hasPatientEverAttendedSchool" value="88" type="radio" onchange="manageQ2();" <?php echo ($row->has_patient_ever_attended_school == 88)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverAttendedSchoolDK" class="active">Don't Know - 88 </label>&nbsp;&nbsp;
                    <input id="hasPatientEverAttendedSchoolR" class="with-gap" name="hasPatientEverAttendedSchool" value="99" type="radio" onchange="manageQ2();" <?php echo ($row->has_patient_ever_attended_school == 99)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverAttendedSchoolR" class="active">Refused - 99 </label>&nbsp;&nbsp;
		    <input id="hasPatientEverAttendedSchoolRNA" class="with-gap" name="hasPatientEverAttendedSchool" value="2222" type="radio" onchange="manageQ2();" <?php echo ($row->has_patient_ever_attended_school == 2222)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverAttendedSchoolRNA" class="active">Response Not Available - 2222 </label>
                </div>
            </div>
            <div class="row degreeSection" style="margin-bottom:0;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q2A. What was the highest level of education that you completed or are attending now?<span class="degreeSectionRequired">*</span>
                </div>
            </div>
            <div class="row degreeSection" style="margin-bottom:10px;">
                <div class="col s4 degree" style="padding-left:3%;">
                    <select id="degree" name="degree" class="material-select isRequired" title="Please enter response for Q2A">
                        <option value=""> -- Select -- </option>
                        <option value="1" <?php echo ($row->patient_degree == 1)?'selected="selected"':''; ?>>Primary/Vocational - 1</option>
                        <option value="2" <?php echo ($row->patient_degree == 2)?'selected="selected"':''; ?>>Secondary - 2</option>
                        <option value="3" <?php echo ($row->patient_degree == 3)?'selected="selected"':''; ?>>University/College - 3</option>
			<option value="88" <?php echo ($row->patient_degree == 88)?'selected="selected"':''; ?>>Don't know - 88</option>
			<option value="99" <?php echo ($row->patient_degree == 99)?'selected="selected"':''; ?>>Refused - 99</option>
			<option value="2222" <?php echo ($row->patient_degree == 2222)?'selected="selected"':''; ?>>Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q3. Have you <span class="highlightedTxt">ever</span> been married or lived with a partner in a union as if married? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="everBeenMarriedYes" class="with-gap isRequired" name="everBeenMarried" title="Please enter response for Q3" value="1" type="radio" onchange="manageQ3('change');" <?php echo ($row->patient_ever_been_married == 1)?'checked="checked"':''; ?>>
		    <label for="everBeenMarriedYes" class="active">Yes - 1 </label>&nbsp;&nbsp;
                    <input id="everBeenMarriedNo" class="with-gap" name="everBeenMarried" value="2" type="radio" onchange="manageQ3('change');" <?php echo ($row->patient_ever_been_married == 2)?'checked="checked"':''; ?>>
		    <label for="everBeenMarriedNo" class="active">No - 2 </label>&nbsp;&nbsp;
		    <input id="everBeenMarriedDK" class="with-gap" name="everBeenMarried" value="88" type="radio" onchange="manageQ3('change');" <?php echo ($row->patient_ever_been_married == 88)?'checked="checked"':''; ?>>
		    <label for="everBeenMarriedDK" class="active">Don't Know - 88 </label>&nbsp;&nbsp;
                    <input id="everBeenMarriedR" class="with-gap" name="everBeenMarried" value="99" type="radio" onchange="manageQ3('change');" <?php echo ($row->patient_ever_been_married == 99)?'checked="checked"':''; ?>>
		    <label for="everBeenMarriedR" class="active">Refused - 99 </label>&nbsp;&nbsp;
		    <input id="everBeenMarriedRNA" class="with-gap" name="everBeenMarried" value="2222" type="radio" onchange="manageQ3('change');" <?php echo ($row->patient_ever_been_married == 2222)?'checked="checked"':''; ?>>
		    <label for="everBeenMarriedRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q3A. How old were you when you <span class="highlightedTxt">first</span> got married or lived with a partner in a union? <span class="everBeenMarriedSectionRequired">*</span>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:10px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="ageAtFirstMarriageInYears" name="ageAtFirstMarriageInYears" type="text" class="validate years checkNum <?php echo($row->age_at_first_marriage == null || $row->age_at_first_marriage == '')?'isRequired':''; ?>" title="Please enter response for Q3A" value="<?php echo($row->age_at_first_marriage!= null && trim($row->age_at_first_marriage)!= '' && $row->age_at_first_marriage[0] == '@')?substr($row->age_at_first_marriage,1):'';?>" style="width:10%;"> Years&nbsp;
                    <input id="ageAtFirstMarriageDK" class="with-gap" name="ageAtFirstMarriage" value="88" type="radio" title="Please enter response for Q3A" <?php echo ($row->age_at_first_marriage == 88)?'checked="checked"':''; ?>>
		    <label for="ageAtFirstMarriageDK" class="active">Don't Know - 88 </label>&nbsp;&nbsp;
                    <input id="ageAtFirstMarriageR" class="with-gap" name="ageAtFirstMarriage" value="99" type="radio" <?php echo ($row->age_at_first_marriage == 99)?'checked="checked"':''; ?>>
		    <label for="ageAtFirstMarriageR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="ageAtFirstMarriageRNA" class="with-gap" name="ageAtFirstMarriage" value="2222" type="radio" <?php echo ($row->age_at_first_marriage == 2222)?'checked="checked"':''; ?>>
		    <label for="ageAtFirstMarriageRNA" class="active">Response Not Available - 2222 </label>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:0;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q3B. Have you <span class="highlightedTxt">ever</span> been widowed? That is, did a spouse ever pass away while you were still married or living with them? <span class="everBeenMarriedSectionRequired">*</span>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:10px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="everBeenWidowedYes" class="with-gap isRequired" name="everBeenWidowed" title="Please enter response for Q3B" value="1" type="radio" <?php echo ($row->patient_ever_been_widowed == 1)?'checked="checked"':''; ?>>
		    <label for="everBeenWidowedYes" class="active">Yes - 1 </label>&nbsp;&nbsp;
                    <input id="everBeenWidowedNo" class="with-gap" name="everBeenWidowed" value="2" type="radio" <?php echo ($row->patient_ever_been_widowed == 2)?'checked="checked"':''; ?>>
		    <label for="everBeenWidowedNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="everBeenWidowedDK" class="with-gap" name="everBeenWidowed" value="88" type="radio" <?php echo ($row->patient_ever_been_widowed == 88)?'checked="checked"':''; ?>>
		    <label for="everBeenWidowedDK" class="active">Don't Know - 88 </label>&nbsp;&nbsp;
                    <input id="everBeenWidowedR" class="with-gap" name="everBeenWidowed" value="99" type="radio" <?php echo ($row->patient_ever_been_widowed == 99)?'checked="checked"':''; ?>>
		    <label for="everBeenWidowedR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="everBeenWidowedRNA" class="with-gap" name="everBeenWidowed" value="2222" type="radio" <?php echo ($row->patient_ever_been_widowed == 2222)?'checked="checked"':''; ?>>
		    <label for="everBeenWidowedRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q3C. What is your marital status <span class="highlightedTxt">now</span>? <span class="everBeenMarriedSectionRequired">*</span>
                </div>
            </div>
            <div class="row everBeenMarriedSection" style="margin-bottom:10px;">
                <div class="col s4 currentMaritalStatus" style="padding-left:3%;">
                    <select id="currentMaritalStatus" name="currentMaritalStatus" class="material-select isRequired" title="Please enter response for Q3C">
                        <option value=""> -- Select -- </option>
                        <option value="1" <?php echo ($row->current_marital_status == 1)?'selected="selected"':''; ?>>Married/Cohabiting - 1</option>
                        <option value="2" <?php echo ($row->current_marital_status == 2)?'selected="selected"':''; ?>>Never Married/Cohabiting - 2</option>
                        <option value="3" <?php echo ($row->current_marital_status == 3)?'selected="selected"':''; ?>>Widowed - 3</option>
                        <option value="4" <?php echo ($row->current_marital_status == 4)?'selected="selected"':''; ?>>Separated - 4</option>
                        <option value="5" <?php echo ($row->current_marital_status == 5)?'selected="selected"':''; ?>>Divorced - 5</option>
                        <option value="88" <?php echo ($row->current_marital_status == 88)?'selected="selected"':''; ?>>Don't Know - 88</option>
                        <option value="99" <?php echo ($row->current_marital_status == 99)?'selected="selected"':''; ?>>Refused - 99</option>
			<option value="2222" <?php echo ($row->current_marital_status == 2222)?'selected="selected"':''; ?>>Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <h6 style="padding:0px 0px 10px 6px;font-size:16px;"><strong>HIV Testing History</strong></h6>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q4. Have you ever been tested for HIV? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="hasPatientEverBeenTestedforHIVYes" class="with-gap isRequired" name="hasPatientEverBeenTestedforHIV" value="1" type="radio" title="Please enter response for Q4" onchange="manageQ4();" <?php echo ($row->has_patient_ever_been_tested_for_HIV == 1)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenTestedforHIVYes" class="active">Yes - 1 </label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenTestedforHIVNo" class="with-gap" name="hasPatientEverBeenTestedforHIV" value="2" type="radio" onchange="manageQ4();" <?php echo ($row->has_patient_ever_been_tested_for_HIV == 2)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenTestedforHIVNo" class="active">No - 2 </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenTestedforHIVDK" class="with-gap" name="hasPatientEverBeenTestedforHIV" value="88" type="radio" onchange="manageQ4();" <?php echo ($row->has_patient_ever_been_tested_for_HIV == 88)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenTestedforHIVDK" class="active">Don't Know - 88 </label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenTestedforHIVR" class="with-gap" name="hasPatientEverBeenTestedforHIV" value="99" type="radio" onchange="manageQ4();" <?php echo ($row->has_patient_ever_been_tested_for_HIV == 99)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenTestedforHIVR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenTestedforHIVRNA" class="with-gap" name="hasPatientEverBeenTestedforHIV" value="2222" type="radio" onchange="manageQ4();" <?php echo ($row->has_patient_ever_been_tested_for_HIV == 2222)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenTestedforHIVRNA" class="active">Response Not Available - 2222 </label>
                </div>
            </div>
            <div class="row everBeenTestedforHIVSection" style="margin-bottom:0;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q4A. When was the <span class="highlightedTxt">most recent</span> time you were tested for HIV? <span class="everBeenTestedforHIVSectionRequired">*</span>
                </div>
            </div>
            <div class="row everBeenTestedforHIVSection" style="margin-bottom:10px;">
                <div class="col s4 timeOfLastHIVTest" style="padding-left:3%;">
                    <select id="timeOfLastHIVTest" name="timeOfLastHIVTest" class="material-select isRequired" title="Please enter response for Q4A">
                        <option value=""> -- Select -- </option>
                        <option value="1" <?php echo ($row->time_of_last_HIV_test == 1)?'selected="selected"':''; ?>>< 3 Months Ago - 1</option>
                        <option value="2" <?php echo ($row->time_of_last_HIV_test == 2)?'selected="selected"':''; ?>>3-6 Months Ago - 2</option>
                        <option value="3" <?php echo ($row->time_of_last_HIV_test == 3)?'selected="selected"':''; ?>>7-12 Months Ago - 3</option>
                        <option value="4" <?php echo ($row->time_of_last_HIV_test == 4)?'selected="selected"':''; ?>> > 12 months - 4</option>
                        <option value="88" <?php echo ($row->time_of_last_HIV_test == 88)?'selected="selected"':''; ?>>Don't Know - 88</option>
                        <option value="99" <?php echo ($row->time_of_last_HIV_test == 99)?'selected="selected"':''; ?>>Refused - 99</option>
			<option value="2222" <?php echo ($row->time_of_last_HIV_test == 2222)?'selected="selected"':''; ?>>Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <div class="row everBeenTestedforHIVSection" style="margin-bottom:0;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q4B. What was the result of that HIV test? <span class="everBeenTestedforHIVSectionRequired">*</span>
                </div>
            </div>
            <div class="row everBeenTestedforHIVSection" style="margin-bottom:10px;">
                <div class="col s4 lastHIVTestStatus" style="padding-left:3%;">
                    <select id="lastHIVTestStatus" name="lastHIVTestStatus" class="material-select isRequired" title="Please enter response for Q4B">
                        <option value=""> -- Select -- </option>
                        <option value="1" <?php echo ($row->last_HIV_test_status == 1)?'selected="selected"':''; ?>>I Did Not Receive Result - 1</option>
                        <option value="2" <?php echo ($row->last_HIV_test_status == 2)?'selected="selected"':''; ?>>HIV Positive - 2</option>
                        <option value="3" <?php echo ($row->last_HIV_test_status == 3)?'selected="selected"':''; ?>>HIV Negative - 3</option>
                        <option value="4" <?php echo ($row->last_HIV_test_status == 4)?'selected="selected"':''; ?>>Indeterminate - 4</option>
                        <option value="88" <?php echo ($row->last_HIV_test_status == 88)?'selected="selected"':''; ?>>Don't Know - 88</option>
                        <option value="99" <?php echo ($row->last_HIV_test_status == 99)?'selected="selected"':''; ?>>Refused - 99</option>
			<option value="2222" <?php echo ($row->last_HIV_test_status == 2222)?'selected="selected"':''; ?>>Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <h6 style="padding:0px 0px 10px 6px;font-size:16px;"><strong>Sexual Activity and History of Sexually Transmitted Infections</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q5. How old were you when you had sexual intercourse for the very <span class="highlightedTxt">first</span> time? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="ageAtVeryFirstSexInNumbers" name="ageAtVeryFirstSexInNumbers" type="text" class="validate years checkNum <?php echo ($row->age_at_very_first_sex == null || trim($row->age_at_very_first_sex) == '')?'isRequired':''; ?>" title="Please enter response for Q5" value="<?php echo($row->age_at_very_first_sex!= null && trim($row->age_at_very_first_sex)!= '' && $row->age_at_very_first_sex[0] == '@')?substr($row->age_at_very_first_sex,1):'';?>" style="width:10%;"> Years &nbsp;&nbsp;
		    <input id="ageAtVeryFirstSexDK" class="with-gap" name="ageAtVeryFirstSex" value="88" type="radio" <?php echo ($row->age_at_very_first_sex == 88)?'checked="checked"':''; ?>>
		    <label for="ageAtVeryFirstSexDK" class="active">Don't Know - 88 </label>&nbsp;&nbsp;
		    <input id="ageAtVeryFirstSexR" class="with-gap" name="ageAtVeryFirstSex" value="99" type="radio" <?php echo ($row->age_at_very_first_sex == 99)?'checked="checked"':''; ?>>
		    <label for="ageAtVeryFirstSexR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="ageAtVeryFirstSexRNA" class="with-gap" name="ageAtVeryFirstSex" value="2222" type="radio" <?php echo ($row->age_at_very_first_sex == 2222)?'checked="checked"':''; ?>>
		    <label for="ageAtVeryFirstSexRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q6. The <span class="highlightedTxt">first</span> time you had sex, was it because you wanted to or because you were forced to? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="reasonForVeryFirstSexWT" class="with-gap isRequired" name="reasonForVeryFirstSex" title="Please enter response for Q6" value="1" type="radio" <?php echo ($row->reason_for_very_first_sex == 1)?'checked="checked"':''; ?>>
		    <label for="reasonForVeryFirstSexWT" class="active">Wanted To - 1</label>&nbsp;&nbsp;
                    <input id="reasonForVeryFirstSexFT" class="with-gap" name="reasonForVeryFirstSex" value="2" type="radio" <?php echo ($row->reason_for_very_first_sex == 2)?'checked="checked"':''; ?>>
		    <label for="reasonForVeryFirstSexFT" class="active">Forced To - 2</label>&nbsp;&nbsp;
                    <input id="reasonForVeryFirstSexDK" class="with-gap" name="reasonForVeryFirstSex" value="88" type="radio" <?php echo ($row->reason_for_very_first_sex == 88)?'checked="checked"':''; ?>>
		    <label for="reasonForVeryFirstSexDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="reasonForVeryFirstSexR" class="with-gap" name="reasonForVeryFirstSex" value="99" type="radio" <?php echo ($row->reason_for_very_first_sex == 99)?'checked="checked"':''; ?>>
		    <label for="reasonForVeryFirstSexR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="reasonForVeryFirstSexRNA" class="with-gap" name="reasonForVeryFirstSex" value="2222" type="radio" <?php echo ($row->reason_for_very_first_sex == 2222)?'checked="checked"':''; ?>>
		    <label for="reasonForVeryFirstSexRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    Q7. How many different people have you had sexual intercourse with <span class="highlightedTxt">in your entire life</span>? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="noOfSexualPartnersInNumbers" name="noOfSexualPartnersInNumbers" type="text" class="validate persons checkNum <?php echo ($row->no_of_sexual_partners == null || trim($row->no_of_sexual_partners) == '')?'isRequired':''; ?>" title="Please enter response for Q7" value="<?php echo($row->no_of_sexual_partners!= null && trim($row->no_of_sexual_partners)!= '' && $row->no_of_sexual_partners[0] == '@')?substr($row->no_of_sexual_partners,1):'';?>" style="width:10%;"> Persons&nbsp;
                    <input id="noOfSexualPartnersDK" class="with-gap" name="noOfSexualPartners" value="88" type="radio" <?php echo ($row->no_of_sexual_partners == 88)?'checked="checked"':''; ?>>
		    <label for="noOfSexualPartnersDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="noOfSexualPartnersR" class="with-gap" name="noOfSexualPartners" value="99" type="radio" <?php echo ($row->no_of_sexual_partners == 99)?'checked="checked"':''; ?>>
		    <label for="noOfSexualPartnersR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="noOfSexualPartnersRNA" class="with-gap" name="noOfSexualPartners" value="2222" type="radio" <?php echo ($row->no_of_sexual_partners == 2222)?'checked="checked"':''; ?>>
		    <label for="noOfSexualPartnersRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q8. How many different people have you had sex with in the last 6 months? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="noOfSexualPartnersInLastSixMonthsInNumbers" name="noOfSexualPartnersInLastSixMonthsInNumbers" type="text" class="validate persons checkNum <?php echo ($row->no_of_sexual_partners_in_last_six_months == null || trim($row->no_of_sexual_partners_in_last_six_months) == '')?'isRequired':''; ?>" title="Please enter response for Q8" value="<?php echo($row->no_of_sexual_partners_in_last_six_months!= null && trim($row->no_of_sexual_partners_in_last_six_months)!= '' && $row->no_of_sexual_partners_in_last_six_months[0] == '@')?substr($row->no_of_sexual_partners_in_last_six_months,1):'';?>" style="width:10%;"> Persons&nbsp;
                    <input id="noOfSexualPartnersInLastSixMonthsDK" class="with-gap" name="noOfSexualPartnersInLastSixMonths" value="88" type="radio" <?php echo ($row->no_of_sexual_partners_in_last_six_months == 88)?'checked="checked"':''; ?>>
		    <label for="noOfSexualPartnersInLastSixMonthsDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="noOfSexualPartnersInLastSixMonthsR" class="with-gap" name="noOfSexualPartnersInLastSixMonths" value="99" type="radio" <?php echo ($row->no_of_sexual_partners_in_last_six_months == 99)?'checked="checked"':''; ?>>
		    <label for="noOfSexualPartnersInLastSixMonthsR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="noOfSexualPartnersInLastSixMonthsRNA" class="with-gap" name="noOfSexualPartnersInLastSixMonths" value="2222" type="radio" <?php echo ($row->no_of_sexual_partners_in_last_six_months == 2222)?'checked="checked"':''; ?>>
		    <label for="noOfSexualPartnersInLastSixMonthsRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
		    Q9. What is the HIV status of your <span class="highlightedTxt">spouse/main</span> sexual partner's (person with whom you have sexual intercourse most frequently)? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="partnerHIVTestStatus" name="partnerHIVTestStatus" class="material-select isRequired" title="Please enter response for Q9" onchange="manageQ9();">
                        <option value=""> -- Select -- </option>
                        <option value="1" <?php echo ($row->partner_HIV_test_status == 1)?'selected="selected"':''; ?>>HIV Positive - 1</option>
                        <option value="2" <?php echo ($row->partner_HIV_test_status == 2)?'selected="selected"':''; ?>>HIV Negative - 2</option>
			 <option value="3" <?php echo ($row->partner_HIV_test_status == 3)?'selected="selected"':''; ?>>No Main Sexual Partner - 3</option>
                        <option value="88" <?php echo ($row->partner_HIV_test_status == 88)?'selected="selected"':''; ?>>Don't Know - 88</option>
                        <option value="99" <?php echo ($row->partner_HIV_test_status == 99)?'selected="selected"':''; ?>>Refused - 99</option>
                        <option value="2222" <?php echo ($row->partner_HIV_test_status == 2222)?'selected="selected"':''; ?>>Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <div class="row partnerHIVTestStatus" style="margin-bottom:0;">
                <div class="col s12">
                    Q10. How old was your <span class="highlightedTxt">spouse/main</span> sexual partner on his last birthday? <span class="partnerHIVTestStatusRequired">*</span>
                </div>
            </div>
            <div class="row partnerHIVTestStatus" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="ageOfMainSexualPartnerAtLastBirthdayInYears" name="ageOfMainSexualPartnerAtLastBirthdayInYears" type="text" class="validate years checkNum <?php echo ($row->age_of_main_sexual_partner_at_last_birthday == null || trim($row->age_of_main_sexual_partner_at_last_birthday) == '')?'isRequired':''; ?>" title="Please enter response for Q10" value="<?php echo($row->age_of_main_sexual_partner_at_last_birthday!= null && trim($row->age_of_main_sexual_partner_at_last_birthday)!= '' && $row->age_of_main_sexual_partner_at_last_birthday[0] == '@')?substr($row->age_of_main_sexual_partner_at_last_birthday,1):'';?>" onchange="manageQ10('txt');" style="width:13%;"> Years&nbsp;
                    <input id="ageOfMainSexualPartnerAtLastBirthdayDK" class="with-gap" name="ageOfMainSexualPartnerAtLastBirthday" value="88" type="radio" onchange="manageQ10('rd');" <?php echo ($row->age_of_main_sexual_partner_at_last_birthday == 88)?'checked="checked"':''; ?>>
		    <label for="ageOfMainSexualPartnerAtLastBirthdayDK" class="active">Don't Know - 88 </label>&nbsp;&nbsp;
                    <input id="ageOfMainSexualPartnerAtLastBirthdayR" class="with-gap" name="ageOfMainSexualPartnerAtLastBirthday" value="99" type="radio" onchange="manageQ10('rd');" <?php echo ($row->age_of_main_sexual_partner_at_last_birthday == 99)?'checked="checked"':''; ?>>
		    <label for="ageOfMainSexualPartnerAtLastBirthdayR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="ageOfMainSexualPartnerAtLastBirthdayRNA" class="with-gap" name="ageOfMainSexualPartnerAtLastBirthday" value="2222" type="radio" onchange="manageQ10('rd');" <?php echo ($row->age_of_main_sexual_partner_at_last_birthday == 2222)?'checked="checked"':''; ?>>
		    <label for="ageOfMainSexualPartnerAtLastBirthdayRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row partnerHIVTestStatus mainSexualPartnerAgeSection" style="margin-bottom:0;">
                <div class="col s12">
                    Q11. Is the age of your <span class="highlightedTxt">spouse/main</span> sexual partner older, younger, or the same age as you? <span class="partnerHIVTestStatusRequired mainSexualPartnerAgeSectionRequired">*</span>
                </div>
            </div>
            <div class="row partnerHIVTestStatus mainSexualPartnerAgeSection" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="ageDiffOfMainSexualPartner" name="ageDiffOfMainSexualPartner" class="material-select isRequired" title="Please enter response for Q11">
                        <option value=""> -- Select -- </option>
                        <option value="1" <?php echo ($row->age_diff_of_main_sexual_partner == 1)?'selected="selected"':''; ?>> < 5 Years Older - 1</option>
                        <option value="2" <?php echo ($row->age_diff_of_main_sexual_partner == 2)?'selected="selected"':''; ?>> 5-10 Years Older - 2</option>
                        <option value="3" <?php echo ($row->age_diff_of_main_sexual_partner == 3)?'selected="selected"':''; ?>> >10 Years Older - 3</option>
                        <option value="4" <?php echo ($row->age_diff_of_main_sexual_partner == 4)?'selected="selected"':''; ?>>Same Age - 4</option>
                        <option value="5" <?php echo ($row->age_diff_of_main_sexual_partner == 5)?'selected="selected"':''; ?>> < 5 Years Younger - 5</option>
                        <option value="6" <?php echo ($row->age_diff_of_main_sexual_partner == 6)?'selected="selected"':''; ?>>5-10 Years Younger - 6</option>
                        <option value="7" <?php echo ($row->age_diff_of_main_sexual_partner == 7)?'selected="selected"':''; ?>> >10 Years Younger - 7</option>
                        <option value="88" <?php echo ($row->age_diff_of_main_sexual_partner == 88)?'selected="selected"':''; ?>>Don't Know - 88</option>
                        <option value="99" <?php echo ($row->age_diff_of_main_sexual_partner == 89)?'selected="selected"':''; ?>>Refused - 99</option>
			<option value="2222" <?php echo ($row->age_diff_of_main_sexual_partner == 2222)?'selected="selected"':''; ?>>Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <div class="row partnerHIVTestStatus" style="margin-bottom:0;">
                <div class="col s12">
                    Q12. Is your <span class="highlightedTxt">spouse/main</span> sexual partner circumcised? <span class="partnerHIVTestStatusRequired">*</span>
                </div>
            </div>
            <div class="row partnerHIVTestStatus" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="isPartnerCircumcisedYes" class="with-gap isRequired" name="isPartnerCircumcised" title="Please enter response for Q12" value="1" type="radio" onchange="manageQ12();" <?php echo ($row->is_partner_circumcised == 1)?'checked="checked"':''; ?>>
		    <label for="isPartnerCircumcisedYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="isPartnerCircumcisedNo" class="with-gap" name="isPartnerCircumcised" value="2" type="radio" onchange="manageQ12();" <?php echo ($row->is_partner_circumcised == 2)?'checked="checked"':''; ?>>
		    <label for="isPartnerCircumcisedNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="isPartnerCircumcisedDK" class="with-gap" name="isPartnerCircumcised" value="88" type="radio" onchange="manageQ12();" <?php echo ($row->is_partner_circumcised == 88)?'checked="checked"':''; ?>>
		    <label for="isPartnerCircumcisedDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="isPartnerCircumcisedR" class="with-gap" name="isPartnerCircumcised" value="99" type="radio" onchange="manageQ12();" <?php echo ($row->is_partner_circumcised == 99)?'checked="checked"':''; ?>>
		    <label for="isPartnerCircumcisedR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="isPartnerCircumcisedRNA" class="with-gap" name="isPartnerCircumcised" value="2222" type="radio" onchange="manageQ12();" <?php echo ($row->is_partner_circumcised == 2222)?'checked="checked"':''; ?>>
		    <label for="isPartnerCircumcisedRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row partnerHIVTestStatus circumcisionSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q12A. What type of circumcision? <span class="partnerHIVTestStatusRequired circumcisionSectionRequired">*</span>
                </div>
            </div>
            <div class="row partnerHIVTestStatus circumcisionSection" style="margin-bottom:10px;">
                <div class="col s4" style="padding-left:3%;">
                    <select id="circumcision" name="circumcision" class="material-select isRequired" title="Please enter response for Q12A">
                        <option value=""> -- Select -- </option>
                        <option value="1" <?php echo ($row->circumcision == 1)?'selected="selected"':''; ?>> Medical Circumcision - 1</option>
                        <option value="2" <?php echo ($row->circumcision == 2)?'selected="selected"':''; ?>> Traditional Circumcision - 2</option>
                        <option value="88" <?php echo ($row->circumcision == 88)?'selected="selected"':''; ?>>Don't Know - 88</option>
                        <option value="99" <?php echo ($row->circumcision == 99)?'selected="selected"':''; ?>>Refused - 99</option>
			<option value="2222" <?php echo ($row->circumcision == 2222)?'selected="selected"':''; ?>>Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q13. Have you ever received money/gifts in exchange for sex? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="hasPatientEverReceivedGiftForSexYes" class="with-gap isRequired" name="hasPatientEverReceivedGiftForSex" title="Please enter response for Q13" value="1" type="radio" onchange="manageQ13();" <?php echo ($row->has_patient_ever_received_gift_for_sex == 1)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverReceivedGiftForSexYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverReceivedGiftForSexNo" class="with-gap" name="hasPatientEverReceivedGiftForSex" value="2" type="radio" onchange="manageQ13();" <?php echo ($row->has_patient_ever_received_gift_for_sex == 2)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverReceivedGiftForSexNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverReceivedGiftForSexDK" class="with-gap" name="hasPatientEverReceivedGiftForSex" value="88" type="radio" onchange="manageQ13();" <?php echo ($row->has_patient_ever_received_gift_for_sex == 88)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverReceivedGiftForSexDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverReceivedGiftForSexR" class="with-gap" name="hasPatientEverReceivedGiftForSex" value="99" type="radio" onchange="manageQ13();" <?php echo ($row->has_patient_ever_received_gift_for_sex == 99)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverReceivedGiftForSexR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverReceivedGiftForSexRNA" class="with-gap" name="hasPatientEverReceivedGiftForSex" value="2222" type="radio" onchange="manageQ13();" <?php echo ($row->has_patient_ever_received_gift_for_sex == 2222)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverReceivedGiftForSexRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row patinetReceivedGiftForSexSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q13A. When did you last receive money/gifts in exchange for sex? <span class="patinetReceivedGiftForSexSectionRequired">*</span>
                </div>
            </div>
            <div class="row patinetReceivedGiftForSexSection" style="margin-bottom:10px;">
                <div class="col s4" style="padding-left:3%;">
                    <select id="lastTimeOfReceivingGiftForSex" name="lastTimeOfReceivingGiftForSex" class="material-select isRequired" title="Please enter response for Q13A">
                        <option value=""> -- Select -- </option>
                        <option value="1" <?php echo ($row->last_time_of_receiving_gift_for_sex == 1)?'selected="selected"':''; ?>> < 6 Months Ago - 1</option>
                        <option value="2" <?php echo ($row->last_time_of_receiving_gift_for_sex == 2)?'selected="selected"':''; ?>> 6-12 Months Ago - 2</option>
                        <option value="3" <?php echo ($row->last_time_of_receiving_gift_for_sex == 3)?'selected="selected"':''; ?>> > 12 Months Ago - 3</option>
                        <option value="88" <?php echo ($row->last_time_of_receiving_gift_for_sex == 88)?'selected="selected"':''; ?>>Don't Know - 88</option>
                        <option value="99" <?php echo ($row->last_time_of_receiving_gift_for_sex == 99)?'selected="selected"':''; ?>>Refused - 99</option>
			<option value="2222" <?php echo ($row->last_time_of_receiving_gift_for_sex == 2222)?'selected="selected"':''; ?>>Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q14. How many times have you been pregnant? * (including this pregnancy)
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="noOfTimesBeenPregnantInNumbers" name="noOfTimesBeenPregnantInNumbers" type="text" class="validate times checkNum <?php echo ($row->no_of_times_been_pregnant == null || trim($row->no_of_times_been_pregnant) == '' || $row->no_of_times_been_pregnant == 'not applicable')?'isRequired':''; ?>" title="Please enter response for Q14" value="<?php echo($row->no_of_times_been_pregnant!= null && trim($row->no_of_times_been_pregnant)!= '' && $row->no_of_times_been_pregnant[0] == '@')?substr($row->no_of_times_been_pregnant,1):'';?>" style="width:20%;"> Times &nbsp;&nbsp;
		    <input id="noOfTimesBeenPregnantDK" class="with-gap" name="noOfTimesBeenPregnant" value="88" type="radio" <?php echo ($row->no_of_times_been_pregnant == 88)?'checked="checked"':''; ?>>
		    <label for="noOfTimesBeenPregnantDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="noOfTimesBeenPregnantR" class="with-gap" name="noOfTimesBeenPregnant" value="99" type="radio" <?php echo ($row->no_of_times_been_pregnant == 99)?'checked="checked"':''; ?>>
		    <label for="noOfTimesBeenPregnantR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="noOfTimesBeenPregnantRNA" class="with-gap" name="noOfTimesBeenPregnant" value="2222" type="radio" <?php echo ($row->no_of_times_been_pregnant == 2222)?'checked="checked"':''; ?>>
		    <label for="noOfTimesBeenPregnantRNA" class="active">Response Not Available </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q15. Before becoming pregnant this time, in the past year how frequently did you use a condom when having sexual intercourse? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="noOfTimesCondomUsedBeforePregnancyA" class="with-gap isRequired" name="noOfTimesCondomUsedBeforePregnancy" title="Please enter response for Q15" value="1" type="radio" <?php echo ($row->no_of_times_condom_used_before_pregnancy == 1)?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedBeforePregnancyA" class="active">Always - 1</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedBeforePregnancyS" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="2" type="radio" <?php echo ($row->no_of_times_condom_used_before_pregnancy == 2)?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedBeforePregnancyS" class="active">Sometimes - 2</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedBeforePregnancyN" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="3" type="radio" <?php echo ($row->no_of_times_condom_used_before_pregnancy == 3)?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedBeforePregnancyN" class="active">Never - 3</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedBeforePregnancyDK" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="88" type="radio" <?php echo ($row->no_of_times_condom_used_before_pregnancy == 88)?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedBeforePregnancyDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedBeforePregnancyR" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="99" type="radio" <?php echo ($row->no_of_times_condom_used_before_pregnancy == 99)?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedBeforePregnancyR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="noOfTimesCondomUsedBeforePregnancyRNA" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="2222" type="radio" <?php echo ($row->no_of_times_condom_used_before_pregnancy == 2222)?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedBeforePregnancyRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    Q16. Since becoming pregnant this time, how frequently have you used a condom when having sexual intercourse? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="noOfTimesCondomUsedAfterPregnancyA" class="with-gap isRequired" name="noOfTimesCondomUsedAfterPregnancy" title="Please enter response for Q16" value="1" type="radio" <?php echo ($row->no_of_times_condom_used_after_pregnancy == 1)?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedAfterPregnancyA" class="active">Always - 1</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedAfterPregnancyS" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="2" type="radio" <?php echo ($row->no_of_times_condom_used_after_pregnancy == 2)?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedAfterPregnancyS" class="active">Sometimes - 2</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedAfterPregnancyN" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="3" type="radio" <?php echo ($row->no_of_times_condom_used_after_pregnancy == 3)?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedAfterPregnancyN" class="active">Never - 3</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedAfterPregnancyDK" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="88" type="radio" <?php echo ($row->no_of_times_condom_used_after_pregnancy == 88)?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedAfterPregnancyDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="noOfTimesCondomUsedAfterPregnancyR" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="99" type="radio" <?php echo ($row->no_of_times_condom_used_after_pregnancy == 99)?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedAfterPregnancyR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="noOfTimesCondomUsedAfterPregnancyRNA" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="2222" type="radio" <?php echo ($row->no_of_times_condom_used_after_pregnancy == 2222)?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedAfterPregnancyRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    Q17. In the past year, did you have symptoms such as genital discharge, sores in your genital area, pain during urination, or pain in your lower abdomen? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="hasPatientHadPainInLowerAbdomenYes" class="with-gap isRequired" name="hasPatientHadPainInLowerAbdomen" title="Please enter response for Q17" value="1" type="radio" onchange="manageQ17();" <?php echo ($row->has_patient_had_pain_in_lower_abdomen == 1)?'checked="checked"':''; ?>>
		    <label for="hasPatientHadPainInLowerAbdomenYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientHadPainInLowerAbdomenNo" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="2" type="radio" onchange="manageQ17();" <?php echo ($row->has_patient_had_pain_in_lower_abdomen == 2)?'checked="checked"':''; ?>>
		    <label for="hasPatientHadPainInLowerAbdomenNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientHadPainInLowerAbdomenDK" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="88" type="radio" onchange="manageQ17();" <?php echo ($row->has_patient_had_pain_in_lower_abdomen == 88)?'checked="checked"':''; ?>>
		    <label for="hasPatientHadPainInLowerAbdomenDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientHadPainInLowerAbdomenR" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="99" type="radio" onchange="manageQ17();" <?php echo ($row->has_patient_had_pain_in_lower_abdomen == 99)?'checked="checked"':''; ?>>
		    <label for="hasPatientHadPainInLowerAbdomenR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientHadPainInLowerAbdomenRNA" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="2222" type="radio" onchange="manageQ17();" <?php echo ($row->has_patient_had_pain_in_lower_abdomen == 2222)?'checked="checked"':''; ?>>
		    <label for="hasPatientHadPainInLowerAbdomenRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row symptomsSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q17A. Were you treated for these symptoms? <span class="symptomsSectionRequired">*</span>
                </div>
            </div>
            <div class="row symptomsSection" style="margin-bottom:0;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="hasPatientBeenTreatedForLowerAbdomenPainYes" class="with-gap isRequired" name="hasPatientBeenTreatedForLowerAbdomenPain" title="Please enter response for Q17A" value="1" type="radio" <?php echo ($row->has_patient_been_treated_for_lower_abdomen_pain == 1)?'checked="checked"':''; ?>>
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientBeenTreatedForLowerAbdomenPainNo" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="2" type="radio" <?php echo ($row->has_patient_been_treated_for_lower_abdomen_pain == 2)?'checked="checked"':''; ?>>
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientBeenTreatedForLowerAbdomenPainDK" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="88" type="radio" <?php echo ($row->has_patient_been_treated_for_lower_abdomen_pain == 88)?'checked="checked"':''; ?>>
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientBeenTreatedForLowerAbdomenPainR" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="99" type="radio" <?php echo ($row->has_patient_been_treated_for_lower_abdomen_pain == 99)?'checked="checked"':''; ?>>
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientBeenTreatedForLowerAbdomenPainRNA" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="2222" type="radio" <?php echo ($row->has_patient_been_treated_for_lower_abdomen_pain == 2222)?'checked="checked"':''; ?>>
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    Q18. Have you <span class="highlightedTxt">ever</span> been diagnosed or treated for syphilis? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="hasPatientEverBeenTreatedForSyphilisYes" class="with-gap isRequired" name="hasPatientEverBeenTreatedForSyphilis" title="Please enter response for Q18" value="1" type="radio" <?php echo ($row->has_patient_ever_been_treated_for_syphilis == 1)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenTreatedForSyphilisYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenTreatedForSyphilisNo" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="2" type="radio" <?php echo ($row->has_patient_ever_been_treated_for_syphilis == 2)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenTreatedForSyphilisNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenTreatedForSyphilisDK" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="88" type="radio" <?php echo ($row->has_patient_ever_been_treated_for_syphilis == 88)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenTreatedForSyphilisDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenTreatedForSyphilisR" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="99" type="radio" <?php echo ($row->has_patient_ever_been_treated_for_syphilis == 99)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenTreatedForSyphilisR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenTreatedForSyphilisRNA" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="2222" type="radio" <?php echo ($row->has_patient_ever_been_treated_for_syphilis == 2222)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenTreatedForSyphilisRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
		    Q19. Have you ever received a vaccine (HPV vaccine) to prevent cervical cancer, which is caused by a common virus that can be passed through sexual contact?
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="hasPatientEverReceivedVaccineToPreventCervicalCancerYes" class="with-gap isRequired" name="hasPatientEverReceivedVaccineToPreventCervicalCancer" title="Please enter response for Q19" value="1" type="radio" <?php echo ($row->has_patient_ever_received_vaccine_to_prevent_cervical_cancer == 1)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverReceivedVaccineToPreventCervicalCancerYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverReceivedVaccineToPreventCervicalCancerNo" class="with-gap" name="hasPatientEverReceivedVaccineToPreventCervicalCancer" value="2" type="radio" <?php echo ($row->has_patient_ever_received_vaccine_to_prevent_cervical_cancer == 2)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverReceivedVaccineToPreventCervicalCancerNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverReceivedVaccineToPreventCervicalCancerDK" class="with-gap" name="hasPatientEverReceivedVaccineToPreventCervicalCancer" value="88" type="radio" <?php echo ($row->has_patient_ever_received_vaccine_to_prevent_cervical_cancer == 88)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverReceivedVaccineToPreventCervicalCancerDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverReceivedVaccineToPreventCervicalCancerR" class="with-gap" name="hasPatientEverReceivedVaccineToPreventCervicalCancer" value="99" type="radio" <?php echo ($row->has_patient_ever_received_vaccine_to_prevent_cervical_cancer == 99)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverReceivedVaccineToPreventCervicalCancerR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverReceivedVaccineToPreventCervicalCancerRNA" class="with-gap" name="hasPatientEverReceivedVaccineToPreventCervicalCancer" value="2222" type="radio" <?php echo ($row->has_patient_ever_received_vaccine_to_prevent_cervical_cancer == 2222)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverReceivedVaccineToPreventCervicalCancerRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Alcohol and drug use</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q20. During the past 6 months, on how many days did you have at least one drink containing alcohol? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="patientHadDrinkWithAlcoholInLastSixMonthsInDays" name="patientHadDrinkWithAlcoholInLastSixMonthsInDays" type="text" class="validate days checkNum <?php echo ($row->patient_had_drink_with_alcohol_in_last_six_months == null || trim($row->patient_had_drink_with_alcohol_in_last_six_months) == '')?'isRequired':''; ?>" title="Please enter response for Q20" value="<?php echo($row->patient_had_drink_with_alcohol_in_last_six_months!= null && trim($row->patient_had_drink_with_alcohol_in_last_six_months)!= '' && $row->patient_had_drink_with_alcohol_in_last_six_months[0] == '@')?substr($row->patient_had_drink_with_alcohol_in_last_six_months,1):'';?>" style="width:10%;"> Days&nbsp;
                    <input id="patientHadDrinkWithAlcoholInLastSixMonthsDK" class="with-gap" name="patientHadDrinkWithAlcoholInLastSixMonths" value="88" type="radio" <?php echo ($row->patient_had_drink_with_alcohol_in_last_six_months == 88)?'checked="checked"':''; ?>>
		    <label for="patientHadDrinkWithAlcoholInLastSixMonthsDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientHadDrinkWithAlcoholInLastSixMonthsR" class="with-gap" name="patientHadDrinkWithAlcoholInLastSixMonths" value="99" type="radio" <?php echo ($row->patient_had_drink_with_alcohol_in_last_six_months == 99)?'checked="checked"':''; ?>>
		    <label for="patientHadDrinkWithAlcoholInLastSixMonthsR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientHadDrinkWithAlcoholInLastSixMonthsRNA" class="with-gap" name="patientHadDrinkWithAlcoholInLastSixMonths" value="2222" type="radio" <?php echo ($row->patient_had_drink_with_alcohol_in_last_six_months == 2222)?'checked="checked"':''; ?>>
		    <label for="patientHadDrinkWithAlcoholInLastSixMonthsRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q21. How often do you have 4 or more drinks with alcohol on one occasion? * (e.g. within 2 hours)
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="hasPatientOftenHad4rmoreDrinksWithAlcoholOnOneOccasion" name="hasPatientOftenHad4rmoreDrinksWithAlcoholOnOneOccasion" class="material-select isRequired" title="Please enter response for Q21">
                        <option value=""> -- Select -- </option>
                        <option value="1" <?php echo ($row->has_patient_often_had_4rmore_drinks_with_alcohol_on_one_occasion == 1)?'selected="selected"':''; ?>>Never - 1</option>
                        <option value="2" <?php echo ($row->has_patient_often_had_4rmore_drinks_with_alcohol_on_one_occasion == 2)?'selected="selected"':''; ?>>Monthly - 2</option>
                        <option value="3" <?php echo ($row->has_patient_often_had_4rmore_drinks_with_alcohol_on_one_occasion == 3)?'selected="selected"':''; ?>>Weekly - 3</option>
                        <option value="4" <?php echo ($row->has_patient_often_had_4rmore_drinks_with_alcohol_on_one_occasion == 4)?'selected="selected"':''; ?>>Daily or On Most Days of The Week - 4</option>
                        <option value="88" <?php echo ($row->has_patient_often_had_4rmore_drinks_with_alcohol_on_one_occasion == 88)?'selected="selected"':''; ?>>Don't Know - 88</option>
                        <option value="99" <?php echo ($row->has_patient_often_had_4rmore_drinks_with_alcohol_on_one_occasion == 99)?'selected="selected"':''; ?>>Refused - 99</option>
			<option value="2222" <?php echo ($row->has_patient_often_had_4rmore_drinks_with_alcohol_on_one_occasion == 2222)?'selected="selected"':''; ?>>Response Not Available - 2222</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q22. Have you <span class="highlightedTxt">ever</span> tried recreational drugs? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    <input id="hasPatientEverTriedRecreationalDrugsYes" class="with-gap isRequired" name="hasPatientEverTriedRecreationalDrugs" title="Please enter response for Q22" value="1" type="radio" onchange="manageQ22();" <?php echo ($row->has_patient_ever_tried_recreational_drugs == 1)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverTriedRecreationalDrugsYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverTriedRecreationalDrugsNo" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="2" type="radio" onchange="manageQ22();" <?php echo ($row->has_patient_ever_tried_recreational_drugs == 2)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverTriedRecreationalDrugsNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverTriedRecreationalDrugsDK" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="88" type="radio" onchange="manageQ22();" <?php echo ($row->has_patient_ever_tried_recreational_drugs == 88)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverTriedRecreationalDrugsDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverTriedRecreationalDrugsR" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="99" type="radio" onchange="manageQ22();" <?php echo ($row->has_patient_ever_tried_recreational_drugs == 99)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverTriedRecreationalDrugsR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverTriedRecreationalDrugsRNA" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="2222" type="radio" onchange="manageQ22();" <?php echo ($row->has_patient_ever_tried_recreational_drugs == 2222)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverTriedRecreationalDrugsRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row recreationalDrugSection" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q22A. In the <span class="highlightedTxt">last 6 months</span>, have you taken any recreational drugs? <span class="recreationalDrugSectionRequired">*</span>
                </div>
            </div>
            <div class="row recreationalDrugSection" style="margin-bottom:0;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="hasPatientHadRecreationalDrugsInLastSixMonthsYes" class="with-gap isRequired" name="hasPatientHadRecreationalDrugsInLastSixMonths" title="Please enter response for Q22A" value="1" type="radio" onchange="setRecreationalDrugs();" <?php echo ($hasPatientHadRecreationalDrugsInLastSixMonths == 1)?'checked="checked"':'';?>>
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsNo" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="2" type="radio" onchange="setRecreationalDrugs();" <?php echo ($hasPatientHadRecreationalDrugsInLastSixMonths == 2)?'checked="checked"':'';?>>
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsDK" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="88" type="radio" onchange="setRecreationalDrugs();" <?php echo ($hasPatientHadRecreationalDrugsInLastSixMonths == 88)?'checked="checked"':'';?>>
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsR" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="99" type="radio" onchange="setRecreationalDrugs();" <?php echo ($hasPatientHadRecreationalDrugsInLastSixMonths == 99)?'checked="checked"':'';?>>
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsRNA" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="2222" type="radio" onchange="setRecreationalDrugs();" <?php echo ($hasPatientHadRecreationalDrugsInLastSixMonths == 2222)?'checked="checked"':'';?>>
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row recreationalDrugSection recreationalDrugs" style="margin-bottom:0;margin-top:16px;display:none;">
	        &nbsp;&nbsp;&nbsp;&nbsp;Specify Drug(s) <span class="recreationalDrugSectionRequired recreationalDrugsRequired">*</span> <input id="recreationalDrugs" name="recreationalDrugs" type="text" class="validate" title="Please enter recreational drugs" value="<?php echo $recreationalDrugs; ?>" style="width:40%;">
	    </div>
	    <h6 style="padding:10px 0px 10px 6px;font-size:16px;"><strong>Abuse</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q23. Have you ever been emotionally or physically abused by your partner or your loved one? *
                </div>
            </div>
            <div class="row" style="margin-bottom:20px;">
                <div class="col s12" style="margin-bottom:0px;">
                    <input id="hasPatientEverBeenAbusedBySomeoneYes" class="with-gap isRequired" name="hasPatientEverBeenAbusedBySomeone" title="Please enter response for Q23" value="1" type="radio" onchange="manageQ23();" <?php echo ($hasPatientAbusedBy == 1)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenAbusedBySomeoneYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenAbusedBySomeoneNo" class="with-gap" name="hasPatientEverBeenAbusedBySomeone" value="2" type="radio" onchange="manageQ23();" <?php echo ($hasPatientAbusedBy == 2)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenAbusedBySomeoneNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenAbusedBySomeoneDK" class="with-gap" name="hasPatientEverBeenAbusedBySomeone" value="88" type="radio" onchange="manageQ23();" <?php echo ($hasPatientAbusedBy == 88)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenAbusedBySomeoneDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenAbusedBySomeoneR" class="with-gap" name="hasPatientEverBeenAbusedBySomeone" value="99" type="radio" onchange="manageQ23();" <?php echo ($hasPatientAbusedBy == 99)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenAbusedBySomeoneR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenAbusedBySomeoneRNA" class="with-gap" name="hasPatientEverBeenAbusedBySomeone" value="2222" type="radio" onchange="manageQ23();" <?php echo ($hasPatientAbusedBy == 2222)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenAbusedBySomeoneRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row patientAbusedBySomeone" style="margin-bottom:5px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q23A. Who abused you? *
                </div>
            </div>
	    <div class="row patientAbusedBySomeone" style="margin-bottom:10px;display:none;">
                <div class="col s12" style="margin-bottom:0px;padding-left:4%;">
                    <input id="patientAbusedByH" class="with-gap" name="patientAbusedBy[]" title="Please enter response for Q23A" value="1" type="checkbox" onchange="setAbusedBy();" <?php echo(in_array(1,$patientAbusedBy))?'checked="checked"':''; ?>>
		    <label for="patientAbusedByH" class="active">Husband - 1</label>&nbsp;&nbsp;
                    <input id="patientAbusedByExH" class="with-gap" name="patientAbusedBy[]" value="2" type="checkbox" onchange="setAbusedBy();" <?php echo(in_array(2,$patientAbusedBy))?'checked="checked"':''; ?>>
		    <label for="patientAbusedByExH" class="active">Ex-Husband - 2</label>&nbsp;&nbsp;
                    <input id="patientAbusedByBf" class="with-gap" name="patientAbusedBy[]" value="3" type="checkbox" onchange="setAbusedBy();" <?php echo(in_array(3,$patientAbusedBy))?'checked="checked"':''; ?>>
		    <label for="patientAbusedByBf" class="active">Boyfriend - 3</label>&nbsp;&nbsp;
                    <input id="patientAbusedByS" class="with-gap" name="patientAbusedBy[]" value="4" type="checkbox" onchange="setAbusedBy();" <?php echo(in_array(4,$patientAbusedBy))?'checked="checked"':''; ?>>
		    <label for="patientAbusedByS" class="active">Stranger - 4</label>&nbsp;&nbsp;
		    <input id="patientAbusedByDK" class="with-gap" name="patientAbusedBy[]" value="88" type="checkbox" onchange="setAbusedBy();" <?php echo(in_array(88,$patientAbusedBy))?'checked="checked"':''; ?>>
		    <label for="patientAbusedByDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientAbusedByR" class="with-gap" name="patientAbusedBy[]" value="99" type="checkbox" onchange="setAbusedBy();" <?php echo(in_array(99,$patientAbusedBy))?'checked="checked"':''; ?>>
		    <label for="patientAbusedByR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientAbusedByRNA" class="with-gap" name="patientAbusedBy[]" value="2222" type="checkbox" onchange="setAbusedBy();" <?php echo(in_array(2222,$patientAbusedBy))?'checked="checked"':''; ?>>
		    <label for="patientAbusedByRNA" class="active">Response Not Available - 2222</label>&nbsp;&nbsp;
		    Other <input id="patientAbusedByOther" name="patientAbusedByOther" type="text" class="validate" value="<?php echo $patientAbusedByOther; ?>" onchange="setAbusedByOther();" style="width:20%;">
                </div>
            </div>
	    <div class="row patientAbusedBySomeone" style="margin-bottom:0;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q23B. How many times were you abused? *
                </div>
            </div>
            <div class="row patientAbusedBySomeone" style="margin-bottom:10px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="patientAbusedBySomeoneInNoofTimes" name="patientAbusedBySomeoneInNoofTimes" type="text" class="validate nooftimes checkNum" title="Please enter response for Q23B" value="<?php echo(trim($patientAbusedByInNoofTimes)!= '' && $patientAbusedByInNoofTimes[0] == '@')?substr($patientAbusedByInNoofTimes,1):'';?>" onchange="patientAbusedBySomeoneinNumbers('txt');" style="width:10%;"> Times&nbsp;
                    <input id="patientAbusedByNoofTimesDK" class="with-gap" name="patientAbusedByNoofTimes" value="88" type="radio" onchange="patientAbusedBySomeoneinNumbers('rd');" <?php echo($patientAbusedByInNoofTimes == 88)?'checked="checked"':''; ?>>
		    <label for="patientAbusedByNoofTimesDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientAbusedByNoofTimesR" class="with-gap" name="patientAbusedByNoofTimes" value="99" type="radio" onchange="patientAbusedBySomeoneinNumbers('rd');" <?php echo($patientAbusedByInNoofTimes == 99)?'checked="checked"':''; ?>>
		    <label for="patientAbusedByNoofTimesR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientAbusedByNoofTimesRNA" class="with-gap" name="patientAbusedByNoofTimes" value="2222" type="radio" onchange="patientAbusedBySomeoneinNumbers('rd');" <?php echo($patientAbusedByInNoofTimes == 2222)?'checked="checked"':''; ?>>
		    <label for="patientAbusedByNoofTimesRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q24. Within the last year, have you ever been hit, slapped, kicked, or otherwise physically hurt by someone? *
                </div>
            </div>
            <div class="row" style="margin-bottom:20px;">
                <div class="col s12" style="margin-bottom:0px;">
                    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearYes" class="with-gap isRequired" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" title="Please enter response for Q24" value="1" type="radio" onchange="manageQ24();" <?php echo($hasPatientHurtByWithinLastYear == 1)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearNo" class="with-gap" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" value="2" type="radio" onchange="manageQ24();" <?php echo($hasPatientHurtByWithinLastYear == 2)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearDK" class="with-gap" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" value="88" type="radio" onchange="manageQ24();" <?php echo($hasPatientHurtByWithinLastYear == 88)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearR" class="with-gap" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" value="99" type="radio" onchange="manageQ24();" <?php echo($hasPatientHurtByWithinLastYear == 99)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenHurtBySomeoneWithinLastYearRNA" class="with-gap" name="hasPatientEverBeenHurtBySomeoneWithinLastYear" value="2222" type="radio" onchange="manageQ24();" <?php echo($hasPatientHurtByWithinLastYear == 2222)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenHurtBySomeoneWithinLastYearRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row patientHurtBySomeoneWithinLastYear" style="margin-bottom:5px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q24A. Who hurt you? *
                </div>
            </div>
	    <div class="row patientHurtBySomeoneWithinLastYear" style="margin-bottom:10px;display:none;">
                <div class="col s12" style="margin-bottom:0px;padding-left:4%;">
                    <input id="patientHurtBySomeoneWithinLastYearH" class="with-gap" name="patientHurtBySomeoneWithinLastYear[]" title="Please enter response for Q24A" value="1" type="checkbox" onchange="setHurtBy();" <?php echo(in_array(1,$patientHurtByWithinLastYear))?'checked="checked"':''; ?>>
		    <label for="patientHurtBySomeoneWithinLastYearH" class="active">Husband - 1</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneWithinLastYearExH" class="with-gap" name="patientHurtBySomeoneWithinLastYear[]" value="2" type="checkbox" onchange="setHurtBy();" <?php echo(in_array(2,$patientHurtByWithinLastYear))?'checked="checked"':''; ?>>
		    <label for="patientHurtBySomeoneWithinLastYearExH" class="active">Ex-Husband - 2</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneWithinLastYearBf" class="with-gap" name="patientHurtBySomeoneWithinLastYear[]" value="3" type="checkbox" onchange="setHurtBy();" <?php echo(in_array(3,$patientHurtByWithinLastYear))?'checked="checked"':''; ?>>
		    <label for="patientHurtBySomeoneWithinLastYearBf" class="active">Boyfriend - 3</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneWithinLastYearS" class="with-gap" name="patientHurtBySomeoneWithinLastYear[]" value="4" type="checkbox" onchange="setHurtBy();" <?php echo(in_array(4,$patientHurtByWithinLastYear))?'checked="checked"':''; ?>>
		    <label for="patientHurtBySomeoneWithinLastYearS" class="active">Stranger - 4</label>&nbsp;&nbsp;
		    <input id="patientHurtBySomeoneWithinLastYearDK" class="with-gap" name="patientHurtBySomeoneWithinLastYear[]" value="88" type="checkbox" onchange="setHurtBy();" <?php echo(in_array(88,$patientHurtByWithinLastYear))?'checked="checked"':''; ?>>
		    <label for="patientHurtBySomeoneWithinLastYearDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneWithinLastYearR" class="with-gap" name="patientHurtBySomeoneWithinLastYear[]" value="99" type="checkbox" onchange="setHurtBy();" <?php echo(in_array(99,$patientHurtByWithinLastYear))?'checked="checked"':''; ?>>
		    <label for="patientHurtBySomeoneWithinLastYearR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientHurtBySomeoneWithinLastYearRNA" class="with-gap" name="patientHurtBySomeoneWithinLastYear[]" value="2222" type="checkbox" onchange="setHurtBy();" <?php echo(in_array(2222,$patientHurtByWithinLastYear))?'checked="checked"':''; ?>>
		    <label for="patientHurtBySomeoneWithinLastYearRNA" class="active">Response Not Available - 2222</label>&nbsp;&nbsp;
		    Other <input id="patientHurtByOther" name="patientHurtByOther" type="text" class="validate" onchange="setHurtByOther();" value="<?php echo $patientHurtByOtherWithinLastYear; ?>" style="width:20%;">
                </div>
            </div>
	    <div class="row patientHurtBySomeoneWithinLastYear" style="margin-bottom:0;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q24B. How many times were you hurt? *
                </div>
            </div>
            <div class="row patientHurtBySomeoneWithinLastYear" style="margin-bottom:10px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="patientHurtBySomeoneInNoofTimes" name="patientHurtBySomeoneInNoofTimes" type="text" class="validate nooftimes checkNum" title="Please enter response for Q24B" value="<?php echo(trim($patientHurtByInNoofTimes)!= '' && $patientHurtByInNoofTimes[0] == '@')?substr($patientHurtByInNoofTimes,1):'';?>" onchange="patientHurtBySomeoneinNumbers('txt');" style="width:10%;"> Times&nbsp;
                    <input id="patientHurtByNoofTimesDK" class="with-gap" name="patientHurtByNoofTimes" value="88" type="radio" onchange="patientHurtBySomeoneinNumbers('rd');" <?php echo($patientHurtByInNoofTimes == 88)?'checked="checked"':''; ?>>
		    <label for="patientHurtByNoofTimesDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientHurtByNoofTimesR" class="with-gap" name="patientHurtByNoofTimes" value="99" type="radio" onchange="patientHurtBySomeoneinNumbers('rd');" <?php echo($patientHurtByInNoofTimes == 99)?'checked="checked"':''; ?>>
		    <label for="patientHurtByNoofTimesR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientHurtByNoofTimesRNA" class="with-gap" name="patientHurtByNoofTimes" value="2222" type="radio" onchange="patientHurtBySomeoneinNumbers('rd');" <?php echo($patientHurtByInNoofTimes == 2222)?'checked="checked"':''; ?>>
		    <label for="patientHurtByNoofTimesRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row patientHurtBySomeoneDuringPregnancySection" style="margin-bottom:0;">
                <div class="col s12">
                    Q25. Since you've been pregnant have you been slapped, kicked or otherwise physically hurt by someone? <span class="patientHurtBySomeoneDuringPregnancySectionRequired">*</span>
                </div>
            </div>
            <div class="row patientHurtBySomeoneDuringPregnancySection" style="margin-bottom:20px;">
                <div class="col s12" style="margin-bottom:0px;">
                    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyYes" class="with-gap isRequired" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" title="Please enter response for Q25" value="1" type="radio" onchange="manageQ25();" <?php echo($hasPatientHurtByDuringPregnancy == 1)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyNo" class="with-gap" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" value="2" type="radio" onchange="manageQ25();" <?php echo($hasPatientHurtByDuringPregnancy == 2)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyDK" class="with-gap" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" value="88" type="radio" onchange="manageQ25();" <?php echo($hasPatientHurtByDuringPregnancy == 88)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyR" class="with-gap" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" value="99" type="radio" onchange="manageQ25();" <?php echo($hasPatientHurtByDuringPregnancy == 99)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenHurtBySomeoneDuringPregnancyRNA" class="with-gap" name="hasPatientEverBeenHurtBySomeoneDuringPregnancy" value="2222" type="radio" onchange="manageQ25();" <?php echo($hasPatientHurtByDuringPregnancy == 2222)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenHurtBySomeoneDuringPregnancyRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row patientHurtBySomeoneDuringPregnancy" style="margin-bottom:5px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q25A. Who hurt you? *
                </div>
            </div>
	    <div class="row patientHurtBySomeoneDuringPregnancy" style="margin-bottom:10px;display:none;">
                <div class="col s12" style="margin-bottom:0px;padding-left:4%;">
                    <input id="patientHurtBySomeoneDuringPregnancyH" class="with-gap" name="patientHurtBySomeoneDuringPregnancy[]" title="Please enter response for Q25A" value="1" type="checkbox" onchange="setHurtBySomoneDuringPregnancy();" <?php echo(in_array(1,$patientHurtByDuringPregnancy))?'checked="checked"':''; ?>>
		    <label for="patientHurtBySomeoneDuringPregnancyH" class="active">Husband - 1</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneDuringPregnancyExH" class="with-gap" name="patientHurtBySomeoneDuringPregnancy[]" value="2" type="checkbox" onchange="setHurtBySomoneDuringPregnancy();" <?php echo(in_array(2,$patientHurtByDuringPregnancy))?'checked="checked"':''; ?>>
		    <label for="patientHurtBySomeoneDuringPregnancyExH" class="active">Ex-Husband - 2</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneDuringPregnancyBf" class="with-gap" name="patientHurtBySomeoneDuringPregnancy[]" value="3" type="checkbox" onchange="setHurtBySomoneDuringPregnancy();" <?php echo(in_array(3,$patientHurtByDuringPregnancy))?'checked="checked"':''; ?>>
		    <label for="patientHurtBySomeoneDuringPregnancyBf" class="active">Boyfriend - 3</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneDuringPregnancyS" class="with-gap" name="patientHurtBySomeoneDuringPregnancy[]" value="4" type="checkbox" onchange="setHurtBySomoneDuringPregnancy();" <?php echo(in_array(4,$patientHurtByDuringPregnancy))?'checked="checked"':''; ?>>
		    <label for="patientHurtBySomeoneDuringPregnancyS" class="active">Stranger - 4</label>&nbsp;&nbsp;
		    <input id="patientHurtBySomeoneDuringPregnancyDK" class="with-gap" name="patientHurtBySomeoneDuringPregnancy[]" value="88" type="checkbox" onchange="setHurtBySomoneDuringPregnancy();" <?php echo(in_array(88,$patientHurtByDuringPregnancy))?'checked="checked"':''; ?>>
		    <label for="patientHurtBySomeoneDuringPregnancyDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientHurtBySomeoneDuringPregnancyR" class="with-gap" name="patientHurtBySomeoneDuringPregnancy[]" value="99" type="checkbox" onchange="setHurtBySomoneDuringPregnancy();" <?php echo(in_array(99,$patientHurtByDuringPregnancy))?'checked="checked"':''; ?>>
		    <label for="patientHurtBySomeoneDuringPregnancyR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientHurtBySomeoneDuringPregnancyRNA" class="with-gap" name="patientHurtBySomeoneDuringPregnancy[]" value="2222" type="checkbox" onchange="setHurtBySomoneDuringPregnancy();" <?php echo(in_array(2222,$patientHurtByDuringPregnancy))?'checked="checked"':''; ?>>
		    <label for="patientHurtBySomeoneDuringPregnancyRNA" class="active">Response Not Available - 2222</label>&nbsp;&nbsp;
		    Other <input id="patientHurtByOtherDuringPregnancy" name="patientHurtByOtherDuringPregnancy" type="text" class="validate" value="<?php echo $patientHurtByOtherDuringPregnancy; ?>" onchange="setHurtByOtherDuringPregnancy();" style="width:20%;">
                </div>
            </div>
	    <div class="row patientHurtBySomeoneDuringPregnancy" style="margin-bottom:0;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q25B. How many times were you hurt? *
                </div>
            </div>
            <div class="row patientHurtBySomeoneDuringPregnancy" style="margin-bottom:10px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="patientHurtBySomeoneDuringPregnancyInNoofTimes" name="patientHurtBySomeoneDuringPregnancyInNoofTimes" type="text" class="validate nooftimes checkNum" title="Please enter response for Q25B" value="<?php echo(trim($patientHurtByDuringPregnancyInNoofTimes)!= '' && $patientHurtByDuringPregnancyInNoofTimes[0] == '@')?substr($patientHurtByDuringPregnancyInNoofTimes,1):'';?>" onchange="patientHurtBySomeoneDuringPrenancyinNumbers('txt');" style="width:10%;"> Times&nbsp;
                    <input id="patientHurtByDuringPregnancyNoofTimesDK" class="with-gap" name="patientHurtByDuringPregnancyNoofTimes" value="88" type="radio" onchange="patientHurtBySomeoneDuringPrenancyinNumbers('rd');" <?php echo($patientHurtByDuringPregnancyInNoofTimes == 88)?'checked="checked"':''; ?>>
		    <label for="patientHurtByDuringPregnancyNoofTimesDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientHurtByDuringPregnancyNoofTimesR" class="with-gap" name="patientHurtByDuringPregnancyNoofTimes" value="99" type="radio" onchange="patientHurtBySomeoneDuringPrenancyinNumbers('rd');" <?php echo($patientHurtByDuringPregnancyInNoofTimes == 99)?'checked="checked"':''; ?>>
		    <label for="patientHurtByDuringPregnancyNoofTimesR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientHurtByDuringPregnancyNoofTimesRNA" class="with-gap" name="patientHurtByDuringPregnancyNoofTimes" value="2222" type="radio" onchange="patientHurtBySomeoneDuringPrenancyinNumbers('rd');" <?php echo($patientHurtByDuringPregnancyInNoofTimes == 2222)?'checked="checked"':''; ?>>
		    <label for="patientHurtByDuringPregnancyNoofTimesRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q26. Within the last year, has anyone forced you to have sexual activities? *
                </div>
            </div>
            <div class="row" style="margin-bottom:20px;">
                <div class="col s12" style="margin-bottom:0px;">
                    <input id="hasPatientEverBeenForcedForSexWithinLastYearYes" class="with-gap isRequired" name="hasPatientEverBeenForcedForSexWithinLastYear" title="Please enter response for Q26" value="1" type="radio" onchange="manageQ26();" <?php echo($hasPatientForcedforSexWithinLastYear == 1)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenForcedForSexWithinLastYearNo" class="with-gap" name="hasPatientEverBeenForcedForSexWithinLastYear" value="2" type="radio" onchange="manageQ26();" <?php echo($hasPatientForcedforSexWithinLastYear == 2)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenForcedForSexWithinLastYearDK" class="with-gap" name="hasPatientEverBeenForcedForSexWithinLastYear" value="88" type="radio" onchange="manageQ26();" <?php echo($hasPatientForcedforSexWithinLastYear == 88)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="hasPatientEverBeenForcedForSexWithinLastYearR" class="with-gap" name="hasPatientEverBeenForcedForSexWithinLastYear" value="99" type="radio" onchange="manageQ26();" <?php echo($hasPatientForcedforSexWithinLastYear == 99)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="hasPatientEverBeenForcedForSexWithinLastYearRNA" class="with-gap" name="hasPatientEverBeenForcedForSexWithinLastYear" value="2222" type="radio" onchange="manageQ26();" <?php echo($hasPatientForcedforSexWithinLastYear == 2222)?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenForcedForSexWithinLastYearRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row patientForcedForSexWithinLastYear" style="margin-bottom:5px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q26A. Who forced you? *
                </div>
            </div>
	    <div class="row patientForcedForSexWithinLastYear" style="margin-bottom:10px;display:none;">
                <div class="col s12" style="margin-bottom:0px;padding-left:4%;">
                    <input id="patientForcedForSexWithinLastYearH" class="with-gap" name="patientForcedForSexWithinLastYear[]" title="Please enter response for Q26A" value="1" type="checkbox" onchange="setPatientForcedforSexWithinLastYear();" <?php echo(in_array(1,$patientForcedforSexBy))?'checked="checked"':''; ?>>
		    <label for="patientForcedForSexWithinLastYearH" class="active">Husband </label>&nbsp;&nbsp;
                    <input id="patientForcedForSexWithinLastYearExH" class="with-gap" name="patientForcedForSexWithinLastYear[]" value="2" type="checkbox" onchange="setPatientForcedforSexWithinLastYear();" <?php echo(in_array(2,$patientForcedforSexBy))?'checked="checked"':''; ?>>
		    <label for="patientForcedForSexWithinLastYearExH" class="active">Ex-Husband </label>&nbsp;&nbsp;
                    <input id="patientForcedForSexWithinLastYearBf" class="with-gap" name="patientForcedForSexWithinLastYear[]" value="3" type="checkbox" onchange="setPatientForcedforSexWithinLastYear();" <?php echo(in_array(3,$patientForcedforSexBy))?'checked="checked"':''; ?>>
		    <label for="patientForcedForSexWithinLastYearBf" class="active">Boyfriend </label>&nbsp;&nbsp;
                    <input id="patientForcedForSexWithinLastYearS" class="with-gap" name="patientForcedForSexWithinLastYear[]" value="4" type="checkbox" onchange="setPatientForcedforSexWithinLastYear();" <?php echo(in_array(4,$patientForcedforSexBy))?'checked="checked"':''; ?>>
		    <label for="patientForcedForSexWithinLastYearS" class="active">Stranger</label>&nbsp;&nbsp;
		    <input id="patientForcedForSexWithinLastYearDK" class="with-gap" name="patientForcedForSexWithinLastYear[]" value="88" type="checkbox" onchange="setPatientForcedforSexWithinLastYear();" <?php echo(in_array(88,$patientForcedforSexBy))?'checked="checked"':''; ?>>
		    <label for="patientForcedForSexWithinLastYearDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientForcedForSexWithinLastYearR" class="with-gap" name="patientForcedForSexWithinLastYear[]" value="99" type="checkbox" onchange="setPatientForcedforSexWithinLastYear();" <?php echo(in_array(99,$patientForcedforSexBy))?'checked="checked"':''; ?>>
		    <label for="patientForcedForSexWithinLastYearR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientForcedForSexWithinLastYearRNA" class="with-gap" name="patientForcedForSexWithinLastYear[]" value="2222" type="checkbox" onchange="setPatientForcedforSexWithinLastYear();" <?php echo(in_array(2222,$patientForcedforSexBy))?'checked="checked"':''; ?>>
		    <label for="patientForcedForSexWithinLastYearRNA" class="active">Response Not Available - 2222</label>&nbsp;&nbsp;
		    Other <input id="patientForcedForSexByOtherWithinLastYear" name="patientForcedForSexByOtherWithinLastYear" type="text" class="validate" onchange="setForcedByOtherWithinLastYear();" value="<?php echo $patientForcedforSexByOther; ?>" style="width:20%;">
                </div>
            </div>
	    <div class="row patientForcedForSexWithinLastYear" style="margin-bottom:0;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Q26B. How many times were you forced? *
                </div>
            </div>
            <div class="row patientForcedForSexWithinLastYear" style="margin-bottom:10px;display:none;">
                <div class="col s12">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="patientForcedForSexInNoofTimes" name="patientForcedForSexInNoofTimes" type="text" class="validate nooftimes checkNum" title="Please enter response for Q26B" value="<?php echo(trim($patientForcedforSexInNoofTimes)!= '' && $patientForcedforSexInNoofTimes[0] == '@')?substr($patientForcedforSexInNoofTimes,1):'';?>" onchange="patientForcedforSexWithinLastYearinNumbers('txt');" style="width:10%;"> Times&nbsp;
                    <input id="patientForcedForSexNoofTimesDK" class="with-gap" name="patientForcedForSexNoofTimes" value="88" type="radio" onchange="patientForcedforSexWithinLastYearinNumbers('rd');" <?php echo($patientForcedforSexInNoofTimes == 88)?'checked="checked"':''; ?>>
		    <label for="patientForcedForSexNoofTimesDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="patientForcedForSexNoofTimesR" class="with-gap" name="patientForcedForSexNoofTimes" value="99" type="radio" onchange="patientForcedforSexWithinLastYearinNumbers('rd');" <?php echo($patientForcedforSexInNoofTimes == 99)?'checked="checked"':''; ?>>
		    <label for="patientForcedForSexNoofTimesR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="patientForcedForSexNoofTimesRNA" class="with-gap" name="patientForcedForSexNoofTimes" value="2222" type="radio" onchange="patientForcedforSexWithinLastYearinNumbers('rd');" <?php echo($patientForcedforSexInNoofTimes == 2222)?'checked="checked"':''; ?>>
		    <label for="patientForcedForSexNoofTimesRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
	    <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    Q27. Are you afraid of your partner or anyone listed above? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s12">
                    <input id="isPatientAfraidOfAnyoneYes" class="with-gap isRequired" name="isPatientAfraidOfAnyone" title="Please enter response for Q27" value="1" type="radio" <?php echo($row->is_patient_afraid_of_anyone == 1)?'checked="checked"':''; ?>>
		    <label for="isPatientAfraidOfAnyoneYes" class="active">Yes - 1</label>&nbsp;&nbsp;
                    <input id="isPatientAfraidOfAnyoneNo" class="with-gap" name="isPatientAfraidOfAnyone" value="2" type="radio" <?php echo($row->is_patient_afraid_of_anyone == 2)?'checked="checked"':''; ?>>
		    <label for="isPatientAfraidOfAnyoneNo" class="active">No - 2</label>&nbsp;&nbsp;
                    <input id="isPatientAfraidOfAnyoneDK" class="with-gap" name="isPatientAfraidOfAnyone" value="88" type="radio" <?php echo($row->is_patient_afraid_of_anyone == 88)?'checked="checked"':''; ?>>
		    <label for="isPatientAfraidOfAnyoneDK" class="active">Don't Know - 88</label>&nbsp;&nbsp;
                    <input id="isPatientAfraidOfAnyoneR" class="with-gap" name="isPatientAfraidOfAnyone" value="99" type="radio" <?php echo($row->is_patient_afraid_of_anyone == 99)?'checked="checked"':''; ?>>
		    <label for="isPatientAfraidOfAnyoneR" class="active">Refused - 99</label>&nbsp;&nbsp;
		    <input id="isPatientAfraidOfAnyoneRNA" class="with-gap" name="isPatientAfraidOfAnyone" value="2222" type="radio" <?php echo($row->is_patient_afraid_of_anyone == 2222)?'checked="checked"':''; ?>>
		    <label for="isPatientAfraidOfAnyoneRNA" class="active">Response Not Available - 2222</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="input-field col s6">
                    <textarea id="comment" name="comment" class="materialize-textarea" title="Please enter comments"><?php echo $row->comment; ?></textarea>
                    <label for="comment">Comments </label>
                </div>
            </div>
            <div class="col s12" style="margin-top:10px;">
		<input type="hidden" name="formVersion" value="1"/>
		<input type="hidden" id="participantEligibility" name="participantEligibility" value="1"/>
                <input id="riskAssessmentId" name="riskAssessmentId" type="hidden" value="<?php echo base64_encode($row->assessment_id); ?>"/>
                <input id="ancRapidRecencyId" name="ancRapidRecencyId" type="hidden" value="<?php echo (isset($row->anc_rapid_recency_id))?base64_encode($row->anc_rapid_recency_id):''; ?>"/>
                <input type="hidden" name="chosenCountry" id="chosenCountry" value="<?php echo base64_encode($countryId);?>"/>
                <input type="hidden" name="status" id="status" value="<?php echo base64_encode($row->status); ?>"/>
                <input type="hidden" name="redirectUrl" id="redirectUrl" value="<?php echo $link;?>"/>
                <a href="<?php echo $link;?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="updateRiskAssessment();">UPDATE</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/moment.min.js' ?>"></script>
<script>
    $(document).ready(function(){
        $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 100, // Creates a dropdown of 100 years to control year
            format: 'dd/mm/yyyy',
	    	max: new Date('Today'),
		    closeOnSelect: true,
		    closeOnClear: true,
		    onSet: function(e){
			if(e.select != undefined && e.select != null){
			    $('.picker__close').click();
			}
		    }
        });
       manageQ2();
       manageQ3('load');
       manageQ4();
       <?php if($row->partner_HIV_test_status == 3) { ?>
          manageQ9();
       <?php } else {
            if($row->age_of_main_sexual_partner_at_last_birthday!= null && trim($row->age_of_main_sexual_partner_at_last_birthday)!= '' && $row->age_of_main_sexual_partner_at_last_birthday[0] == '@'){
                $fromSrc = 'txt';
            }else{
                $fromSrc = 'rd';
            }
        ?>
         manageQ10('<?php echo $fromSrc; ?>');
         manageQ12();
       <?php } ?>
        manageQ13();
        manageQ17();
        manageQ22();
        manageQ23();
       <?php if($hasPatientAbusedBy == 1 && count($patientAbusedBy) >0){ ?> setAbusedBy(); <?php } ?>
       <?php if($hasPatientAbusedBy == 1 && trim($patientAbusedByOther)!= ''){ ?> setAbusedByOther(); <?php } ?>
       <?php if($hasPatientAbusedBy == 1 && trim($patientAbusedByInNoofTimes)!= '' && $patientAbusedByInNoofTimes[0] == '@'){
            $fromSrc = 'txt';
        }else{
            $fromSrc = 'rd';
        }
        ?>
        <?php if($hasPatientAbusedBy == 1) { ?> patientAbusedBySomeoneinNumbers('<?php echo $fromSrc; ?>'); <?php } ?>
        manageQ24();
        <?php if($hasPatientHurtByWithinLastYear == 1 && count($patientHurtByWithinLastYear) >0){ ?> setHurtBy(); <?php } ?>
        <?php if($hasPatientHurtByWithinLastYear == 1 && trim($patientHurtByOtherWithinLastYear)!= ''){ ?> setHurtByOther(); <?php } ?>
        <?php if($hasPatientHurtByWithinLastYear == 1 && trim($patientHurtByInNoofTimes)!= '' && $patientHurtByInNoofTimes[0] == '@'){
            $fromSrc = 'txt';
        }else{
            $fromSrc = 'rd';
        }
        ?>
        <?php if($hasPatientHurtByWithinLastYear == 1) { ?> patientHurtBySomeoneinNumbers('<?php echo $fromSrc; ?>'); <?php } ?>
        <?php if($hasPatientHurtByWithinLastYear == 1) { ?>
           manageQ25();
          <?php if($hasPatientHurtByDuringPregnancy == 1 && count($patientHurtByDuringPregnancy) >0){ ?> setHurtBySomoneDuringPregnancy(); <?php } ?>
          <?php if($hasPatientHurtByDuringPregnancy == 1 && trim($patientHurtByOtherDuringPregnancy)!= ''){ ?> setHurtByOtherDuringPregnancy(); <?php } ?>
          <?php if($hasPatientHurtByDuringPregnancy == 1 && trim($patientHurtByDuringPregnancyInNoofTimes)!= '' && $patientHurtByDuringPregnancyInNoofTimes[0] == '@'){
                $fromSrc = 'txt';
            }else{
                $fromSrc = 'rd';
            }
           ?>
           <?php if($hasPatientHurtByDuringPregnancy == 1) { ?> patientHurtBySomeoneDuringPrenancyinNumbers('<?php echo $fromSrc; ?>'); <?php } ?>
        <?php } ?>
        manageQ26();
        <?php if($hasPatientForcedforSexWithinLastYear == 1 && count($patientForcedforSexBy) >0){ ?> setPatientForcedforSexWithinLastYear(); <?php } ?>
        <?php if($hasPatientForcedforSexWithinLastYear == 1 && trim($patientForcedforSexByOther)!= ''){ ?> setForcedByOtherWithinLastYear(); <?php } ?>
        <?php if($hasPatientForcedforSexWithinLastYear == 1 && trim($patientForcedforSexInNoofTimes)!= '' && $patientForcedforSexInNoofTimes[0] == '@'){
                $fromSrc = 'txt';
            }else{
                $fromSrc = 'rd';
            }
           ?>
        <?php if($hasPatientForcedforSexWithinLastYear == 1) { ?> patientForcedforSexWithinLastYearinNumbers('<?php echo $fromSrc; ?>'); <?php } ?>
    });
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if($.trim(checkValue)!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
    
    //set occupation
    $('#occupation').on('change',function(){
	if(this.value == 1111){
	    $('.occupationNew').show();
	    $('#occupationNew').addClass('isRequired');
	    $('#occupationNew').focus();
	}else{
	   $('.occupationNew').hide();
	   $('#occupationNew').removeClass('isRequired'); 
	}
    });
    
    //set age at first marriage
    $('#ageAtFirstMarriageInYears').on('change',function() {
	setAgeAtFirstMarriage('txt');
    });
    $('input:radio[name=ageAtFirstMarriage]').change(function () {
	setAgeAtFirstMarriage('rd');
    });
    
    function setAgeAtFirstMarriage(fromSource){
        if(fromSource == 'txt'){
	    if($('#ageAtFirstMarriageInYears').val()!= ''){
		$('input[name="ageAtFirstMarriage"]:radio').prop('checked',false);
                $('#ageAtFirstMarriageInYears').addClass('isRequired');
                $('#ageAtFirstMarriageDK').removeClass('isRequired');
	    }else{
               $('#ageAtFirstMarriageDK').addClass('isRequired'); 
            }
	}else if(fromSource == 'rd'){
	   $('#ageAtFirstMarriageInYears').val('');
	   $('#ageAtFirstMarriageInYears').removeClass('isRequired');
	}
    }
    
    //set no.of sexual partners
    $('#noOfSexualPartnersInNumbers').on('change',function() {
	setNoOfSexualPartners('txt');
    });
    $('input:radio[name=noOfSexualPartners]').change(function () {
	setNoOfSexualPartners('rd');
    });
    function setNoOfSexualPartners(fromSource){
	if(fromSource == 'txt'){
	    if($('#noOfSexualPartnersInNumbers').val()!= ''){
		$('input[name="noOfSexualPartners"]:radio').prop('checked',false);
	    }
	    $('#noOfSexualPartnersInNumbers').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#noOfSexualPartnersInNumbers').val('');
	   $('#noOfSexualPartnersInNumbers').removeClass('isRequired');
	}
    }
    
    //set no.of sexual partners in last six months
    $('#noOfSexualPartnersInLastSixMonthsInNumbers').on('change',function() {
	setNoOfSexualPartnersInLastSixMonths('txt');
    });
    $('input:radio[name=noOfSexualPartnersInLastSixMonths]').change(function () {
	setNoOfSexualPartnersInLastSixMonths('rd');
    });
    function setNoOfSexualPartnersInLastSixMonths(fromSource){
	if(fromSource == 'txt'){
	    if($('#noOfSexualPartnersInLastSixMonthsInNumbers').val()!= ''){
		$('input[name="noOfSexualPartnersInLastSixMonths"]:radio').prop('checked',false);
	    }
	    $('#noOfSexualPartnersInLastSixMonthsInNumbers').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#noOfSexualPartnersInLastSixMonthsInNumbers').val('');
	   $('#noOfSexualPartnersInLastSixMonthsInNumbers').removeClass('isRequired');
	}
    }
    
    //set main sexual partner age at last birthday
    function manageQ10(fromSource){
	if(fromSource == 'txt'){
	    if($('#ageOfMainSexualPartnerAtLastBirthdayInYears').val()!= ''){
		$('.mainSexualPartnerAgeSectionRequired').css('visibility','hidden');
		$('.mainSexualPartnerAgeSection').css('color','rgba(0,0,0,0.26)');
		$('.mainSexualPartnerAgeSection').css('pointer-events','none');
		$('input[name="ageOfMainSexualPartnerAtLastBirthday"]:radio').prop('checked',false);
		$('#ageDiffOfMainSexualPartner').removeClass('isRequired');
	    }else{
		$('.mainSexualPartnerAgeSectionRequired').css('visibility','visible');
		$('.mainSexualPartnerAgeSection').css('color','');
		$('.mainSexualPartnerAgeSection').css('pointer-events','auto');
		$('#ageDiffOfMainSexualPartner').addClass('isRequired');
	    }
	    $('#ageOfMainSexualPartnerAtLastBirthdayInYears').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('.mainSexualPartnerAgeSectionRequired').css('visibility','visible');
	   $('.mainSexualPartnerAgeSection').css('color','');
	   $('.mainSexualPartnerAgeSection').css('pointer-events','auto');
	   $('#ageOfMainSexualPartnerAtLastBirthdayInYears').val('');
	   $('#ageOfMainSexualPartnerAtLastBirthdayInYears').removeClass('isRequired');
	   $('#ageDiffOfMainSexualPartner').addClass('isRequired');
	}
    }
    
    //set no.of days in last six months
    $('#patientHadDrinkWithAlcoholInLastSixMonthsInDays').on('change',function() {
        noOfDaysHadDrinkInLastSixMonth('txt');
    });
    $('input:radio[name=patientHadDrinkWithAlcoholInLastSixMonths]').change(function () {
	noOfDaysHadDrinkInLastSixMonth('rd');
    });
    function noOfDaysHadDrinkInLastSixMonth(fromSource){
	if(fromSource == 'txt'){
	    if($('#patientHadDrinkWithAlcoholInLastSixMonthsInDays').val()!= ''){
		$('input[name="patientHadDrinkWithAlcoholInLastSixMonths"]:radio').prop('checked',false);
	    }
	    $('#patientHadDrinkWithAlcoholInLastSixMonthsInDays').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#patientHadDrinkWithAlcoholInLastSixMonthsInDays').val('');
	   $('#patientHadDrinkWithAlcoholInLastSixMonthsInDays').removeClass('isRequired');
	}
    }
    
    //set patient abused by someone
    function manageQ23(){
        if ($("input[name='hasPatientEverBeenAbusedBySomeone']:checked").val() == 1) {
	    $('.patientAbusedBySomeone').show();
	    $('#patientAbusedByH,#patientAbusedBySomeoneInNoofTimes').addClass('isRequired');
	}else{
	  $('.patientAbusedBySomeone').hide();
	  $('input[name="patientAbusedBy[]"]:checkbox').prop('checked',false);
	  $('input[name="patientAbusedByNoofTimes"]:radio').prop('checked',false);
	  $('#patientAbusedByH,#patientAbusedBySomeoneInNoofTimes').removeClass('isRequired');
	  $('#patientAbusedBySomeoneInNoofTimes').val('');
	  resetPatientAbusedBySection();
	}
    }
    
    abusedByGroup = [1,2,3,4];
    notAbusedByGroup = [88,99,2222];
    function setAbusedBy(){
        var chk_arr =  document.getElementsByName('patientAbusedBy[]');
        abusedBy = [];
        for(k=0;k< chk_arr.length;k++){
            if($('#'+chk_arr[k].id).is(':checked')){
              abusedBy.push(chk_arr[k].value);  
            }
        }
	hasAbusedBy = false;
	hasNotAbusedBy = false;
	for(var i = 0;i < abusedBy.length; i++){
	    if(abusedByGroup.indexOf(parseInt(abusedBy[i]))!= -1){
		hasAbusedBy = true;
	    } if(notAbusedByGroup.indexOf(parseInt(abusedBy[i]))!= -1){
		hasNotAbusedBy = true;
                hasNotAbusedByVal = parseInt(abusedBy[i]);
	    }
	}
	if(hasAbusedBy){
	    $('#patientAbusedByDK,#patientAbusedByR,#patientAbusedByRNA').prop('checked',false);
	    $('label[for="patientAbusedByDK"]').css('pointer-events','none');
	    $('label[for="patientAbusedByR"]').css('pointer-events','none');
	    $('label[for="patientAbusedByRNA"]').css('pointer-events','none');
	    $('#patientAbusedByOther').css('pointer-events','none');
	    $('#patientAbusedByOther').val('');
	}else if(hasNotAbusedBy){
	    $('label[for="patientAbusedByH"]').css('pointer-events','none');
	    $('label[for="patientAbusedByExH"]').css('pointer-events','none');
	    $('label[for="patientAbusedByBf"]').css('pointer-events','none');
	    $('label[for="patientAbusedByS"]').css('pointer-events','none');
	    $('#patientAbusedByOther').css('pointer-events','none');
	    $('#patientAbusedByOther').val('');
	    if(hasNotAbusedByVal == 88){
		$('#patientAbusedByH,#patientAbusedByExH,#patientAbusedByBf,#patientAbusedByS,#patientAbusedByR,#patientAbusedByRNA').prop('checked',false);
		$('label[for="patientAbusedByR"]').css('pointer-events','none');
		$('label[for="patientAbusedByRNA"]').css('pointer-events','none');
	    }else if(hasNotAbusedByVal == 99){
		$('#patientAbusedByH,#patientAbusedByExH,#patientAbusedByBf,#patientAbusedByS,#patientAbusedByDK,#patientAbusedByRNA').prop('checked',false);
		$('label[for="patientAbusedByDK"]').css('pointer-events','none');
		$('label[for="patientAbusedByRNA"]').css('pointer-events','none');
	    }else if(hasNotAbusedByVal == 2222){
		$('#patientAbusedByH,#patientAbusedByExH,#patientAbusedByBf,#patientAbusedByS,#patientAbusedByDK,#patientAbusedByR').prop('checked',false);
		$('label[for="patientAbusedByDK"]').css('pointer-events','none');
		$('label[for="patientAbusedByR"]').css('pointer-events','none');
	    }
	    
	}else{
	    resetPatientAbusedBySection();
	}
    }
    
    function setAbusedByOther(){
	if($.trim($('#patientAbusedByOther').val())!= ''){
	    $('#patientAbusedByH').removeClass('isRequired');
	    $('#patientAbusedByH,#patientAbusedByExH,#patientAbusedByBf,#patientAbusedByS,#patientAbusedByDK,#patientAbusedByR,#patientAbusedByRNA').prop('checked',false);
	    $('label[for="patientAbusedByH"]').css('pointer-events','none');
	    $('label[for="patientAbusedByExH"]').css('pointer-events','none');
	    $('label[for="patientAbusedByBf"]').css('pointer-events','none');
	    $('label[for="patientAbusedByS"]').css('pointer-events','none');
	    $('label[for="patientAbusedByDK"]').css('pointer-events','none');
	    $('label[for="patientAbusedByR"]').css('pointer-events','none');
	    $('label[for="patientAbusedByRNA"]').css('pointer-events','none');
	}else{
	    $('#patientAbusedByH').addClass('isRequired');
	    resetPatientAbusedBySection();
	}
    }
    
    function patientAbusedBySomeoneinNumbers(fromSource){
	if(fromSource == 'txt'){
	    if($('#patientAbusedBySomeoneInNoofTimes').val()!= ''){
		$('#patientAbusedByNoofTimesDK,#patientAbusedByNoofTimesR,#patientAbusedByNoofTimesRNA').prop('checked',false);
	    }
	    $('#patientAbusedBySomeoneInNoofTimes').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#patientAbusedBySomeoneInNoofTimes').val('');
	   $('#patientAbusedBySomeoneInNoofTimes').removeClass('isRequired');
	}
    }
    
    function resetPatientAbusedBySection(){
	$('label[for="patientAbusedByH"]').css('pointer-events','auto');
	$('label[for="patientAbusedByExH"]').css('pointer-events','auto');
	$('label[for="patientAbusedByBf"]').css('pointer-events','auto');
	$('label[for="patientAbusedByS"]').css('pointer-events','auto');
	$('label[for="patientAbusedByDK"]').css('pointer-events','auto');
	$('label[for="patientAbusedByR"]').css('pointer-events','auto');
	$('label[for="patientAbusedByRNA"]').css('pointer-events','auto');
	$('#patientAbusedByOther').css('pointer-events','auto');
	$('#patientAbusedByOther').val('');
    }
    
    //set patient hurt by someone within last year
    function manageQ24(){
	skipToQ26($("input[name='hasPatientEverBeenHurtBySomeoneWithinLastYear']:checked").val());
        if ($("input[name='hasPatientEverBeenHurtBySomeoneWithinLastYear']:checked").val() == 1) {
	    $('.patientHurtBySomeoneWithinLastYear').show();
	    $('#patientHurtBySomeoneWithinLastYearH,#patientHurtBySomeoneInNoofTimes').addClass('isRequired');
	}else{
	    $('.patientHurtBySomeoneWithinLastYear').hide();
	    $('input[name="patientHurtBySomeoneWithinLastYear[]"]:checkbox').prop('checked',false);
	    $('input[name="patientHurtByNoofTimes"]:radio').prop('checked',false);
	    $('#patientHurtBySomeoneWithinLastYearH,#patientHurtBySomeoneInNoofTimes').removeClass('isRequired');
	    $('#patientHurtBySomeoneInNoofTimes').val('');
	    resetPatientHurtBySection();
	}
    }
    
    hurtByGroup = [1,2,3,4];
    notHurtByGroup = [88,99,2222];
    function setHurtBy(){
	var chk_arr =  document.getElementsByName('patientHurtBySomeoneWithinLastYear[]');
        hurtBy = [];
        for(k=0;k< chk_arr.length;k++){
            if($('#'+chk_arr[k].id).is(':checked')){
              hurtBy.push(chk_arr[k].value);  
            }
        }
	hasHurtBy = false;
	hasNotHurtBy = false;
	for(var i = 0;i < hurtBy.length; i++){
	    if(hurtByGroup.indexOf(parseInt(hurtBy[i]))!= -1){
		hasHurtBy = true;
	    } if(notHurtByGroup.indexOf(parseInt(hurtBy[i]))!= -1){
		hasNotHurtBy = true;
                hasNotHurtByVal = parseInt(hurtBy[i]);
	    }
	}
	if(hasHurtBy){
	    $('#patientHurtBySomeoneWithinLastYearDK,#patientHurtBySomeoneWithinLastYearR,#patientHurtBySomeoneWithinLastYearRNA').prop('checked',false);
	    $('label[for="patientHurtBySomeoneWithinLastYearDK"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearR"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearRNA"]').css('pointer-events','none');
	    $('#patientHurtByOther').css('pointer-events','none');
	    $('#patientHurtByOther').val('');
	}else if(hasNotHurtBy){
	    $('label[for="patientHurtBySomeoneWithinLastYearH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearExH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearBf"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearS"]').css('pointer-events','none');
	    $('#patientHurtByOther').css('pointer-events','none');
	    $('#patientHurtByOther').val('');
	    if(hasNotHurtByVal == 88){
		$('#patientHurtBySomeoneWithinLastYearH,#patientHurtBySomeoneWithinLastYearExH,#patientHurtBySomeoneWithinLastYearBf,#patientHurtBySomeoneWithinLastYearS,#patientHurtBySomeoneWithinLastYearR,#patientHurtBySomeoneWithinLastYearRNA').prop('checked',false);
		$('label[for="patientHurtBySomeoneWithinLastYearR"]').css('pointer-events','none');
		$('label[for="patientHurtBySomeoneWithinLastYearRNA"]').css('pointer-events','none');
	    }else if(hasNotHurtByVal == 99){
		$('#patientHurtBySomeoneWithinLastYearH,#patientHurtBySomeoneWithinLastYearExH,#patientHurtBySomeoneWithinLastYearBf,#patientHurtBySomeoneWithinLastYearS,#patientHurtBySomeoneWithinLastYearDK,#patientHurtBySomeoneWithinLastYearRNA').prop('checked',false);
		$('label[for="patientHurtBySomeoneWithinLastYearDK"]').css('pointer-events','none');
		$('label[for="patientHurtBySomeoneWithinLastYearRNA"]').css('pointer-events','none');
	    }else if(hasNotHurtByVal == 2222){
		$('#patientHurtBySomeoneWithinLastYearH,#patientHurtBySomeoneWithinLastYearExH,#patientHurtBySomeoneWithinLastYearBf,#patientHurtBySomeoneWithinLastYearS,#patientHurtBySomeoneWithinLastYearDK,#patientHurtBySomeoneWithinLastYearR').prop('checked',false);
		$('label[for="patientHurtBySomeoneWithinLastYearDK"]').css('pointer-events','none');
		$('label[for="patientHurtBySomeoneWithinLastYearR"]').css('pointer-events','none');
	    }
	    
	}else{
	    resetPatientHurtBySection();
	}
    }
    
    function setHurtByOther(){
	if($.trim($('#patientHurtByOther').val())!= ''){
	    $('#patientHurtBySomeoneWithinLastYearH').removeClass('isRequired');
	    $('#patientHurtBySomeoneWithinLastYearH,#patientHurtBySomeoneWithinLastYearExH,#patientHurtBySomeoneWithinLastYearBf,#patientHurtBySomeoneWithinLastYearS,#patientHurtBySomeoneWithinLastYearDK,#patientHurtBySomeoneWithinLastYearR,#patientHurtBySomeoneWithinLastYearRNA').prop('checked',false);
	    $('label[for="patientHurtBySomeoneWithinLastYearH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearExH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearBf"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearS"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearDK"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearR"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneWithinLastYearRNA"]').css('pointer-events','none');
	}else{
	    $('#patientHurtBySomeoneWithinLastYearH').addClass('isRequired');
	    resetPatientHurtBySection();
	}
    }
    
    function patientHurtBySomeoneinNumbers(fromSource){
	if(fromSource == 'txt'){
	    if($('#patientHurtBySomeoneInNoofTimes').val()!= ''){
		$('#patientHurtByNoofTimesDK,#patientHurtByNoofTimesR,#patientHurtByNoofTimesRNA').prop('checked',false);
	    }
	    $('#patientHurtBySomeoneInNoofTimes').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#patientHurtBySomeoneInNoofTimes').val('');
	   $('#patientHurtBySomeoneInNoofTimes').removeClass('isRequired');
	}
    }
    
    function resetPatientHurtBySection(){
	$('label[for="patientHurtBySomeoneWithinLastYearH"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneWithinLastYearExH"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneWithinLastYearBf"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneWithinLastYearS"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneWithinLastYearDK"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneWithinLastYearR"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneWithinLastYearRNA"]').css('pointer-events','auto');
	$('#patientHurtByOther').css('pointer-events','auto');
	$('#patientAbusedByOther').val('');
    }
    
    //set patient hurt by someone during pregnancy
    function manageQ25(){
        if ($("input[name='hasPatientEverBeenHurtBySomeoneDuringPregnancy']:checked").val() == 1) {
	    $('.patientHurtBySomeoneDuringPregnancy').show();
	    $('#patientHurtBySomeoneDuringPregnancyH,#patientHurtBySomeoneDuringPregnancyInNoofTimes').addClass('isRequired');
	}else{
	  $('.patientHurtBySomeoneDuringPregnancy').hide();
	  $('input[name="patientHurtBySomeoneDuringPregnancy[]"]:checkbox').prop('checked',false);
	  $('input[name="patientHurtByDuringPregnancyNoofTimes"]:radio').prop('checked',false);
	  $('#patientHurtBySomeoneDuringPregnancyH,#patientHurtBySomeoneDuringPregnancyInNoofTimes').removeClass('isRequired');
	  $('#patientHurtBySomeoneDuringPregnancyInNoofTimes').val('');
	  resetPatientHurtByDuringPregnancySection();
	}
    }
    
    hurtByDuringPregnancyGroup = [1,2,3,4];
    notHurtByDuringPregnancyGroup = [88,99,2222];
    function setHurtBySomoneDuringPregnancy(){
	var chk_arr =  document.getElementsByName('patientHurtBySomeoneDuringPregnancy[]');
        hurtByDuringPregnancy = [];
        for(k=0;k< chk_arr.length;k++){
            if($('#'+chk_arr[k].id).is(':checked')){
              hurtByDuringPregnancy.push(chk_arr[k].value);  
            }
        }
	hasHurtByDuringPregnancy = false;
	hasNotHurtByDuringPregnancy = false;
	for(var i = 0;i < hurtByDuringPregnancy.length; i++){
	    if(hurtByDuringPregnancyGroup.indexOf(parseInt(hurtByDuringPregnancy[i]))!= -1){
		hasHurtByDuringPregnancy = true;
	    } if(notHurtByDuringPregnancyGroup.indexOf(parseInt(hurtByDuringPregnancy[i]))!= -1){
		hasNotHurtByDuringPregnancy = true;
                hasNotHurtByDuringPregnancyVal = parseInt(hurtByDuringPregnancy[i]);
	    }
	}
	if(hasHurtByDuringPregnancy){
	    $('#patientHurtBySomeoneDuringPregnancyDK,#patientHurtBySomeoneDuringPregnancyR,#patientHurtBySomeoneDuringPregnancyRNA').prop('checked',false);
	    $('label[for="patientHurtBySomeoneDuringPregnancyDK"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyR"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyRNA"]').css('pointer-events','none');
	    $('#patientHurtByOtherDuringPregnancy').css('pointer-events','none');
	    $('#patientHurtByOtherDuringPregnancy').val('');
	}else if(hasNotHurtByDuringPregnancy){
	    $('label[for="patientHurtBySomeoneDuringPregnancyH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyExH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyBf"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyS"]').css('pointer-events','none');
	    $('#patientHurtByOtherDuringPregnancy').css('pointer-events','none');
	    $('#patientHurtByOtherDuringPregnancy').val('');
	    if(hasNotHurtByDuringPregnancyVal == 88){
		$('#patientHurtBySomeoneDuringPregnancyH,#patientHurtBySomeoneDuringPregnancyExH,#patientHurtBySomeoneDuringPregnancyBf,#patientHurtBySomeoneDuringPregnancyS,#patientHurtBySomeoneDuringPregnancyR,#patientHurtBySomeoneDuringPregnancyRNA').prop('checked',false);
		$('label[for="patientHurtBySomeoneDuringPregnancyR"]').css('pointer-events','none');
		$('label[for="patientHurtBySomeoneDuringPregnancyRNA"]').css('pointer-events','none');
	    }else if(hasNotHurtByDuringPregnancyVal == 99){
		$('#patientHurtBySomeoneDuringPregnancyH,#patientHurtBySomeoneDuringPregnancyExH,#patientHurtBySomeoneDuringPregnancyBf,#patientHurtBySomeoneDuringPregnancyS,#patientHurtBySomeoneDuringPregnancyDK,#patientHurtBySomeoneDuringPregnancyRNA').prop('checked',false);
		$('label[for="patientHurtBySomeoneDuringPregnancyDK"]').css('pointer-events','none');
		$('label[for="patientHurtBySomeoneDuringPregnancyRNA"]').css('pointer-events','none');
	    }else if(hasNotHurtByDuringPregnancyVal == 2222){
		$('#patientHurtBySomeoneDuringPregnancyH,#patientHurtBySomeoneDuringPregnancyExH,#patientHurtBySomeoneDuringPregnancyBf,#patientHurtBySomeoneDuringPregnancyS,#patientHurtBySomeoneDuringPregnancyDK,#patientHurtBySomeoneDuringPregnancyR').prop('checked',false);
		$('label[for="patientHurtBySomeoneDuringPregnancyDK"]').css('pointer-events','none');
		$('label[for="patientHurtBySomeoneDuringPregnancyR"]').css('pointer-events','none');
	    }
	    
	}else{
	    resetPatientHurtByDuringPregnancySection();
	}
    }
    
    function setHurtByOtherDuringPregnancy(){
	if($.trim($('#patientHurtByOtherDuringPregnancy').val())!= ''){
	    $('#patientHurtBySomeoneDuringPregnancyH').removeClass('isRequired');
	    $('#patientHurtBySomeoneDuringPregnancyH,#patientHurtBySomeoneDuringPregnancyExH,#patientHurtBySomeoneDuringPregnancyBf,#patientHurtBySomeoneDuringPregnancyS,#patientHurtBySomeoneDuringPregnancyDK,#patientHurtBySomeoneDuringPregnancyR,#patientHurtBySomeoneDuringPregnancyRNA').prop('checked',false);
	    $('label[for="patientHurtBySomeoneDuringPregnancyH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyExH"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyBf"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyS"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyDK"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyR"]').css('pointer-events','none');
	    $('label[for="patientHurtBySomeoneDuringPregnancyRNA"]').css('pointer-events','none');
	}else{
	    $('#patientHurtBySomeoneDuringPregnancyH').addClass('isRequired');
	    resetPatientHurtByDuringPregnancySection();
	}
    }
    
    function patientHurtBySomeoneDuringPrenancyinNumbers(fromSource){
	if(fromSource == 'txt'){
	    if($('#patientHurtBySomeoneDuringPregnancyInNoofTimes').val()!= ''){
		$('#patientHurtByDuringPregnancyNoofTimesDK,#patientHurtByDuringPregnancyNoofTimesR,#patientHurtByDuringPregnancyNoofTimesRNA').prop('checked',false);
	    }
	    $('#patientHurtBySomeoneDuringPregnancyInNoofTimes').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#patientHurtBySomeoneDuringPregnancyInNoofTimes').val('');
	   $('#patientHurtBySomeoneDuringPregnancyInNoofTimes').removeClass('isRequired');
	}
    }
    
    function resetPatientHurtByDuringPregnancySection(){
	$('label[for="patientHurtBySomeoneDuringPregnancyH"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneDuringPregnancyExH"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneDuringPregnancyBf"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneDuringPregnancyS"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneDuringPregnancyDK"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneDuringPregnancyR"]').css('pointer-events','auto');
	$('label[for="patientHurtBySomeoneDuringPregnancyRNA"]').css('pointer-events','auto');
	$('#patientHurtByOtherDuringPregnancy').css('pointer-events','auto');
	$('#patientHurtByOtherDuringPregnancy').val('');
    }
    
    //set patient forced for sex within last year
    function manageQ26(){
        if ($("input[name='hasPatientEverBeenForcedForSexWithinLastYear']:checked").val() == 1) {
	    $('.patientForcedForSexWithinLastYear').show();
	    $('#patientForcedForSexWithinLastYearH,#patientForcedForSexInNoofTimes').addClass('isRequired');
	}else{
	  $('.patientForcedForSexWithinLastYear').hide();
	  $('input[name="patientForcedForSexWithinLastYear[]"]:checkbox').prop('checked',false);
	  $('input[name="patientForcedForSexNoofTimes"]:radio').prop('checked',false);
	  $('#patientForcedForSexWithinLastYearH,#patientForcedForSexInNoofTimes').removeClass('isRequired');
	  $('#patientForcedForSexInNoofTimes').val('');
	  resetPatientForcedforSexWithinLastYearSection();
	}
    }
    
    forcedforSexByGroup = [1,2,3,4];
    notForcedforSexByGroup = [88,99,2222];
    function setPatientForcedforSexWithinLastYear(){
	var chk_arr =  document.getElementsByName('patientForcedForSexWithinLastYear[]');
        forcedforSexBy = [];
        for(k=0;k< chk_arr.length;k++){
            if($('#'+chk_arr[k].id).is(':checked')){
              forcedforSexBy.push(chk_arr[k].value);  
            }
        }
	hasForcedforSexBy = false;
	hasNotForcedforSexBy = false;
	for(var i = 0;i < forcedforSexBy.length; i++){
	    if(forcedforSexByGroup.indexOf(parseInt(forcedforSexBy[i]))!= -1){
		hasForcedforSexBy = true;
	    } if(notForcedforSexByGroup.indexOf(parseInt(forcedforSexBy[i]))!= -1){
		hasNotForcedforSexBy = true;
                hasNotForcedforSexByVal = parseInt(forcedforSexBy[i]);
	    }
	}
	if(hasForcedforSexBy){
	    $('#patientForcedForSexWithinLastYearDK,#patientForcedForSexWithinLastYearR,#patientForcedForSexWithinLastYearRNA').prop('checked',false);
	    $('label[for="patientForcedForSexWithinLastYearDK"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearR"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearRNA"]').css('pointer-events','none');
	    $('#patientForcedForSexByOtherWithinLastYear').css('pointer-events','none');
	    $('#patientForcedForSexByOtherWithinLastYear').val('');
	}else if(hasNotForcedforSexBy){
	    $('label[for="patientForcedForSexWithinLastYearH"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearExH"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearBf"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearS"]').css('pointer-events','none');
	    $('#patientForcedForSexByOtherWithinLastYear').css('pointer-events','none');
	    $('#patientForcedForSexByOtherWithinLastYear').val('');
	    if(hasNotForcedforSexByVal == 88){
		$('#patientForcedForSexWithinLastYearH,#patientForcedForSexWithinLastYearExH,#patientForcedForSexWithinLastYearBf,#patientForcedForSexWithinLastYearS,#patientForcedForSexWithinLastYearR,#patientForcedForSexWithinLastYearRNA').prop('checked',false);
		$('label[for="patientForcedForSexWithinLastYearR"]').css('pointer-events','none');
		$('label[for="patientForcedForSexWithinLastYearRNA"]').css('pointer-events','none');
	    }else if(hasNotForcedforSexByVal == 99){
		$('#patientForcedForSexWithinLastYearH,#patientForcedForSexWithinLastYearExH,#patientForcedForSexWithinLastYearBf,#patientForcedForSexWithinLastYearS,#patientForcedForSexWithinLastYearDK,#patientForcedForSexWithinLastYearRNA').prop('checked',false);
		$('label[for="patientForcedForSexWithinLastYearDK"]').css('pointer-events','none');
		$('label[for="patientForcedForSexWithinLastYearRNA"]').css('pointer-events','none');
	    }else if(hasNotForcedforSexByVal == 2222){
		$('#patientForcedForSexWithinLastYearH,#patientForcedForSexWithinLastYearExH,#patientForcedForSexWithinLastYearBf,#patientForcedForSexWithinLastYearS,#patientForcedForSexWithinLastYearDK,#patientForcedForSexWithinLastYearR').prop('checked',false);
		$('label[for="patientForcedForSexWithinLastYearDK"]').css('pointer-events','none');
		$('label[for="patientForcedForSexWithinLastYearR"]').css('pointer-events','none');
	    }
	    
	}else{
	    resetPatientForcedforSexWithinLastYearSection();
	}
    }
    
    function setForcedByOtherWithinLastYear(){
	if($.trim($('#patientForcedForSexByOtherWithinLastYear').val())!= ''){
	    $('#patientForcedForSexWithinLastYearH').removeClass('isRequired');
	    $('#patientForcedForSexWithinLastYearH,#patientForcedForSexWithinLastYearExH,#patientForcedForSexWithinLastYearBf,#patientForcedForSexWithinLastYearS,#patientForcedForSexWithinLastYearDK,#patientForcedForSexWithinLastYearR,#patientForcedForSexWithinLastYearRNA').prop('checked',false);
	    $('label[for="patientForcedForSexWithinLastYearH"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearExH"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearBf"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearS"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearDK"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearR"]').css('pointer-events','none');
	    $('label[for="patientForcedForSexWithinLastYearRNA"]').css('pointer-events','none');
	}else{
	    $('#patientForcedForSexWithinLastYearH').addClass('isRequired');
	    resetPatientForcedforSexWithinLastYearSection();
	}
    }
    
    function patientForcedforSexWithinLastYearinNumbers(fromSource){
	if(fromSource == 'txt'){
	    if($('#patientForcedForSexInNoofTimes').val()!= ''){
		$('#patientForcedForSexNoofTimesDK,#patientForcedForSexNoofTimesR,#patientForcedForSexNoofTimesRNA').prop('checked',false);
	    }
	    $('#patientForcedForSexInNoofTimes').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#patientForcedForSexInNoofTimes').val('');
	   $('#patientForcedForSexInNoofTimes').removeClass('isRequired');
	}
    }
    
    function resetPatientForcedforSexWithinLastYearSection(){
	$('label[for="patientForcedForSexWithinLastYearH"]').css('pointer-events','auto');
	$('label[for="patientForcedForSexWithinLastYearExH"]').css('pointer-events','auto');
	$('label[for="patientForcedForSexWithinLastYearBf"]').css('pointer-events','auto');
	$('label[for="patientForcedForSexWithinLastYearS"]').css('pointer-events','auto');
	$('label[for="patientForcedForSexWithinLastYearDK"]').css('pointer-events','auto');
	$('label[for="patientForcedForSexWithinLastYearR"]').css('pointer-events','auto');
	$('label[for="patientForcedForSexWithinLastYearRNA"]').css('pointer-events','auto');
	$('#patientForcedForSexByOtherWithinLastYear').css('pointer-events','auto');
	$('#patientForcedForSexByOtherWithinLastYear').val('');
    }
    
    function skipToQ26(val){
	if(val!= 1){
	   $('.patientHurtBySomeoneDuringPregnancySectionRequired').css('visibility','hidden');
	   $('.patientHurtBySomeoneDuringPregnancySection').css('color','rgba(0,0,0,0.26)');
	   $('.patientHurtBySomeoneDuringPregnancySection').css('pointer-events','none');
	   $('input[name="hasPatientEverBeenHurtBySomeoneDuringPregnancy"]:radio').prop('checked',false);
	   $('.patientHurtBySomeoneDuringPregnancy').hide();
	   $('input[name="patientHurtBySomeoneDuringPregnancy[]"]:checkbox').prop('checked',false);
	   $('input[name="patientHurtByDuringPregnancyNoofTimes"]:radio').prop('checked',false);
	   $('#hasPatientEverBeenHurtBySomeoneDuringPregnancyYes,#patientHurtBySomeoneDuringPregnancyH,#patientHurtBySomeoneDuringPregnancyInNoofTimes').removeClass('isRequired');
	   $('#patientHurtBySomeoneDuringPregnancyInNoofTimes').val('');
	   resetPatientHurtByDuringPregnancySection();
	}else{
	   $('.patientHurtBySomeoneDuringPregnancySectionRequired').css('visibility','visible');
	   $(".patientHurtBySomeoneDuringPregnancySection").css("color","");
	   $('.patientHurtBySomeoneDuringPregnancySection').css('pointer-events','auto');
	   $('#hasPatientEverBeenHurtBySomeoneDuringPregnancyYes').addClass('isRequired');
	}
    }
    
    //set patient recency test status
    $('input:radio[name=hasPatientHadRapidRecencyTest]').change(function () {
	if ($("input[name='hasPatientHadRapidRecencyTest']:checked").val() == 'done') {
	    $('#rtrSection').css('height','auto');
	    $('.rrrSection').show();
            $('#rrrControl,#rrrHIVDiagnostic,#rrrRecency').addClass('isRequired');
	}else{
	   $('#rtrSection').css('height','90px');
	   $('.rrrSection').hide();
	   //$('#rrrHIVDiagnostic option:first').prop('selected', true);
	   //$('#rrrRecency option:first').prop('selected', true);
           $('#rrrControl,#rrrHIVDiagnostic,#rrrRecency').removeClass('isRequired');
	}
    });
    
    //recency show/hide based on HIV diagostic
    $('#rrrHIVDiagnostic').on('change',function () {
	if ($('#rrrHIVDiagnostic').val() == 'negative') {
	    $('.rrrRecency').hide();
            $('#rrrRecency').removeClass('isRequired');
	}else{
	    $('.rrrRecency').show();
            $('#rrrRecency').addClass('isRequired');
	}
    });
    
    //enable/disable Demographic Characteristics fields based on q.2
    function manageQ2(){
	if ($("input[name='hasPatientEverAttendedSchool']:checked").val()!= 1) {
	    //css section
	    $(".degreeSectionRequired").css("visibility","hidden");
	    $(".degreeSection").css("color","rgba(0,0,0,0.26)");
	    $(".degree").css("pointer-events","none");
	    //validate/content section
	    $("#degree").removeClass("isRequired");
	}else{
	    //css section
	    $(".degreeSectionRequired").css("visibility","visible");
	    $(".degreeSection").css("color","");
	    $(".degree").css("pointer-events","auto");
	    //validate/content section
	    $("#degree").addClass("isRequired");
	}
    }
    //enable/disable Demographic Characteristics fields based on q.3
    function manageQ3(frmSrc){
	if ($("input[name='everBeenMarried']:checked").val() != 1) {
	    //css section
	    $(".everBeenMarriedSectionRequired").css("visibility","hidden");
	    $(".everBeenMarriedSection").css("color","rgba(0,0,0,0.26)");
	    $('#ageAtFirstMarriageInYears').css("pointer-events","none");
	    $("input[name='ageAtFirstMarriage']").attr("disabled","disabled");
	    $("input[name='everBeenWidowed']").attr("disabled","disabled");
	    $(".currentMaritalStatus").css("pointer-events","none");
	    //validate/content section
	    $("#ageAtFirstMarriageInYears").val("");
	    $('input[name="ageAtFirstMarriage"]:radio').prop('checked',false);
	    $('input[name="everBeenWidowed"]:radio').prop('checked',false);
	    $("#ageAtFirstMarriageInYears,#currentMaritalStatus").removeClass("isRequired");
	    $("input[name='ageAtFirstMarriage']").removeClass("isRequired");
	    $("input[name='everBeenWidowed']").removeClass("isRequired");
	    if (frmSrc == 'change' && $("input[name='everBeenMarried']:checked").val() == 2) {
		$("#currentMaritalStatus").val(2);
		$("#currentMaritalStatus").material_select();
		$('div').removeClass('isRequired');
	    }else{
		$("#currentMaritalStatus").val("");
	        $("#currentMaritalStatus").material_select();
		$('div').removeClass('isRequired');
	    }
	}else{
	    //css section
	    $(".everBeenMarriedSectionRequired").css("visibility","visible");
	    $(".everBeenMarriedSection").css("color","");
	    $('#ageAtFirstMarriageInYears').css("pointer-events","auto");
	    $("input[name='ageAtFirstMarriage']").removeAttr("disabled");
	    $("input[name='everBeenWidowed']").removeAttr("disabled");
	    $(".currentMaritalStatus").css("pointer-events","auto");
	    //validate/content section
	    if($.trim($("#ageAtFirstMarriageInYears").val()) == '') { $("#ageAtFirstMarriageDK").addClass("isRequired"); }
	    $("#currentMaritalStatus").addClass("isRequired");
	    $("input[name='everBeenWidowed']").addClass("isRequired");
	    if (frmSrc == 'change'){ $("#currentMaritalStatus").val(""); $("#currentMaritalStatus").material_select(); $('div').removeClass('isRequired'); }
	}
    }
    
    //enable/disable Demographic Characteristics fields based on q.4
    function manageQ4(){
	if ($("input[name='hasPatientEverBeenTestedforHIV']:checked").val() != 1) {
	    //css section
	    $(".everBeenTestedforHIVSectionRequired").css("visibility","hidden");
	    $(".everBeenTestedforHIVSection").css("color","rgba(0,0,0,0.26)");
	    $(".timeOfLastHIVTest").css("pointer-events","none");
	    $(".lastHIVTestStatus").css("pointer-events","none");
	    //validate/content section
	    $("#timeOfLastHIVTest,#lastHIVTestStatus").removeClass("isRequired");
	}else{
	    //css section
	    $(".everBeenTestedforHIVSectionRequired").css("visibility","visible");
	    $(".everBeenTestedforHIVSection").css("color","");
	    $(".timeOfLastHIVTest").css("pointer-events","auto");
	    $(".lastHIVTestStatus").css("pointer-events","auto");
	    //validate/content section
	    $("#timeOfLastHIVTest,#lastHIVTestStatus").addClass("isRequired");
	}
    }
    
    //partner HIV status
    function manageQ9(){
	if($.trim($('#partnerHIVTestStatus').val()) == 3){
	    $(".partnerHIVTestStatusRequired").css("visibility","hidden");
	    $(".partnerHIVTestStatus").css("color","rgba(0,0,0,0.26)");
	    $(".partnerHIVTestStatus").css("pointer-events","none");
	    $('#ageOfMainSexualPartnerAtLastBirthdayInYears').val("");
	    $('input[name="ageOfMainSexualPartnerAtLastBirthday"]:radio').prop('checked',false);
	    $('input[name="isPartnerCircumcised"]:radio').prop('checked',false);
	    $('#ageOfMainSexualPartnerAtLastBirthdayInYears,#ageDiffOfMainSexualPartner,#isPartnerCircumcisedYes,#circumcision').removeClass("isRequired");
	}else{
	   $(".partnerHIVTestStatusRequired").css("visibility","visible");
	   $(".partnerHIVTestStatus").css("color","");
	   $(".partnerHIVTestStatus").css("pointer-events","auto");
	   $('#ageOfMainSexualPartnerAtLastBirthdayInYears,#ageDiffOfMainSexualPartner,#isPartnerCircumcisedYes,#circumcision').addClass("isRequired");
	}
    }
    
    //patient circumcision status
    function manageQ12(){
	if ($("input[name='isPartnerCircumcised']:checked").val() != 1) {
	    $(".circumcisionSectionRequired").css("visibility","hidden");
	    $(".circumcisionSection").css("color","rgba(0,0,0,0.26)");
	    $(".circumcisionSection").css("pointer-events","none");
	    $("#circumcision").removeClass("isRequired");
	}else{
	   $(".circumcisionSectionRequired").css("visibility","visible");
	   $(".circumcisionSection").css("color","");
	   $(".circumcisionSection").css("pointer-events","auto");
	   $("#circumcision").addClass("isRequired");
	}
    }
    
    //patient received gift for sex
    function manageQ13(){
	if ($("input[name='hasPatientEverReceivedGiftForSex']:checked").val() != 1) {
	    $(".patinetReceivedGiftForSexSectionRequired").css("visibility","hidden");
	    $(".patinetReceivedGiftForSexSection").css("color","rgba(0,0,0,0.26)");
	    $(".patinetReceivedGiftForSexSection").css("pointer-events","none");
	    $("#lastTimeOfReceivingGiftForSex").removeClass("isRequired");
	}else{
	   $(".patinetReceivedGiftForSexSectionRequired").css("visibility","visible");
	   $(".patinetReceivedGiftForSexSection").css("color","");
	   $(".patinetReceivedGiftForSexSection").css("pointer-events","auto");
	   $("#lastTimeOfReceivingGiftForSex").addClass("isRequired");
	}
    }
    
    //treated for symptoms
    function manageQ17(){
	if ($("input[name='hasPatientHadPainInLowerAbdomen']:checked").val() != 1) {
	    $(".symptomsSectionRequired").css("visibility","hidden");
	    $(".symptomsSection").css("color","rgba(0,0,0,0.26)");
	    $(".symptomsSection").css("pointer-events","none");
	    $('input[name="hasPatientBeenTreatedForLowerAbdomenPain"]:radio').prop('checked',false);
	    $("#hasPatientBeenTreatedForLowerAbdomenPainYes").removeClass("isRequired");
	}else{
	    $(".symptomsSectionRequired").css("visibility","visible");
	    $(".symptomsSection").css("color","");
	    $(".symptomsSection").css("pointer-events","auto");
	    $("#hasPatientBeenTreatedForLowerAbdomenPainYes").addClass("isRequired");
	}
    }
    
    //recerational drugs
    function manageQ22(){
	if ($("input[name='hasPatientEverTriedRecreationalDrugs']:checked").val() != 1) {
	    $(".recreationalDrugSectionRequired").css("visibility","hidden");
	    $(".recreationalDrugSection").css("color","rgba(0,0,0,0.26)");
	    $(".recreationalDrugSection").css("pointer-events","none");
	    $('input[name="hasPatientHadRecreationalDrugsInLastSixMonths"]:radio').prop('checked',false);
	    $("#hasPatientHadRecreationalDrugsInLastSixMonthsYes").removeClass("isRequired");
	}else{
	    $(".recreationalDrugSectionRequired").css("visibility","visible");
	    $(".recreationalDrugSection").css("color","");
	    $(".recreationalDrugSection").css("pointer-events","auto");
	    $("#hasPatientHadRecreationalDrugsInLastSixMonthsYes").addClass("isRequired");
	}
	setRecreationalDrugs();
    }
    
    function setRecreationalDrugs(){
	if ($("input[name='hasPatientHadRecreationalDrugsInLastSixMonths']:checked").val() == 1) {
            $('.recreationalDrugs').show();
            $('#recreationalDrugs').addClass('isRequired');
            $('#recreationalDrugs').focus();
        }else{
           $('.recreationalDrugs').hide();
           $('#recreationalDrugs').val('');
           $('#recreationalDrugs').removeClass('isRequired');
        }
    }
    
    //set age at very first sex
    $('#ageAtVeryFirstSexInNumbers').on('change',function() {
        ageAtVeryFirstSex('txt');
    });
    $('input:radio[name=ageAtVeryFirstSex]').change(function () {
	ageAtVeryFirstSex('rd');
    });
    function ageAtVeryFirstSex(fromSource){
	if(fromSource == 'txt'){
	    if($('#ageAtVeryFirstSexInNumbers').val()!= ''){
		$('input[name="ageAtVeryFirstSex"]:radio').prop('checked',false);
	    }
	    $('#ageAtVeryFirstSexInNumbers').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#ageAtVeryFirstSexInNumbers').val('');
	   $('#ageAtVeryFirstSexInNumbers').removeClass('isRequired');
	}
    }
    
    //set no.of times been pregnant
    $('#noOfTimesBeenPregnantInNumbers').on('change',function() {
        totalNoofPregnancy('txt');
    });
    $('input:radio[name=noOfTimesBeenPregnant]').change(function () {
	totalNoofPregnancy('rd');
    });
    function totalNoofPregnancy(fromSource){
	if(fromSource == 'txt'){
	    if($('#noOfTimesBeenPregnantInNumbers').val()!= ''){
		$('input[name="noOfTimesBeenPregnant"]:radio').prop('checked',false);
	    }
	    $('#noOfTimesBeenPregnantInNumbers').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#noOfTimesBeenPregnantInNumbers').val('');
	   $('#noOfTimesBeenPregnantInNumbers').removeClass('isRequired');
	}
    }
    
    //age range validation
    $('.years').on('change',function() {
	var years = $('#'+this.id).val();
	if(parseInt(years) < 1 || parseInt(years) > 100) { alert('Age range should be 1-100'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    //person range validation
    $('.persons').on('change',function() {
	var persons = $('#'+this.id).val();
	if(parseInt(persons) > 10000) { alert('Person range should be 0-10,000'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    //pregnancy range validation
    $('.times').on('change',function() {
	var times = $('#'+this.id).val();
	if(parseInt(times) > 15) { alert('Pregnancy range should be 0-15'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    //alcohol days range validation
    $('.days').on('change',function() {
	var days = $('#'+this.id).val();
	if(parseInt(days) > 185) { alert('Days can\'t be more than 185'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    //patient hurt/forced to have sex range validation
    $('.nooftimes').on('change',function() {
	var nooftimes = $('#'+this.id).val();
	if(parseInt(nooftimes) > 10000) { alert('No.of times range should be 0-10,000'); $('#'+this.id).val(''); $('#'+this.id).focus(); }
    });
    
    function checkPatientRecord(){
	checkPatientBarcodeId();
    }
    
    function checkPatientBarcodeId(){
	var patientBarcodeId = $('#patientBarcodeId').val();
	var countryId = $('#chosenCountry').val();
	if($.trim(patientBarcodeId)!= '' && $.trim(countryId)!= ''){
            $.post("<?php echo $this->url('check-patient-record'); ?>", {assessmentId:'<?php echo base64_encode($row->assessment_id); ?>',patientBarcodeId: patientBarcodeId,countryId:countryId,type:'clinic'},
            function(data) {
                if ($.trim(data)!= '') { $.blockUI(); document.location.href = data; }
            });
        }
    }
    
    function updateRiskAssessment(){
        flag = deforayValidator.init({
            formId: 'editRiskAssessmentForm'
        });
	
        if(flag){
            document.getElementById('editRiskAssessmentForm').submit();
        }
    }
</script>