<?php
use Application\Service\CommonService;
$common = new CommonService();
if(!isset($countryId) || trim($countryId)== ''){
    $countryId = '';
    $link = "/clinic/risk-assessment";
}else{
    $link = "/clinic/risk-assessment/".base64_encode($countryId);
}
$interviewDate = '';
if(isset($row->interview_date) && $row->interview_date!= null && trim($row->interview_date)!= '' && $row->interview_date!= '0000-00-00'){
    $interviewDate = $common->viewDateFormat($row->interview_date);
}
?>
<style>
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        background-color: #eaeaea;
        border-bottom: 1px solid #ccc;
        padding: 10px 20px;
    }
    pre {
        max-height: 596px;
    }
    table.dataTable tbody td {
        padding: 8px 18px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        /*left: -184px*/
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Edit Risk Assessment</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="/" class="breadcrumb">Home</a>
            <a href="/clinic/risk-assessment/<?php echo base64_encode($countryId); ?>" class="breadcrumb">Risk Assessment Form</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Edit Risk Assessment</a>
       </div>
    </div>
    <div class="formContainer row dashboard-wrapper content-container" style="margin-bottom:20px;">
        <form id="editRiskAssessmentForm" name="editRiskAssessmentForm" method="post" action="<?php echo $this->url('edit-clinic-risk-assessment',array('action'=>'edit')); ?>">
        <div class="card">
            <h6 style="padding:10px 0px 10px 6px;font-size:16px;text-decoration:underline;"><strong>Sample Particpant Risk Questionnaire</strong></h6>
            <fieldset style="border-color:#2196F3;border-style:solid;">
                <div class="row" style="margin-bottom:0;">
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <select id="lab" name="lab" class="material-select isRequired" title="Please select facility">
                                <option value=""> -- Select -- </option>
                                <?php
                                foreach($facilities as $facility){
                                ?>
                                  <option value="<?php echo base64_encode($facility['facility_id']); ?>" <?php echo ($row->lab == $facility['facility_id'])?'selected="selected"':''; ?>><?php echo $facility['facility_code'].' - '.ucwords($facility['facility_name']); ?></option>
                                <?php } ?>
                            </select>
                            <label for="ancSite">Name of Facility *</label>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <input id="patientBarcodeId" name="patientBarcodeId" type="text" class="validate isRequired" title="Please enter patient barcode id" value="<?php echo $row->patient_barcode_id; ?>" onblur="checkPatientRecord('barcodeid');">
                            <label for="patientBarcodeId" class="">Patient Barcode ID *</label>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <input id="interviewerName" name="interviewerName" type="text" class="validate isRequired" title="Please enter interviewer name" value="<?php echo $row->interviewer_name; ?>">
                            <label for="interviewerName" class="">Interviewer Name *</label>
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-bottom:0;">
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <input id="ancPatientId" name="ancPatientId" type="text" class="validate isRequired" title="Please enter anc patient ID" value="<?php echo $row->anc_patient_id; ?>" onblur="checkPatientRecord('ancid');">
                            <label for="ancPatientId" class="">ANC Patient ID *</label>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <input id="interviewDate" name="interviewDate" type="text" class="validate isRequired datepicker" title="Please enter interview date" value="<?php echo $interviewDate; ?>">
                            <label for="interviewDate" class="">Interview Date *</label>
                        </div>
                    </div>
                </div>
            </fieldset>
            <h6 style="padding:10px 0px 10px 6px;font-size:16px;text-decoration:underline;"><strong>Demographic Characteristics</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    1. What kind of work/occupation do you do most of the time? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="occupation" name="occupation" class="material-select isRequired" title="Don't leave 1st question">
                        <option value=""> -- Select -- </option>
                        <?php
			foreach($occupationTypes as $occupation){
			?>
                           <option value="<?php echo base64_encode($occupation['occupation_id']); ?>" <?php echo ($row->patient_occupation == $occupation['occupation_id'])?'selected="selected"':''; ?>><?php echo ucwords($occupation['occupation']); ?></option>
			<?php } ?>
                        <option value="other">Other</option>
                    </select>
                </div>
		<div class="col s4 occupationNew" style="display:none;">
		    <input id="occupationNew" name="occupationNew" type="text" class="validate" placeholder="Occupation" title="Please enter occupation" onblur="checkNameValidation('occupation_type', 'occupation', this, null,'The occupation that you entered already listed. Please enter different occupation');">
		</div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    2. What was the highest level of school that you completed or are attending now? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="degree" name="degree" class="material-select isRequired" title="Don't leave 2nd question">
                        <option value=""> -- Select -- </option>
                        <option value="noedu" <?php echo ($row->patient_degree == 'noedu')?'selected="selected"':''; ?>>No Education</option>
                        <option value="primary" <?php echo ($row->patient_degree == 'primary')?'selected="selected"':''; ?>>Primary/Post-Primary/Vocational</option>
                        <option value="secondary" <?php echo ($row->patient_degree == 'secondary')?'selected="selected"':''; ?>>Secondary/Post-Secondary</option>
                        <option value="university" <?php echo ($row->patient_degree == 'university')?'selected="selected"':''; ?>>University/College</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    3. Have you ever been married or lived with a partner in a union as if married? * &nbsp;(If no, go to question 7)
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s4">
                    <input id="everBeenMarriedYes" class="with-gap isRequired" name="everBeenMarried" title="Don't leave 3rd question" value="yes" type="radio" <?php echo ($row->patient_ever_been_married == 'yes')?'checked="checked"':''; ?>>
		    <label for="everBeenMarriedYes" class="active">Yes </label>&nbsp&nbsp
                    <input id="everBeenMarriedNo" class="with-gap" name="everBeenMarried" value="no" type="radio" <?php echo ($row->patient_ever_been_married == 'no')?'checked="checked"':''; ?>>
		    <label for="everBeenMarriedNo" class="active">No </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    4. How old were you when you first got married or lived with a partner in a union? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s8">
                    <input id="ageAtFirstMarriageInYears" name="ageAtFirstMarriageInYears" type="text" class="validate <?php echo ($row->age_at_first_marriage == null || $row->age_at_first_marriage == '')?'isRequired':''; ?> checkNum" title="Please enter years" value="<?php echo($row->age_at_first_marriage!= null && trim($row->age_at_first_marriage)!= '' && is_numeric($row->age_at_first_marriage))?$row->age_at_first_marriage:'';?>" style="width:10%;"> Years&nbsp;
                    <input id="ageAtFirstMarriageDK" class="with-gap" name="ageAtFirstMarriage" value="dontknow" type="radio" <?php echo ($row->age_at_first_marriage == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="ageAtFirstMarriageDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="ageAtFirstMarriageR" class="with-gap" name="ageAtFirstMarriage" value="refused" type="radio" <?php echo ($row->age_at_first_marriage == 'refused')?'checked="checked"':''; ?>>
		    <label for="ageAtFirstMarriageR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    5. Have you ever been widowed? That is, did a spouse ever pass away while you were still married or living with them? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s6">
                    <input id="everBeenWidowedYes" class="with-gap isRequired" name="everBeenWidowed" title="Don't leave 5th question" value="yes" type="radio" <?php echo ($row->patient_ever_been_widowed == 'yes')?'checked="checked"':''; ?>>
		    <label for="everBeenWidowedYes" class="active">Yes </label>&nbsp&nbsp
                    <input id="everBeenWidowedNo" class="with-gap" name="everBeenWidowed" value="no" type="radio" <?php echo ($row->patient_ever_been_widowed == 'no')?'checked="checked"':''; ?>>
		    <label for="everBeenWidowedNo" class="active">No </label>&nbsp&nbsp
                    <input id="everBeenWidowedDK" class="with-gap" name="everBeenWidowed" value="dontknow" type="radio" <?php echo ($row->patient_ever_been_widowed == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="everBeenWidowedDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="everBeenWidowedR" class="with-gap" name="everBeenWidowed" value="refused" type="radio" <?php echo ($row->patient_ever_been_widowed == 'refused')?'checked="checked"':''; ?>>
		    <label for="everBeenWidowedR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    6. What is your marital status now? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="currentMaritalStatus" name="currentMaritalStatus" class="material-select isRequired" title="Don't leave 6th question">
                        <option value=""> -- Select -- </option>
                        <option value="married" <?php echo ($row->current_marital_status == 'married')?'selected="selected"':''; ?>>Married/Cohabiting</option>
                        <option value="nevermarried" <?php echo ($row->current_marital_status == 'nevermarried')?'selected="selected"':''; ?>>Never Married/Cohabiting</option>
                        <option value="widowed" <?php echo ($row->current_marital_status == 'widowed')?'selected="selected"':''; ?>>widowed</option>
                        <option value="separated" <?php echo ($row->current_marital_status == 'separated')?'selected="selected"':''; ?>>Separated</option>
                        <option value="divorced" <?php echo ($row->current_marital_status == 'divorced')?'selected="selected"':''; ?>>Divorced</option>
                        <option value="dontknow" <?php echo ($row->current_marital_status == 'dontknow')?'selected="selected"':''; ?>>Don't Know</option>
                        <option value="refused" <?php echo ($row->current_marital_status == 'refused')?'selected="selected"':''; ?>>Refused</option>
                    </select>
                </div>
            </div>
            <h6 style="padding:0px 0px 10px 6px;font-size:16px;text-decoration:underline;"><strong>HIV Testing History</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    7. When was the most recent time you were tested for HIV? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="timeOfLastHIVTest" name="timeOfLastHIVTest" class="material-select isRequired" title="Don't leave 7th question">
                        <option value=""> -- Select -- </option>
                        <option value="nevertested" <?php echo ($row->time_of_last_HIV_test == 'nevertested')?'selected="selected"':''; ?>>Never Tested</option>
                        <option value="lt3months" <?php echo ($row->time_of_last_HIV_test == 'lt3months')?'selected="selected"':''; ?>>< 3 Months Ago</option>
                        <option value="3to6months" <?php echo ($row->time_of_last_HIV_test == '3to6months')?'selected="selected"':''; ?>>3-6 Months Ago</option>
                        <option value="7to12months" <?php echo ($row->time_of_last_HIV_test == '7to12months')?'selected="selected"':''; ?>>7-12 Months Ago</option>
                        <option value="gt12months" <?php echo ($row->time_of_last_HIV_test == 'gt12months')?'selected="selected"':''; ?>> > 12 months</option>
                        <option value="dontknow" <?php echo ($row->time_of_last_HIV_test == 'dontknow')?'selected="selected"':''; ?>>Don't Know</option>
                        <option value="refused" <?php echo ($row->time_of_last_HIV_test == 'refused')?'selected="selected"':''; ?>>Refused</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    8. What was the result of that HIV test? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="lastHIVTestStatus" name="lastHIVTestStatus" class="material-select isRequired" title="Don't leave 8th question">
                        <option value=""> -- Select -- </option>
                        <option value="didnotreceive" <?php echo ($row->last_HIV_test_status == 'didnotreceive')?'selected="selected"':''; ?>>I Did Not Receive Result</option>
                        <option value="hivpos" <?php echo ($row->last_HIV_test_status == 'hivpos')?'selected="selected"':''; ?>>HIV+</option>
                        <option value="hivneg" <?php echo ($row->last_HIV_test_status == 'hivneg')?'selected="selected"':''; ?>>HIV-</option>
                        <option value="indeterminate" <?php echo ($row->last_HIV_test_status == 'indeterminate')?'selected="selected"':''; ?>>Indeterminate</option>
                        <option value="dontknow" <?php echo ($row->last_HIV_test_status == 'dontknow')?'selected="selected"':''; ?>>Don't Know</option>
                        <option value="refused" <?php echo ($row->last_HIV_test_status == 'refused')?'selected="selected"':''; ?>>Refused</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    9. What is your spouse/main sexual partner's HIV status? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="partnerHIVTestStatus" name="partnerHIVTestStatus" class="material-select isRequired" title="Don't leave 9th question">
                        <option value=""> -- Select -- </option>
                        <option value="hivpos" <?php echo ($row->partner_HIV_test_status == 'hivpos')?'selected="selected"':''; ?>>HIV+</option>
                        <option value="hivneg" <?php echo ($row->partner_HIV_test_status == 'hivneg')?'selected="selected"':''; ?>>HIV-</option>
                        <option value="idonotknow" <?php echo ($row->partner_HIV_test_status == 'idonotknow')?'selected="selected"':''; ?>>I Do Not Know</option>
                        <option value="refused" <?php echo ($row->partner_HIV_test_status == 'refused')?'selected="selected"':''; ?>>Refused</option>
                    </select>
                </div>
            </div>
            <h6 style="padding:0px 0px 10px 6px;font-size:16px;text-decoration:underline;"><strong>Sexual Activity and History of Sexually Transmitted Infections</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    10. How old were you when you had sexual intercourse for the very first time? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <input id="ageAtVeryFirstSex" name="ageAtVeryFirstSex" type="text" class="validate isRequired checkNum" title="Please enter years" value="<?php echo $row->age_at_very_first_sex; ?>" style="width:20%;"> Years
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    11. The first time you had sex, was it because you wanted to or because you were forced to? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s6">
                    <input id="reasonForVeryFirstSexWT" class="with-gap isRequired" name="reasonForVeryFirstSex" title="Don't leave 11th question" value="wantedto" type="radio" <?php echo ($row->reason_for_very_first_sex == 'wantedto')?'checked="checked"':''; ?>>
		    <label for="reasonForVeryFirstSexWT" class="active">Wanted To </label>&nbsp&nbsp
                    <input id="reasonForVeryFirstSexFT" class="with-gap" name="reasonForVeryFirstSex" value="forcedto" type="radio" <?php echo ($row->reason_for_very_first_sex == 'forcedto')?'checked="checked"':''; ?>>
		    <label for="reasonForVeryFirstSexFT" class="active">Forced To </label>&nbsp&nbsp
                    <input id="reasonForVeryFirstSexDK" class="with-gap" name="reasonForVeryFirstSex" value="dontknow" type="radio" <?php echo ($row->reason_for_very_first_sex == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="reasonForVeryFirstSexDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="reasonForVeryFirstSexR" class="with-gap" name="reasonForVeryFirstSex" value="refused" type="radio" <?php echo ($row->reason_for_very_first_sex == 'refused')?'checked="checked"':''; ?>>
		    <label for="reasonForVeryFirstSexR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    12. How many different people have you had sexual intercourse with in your entire life? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s6">
                    <input id="noOfSexualPartnersInNumbers" name="noOfSexualPartnersInNumbers" type="text" class="validate <?php echo ($row->no_of_sexual_partners== null || trim($row->no_of_sexual_partners) == '')?'isRequired':''; ?> checkNum" title="Please enter no. of persons" value="<?php echo($row->no_of_sexual_partners!= null && trim($row->no_of_sexual_partners)!= '' && is_numeric($row->no_of_sexual_partners))?$row->no_of_sexual_partners:'';?>" style="width:10%;"> Persons&nbsp;
                    <input id="noOfSexualPartnersDK" class="with-gap" name="noOfSexualPartners" value="dontknow" type="radio" <?php echo ($row->no_of_sexual_partners == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="noOfSexualPartnersDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="noOfSexualPartnersR" class="with-gap" name="noOfSexualPartners" value="refused" type="radio" <?php echo ($row->no_of_sexual_partners == 'refused')?'checked="checked"':''; ?>>
		    <label for="noOfSexualPartnersR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    13. How many different people have you had sex with in the last 6 months? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s6">
                    <input id="noOfSexualPartnersInLastSixMonthsInNumbers" name="noOfSexualPartnersInLastSixMonthsInNumbers" type="text" class="validate <?php echo ($row->no_of_sexual_partners_in_last_six_months == null || $row->no_of_sexual_partners_in_last_six_months == '')?'isRequired':''; ?> checkNum" title="Please enter no. of persons" value="<?php echo($row->no_of_sexual_partners_in_last_six_months!= null && trim($row->no_of_sexual_partners_in_last_six_months)!= '' && is_numeric($row->no_of_sexual_partners_in_last_six_months))?$row->no_of_sexual_partners_in_last_six_months:'';?>" style="width:10%;"> Persons&nbsp;
                    <input id="noOfSexualPartnersInLastSixMonthsDK" class="with-gap" name="noOfSexualPartnersInLastSixMonths" value="dontknow" type="radio" <?php echo ($row->no_of_sexual_partners_in_last_six_months == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="noOfSexualPartnersInLastSixMonthsDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="noOfSexualPartnersInLastSixMonthsR" class="with-gap" name="noOfSexualPartnersInLastSixMonths" value="refused" type="radio" <?php echo ($row->no_of_sexual_partners_in_last_six_months == 'refused')?'checked="checked"':''; ?>>
		    <label for="noOfSexualPartnersInLastSixMonthsR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    14. How old was your main sexual partner on his last birthday? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s6">
                    <input id="ageOfMainSexualPartnerAtLastBirthdayInYears" name="ageOfMainSexualPartnerAtLastBirthdayInYears" type="text" class="validate <?php echo ($row->age_of_main_sexual_partner_at_last_birthday == null || $row->age_of_main_sexual_partner_at_last_birthday == '')?'isRequired':''; ?> checkNum" title="Please enter years" value="<?php echo($row->age_of_main_sexual_partner_at_last_birthday!= null && trim($row->age_of_main_sexual_partner_at_last_birthday)!= '' && is_numeric($row->age_of_main_sexual_partner_at_last_birthday))?$row->age_of_main_sexual_partner_at_last_birthday:'';?>" style="width:10%;"> Years&nbsp;
                    <input id="ageOfMainSexualPartnerAtLastBirthdayDK" class="with-gap" name="ageOfMainSexualPartnerAtLastBirthday" value="dontknow" type="radio" <?php echo ($row->age_of_main_sexual_partner_at_last_birthday == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="ageOfMainSexualPartnerAtLastBirthdayDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="ageOfMainSexualPartnerAtLastBirthdayR" class="with-gap" name="ageOfMainSexualPartnerAtLastBirthday" value="refused" type="radio" <?php echo ($row->age_of_main_sexual_partner_at_last_birthday == 'refused')?'checked="checked"':''; ?>>
		    <label for="ageOfMainSexualPartnerAtLastBirthdayR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    15. Is the age of your main sexual partner older, younger, or the same age as you? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="ageDiffOfMainSexualPartner" name="ageDiffOfMainSexualPartner" class="material-select isRequired" title="Don't leave 15th question">
                        <option value=""> -- Select -- </option>
                        <option value="lt5yearolder" <?php echo ($row->age_diff_of_main_sexual_partner == 'lt5yearolder')?'selected="selected"':''; ?>> < 5 Years Older</option>
                        <option value="5to10yearolder" <?php echo ($row->age_diff_of_main_sexual_partner == '5to10yearolder')?'selected="selected"':''; ?>> 5-10 Years Older</option>
                        <option value="10yearsolder" <?php echo ($row->age_diff_of_main_sexual_partner == '10yearsolder')?'selected="selected"':''; ?>> >10 Years Older</option>
                        <option value="sameage" <?php echo ($row->age_diff_of_main_sexual_partner == 'sameage')?'selected="selected"':''; ?>>Same Age</option>
                        <option value="lt5yearyounger" <?php echo ($row->age_diff_of_main_sexual_partner == 'lt5yearyounger')?'selected="selected"':''; ?>> < 5 Years Younger</option>
                        <option value="5to10yearyounger" <?php echo ($row->age_diff_of_main_sexual_partner == '5to10yearyounger')?'selected="selected"':''; ?>>5-10 Years Younger</option>
                        <option value="gt10yearyounger" <?php echo ($row->age_diff_of_main_sexual_partner == 'gt10yearyounger')?'selected="selected"':''; ?>> >10 Years Younger</option>
                        <option value="dontknow" <?php echo ($row->age_diff_of_main_sexual_partner == 'dontknow')?'selected="selected"':''; ?>>Don't Know</option>
                        <option value="refused" <?php echo ($row->age_diff_of_main_sexual_partner == 'refused')?'selected="selected"':''; ?>>Refused</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    16. Is your main sexual partner circumcised? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s6">
                    <input id="isPartnerCircumcisedYes" class="with-gap isRequired" name="isPartnerCircumcised" title="Don't leave 16th question" value="yes" type="radio" <?php echo ($row->is_partner_circumcised == 'yes')?'checked="checked"':''; ?>>
		    <label for="isPartnerCircumcisedYes" class="active">Yes </label>&nbsp&nbsp
                    <input id="isPartnerCircumcisedNo" class="with-gap" name="isPartnerCircumcised" value="no" type="radio" <?php echo ($row->is_partner_circumcised == 'no')?'checked="checked"':''; ?>>
		    <label for="isPartnerCircumcisedNo" class="active">No </label>&nbsp&nbsp
                    <input id="isPartnerCircumcisedDK" class="with-gap" name="isPartnerCircumcised" value="dontknow" type="radio" <?php echo ($row->is_partner_circumcised == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="isPartnerCircumcisedDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="isPartnerCircumcisedR" class="with-gap" name="isPartnerCircumcised" value="refused" type="radio" <?php echo ($row->is_partner_circumcised == 'refused')?'checked="checked"':''; ?>>
		    <label for="isPartnerCircumcisedR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    17. When did you last receive money/gifts in exchange for sex? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="lastTimeOfReceivingGiftForSex" name="lastTimeOfReceivingGiftForSex" class="material-select isRequired" title="Don't leave 17th question">
                        <option value=""> -- Select -- </option>
                        <option value="never" <?php echo ($row->last_time_of_receiving_gift_for_sex == 'never')?'selected="selected"':''; ?>> Never</option>
                        <option value="lt6months" <?php echo ($row->last_time_of_receiving_gift_for_sex == 'lt6months')?'selected="selected"':''; ?>> < 6 Months Ago</option>
                        <option value="6to12months" <?php echo ($row->last_time_of_receiving_gift_for_sex == '6to12months')?'selected="selected"':''; ?>> 6-12 Months Ago</option>
                        <option value="gt12months" <?php echo ($row->last_time_of_receiving_gift_for_sex == 'gt12months')?'selected="selected"':''; ?>> > 12 Months Ago</option>
                        <option value="dontknow" <?php echo ($row->last_time_of_receiving_gift_for_sex == 'dontknow')?'selected="selected"':''; ?>>Don't Know</option>
                        <option value="refused" <?php echo ($row->last_time_of_receiving_gift_for_sex == 'refused')?'selected="selected"':''; ?>>Refused</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    18. How many times have you been pregnant? * (including this pregnancy)
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <input id="noOfTimesBeenPregnant" name="noOfTimesBeenPregnant" type="text" class="validate isRequired checkNum" title="Don't leave 18th question" value="<?php echo $row->no_of_times_been_pregnant; ?>" style="width:20%;"> Times
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    19. Before becoming pregnant this time, in the past year how frequently did you use a condom when having sexual intercourse? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s8">
                    <input id="noOfTimesCondomUsedBeforePregnancyA" class="with-gap isRequired" name="noOfTimesCondomUsedBeforePregnancy" title="Don't leave 19th question" value="always" type="radio" <?php echo ($row->no_of_times_condom_used_before_pregnancy == 'always')?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedBeforePregnancyA" class="active">Always </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedBeforePregnancyS" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="sometimes" type="radio" <?php echo ($row->no_of_times_condom_used_before_pregnancy == 'sometimes')?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedBeforePregnancyS" class="active">Sometimes </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedBeforePregnancyN" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="never" type="radio" <?php echo ($row->no_of_times_condom_used_before_pregnancy == 'never')?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedBeforePregnancyN" class="active">Never </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedBeforePregnancyDK" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="dontknow" type="radio" <?php echo ($row->no_of_times_condom_used_before_pregnancy == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedBeforePregnancyDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedBeforePregnancyR" class="with-gap" name="noOfTimesCondomUsedBeforePregnancy" value="refused" type="radio" <?php echo ($row->no_of_times_condom_used_before_pregnancy == 'refused')?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedBeforePregnancyR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    20. Since becoming pregnant this time, how frequently have you used a condom when having sexual intercourse? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s8">
                    <input id="noOfTimesCondomUsedAfterPregnancyA" class="with-gap isRequired" name="noOfTimesCondomUsedAfterPregnancy" title="Don't leave 20th question" value="always" type="radio" <?php echo ($row->no_of_times_condom_used_after_pregnancy == 'always')?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedAfterPregnancyA" class="active">Always </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedAfterPregnancyS" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="sometimes" type="radio" <?php echo ($row->no_of_times_condom_used_after_pregnancy == 'sometimes')?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedAfterPregnancyS" class="active">Sometimes </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedAfterPregnancyN" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="never" type="radio" <?php echo ($row->no_of_times_condom_used_after_pregnancy == 'never')?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedAfterPregnancyN" class="active">Never </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedAfterPregnancyDK" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="dontknow" type="radio" <?php echo ($row->no_of_times_condom_used_after_pregnancy == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedAfterPregnancyDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="noOfTimesCondomUsedAfterPregnancyR" class="with-gap" name="noOfTimesCondomUsedAfterPregnancy" value="refused" type="radio" <?php echo ($row->no_of_times_condom_used_after_pregnancy == 'refused')?'checked="checked"':''; ?>>
		    <label for="noOfTimesCondomUsedAfterPregnancyR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    21. In the past year, did you have symptoms such as genital discharge, sores in your genital area, pain during urination, or pain in your lower abdomen? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s6">
                    <input id="hasPatientHadPainInLowerAbdomenYes" class="with-gap isRequired" name="hasPatientHadPainInLowerAbdomen" title="Don't leave 21st question" value="yes" type="radio" <?php echo ($row->has_patient_had_pain_in_lower_abdomen == 'yes')?'checked="checked"':''; ?>>
		    <label for="hasPatientHadPainInLowerAbdomenYes" class="active">Yes </label>&nbsp&nbsp
                    <input id="hasPatientHadPainInLowerAbdomenNo" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="no" type="radio" <?php echo ($row->has_patient_had_pain_in_lower_abdomen == 'no')?'checked="checked"':''; ?>>
		    <label for="hasPatientHadPainInLowerAbdomenNo" class="active">No </label>&nbsp&nbsp
                    <input id="hasPatientHadPainInLowerAbdomenDK" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="dontknow" type="radio" <?php echo ($row->has_patient_had_pain_in_lower_abdomen == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="hasPatientHadPainInLowerAbdomenDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="hasPatientHadPainInLowerAbdomenR" class="with-gap" name="hasPatientHadPainInLowerAbdomen" value="refused" type="radio" <?php echo ($row->has_patient_had_pain_in_lower_abdomen == 'refused')?'checked="checked"':''; ?>>
		    <label for="hasPatientHadPainInLowerAbdomenR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    22. If yes, were you treated for these symptoms? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s6">
                    <input id="hasPatientBeenTreatedForLowerAbdomenPainYes" class="with-gap isRequired" name="hasPatientBeenTreatedForLowerAbdomenPain" title="Don't leave 22nd question" value="yes" type="radio" <?php echo ($row->has_patient_been_treated_for_lower_abdomen_pain == 'yes')?'checked="checked"':''; ?>>
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainYes" class="active">Yes </label>&nbsp&nbsp
                    <input id="hasPatientBeenTreatedForLowerAbdomenPainNo" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="no" type="radio" <?php echo ($row->has_patient_been_treated_for_lower_abdomen_pain == 'no')?'checked="checked"':''; ?>>
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainNo" class="active">No </label>&nbsp&nbsp
                    <input id="hasPatientBeenTreatedForLowerAbdomenPainDK" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="dontknow" type="radio" <?php echo ($row->has_patient_been_treated_for_lower_abdomen_pain == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="hasPatientBeenTreatedForLowerAbdomenPainR" class="with-gap" name="hasPatientBeenTreatedForLowerAbdomenPain" value="refused" type="radio" <?php echo ($row->has_patient_been_treated_for_lower_abdomen_pain == 'refused')?'checked="checked"':''; ?>>
		    <label for="hasPatientBeenTreatedForLowerAbdomenPainR" class="active">Refused </label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    23. Have you ever been diagnosed or treated for syphilis? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s6">
                    <input id="hasPatientEverBeenTreatedForSyphilisYes" class="with-gap isRequired" name="hasPatientEverBeenTreatedForSyphilis" title="Don't leave 23rd question" value="yes" type="radio" <?php echo ($row->has_patient_ever_been_treated_for_syphilis == 'yes')?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenTreatedForSyphilisYes" class="active">Yes </label>&nbsp&nbsp
                    <input id="hasPatientEverBeenTreatedForSyphilisNo" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="no" type="radio" <?php echo ($row->has_patient_ever_been_treated_for_syphilis == 'no')?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenTreatedForSyphilisNo" class="active">No </label>&nbsp&nbsp
                    <input id="hasPatientEverBeenTreatedForSyphilisDK" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="dontknow" type="radio" <?php echo ($row->has_patient_ever_been_treated_for_syphilis == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenTreatedForSyphilisDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="hasPatientEverBeenTreatedForSyphilisR" class="with-gap" name="hasPatientEverBeenTreatedForSyphilis" value="refused" type="radio" <?php echo ($row->has_patient_ever_been_treated_for_syphilis == 'refused')?'checked="checked"':''; ?>>
		    <label for="hasPatientEverBeenTreatedForSyphilisR" class="active">Refused </label>
                </div>
            </div>
            <h6 style="padding:10px 0px 10px 6px;font-size:16px;text-decoration:underline;"><strong>Alcohol and drug use</strong></h6>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    24. During the past 6 months, on how many days did you have at least one drink containing alcohol? *
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s8">
                    <input id="hasPatientHadDrinkWithAlcoholInLastSixMonthsInDays" name="hasPatientHadDrinkWithAlcoholInLastSixMonthsInDays" type="text" class="validate <?php echo ($row->has_patient_had_drink_with_alcohol_in_last_six_months == null || $row->has_patient_had_drink_with_alcohol_in_last_six_months == '')?'isRequired':''; ?> checkNum" title="Please enter no. of days" value="<?php echo($row->has_patient_had_drink_with_alcohol_in_last_six_months!= null && trim($row->has_patient_had_drink_with_alcohol_in_last_six_months)!= '' && is_numeric($row->has_patient_had_drink_with_alcohol_in_last_six_months))?$row->has_patient_had_drink_with_alcohol_in_last_six_months:'';?>" style="width:10%;"> Days&nbsp;
                    <input id="hasPatientHadDrinkWithAlcoholInLastSixMonthsNot" class="with-gap" name="hasPatientHadDrinkWithAlcoholInLastSixMonths" value="havenotdrink" type="radio" <?php echo ($row->has_patient_had_drink_with_alcohol_in_last_six_months == 'havenotdrink')?'checked="checked"':''; ?>>
		    <label for="hasPatientHadDrinkWithAlcoholInLastSixMonthsNot" class="active">Haven't Had a Drink </label>&nbsp&nbsp
                    <input id="hasPatientHadDrinkWithAlcoholInLastSixMonthsDK" class="with-gap" name="hasPatientHadDrinkWithAlcoholInLastSixMonths" value="dontknow" type="radio" <?php echo ($row->has_patient_had_drink_with_alcohol_in_last_six_months == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="hasPatientHadDrinkWithAlcoholInLastSixMonthsDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="hasPatientHadDrinkWithAlcoholInLastSixMonthsR" class="with-gap" name="hasPatientHadDrinkWithAlcoholInLastSixMonths" value="refusedtoanswer" type="radio" <?php echo ($row->has_patient_had_drink_with_alcohol_in_last_six_months == 'refusedtoanswer')?'checked="checked"':''; ?>>
		    <label for="hasPatientHadDrinkWithAlcoholInLastSixMonthsR" class="active">Refused To Answer</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    25. How often do you have 4 or more drinks with alcohol on one occasion? * (e.g. within 2 hours)
                </div>
            </div>
            <div class="row" style="margin-bottom:10px;">
                <div class="col s4">
                    <select id="hasPatientOftenHad4rmoreDrinksWithAlcoholOnOneOccasion" name="hasPatientOftenHad4rmoreDrinksWithAlcoholOnOneOccasion" class="material-select isRequired" title="Don't leave 25th question">
                        <option value=""> -- Select -- </option>
                        <option value="never" <?php echo ($row->has_patient_often_had_4rmore_drinks_with_alcohol_on_one_occasion == 'never')?'selected="selected"':''; ?>>Never</option>
                        <option value="monthly" <?php echo ($row->has_patient_often_had_4rmore_drinks_with_alcohol_on_one_occasion == 'monthly')?'selected="selected"':''; ?>>Monthly</option>
                        <option value="weekly" <?php echo ($row->has_patient_often_had_4rmore_drinks_with_alcohol_on_one_occasion == 'weekly')?'selected="selected"':''; ?>>Weekly</option>
                        <option value="daily" <?php echo ($row->has_patient_often_had_4rmore_drinks_with_alcohol_on_one_occasion == 'daily')?'selected="selected"':''; ?>>Daily or On Most Days of The Week</option>
                        <option value="dontknow" <?php echo ($row->has_patient_often_had_4rmore_drinks_with_alcohol_on_one_occasion == 'dontknow')?'selected="selected"':''; ?>>Don't Know</option>
                        <option value="refused" <?php echo ($row->has_patient_often_had_4rmore_drinks_with_alcohol_on_one_occasion == 'refused')?'selected="selected"':''; ?>>Refused</option>
                    </select>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12">
                    26. Have you ever tried recreational drugs? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s8">
                    <input id="hasPatientEverTriedRecreationalDrugsYes" class="with-gap isRequired" name="hasPatientEverTriedRecreationalDrugs" title="Don't leave 26th question" value="yes" type="radio" <?php echo ($row->has_patient_ever_tried_recreational_drugs == 'yes')?'checked="checked"':''; ?>>
		    <label for="hasPatientEverTriedRecreationalDrugsYes" class="active">Yes </label>&nbsp&nbsp
                    <input id="hasPatientEverTriedRecreationalDrugsNo" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="no" type="radio" <?php echo ($row->has_patient_ever_tried_recreational_drugs == 'no')?'checked="checked"':''; ?>>
		    <label for="hasPatientEverTriedRecreationalDrugsNo" class="active">No </label>&nbsp&nbsp
                    <input id="hasPatientEverTriedRecreationalDrugsDK" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="dontknow" type="radio" <?php echo ($row->has_patient_ever_tried_recreational_drugs == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="hasPatientEverTriedRecreationalDrugsDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="hasPatientEverTriedRecreationalDrugsR" class="with-gap" name="hasPatientEverTriedRecreationalDrugs" value="refused" type="radio" <?php echo ($row->has_patient_ever_tried_recreational_drugs == 'refused')?'checked="checked"':''; ?>>
		    <label for="hasPatientEverTriedRecreationalDrugsR" class="active">Refused</label>
                </div>
            </div>
            <div class="row" style="margin-bottom:0;margin-top:16px;">
                <div class="col s12">
                    27. In the last 6 months, have you taken any recreational drugs? *
                </div>
            </div>
            <div class="row" style="margin-bottom:0;">
                <div class="col s12" style="margin-bottom:20px;">
                    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsYes" class="with-gap isRequired" name="hasPatientHadRecreationalDrugsInLastSixMonths" title="Don't leave 27th question" value="yes" type="radio" <?php echo ($row->has_patient_had_recreational_drugs_in_last_six_months == 'yes')?'checked="checked"':''; ?>>
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsYes" class="active">Yes </label>&nbsp&nbsp
                    <span class="recreationalDrugs" style="display:<?php echo ($row->has_patient_had_recreational_drugs_in_last_six_months == 'yes')?'':'none'; ?>;">Specify Drug(s) <input id="recreationalDrugs" name="recreationalDrugs" type="text" class="validate <?php echo ($row->has_patient_had_recreational_drugs_in_last_six_months == 'yes')?'isRequired':''; ?>" title="Please enter recreational drugs" value="<?php echo $row->recreational_drugs; ?>" style="width:30%;">&nbsp;</span>
                    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsNo" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="no" type="radio" <?php echo ($row->has_patient_had_recreational_drugs_in_last_six_months == 'no')?'checked="checked"':''; ?>>
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsNo" class="active">No </label>&nbsp&nbsp
                    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsDK" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="dontknow" type="radio" <?php echo ($row->has_patient_had_recreational_drugs_in_last_six_months == 'dontknow')?'checked="checked"':''; ?>>
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsDK" class="active">Don't Know </label>&nbsp&nbsp
                    <input id="hasPatientHadRecreationalDrugsInLastSixMonthsR" class="with-gap" name="hasPatientHadRecreationalDrugsInLastSixMonths" value="refused" type="radio" <?php echo ($row->has_patient_had_recreational_drugs_in_last_six_months == 'refused')?'checked="checked"':''; ?>>
		    <label for="hasPatientHadRecreationalDrugsInLastSixMonthsR" class="active">Refused</label>
                </div>
            </div>
            <div class="col s12" style="margin-top:20px;">
                <input type="hidden" name="chosenCountry" id="chosenCountry" value="<?php echo base64_encode($countryId);?>"/>
                <input type="hidden" name="redirectUrl" id="redirectUrl" value="<?php echo $link;?>"/>
                <input id="riskAssessmentId" name="riskAssessmentId" type="hidden" value="<?php echo base64_encode($row->assessment_id); ?>"/>
                <a href="<?php echo $link;?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="updateRiskAssessment();">UPDATE</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/moment.min.js' ?>"></script>
<script>
    $(document).ready(function(){
       $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 15, // Creates a dropdown of 15 years to control year
            format: 'dd/mm/yyyy',
	    max: new Date('Today')
        });
    });
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if(checkValue!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
    
    //set occupation
    $('#occupation').on('change',function(){
	if(this.value == 'other'){
	    $('.occupationNew').show();
	    $('#occupationNew').addClass('isRequired');
	    $('#occupationNew').focus();
	}else{
	   $('.occupationNew').hide();
	   $('#occupationNew').removeClass('isRequired'); 
	}
    });
    
    //set age at first marriage
    $('#ageAtFirstMarriageInYears').on('change',function() {
	setAgeAtFirstMarriage('txt');
    });
    $('input:radio[name=ageAtFirstMarriage]').change(function () {
	setAgeAtFirstMarriage('rd');
    });
    function setAgeAtFirstMarriage(fromSource){
	if(fromSource == 'txt'){
	    if($('#ageAtFirstMarriageInYears').val()!= ''){
		$('#ageAtFirstMarriageDK').prop('checked',false);
		$('#ageAtFirstMarriageR').prop('checked',false);
	    }
	    $('#ageAtFirstMarriageInYears').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#ageAtFirstMarriageInYears').val('');
	   $('#ageAtFirstMarriageInYears').removeClass('isRequired');
	}
    }
    
    //set no.of sexual partners
    $('#noOfSexualPartnersInNumbers').on('change',function() {
	setNoOfSexualPartners('txt');
    });
    $('input:radio[name=noOfSexualPartners]').change(function () {
	setNoOfSexualPartners('rd');
    });
    function setNoOfSexualPartners(fromSource){
	if(fromSource == 'txt'){
	    if($('#noOfSexualPartnersInNumbers').val()!= ''){
		$('#noOfSexualPartnersDK').prop('checked',false);
		$('#noOfSexualPartnersR').prop('checked',false);
	    }
	    $('#noOfSexualPartnersInNumbers').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#noOfSexualPartnersInNumbers').val('');
	   $('#noOfSexualPartnersInNumbers').removeClass('isRequired');
	}
    }
    
    //set no.of sexual partners in last six months
    $('#noOfSexualPartnersInLastSixMonthsInNumbers').on('change',function() {
	setNoOfSexualPartnersInLastSixMonths('txt');
    });
    $('input:radio[name=noOfSexualPartnersInLastSixMonths]').change(function () {
	setNoOfSexualPartnersInLastSixMonths('rd');
    });
    
    function setNoOfSexualPartnersInLastSixMonths(fromSource){
	if(fromSource == 'txt'){
	    if($('#noOfSexualPartnersInLastSixMonthsInNumbers').val()!= ''){
		$('#noOfSexualPartnersInLastSixMonthsDK').prop('checked',false);
		$('#noOfSexualPartnersInLastSixMonthsR').prop('checked',false);
	    }
	    $('#noOfSexualPartnersInLastSixMonthsInNumbers').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#noOfSexualPartnersInLastSixMonthsInNumbers').val('');
	   $('#noOfSexualPartnersInLastSixMonthsInNumbers').removeClass('isRequired');
	}
    }
    
    //set main sexual partner age at last birthday
    $('#ageOfMainSexualPartnerAtLastBirthdayInYears').on('change',function() {
	mainSexualPartnerAgeAtLastBirthday('txt');
    });
    $('input:radio[name=ageOfMainSexualPartnerAtLastBirthday]').change(function () {
	mainSexualPartnerAgeAtLastBirthday('rd');
    });
    function mainSexualPartnerAgeAtLastBirthday(fromSource){
	if(fromSource == 'txt'){
	    if($('#ageOfMainSexualPartnerAtLastBirthdayInYears').val()!= ''){
		$('#ageOfMainSexualPartnerAtLastBirthdayDK').prop('checked',false);
		$('#ageOfMainSexualPartnerAtLastBirthdayR').prop('checked',false);
	    }
	    $('#ageOfMainSexualPartnerAtLastBirthdayInYears').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#ageOfMainSexualPartnerAtLastBirthdayInYears').val('');
	   $('#ageOfMainSexualPartnerAtLastBirthdayInYears').removeClass('isRequired');
	}
    }
    
    //set no.of days in last six months
    $('#hasPatientHadDrinkWithAlcoholInLastSixMonthsInDays').on('change',function() {
        noOfDaysHadDrinkInLastSixMonth('txt');
    });
    $('input:radio[name=hasPatientHadDrinkWithAlcoholInLastSixMonths]').change(function () {
	noOfDaysHadDrinkInLastSixMonth('rd');
    });
    function noOfDaysHadDrinkInLastSixMonth(fromSource){
	if(fromSource == 'txt'){
	    if($('#hasPatientHadDrinkWithAlcoholInLastSixMonthsInDays').val()!= ''){
		$('#hasPatientHadDrinkWithAlcoholInLastSixMonthsNot').prop('checked',false);
		$('#hasPatientHadDrinkWithAlcoholInLastSixMonthsDK').prop('checked',false);
		$('#hasPatientHadDrinkWithAlcoholInLastSixMonthsR').prop('checked',false);
	    }
	    $('#hasPatientHadDrinkWithAlcoholInLastSixMonthsInDays').addClass('isRequired');
	}else if(fromSource == 'rd'){
	   $('#hasPatientHadDrinkWithAlcoholInLastSixMonthsInDays').val('');
	   $('#hasPatientHadDrinkWithAlcoholInLastSixMonthsInDays').removeClass('isRequired');
	}
    }
    
    //set recreational drugs
    $('input:radio[name=hasPatientHadRecreationalDrugsInLastSixMonths]').change(function () {
	if ($("input[name='hasPatientHadRecreationalDrugsInLastSixMonths']:checked").val() == 'yes') {
            $('.recreationalDrugs').show();
            $('#recreationalDrugs').addClass('isRequired');
            $('#recreationalDrugs').focus();
        }else{
           $('.recreationalDrugs').hide();
           $('#recreationalDrugs').val('');
           $('#recreationalDrugs').removeClass('isRequired');
        }
    });
    
    function checkPatientRecord(type){
	if(type == 'barcodeid'){
	    checkPatientBarcodeId();
	}else if(type == 'ancid'){
	    checkANCPatientId();
	}else{
	    checkPatientBarcodeId();
	    checkANCPatientId();
	}
    }
    
    function checkPatientBarcodeId(){
	var patientBarcodeId = $('#patientBarcodeId').val();
	var countryId = $('#chosenCountry').val();
	if($.trim(patientBarcodeId)!= '' && $.trim(countryId)!= ''){
            $.post("<?php echo $this->url('check-patient-record'); ?>", {assessmentId:'<?php echo base64_encode($row->assessment_id); ?>',patientBarcodeId: patientBarcodeId,countryId:countryId,type:'clinic',src:'barcodeid'},
            function(data) {
                if ($.trim(data)!= '') { $.blockUI(); document.location.href = data; }
            });
        }
    }
    
    function checkANCPatientId(){
        var ancPatientId = $('#ancPatientId').val();
	var countryId = $('#chosenCountry').val();
        if($.trim(ancPatientId)!= '' && $.trim(countryId)!= ''){
            $.post("<?php echo $this->url('check-patient-record'); ?>", {assessmentId:'<?php echo base64_encode($row->assessment_id); ?>',ancPatientId: ancPatientId,countryId:countryId,type:'clinic',src:'ancid'},
            function(data) {
                if ($.trim(data)!= '') {
		    var conf = confirm("The risk assessment form with ANC Patient ID "+$('#ancPatientId').val()+" has already been submitted. Please click OK if you want to continue editing the same");
		    if(conf){
		       $.blockUI();	
		       document.location.href = data;
		    }else{
		      $('#ancPatientId').val('');
		    }
                }
            });
        }
    }
    
    function updateRiskAssessment(){
        flag = deforayValidator.init({
            formId: 'editRiskAssessmentForm'
        });
	
        if(flag){
            document.getElementById('editRiskAssessmentForm').submit();
        }
    }
</script>