<?php
use Zend\Session\Container;
$loginContainer = new Container('user');
$interviewFilterDate = '';
if(isset($date) && trim($date)!= ''){
    $dateArray = explode("/",$date);
    $month = date('M', strtotime($dateArray[0]));
    $year = $dateArray[1];
    $interviewFilterDate = '01-'.$month.'-'.$year.' to 31-'.$month.'-'.$year;
}
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/daterangepicker/daterangepicker.css' ?>"/>
<style>
    .ranges{display: none;}
    .daterangepicker .ranges{
	width: 190px;
    }
    @font-face {
	font-family: 'Glyphicons Halflings';
	src: url('../../assets/fonts/glyphicons-halflings-regular.eot');
	src: url('../../assets/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../../assets/fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../../assets/fonts/glyphicons-halflings-regular.woff') format('woff'), url('../../assets/fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../../assets/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
    }
    .glyphicon {
      position: relative;
      top: 1px;
      display: inline-block;
      font-family: 'Glyphicons Halflings';
      font-style: normal;
      font-weight: normal;
      line-height: 1;
    
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }
    .glyphicon-arrow-left:before {
      content: "\e091";
    }
    .glyphicon-arrow-right:before {
      content: "\e092";
    }
    .glyphicon-arrow-up:before {
      content: "\e093";
    }
    .glyphicon-arrow-down:before {
      content: "\e094";
    }
    * {
      -webkit-box-sizing: border-box;
	 -moz-box-sizing: border-box;
	      box-sizing: border-box;
    }
    *:before,
    *:after {
      -webkit-box-sizing: border-box;
	 -moz-box-sizing: border-box;
	      box-sizing: border-box;
    }
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        background-color: #eaeaea;
        border-bottom: 1px solid #ccc;
        padding: 10px 20px;
    }
    pre {
        max-height: 596px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        left: -184px;
    }
    .select-wrapper{
	width:100%;
    }
    #riskAssessmentDataTable_wrapper{
	overflow-x:scroll;
    }
    .dataTable_noWrap{
	white-space: nowrap;
        overflow: hidden;
    }
    table.dataTable tbody td{
	padding:2px 4px 2px 4px;
    }
    @media only screen and (max-width: 1024px){
	table.dataTable.display tbody tr:first-child td {
	    border-top: 1px solid #ddd;
        }
	table.dataTable tbody td{
	    padding: 6px 4px 6px 4px;
	}
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Risk Assessment</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Risk Assessment</a>
       </div>
    </div>
    <div class="row" style="max-width:1109px;">
	<form id="rASearchFilterForm" action="#">
	    <div class="col l12 m12 s12">
		<div class="col l1 m1 s1" style="visibility:hidden;">--FILTER START--</div>
		<div class="col l2 m2 s2 left-align"><h6><strong>Interview Date </strong></h6></div>
		<div class="col l3 m3 s3 left-align">
		    <input id="interviewDate" name="interviewDate" type="text" title="Please enter interview date" value="<?php echo $interviewFilterDate; ?>" onclick="selectDate();" readonly>
		</div>
		<div class="col l2 m2 s2 left-align" style="padding-left:4%;"><h6><strong>ANC Site</strong></h6></div>
		<div class="col l3 m3 s3 left-align">
		    <select id="anc" name="anc[]" class="material-select" title="Please select ANC Site" multiple="multiple" style="width:40% !important;">
			<?php
			foreach($ancSites as $anc){
			?>
			<option value="<?php echo $anc['anc_site_id']; ?>"><?php echo $anc['anc_site_code'].' - '.ucwords($anc['anc_site_name']); ?></option>
			<?php } ?>
		    </select>
		</div>
		<div class="col l1 m1 s1" style="visibility:hidden;">--FILTER END--</div>
	    </div>
	    <div class="col l12 m12 s12" style="text-align:center;">
		<a href="javascript:void(0);" onclick="clearSearchFields();" class="waves-effect waves-light btn-small btn red-text custom-btn custom-btn-red"><i class="zmdi zmdi-refresh"></i> Reset</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="searchRiskAssessmentData();" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="exportRiskAssessmentData();" class="waves-effect waves-light btn-small btn green-text custom-btn custom-btn-green"><i class="zmdi zmdi-collection-text"></i> Export Excel</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="exportIPVReport();" class="waves-effect waves-light btn-small btn green-text custom-btn custom-btn-green"><i class="zmdi zmdi-collection-text"></i> Export IPV Report</a>
	    </div>
	</form>
    </div>
    <div class="row dashboard-wrapper content-container">
        <div class="col l12 m12 s12">
            <div class="card card-default table-height">
                <div class="card-header dataTable-header"><i class="zmdi zmdi-filter-list"></i> Risk Assessment List
		<?php if($loginContainer->hasViewOnlyAccess!= 'yes') { ?>
		  <span style="float:right;"><a class="custom-add-btn" href="/clinic/risk-assessment/add/<?php echo base64_encode($countryId); ?>"><i class="zmdi zmdi-plus"></i> Add Risk Assessment</a></span>
		<?php } ?>
		</div>
                <div class="card-content clearfix">
                    <table id="riskAssessmentDataTable" class="responsive-table display dataTable">
                        <thead>
                            <tr>
                                <th>ANC Site</th>
                                <th>ANC Site Code</th>
                                <th>Patient Barcode ID</th>
				<th>Interviewer Name</th>
				<th>ANC Patient ID</th>
				<th>Interview Date</th>
				<th>Added On</th>
				<th>Added By</th>
				<?php
                                if(trim($countryId)== ''){
                                ?>
                                 <th>Country</th>
				<?php } ?>
				<th>Status</th>
                                <th style="width:120px !important;text-align:center;">Action</th>
                            </tr>
                        </thead>
			<tfoot>
                            <tr>
                                <th>ANC Site</th>
                                <th>ANC Site Code</th>
                                <th>Patient Barcode ID</th>
				<th>Interviewer Name</th>
				<th>ANC Patient ID</th>
				<th>Interview Date</th>
				<th>Added On</th>
				<th>Added By</th>
				<?php
                                if(trim($countryId)== ''){
                                ?>
                                 <th>Country</th>
				<?php } ?>
				<th>Status</th>
                                <th style="text-align:center;">Action</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/daterangepicker/daterangepicker.js' ?>"></script>
<script>
    $(document).ready(function() {
	selectDate();
	oTable = $('#riskAssessmentDataTable').dataTable({
	    "autoWidth": false,
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
	    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
	    "iDisplayLength": 25,
            "aoColumns": [
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		<?php if(trim($countryId)== ''){ ?>
		  {"sClass":"dataTable_noWrap"},
		<?php } ?>
		{"sClass":"dataTable_noWrap"},
                {"sClass":"dataTable_noWrap","bSortable":false}
            ],
            "aaSorting": [[5, "desc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('clinic-risk-assessment',array('action' => 'index')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
		aoData.push({"name": "countryId", "value": '<?php echo $countryId; ?>' });
		aoData.push({"name": "type", "value": '<?php echo $type; ?>'});
                aoData.push({"name": "interviewDate", "value": $('#interviewDate').val()});
                aoData.push({"name": "anc", "value": $('#anc').val()});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
       
       $('.dataTables_filter').empty(); // clears the content generated
       $('.dataTables_filter').append(
                "<div class='input-field col s6 search-div right' style='width: 250px'>" +
                "    <i class='material-icons search-icon'>search</i> "+
                "    <input id='search-items' type='text' class='validate' />" +
                "    <label for='icon_prefix' class='search-label'>Search</label>   "+
                "</div>");
       $(document).on('keyup', "input[type='text']", function(){
                    var oTable = $('.dataTable').dataTable();
                    oTable.fnFilter($(this).val());
                });
    });
    
    function selectDate(){
	$(".ranges").show();
        $(".left").css({"float":"none !important"});
        $('#interviewDate').daterangepicker({
            format: 'DD-MMM-YYYY',
	    separator: ' to ',
            maxDate: moment(),
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                'Last 7 Days': [moment().subtract('days', 6), moment()],
                'Last 30 Days': [moment().subtract('days', 29), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
            },
        },function(start, end) {
            startDate = start.format('YYYY-MM-DD');
            endDate = end.format('YYYY-MM-DD');
            $('label[for="interviewDate"]').css("transform", "translateY(-140%)");
        });
        $('.applyBtn').addClass('waves-effect waves-light btn-small white-text blue margin-bottom-10');
        $('.cancelBtn').addClass('waves-effect waves-light btn-small btn blue-text custom-btn custom-btn-blue margin-bottom-10');
    }
    
    function searchRiskAssessmentData(){
       oTable.fnDraw(false);
    }
    
    function clearSearchFields(){
        $('#rASearchFilterForm')[0].reset();
	$('#rASearchFilterForm .select-dropdown').val('');
        searchRiskAssessmentData();
    }
    
    function exportRiskAssessmentData(){
	$.blockUI();
	$.post("<?php echo $this->url('export-risk-assessment-excel'); ?>", { },
	function(data){
	    if(data == "" || data == null || data == undefined){
		alert('OOPS..Unable to generate excel.');
		$.unblockUI();
	    }else{
		$.unblockUI();
		window.open("/temporary/"+data, "_blank");
	    }
	});
    }
    
    function exportIPVReport(){
	$.blockUI();
	$.post("<?php echo $this->url('export-ipv-report'); ?>", { },
	function(data){
	    if(data == "" || data == null || data == undefined){
		alert('OOPS..Unable to generate excel.');
		$.unblockUI();
	    }else{
		$.unblockUI();
		window.open("/temporary/"+data, "_blank");
	    }
	});
    }
    
    assessid = [];
    function printAssessmentForm(ID){
	assessid.push(ID);
	$.blockUI();
	$.post("<?php echo $this->url('generate-risk-assessment-pdf'); ?>", {assessment:assessid},
	    function(data){
		if(data === "" || data === null || data === undefined){
		    assessid = [];
		    alert('OOPS..');
		    $.unblockUI();
		}else{
		    assessid = [];
		    $.unblockUI();
		    window.open("/temporary/"+data, "_blank");
		}
	    });
    }
    
    function lockRiskAssessment(ID){
	var conf = confirm("Are you sure you want to lock this risk assessment data?");
	if(conf){
	    $.post("<?php echo $this->url('lock-risk-assessment-data'); ?>", {assessment:ID},
		function(data){
		    if($.trim(data) == 0 || $.trim(data) == ''){
		      alert("OOPS..");
		    }else{
		      oTable.fnDraw(false);
		    }
		});
	}
    }
    
    function unlockRiskAssessment(ID){
	var conf = confirm("Are you sure you want to unlock this risk assessment data?");
	if(conf){
	    $.post("<?php echo $this->url('unlock-risk-assessment-data'); ?>", {assessment:ID},
		function(data){
		    if($.trim(data) == 0 || $.trim(data) == ''){
		      alert("OOPS..");
		    }else{
		      oTable.fnDraw(false);
		    }
		});
	}
    }
</script>