<?php
$behaviourDataPending = 0;
$totalBehaviourLabData = 0;
if(isset($summaries['collectionResult'][0]['totalLabData']) && $summaries['collectionResult'][0]['totalLabData'] > 0){
    $totalLabDatas = $summaries['collectionResult'][0]['totalLabData'];
}
if(isset($summaries['collectionResult'][0]['totalBehaviourLabData']) && $summaries['collectionResult'][0]['totalBehaviourLabData'] > 0){
    $totalBehaviourLabData = $summaries['collectionResult'][0]['totalBehaviourLabData'];
}
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/css/jquery-ui.css' ?>"/>
<style>
    .ui-datepicker-calendar {
       display: none;
    }
    .ui-datepicker-month,.ui-datepicker-year{
       display:block;
       display:inline-block;
    }
    .ui-datepicker-title select{
	padding:0;
	height:1.5rem;
    }

    .general small{
        font-size:16px;
        text-transform:uppercase;
    }

    .general .row h2{
        font-size:1.7em;
    }
    .card{
        box-shadow:none;
    }
    .summary-count{
        font-size: 38px;
        font-weight: bold;
        margin: 0 0 10px 0;
        white-space: nowrap;
        padding: 0;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m8 s12 left-align" style="font-size: 34px;font-weight:400;">Summary of Online Reported Data</div>
        <div class="col m4 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Summary</a>
        </div>
    </div>
    <br><br>
    <div class="row content-container general">
        <div class="row">
            <div class="col l4 m6 s12">
                 <div class="card small-chart margin" style="background-color:#3dc587;">
                    <div class="col l12 m12 s12" style="padding:5px;">
                        <small>Lab Tests Completed</small>
                        <div class="summary-count"><?php echo (isset($summaries['collectionResult'][0]['labTestCompleted']))?$summaries['collectionResult'][0]['labTestCompleted']:0; ?></div>
                    </div>
                 </div>
             </div>
             <div class="col l4 m6 s12">
                 <div class="card small-chart margin" style="background-color:#52bed8;">
                     <div class="col l12 m12 s12" style="padding:5px;">
                        <small>Behaviour Data</small>
                        <div class="summary-count"><?php echo (isset($summaries['riskAssessmentResult'][0]['totalBehaviourData']))?$summaries['riskAssessmentResult'][0]['totalBehaviourData']:0; ?></div>
                     </div>
                 </div>
             </div>
             <div class="col l4 m6 s12">
                 <div class="card small-chart margin" style="background-color:#fbb548;">
                     <div class="col l12 m12 s12" style="padding:5px;">
                        <small>ANC Rapid Recency Assay Recent <span style="text-transform:none;font-size:13px;">(Visual)</span></small>
                        <div class="summary-count"><?php echo (isset($summaries['riskAssessmentResult'][0]['totalANCRecencyTestRecent']))?$summaries['riskAssessmentResult'][0]['totalANCRecencyTestRecent']:0; ?></div>
                     </div>
                 </div>
             </div>
        </div>
        <div class="row">
	    <div class="col l4 m4 s12">
                <div class="card small-chart margin" style="background-color:#f97465;">
                    <div class="col l12 m12 s12" style="padding:5px;">
                       <small>Lab Rejections</small>
                       <div class="summary-count"><?php echo (isset($summaries['collectionResult'][0]['labRejections']))?$summaries['collectionResult'][0]['labRejections']:0; ?></div>
                    </div>
                </div>
            </div>
            <div class="col l4 m4 s12">
                 <div class="card small-chart margin" style="background-color:#f97465;">
                     <div class="col l12 m12 s12" style="padding:5px;">
                        <small>Lab Tests Pending as on Today</small>
                        <div class="summary-count"><?php echo (isset($summaries['collectionResult'][0]['labTestIncompletes']))?$summaries['collectionResult'][0]['labTestIncompletes']:0; ?></div>
                     </div>
                 </div>
            </div>
	    <div class="col l4 m4 s12">
                <div class="card small-chart margin" style="background-color:#f97465;">
                    <div class="col l12 m12 s12" style="padding:5px;">
                       <small>Behaviour Data Pending</small>
                       <div class="summary-count"><?php echo $totalLabDatas-$totalBehaviourLabData; ?></div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <hr style="border:1px solid #e0dddd;">
        <br>
        <div class="row" style="max-width:1109px;">
            <form id="summaryFilter" action="#" style="margin-top:30px;">
                <div class="col l12 m12 s12" style="text-align:center;text-transform:uppercase;">Choose Month Range</div>
                <div class="row" style="margin-top:30px;">
                    <div class="col s2" style="visibility:hidden;">--FILTER START--</div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <input id="startmonth" name="startmonth" type="text" class="" title="Select month/year" readonly>
                            <label for="startmonth">From </label>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <input id="endmonth" name="endmonth" type="text" class="" title="Select month/year" readonly>
                            <label for="endmonth">To </label>
                        </div>
                    </div>
                    <div class="col s2" style="visibility:hidden;">--FILTER END--</div>
                </div>
                <div class="col l12 m12 s12" style="text-align:center;margin-bottom:20px;">
                    <a href="javascript:void(0);" onclick="clearSearchFields();" class="waves-effect waves-light btn-small btn red-text custom-btn custom-btn-red"><i class="zmdi zmdi-refresh"></i> Reset Filters</a>&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="javascript:void(0);" onclick="searchDataReporting('search');" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a>
                </div>
            </form>
        </div>
        <div class="row">
            <div class="col l12 m12 s12">
                <div class="card charts">
                    <div class="card-content">
                        <h5>Weekly Lab Data Entered Online</h5>
                    </div>
                    <div class="card-action">
                        <div class="weekly-data-reporting-container">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="margin-bottom:0;">
            <div class="col l12 m12 s12">
                <div class="card charts">
                    <div class="card-content">
                        <h5>Weekly Behaviour Data Entered Online</h5>
                    </div>
                    <div class="card-action">
                        <div class="weekly-behaviour-data-container">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery-ui.js' ?>"></script>
<script>
    $(document).ready(function(){
        $("#startmonth").datepicker({ 
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'M/yy',
            maxDate: 'Today',        
            beforeShow : function(input, inst) {
                tmp = $('#startmonth').val().split('/');
                var dat = new Date('1 ' + tmp[0] + ' 1969');
                $('#startmonth').datepicker('option','defaultDate',new Date(tmp[1],parseInt(dat.getMonth()-1)+parseInt(1),1));
                $('#startmonth').datepicker('setDate', new Date(tmp[1], parseInt(dat.getMonth()-1)+parseInt(1), 1));
            },
            onClose: function(dateText, inst) {
                var month=$("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $('#startmonth').datepicker('setDate', new Date(year, month, 1));
                $('#endmonth').datepicker('option','minDate',new Date(year, month, 1));
                $('#endmonth').datepicker('setDate', new Date(year, month, 1));
                $('label[for="endmonth"]').css("transform", "translateY(-140%)");
            }
        });
        $("#endmonth").datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'M/yy',
            maxDate: 'Today',     
            beforeShow : function(input, inst) {
                tmp = $('#endmonth').val().split('/');
                var dat = new Date('1 ' + tmp[0] + ' 1969');
                $('#endmonth').datepicker('option','defaultDate',new Date(tmp[1],parseInt(dat.getMonth()-1)+parseInt(1),1));
                $('#endmonth').datepicker('setDate', new Date(tmp[1], parseInt(dat.getMonth()-1)+parseInt(1), 1));
            },
            onClose: function(dateText, inst) {
                var month=$("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $('#endmonth').datepicker('setDate', new Date(year, month, 1));
            }
        });
        searchDataReporting('load');
    });
    
    function searchDataReporting(frmSrc){
        getWeeklyDataReporting(frmSrc);
        getWeeklyBehaviourData(frmSrc);
    }
    
    function getWeeklyDataReporting(frmSrc){
        var fromDate = $('#startmonth').val();
        var toDate = $('#endmonth').val();
        if(frmSrc!= 'load') { $.blockUI(); }
        $.post("<?php echo $this->url('get-data-reporting-weekly-bar-chart'); ?>",{fromDate:fromDate,toDate:toDate,countryId:'<?php echo $countryId; ?>'},
        function (data) {
            if(frmSrc!= 'load') { $.unblockUI(); }
            $(".weekly-data-reporting-container").html(data);
        });
    }
    
    function getWeeklyBehaviourData(frmSrc){
        var fromDate = $('#startmonth').val();
        var toDate = $('#endmonth').val();
        if(frmSrc!= 'load') { $.blockUI(); }
        $.post("<?php echo $this->url('get-behaviour-data-reporting-weekly-bar-chart'); ?>",{fromDate:fromDate,toDate:toDate,countryId:'<?php echo $countryId; ?>'},
        function (data) {
            if(frmSrc!= 'load') { $.unblockUI(); }
            $(".weekly-behaviour-data-container").html(data);
        });
    }
    
    function clearSearchFields(){
       $('#summaryFilter')[0].reset();
       searchDataReporting('reset');
    }
</script>