<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Add Country</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="<?php echo $this->url('country'); ?>" class="breadcrumb">Countries</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Add Country</a>
        </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="addCountryForm" name="addCountryForm" method="post" action="<?php echo $this->url('country',array('action'=>'add')); ?>">
        <div class="card">
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <input id="countryName" name="countryName" type="text" class="validate isRequired" title="Please enter country name" onblur="checkNameValidation('country', 'country_name', this, null,'The country name that you entered already exist. Please enter different country name.')">
                        <label for="countryName" class="">Country Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <input id="countryCode" name="countryCode" type="text" class="validate isRequired" title="Please enter country code" onblur="checkNameValidation('country', 'country_code', this, null,'The country code that you entered already exist. Please enter different country code.')">
                        <label for="countryCode" class="">Country Code *</label>
                    </div>
                </div>
            </div>
            
            <div class="col s12">
                <a href="<?php echo $this->url('country'); ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addCountry();">ADD</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script>
    function addCountry(){
        flag = deforayValidator.init({
               formId: 'addCountryForm'
        });
        
        if(flag){
            document.getElementById('addCountryForm').submit();
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if(checkValue!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
</script>