<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/css/jquery-ui.css' ?>"/>
<style>
    .card-header{
        background-color:#ff69b4;
    }
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        padding: 10px 20px;
    }
    table th,table td{
        text-align:center;
    }
    tbody tr td {
        border-top: 1px solid #ddd;
    }
    #countryLabDataReportingTable_wrapper,#countryClinicDataReportingTable_wrapper{
	overflow-x:scroll;
    }
    .ui-datepicker-calendar {
       display: none;
    }
    .ui-datepicker-month,.ui-datepicker-year{
       display:block;
       display:inline-block;
    }
    .ui-datepicker-title select{
	padding:0;
	height:1.5rem;
    }
    .total_row{
	font-size:15px !important;
	font-weight:800 !important;
    }
</style>
<div id="page-content">
    <div class="row section-header">
	<div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Dashboard (<?php echo (isset($countryInfo->country_name) && trim($countryInfo->country_name)!= '')?ucwords($countryInfo->country_name):'#'; ?>)</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Dashboard</a>
        </div>
    </div>
    <div class="row" style="max-width:1109px;">
        <form id="countryDashboardFilter" action="#">
	    <div class="row">
		<div class="col s4">
		    <div class="input-field col m11 s11">
			<input id="reportingMonthYear" name="reportingMonthYear" type="text" class="monthYear" title="Please select month and year" readonly>
			<label for="reportingMonthYear">Month/Year </label>
		    </div>
		    <div class="col m1 s1" style="padding-top:4vh;">
		        <a href="javascript:void(0);" title="Clear" onclick="clearReportingDate();" style="font-size:16px;color:#333333;"><i class="zmdi zmdi-close"></i></a>
		    </div>
		</div>
		<div class="col s4">
		    <div class="input-field col m12 s12">
			<select class="material-select" id="province" name="province" title="Please select province">
			    <option value=""> All Provinces </option>
			    <?php foreach($provinces as $province) { ?>
			       <option value="<?php echo base64_encode($province['location_id']); ?>"><?php echo ucwords($province['location_name']); ?></option>
			    <?php } ?>
			</select>
			<label for="province">Province </label>
		    </div>
		</div>
		<div class="col s4">
		    <div class="input-field col m12 s12">
			<select class="material-select" id="specimenType" name="specimenType[]" multiple="multiple" title="Please select speciment type">
			    <option value="" disabled selected> All Sample Types </option>
			    <option value="1">Venous</option>
			    <option value="2">Plasma</option>
			    <option value="3">DBS</option>
			</select>
			<label for="specimenType">Sample Type </label>
		    </div>
		</div>
	    </div>
            <div class="col l12 m12 s12" style="text-align:center;margin-bottom:20px;">
		<a href="javascript:void(0);" onclick="searchDashboardData('search');" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="exportDashboardData();" class="waves-effect waves-light btn-small btn green-text custom-btn custom-btn-green"><i class="zmdi zmdi-collection-text"></i> Export Excel</a>&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="javascript:void(0);" onclick="clearSearchFields();" class="waves-effect waves-light btn-small btn red-text custom-btn custom-btn-red"><i class="zmdi zmdi-refresh"></i> Reset Filters </a>
            </div>
        </form>
    </div>
    <div class="row content-container">
	<div class="col l12 m12 s12">
	    <input class="with-gap" name="labDataReportingDate" id="labDataAddedOn" value="added_on" type="radio" checked="checked" onchange="searchCountryLabDataReportingDeatils('change');"/>
	    <label for="labDataAddedOn" style="padding-left:25px;color:#333333;font-weight:600;">Data Entry Date </label>&nbsp;&nbsp;&nbsp;&nbsp;
	    <input class="with-gap" name="labDataReportingDate" id="sampleCollectionOn" value="specimen_collected_date" type="radio" onchange="searchCountryLabDataReportingDeatils('change');"/>
	    <label for="sampleCollectionOn" style="padding-left:25px;color:#333333;font-weight:600;">Sample Collection Date </label>
	</div>
        <div class="col s12">
            <div class="card card-default">
                <div class="card-header white-text">
                    Lab Data Reporting
                </div>
                <div class="card-content clearfix">
                    <table id="countryLabDataReportingTable" class="responsive-table display">
                        <thead>
                        <tr>
                            <th>Lab Name</th>
			    <th>Month - Year</th>
			    <th>No. of ANC Sites</th>
                            <th>Samples Received</th>
			    <th>Samples Incomplete</th>
                            <th>Samples Tested</th>
                            <th>Samples Locked for Editing</th>
                            <th>Lab LAg Recent</th>
                            <th>Lab Rapid Recency Assay Recent (Visual)</th>
                        </tr>
                        </thead>
                        <tbody id="countryLabDataReportingDetails"></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row content-container">
	<div class="col l12 m12 s12">
	    <input class="with-gap" name="clinicDataReportingDate" id="clinicDataAddedOn" value="added_on" type="radio" checked="checked" onchange="searchCountryANCDataReportingDeatils('change');"/>
	    <label for="clinicDataAddedOn" style="padding-left:25px;color:#333333;font-weight:600;">Data Entry Date </label>&nbsp;&nbsp;&nbsp;&nbsp;
	    <input class="with-gap" name="clinicDataReportingDate" id="interviewOn" value="interview_date" type="radio" onchange="searchCountryANCDataReportingDeatils('change');"/>
	    <label for="interviewOn" style="padding-left:25px;color:#333333;font-weight:600;">Interview Date </label>
	</div>
        <div class="col s12">
            <div class="card card-default">
                <div class="card-header white-text">
                    ANC Data Reporting
                </div>
                <div class="card-content clearfix">
                    <table id="countryClinicDataReportingTable" class="responsive-table display">
                        <thead>
                        <tr>
			    <th>Province Name</th>
			    <th>Month - Year</th>
			    <th>No. of ANC Sites</th>
                            <th>Risk Questionnaires</th>
			    <th>ANC Rapid Recency Assay Recent (Visual)</th>
                        </tr>
                        </thead>
                        <tbody id="countryClinicDataReportingDetails"></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <hr style="border:1px solid #e0dddd;">
    <br>
    <div class="row" style="max-width:1109px;">
	<form id="mapFilter" action="#">
	    <div class="row">
		<div class="col s4">
		    <div class="input-field col m11 s11">
			<input id="mapReportingMonthYear" name="mapReportingMonthYear" type="text" class="monthYear" title="Please select month and year" readonly>
			<label for="mapReportingMonthYear">Month/Year </label>
		    </div>
		    <div class="col m1 s1" style="padding-top:4vh;">
		        <a href="javascript:void(0);" title="Clear" onclick="clearMapReportingDate();" style="font-size:16px;color:#333333;"><i class="zmdi zmdi-close"></i></a>
		    </div>
		</div>
		<div class="col s4">
		    <div class="input-field col m12 s12">
			<select class="material-select" id="mapProvince" name="mapProvince" title="Please select province">
			    <option value=""> All Provinces </option>
			    <?php foreach($provinces as $province) { ?>
			       <option value="<?php echo base64_encode($province['location_id']); ?>"><?php echo ucwords($province['location_name']); ?></option>
			    <?php } ?>
			</select>
			<label for="mapProvince">Province </label>
		    </div>
		</div>
		<div class="col s4">
		    <div class="input-field col m12 s12">
			<select class="material-select" id="mapSpecimenType" name="mapSpecimenType[]" multiple="multiple" title="Please select speciment type">
			    <option value="" disabled selected> All Sample Types </option>
			    <option value="1">Venous</option>
			    <option value="2">Plasma</option>
			    <option value="3">DBS</option>
			</select>
			<label for="mapSpecimenType">Sample Type </label>
		    </div>
		</div>
	    </div>
	    <div class="row">
		<div class="col s6">
		    <div class="input-field col m12 s12">
			<select class="material-select" id="sitehavingRecentInfectionby" name="sitehavingRecentInfectionby[]" multiple title="Please select any option">
			    <option value="" disabled selected> All Types </option>
			    <option value="labLAgRecency">Lab LAg Test - Recent</option>
			    <option value="labRecencyAssay">Lab Rapid Recency Assay Test (Visual) - Recent </option>
			    <option value="ancRecencyAssay">ANC Rapid Recency Assay Test (Visual) - Recent </option>
			</select>
			<label for="mapSpecimenType">Site having Recent HIV Infection by </label>
		    </div>
		</div>
	    </div>
	    <div class="col l12 m12 s12" style="text-align:center;margin-bottom:20px;">
		<a href="javascript:void(0);" onclick="clearMapSearchFields();" class="waves-effect waves-light btn-small btn red-text custom-btn custom-btn-red"><i class="zmdi zmdi-refresh"></i> Reset Filters</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="getDataReportingLocations('search');" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a>
	    </div>
	</form>
    </div>
    <div class="row content-container">
	<div class="col s12">
	    <div class="card card-default">
		<div class="col l12 m12 s12" style="margin-top:3vh;">
		    <div class="col l3 m3 s3" style="float:right;">&nbsp;&nbsp;<img src="<?php echo $this->basePath('assets/images/map-points/blue.png'); ?>"> <strong>ANC Site</strong></div>
		</div>
		<div class="col l12 m12 s12" style="margin-top:3vh;">
		    <div class="col l4 m3 s3">
		        <svg height="20" width="40" style="float:left;">
 			   <circle cx="20" cy="10" r="8" stroke="#FF0000" stroke-width="2" fill="#F79D9A"/>
 			</svg>
		       <div style="float:left;">&nbsp;&nbsp;<strong>Lab LAg Test - Recent</strong></div>
		    </div>
		    <div class="col l4 m3 s3">
		       <img style="float:left;padding-top:3px;" src="<?php echo $this->basePath('assets/images/map-points/yellow.png'); ?>">
		       <div style="float:left;">&nbsp;&nbsp;<strong>Lab Rapid Recency Assay Test (Visual) - Recent </strong></div>
		    </div>
		    <div class="col l4 m3 s3">
		       <img style="float:left;padding-top:3px;" src="<?php echo $this->basePath('assets/images/map-points/purple.png'); ?>">
		       <div style="float:left;">&nbsp;&nbsp;<strong>ANC Rapid Recency Assay Test (Visual) - Recent </strong></div>
		    </div>
		</div>
		<div class="card-content map-container clearfix" style="padding-top:20px;">
		</div>
	    </div>
	</div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery-ui.js' ?>"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM"></script>
<script>
    $(document).ready(function(){
        $('#reportingMonthYear').datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'M/yy',
            maxDate: 'Today',
            beforeShow : function(input, inst) {
                tmp = $('#reportingMonthYear').val().split('/');
                var dat = new Date('1 ' + tmp[0] + ' 1969');
                $('#reportingMonthYear').datepicker('option','defaultDate',new Date(tmp[1],parseInt(dat.getMonth()-1)+parseInt(1),1));
                $('#reportingMonthYear').datepicker('setDate', new Date(tmp[1], parseInt(dat.getMonth()-1)+parseInt(1), 1));
            },
            onClose: function(dateText, inst) {
                var month=$("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $('#reportingMonthYear').datepicker('setDate', new Date(year, month, 1));
            }
       });
	$('#mapReportingMonthYear').datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'M/yy',
            maxDate: 'Today',
            beforeShow : function(input, inst) {
                tmp = $('#mapReportingMonthYear').val().split('/');
                var dat = new Date('1 ' + tmp[0] + ' 1969');
                $('#mapReportingMonthYear').datepicker('option','defaultDate',new Date(tmp[1],parseInt(dat.getMonth()-1)+parseInt(1),1));
                $('#mapReportingMonthYear').datepicker('setDate', new Date(tmp[1], parseInt(dat.getMonth()-1)+parseInt(1), 1));
            },
            onClose: function(dateText, inst) {
                var month=$("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $('#mapReportingMonthYear').datepicker('setDate', new Date(year, month, 1));
            }
       });
       searchDashboardData('load');
       getDataReportingLocations('load');
    });
    
    function searchDashboardData(frmSrc){
	searchCountryLabDataReportingDeatils(frmSrc);
	searchCountryANCDataReportingDeatils(frmSrc);
    }
    
    function searchCountryLabDataReportingDeatils(frmSrc){
        var reportingMonthYear = $('#reportingMonthYear').val();
        var province = $('#province').val();
        var specimenType = ($('#specimenType').val()!= null)?$('#specimenType').val().join(','):'';
	var labDataReportingDate = $("input:radio[name=labDataReportingDate]:checked").val();
        if(frmSrc!= 'load' && frmSrc!= 'change') { $.blockUI(); }
            $.post("<?php echo $this->url('country',array('action'=>'get-lab-data-reporting-details')); ?>", {country:'<?php echo $countryInfo->country_id; ?>',reportingMonthYear: reportingMonthYear,province:province,specimenType:specimenType,labDataReportingDate:labDataReportingDate},
            function(data) {
            if(frmSrc!= 'load' && frmSrc!= 'change') { $.unblockUI(); }
                $('#countryLabDataReportingDetails').html(data);
            });
    }
    
    function searchCountryANCDataReportingDeatils(frmSrc){
	var reportingMonthYear = $('#reportingMonthYear').val();
        var province = $('#province').val();
        var specimenType = ($('#specimenType').val()!= null)?$('#specimenType').val().join(','):'';
	var clinicDataReportingDate = $("input:radio[name=clinicDataReportingDate]:checked").val();
        if(frmSrc!= 'load' && frmSrc!= 'change') { $.blockUI(); }
            $.post("<?php echo $this->url('country',array('action'=>'get-clinic-data-reporting-details')); ?>", {country:'<?php echo $countryInfo->country_id; ?>',reportingMonthYear: reportingMonthYear,province:province,specimenType:specimenType,clinicDataReportingDate:clinicDataReportingDate},
            function(data) {
            if(frmSrc!= 'load' && frmSrc!= 'change') { $.unblockUI(); }
                $('#countryClinicDataReportingDetails').html(data);
            });
    }
    
    function getDataReportingLocations(frmSrc){
        var reportingMonthYear = $('#mapReportingMonthYear').val();
        var province = $('#mapProvince').val();
        var specimenType = ($('#mapSpecimenType').val()!= null)?$('#mapSpecimenType').val().join(','):'';
        //var hasSitePerformedRapidRecencyTest = $('#hasSitePerformedRapidRecencyTest').val();
        var sitehavingRecentInfectionby = ($('#sitehavingRecentInfectionby').val()!= null)?$('#sitehavingRecentInfectionby').val().join(','):'';
        if(frmSrc!= 'load') { $.blockUI(); }
            $.post("<?php echo $this->url('country',array('action'=>'get-data-reporting-locations')); ?>", {country:'<?php echo $countryInfo->country_id; ?>',reportingMonthYear: reportingMonthYear,province:province,specimenType:specimenType,/*hasSitePerformedRapidRecencyTest:hasSitePerformedRapidRecencyTest,*/sitehavingRecentInfectionby:sitehavingRecentInfectionby},
            function(data) {
            if(frmSrc!= 'load') { $.unblockUI(); }
                $('.map-container').html(data);
            });
    }
    
    function clearSearchFields(){
        $('#countryDashboardFilter')[0].reset();
        searchDashboardData('reset');
    }
    
    function clearMapSearchFields(){
	$('#mapFilter')[0].reset();
        getDataReportingLocations('reset');
    }
    
    function clearReportingDate(){
	if($('#reportingMonthYear').val()!= ''){
	   $('#reportingMonthYear').val('');
	   searchDashboardData('reset');
	}
    }
    
    function clearMapReportingDate(){
	if($('#mapReportingMonthYear').val()!= ''){
	   $('#mapReportingMonthYear').val('');
	   getDataReportingLocations('reset');
	}
    }
    
    function exportDashboardData(){
	$.blockUI();
	$.post("<?php echo $this->url('export-country-dashboard-data'); ?>", { countryname :'<?php echo $countryInfo->country_name; ?>'},
	function(data){
	    if(data == "" || data == null || data == undefined){
		alert('Error-Oops, Unable to generate excel');
		$.unblockUI();
	    }else{
		$.unblockUI();
		window.open("/temporary/"+data, "_blank");
	    }
	});
    }
</script>