<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/css/jquery-ui.css' ?>"/>
<style>
    .card-header{
        background-color:#ff69b4;
    }
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        padding: 10px 20px;
    }
    table th,table td{
        text-align:center;
    }
    tbody tr td {
        border-top: 1px solid #ddd;
    }
    #countryDashboardTable_wrapper{
	overflow-x:scroll;
    }
    .ui-datepicker-calendar {
       display: none;
    }
    .ui-datepicker-month,.ui-datepicker-year{
       display:block;
       display:inline-block;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <h4 class="page-title">Dashboard (<?php echo ucwords($countryInfo->country_name); ?>)</h4>
    </div>
    <div class="row" style="max-width:1109px;">
        <form id="dashboardFilter" action="#">
            <div class="col l12 m12 s12">
                <div class="col l4 m4 s4" style="text-align:center;"><strong>Month/Year </strong> <input type="text" class="monthYear" id="reportingMonthYear" name="reportingMonthYear" placeholder="Select Month and Year" title="Please select month and year" readonly/></div>
		<div class="col l4 m4 s4" style="text-align:center;"><strong>Provinces </strong> <select class="material-select" id="province" name="province" title="Please select province"><option value=""> -- Select -- </option><?php foreach($provinces as $province) { ?><option value="<?php echo base64_encode($province['location_id']); ?>"><?php echo ucwords($province['location_name']); ?></option><?php } ?></select></div>
		<div class="col l4 m4 s4" style="text-align:center;"><strong>Sample Type </strong> <select class="material-select" id="specimenType" name="specimenType[]" multiple="multiple" title="Please select speciment type"><option value="1">Venous</option><option value="2">Plasma</option><option value="3">DBS</option></select></div>
            </div>
            <div class="col l12 m12 s12" style="text-align:center;margin-bottom:20px;">
                <a href="javascript:void(0);" onclick="clearSearchFields();" class="waves-effect waves-light btn-small btn red-text custom-btn custom-btn-red"><i class="zmdi zmdi-refresh"></i> Reset</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="searchDashboardData('search');getDataReportingLocations();" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="extractDashboardData();" class="waves-effect waves-light btn-small btn green-text custom-btn custom-btn-green"><i class="zmdi zmdi-collection-text"></i> Export Excel</a>
            </div>
        </form>
    </div>
    <div class="row">
        <div class="col s12">
            <div class="card card-default">
                <div class="card-header white-text">
                    Lab Data Reporting/Completed Forms
                </div>
                <div class="card-content clearfix">
                    <table id="countryDashboardTable" class="responsive-table display">
                        <thead>
                        <tr>
                            <th>Name of the Province</th>
                            <th>Samples Received</th>
			    <th>Samples Incomplete</th>
                            <th>Samples Tested</th>
                            <th>Samples Finalized</th>
			    <th>No. of LAg Recent</th>
			    <th>No. of Recency Assay Recent</th>
			    <th>No. of Risk Questionnaires</th>
			    <th>No. of ANC Recency Test</th>
                            <th>Month - Year</th>
                        </tr>
                        </thead>
                        <tbody id="dashboardDetails"></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <div class="card card-default">
		<div class="col l12 m12 s12" style="margin-top:3vh;">
		    <div class="col l2 m2 s2"><img src="<?php echo $this->basePath('assets/images/map-points/lab-red.png'); ?>"> <strong>ANC Site</strong></div>
		    <div class="col l2 m2 s2"><img src="<?php echo $this->basePath('assets/images/map-points/lab-green.png'); ?>"> <strong>Lab/Facility</strong></div>
		</div>
                <div class="card-content map-container clearfix" style="padding-top:20px;">
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery-ui.js' ?>"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhZa4hDifE6p2sbaxJehS7gcrZOJScIqM"></script>
<script>
    $(document).ready(function(){
        $('#reportingMonthYear').datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'M/yy',
            maxDate: 'Today',
            beforeShow : function(input, inst) {
                tmp = $('#reportingMonthYear').val().split('/');
                var dat = new Date('1 ' + tmp[0] + ' 1969');
                $('#reportingMonthYear').datepicker('option','defaultDate',new Date(tmp[1],parseInt(dat.getMonth()-1)+parseInt(1),1));
                $('#reportingMonthYear').datepicker('setDate', new Date(tmp[1], parseInt(dat.getMonth()-1)+parseInt(1), 1));
            },
            onClose: function(dateText, inst) {
                var month=$("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $('#reportingMonthYear').datepicker('setDate', new Date(year, month, 1));
            }
       });
       searchDashboardData('load');
       getDataReportingLocations();
    });
    
    function searchDashboardData(frmSrc){
        var reportingMonthYear = $('#reportingMonthYear').val();
	var province = $('#province').val();
	var specimenType = ($('#specimenType').val()!= null)?$('#specimenType').val().join(','):'';
	if(frmSrc!= 'load') { $.blockUI(); }
        $.post("<?php echo $this->url('country',array('action'=>'get-dashboard-details')); ?>", {country:'<?php echo $countryInfo->country_id; ?>',reportingMonthYear: reportingMonthYear,province:province,specimenType:specimenType},
        function(data) {
	    if(frmSrc!= 'load') { $.unblockUI(); }
            $('#dashboardDetails').html(data);
        });
    }
    
    function getDataReportingLocations(){
	var reportingMonthYear = $('#reportingMonthYear').val();
	var province = $('#province').val();
	var specimenType = ($('#specimenType').val()!= null)?$('#specimenType').val().join(','):'';
        $.post("<?php echo $this->url('country',array('action'=>'get-data-reporting-locations')); ?>", {country:'<?php echo $countryInfo->country_id; ?>',reportingMonthYear: reportingMonthYear,province:province,specimenType:specimenType},
        function(data) {
            $('.map-container').html(data);
        });
    }
    
    function clearSearchFields(){
        $('#dashboardFilter')[0].reset();
        $('#dashboardFilter .select-dropdown').val('');
        searchDashboardData('reset');
        getDataReportingLocations();
    }
    
    function extractDashboardData(){
	$.blockUI();
	$.post("<?php echo $this->url('export-country-dashboard-data'); ?>", { countryname :'<?php echo $countryInfo->country_name; ?>'},
	function(data){
	    if(data == "" || data == null || data == undefined){
		alert('OOPS..Unable to generate excel.');
		$.unblockUI();
	    }else{
		$.unblockUI();
		window.open("/temporary/"+data, "_blank");
	    }
	});
    }
</script>