<div id="page-content">
    <div class="row section-header">
        <h4 class="page-title">Edit Country</h4>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="editCountryForm" name="editCountryForm" method="post" action="<?php echo $this->url('country',array('action'=>'edit')); ?>">
        <div class="card">
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <input id="countryName" name="countryName" type="text" class="validate isRequired" title="Please enter country name" value="<?php echo $row->country_name; ?>" onblur="checkNameValidation('country', 'country_name', this, '<?php echo "country_id##" .$row->country_id; ?>','The country name that you entered already exist. Please enter different country name.')">
                        <label for="countryName" class="">Country Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <input id="countryCode" name="countryCode" type="text" class="validate isRequired" title="Please enter country code" value="<?php echo $row->country_code; ?>" onblur="checkNameValidation('country', 'country_code', this, '<?php echo "country_id##" .$row->country_id; ?>','The country code that you entered already exist. Please enter different country code.')">
                        <label for="countryCode" class="">Country Code *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <select id="countryStatus" name="countryStatus" class="material-select">
                            <option value="active" <?php echo($row->status == "active")?'selected="selected"':'';  ?>>Active</option>
                            <option value="inactive" <?php echo($row->status == "inactive")?'selected="selected"':'';  ?>>Inactive</option>
                        </select>
                        <label for="countryStatus" class="">Country Status</label>
                    </div>
                </div>
            </div>
            <div class="col s12">
                <input id="countryId" name="countryId" type="hidden" value="<?php echo base64_encode($row->country_id); ?>"/>
                <a href="<?php echo $this->url('country'); ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addCountry();">UPDATE</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script>
    function addCountry(){
        flag = deforayValidator.init({
               formId: 'editCountryForm'
        });
        
        if(flag){
            document.getElementById('editCountryForm').submit();
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if(checkValue!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
</script>