<?php
$province = '';
$province.= '<i class="material-icons prefix">room</i>';
$province.='<select class="material-select validate isRequired" id="province" name="province" title="Please select province" onchange="checkProvince(this.value);">';
$province.='<option data-latitude="" data-longitude="" value=""> -- Select -- </option>';
        foreach($response as $pv){
          $province.='<option data-latitude="'.$pv['latitude'].'" data-longitude="'.$pv['longitude'].'" value="'.base64_encode($pv['province_id']).'">'.ucwords($pv['province_name']).'</option>';
        }
        $province.='<option data-latitude="" data-longitude="" value="other">Other</option>';
$province.='</select>';
$province.='<label for="province" class="">Province *</label>';
$province.='<input type="text" id="provinceNew" name="provinceNew" placeholder="Enter Province" title="Please enter province name" class="validate" style="display:none;"/>';
echo $province;