<?php
$location = 0;
$ancArray = array();
$sitehavingRecentInfectionbyArray = array();
if(trim($params['sitehavingRecentInfectionby'])!= ''){
    $sitehavingRecentInfectionbyArray = explode(",",$params['sitehavingRecentInfectionby']);
}
if(isset($response['labRecent']) && count($response['labRecent']) > 0){
    foreach($response['labRecent'] as $labRecentPoint){
        if(trim($labRecentPoint['latitude'])!= '' && trim($labRecentPoint['longitude'])!= '' && (trim($params['sitehavingRecentInfectionby']) == '' || in_array('labLAgRecency',$sitehavingRecentInfectionbyArray) || in_array('labRecencyAssay',$sitehavingRecentInfectionbyArray))){
            $location+= 1;
            if(!in_array($labRecentPoint['anc_site_name'],$ancArray)){
                $ancArray[] = $labRecentPoint['anc_site_name'];
                $ancArray[$labRecentPoint['anc_site_name']]['lat'] = $labRecentPoint['latitude'];
                $ancArray[$labRecentPoint['anc_site_name']]['lon'] = $labRecentPoint['longitude'];
            }
            
            if(trim($params['sitehavingRecentInfectionby'])!= ''){
                if(in_array('labLAgRecency',$sitehavingRecentInfectionbyArray)){
                    $ancArray[$labRecentPoint['anc_site_name']]['color'][] = 'red';
                    $ancArray[$labRecentPoint['anc_site_name']]['recents'][] = (int)$labRecentPoint['noofLAgRecent'];
                }
                if(in_array('labRecencyAssay',$sitehavingRecentInfectionbyArray)){
                    $ancArray[$labRecentPoint['anc_site_name']]['color'][] = 'yellow';
                    $ancArray[$labRecentPoint['anc_site_name']]['recents'][] = (int)$labRecentPoint['noofLabRecencyAssayRecent'];
                }
            }else{
                $ancArray[$labRecentPoint['anc_site_name']]['color'][] = 'default-red';
                $ancArray[$labRecentPoint['anc_site_name']]['recents'][] = (int)$labRecentPoint['noofLAgRecent'];
               
                $ancArray[$labRecentPoint['anc_site_name']]['color'][] = 'default-yellow';
                $ancArray[$labRecentPoint['anc_site_name']]['recents'][] = (int)$labRecentPoint['noofLabRecencyAssayRecent'];
            }
        }
    }
}
if(isset($response['ancRecent']) && count($response['ancRecent']) > 0){
    foreach($response['ancRecent'] as $ancRecentPoint){
        if(trim($ancRecentPoint['latitude'])!= '' && trim($ancRecentPoint['longitude'])!= '' && (trim($params['sitehavingRecentInfectionby']) == '' || in_array('ancRecencyAssay',$sitehavingRecentInfectionbyArray))){
            $location+= 1;
            if(!in_array($ancRecentPoint['anc_site_name'],$ancArray)){
                $ancArray[] = $ancRecentPoint['anc_site_name'];
                $ancArray[$ancRecentPoint['anc_site_name']]['lat'] = $ancRecentPoint['latitude'];
                $ancArray[$ancRecentPoint['anc_site_name']]['lon'] = $ancRecentPoint['longitude'];
            }
            
            if(trim($params['sitehavingRecentInfectionby'])!= ''){
                if(in_array('ancRecencyAssay',$sitehavingRecentInfectionbyArray)){
                    $ancArray[$ancRecentPoint['anc_site_name']]['color'][] = 'purple';
                    $ancArray[$ancRecentPoint['anc_site_name']]['recents'][] = (int)$ancRecentPoint['noofANCRecencyTestRecent'];
                }
            }else{
                $ancArray[$ancRecentPoint['anc_site_name']]['color'][] = 'default-purple';
                $ancArray[$ancRecentPoint['anc_site_name']]['recents'][] = (int)$ancRecentPoint['noofANCRecencyTestRecent'];
            }
        }
    }
}
if($location > 0) { ?>
    <div class="gmap" id="gmap" style="min-height: 500px;width:100%;"></div>
    <script>
        $(document).ready(function(){
            var map;
            var bounds = new google.maps.LatLngBounds();
            var prev_infowindow = false;
            var mapOptions = {
                mapTypeId: 'roadmap',
                scrollwheel: false
            };  
           // Display a map on the page
           map = new google.maps.Map(document.getElementById("gmap"),mapOptions);
            // Multiple Markers
            var markers = [
                <?php
                if(isset($ancArray) && count($ancArray) > 0){
                    for($i=0;$i< count($ancArray);$i++){
                        if(isset($ancArray[$i])) {
                    ?>
                    {
                        lat:"<?php echo $ancArray[$ancArray[$i]]['lat']; ?>",
                        lon:"<?php echo $ancArray[$ancArray[$i]]['lon']; ?>",
                        icon:"<?php echo implode(',',$ancArray[$ancArray[$i]]['color']); ?>",
                        recents:"<?php echo implode(',',$ancArray[$ancArray[$i]]['recents']); ?>",
                        label:"<h6><?php echo ucwords($ancArray[$i]);?></h6>"
                    },
                    <?php }
                    }
                }
                ?>
            ];
            
            // Loop through our array of markers & place each one on the map
            for( i = 0; i < markers.length; i++ ) {
                var position = new google.maps.LatLng(markers[i]['lat'], markers[i]['lon']);
                bounds.extend(position);
                var iconArray = markers[i]['icon'].split(",");
                var recentsArray = markers[i]['recents'].split(",");
                var iconImg;
                var contentString = markers[i]['label'];
                var infowindow = new google.maps.InfoWindow({});
                var redCircle = false;
                for( t = 0; t < iconArray.length; t++ ) {
                    if(iconArray[t] == 'red' && recentsArray[t] > 0){
                       redCircle = true;
                       contentString+= '<span style="color:red;">Lab LAg Test - Recent (<strong>'+recentsArray[t]+'</strong>)</span><br>';
                    }else if(iconArray[t] == 'yellow' && recentsArray[t] > 0){
                       iconImg = '<?php echo $this->basePath('assets/images/map-points/yellow.png'); ?>';
                       contentString+= '<span style="color:#f39c12;">Lab Rapid Recency Assay Test (Visual) - Recent (<strong>'+recentsArray[t]+'</strong>)</span><br>';
                    }else if(iconArray[t] == 'purple' && recentsArray[t] > 0){
                       iconImg = '<?php echo $this->basePath('assets/images/map-points/purple.png'); ?>';
                       contentString+= '<span style="color:purple;">ANC Rapid Recency Assay Test (Visual)- Recent (<strong>'+recentsArray[t]+'</strong>)</span><br>';
                    }else if(iconArray[t] == 'default-red'){
                       iconImg = '<?php echo $this->basePath('assets/images/map-points/blue.png'); ?>';
                       contentString+= '<span style="color:red;">Lab LAg Test - Recent (<strong>'+recentsArray[t]+'</strong>)</span><br>';
                    }else if(iconArray[t] == 'default-yellow'){
                       iconImg = '<?php echo $this->basePath('assets/images/map-points/blue.png'); ?>';
                       contentString+= '<span style="color:#f39c12;">Lab Rapid Recency Assay Test (Visual)- Recent (<strong>'+recentsArray[t]+'</strong>)</span><br>';
                    }else if(iconArray[t] == 'default-purple'){
                       iconImg = '<?php echo $this->basePath('assets/images/map-points/blue.png'); ?>';
                       contentString+= '<span style="color:purple;">ANC Rapid Recency Assay Test (Visual) - Recent (<strong>'+recentsArray[t]+'</strong>)</span><br>';
                    }
                }
                for( j = 0; j < iconArray.length; j++ ) {
                    if(redCircle){
                       var cityCircle = new google.maps.Circle({
                            strokeColor: '#FF0000',
                            strokeOpacity: 0.8,
                            strokeWeight: 2,
                            fillColor: '#F79D9A',
                            fillOpacity: 0.35,
                            map: map,
                            center: position,
                            label: contentString,
                            radius: 44 * 100
                       });
                       
                        var marker = new google.maps.Marker({
                            map: map
                        });
                        google.maps.event.addListener(cityCircle, 'mouseover', function() {
                            marker.setPosition(this.getCenter());
                            infowindow.setContent(this.label); // set content
                            infowindow.open(map, marker); // open at marker's location
                            marker.setVisible(false); // hide the marker
                        });
                        google.maps.event.addListener(cityCircle, 'mouseout', function () {
                            infowindow.close();
                        });
                        break;
                    }else{
                       marker = new google.maps.Marker({
                        position: position,
                        map: map,
                        icon: iconImg
                        });
                        
                        marker['infowindow'] = new google.maps.InfoWindow({
                            content:contentString,
                            //maxWidth: 400
                        });
                        google.maps.event.addListener(marker, 'mouseover', function() {
                            current_infowindow = this['infowindow'];
                            current_infowindow.open(map, this);
                        });
                        google.maps.event.addListener(marker, 'mouseout', function () {
                            current_infowindow.close();
                        });
                    }
                }
                // Automatically center the map fitting all markers on the screen
                map.fitBounds(bounds);
            }
            // Override our map zoom level once our fitBounds function runs (Make sure it only runs once)
            var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function(event) {
                this.setZoom(8);
                google.maps.event.removeListener(boundsListener);
            });
         });
    </script>
<?php } else { ?>
    <div style="text-align:center;"><h6>Location not available..</h6></div>
<?php } ?>