<?php
$provinces = '';
$provinces.= '<i class="material-icons prefix">room</i>';
$provinces.='<select class="material-select validate isRequired" id="province" name="province" title="Please select province" onchange="checkProvince(this.value);">';
$provinces.='<option value=""> -- Select -- </option>';
        foreach($response as $province){
          $provinces.='<option value="'.base64_encode($province['location_id']).'">'.ucwords($province['location_name']).'</option>';
        }
        $provinces.='<option value="other">Other</option>';
$provinces.='</select>';
$provinces.='<label for="province" class="">Province *</label>';
$provinces.='<input type="text" id="provinceNew" name="provinceNew" placeholder="Enter Province" title="Please enter province name" class="validate" style="display:none;"/>';
echo $provinces;