<?php
$location = 0;
if(isset($response['facilities']) && count($response['facilities']) > 0){
    foreach($response['facilities'] as $facilities){
        if(trim($facilities['latitude'])!= '' && trim($facilities['longitude'])!= ''){
            $location+=1;
        }
    }
}

if(isset($response['anc']) && count($response['anc']) > 0){
    foreach($response['anc'] as $anc){
        if(trim($anc['latitude'])!= '' && trim($anc['longitude'])!= ''){
           $location+=1;
        }
    }
}
if($location > 0) { ?>
    <div class="gmap" id="gmap" style="min-height: 500px;width:100%;"></div>
    <script>
        $(document).ready(function(){
            var map;
            var bounds = new google.maps.LatLngBounds();
            var prev_infowindow = false;
            var mapOptions = {
                mapTypeId: 'roadmap',
                scrollwheel: false
            };  
           // Display a map on the page
           map = new google.maps.Map(document.getElementById("gmap"),mapOptions);
            // Multiple Markers
            var markers = [
                //facilities
                <?php
                if(isset($response['facilities']) && count($response['facilities']) > 0){
                    foreach($response['facilities'] as $facilities){
                        if(trim($facilities['latitude'])!= '' && trim($facilities['longitude'])!= ''){
                ?>
                {
                 lat: "<?php echo $facilities['latitude']; ?>",
                 lon: "<?php echo $facilities['longitude']; ?>",
                 icon : "<?php echo $this->basePath('assets/images/map-points/lab-green.png'); ?>",
                 label : "<h6><?php echo ucwords($facilities['facility_name']);?></h6>"
                },
                <?php } } } ?>
                //anc sites
                <?php
                if(isset($response['anc']) && count($response['anc']) > 0){
                    foreach($response['anc'] as $anc){
                        if(trim($anc['latitude'])!= '' && trim($anc['longitude'])!= ''){
                ?>
                {
                 lat: "<?php echo $anc['latitude']; ?>",
                 lon: "<?php echo $anc['longitude']; ?>",
                 icon : "<?php echo $this->basePath('assets/images/map-points/lab-red.png'); ?>",
                 label : "<h6><?php echo ucwords($anc['anc_site_name']);?></h6>"
                },
                <?php } } } ?>
            ];
            
            // Loop through our array of markers & place each one on the map
            for( i = 0; i < markers.length; i++ ) {
                var position = new google.maps.LatLng(markers[i]['lat'], markers[i]['lon']);
                bounds.extend(position);
                marker = new google.maps.Marker({
                    position: position,
                    map: map,
                    //title: markers[i]['title'],
                    icon : markers[i]['icon'],
                });
                marker['infowindow'] = new google.maps.InfoWindow({
                    content: markers[i]['label']    
                });
                google.maps.event.addListener(marker, 'mouseover', function() {
                    if( prev_infowindow ) {
                       prev_infowindow.close();
                    }
            
                    prev_infowindow = this['infowindow'];
                    prev_infowindow.open(map, this);
                    setTimeout(function() { prev_infowindow.close(); }, 3000);
                });
                // Automatically center the map fitting all markers on the screen
                map.fitBounds(bounds);
            }
            // Override our map zoom level once our fitBounds function runs (Make sure it only runs once)
            var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function(event) {
                this.setZoom(8);
                google.maps.event.removeListener(boundsListener);
            });
         });
    </script>
<?php } else { ?>
    <div style="text-align:center;"><h6>Location not available..</h6></div>
<?php } ?>