<?php
if(count($response) >0){
    foreach($response as $country){
?>
    <tr>
        <td><?php echo ucwords($country['province']); ?></td>
        <td><?php echo $country['totalDataPoints']; ?></td>
        <td><?php echo $country['dataPointFinalized']; ?></td>
        <td><?php echo $country['assessment_id']; ?></td>
        <td><?php echo $country['month'].' - '.$country['year']; ?></td>
        
    </tr>
<?php } } else { ?>
    <tr>
        <td colspan="4">No data available..</td>
    </tr>
<?php } ?>