<?php
if(count($response) >0){
    $samplesReceivedArray = array();
    $samplesIncompleteArray = array();
    $samplesTestedArray = array();
    $samplesFinalizedArray = array();
    $noofLAgRecentArray = array();
    $noofLabRecencyAssayRecentArray = array();
    foreach($response as $country){
        $samplesReceivedArray[] = $country['totalSample'];
        $samplesIncompleteArray[] = $country['samplesIncomplete'];
        $samplesTestedArray[] = $country['samplesTested'];
        $samplesFinalizedArray[] = $country['samplesFinalized'];
        $noofLAgRecentArray[] = $country['noofLAgRecent'];
        $noofLabRecencyAssayRecentArray[] = $country['noofLabRecencyAssayRecent'];
?>
    <tr>
        <td><?php echo $country['monthName'].' - '.$country['year']; ?></td>
        <td><?php echo (isset($country['location_name']))?ucwords($country['location_name']):''; ?></td>
        <td><?php echo ucwords($country['facility_name']); ?></td>
        <td><?php echo ($country['totalSample'] >0)?'<a href="/data-collection/' . base64_encode($country['country']) . '?type=s-received&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$country['totalSample'].'</a>':0; ?></td>
        <td><?php echo ($country['samplesIncomplete'] >0)?'<a href="/data-collection/' . base64_encode($country['country']) . '?type=s-incomplete&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$country['samplesIncomplete'].'</a>':0; ?></td>
        <td><?php echo ($country['samplesTested'] >0)?'<a href="/data-collection/' . base64_encode($country['country']) . '?type=s-tested&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$country['samplesTested'].'</a>':0; ?></td>
        <td><?php echo ($country['samplesFinalized'] >0)?'<a href="/data-collection/' . base64_encode($country['country']) . '?type=s-finalized&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$country['samplesFinalized'].'</a>':0; ?></td>
        <td><?php echo ($country['noofLAgRecent'] >0)?'<a href="/data-collection/' . base64_encode($country['country']) . '?type=no-of-lag-rececnt&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$country['noofLAgRecent'].'</a>':0; ?></td>
        <td><?php echo ($country['noofLabRecencyAssayRecent'] >0)?'<a href="/data-collection/' . base64_encode($country['country']) . '?type=no-of-recency-assay-recent&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$country['noofLabRecencyAssayRecent'].'</a>':0; ?></td>
    </tr>
<?php } ?>
    <tr>
        <td colspan="3" class="total_row">Total</td>
        <td class="total_row"><?php echo array_sum($samplesReceivedArray); ?></td>
        <td class="total_row"><?php echo array_sum($samplesIncompleteArray); ?></td>
        <td class="total_row"><?php echo array_sum($samplesTestedArray); ?></td>
        <td class="total_row"><?php echo array_sum($samplesFinalizedArray); ?></td>
        <td class="total_row"><?php echo array_sum($noofLAgRecentArray); ?></td>
        <td class="total_row"><?php echo array_sum($noofLabRecencyAssayRecentArray); ?></td>
    </tr>
<?php } else { ?>
    <tr>
        <td colspan="9">No data available..</td>
    </tr>
<?php } ?>