<?php
if(count($response) >0){
    $assessmentArray = array();
    $noofANCRecencyAssayRecentArray = array();
    foreach($response as $country){
        $assessmentArray[] = $country['assessments'];
        $noofANCRecencyAssayRecentArray[] = (isset($country['noofANCRecencyTestRecent']))?$country['noofANCRecencyTestRecent']:0;
?>
    <tr>
        <td><?php echo $country['monthName'].' - '.$country['year']; ?></td>
        <td><?php echo (isset($country['location_name']))?ucwords($country['location_name']):''; ?></td>
        <td><?php echo ($country['assessments'] >0)?'<a href="/clinic/risk-assessment/' . base64_encode($country['country']) . '?type=assessment&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$country['assessments'].'</a>':0; ?></td>
        <td><?php echo (isset($country['noofANCRecencyTestRecent']) && $country['noofANCRecencyTestRecent'] >0)?'<a href="/clinic/risk-assessment/' . base64_encode($country['country']) . '?type=no-of-anc-recency-test&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$country['noofANCRecencyTestRecent'].'</a>':0; ?></td>
    </tr>
<?php } ?>
    <tr>
        <td colspan="2" class="total_row">Total</td>
        <td class="total_row"><?php echo array_sum($assessmentArray); ?></td>
        <td class="total_row"><?php echo array_sum($noofANCRecencyAssayRecentArray); ?></td>
    </tr>
<?php } else { ?>
    <tr>
        <td colspan="4">No data available..</td>
    </tr>
<?php } ?>