<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/daterangepicker/daterangepicker.css' ?>"/>
<style>
    .ranges{display: none;}
    .daterangepicker .ranges{
	width: 190px;
    }
    @font-face {
	font-family: 'Glyphicons Halflings';
	src: url('../assets/fonts/glyphicons-halflings-regular.eot');
	src: url('../assets/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../assets/fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../assets/fonts/glyphicons-halflings-regular.woff') format('woff'), url('../assets/fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../assets/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
    }
    .glyphicon {
      position: relative;
      top: 1px;
      display: inline-block;
      font-family: 'Glyphicons Halflings';
      font-style: normal;
      font-weight: normal;
      line-height: 1;
    
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }
    .glyphicon-arrow-left:before {
      content: "\e091";
    }
    .glyphicon-arrow-right:before {
      content: "\e092";
    }
    .glyphicon-arrow-up:before {
      content: "\e093";
    }
    .glyphicon-arrow-down:before {
      content: "\e094";
    }
    * {
      -webkit-box-sizing: border-box;
	 -moz-box-sizing: border-box;
	      box-sizing: border-box;
    }
    *:before,
    *:after {
      -webkit-box-sizing: border-box;
	 -moz-box-sizing: border-box;
	      box-sizing: border-box;
    }
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        background-color: #eaeaea;
        border-bottom: 1px solid #ccc;
        padding: 10px 20px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        left: -184px;
    }
    .select-wrapper{
	width:100%;
    }
    #dataExtractionDataTable_wrapper{
	overflow-x: scroll;
    }
    .dataTable_noWrap{
	white-space: nowrap;
        overflow: hidden;
    }
    table.dataTable tbody td{
	padding:4px 4px 4px 4px;
    }
    @media only screen and (max-width: 1024px){
	table.dataTable.display tbody tr:first-child td {
	    border-top: 1px solid #ddd;
        }
	table.dataTable tbody td{
	    padding: 6px 4px 6px 4px;
	}
    }
    .redTxt{
	color:#F44336 !important;
    }
    .yellowTxt,.remove_sorting_1_style{
	background-color:#FFFF00 !important;
    }
    .blueTxt{
	color:#3792a8 !important;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Lab Data Reporting for Asante on Whole Blood</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Lab Data Reporting for Asante on Whole Blood</a>
       </div>
    </div>
    <div id="showhide" class="row" style="display: none;position:absolute;z-index: 9999 !important;color:#333;font-size:12px;font-weight:bold;padding: 5px 0px 5px 5px;height:280px;background:#e0e0e0;">
	<div class="col m12">
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="0" id="iCol0" data-showhide="patient_barcode_id" class="showhideCheckBox" /> <label for="iCol0">Patient Barcode ID</label>
	    </div>
	    <!-- <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="1" id="iCol1" data-showhide="specimen_collected_date" class="showhideCheckBox"  /> <label for="iCol1">Specimen Collected Date</label>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="2" id="iCol2" data-showhide="anc_site_name" class="showhideCheckBox"  /> <label for="iCol2">ANC Site</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="3" id="iCol3" data-showhide="anc_site_code" class="showhideCheckBox"  /> <label for="iCol3">ANC Site Code</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="4" id="iCol4" data-showhide="anc_patient_id" class="showhideCheckBox"  /> <label for="iCol4">ANC Patient ID</label>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="5" id="iCol5" data-showhide="age" class="showhideCheckBox" /> <label for="iCol5">Age</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="6" id="iCol6" data-showhide="gestational_age" class="showhideCheckBox" /> <label for="iCol6">Gestation Age (Weeks)</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="7" id="iCol7" data-showhide="specimen_picked_up_date_at_anc" class="showhideCheckBox" /> <label for="iCol7">Specimen Pick Up Date at ANC</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="8" id="iCol8" data-showhide="facility_name" class="showhideCheckBox" /> <label for="iCol8">Lab/Facility</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="9" id="iCol9" data-showhide="facility_code" class="showhideCheckBox" /> <label for="iCol9">Lab/Facility Code</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="10" id="iCol10" data-showhide="lab_specimen_id" class="showhideCheckBox" /> <label for="iCol10">Lab Specimen ID</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="10" id="iCol10" data-showhide="rejection_code" class="showhideCheckBox" /> <label for="iCol10">Rejection Code At Central Lab</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="11" id="iCol11" data-showhide="receipt_date_at_central_lab" class="showhideCheckBox" /> <label for="iCol11">Receipt Date at Lab</label> <br>
	    </div> -->
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="1" id="iCol1" data-showhide="lab_tech_name" class="showhideCheckBox" /> <label for="iCol1">Lab Tech. Name/ID</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="2" id="iCol2" data-showhide="date_of_test_completion" class="showhideCheckBox" /> <label for="iCol2">Date of Test Completion</label> <br>
	    </div>
	    <!-- <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="14" id="iCol14" data-showhide="result_dispatched_date_to_clinic" class="showhideCheckBox" /> <label for="iCol14">Result Dispatched Date to Clinic</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="15" id="iCol15" data-showhide="final_lag_avidity_odn" class="showhideCheckBox" /> <label for="iCol15">LAg Avidity ODn</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="16" id="iCol16" data-showhide="lag_avidity_result" class="showhideCheckBox" /> <label for="iCol16">Lab LAg Recency<br>(Based on LAg ODn)</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="17" id="iCol17" data-showhide="hiv_rna" class="showhideCheckBox" /> <label for="iCol17">HIV RNA (cp/ml)</label> <br>
	    </div> 
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="18" id="iCol18" data-showhide="hiv_rna_gt_1000" class="showhideCheckBox" /> <label for="iCol18">HIV RNA > 1000 <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="18" id="iCol18" data-showhide="recent_infection" class="showhideCheckBox" /> <label for="iCol18">Lab LAg Recency<br>(Based on algorithm)</label> <br>
	    </div>-->
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="3" id="iCol3" data-showhide="asante_rapid_recency_assy_rrdt" class="showhideCheckBox" /> <label for="iCol3">Asante Positive Verification Line (Visual)</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="4" id="iCol4" data-showhide="asante_rapid_recency_assy_rrr" class="showhideCheckBox" /> <label for="iCol4">Asante Long Term Line (Visual)</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="5" id="iCol5" data-showhide="comments" class="showhideCheckBox" /> <label for="iCol5">Comments</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="6" id="iCol6" data-showhide="added_on" class="showhideCheckBox" /> <label for="iCol6">Added Date</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="7" id="iCol7" data-showhide="added_by" class="showhideCheckBox" /> <label for="iCol7">Added by</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="8" id="iCol8" data-showhide="updated_on" class="showhideCheckBox" /> <label for="iCol8">Last Updated Date</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="9" id="iCol9" data-showhide="updated_by" class="showhideCheckBox" /> <label for="iCol9">Last Updated by</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="10" id="iCol10" data-showhide="test_status_name" class="showhideCheckBox" /> <label for="iCol10">Status</label> <br>
	    </div>
	    <!-- <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="27" id="iCol27" data-showhide="date_result_returned_clinic" class="showhideCheckBox" /> <label for="iCol27">Date Result Returned at Clinic</label> <br>
	    </div>
	      <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="28" id="iCol28" data-showhide="date_returned_to_participant" class="showhideCheckBox" /> <label for="iCol28">Date Returned to Participant</label> <br>
	    </div> -->
	    <?php
	    if(trim($countryId) == ''){
	    ?>
	    <div class="col m3">
		<input type="hidden" id="countColumn" value="11"/>
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="11" id="iCol11" data-showhide="country_name" class="showhideCheckBox" /> <label for="iCol11">Country Name</label> <br>
	    </div>
	    <?php } else { ?>
	      <input type="hidden" id="countColumn" value="11"/>
	    <?php } ?>
	</div>
    </div>
    <div class="row" style="max-width:1109px;">
	<form id="searchFilterForm" action="#">
	    <!-- <div class="row">
		<div class="col s4">
		     <div class="input-field col m12 s12">
			<input id="specimenCollectedDate" name="specimenCollectedDate" type="text" title="Please enter specimen collected date" onclick="selectDate();" readonly>
			<label for="specimenCollectedDate">Specimen Collected Date </label>
		     </div>
		</div>
		<div class="col s4">
		     <div class="input-field col m12 s12">
			<select class="material-select" id="anc" name="anc" title="Please select anc">
			    <option value="">All ANCs</option>
			    < ?php
			    foreach($ancSites as $anc){
				?>
				<option value="< ?php echo base64_encode($anc['anc_site_id']);?>">< ?php echo $anc['anc_site_code'].' - '.ucwords($anc['anc_site_name']);?></option>
				< ?php
			    }
			    ?>
			</select>
			<label for="anc">ANC Site </label>
		     </div>
		</div>
		<div class="col s4">
		     <div class="input-field col m12 s12">
			<select class="material-select" id="lab" name="lab" title="Please select lab">
			    <option value="">All Labs/Facilities</option>
			    < ?php
			    foreach($facilities as $lab){
				?>
				<option value="< ?php echo base64_encode($lab['facility_id']);?>">< ?php echo $lab['facility_code'].' - '.ucwords($lab['facility_name']);?></option>
				< ?php
			    }
			    ?>
			</select>
			<label for="lab">Lab/Facility </label>
		     </div>
		</div>
	    </div> -->
	    <div class="row" style="<?php echo (trim($countryId) == '')?'':'display:none;'; ?>">
		<div class="col s4">
		     <div class="input-field col m12 s12">
			<select class="material-select" id="country" name="country" title="Please select country">
			    <option value="">All Countries</option>
			    <?php
			    foreach($countries as $country){
				?>
				<option value="<?php echo base64_encode($country['country_id']);?>"><?php echo ucwords($country['country_name']);?></option>
				<?php
			    }
			    ?>
			</select>
			<label for="country">Country </label>
		     </div>
		</div>
	    </div>
	    <div class="col l12 m12 s12" style="text-align:right;">
		<!-- <a href="javascript:void(0);" onclick="clearSearchFields();" class="waves-effect waves-light btn-small btn red-text custom-btn custom-btn-red"><i class="zmdi zmdi-refresh"></i> Reset Filters</a>&nbsp;&nbsp;&nbsp;&nbsp; -->
		<!-- <a href="javascript:void(0);" onclick="searchDataExtractionData();" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a>&nbsp;&nbsp;&nbsp;&nbsp; -->
		<a href="javascript:void(0);" onclick="extractDataCollectionData();" class="waves-effect waves-light btn-small btn green-text custom-btn custom-btn-green"><i class="zmdi zmdi-collection-text"></i> Export Excel</a>
	    </div>
	</form>
    </div>
    <div class="row content-container">
        <div class="col l12 m12 s12">
            <div class="card card-default table-height">
                <div class="card-header dataTable-header"><i class="zmdi zmdi-filter-list"></i> Lab Data Download List
		  <!-- <span style="float:right;"><a href="javascript:void(0)" onclick="$('#showhide').fadeToggle();return false;" style="color:#fff;"><i class="zmdi zmdi-plus-circle-o-duplicate"></i> Manage Columns</a></span> -->
		</div>
                <div class="card-content clearfix">
                    <table id="dataExtractionDataTable" class="responsive-table display dataTable">
                        <thead>
                            <tr>
                                <th>Patient Barcode ID</th>
                                <!-- <th>Specimen Collected Date</th>
				<th>ANC Site</th>
				<th>ANC Site Code</th>
				<th>ANC Patient ID</th>
                                <th>Age</th>
				<th>Gestation Age (Weeks)</th>
                                <th>Specimen Pick Up Date at ANC</th>
	                        <th>Lab/Facility</th>
	                        <th>Lab/Facility Code</th>
                                <th>Lab Specimen ID</th>
				<th>Rejection Code At Central Lab</th>
				<th>Receipt Date at Lab</th> -->
				<th>Lab Tech. Name/ID</th>
				<th>Date of Test Completion</th>
				<!-- <th>Result Dispatched Date to Clinic</th>
				<th>LAg Avidity</th>
                                <th>Lab LAg Recency<br>(Based on LAg ODn)</th>
				<th>HIV RNA (cp/ml)</th>
                                <th>HIV RNA > 1000</th>
				<th>Lab LAg Recency<br>(Based on algorithm)</th> -->
                                <th>Asante Positive Verification Line (Visual)</th>
                                <th>Asante Long Term Line (Visual)</th>
                                <th>Comments</th>
				<th>Added Date</th>
				<th>Added by</th>
				<th>Last Updated Date</th>
				<th>Last Updated by</th>
				<th>Status</th>
				<!-- <th>Date Result Returned at Clinic</th>
				<th>Date Returned to Participant</th> -->
				<?php
                                if(trim($countryId)== ''){
                                ?>
                                 <th>Country</th>
				<?php } ?>
                            </tr>
                        </thead>
			<tfoot>
                            <tr>
                                <th>Patient Barcode ID</th>
                                <!-- <th>Specimen Collected Date</th>
				<th>ANC Site</th>
				<th>ANC Site Code</th>
				<th>ANC Patient ID</th>
                                <th>Age</th>
				<th>Gestation Age (Weeks)</th>
                                <th>Specimen Pick Up Date at ANC</th>
	                        <th>Lab/Facility</th>
	                        <th>Lab/Facility Code</th>
                                <th>Lab Specimen ID</th>
				<th>Rejection Code At Central Lab</th>
				<th>Receipt Date at Lab</th> -->
				<th>Lab Tech. Name/ID</th>
				<th>Date of Test Completion</th>
				<!-- <th>Result Dispatched Date to Clinic</th>
				<th>LAg Avidity</th>
                                <th>Lab LAg Recency<br>(Based on LAg ODn)</th>
				<th>HIV RNA (cp/ml)</th>
                                <th>HIV RNA > 1000</th>
				<th>Lab LAg Recency<br>(Based on algorithm)</th> -->
                                <th>Asante Positive Verification Line (Visual)</th>
                                <th>Asante Long Term Line (Visual)</th>
                                <th>Comments</th>
				<th>Added Date</th>
				<th>Added by</th>
				<th>Last Updated Date</th>
				<th>Last Updated by</th>
				<th>Status</th>
				<!-- <th>Date Result Returned at Clinic</th>
				<th>Date Returned to Participant</th> -->
				<?php
                                if(trim($countryId)== ''){
                                ?>
                                 <th>Country</th>
				<?php } ?>
                            </tr>
                        </tfoot>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/daterangepicker/daterangepicker.js' ?>"></script>
<script>
    $(document).ready(function() {
	selectDate();
	oTable = $('#dataExtractionDataTable').dataTable({
	    "autoWidth": false,
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
	    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
	    "iDisplayLength": 25,
            "aoColumns": [
		{"sClass":"center dataTable_noWrap"},
		// {"sClass":"center dataTable_noWrap"},
		// {"sClass":"dataTable_noWrap"},
		// {"sClass":"center dataTable_noWrap"},
		// {"sClass":"center dataTable_noWrap"},
		// {"sClass":"dataTable_noWrap"},
		// {"sClass":"center dataTable_noWrap"},
		// {"sClass":"center dataTable_noWrap"},
		// {"sClass":"dataTable_noWrap"},
		// {"sClass":"center dataTable_noWrap"},
		// //{"sClass":"center dataTable_noWrap"},
		// {"sClass":"center dataTable_noWrap"},
		// {"sClass":"center dataTable_noWrap"},
		// {"sClass":"dataTable_noWrap"},
		// {"sClass":"center dataTable_noWrap"},
		// {"sClass":"center dataTable_noWrap"},
		// {"sClass":"center dataTable_noWrap"},
		// {"sClass":"center dataTable_noWrap"},
		// {"sClass":"center dataTable_noWrap"},
		// {"sClass":"center dataTable_noWrap"},
		 {"sClass":"center dataTable_noWrap"},
		{"sClass":"center dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"center dataTable_noWrap"},
		{"sClass":"center dataTable_noWrap"},
		{"sClass":"center dataTable_noWrap"},
		{"sClass":"center dataTable_noWrap"},
		{"sClass":"center dataTable_noWrap"},
		{"sClass":"center dataTable_noWrap"},
		{"sClass":"center dataTable_noWrap"},
		<?php
		if(trim($countryId)== ''){
		?>
		  {"sClass":"dataTable_noWrap"}
		<?php } ?>
            ],
	    "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
		//if($.trim(aData[10])!= ''){
		  //  $(nRow).addClass("blueTxt");
		//}else{
		    //if(aData[26] == 'Incomplete'){ $("td:eq(1)", nRow).addClass("remove_sorting_1_style"); $(nRow).addClass("yellowTxt"); }
		    //if(aData[19] =='Absent' || (aData[18] == 'Long Term' && aData[20] == 'Absent') || (aData[18] == 'Recent' && aData[20] == 'Present')){ $(nRow).addClass("redTxt"); }
		//}
	    },
            "aaSorting": [[0, "desc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('data-extraction-admin',array('action' => 'index')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
		aoData.push({"name": "countryId", "value": '<?php echo $countryId; ?>' });
		aoData.push({"name": "specimenCollectedDate", "value": $("#specimenCollectedDate").val() });
		aoData.push({"name": "anc", "value": $("#anc").val() });
		aoData.push({"name": "lab", "value": $("#lab").val() });
		aoData.push({"name": "country", "value": $("#country").val()});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
       
       $("#showhide").hover(function(){}, function(){$(this).fadeOut('slow')});
        for(colNo=0;colNo <= $("#countColumn").val();colNo++){
            $("#iCol"+colNo).attr("checked",oTable.fnSettings().aoColumns[parseInt(colNo)].bVisible);
        }
       
       $('.dataTables_filter').empty(); // clears the content generated
       $('.dataTables_filter').append(
                "<div class='input-field col s6 search-div right' style='width: 250px'>" +
                "    <i class='material-icons search-icon'>search</i> "+
                "    <input id='search-items' type='text' class='validate' />" +
                "    <label for='icon_prefix' class='search-label'>Search</label>   "+
                "</div>");
       $(document).on('keyup', "input[type='text']", function(){
	    oTable.fnFilter($(this).val());
       });
    });
    
    function fnShowHide(iCol){
        var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
        oTable.fnSetColumnVis( iCol, bVis ? false : true );
    }
    
    function selectDate(){
	$(".ranges").show();
        $(".left").css({"float":"none !important"});
        $('#specimenCollectedDate').daterangepicker({
            format: 'DD-MMM-YYYY',
	    separator: ' to ',
            maxDate: moment(),
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                'Last 7 Days': [moment().subtract('days', 6), moment()],
                'Last 30 Days': [moment().subtract('days', 29), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
            },
        },function(start, end) {
            startDate = start.format('YYYY-MM-DD');
            endDate = end.format('YYYY-MM-DD');
            $('label[for="specimenCollectedDate"]').css("transform", "translateY(-140%)");
        });
        $('.applyBtn').addClass('waves-effect waves-light btn-small white-text blue margin-bottom-10');
        $('.cancelBtn').addClass('waves-effect waves-light btn-small btn blue-text custom-btn custom-btn-blue margin-bottom-10');
    }
    
    function searchDataExtractionData(){
       oTable.fnDraw(false);
    }
    
    function clearSearchFields(){
        $('#searchFilterForm')[0].reset();
        searchDataExtractionData();
    }
    
    function extractDataCollectionData(){
	$.blockUI();
	$.post("<?php echo $this->url('export-data-collection-admin'); ?>", { countryId:'<?php echo $countryId; ?>'},
	function(data){
	    if(data == "" || data == null || data == undefined){
		alert('Error-Oops, Unable to generate excel');
		$.unblockUI();
	    }else if(data == "na"){
		alert('Export data not available');
		$.unblockUI();
	    }else{
		$.unblockUI();
		window.open("/temporary/"+data, "_blank");
	    }
	});
    }
</script>