<?php
use Zend\Session\Container;
$alertContainer = new Container('alert');
$common = new \Application\Service\CommonService();
$alertContainer->pageHeight = 46;
if(count($logbookResult) >0){
    //set ancs
    $selectedANC = '';
    $displayANC = '';
    $allANCs = array();
    $displayAllANCs = '';
    if(trim($params['anc'])!= ''){
	$selectedANC = base64_decode($params['anc']);
    }
    if(isset($ancSites) && count($ancSites) > 0){
	foreach($ancSites as $anc){
	    $allANCs[] = ' '.ucwords($anc['anc_site_name']);
	    if(trim($selectedANC)!= '' && $selectedANC == $anc['anc_site_id']){
		$displayANC = ucwords($anc['anc_site_name']);
		break;
	    }
	}
       $displayAllANCs = implode(',',$allANCs);
    }
    $ancs = (trim($displayANC)!= '')?$displayANC:$displayAllANCs;
    //set labs
    $selectedLab = '';
    $displayLab = '';
    $allLabs = array();
    $displayAllLabs = '';
    if(trim($params['lab'])!= ''){
	$selectedLab = base64_decode($params['lab']);
    }
    if(isset($facilities) && count($facilities) > 0){
	foreach($facilities as $facility){
	    $allLabs[] = ' '.ucwords($facility['facility_name']);
	    if(trim($selectedLab)!= '' && $selectedLab == $facility['facility_id']){
		$displayLab = ucwords($facility['facility_name']);
		break;
	    }
	}
       $displayAllLabs = implode(',',$allLabs);
    }
    $labs = (trim($displayLab)!= '')?$displayLab:$displayAllLabs;
    //set receipt date at lab
    $receiptDateatLab = '';
    if(trim($params['date'])!= ''){
	$receiptDateatLab = $params['date'];
    }
    //set result reported
    $resultReported = 'Completed Tests, Pending Tests';
    if(trim($params['status']) == 'completed'){
	$resultReported = 'Completed Tests';
    }else if(trim($params['status']) == 'pending'){
	$resultReported = 'Pending Tests';
    }
    $filterContent = '';
    $filterContent .='<table>';
    $filterContent .='<tr><td colspan="4" style="line-height:30px;"></td></tr>';
    $filterContent .='<tr><td style="width:15%;font-size:14px;text-align:left;">ANC Site</td><td style="width:35%;font-size:14px;font-weight:normal;text-align:left;">'.$ancs.'</td><td style="width:15%;font-size:14px;text-align:left;">Lab Site/Facility</td><td style="width:35%;font-size:14px;font-weight:normal;text-align:left;">'.$labs.'</td></tr>';
    $filterContent .='<tr><td colspan="4" style="line-height:6px;"></td></tr>';
    $filterContent .='<tr><td style="width:15%;font-size:14px;text-align:left;">Receipt Date at Lab</td><td style="width:35%;font-size:14px;font-weight:normal;text-align:left;">'.$receiptDateatLab.'</td><td style="width:15%;font-size:14px;text-align:left;">Result Reported</td><td style="width:35%;font-size:14px;font-weight:normal;text-align:left;">'.$resultReported.'</td></tr>';
    $filterContent .='<tr><td colspan="4" style="line-height:6px;"></td></tr>';
    $filterContent .='</table>';
    
    //header and footer
    class MYPDF extends TCPDF {
        public function setSchemeName($heading,$logo,$filterContent) {
	  $this->heading = $heading;
	  $this->logo = $logo;
	  $this->filterContent = $filterContent;
        }
	
        //Page header
        public function Header() {
	    $alertContainer = new Container('alert');
            // Logo
            $image_file = APPLICATION_PATH . DIRECTORY_SEPARATOR . 'assets'. DIRECTORY_SEPARATOR . 'images'. DIRECTORY_SEPARATOR . $this->logo;
            $this->Image($image_file, 12,3, 20, '', 'PNG', '', 'T', false, 300, '', false, false, 0, false, false, false);
             //Set font
            $this->SetFont('helvetica', 'B', 20);
             //Title
            $this->writeHTMLCell(0,'',36,10,$this->heading,0,1,false,true,'C',true);
	    $this->writeHTMLCell(0,'','','',$this->filterContent,0,1,false,true,'C',true);
	    $alertContainer->pageHeight = $this->GetY();
        }
    
        // Page footer
        public function Footer() {
            // Position at 15 mm from bottom
            $this->SetY(-15);
            // Set font
            $this->SetFont('helvetica', '', 8);
            // Page number
            $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
        }
    }
    // create new PDF document
    $pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    $pdf->setPageOrientation('L');
    $pdf->setSchemeName('Logbook for Recency Test','dreams-small-logo.png',$filterContent);
    // set document information
    $pdf->SetCreator(PDF_CREATOR);
    //$pdf->SetAuthor('Dream');
    $pdf->SetTitle('Logbook for Recency Test');
    //$pdf->SetSubject('TCPDF Tutorial');
    //$pdf->SetKeywords('TCPDF, PDF, example, test, guide');
    
    // set default header data
    $pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);
    
    // set header and footer fonts
    $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
    $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
    
    // set default monospaced font
    $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
    
    // set margins
    //$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_RIGHT);
    //$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
    //$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
    
    // set auto page breaks
    $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
    
    // set image scale factor
    $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
    
    // set some language-dependent strings (optional)
    //if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    //    require_once(dirname(__FILE__).'/lang/eng.php');
    //    $pdf->setLanguageArray($l);
    //}
    
    // ---------------------------------------------------------
    
    // set font
    $pdf->SetFont('helvetica', '', 10);
    
    $pdf->AddPage();
    $pdf->SetMargins(10, $alertContainer->pageHeight, 10, true);
    //$pdf->SetFooterMargin(10);
    $pdf->SetY($alertContainer->pageHeight,true,false);
    //pdf content
    $html = '';
      $html.='<table border="1" style="padding:2px;">';
          $html .='<thead>';
           $html .='<tr>';
	   $html .='<th><strong>Receipt Date at Lab</strong></th>';
           $html .='<th><strong>Patient Barcode ID</strong></th>';
           $html .='<th><strong>Specimen Collected Date</strong></th>';
           $html .='<th><strong>ANC Site Name/Code</strong></th>';
           $html .='<th><strong>ANC Patient ID</strong></th>';
           $html .='<th><strong>Age</strong></th>';
           $html .='<th><strong>Specimen Pick Up Date at ANC</strong></th>';
           $html .='<th><strong>Lab Site Name/Code</strong></th>';
           $html .='<th><strong>Lab Specimen ID</strong></th>';
           $html .='<th><strong>Rejection Code</strong></th>';
           $html .='<th><strong>Date of Test Completion</strong></th>';
           $html .='<th><strong>Result Dispatched Date to Clinic</strong></th>';
           $html .='<th><strong>LAg Avidity</strong></th>';
           $html .='<th><strong>LAg Avidity Result</strong></th>';
           $html .='<th><strong>HIV RNA (cp/ml)</strong></th>';
           //$html .='<th><strong>HIV RNA > 1000</strong></th>';
           $html .='<th><strong>Recent Infection</strong></th>';
           $html .='<th><strong>Rapid Recency Diagnosis Test</strong></th>';
	   $html .='<th><strong>Diagnosis Reader Value</strong></th>';
           $html .='<th><strong>Rapid Recency Result</strong></th>';
	   $html .='<th><strong>Recency Reader Value</strong></th>';
	   $html .='<th><strong>Manager\'s Approval</strong></th>';
           $html .='</tr>';
          $html .='</thead>';
          $html .='<tbody>';
          foreach($logbookResult as $row){
            $specimenCollectedDate = '';
	    $specimenPickUpDateatAnc = '';
	    $receiptDateAtCentralLab = '';
	    $testCompletionDate = '';
	    $resultDispatchedDateToClinic = '';
	    if(isset($row['specimen_collected_date']) && trim($row['specimen_collected_date'])!= '' && $row['specimen_collected_date']!= '0000-00-00'){
	      $specimenCollectedDate = $common->viewDateFormat($row['specimen_collected_date']);
	    }if(isset($row['specimen_picked_up_date_at_anc']) && trim($row['specimen_picked_up_date_at_anc'])!= '' && $row['specimen_picked_up_date_at_anc']!= '0000-00-00'){
	      $specimenPickUpDateatAnc = $common->viewDateFormat($row['specimen_picked_up_date_at_anc']);
	    }if(isset($row['receipt_date_at_central_lab']) && trim($row['receipt_date_at_central_lab'])!= '' && $row['receipt_date_at_central_lab']!= '0000-00-00'){
	      $receiptDateAtCentralLab = $common->viewDateFormat($row['receipt_date_at_central_lab']);
	    }if(isset($row['date_of_test_completion']) && trim($row['date_of_test_completion'])!= '' && $row['date_of_test_completion']!= '0000-00-00'){
	      $testCompletionDate = $common->viewDateFormat($row['date_of_test_completion']);
	    }if(isset($row['result_dispatched_date_to_clinic']) && trim($row['result_dispatched_date_to_clinic'])!= '' && $row['result_dispatched_date_to_clinic']!= '0000-00-00'){
	      $resultDispatchedDateToClinic = $common->viewDateFormat($row['result_dispatched_date_to_clinic']);
	    }
	    $lAgAvidityResult = ($row['lag_avidity_result']!= null && trim($row['lag_avidity_result'])!= '')?ucwords($row['lag_avidity_result']):'';
	    //$hIVRNAResult = '';
	    //if(trim($row['hiv_rna_gt_1000'])!= '' && $row['hiv_rna_gt_1000'] =='yes'){
	    //  $hIVRNAResult = 'High Viral Load';
	    //}else if(trim($row['hiv_rna_gt_1000'])!= '' && $row['hiv_rna_gt_1000'] =='no'){
	    //  $hIVRNAResult = 'Low Viral Load';
	    //}
	    
	    $rapidRecencyAssay = '';
	    $diagnosisReaderValue = '';
	    $rapidRecencyAssayDuration = '';
	    $recencyReaderValue = '';
	    if(trim($row['asante_rapid_recency_assy'])!= ''){
		$asanteRapidRecencyAssy = json_decode($row['asante_rapid_recency_assy'],true);
		if(isset($asanteRapidRecencyAssy['rrdt'])){
		    $rapidRecencyAssay = (isset($asanteRapidRecencyAssy['rrdt']['assay']))?$asanteRapidRecencyAssy['rrdt']['assay']:'';
		    $diagnosisReaderValue = (isset($asanteRapidRecencyAssy['rrdt']['reader']))?$asanteRapidRecencyAssy['rrdt']['reader']:'';
		}if(isset($asanteRapidRecencyAssy['rrr'])){
		    $rapidRecencyAssayDuration = (isset($asanteRapidRecencyAssy['rrr']['assay']))?ucwords($asanteRapidRecencyAssy['rrr']['assay']):'';
		    $recencyReaderValue = (isset($asanteRapidRecencyAssy['rrr']['reader']))?$asanteRapidRecencyAssy['rrr']['reader']:'';
		}
	    }
	    $redTxt='';
	    if($rapidRecencyAssay == 'HIV Negative' || ($row['final_lag_avidity_odn'] > 2 && (($rapidRecencyAssay == 'HIV Positive' && $rapidRecencyAssayDuration == 'Recent') || $rapidRecencyAssayDuration == 'Recent'))){
		$redTxt = 'color:#F44336;';
	    }
            $html .='<tr style="'.$redTxt.'">';
	      $html .='<td>'.$receiptDateAtCentralLab.'</td>';
              $html .='<td>'.$row['patient_barcode_id'].'</td>';
              $html .='<td>'.$specimenCollectedDate.'</td>';
              $html .='<td>'.ucwords($row['anc_site_name'])." - ".$row['anc_site_code'].'</td>';
              $html .='<td>'.$row['anc_patient_id'].'</td>';
              $html .='<td>'.$row['age'].'</td>';
              $html .='<td>'.$specimenPickUpDateatAnc.'</td>';
              $html .='<td>'.ucwords($row['facility_name'])." - ".$row['facility_code'].'</td>';
              $html .='<td>'.$row['lab_specimen_id'].'</td>';
              $html .='<td>'.ucwords($row['rejection_code']).'</td>';
              $html .='<td>'.$testCompletionDate.'</td>';
              $html .='<td>'.$resultDispatchedDateToClinic.'</td>';
              $html .='<td>'.$row['final_lag_avidity_odn'].'</td>';
              $html .='<td>'.$lAgAvidityResult.'</td>';
              $html .='<td>'.$row['hiv_rna'].'</td>';
              //$html .='<td>'.$hIVRNAResult.'</td>';
              $html .='<td>'.ucfirst($row['recent_infection']).'</td>';
              $html .='<td>'.$rapidRecencyAssay.'</td>';
	      $html .='<td>'.$diagnosisReaderValue.'</td>';
              $html .='<td>'.$rapidRecencyAssayDuration.'</td>';
	      $html .='<td>'.$recencyReaderValue.'</td>';
	      $html .='<td></td>';
            $html .='</tr>';
          }
          $html .='</tbody>';
      $html.='</table>';
    $pdf->writeHTML(utf8_encode($html),true,0,true,0);
    $filename = 'LOGBOOK--'.date('d-M-Y-H-i-s').'.pdf';
    $pdf->Output(TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR . $filename,"F");
    echo $filename;
}else{
    echo null;
}
?>