<?php
use Zend\Session\Container;
$common = new \Application\Service\CommonService();
if(count($logbookResult) >0){
    //header and footer
    class MYPDF extends TCPDF {
    
        //Page header
        public function Header() {
            // Logo
            //$image_file = K_PATH_IMAGES.'logo_example.jpg';
            //$this->Image($image_file, 10, 10, 15, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
            // Set font
            //$this->SetFont('helvetica', 'B', 20);
            // Title
            //$this->Cell(0, 15, 'VL Request Form Report', 0, false, 'C', 0, '', 0, false, 'M', 'M');
        }
    
        // Page footer
        public function Footer() {
            // Position at 15 mm from bottom
            $this->SetY(-15);
            // Set font
            $this->SetFont('helvetica', '', 8);
            // Page number
            $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
        }
    }
    // create new PDF document
    $pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    $pdf->setPageOrientation('L');
    // set document information
    $pdf->SetCreator(PDF_CREATOR);
    //$pdf->SetAuthor('Saravanan');
    $pdf->SetTitle('Lab Logbook');
    //$pdf->SetSubject('TCPDF Tutorial');
    //$pdf->SetKeywords('TCPDF, PDF, example, test, guide');
    
    // set default header data
    $pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);
    
    // set header and footer fonts
    $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
    $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
    
    // set default monospaced font
    $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
    
    // set margins
    //$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_RIGHT);
    //$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
    //$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
    
    // set auto page breaks
    $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
    
    // set image scale factor
    $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
    
    // set some language-dependent strings (optional)
    //if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    //    require_once(dirname(__FILE__).'/lang/eng.php');
    //    $pdf->setLanguageArray($l);
    //}
    
    // ---------------------------------------------------------
    
    // set font
    $pdf->SetFont('helvetica', '', 10);
    
    $pdf->AddPage();
    
    
    $html = '';
      $html.='<table border="1" style="padding:2px;">';
          $html .='<thead>';
           $html .='<tr>';
           $html .='<th><strong>Surveillance ID</strong></th>';
           $html .='<th><strong>Specimen Collected Date</strong></th>';
           $html .='<th><strong>ANC Site Code/Name</strong></th>';
           $html .='<th><strong>ANC Patient ID</strong></th>';
           $html .='<th><strong>Age</strong></th>';
           $html .='<th><strong>Specimen Pick Up Date at ANC</strong></th>';
           $html .='<th><strong>Lab Site Code/Name</strong></th>';
           $html .='<th><strong>Lab Specimen ID</strong></th>';
           $html .='<th><strong>Rejection Code</strong></th>';
           $html .='<th><strong>Receipt Date at Central Lab</strong></th>';
           $html .='<th><strong>Date of Test Completion</strong></th>';
           $html .='<th><strong>Result Dispatched Date to Clinic</strong></th>';
           $html .='<th><strong>Final LAg Avidity</strong></th>';
           $html .='<th><strong>LAg Avidity Result</strong></th>';
           $html .='<th><strong>HIV RNA</strong></th>';
           $html .='<th><strong>HIV RNA >= 1,000</strong></th>';
           $html .='<th><strong>Recent Infection</strong></th>';
           $html .='<th><strong>Asante Rapid Recency Assay</strong></th>';
           $html .='</tr>';
          $html .='</thead>';
          $html .='<tbody>';
          foreach($logbookResult as $row){
            $specimenCollectedDate = '';
	    $specimenPickUpDateatAnc = '';
	    $receiptDateAtCentralLab = '';
	    $testCompletionDate = '';
	    $resultDispatchedDateToClinic = '';
	    if(isset($row['specimen_collected_date']) && trim($row['specimen_collected_date'])!= '' && $row['specimen_collected_date']!= '0000-00-00'){
		$specimenCollectedDate = $common->viewDateFormat($row['specimen_collected_date']);
	    }if(isset($row['specimen_picked_up_date_at_anc']) && trim($row['specimen_picked_up_date_at_anc'])!= '' && $row['specimen_picked_up_date_at_anc']!= '0000-00-00'){
		$specimenPickUpDateatAnc = $common->viewDateFormat($row['specimen_picked_up_date_at_anc']);
	    }if(isset($row['receipt_date_at_central_lab']) && trim($row['receipt_date_at_central_lab'])!= '' && $row['receipt_date_at_central_lab']!= '0000-00-00'){
		$receiptDateAtCentralLab = $common->viewDateFormat($row['receipt_date_at_central_lab']);
	    }if(isset($row['date_of_test_completion']) && trim($row['date_of_test_completion'])!= '' && $row['date_of_test_completion']!= '0000-00-00'){
		$testCompletionDate = $common->viewDateFormat($row['date_of_test_completion']);
	    }if(isset($row['result_dispatched_date_to_clinic']) && trim($row['result_dispatched_date_to_clinic'])!= '' && $row['result_dispatched_date_to_clinic']!= '0000-00-00'){
		$resultDispatchedDateToClinic = $common->viewDateFormat($row['result_dispatched_date_to_clinic']);
	    }
            $lAgAvidityResult = '';
	    if(trim($row['lag_avidity_result'])!= '' && $row['lag_avidity_result'] =='lt'){
		$lAgAvidityResult = 'LONG TERM';
	    }else if(trim($row['lag_avidity_result'])!= '' && $row['lag_avidity_result'] =='r'){
		$lAgAvidityResult = 'RECENT';
	    }
	    $hIVRNAResult = '';
	    if(trim($row['hiv_rna_gt_1000'])!= '' && $row['hiv_rna_gt_1000'] =='yes'){
		$hIVRNAResult = 'HIGH VIRAL LOAD';
	    }else if(trim($row['hiv_rna_gt_1000'])!= '' && $row['hiv_rna_gt_1000'] =='no'){
		$hIVRNAResult = 'LOW VIRAL LOAD';
	    }
	    $asanteRapidRecencyAssay = '';
	    if(trim($row['asante_rapid_recency_assy'])!= '' && $row['asante_rapid_recency_assy'] =='p/lt'){
		$asanteRapidRecencyAssay = 'POSITIVE/LONG TERM';
	    }else if(trim($row['asante_rapid_recency_assy'])!= '' && $row['asante_rapid_recency_assy'] =='n/lt'){
		$asanteRapidRecencyAssay = 'NEGATIVE/LONG TERM';
	    }else if(trim($row['asante_rapid_recency_assy'])!= '' && $row['asante_rapid_recency_assy'] =='n/r'){
		$asanteRapidRecencyAssay = 'NEGATIVE/RECENT';
	    }else if(trim($row['asante_rapid_recency_assy'])!= '' && $row['asante_rapid_recency_assy'] =='p/r'){
		$asanteRapidRecencyAssay = 'POSITIVE/RECENT';
	    }
            $html .='<tr>';
              $html .='<td>'.$row['surveillance_id'].'</td>';
              $html .='<td>'.$specimenCollectedDate.'</td>';
              $html .='<td>'.ucwords($row['anc_site_name'])." - ".$row['anc_site_code'].'</td>';
              $html .='<td>'.$row['anc_patient_id'].'</td>';
              $html .='<td>'.$row['age'].'</td>';
              $html .='<td>'.$specimenPickUpDateatAnc.'</td>';
              $html .='<td>'.ucwords($row['facility_name'])." - ".$row['facility_code'].'</td>';
              $html .='<td>'.$row['lab_specimen_id'].'</td>';
              $html .='<td>'.ucwords($row['rejection_code']).'</td>';
              $html .='<td>'.$receiptDateAtCentralLab.'</td>';
              $html .='<td>'.$testCompletionDate.'</td>';
              $html .='<td>'.$resultDispatchedDateToClinic.'</td>';
              $html .='<td>'.$row['final_lag_avidity_odn'].'</td>';
              $html .='<td>'.$lAgAvidityResult.'</td>';
              $html .='<td>'.$row['hiv_rna'].'</td>';
              $html .='<td>'.$hIVRNAResult.'</td>';
              $html .='<td>'.ucwords($row['recent_infection']).'</td>';
              $html .='<td>'.$asanteRapidRecencyAssay.'</td>';
            $html .='</tr>';
          }
          $html .='</tbody>';
      $html.='</table>';
    $pdf->writeHTML(utf8_encode($html));
    $pdf->lastPage();
    $filename = 'Lab-Logbook-'.date('d-M-Y-H-i-s').'.pdf';
    $pdf->Output(TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR . $filename,"F");
    echo $filename;
}else{
    echo null;
}
?>