<?php
use Zend\Session\Container;
$loginContainer = new Container('user');
if(!isset($countryId) || trim($countryId)== ''){
    $countryId = '';
    $display="";
    $style="width:40%;text-align:left;";
}else{
    $display="display:none;";
    $style = "text-align:right;padding-right:6%;";
}
?>
<style>
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        background-color: #eaeaea;
        border-bottom: 1px solid #ccc;
        padding: 10px 20px;
    }
    pre {
        max-height: 596px;
    }
    table.dataTable tbody td {
        padding: 8px 18px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        /*left: -184px*/

    }
    #dataCollectionDataTable_wrapper{
	overflow-x:scroll;
    }
    .select-wrapper{
	width:100%;
    }
    .dataTables_wrapper{
	overflow-x: scroll;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Data Extractions</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Data Extractions</a>
       </div>
    </div>
    <?php
    if($loginContainer->roleCode!= 'LDEO'){
    ?>
	<div class="row">
	    <div class="col l12 m12 s12">
		<table style="width:100%;">
		    <tr>
			<td style="width:20%;text-align:right;<?php echo $display;?>"><h6><strong>Country</strong></h6></td>
			<td style="text-align:left;<?php echo $display;?>">
			    <select class="material-select" id="country" name="country" title="Please select country" style="width:40% !important;">
				<option value=""> -- Select -- </option>
				<?php
				foreach($countries as $country){
				    ?>
				    <option value="<?php echo base64_encode($country['country_id']);?>"><?php echo ucwords($country['country_name']);?></option>
				    <?php
				}
				?>
			    </select>
			</td>
			<td style="<?php echo $style; ?>"><a href="javascript:void(0);" style="<?php echo $display;?>" onclick="searchDataExtractionData();" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0);" onclick="extractDataCollectionData();" class="waves-effect waves-light btn-small btn green-text custom-btn custom-btn-green"><i class="zmdi zmdi-collection-text"></i> Export Excel</a></td>
		    </tr>
		</table>
	    </div>
	</div>
    <?php } ?>
    <div id="showhide" class="row" style="display: none;position:absolute;z-index: 9999 !important;color:#333;font-size:12px;font-weight:bold;padding: 5px 0px 5px 5px;height:250px;background:#e0e0e0;">
	<div class="col m12">
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="0" id="iCol0" data-showhide="surveillance_id" class="showhideCheckBox" /> <label for="iCol0">Surveillance ID</label>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="1" id="iCol1" data-showhide="specimen_collected_date" class="showhideCheckBox"  /> <label for="iCol1">Specimen Collected Date</label>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="2" id="iCol2" data-showhide="anc_site_name" class="showhideCheckBox"  /> <label for="iCol2">ANC site</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="3" id="iCol3" data-showhide="anc_patient_id" class="showhideCheckBox"  /> <label for="iCol3">ANC Patient ID</label>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="4" id="iCol4" data-showhide="age" class="showhideCheckBox" /> <label for="iCol4">Age</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="5" id="iCol5" data-showhide="specimen_picked_up_date_at_anc" class="showhideCheckBox" /> <label for="iCol5">Specimen Pick Up Date at ANC</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="6" id="iCol6" data-showhide="facility_name" class="showhideCheckBox" /> <label for="iCol6">Lab Name</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="7" id="iCol7" data-showhide="lab_specimen_id" class="showhideCheckBox" /> <label for="iCol7">Lab Specimen ID</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="8" id="iCol8" data-showhide="rejection_code" class="showhideCheckBox" /> <label for="iCol8">Rejection Code</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="9" id="iCol9" data-showhide="receipt_date_at_central_lab" class="showhideCheckBox" /> <label for="iCol9">Receipt Date at Central Lab</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="10" id="iCol10" data-showhide="date_of_test_completion" class="showhideCheckBox" /> <label for="iCol10">Date of Test Completion</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="11" id="iCol11" data-showhide="result_dispatched_date_to_clinic" class="showhideCheckBox" /> <label for="iCol11">Result Dispatched Date to Clinic</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="12" id="iCol12" data-showhide="final_lag_avidity_odn" class="showhideCheckBox" /> <label for="iCol12">Final LAg Avidity ODn</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="13" id="iCol13" data-showhide="lag_avidity_result" class="showhideCheckBox" /> <label for="iCol13">LAg Avidity Result</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="14" id="iCol14" data-showhide="hiv_rna" class="showhideCheckBox" /> <label for="iCol14">Hiv RNA</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="15" id="iCol15" data-showhide="hiv_rna_gt_1000" class="showhideCheckBox" /> <label for="iCol15">HIV RNA >= 1,000 <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="16" id="iCol16" data-showhide="recent_infection" class="showhideCheckBox" /> <label for="iCol16">Recent Infection</label> <br>
	    </div>
	    <div class="col m3">
		<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="17" id="iCol17" data-showhide="asante_rapid_recency_assy" class="showhideCheckBox" /> <label for="iCol17">Asante Rapid Recency Assay</label>
		<input type="hidden" id="countColumn" value="17"/>
	    </div>
	</div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <div class="col l12 m12 s12">
            <div class="card card-default table-height">
                <div class="card-header dataTable-header"><i class="zmdi zmdi-filter-list"></i> Data Extraction List
		  <span style="float:right;"><a href="javascript:void(0)" onclick="$('#showhide').fadeToggle();return false;" style="color:#fff;"><i class="zmdi zmdi-plus-circle-o-duplicate"></i> Manage Columns</a></span>
		</div>
                <div class="card-content clearfix">
                    <table id="dataExtractionDataTable" class="responsive-table display dataTable">
                        <thead>
                            <tr>
                                <th>Surveillance ID</th>
                                <th>Specimen Collected Date</th>
				<th>ANC site</th>
				<th>ANC Patient ID</th>
                                <th>Age</th>
                                <th>Specimen Pick Up Date at ANC</th>
	                        <th>Lab Name</th>
                                <th>Lab Specimen ID</th>
				<th>Rejection Code</th>
				<th>Receipt Date at Central Lab</th>
				<th>Date of Test Completion</th>
				<th>Result Dispatched Date to Clinic</th>
				<th>Final LAg Avidity</th>
                                <th>LAg Avidity Result</th>
				<th>HIV RNA</th>
                                <th>HIV RNA >= 1,000</th>
				<th>Recent Infection</th>
                                <th>Asante Rapid Recency Assay</th>
                            </tr>
                        </thead>
			<tfoot>
                            <tr>
                                <th>Surveillance ID</th>
                                <th>Specimen Collected Date</th>
				<th>ANC site</th>
				<th>ANC Patient ID</th>
                                <th>Age</th>
                                <th>Specimen Pick Up Date at ANC</th>
	                        <th>Lab Name</th>
                                <th>Lab Specimen ID</th>
				<th>Rejection Code</th>
				<th>Receipt Date at Central Lab</th>
				<th>Date of Test Completion</th>
				<th>Result Dispatched Date to Clinic</th>
				<th>Final LAg Avidity</th>
                                <th>LAg Avidity Result</th>
				<th>HIV RNA</th>
                                <th>HIV RNA >= 1,000</th>
				<th>Recent Infection</th>
                                <th>Asante Rapid Recency Assay</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
	oTable = $('#dataExtractionDataTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
	    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
	    "iDisplayLength": 25,
            "aoColumns": [
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"}
            ],
            "aaSorting": [[1, "desc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('data-extraction',array('action' => 'index')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                aoData.push({"name": "country", "value": $("#country").val()});
		aoData.push({"name": "countryId", "value": '<?php echo $countryId; ?>' });
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
       
       $("#showhide").hover(function(){}, function(){$(this).fadeOut('slow')});
        for(colNo=0;colNo <=$("#countColumn").val();colNo++){
            $("#iCol"+colNo).attr("checked",oTable.fnSettings().aoColumns[parseInt(colNo)].bVisible);
            if(oTable.fnSettings().aoColumns[colNo].bVisible){
                $("#iCol"+colNo+"-sort").show();    
            }else{
                $("#iCol"+colNo+"-sort").hide();    
            }
        }
       
       $('.dataTables_filter').empty(); // clears the content generated
       $('.dataTables_filter').append(
                "<div class='input-field col s6 search-div right' style='width: 250px'>" +
                "    <i class='material-icons search-icon'>search</i> "+
                "    <input id='search-items' type='text' class='validate' />" +
                "    <label for='icon_prefix' class='search-label'>Search</label>   "+
                "</div>");
       $(document).on('keyup', "input[type='text']", function(){
                    var oTable = $('.dataTable').dataTable();
                    oTable.fnFilter($(this).val());
                });
    });
    
    function fnShowHide(iCol){
        var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
        oTable.fnSetColumnVis( iCol, bVis ? false : true );
    }
	
    function searchDataExtractionData(){
       oTable.fnDraw(false);
    }
    
    function extractDataCollectionData(){
	$.blockUI();
	$.post("<?php echo $this->url('export-data-extraction'); ?>", {},
	function(data){
	    if(data == "" || data == null || data == undefined){
		alert('OOPS..Unable to generate excel.');
		$.unblockUI();
	    }else{
		$.unblockUI();
		document.location.href = '/temporary/'+data;
	    }
	});
    }
</script>