<?php
use Application\Service\CommonService;
$common = new CommonService();
if(trim($countryId)!= ''){
    $link = "/clinic/data-collection/".base64_encode($countryId);
}else{
    $link = "/clinic/data-collection";
}
$dateofSupportVisit = '';
if(isset($row->date_of_support_visit) && trim($row->date_of_support_visit)!= '' && $row->date_of_support_visit!= '0000-00-00'){
    $dateofSupportVisit = $common->viewDateFormat($row->date_of_support_visit);
}
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/css/jquery-ui.css' ?>"/>
<style>
    .ui-datepicker-calendar {
       display: none;
    }
    .ui-datepicker-month,.ui-datepicker-year{
       display:block;
       display:inline-block;
    }
    .ui-datepicker-title select{
	padding:0;
	height:1.5rem;
    }
    #ancFormTable thead tr th{
        text-align:center;
    }
    .rowOne{
        padding-top:20px;
	padding-bottom:0px;
    }
    @media only screen and (max-width: 1024px){
	.rowOne{
	    padding-top:0px !important;
	}
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Edit ANC Monthly Reporting</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="<?php echo $link; ?>" class="breadcrumb">ANC Monthly Reporting</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Edit ANC Monthly Reporting</a>
       </div>
    </div>
    <div class="row dashboard-wrapper content-container" style="margin-bottom:14px;">
        <form id="editClinicDataReportingForm" name="editClinicDataReportingForm" method="post" action="<?php echo $this->url('clinic-data-collection-edit'); ?>">
            <div class="col l12 m12 s12" style="padding:0;">
                <div class="card card-default table-height">
                    <div class="card-content clearfix">
			<div class="col l12 m12 s12" style="margin-bottom:1vh;padding:0;pointer-events:<?php echo ($row->status == 2)?'none':'auto'; ?>;">
			    <div class="col l6 m6 s6" style="text-align:center;"><strong>Anc site name/code *</strong> <select class="material-select isRequired" id="anc" name="anc" title="Please select anc site" onchange="checkDublicateDataReporting();"><option value=""> -- Select -- </option><?php foreach($ancSites as $anc) { ?><option value="<?php echo base64_encode($anc['anc_site_id']); ?>" <?php echo($row->anc == $anc['anc_site_id'])?'selected="selected"':''; ?>><?php echo ucwords($anc['anc_site_name']).'-'.$anc['anc_site_code']; ?></option><?php } ?></select></div>
			    <div class="col l3 m3 s3" style="text-align:center;"><strong>Month/Year *</strong> <input type="text" class="isRequired" id="reportingMonthYear" name="reportingMonthYear" placeholder="Select month/year" title="Please select month and year" value="<?php echo ucfirst($row->reporting_month_year); ?>" readonly/></div>
			    <div class="col l3 m3 s3" style="text-align:center;"><strong>Date of Support Visit </strong> <input type="text" id="dateofSupportVisit" name="dateofSupportVisit" placeholder="Select support visit date" title="Please select support visit date" value="<?php echo $dateofSupportVisit; ?>" readonly/></div>
			</div>
		        <div class="col l12 m12 s12" style="padding:0;">
			    <table id="ancFormTable" class="responsive-table display">
				<thead>
				    <tr>
					<th>Characteristics</th>
					<th>Age < 15</th>
					<th>Age 15-19</th>
					<th>Age 20-24</th>
					<th>Age Unknown</th>
					<th>Total</th>
				    </tr>
				</thead>
				<tbody>
				    <?php
				    //set characteristics array data from josn data
				    if(isset($row->characteristics_data) && $row->characteristics_data!= null && trim($row->characteristics_data)!= ''){
				      $fieldArray = array();
				      $fields = json_decode($row->characteristics_data,true);
				      foreach($fields as $fieldName=>$fieldValue){
					foreach($fieldValue[0] as $characteristicsName=>$characteristicsValue){
					    $fieldArray[$fieldName][$characteristicsName] = $characteristicsValue;
					}
				      }
				    }
				    $r=1;
				    foreach($ancFormFields as $key=>$value){
					$fieldName = $key;
					$tempLabel = ucfirst(str_replace("_"," ",$key));
					$commonFieldReadOnly = ($row->status == 2 && $fieldName!= 'no_of_recency_result' && $fieldName!= 'no_of_clients_who_received_recency_result')?'readonly':'';
					$mandatoryicon = ($fieldName!= 'no_of_recency_result' && $fieldName!= 'no_of_clients_who_received_recency_result')?' *':'';
					$formLabel = str_replace("No.","No",$tempLabel);
					if($fieldName == 'no_of_clients_ATTENDING_ANC_FIRST_VISIT'){
					    $formLabel = 'No. of clients <span style="font-weight:600;text-decoration:underline;">ATTENDING ANC FIRST VISIT</span>';
					}else if($fieldName == 'no_of_clients_PREVIOUSLY_KNOWN_HIV_POSITIVE_at_ANC_first_visit'){
					    $formLabel = 'No. of clients <span style="font-weight:600;text-decoration:underline;">PREVIOUSLY KNOWN HIV POSITIVE</span> at ANC first visit';
					}else if($fieldName == 'no_of_clients_PREVIOUSLY_KNOWN_HIV_NEGATIVE_at_ANC_first_visit'){
					    $formLabel = 'No. of clients <span style="font-weight:600;text-decoration:underline;">PREVIOUSLY KNOWN HIV NEGATIVE</span> at ANC first visit';
					}else if($fieldName == 'no_of_clients_with_UNKNOWN_HIV_STATUS_at_ANC_first_visit'){
					    $formLabel = 'No. of clients with <span style="font-weight:600;text-decoration:underline;">UNKNOWN HIV STATUS("ND")</span> at ANC first visit';
					}else if($fieldName == 'no_of_clients_TESTED_FOR_HIV_with_rapid_diagnostic_test_at_ANC_first_visit'){
					    $formLabel = 'No. of clients <span style="font-weight:600;text-decoration:underline;">TESTED FOR HIV</span> with rapid diagnostic test(RDT) at ANC first visit';
					}else if($fieldName == 'no_of_clients_TESTED_NEWLY_POSITIVE_FOR_HIV_with_RDT_at_ANC_first_visit'){
					    $formLabel = 'No. of clients <span style="font-weight:600;text-decoration:underline;">TESTED NEWLY POSITIVE FOR HIV</span> with RDT at ANC first visit';
					}else if($fieldName == 'no_of_clients_TESTED_NEWLY_NEGATIVE_FOR_HIV_with_RDT_at_ANC_first_visit'){
					    $formLabel = 'No. of clients <span style="font-weight:600;text-decoration:underline;">TESTED NEWLY NEGATIVE FOR HIV</span> with RDT at ANC first visit';
					}else if($fieldName == 'no_of_clients_TESTED_INDETERMINATE_FOR_HIV_with_RDT_at_ANC_first_visit'){
					    $formLabel = 'No. of clients <span style="font-weight:600;text-decoration:underline;">TESTED INDETERMINATE FOR HIV</span> with RDT at ANC first visit';
					}else if($fieldName == 'no_of_eligible_clients_ENROLLED_IN_RECENT_STUDY'){
					    $formLabel = 'No. of eligible clients <span style="font-weight:600;text-decoration:underline;">ENROLLED IN RECENT STUDY</span>';
					}else if($fieldName == 'no_of_eligible_clients_NOT_ENROLLED_IN_RECENT_STUDY'){
					    $formLabel = 'No. of eligible clients <span style="font-weight:600;text-decoration:underline;">NOT ENROLLED IN RECENT STUDY</span>';
					}else if($fieldName == 'no_of_SPECIMENS_COLLECTED_FOR_RECENCY_TESTING'){
					    $formLabel = 'No. of <span style="font-weight:600;text-decoration:underline;">SPECIMENS COLLECTED FOR RECENCY TESTING</span>';
					}else if($fieldName == 'total_no_of_clients_of_ALL_AGES_ATTENDING_ANC_FIRST_VISIT'){
					    $formLabel = 'Total no. of clients of <span style="font-weight:600;text-decoration:underline;">ALL AGES ATTENDING ANC FIRST VISIT</span>';
					}
					//set readonly fields based on age disaggregation
					$commonFieldsStyle = ($row->status == 2 && $fieldName!= 'no_of_recency_result' && $fieldName!= 'no_of_clients_who_received_recency_result')?'pointer-events:none;':'pointer-events:auto;';
					$styleTotal = 'pointer-events:none;display:none;';
					$commonFieldsIsRequired = ($fieldName!= 'no_of_recency_result' && $fieldName!= 'no_of_clients_who_received_recency_result')?'isRequired':'';
					$isRequiredTotal = '';
					$labelStyle = ($fieldName!= 'no_of_recency_result' && $fieldName!= 'no_of_clients_who_received_recency_result')?'':'color:#056dd2;font-weight:bold;';
					$labelStyleTotal = '';
					$totalFieldReadOnly = '';
					if($value == 'no'){
					    $totalFieldReadOnly = ($row->status == 2)?'readonly':'';
					    $mandatoryicon = ' *';
					    $labelStyle = '';
					    $commonFieldsStyle = 'pointer-events:none;display:none;';
					    $styleTotal = ($row->status == 2)?'pointer-events:none;':'pointer-events:auto;';
					    $labelStyleTotal = 'display:none;';
					    $commonFieldsIsRequired = '';
					    $isRequiredTotal = 'isRequired';
					}
					//set characteristics value
					$ageLt15 = '';
					$age15to19 ='';
					$age20to24 = '';
					$ageUnknown = '';
					$total = '';
					if(array_key_exists($key,$fieldArray)){
					    $ageLt15 = (isset($fieldArray[$key]['age_lt_15']) && $fieldArray[$key]['age_lt_15']!= '')?$fieldArray[$key]['age_lt_15']:'';
					    $age15to19 = (isset($fieldArray[$key]['age_15_to_19']) && $fieldArray[$key]['age_15_to_19']!= '')?$fieldArray[$key]['age_15_to_19']:'';
					    $age20to24 = (isset($fieldArray[$key]['age_20_to_24']) && $fieldArray[$key]['age_20_to_24']!= '')?$fieldArray[$key]['age_20_to_24']:'';
					    $ageUnknown = (isset($fieldArray[$key]['age_unknown']) && $fieldArray[$key]['age_unknown']!= '')?$fieldArray[$key]['age_unknown']:'';
					    $total = (isset($fieldArray[$key]['total']) && $fieldArray[$key]['total']!= '')?$fieldArray[$key]['total']:'';
					}
				    ?>
					<tr>
					  <td class="<?php echo($r > 1)?'':'rowOne'; ?>" style="<?php echo $labelStyle; ?><?php echo($r > 1)?'padding-top:0px;padding-bottom:0px;':''; ?>"><input type="hidden" id="field<?php echo $r; ?>" name="field[]" value="<?php echo $fieldName; ?>" style="height:2rem;"/><?php echo $formLabel.$mandatoryicon; ?></td>
					  <td class="<?php echo($r > 1)?'':'rowOne'; ?>" <?php echo($value == 'no')?'colspan="5"':'' ?> style="<?php echo($r > 1)?'padding-top:0px;padding-bottom:0px;':''; ?>"><input id="<?php echo $fieldName; ?>_age_lt_15" name="<?php echo $fieldName; ?>[age_lt_15]" type="text" class="checkNum <?php echo $fieldName.' '.$commonFieldsIsRequired; ?>" title="Please fill in all the required fields" value="<?php echo $ageLt15; ?>" onkeyup="getTotal('<?php echo $fieldName; ?>');" style="height:2rem;text-align:center;<?php echo $commonFieldsStyle; ?>" <?php echo $commonFieldReadOnly; ?>/><?php if($value!= 'no') { ?></td><?php } ?>
					  <?php if($value!= 'no') { ?><td class="<?php echo($r > 1)?'':'rowOne'; ?>" style="<?php echo($r > 1)?'padding-top:0px;padding-bottom:0px;':''; ?>"><?php } ?><input id="<?php echo $fieldName; ?>_age_15_to_19" name="<?php echo $fieldName; ?>[age_15_to_19]" type="text" class="checkNum <?php echo $fieldName.' '.$commonFieldsIsRequired; ?>" title="Please fill in all the required fields" value="<?php echo $age15to19; ?>" onkeyup="getTotal('<?php echo $fieldName; ?>');" style="height:2rem;text-align:center;<?php echo $commonFieldsStyle; ?>" <?php echo $commonFieldReadOnly; ?>/><?php if($value!= 'no') { ?></td><?php } ?>
					  <?php if($value!= 'no') { ?><td class="<?php echo($r > 1)?'':'rowOne'; ?>" style="<?php echo($r > 1)?'padding-top:0px;padding-bottom:0px;':''; ?>"><?php } ?><input id="<?php echo $fieldName; ?>_age_20_to_24" name="<?php echo $fieldName; ?>[age_20_to_24]" type="text" class="checkNum <?php echo $fieldName.' '.$commonFieldsIsRequired; ?>" title="Please fill in all the required fields" value="<?php echo $age20to24; ?>" onkeyup="getTotal('<?php echo $fieldName; ?>');" style="height:2rem;text-align:center;<?php echo $commonFieldsStyle; ?>" <?php echo $commonFieldReadOnly; ?>/><?php if($value!= 'no') { ?></td><?php } ?>
					  <?php if($value!= 'no') { ?><td class="<?php echo($r > 1)?'':'rowOne'; ?>" style="<?php echo($r > 1)?'padding-top:0px;padding-bottom:0px;':''; ?>"><?php } ?><input id="<?php echo $fieldName; ?>_age_unknown" name="<?php echo $fieldName; ?>[age_unknown]" type="text" class="checkNum <?php echo $fieldName.' '.$commonFieldsIsRequired; ?>" title="Please fill in all the required fields" value="<?php echo $ageUnknown; ?>" onkeyup="getTotal('<?php echo $fieldName; ?>');" style="height:2rem;text-align:center;<?php echo $commonFieldsStyle; ?>" <?php echo $commonFieldReadOnly; ?>/><?php if($value!= 'no') { ?></td><?php } ?>
					  <?php if($value!= 'no') { ?><td class="<?php echo($r > 1)?'':'rowOne'; ?>" style="<?php echo($r > 1)?'padding-top:0px;padding-bottom:0px;':''; ?>"><?php } ?><input id="<?php echo $fieldName; ?>_total" name="<?php echo $fieldName; ?>[total]" type="text" class="checkNum <?php echo $isRequiredTotal; ?>" title="Please fill in all the required fields" value="<?php echo $total; ?>" style="height:2rem;text-align:center;<?php echo $styleTotal; ?>" <?php echo $totalFieldReadOnly; ?>/><div id="lbl_<?php echo $fieldName; ?>_total" style="width:100%;text-align:center;border-bottom: 1px solid #eee;<?php echo $labelStyleTotal; ?>"><?php echo $total; ?></div></td>
					</tr>
				    <?php $r++; } ?>
				    <tr>
					<td style="padding-top:0px;padding-bottom:0px;">Comments</td>
					<td colspan="5" style="padding-top:0px;padding-bottom:0px;">
					    <textarea id="comments" name="comments" class="materialize-textarea" style="height:2rem;pointer-events:<?php echo ($row->status == 2)?'none':'auto'; ?>;"><?php echo $row->comments; ?></textarea>
					</td>
				    </tr>
				</tbody>
			    </table>
		        </div>
                    </div>
                </div>
            </div>
            <div class="col s12" style="margin-top:5px;">
                <input type="hidden" name="clinicDataCollectionId" id="clinicDataCollectionId" value="<?php echo base64_encode($row->cl_data_collection_id); ?>"/>
		<input type="hidden" name="chosenCountry" id="chosenCountry" value="<?php echo base64_encode($countryId); ?>"/>
		<input type="hidden" name="status" id="status" value="<?php echo base64_encode($row->status); ?>"/>
		<input type="hidden" name="redirectUrl" id="redirectUrl" value="<?php echo $link;?>"/>
                <a href="<?php echo $link;?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="updateDataReporting();">UPDATE</a>&nbsp;&nbsp;
            </div>
        </form>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery-ui.js' ?>"></script>
<script>
    $(document).ready(function(){
      <?php if($row->status!= 2) { ?>
        $('#reportingMonthYear').datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'M/yy',
            maxDate: 'Today',
            beforeShow : function(input, inst) {
                tmp = $('#reportingMonthYear').val().split('/');
                var dat = new Date('1 ' + tmp[0] + ' 1969');
                $('#reportingMonthYear').datepicker('option','defaultDate',new Date(tmp[1],parseInt(dat.getMonth()-1)+parseInt(1),1));
                $('#reportingMonthYear').datepicker('setDate', new Date(tmp[1], parseInt(dat.getMonth()-1)+parseInt(1), 1));
            },
            onClose: function(dateText, inst) {
                var month=$("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $('#reportingMonthYear').datepicker('setDate', new Date(year, month, 1));
		checkDublicateDataReporting();
            },
	    onChangeMonthYear: function(e){
                checkDublicateDataReporting();
            }
        });
	
	$('#dateofSupportVisit').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 100, // Creates a dropdown of 100 years to control year
            format: 'dd/mm/yyyy',
	    	max: new Date('Today'),
			closeOnSelect: true,
			closeOnClear: true,
			onSet: function(e){
				validateDataReportingDates();
				if(e.select != undefined && e.select != null){
					$('.picker__close').click();
				}
			}
        });
      <?php } ?>
    });
    
//    $(window).keyup(function (e) {
//	var code = (e.keyCode ? e.keyCode : e.which);
//	if (code == 9) {
//	   e.preventDefault();
//	}
//    });
    
    function getTotal(commonFieldClassName){
        var total = 0;
        $('.'+commonFieldClassName).each( function(i,e) {
            if($('#'+$(e).attr('id')).val()!= ''){
                total = parseInt(total)+parseInt($('#'+$(e).attr('id')).val());
                $('#lbl_'+commonFieldClassName+'_total').html(total);
                $('#'+commonFieldClassName+'_total').val(total);
            }
        });
    }
    
    function checkDublicateDataReporting(){
        var reportingMonthYear = $('#reportingMonthYear').val();
        var anc = $('#anc').val();
        if($.trim(reportingMonthYear)!= '' && $.trim(anc)!= ''){
            $.post("<?php echo $this->url('check-duplicate-data-report'); ?>", {clDataCollectionID:'<?php echo base64_encode($row->cl_data_collection_id); ?>',reportingMonthYear: reportingMonthYear,anc:anc,countryId:'<?php echo base64_encode($countryId); ?>'},
            function(data) {
                //alert('Duplicate data not allowed. The monthly data for anc site and year/month that you have choosed already entered');
		if ($.trim(data)!= '') { $.blockUI(); document.location.href = data; }
            });
        }
    }
    
    function updateDataReporting(){
        flag = deforayValidator.init({
            formId: 'editClinicDataReportingForm'
        });
        
        if(flag){
            document.getElementById('editClinicDataReportingForm').submit();
        }
    }
</script>