<?php
use Zend\Session\Container;
$loginContainer = new Container('user');
if(trim($countryId)!= ''){
    $link = "/clinic/data-collection/".base64_encode($countryId);
}else{
    $link = "/clinic/data-collection";
}
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/css/jquery-ui.css' ?>"/>
<style>
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        background-color: #eaeaea;
        border-bottom: 1px solid #ccc;
        padding: 10px 20px;
    }
    pre {
        max-height: 596px;
    }
    table.dataTable tbody td {
        padding: 8px 18px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        left: -184px;
    }
    #dataReportingDataTable_wrapper{
	overflow-x:scroll;
    }
    .select-wrapper{
	width:100%;
    }
    .ui-datepicker-calendar {
       display: none;
    }
    .ui-datepicker-month,.ui-datepicker-year{
       display:block;
       display:inline-block;
    }
    #ancFormTable thead tr th{
        text-align:center;
    }
    .dataTable_noWrap{
	white-space: nowrap;
        overflow: hidden;
    }
    .center_align{
	text-align:center;
    }
    table.dataTable tbody td{
	padding:2px 4px 0px 4px;
    }
    .rowOne{
        padding-top:20px;
	padding-bottom:0px;
    }
    @media only screen and (max-width: 1024px){
	.rowOne{
	    padding-top:0px !important;
	}
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">ANC Monthly Reporting</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">ANC Monthly Reporting</a>
       </div>
    </div>
    <?php if($loginContainer->hasViewOnlyAccess!= 'yes') { ?>
        <div class="formContainer row dashboard-wrapper content-container" style="margin-bottom:20px;">
	    <a class="formHide waves-effect waves-light btn-small  white-text pink margin-bottom-10" style="font-size:13px;">Hide this form</a>
            <form id="addClinicDataReportingForm" name="addClinicDataReportingForm" method="post" action="<?php echo $this->url('clinic-data-collection-add'); ?>">
                <div class="col l12 m12 s12" style="padding:0 !important;">
                    <div class="card card-default table-height">
                        <div class="card-content clearfix">
			    <div class="col l12 m12 s12" style="margin-bottom:1vh;">
				<div class="col l6 m6 s6" style="text-align:center;"><strong>Anc site name/code *</strong> <select class="material-select isRequired" id="anc" name="anc" title="Please select anc site" onchange="checkDublicateDataReporting();"><option value=""> -- Select -- </option><?php foreach($ancSites as $anc) { ?><option value="<?php echo base64_encode($anc['anc_site_id']); ?>"><?php echo ucwords($anc['anc_site_name']).' - '.$anc['anc_site_code']; ?></option><?php } ?></select></div>
				<div class="col l6 m6 s6" style="text-align:center;"><strong>Month/Year *</strong> <input type="text" class="monthYear isRequired" id="reportingMonthYear" name="reportingMonthYear" placeholder="Select Month and Year" title="Please select month and year" readonly/></div>
			    </div>
			    <div class="col l12 m12 s12">
				<table id="ancFormTable" class="responsive-table display">
				    <thead>
					<tr>
					    <th>Characteristics</th>
					    <th>Age < 15</th>
					    <th>Age 15-19</th>
					    <th>Age 20-24</th>
					    <th>Total</th>
					</tr>
				    </thead>
				    <tbody>
					<?php
					$r=1;
					foreach($ancFormFields as $key=>$value){
					    $fieldName = $key;
					    $tempLabel = ucwords(str_replace("_"," ",$key));
					    $mandatoryicon = ($fieldName!= 'no_of_recency_result' && $fieldName!= 'no_of_clients_who_received_recency_result')?' *':'';
					    $formLabel = str_replace("No","No.",$tempLabel).$mandatoryicon;
					    //set readonly fields based on age disaggregation
					    $commonFieldsStyle = 'pointer-events:auto;';
					    $styleTotal = 'pointer-events:none;display:none;';
					    $labelStyle = ($fieldName!= 'no_of_recency_result' && $fieldName!= 'no_of_clients_who_received_recency_result')?'':'color:#056dd2;font-weight:bold;';
					    $lblStyleTotal = '';
					    $commonFieldsIsRequired = ($fieldName!= 'no_of_recency_result' && $fieldName!= 'no_of_clients_who_received_recency_result')?'isRequired':'';
					    $isRequiredTotal = '';
					    if($value == 'no'){
						$mandatoryicon = ' *';
						$formLabel = str_replace("No","No.",$tempLabel).$mandatoryicon;
						$labelStyle = '';
						$commonFieldsStyle = 'pointer-events:none;display:none;';
						$styleTotal = 'pointer-events:auto;';
						$lblStyleTotal = 'display:none;';
						$commonFieldsIsRequired = '';
						$isRequiredTotal = 'isRequired';
					    }
					?>
					    <tr>
					      <td class="<?php echo($r > 1)?'':'rowOne'; ?>" style="<?php echo $labelStyle; ?><?php echo($r > 1)?'padding-top:0px;padding-bottom:0px;':''; ?>"><input type="hidden" id="field<?php echo $r; ?>" name="field[]" value="<?php echo $fieldName; ?>" style="height:2rem;"/><?php echo $formLabel; ?></td>
					      <td class="<?php echo($r > 1)?'':'rowOne'; ?>" <?php echo($value == 'no')?'colspan="4"':'' ?> style="<?php echo($r > 1)?'padding-top:0px;padding-bottom:0px;':''; ?>"><input id="<?php echo $fieldName; ?>_age_lt_15" name="<?php echo $fieldName; ?>[age_lt_15]" type="text" class="checkNum <?php echo $fieldName.' '.$commonFieldsIsRequired; ?>" title="Please fill in all the required fields" onkeyup="getTotal('<?php echo $fieldName; ?>');" style="height:2rem;text-align:center;<?php echo $commonFieldsStyle; ?>"/><?php if($value!= 'no') { ?></td><?php } ?>
					     <?php if($value!= 'no') { ?><td class="<?php echo($r > 1)?'':'rowOne'; ?>" style="<?php echo($r > 1)?'padding-top:0px;padding-bottom:0px;':''; ?>"><?php } ?><input id="<?php echo $fieldName; ?>_age_15_to_19" name="<?php echo $fieldName; ?>[age_15_to_19]" type="text" class="checkNum <?php echo $fieldName.' '.$commonFieldsIsRequired; ?>" title="Please fill in all the required fields" onkeyup="getTotal('<?php echo $fieldName; ?>');" style="height:2rem;text-align:center;<?php echo $commonFieldsStyle; ?>"/><?php if($value!= 'no') { ?></td><?php } ?>
					     <?php if($value!= 'no') { ?><td class="<?php echo($r > 1)?'':'rowOne'; ?>" style="<?php echo($r > 1)?'padding-top:0px;padding-bottom:0px;':''; ?>"><?php } ?><input id="<?php echo $fieldName; ?>_age_20_to_24" name="<?php echo $fieldName; ?>[age_20_to_24]" type="text" class="checkNum <?php echo $fieldName.' '.$commonFieldsIsRequired; ?>" title="Please fill in all the required fields" onkeyup="getTotal('<?php echo $fieldName; ?>');" style="height:2rem;text-align:center;<?php echo $commonFieldsStyle; ?>"/><?php if($value!= 'no') { ?></td><?php } ?>
					     <?php if($value!= 'no') { ?><td class="<?php echo($r > 1)?'':'rowOne'; ?>" style="<?php echo($r > 1)?'padding-top:0px;padding-bottom:0px;':''; ?>"><?php } ?><input id="<?php echo $fieldName; ?>_total" name="<?php echo $fieldName; ?>[total]" type="text" class="checkNum <?php echo $isRequiredTotal; ?>" title="Please fill in all the required fields" style="height:2rem;text-align:center;<?php echo $styleTotal; ?>"/><div id="lbl_<?php echo $fieldName; ?>_total" style="width:100%;text-align:center;border-bottom: 1px solid #eee;<?php echo $lblStyleTotal; ?>">0</div></td>
					    </tr>
					<?php $r++; } ?>
					<tr>
					    <td style="padding-top:0px;padding-bottom:0px;">Comments</td>
					    <td colspan="4" style="padding-top:0px;padding-bottom:0px;">
						<textarea id="comments" name="comments" class="materialize-textarea" style="height:2rem;"></textarea>
					    </td>
					</tr>
				    </tbody>
				</table>
			    </div>
                        </div>
                    </div>
                </div>
                <div class="col s12" style="margin-top:20px;">
                    <input type="hidden" name="chosenCountry" id="chosenCountry" value="<?php echo base64_encode($countryId); ?>"/>
                    <input type="hidden" name="redirectUrl" id="redirectUrl" value="<?php echo $link;?>"/>
                    <a href="<?php echo $link;?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                    <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addDataReporting();">SAVE</a>&nbsp;&nbsp;
                </div>
            </form>
        </div>
    <?php } ?>
    <div id="showListButton" class="row dashboard-wrapper content-container" style="margin-bottom: 10px;">
       <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="loadANCDataList();">Show ANC Data List</a>
    </div>
    <div class="row ancDataList" style="max-width:1109px;display:none;">
	<form id="dataCollectionFilter" action="#">
            <div class="col l12 m12 s12">
                <div class="col l1 m1 s1" style="visibility:hidden;">--FILTER START--</div>
                <div class="col l5 m5 s5" style="text-align:center;"><strong>Anc site name/code </strong> <select class="material-select" id="ancFilter" name="ancFilter" title="Please select anc site"><option value="">All</option><?php foreach($ancSites as $anc) { ?><option value="<?php echo base64_encode($anc['anc_site_id']); ?>"><?php echo ucwords($anc['anc_site_name']).'-'.$anc['anc_site_code']; ?></option><?php } ?></select></div>
                <div class="col l5 m5 s5" style="text-align:center;"><strong>Month/Year </strong> <input type="text" class="monthYear" id="reportingMonthYearFilter" name="reportingMonthYearFilter" placeholder="Select Month and Year" title="Please select month and year" readonly/></div>
                <div class="col l1 m1 s1" style="visibility:hidden;">--FILTER END--</div>
            </div>
            <div class="col l12 m12 s12" style="text-align:center;margin-bottom:20px;">
                <a href="javascript:void(0);" onclick="clearSearchFields();" class="waves-effect waves-light btn-small btn red-text custom-btn custom-btn-red"><i class="zmdi zmdi-refresh"></i> Reset</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0);" onclick="searchDataCollectionData();" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a>
            </div>
        </form>
    </div>
    <div class="row dashboard-wrapper content-container ancDataList" style="display:none;">
        <div class="col l12 m12 s12" style="padding:0 !important;">
            <div class="card card-default table-height">
                <div class="card-header dataTable-header"><i class="zmdi zmdi-filter-list"></i> ANC Data Reporting List</div>
                <div class="card-content clearfix">
                    <table id="dataReportingDataTable" class="responsive-table display dataTable">
                        <thead>
                            <tr>
                                <th>Clinic Name</th>
                                <th>Clinic ID</th>
				<th>Month</th>
				<th>Year</th>
				<?php
                                if(trim($countryId)== ''){ ?>
                                 <th>Country</th>
                                <?php }
				foreach($ancFormFields as $key=>$value){
                                    $formLabel = ucwords(str_replace("_"," ",$key));
                                    $formLabel = str_replace("No","No.",$formLabel);
                                ?>
                                  <th><?php echo $formLabel; ?></th>
                                <?php } ?>
				<th>Status</th>
                                <?php
                                if($loginContainer->hasViewOnlyAccess!= 'yes') {
                                ?>
                                  <th style="width:80px !important;text-align:center;">Action</th>
                                <?php } ?>
                            </tr>
                        </thead>
			<tfoot>
                            <tr>
                                <th>Clinic Name</th>
                                <th>Clinic ID</th>
				<th>Month</th>
				<th>Year</th>
				<?php
                                if(trim($countryId)== ''){ ?>
                                 <th>Country</th>
                                <?php }
                                foreach($ancFormFields as $key=>$value){
                                    $formLabel = ucwords(str_replace("_"," ",$key));
                                    $formLabel = str_replace("No","No.",$formLabel);
                                ?>
                                  <th><?php echo $formLabel; ?></th>
                                <?php } ?>
				<th>Status</th>
                                <?php
                                if($loginContainer->hasViewOnlyAccess!= 'yes') {
                                ?>
                                  <th style="text-align:center;">Action</th>
                                <?php } ?>
                            </tr>
                        </tfoot>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery-ui.js' ?>"></script>
<script>
    $(document).ready(function(){
       $('#reportingMonthYear').datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'M/yy',
            maxDate: 'Today',
            beforeShow : function(input, inst) {
                tmp = $('#reportingMonthYear').val().split('/');
                var dat = new Date('1 ' + tmp[0] + ' 1969');
                $('#reportingMonthYear').datepicker('option','defaultDate',new Date(tmp[1],parseInt(dat.getMonth()-1)+parseInt(1),1));
                $('#reportingMonthYear').datepicker('setDate', new Date(tmp[1], parseInt(dat.getMonth()-1)+parseInt(1), 1));
            },
            onClose: function(dateText, inst) {
                var month=$("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $('#reportingMonthYear').datepicker('setDate', new Date(year, month, 1));
                checkDublicateDataReporting();
            },
            onChangeMonthYear: function(e){
                checkDublicateDataReporting();
            }
       });
       
       $('#reportingMonthYearFilter').datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'M/yy',
            maxDate: 'Today',
            beforeShow : function(input, inst) {
                tmp = $('#reportingMonthYearFilter').val().split('/');
                var dat = new Date('1 ' + tmp[0] + ' 1969');
                $('#reportingMonthYearFilter').datepicker('option','defaultDate',new Date(tmp[1],parseInt(dat.getMonth()-1)+parseInt(1),1));
                $('#reportingMonthYearFilter').datepicker('setDate', new Date(tmp[1], parseInt(dat.getMonth()-1)+parseInt(1), 1));
            },
            onClose: function(dateText, inst) {
                var month=$("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $('#reportingMonthYearFilter').datepicker('setDate', new Date(year, month, 1));
            }
       });
    });
    
    var oTable = null;
    function loadANCDataList(){
	$(".ancDataList").show();
	$("#showListButton").hide();
	oTable = $('#dataReportingDataTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
	    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
	    "iDisplayLength": 25,
            "aoColumns": [
                {"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		<?php
                if(trim($countryId)== ''){ ?>
		{"sClass":"dataTable_noWrap"},
                <?php }
                foreach($ancFormFields as $key=>$value){ ?>
		  {"sClass":"dataTable_noWrap center_align","bSortable":false},
                <?php } ?>
		{"sClass":"dataTable_noWrap"},
                <?php
                if($loginContainer->hasViewOnlyAccess!= 'yes') {
                ?>
                  {"sClass":"dataTable_noWrap","bSortable":false}
                <?php } ?>
            ],
            "aaSorting": [[0, "asc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('clinic-data-collection'); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                aoData.push({"name": "countryId", "value": '<?php echo $countryId; ?>'});
                aoData.push({"name": "anc", "value": $('#ancFilter').val()});
                aoData.push({"name": "reportingMonthYear", "value": $('#reportingMonthYearFilter').val()});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
        
	$('.dataTables_filter').empty(); // clears the content generated
       $('.dataTables_filter').append(
                "<div class='input-field col s6 search-div right' style='width: 250px'>" +
                "    <i class='material-icons search-icon'>search</i> "+
                "    <input id='search-items' type='text' class='validate' />" +
                "    <label for='icon_prefix' class='search-label'>Search</label>   "+
                "</div>");
       $('#search-items').on('keyup', function(){
                    var oTable = $('.dataTable').dataTable();
                    oTable.fnFilter($(this).val());
                });
    }
    
    $("a.formHide").click(function(){
	$("#addClinicDataReportingForm").toggle();
	if ($.trim($(this).text()) === 'Hide this form') {
           $(this).text('Show this form');
	   $('.formContainer').css('margin-bottom','0px');
	} else {
	   $(this).text('Hide this form');
	   $('.formContainer').css('margin-bottom','20px');
	}
      return false;
    });
    
    function getTotal(commonFieldClassName){
        var total = 0;
        $('.'+commonFieldClassName).each( function(i,e) {
           /* you can use e.id instead of $(e).attr('id') */
            if($('#'+$(e).attr('id')).val()!= ''){
                total = parseInt(total)+parseInt($('#'+$(e).attr('id')).val());
                $('#lbl_'+commonFieldClassName+'_total').html(total);
                $('#'+commonFieldClassName+'_total').val(total);
            }
        });
    }
   
    function searchDataCollectionData(){
       oTable.fnDraw(false);
    }
    
    function clearSearchFields(){
        $('#dataCollectionFilter')[0].reset();
        searchDataCollectionData();
    }
    
    function checkDublicateDataReporting(){
        var reportingMonthYear = $('#reportingMonthYear').val();
        var anc = $('#anc').val();
        if($.trim(reportingMonthYear)!= '' && $.trim(anc)!= ''){
            $.post("<?php echo $this->url('check-duplicate-data-report'); ?>", {reportingMonthYear: reportingMonthYear,anc:anc,countryId:'<?php echo base64_encode($countryId); ?>'},
            function(data) {
                //alert('Duplicate data not allowed. The monthly data for anc site and year/month that you have choosed already entered');
                if ($.trim(data)!= '') { $.blockUI(); document.location.href = data; }
            });
        }
    }
    
    function lockClinicDataCollection(ID){
	var conf = confirm("Are you sure you want to lock this clinic data reporting?");
	if(conf){
	    $.post("<?php echo $this->url('lock-clinic-data-collection'); ?>", {clinicDataCollectionId:ID},
		function(data){
		    if($.trim(data) == 0 || $.trim(data) == ''){
		      alert("OOPS..");
		    }else{
		      oTable.fnDraw(false);
		    }
		});
	}
    }
    
    function unlockClinicDataCollection(ID){
	var conf = confirm("Are you sure you want to unlock this clinic data reporting?");
	if(conf){
	    $.post("<?php echo $this->url('unlock-clinic-data-collection'); ?>", {clinicDataCollectionId:ID},
		function(data){
		    if($.trim(data) == 0 || $.trim(data) == ''){
		      alert("OOPS..");
		    }else{
		      oTable.fnDraw(false);
		    }
		});
	}
    }
    
    function addDataReporting(){
        flag = deforayValidator.init({
            formId: 'addClinicDataReportingForm'
        });
        
        if(flag){
            document.getElementById('addClinicDataReportingForm').submit();
        }
    }
</script>