<?php
use Zend\Session\Container;
$loginContainer = new Container('user');
if(!isset($countryId) || trim($countryId)== ''){
    $countryId = '';
    $link = "/clinic/data-collection";
}else{
    $link = "/clinic/data-collection/".base64_encode($countryId);
}
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/css/jquery-ui.css' ?>"/>
<style>
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        background-color: #eaeaea;
        border-bottom: 1px solid #ccc;
        padding: 10px 20px;
    }
    pre {
        max-height: 596px;
    }
    table.dataTable tbody td {
        padding: 8px 18px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        /*left: -184px*/
    }
    #dataReportingDataTable_wrapper{
	overflow-x:scroll;
    }
    .select-wrapper{
	width:100%;
    }
    .ui-datepicker-calendar {
       display: none;
    }
    .ui-datepicker-month,.ui-datepicker-year{
       display:block;
       display:inline-block;
    }
    #ancFormTable thead tr th{
        text-align:center;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">ANC Data Reporting</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">ANC Data Reporting</a>
       </div>
    </div>
    <?php
    if($loginContainer->hasViewOnlyAccess =='no') {
    ?>
        <div class="row dashboard-wrapper content-container">
            <form id="addClinicDataReportingForm" name="addClinicDataReportingForm" method="post" action="<?php echo $this->url('clinic-data-collection-add'); ?>">
                <div class="col l12 m12 s12">
                    <div class="col l1 m1 s1" style="visibility:hidden;">--FILTER START--</div>
                    <div class="col l5 m5 s5" style="text-align:center;"><strong>Anc Site *</strong> <select class="material-select isRequired" id="anc" name="anc" title="Please select anc site"><option value=""> -- Select -- </option><?php foreach($ansSites as $anc) { ?><option value="<?php echo base64_encode($anc['anc_site_id']); ?>"><?php echo ucwords($anc['anc_site_name']); ?></option><?php } ?></select></div>
                    <div class="col l5 m5 s5" style="text-align:center;"><strong>Month/Year *</strong> <input type="text" class="monthYear isRequired" id="reportingMonthYear" name="reportingMonthYear" placeholder="Select Month and Year" title="Please select month and year" readonly/></div>
                    <div class="col l1 m1 s1" style="visibility:hidden;">--FILTER END--</div>
                </div>
                <div class="col l12 m12 s12">
                    <div class="card card-default table-height">
                        <div class="card-content clearfix">
                            <table id="ancFormTable" class="responsive-table display">
                                <thead>
                                    <tr>
                                        <th>Characteristics</th>
                                        <th>Age < 15</th>
                                        <th>Age 15-19</th>
                                        <th>Age 20-24</th>
                                        <th>Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $f=1;
                                    foreach($ancFormFields as $key=>$value){
                                        $fieldName = $key;
                                        $formLabel = ucwords(str_replace("_"," ",$key));
                                        $formLabel = str_replace("No","No.",$formLabel);
                                        //Set readonly on 'No'
                                        $commonFieldsStyle = 'pointer-events:auto;';
                                        $totalStyle = 'pointer-events:none;';
                                        if($value == 'no'){
                                            $commonFieldsStyle = 'pointer-events:none;';
                                            $totalStyle = 'pointer-events:auto;';
                                        }
                                    ?>
                                        <tr>
                                          <td><input type="hidden" id="field<?php echo $f; ?>" name="field[]" value="<?php echo $fieldName; ?>"/><?php echo $formLabel; ?></td>
                                          <td><input id="<?php echo $fieldName; ?>_age_lt_15" name="<?php echo $fieldName; ?>[age_lt_15]" type="text" class="checkNum <?php echo $fieldName; ?>" onkeyup="getTotal('<?php echo $fieldName; ?>');" style="<?php echo $commonFieldsStyle; ?>"/></td>
                                          <td><input id="<?php echo $fieldName; ?>_age_15_to_19" name="<?php echo $fieldName; ?>[age_15_to_19]" type="text" class="checkNum <?php echo $fieldName; ?>" onkeyup="getTotal('<?php echo $fieldName; ?>');" style="<?php echo $commonFieldsStyle; ?>"/></td>
                                          <td><input id="<?php echo $fieldName; ?>_age_20_to_24" name="<?php echo $fieldName; ?>[age_20_to_24]" type="text" class="checkNum <?php echo $fieldName; ?>" onkeyup="getTotal('<?php echo $fieldName; ?>');" style="<?php echo $commonFieldsStyle; ?>"/></td>
                                          <td><input id="<?php echo $fieldName; ?>_total" name="<?php echo $fieldName; ?>[total]" type="text" class="checkNum" style="<?php echo $totalStyle; ?>"/></td>
                                        </tr>
                                    <?php $f++; } ?>
                                    <tr>
                                        <td>Comments</td>
                                        <td colspan="4">
                                            <textarea id="comments" name="comments" class="materialize-textarea"></textarea>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col s12" style="margin-top:20px;">
                    <input type="hidden" name="chosenCountry" id="chosenCountry" value="<?php echo base64_encode($countryId); ?>"/>
                    <input type="hidden" name="redirectUrl" id="redirectUrl" value="<?php echo $link;?>"/>
                    <a href="<?php echo $link;?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                    <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addDataReporting();">SAVE</a>&nbsp;&nbsp;
                </div>
            </form>
        </div>
    <?php } ?>
    <div class="row" style="max-width:1109px;">
	<form id="dataCollectionFilter" action="#">
            <div class="col l12 m12 s12">
                <div class="col l1 m1 s1" style="visibility:hidden;">--FILTER START--</div>
                <div class="col l5 m5 s5" style="text-align:center;"><strong>Anc Site </strong> <select class="material-select" id="ancFilter" name="ancFilter" title="Please select anc site"><option value=""> -- Select -- </option><?php foreach($ansSites as $anc) { ?><option value="<?php echo base64_encode($anc['anc_site_id']); ?>"><?php echo ucwords($anc['anc_site_name']); ?></option><?php } ?></select></div>
                <div class="col l5 m5 s5" style="text-align:center;"><strong>Month/Year </strong> <input type="text" class="monthYear" id="reportingMonthYearFilter" name="reportingMonthYearFilter" placeholder="Select Month and Year" title="Please select month and year" readonly/></div>
                <div class="col l1 m1 s1" style="visibility:hidden;">--FILTER END--</div>
            </div>
            <div class="col l12 m12 s12" style="text-align:center;margin-bottom:20px;">
                <a href="javascript:void(0);" onclick="clearSearchFields();" class="waves-effect waves-light btn-small btn red-text custom-btn custom-btn-red"><i class="zmdi zmdi-refresh"></i> Reset</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0);" onclick="searchDataCollectionData();" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a>
            </div>
        </form>
    </div>
    <div class="row dashboard-wrapper content-container">
        <div class="col l12 m12 s12">
            <div class="card card-default table-height">
                <div class="card-header dataTable-header"><i class="zmdi zmdi-filter-list"></i> ANC Data Reporting List</div>
                <div class="card-content clearfix">
                    <table id="dataReportingDataTable" class="responsive-table display dataTable">
                        <thead>
                            <tr>
                                <th>Clinic Name</th>
                                <th>Clinic ID</th>
				<th>Month</th>
				<th>Year</th>
                                <th>Country</th>
                                <?php
                                foreach($ancFormFields as $key=>$value){
                                    $formLabel = ucwords(str_replace("_"," ",$key));
                                    $formLabel = str_replace("No","No.",$formLabel);
                                ?>
                                  <th><?php echo $formLabel; ?></th>
                                <?php } ?>
                                <th>Comments</th>
                                <?php
                                if($loginContainer->hasViewOnlyAccess =='no') {
                                ?>
                                  <th style="width:120px !important;">Action</th>
                                <?php } ?>
                            </tr>
                        </thead>
			<tfoot>
                            <tr>
                                <th>Clinic Name</th>
                                <th>Clinic ID</th>
				<th>Month</th>
				<th>Year</th>
                                <th>Country</th>
                                <?php
                                foreach($ancFormFields as $key=>$value){
                                    $formLabel = ucwords(str_replace("_"," ",$key));
                                    $formLabel = str_replace("No","No.",$formLabel);
                                ?>
                                  <th><?php echo $formLabel; ?></th>
                                <?php } ?>
                                <th>Comments</th>
                                <?php
                                if($loginContainer->hasViewOnlyAccess =='no') {
                                ?>
                                  <th>Action</th>
                                <?php } ?>
                            </tr>
                        </tfoot>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery-ui.js' ?>"></script>
<script>
    $(document).ready(function(){
        oTable = $('#dataReportingDataTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
	    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
	    "iDisplayLength": 25,
            "aoColumns": [
                {"sClass":"left"},
		{"sClass":"left"},
		{"sClass":"left"},
		{"sClass":"left"},
		{"sClass":"left"},
                <?php
                foreach($ancFormFields as $key=>$value){ ?>
		  {"sClass":"left","bSortable":false},
                <?php } ?>
                {"sClass":"center","bSortable":false},
                <?php
                if($loginContainer->hasViewOnlyAccess =='no') {
                ?>
                  {"sClass":"center","bSortable":false}
                <?php } ?>
            ],
            "aaSorting": [[0, "asc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('clinic-data-collection'); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                aoData.push({"name": "countryId", "value": '<?php echo $countryId; ?>'});
                aoData.push({"name": "anc", "value": $('#ancFilter').val()});
                aoData.push({"name": "reportingMonthYear", "value": $('#reportingMonthYearFilter').val()});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
        
       $('#reportingMonthYear').datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'M/yy',
            maxDate: 'Today',
            beforeShow : function(input, inst) {
                tmp = $('#reportingMonthYear').val().split('/');
                var dat = new Date('1 ' + tmp[0] + ' 1969');
                $('#reportingMonthYear').datepicker('option','defaultDate',new Date(tmp[1],parseInt(dat.getMonth()-1)+parseInt(1),1));
                $('#reportingMonthYear').datepicker('setDate', new Date(tmp[1], parseInt(dat.getMonth()-1)+parseInt(1), 1));
            },
            onClose: function(dateText, inst) {
                var month=$("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $('#reportingMonthYear').datepicker('setDate', new Date(year, month, 1));
            }
       });
       
       $('#reportingMonthYearFilter').datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'M/yy',
            maxDate: 'Today',
            beforeShow : function(input, inst) {
                tmp = $('#reportingMonthYearFilter').val().split('/');
                var dat = new Date('1 ' + tmp[0] + ' 1969');
                $('#reportingMonthYearFilter').datepicker('option','defaultDate',new Date(tmp[1],parseInt(dat.getMonth()-1)+parseInt(1),1));
                $('#reportingMonthYearFilter').datepicker('setDate', new Date(tmp[1], parseInt(dat.getMonth()-1)+parseInt(1), 1));
            },
            onClose: function(dateText, inst) {
                var month=$("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $('#reportingMonthYearFilter').datepicker('setDate', new Date(year, month, 1));
            }
       });
       doubleScroll(document.getElementById('dataReportingDataTable_wrapper'));
    });
    
    function getTotal(commonFieldClassName){
        total = 0;
        $('.'+commonFieldClassName).each( function(i,e) {
           /* you can use e.id instead of $(e).attr('id') */
            if($('#'+$(e).attr('id')).val()!= ''){
                total = parseInt(total)+parseInt($('#'+$(e).attr('id')).val());
                $('#'+commonFieldClassName+'_total').val(total);
            }
        });
    }
   
    function searchDataCollectionData(){
       oTable.fnDraw(false);
    }
    
    function clearSearchFields(){
        $('#dataCollectionFilter')[0].reset();
        searchDataCollectionData();
    }
    
    function addDataReporting(){
        flag = deforayValidator.init({
            formId: 'addClinicDataReportingForm'
        });
        
        if(flag){
            document.getElementById('addClinicDataReportingForm').submit();
        }
    }
</script>