<?php
use Zend\Session\Container;
$loginContainer = new Container('user');
if(trim($countryId)!= ''){
    $link = "/clinic/data-extraction/".base64_encode($countryId);
}else{
    $link = "/clinic/data-extraction";
}
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/css/jquery-ui.css' ?>"/>
<style>
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        background-color: #eaeaea;
        border-bottom: 1px solid #ccc;
        padding: 10px 20px;
    }
    pre {
        max-height: 596px;
    }
    table.dataTable tbody td {
        padding: 8px 18px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        left: -184px;
    }
    #dataExtractionDataTable_wrapper{
	overflow-x:scroll;
    }
    .select-wrapper{
	width:100%;
    }
    .ui-datepicker-calendar {
       display: none;
    }
    .ui-datepicker-month,.ui-datepicker-year{
       display:block;
       display:inline-block;
    }
    #ancFormTable thead tr th{
        text-align:center;
    }
    .dataTable_noWrap{
	white-space: nowrap;
        overflow: hidden;
    }
    .center_align{
	text-align:center;
    }
    table.dataTable tbody td{
	padding:4px 4px 4px 4px;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">ANC Data Download</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">ANC Data Download</a>
       </div>
    </div>
    <div class="row" style="max-width:1109px;">
	<form id="dataExtractionFilter" action="#">
	    <div class="col l12 m12 s12">
		<div class="col l1 m1 s1" style="visibility:hidden;">--FILTER START--</div>
		<div class="col l5 m5 s5" style="text-align:center;"><strong>Anc Site </strong> <select class="material-select" id="ancFilter" name="ancFilter" title="Please select anc site"><option value="">All</option><?php foreach($ancSites as $anc) { ?><option value="<?php echo base64_encode($anc['anc_site_id']); ?>"><?php echo ucwords($anc['anc_site_name']); ?></option><?php } ?></select></div>
		<div class="col l5 m5 s5" style="text-align:center;"><strong>Month/Year </strong> <input type="text" class="monthYear" id="reportingMonthYearFilter" name="reportingMonthYearFilter" placeholder="Select Month and Year" title="Please select month and year" readonly/></div>
		<div class="col l1 m1 s1" style="visibility:hidden;">--FILTER END--</div>
	    </div>
	    <div class="col l12 m12 s12" style="text-align:center;margin-bottom:20px;">
		<a href="javascript:void(0);" onclick="clearSearchFields();" class="waves-effect waves-light btn-small btn red-text custom-btn custom-btn-red"><i class="zmdi zmdi-refresh"></i> Reset</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="searchDataExtractionData();" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a>
		<?php if($loginContainer->hasViewOnlyAccess!= 'yes') { ?>
		   &nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:void(0);" onclick="extractDataCollectionData();" class="waves-effect waves-light btn-small btn green-text custom-btn custom-btn-green"><i class="zmdi zmdi-collection-text"></i> Export Excel</a>
		<?php } ?>
	    </div>
	</form>
    </div>
    <div class="row dashboard-wrapper content-container">
        <div class="col l12 m12 s12">
            <div class="card card-default table-height">
                <div class="card-header dataTable-header"><i class="zmdi zmdi-filter-list"></i> ANC Data Download List</div>
                <div class="card-content clearfix">
                    <table id="dataExtractionDataTable" class="responsive-table display dataTable">
                        <thead>
                            <tr>
                                <th>Clinic Name</th>
                                <th>Clinic ID</th>
				<th>Month</th>
				<th>Year</th>
				<?php
                                if(trim($countryId)== ''){ ?>
                                 <th>Country</th>
                                <?php }
                                foreach($ancFormFields as $key=>$value){
                                    $formLabel = ucwords(str_replace("_"," ",$key));
                                    $formLabel = str_replace("No","No.",$formLabel);
                                ?>
                                  <th><?php echo $formLabel; ?></th>
                                <?php } ?>
				<th>Comments</th>
                            </tr>
                        </thead>
			<tfoot>
                            <tr>
                                <th>Clinic Name</th>
                                <th>Clinic ID</th>
				<th>Month</th>
				<th>Year</th>
				<?php
                                if(trim($countryId)== ''){ ?>
                                 <th>Country</th>
                                <?php }
                                foreach($ancFormFields as $key=>$value){
                                    $formLabel = ucwords(str_replace("_"," ",$key));
                                    $formLabel = str_replace("No","No.",$formLabel);
                                ?>
                                  <th><?php echo $formLabel; ?></th>
                                <?php } ?>
				<th>Comments</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery-ui.js' ?>"></script>
<script>
    $(document).ready(function(){
        oTable = $('#dataExtractionDataTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
	    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
	    "iDisplayLength": 25,
            "aoColumns": [
                {"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		<?php
                if(trim($countryId)== ''){ ?>
		  {"sClass":"dataTable_noWrap"},
                <?php }
                foreach($ancFormFields as $key=>$value){ ?>
		  {"sClass":"dataTable_noWrap center_align","bSortable":false},
                <?php } ?>
		{"sClass":"dataTable_noWrap"}
            ],
            "aaSorting": [[0, "asc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('clinic-data-extraction'); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                aoData.push({"name": "countryId", "value": '<?php echo $countryId; ?>'});
                aoData.push({"name": "anc", "value": $('#ancFilter').val()});
                aoData.push({"name": "reportingMonthYear", "value": $('#reportingMonthYearFilter').val()});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
        
       $('.dataTables_filter').empty(); // clears the content generated
       $('.dataTables_filter').append(
                "<div class='input-field col s6 search-div right' style='width: 250px'>" +
                "    <i class='material-icons search-icon'>search</i> "+
                "    <input id='search-items' type='text' class='validate' />" +
                "    <label for='icon_prefix' class='search-label'>Search</label>   "+
                "</div>");
       $(document).on('keyup', "input[type='text']", function(){
                    var oTable = $('.dataTable').dataTable();
                    oTable.fnFilter($(this).val());
                });
       
       $('#reportingMonthYearFilter').datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'M/yy',
            maxDate: 'Today',
            beforeShow : function(input, inst) {
                tmp = $('#reportingMonthYearFilter').val().split('/');
                var dat = new Date('1 ' + tmp[0] + ' 1969');
                $('#reportingMonthYearFilter').datepicker('option','defaultDate',new Date(tmp[1],parseInt(dat.getMonth()-1)+parseInt(1),1));
                $('#reportingMonthYearFilter').datepicker('setDate', new Date(tmp[1], parseInt(dat.getMonth()-1)+parseInt(1), 1));
            },
            onClose: function(dateText, inst) {
                var month=$("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $('#reportingMonthYearFilter').datepicker('setDate', new Date(year, month, 1));
            }
       });
    });
   
    function searchDataExtractionData(){
       oTable.fnDraw(false);
    }
    
    function clearSearchFields(){
        $('#dataExtractionFilter')[0].reset();
        searchDataExtractionData();
    }
    
    function extractDataCollectionData(){
	$.blockUI();
	$.post("<?php echo $this->url('export-clinic-data-collection'); ?>", {countryId:'<?php echo $countryId; ?>'},
	function(data){
	    if(data == "" || data == null || data == undefined){
		alert('OOPS..Unable to generate excel.');
		$.unblockUI();
	    }else{
		$.unblockUI();
		window.open("/temporary/"+data, "_blank");
	    }
	});
    }
</script>