<?php
use Zend\Session\Container;
use Application\Service\CommonService;
$common = new CommonService();
$loginContainer = new Container('user');
if(isset($date) && trim($date)!= ''){
    $link = "/";
}else if(isset($countryId) && trim($countryId)!= ''){
    $link = "/clinic/return-recency/".base64_encode($countryId);
}else{
    $link = "/clinic/return-recency";
}



$dateReturnedToANC = '';
if(isset($result->anc_date_anc) && trim($result->anc_date_anc)!= '' && $result->anc_date_anc!= '0000-00-00' && $result->anc_date_anc!= NULL){
    $dateReturnedToANC = $common->viewDateFormat($result->anc_date_anc);
}else if(isset($result->ussd_date_anc) && trim($result->ussd_date_anc)!= '' && $result->ussd_date_anc!= '0000-00-00' && $result->ussd_date_anc!= NULL){
    $arr = explode(" ",$result->ussd_date_anc);
    $dateReturnedToANC = $common->viewDateFormat($arr[0]);
}

$dateReturnedToPatient = '';
if(isset($result->anc_date_participant) && trim($result->anc_date_participant)!= '' && $result->anc_date_participant!= '0000-00-00' && $result->anc_date_participant!= NULL){
    $dateReturnedToPatient = $common->viewDateFormat($result->anc_date_participant);
}else if(isset($result->ussd_date_participant) && trim($result->ussd_date_participant)!= '' && $result->ussd_date_participant!= '0000-00-00' && $result->ussd_date_participant!= NULL){
    $arr = explode(" ",$result->ussd_date_participant);
    $dateReturnedToPatient = $common->viewDateFormat($arr[0]);
}


?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/css/chosen.min.css' ?>"/>
<style>
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        background-color: #eaeaea;
        border-bottom: 1px solid #ccc;
        padding: 10px 20px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        left: -184px;
    }
    #recencyReturnTable_wrapper{
	overflow-x:scroll;
    }
    .dataTable_noWrap{
	white-space: nowrap;
        overflow: hidden;
    }
    table.dataTable tbody td{
	padding:2px 4px 2px 4px;
    }
    @media only screen and (max-width: 1024px){
	table.dataTable.display tbody tr:first-child td {
	    border-top: 1px solid #ddd;
        }
	table.dataTable tbody td{
	    padding: 6px 4px 6px 4px;
	}
    }
    .box-1,.box-2{
	float:left;
	width:44%;
    }
    .box-11,.box-21{
	float:left;
	width:100%;
	border:2px dotted #333;
	margin-top:8px !important;
    }
    #box-breaker{
	float:left;
	width:12%;
	font-size:40px;
	text-align:center;
	padding-top:3vh;
    }
    @media (max-width: 460px) {
	.hideDataTable{
	    display: none;
	}
    }
    /*.unlocKbtn:hover{
	position:relative;
    }
    .unlocKbtn[title]:hover:after {
	content: attr(title);
	position: absolute;
	left: -600px;
	top: 100%;
	white-space: nowrap;
	z-index: 1;
	background:red;
    }*/
    .redTxt{
	color:#F44336 !important;
    }
    .yellowTxt,.remove_sorting_1_style{
	background-color:#FFFF00 !important;
    }
    .blueTxt{
	color:#3792a8 !important;
    }
    .no_bgColor{
	background-color:#fff;
    }
    #readerValueRRDTLogVal, /*#readerValueRRDTLogValText,*/ #readerValueRRRLogVal/*, #readerValueRRRLogValText*/{
        text-align: center !important;
        font-size:14px;
    }
    #readerValueRRDTLogValText/*, #readerValueRRRLogValText*/{
        font-weight:bold;
        font-size:13px;
    }
    table.dataTable thead th, table.dataTable thead td,
    table.dataTable tfoot th, table.dataTable tfoot td{
	text-align:center;
    }
    table.dataTable thead th, table.dataTable thead td,
    table.dataTable tfoot th, table.dataTable tfoot td,
    table.dataTable.row-border tbody th, 
    table.dataTable.row-border tbody td, 
    table.dataTable.display tbody th, 
    table.dataTable.display tbody td{
	border: 1px solid #eeeeef;
    }
    .chosen-container-single .chosen-search input[type="text"]{
	padding:4px 0px 4px 0px !important;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Return of Recency Results</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">ANC Return of Recency Results</a>
       </div>
    </div>
    <?php
    if($loginContainer->hasViewOnlyAccess!= 'yes') { ?>
        <div class="formContainer row content-container" style="margin-bottom:20px;padding: 0 20px;">
            
            <form id="returnRecencyForm" name="returnRecencyForm" method="post" action="<?php echo $this->url('add-return-recency'); ?>" style="display:<?php echo (trim($type)!= '')?'none':'block'; ?>;">
            <div class="card">
                
                    <div class="row" style="margin-bottom:0;">
                            <?php
                            if(trim($countryId) == ''){
                            ?>
                            <div class="row" style="margin-bottom:0;">
                                <div class="col s4">
                                    <div class="input-field col m12 s12">
                                        <select id="country" name="country" class="material-select isRequired" title="Please select country" onchange="getCountriesLabAnc();">
                                            <option data-code="" value=""> -- Select -- </option>
                                            <?php
                                            foreach($countries as $country){
                                            ?>
                                            <option data-code="<?php echo $country['country_code']; ?>" value="<?php echo base64_encode($country['country_id']); ?>"><?php echo ucwords($country['country_name']); ?></option>
                                            <?php } ?>
                                        </select>
                                        <label for="country">Country **</label>
                                    </div>
                                </div>
                            </div>
                            <?php } ?>
                            <div class="row" style="margin-bottom:0;">
                                <div class="col s4">
                                    <div class="input-field col m12 s12">
                                        <input id="patientBarcodeId" name="patientBarcodeId" type="text" class="validate isRequired" title="Please enter Patient Barcode ID" value="<?php echo $result->patient_barcode_id; ?>">
                                        <label for="patientBarcodeId" class="">Patient Barcode ID **</label>
                                    </div>
                                </div>
                                <div class="col s4">
                                    <div class="input-field col m12 s12">
                                        <input id="ancPatientId" name="ancPatientId" type="text" class="validate" title="Please enter ANC patient ID" value="<?php echo $result->anc_patient_id; ?>">
                                        <label for="ancPatientId" class="">ANC Patient ID</label>
                                    </div>
                                </div>
                            
                                
                                <div class="col s4">
                                    <div class="input-field col m12 s12 ancSiteSection">
                                    <span>ANC site name **</span>
                                    <select id="ancSite" name="ancSite" class="ancSite isRequired" title="Please select ANC site">
                                        <option data-anc-site-code="" value=""> -- Select -- </option>
                                        <?php
                                        foreach($ancSites as $ancSite){
                                        ?>
                                        <option data-anc-site-code="<?php echo $ancSite['anc_site_code']; ?>" value="<?php echo base64_encode($ancSite['anc_site_id']); ?>"   <?php echo($result->anc_site == $ancSite['anc_site_id'])?'selected="selected"':''; ?>   ><?php echo $ancSite['anc_site_code'].' - '.ucwords($ancSite['anc_site_name']); ?></option>
                                        <?php } ?>
                                    </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-bottom:0;">
                                <div class="col s6">
                                    <div class="input-field col m12 s12">
                                    <input id="dateReturnedToANC" name="dateReturnedToANC" type="text" class="validate datepicker" title="Please enter date result returned to anc" value="<?php echo $dateReturnedToANC; ?>">
                                    <label for="dateReturnedToANC" class="">Date recency result returned to ANC site </label>
                                    </div>
                                </div>
                                <div class="col s6">
                                    <div class="input-field col m12 s12">
                                    <input id="dateReturnedToPatient" name="dateReturnedToPatient" type="text" class="validate datepicker" title="Please enter Date recency result returned to participant" value="<?php echo $dateReturnedToPatient; ?>">
                                    <label for="dateReturnedToPatient" class="">Date recency result returned to participant </label>
                                    </div>
                                </div>                
                                            
                            </div>
                            <div class="row" style="margin-bottom:0;">
                                <div class="col s6">
                                        <div class="input-field col m12 s12">
                                            <select id="reasonForNotReturningResult" name="reasonForNotReturningResult" class="material-select" title="Please select reason for not returning result">
                                                <option value=""> -- Select -- </option>
                                                <option value="1"   <?php echo($result->reason_for_not_returning == 1)?'selected="selected"':''; ?>   >Woman has not returned for follow-up</option>
                                                <option value="2"   <?php echo($result->reason_for_not_returning == 2)?'selected="selected"':''; ?>   >Woman returned for follow-up, but result had not yet been returned to ANC site at that time</option>
                                                <option value="3"   <?php echo($result->reason_for_not_returning == 3)?'selected="selected"':''; ?>   >Woman returned for follow-up after recency result was returned to ANC site, but staff did not return recency result. </option>
                                                <option value="4"   <?php echo($result->reason_for_not_returning == 4)?'selected="selected"':''; ?>   >Other</option>
                                            </select>
                                            <label for="reasonForNotReturningResult" class="">Reason for not returning result </label>
                                        </div>
                                </div>   
                                <div class="col s6" style="display:none;" id="reasonForNotReturningResultOtherSection">
                                    <div class="input-field col m12 s12">
                                    <input id="reasonForNotReturningResultOther" name="reasonForNotReturningResultOther" type="text" class="validate" title="Please enter reason for not returning result" value="<?php echo $result->reason_for_not_returning_other; ?>">
                                    <label for="reasonForNotReturningResultOther" class="">Please enter reason for not returning the result ** </label>
                                    </div>
                                </div>                                             
                            </div>
                        
                            
                    
                        <div class="col s6">
                        <input type="hidden" name="chosenCountry" id="chosenCountry" value="<?php echo (trim($countryId)!= '')?base64_encode($countryId):'';?>"/>
                        <input type="hidden" name="redirectUrl" id="redirectUrl" value="<?php echo $link;?>"/>
                        
                        <a href="<?php echo $link;?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                        <a id="addBtn" href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="returnRecency();">SAVE RETURN OF RECENCY RESULT</a>&nbsp;&nbsp;
                        </div>
                        <div class="col s6" style="text-align:right;">
                            ** required fields
                        </div>
                    </div>
                    </form>
                </div>
	    </div>
	</div>
    <?php } ?>
    

    
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/moment.min.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/chosen.jquery.js' ?>"></script>
<script>
    var oTable = null;
    function loadLabDataList(){
	
        
	
       $('.dataTables_filter').empty(); // clears the content generated
       $('.dataTables_filter').append(
                "<div class='input-field col s6 search-div right' style='width: 250px'>" +
                "    <i class='material-icons search-icon'>search</i> "+
                "    <input id='search-items' type='text' class='validate' />" +
                "    <label for='icon_prefix' class='search-label'>Search</label>   "+
                "</div>");
       $('#search-items').on('keyup', function(){
            oTable.fnFilter($(this).val());
       });
    }									

    $(document).ready(function() {
        $(".ancSite").chosen({
	        placeholder_text_single:"Select ANC", 
	        width:"100%"
	    });
	});
    
    
    function fnShowHide(iCol){
        var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
        oTable.fnSetColumnVis( iCol, bVis ? false : true );
    }

    
    
    
    
    $(document).ready(function(){

        $("#reasonForNotReturningResult").on('change',function(){

            if($(this).val() != ''){
                $("#dateReturnedToPatient").val("");
            }

            if($(this).val() == 4){
                $("#reasonForNotReturningResultOther").addClass('isRequired');
                $("#reasonForNotReturningResultOtherSection").show();
            }else{
                $("#reasonForNotReturningResultOther").val('');
                $("#reasonForNotReturningResultOther").removeClass('isRequired');
                $("#reasonForNotReturningResultOtherSection").hide();
            }
        });

          if($("#reasonForNotReturningResult").val() != ''){
                $("#dateReturnedToPatient").val("");
            }

        if($("#reasonForNotReturningResult").val() == 4){
                $("#reasonForNotReturningResultOther").addClass('isRequired');
                $("#reasonForNotReturningResultOtherSection").show();
            }else{
                $("#reasonForNotReturningResultOther").val('');
                $("#reasonForNotReturningResultOther").removeClass('isRequired');
                $("#reasonForNotReturningResultOtherSection").hide();
            }        

            $('.datepicker').pickadate({
                selectMonths: true, // Creates a dropdown to control month
                selectYears: 100, // Creates a dropdown of 100 years to control year
                format: 'dd/mm/yyyy',
                max: new Date('Today'),
                closeOnSelect: true,
                closeOnClear: true,
                onSet: function(e){
                    validateDataReportingDates();
                    if(e.select != undefined && e.select != null){
                        $('.picker__close').click();
                    }
                }
            });
    });
    
    
    function getCountriesLabAnc(){
	$.post("<?php echo $this->url('get-countries-lab-anc'); ?>", {country: $('#country').val()},
            function(data) {
		var dataArray = data.split('divider');
		    $('.ancSiteSection').html(dataArray[0]);
		    $(".ancSite").chosen({ placeholder_text_single:"Select ANC",  width:"100%" });
	    });
    }
    
   
    
    function validateDataReportingDates(){
	
    }
    
    function returnRecency(){
	
	    if($("#ancSite").val()==''){
		    alert("Please choose ANC site name");
		    $("#ancSite").css("background-color","#ffff99");
		    return false;
	    }
	
        flag = deforayValidator.init({
            formId: 'returnRecencyForm'
        });
	
        if(flag){
	    $("#addBtn").css("pointer-events","none");
	    $("#addBtn").css("background-color","#f3cdcd !important");
            document.getElementById('returnRecencyForm').submit();
        }
    }

</script>