<?php
use Zend\Session\Container;
$loginContainer = new Container('user');
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/css/jquery-ui.css' ?>"/>
<style>
    .ui-datepicker-calendar {
       display: none;
    }
    .ui-datepicker-month,.ui-datepicker-year{
       display:block;
       display:inline-block;
    }
    .ui-datepicker-title select{
	padding:0;
	height:1.5rem;
    }
    @font-face {
	font-family: 'Glyphicons Halflings';
	src: url('../../assets/fonts/glyphicons-halflings-regular.eot');
	src: url('../../assets/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../../assets/fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../../assets/fonts/glyphicons-halflings-regular.woff') format('woff'), url('../../assets/fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../../assets/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
    }
    .glyphicon {
      position: relative;
      top: 1px;
      display: inline-block;
      font-family: 'Glyphicons Halflings';
      font-style: normal;
      font-weight: normal;
      line-height: 1;
    
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }
    .glyphicon-arrow-left:before {
      content: "\e091";
    }
    .glyphicon-arrow-right:before {
      content: "\e092";
    }
    .glyphicon-arrow-up:before {
      content: "\e093";
    }
    .glyphicon-arrow-down:before {
      content: "\e094";
    }
    * {
      -webkit-box-sizing: border-box;
	 -moz-box-sizing: border-box;
	      box-sizing: border-box;
    }
    *:before,
    *:after {
      -webkit-box-sizing: border-box;
	 -moz-box-sizing: border-box;
	      box-sizing: border-box;
    }
    .card-header{
        background-color:#ff69b4;
    }
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        padding: 10px 20px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        left: -184px;

    }
    .select-wrapper{
	width:100%;
    }
    .dataTable_noWrap{
	white-space: nowrap;
        overflow: hidden;
    }
    table.dataTable tbody td{
	padding:4px 4px 4px 4px;
    }
    @media only screen and (max-width: 1024px){
	table.dataTable.display tbody tr:first-child td {
	    border-top: 1px solid #ddd;
        }
	table.dataTable tbody td{
	    padding: 6px 4px 6px 4px;
	}
    }
    #clinicEnrollmentDataTable_wrapper{
	padding-top:3vh;
    }
    .align_Center{
	text-align:center;
    }
    table tbody td:not(:first-child){
	text-align:center;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Enrollment Report</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Enrollment Report</a>
       </div>
    </div>
    <div class="row" style="max-width:1109px;">
	<form id="searchFilterForm" action="#">
	    <div class="row">
		<div class="col s6">
		     <div class="input-field col m12 s12">
			<input id="reportingMonthYear" name="reportingMonthYear" type="text" placeholder="Select month/year" title="Select month/year" readonly>
			<label for="reportingMonthYear">Month/Year</label>
		     </div>
		</div>
		<div class="col s6">
		     <div class="input-field col m12 s12">
			<select class="material-select" id="anc" name="anc" title="Please select anc">
			    <option value="">All ANCs</option>
			    <?php if(isset($ancSiteList) && count($ancSiteList) > 0){
				foreach($ancSiteList as $anc){
				?>
			       <option value="<?php echo base64_encode($anc['anc_site_id']); ?>"><?php echo ucwords($anc['anc_site_name']); ?></option>
			    <?php } } ?>
			</select>
			<label for="anc">ANC site name/code </label>
		     </div>
		</div>
	    </div>
	    <div class="col l12 m12 s12" style="text-align:center;">
		<a href="javascript:void(0);" onclick="clearSearchFields();" class="waves-effect waves-light btn-small btn red-text custom-btn custom-btn-red"><i class="zmdi zmdi-refresh"></i> Reset Filters</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="searchEnrollmentReportData('change');" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a>
	    </div>
	</form>
    </div>
    <div class="row content-container">
        <div class="col l12 m12 s12">
            <div class="card card-default">
                <div class="card-header white-text"><i class="zmdi zmdi-filter-list"></i> Enrollment Report</div>
                    <table id="clinicEnrollmentDataTable" class="responsive-table display dataTable">
                        <thead>
                            <tr>
				<th></th>
				<th style="text-align:center;">Overall</th>
				<th></th>
				<?php if(isset($provinces) && count($provinces) > 0){
				    foreach($provinces as $province){
				    ?>
				  <th style="text-align:center;"><?php echo ucwords($province['location_name']); ?></th>
				  <th></th>
				<?php } } ?>
                            </tr>
                        </thead>
			<tfoot>
                            <tr>
				<th></th>
                                <th style="text-align:center;">Overall</th>
				<th></th>
				<?php if(isset($provinces) && count($provinces) > 0){
				    foreach($provinces as $province){
				    ?>
				  <th style="text-align:center;"><?php echo ucwords($province['location_name']); ?></th>
				  <th></th>
				<?php } } ?>
                            </tr>
                        </tfoot>
                        <tbody id="clinicEnrollmentReportDetails">
                            
                        </tbody>
                    </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery-ui.js' ?>"></script>
<script>
    $(document).ready(function() {
	$("#reportingMonthYear").datepicker({ 
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'M/yy',
            maxDate: 'Today',        
            beforeShow : function(input, inst) {
                tmp = $('#reportingMonthYear').val().split('/');
                var dat = new Date('1 ' + tmp[0] + ' 1969');
                $('#reportingMonthYear').datepicker('option','defaultDate',new Date(tmp[1],parseInt(dat.getMonth()-1)+parseInt(1),1));
                $('#reportingMonthYear').datepicker('setDate', new Date(tmp[1], parseInt(dat.getMonth()-1)+parseInt(1), 1));
            },
            onClose: function(dateText, inst) {
                var month=$("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $('#reportingMonthYear').datepicker('setDate', new Date(year, month, 1));
            }
        });
	searchEnrollmentReportData('load');
    });
    
    function searchEnrollmentReportData(frmSrc){
	var reportingMonthYear = $('#reportingMonthYear').val();
	var anc = $('#anc').val();
	if(frmSrc!= 'load') { $.blockUI(); }
        $.post("<?php echo $this->url('get-enrollment-report-details'); ?>", {reportingMonthYear:reportingMonthYear,anc:anc,country:'<?php echo $countryId; ?>'},
	function(data) {
	    if(frmSrc!= 'load') { $.unblockUI(); }
	    $("#clinicEnrollmentReportDetails").html(data);
	});
    }
    
    function clearSearchFields(){
        $('#searchFilterForm')[0].reset();
        searchEnrollmentReportData('reset');
    }
</script>