<?php
$common = new \Application\Service\CommonService();
if(count($labReportResult) >0){
    //header and footer
    class MYPDF extends TCPDF {
        public function setSchemeName($heading,$logo) {
	  $this->heading = $heading;
	  $this->logo = $logo;
        }
	
        //Page header
        public function Header() {
            // Logo
            $image_file = APPLICATION_PATH . DIRECTORY_SEPARATOR . 'assets'. DIRECTORY_SEPARATOR . 'images'. DIRECTORY_SEPARATOR . $this->logo;
            $this->Image($image_file, 12,3, 20, '', 'PNG', '', 'T', false, 300, '', false, false, 0, false, false, false);
             //Set font
            $this->SetFont('helvetica', 'B', 20);
             //Title
            $this->writeHTMLCell(0,'',36,10,$this->heading,0,1,false,true,'C',true);
	    $this->writeHTMLCell(0,'','','','<br/><hr/>',0,1,false,true,'C',true);
        }
    
        // Page footer
        public function Footer() {
            // Position at 15 mm from bottom
            $this->SetY(-15);
            // Set font
            $this->SetFont('helvetica', '', 8);
            // Page number
            $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
        }
    }
    // create new PDF document
    $pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    $pdf->setPageOrientation('L');
    $pdf->setSchemeName('DREAMS Lab Results','dreams-small-logo.png');
    // set document information
    $pdf->SetCreator(PDF_CREATOR);
    //$pdf->SetAuthor('Dream');
    $pdf->SetTitle('DREAMS Lab Results');
    //$pdf->SetSubject('TCPDF Tutorial');
    //$pdf->SetKeywords('TCPDF, PDF, example, test, guide');
    
    // set default header data
    $pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);
    
    // set header and footer fonts
    $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
    $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
    
    // set default monospaced font
    $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
    
    // set margins
    //$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_RIGHT);
    //$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
    //$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
    
    // set auto page breaks
    $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
    
    // set image scale factor
    $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
    
    // set some language-dependent strings (optional)
    //if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    //    require_once(dirname(__FILE__).'/lang/eng.php');
    //    $pdf->setLanguageArray($l);
    //}
    
    // ---------------------------------------------------------
    
    // set font
    $pdf->SetFont('helvetica', '', 10);
    
    $pdf->AddPage();
    $pdf->SetMargins(10, 28, 10, true);
    //$pdf->SetFooterMargin(10);
    $pdf->SetY(28,true,false);
    
    $vlReportType = 'show';
    $infectionType = 'show';
    if(isset($params['reportType']) && trim($params['reportType'])== 'vl'){
        $infectionType = 'hide';
    }else if(isset($params['reportType']) && trim($params['reportType'])== 'in'){
        $vlReportType = 'hide';
    }
    $html = '';
      $html.='<table border="1" style="padding:2px;">';
          $html .='<thead>';
           $html .='<tr>';
           $html .='<th><strong>Specimen Collected Date</strong></th>';
           $html .='<th><strong>Status</strong></th>';
           $html .='<th><strong>ANC Site</strong></th>';
           $html .='<th><strong>ANC Patient ID</strong></th>';
           $html .='<th><strong>Age</strong></th>';
           $html .='<th><strong>Specimen Pick Up Date at ANC</strong></th>';
           $html .='<th><strong>Lab/Facility</strong></th>';
           $html .='<th><strong>Lab Specimen ID</strong></th>';
           $html .='<th><strong>Rejection Code</strong></th>';
           $html .='<th><strong>Receipt Date at Lab</strong></th>';
           $html .='<th><strong>Date of Test Completion</strong></th>';
           $html .='<th><strong>Result Dispatched Date to Clinic</strong></th>';
           if($infectionType =='show'){
              $html .='<th><strong>LAg Avidity</strong></th>';
              $html .='<th><strong>LAg Avidity Result</strong></th>';
           }if($vlReportType =='show'){
              $html .='<th><strong>HIV RNA</strong></th>';
              //$html .='<th><strong>HIV RNA > 1000</strong></th>';
           }if($infectionType =='show'){
              $html .='<th><strong>Recent Infection</strong></th>';
           }
	   $html .='<th><strong>Comments</strong></th>';
           $html .='</tr>';
          $html .='</thead>';
          $html .='<tbody>';
          foreach($labReportResult as $row){
            $specimenCollectedDate = '';
	    $specimenPickUpDateatAnc = '';
	    $receiptDateAtCentralLab = '';
	    $testCompletionDate = '';
	    $resultDispatchedDateToClinic = '';
	    if(isset($row['specimen_collected_date']) && trim($row['specimen_collected_date'])!= '' && $row['specimen_collected_date']!= '0000-00-00'){
	      $specimenCollectedDate = $common->viewDateFormat($row['specimen_collected_date']);
	    }if(isset($row['specimen_picked_up_date_at_anc']) && trim($row['specimen_picked_up_date_at_anc'])!= '' && $row['specimen_picked_up_date_at_anc']!= '0000-00-00'){
	      $specimenPickUpDateatAnc = $common->viewDateFormat($row['specimen_picked_up_date_at_anc']);
	    }if(isset($row['receipt_date_at_central_lab']) && trim($row['receipt_date_at_central_lab'])!= '' && $row['receipt_date_at_central_lab']!= '0000-00-00'){
	      $receiptDateAtCentralLab = $common->viewDateFormat($row['receipt_date_at_central_lab']);
	    }if(isset($row['date_of_test_completion']) && trim($row['date_of_test_completion'])!= '' && $row['date_of_test_completion']!= '0000-00-00'){
	      $testCompletionDate = $common->viewDateFormat($row['date_of_test_completion']);
	    }if(isset($row['result_dispatched_date_to_clinic']) && trim($row['result_dispatched_date_to_clinic'])!= '' && $row['result_dispatched_date_to_clinic']!= '0000-00-00'){
	      $resultDispatchedDateToClinic = $common->viewDateFormat($row['result_dispatched_date_to_clinic']);
	    }
	    $rejectionCode = '';
	    if(isset($row['rejection_code']) && (int)$row['rejection_code'] > 1){
		$rejectionCode = $row['rejection_code'];
	    }
	    $lAgAvidityResult = ($row['lag_avidity_result']!= null && trim($row['lag_avidity_result'])!= '')?ucwords($row['lag_avidity_result']):'';
	    //$hIVRNAResult = '';
	    //if(trim($row['hiv_rna_gt_1000'])!= '' && $row['hiv_rna_gt_1000'] =='yes'){
	    //  $hIVRNAResult = 'High Viral Load';
	    //}else if(trim($row['hiv_rna_gt_1000'])!= '' && $row['hiv_rna_gt_1000'] =='no'){
	    //  $hIVRNAResult = 'Low Viral Load';
	    //}
	    //status
	    if($row['final_lag_avidity_odn'] <= 2 && (trim($row['hiv_rna']) == '' || $row['hiv_rna'] == null)){
		$status = 'Results Awaited';
	    }else{
		$status = ucwords($row['test_status_name']);
	    }
	    
            $html .='<tr>';
              $html .='<td>'.$specimenCollectedDate.'</td>';
              $html .='<td>'.$status.'</td>';
              $html .='<td>'.ucwords($row['anc_site_name'])." - ".$row['anc_site_code'].'</td>';
              $html .='<td>'.$row['anc_patient_id'].'</td>';
              $html .='<td>'.$row['age'].'</td>';
              $html .='<td>'.$specimenPickUpDateatAnc.'</td>';
              $html .='<td>'.ucwords($row['facility_name'])." - ".$row['facility_code'].'</td>';
              $html .='<td>'.$row['lab_specimen_id'].'</td>';
              $html .='<td>'.$rejectionCode.'</td>';
              $html .='<td>'.$receiptDateAtCentralLab.'</td>';
              $html .='<td>'.$testCompletionDate.'</td>';
              $html .='<td>'.$resultDispatchedDateToClinic.'</td>';
              if($infectionType =='show'){
                  $html .='<td>'.$row['final_lag_avidity_odn'].'</td>';
                  $html .='<td>'.$lAgAvidityResult.'</td>';
              }if($vlReportType =='show'){
                  $html .='<td>'.$row['hiv_rna'].'</td>';
                  //$html .='<td>'.$hIVRNAResult.'</td>';
              }if($infectionType =='show'){
                $html .='<td>'.ucfirst($row['recent_infection']).'</td>';
              }
	      $html .='<td>'.ucfirst($row['comments']).'</td>';
            $html .='</tr>';
          }
          $html .='</tbody>';
      $html.='</table>';
    $pdf->writeHTML(utf8_encode($html),true,0,true,0);
    $filename = 'ANC-LAB-REPORT--'.date('d-M-Y-H-i-s').'.pdf';
    $pdf->Output(TEMP_UPLOAD_PATH . DIRECTORY_SEPARATOR . $filename,"F");
    echo $filename;
}else{
    echo null;
}
?>