<?php
use Zend\Session\Container;
$loginContainer = new Container('user');
?>
<style>
    .card-header{
        background-color:#ff69b4;
    }
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        padding: 10px 20px;
    }
    table th,table td{
        text-align:center;
    }
    .select-wrapper{
	width:100%;
    }
    table.dataTable tbody td {
        padding: 8px 18px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        left: -184px;
    }
    .select-wrapper{
	width:100%;
    }
    .dataTable_noWrap{
	white-space: nowrap;
        overflow: hidden;
    }
    table.dataTable tbody td{
	padding:4px 4px 4px 4px;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <h4 class="page-title">Study Files </h4>
    </div>
    <div class="row">
	<div class="col s12">
	    <div class="card card-default">
		<div class="card-header white-text"><i class="zmdi zmdi-filter-list"></i> Study Files
                  <?php if($loginContainer->hasViewOnlyAccess!= 'yes') { ?>
                    <span style="float:right;"><a class="custom-add-btn" href="/study-files/upload"><i class="zmdi zmdi-cloud-upload"></i> Upload</a></span>
                  <?php } ?>
                </div>
		<div class="card-content clearfix">
		    <table id="studyFilesDataTable" class="responsive-table striped">
			<thead>
			<tr>
			    <th>File Name</th>
			    <th>File Description/Comments</th>
			    <th>Uploaded Datetime</th>
			    <th>Uploaded By</th>
                            <th>Action</th>
			</tr>
			</thead>
			<tfoot>
			<tr>
			    <th>File Name</th>
			    <th>File Description/Comments</th>
			    <th>Uploaded Datetime</th>
			    <th>Uploaded By</th>
                            <th>Action</th>
			</tr>
			</tfoot>
			<tbody>
			</tbody>
		    </table>
		</div>
	    </div>
	</div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery-ui.js' ?>"></script>
<script>
    $(document).ready(function(){
       oTable = $('#studyFilesDataTable').dataTable({
	    "autoWidth": false,
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
	    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
	    "iDisplayLength": 25,
            "aoColumns": [
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
                {"sClass":"dataTable_noWrap","bSortable":false}
            ],
            "aaSorting": [[2, "desc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('study-files'); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
        $('.dataTables_filter').empty(); // clears the content generated
        $('.dataTables_filter').append(
                "<div class='input-field col s6 search-div right' style='width: 250px'>" +
                "    <i class='material-icons search-icon'>search</i> "+
                "    <input id='search-items' type='text' class='validate' />" +
                "    <label for='icon_prefix' class='search-label'>Search</label>   "+
                "</div>");
        $(document).on('keyup', "input[type='text']", function(){
                    var oTable = $('.dataTable').dataTable();
                    oTable.fnFilter($(this).val());
                });
    });
</script>