<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Study File Upload</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Study File Upload</a>
        </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="studyFileUpload" name="studyFileUpload" method="post" enctype="multipart/form-data" action="<?php echo $this->url('study-files',array('action'=>'upload')); ?>">
            <div class="card">
                <div class="row" style="margin-bottom:10px;">
                    <div class="col s12">
                        <div class="input-field col m8 s8">
                            <span style="color:#9e9e9e;">Choose File *</span><br>
                            <input id="studyFile" name="studyFile" type="file" class="validate isRequired" title="Please select file" onchange="return fileValidation();" style="margin-top:1vh;">
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-bottom:10px;">
                    <div class="col m8 s8" style="color:red;font-size:13px;">Supported formats : .txt, .csv, .xls, .xlsx, .doc, .pdf</div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <div class="input-field col m8 s8">
                            <textarea id="description" name="description" class="materialize-textarea isRequired" title="Please enter file description or comments"></textarea>
                            <label for="description">File Description/Comments *</label>
                        </div>
                    </div>
                </div>
                <div class="col s12">
                    <a href="/study-files" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                    <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="validateNow();">UPLOAD </a>&nbsp;&nbsp;
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    function fileValidation(){
        var fileInput = document.getElementById('studyFile');
        var filePath = fileInput.value;
        var allowedExtensions = /(\.txt|\.csv|\.xls|\.xlsx|\.doc|\.pdf)$/i;
        if(!allowedExtensions.exec(filePath)){
            alert('The format of the file you\'ve chosen is not among the formats supported by DREAMS. The supported formats include .txt, .csv, .xls, .xlsx, .doc, .pdf');
            fileInput.value = '';
            return false;
        }
    }

    function validateNow(){
        flag = deforayValidator.init({
            formId: 'studyFileUpload'
        });
        
        if(flag){
            $.blockUI();
            document.getElementById('studyFileUpload').submit();
        }
    }
</script>