<?php
use Zend\Session\Container;
$alertContainer = new Container('alert');
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta name="description" content="Dream">
        <title>DREAM</title>
        <link rel="shortcut icon" type="image/x-icon" href="assets/images/favicon32x32.ico">
        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="<?php echo $this->basePath() .'/assets/css/material-design-iconic-font.css' ?>">

        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() .'/assets/css/mara.min.css' ?>"  media="screen"/>
    </head>
    <body class="black">
        <div class="center signin-page" id="full-page">
            <div class="black white-text signin-content">
                <h1 class="center-align mTitle" style="font-family: BaronFont">DREAM</h1>
                <div class="white signUpContainer center">
                  <form id="loginForm" name="loginForm" method="post" action="<?php echo $this->url('login'); ?>">
                    <div class="signUpContent">
                        <h6 class="black-text center-align">Sign in with your Dream account:</h6>
                        <div class="input-field">
                            <input id="userName" name="userName" type="text" class="validate black-text isRequired" title="Please enter user name">
                            <label for="userName" class="left-align">User Name</label>
                        </div>
                        <div class="input-field">
                            <input id="password" name="password" type="password" class="validate black-text isRequired" title="Please enter your password">
                            <label for="password" class=" left-align">Password</label>
                        </div>
                        <div class="input-field">
                            <select id="country" name="country" class="black-text material-select" title="Please select country">
                               <option value=""> -- Select -- </option>
                               <?php
                               foreach($countries as $country){
                               ?>
                                 <option value="<?php echo base64_encode($country['country_id']); ?>"><?php echo ucwords($country['country_name']); ?></option>
                               <?php } ?>
                            </select>
                            <label for="country" class=" left-align">Country (Optional)</label>
                        </div>
                        <p>
                            <input type="checkbox" id="terms" />
                            <label for="terms" class="black-text">Keep me signed in</label>
                        </p>
                        <a class="waves-effect waves-light btn signInButton" onclick="getLogin();return false;">Sign In</a>
                    </div>
                  </form>
                </div>
            </div>
        </div>
        <script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery-2.1.1.min.js' ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/materialize.js' ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/mara.min.js' ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/deforayValidation.js' ?>"></script>
        <script>
          $(document).ready(function() {
            $('.material-select').material_select();
            <?php
            if (isset($alertContainer->msg) && $alertContainer->msg != "") {
                ?>
                   alert("<?php echo $alertContainer->msg; ?>");
                <?php
                $alertContainer->msg = "";
                unset($alertContainer->msg);
            }
            ?>
          });
          
          function getLogin(){
            flag = deforayValidator.init({
                formId: 'loginForm'
            });
            
            if(flag){
                document.getElementById('loginForm').submit();
            }
          }
        </script>
    </body>
</html>