<?php
use Zend\Session\Container;
$container = new Container('alert');
$sessionLogin = new Container('credo');
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>BNI Dollars</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link href="<?php echo $this->basePath() . '/assets/css/bootstrap.min.css'?>" rel="stylesheet">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/datatables/dataTables.bootstrap.css' ?>">
  <!-- Theme style -->
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/AdminLTE.min.css' ?>">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/skins/_all-skins.min.css' ?>">
  <!--files-->
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/select2.min.css' ?>">
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/daterangepicker/daterangepicker.css' ?>">
  

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <!-- jQuery 2.2.3 -->
<script src="<?php echo $this->basePath() . '/assets/plugins/jQuery/jquery-2.2.3.min.js' ?>"></script>
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<style>
  .mandatory{color: #f30f00;}
</style>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="../../index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>BNI</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>BNI Dollars </b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
	<!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
         
              
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="<?php echo $this->basePath() . '/assets/img/user2-160x160.jpg'; ?>" class="user-image" alt="User Image">
              <span class="hidden-xs"><?php echo $sessionLogin->name; ?></span>
            </a>
            <ul class="dropdown-menu">
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
		  <a href="<?php echo $this->url('admin-user',array('action'=>'change-password')); ?>" class="btn btn-default btn-flat">Change Password</a>
                </div>
		<div class="pull-right">
                  <a href="<?php echo $this->url('login',array('action'=>'logout')); ?>" class="btn btn-default btn-flat">Log out</a>
                </div>
              </li>
            </ul>
          </li>
          
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
     <div class="user-panel">
        <div class="pull-left image">
          <img src="<?php echo $this->basePath() . '/assets/img/user2-160x160.jpg'; ?>" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p><?php echo $sessionLogin->name; ?></p>
          
        </div>
      </div>
      
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        
        <li>
          <a href="<?php echo $this->url('admin-home', array('action' => 'index'));?>">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
          </a>
	  </li>
	<li class="treeview" id="manage">
	    <a href="javascript:void(0);">
		<i class="fa fa-cogs"></i>
		<span>Industry</span>
		<i class="fa fa-angle-left pull-right"></i>
	    </a>
	     <ul class="treeview-menu" id="admin">
		<li id='layout-industry'><a href="<?php echo $this->url('admin-industry', array('action' => 'index'));?>"><i class="fa fa-angle-double-right "></i><span>Manage Industry</span></a></li>
	     </ul>
	</li>
	<li class="treeview" id="manage">
	    <a href="javascript:void(0);">
		<i class="fa fa-cogs"></i>
		<span>User</span>
		<i class="fa fa-angle-left pull-right"></i>
	    </a>
	     <ul class="treeview-menu" id="user">
		<li id='layout-user'><a href="<?php echo $this->url('admin-user', array('action' => 'index'));?>"><i class="fa fa-angle-double-right "></i><span>Manage User</span></a></li>
	     </ul>
	</li>
	<li class="treeview" id="giveAsk">
	      <a href="javascript:void(0);">
		  <i class="fa fa-database"></i>
		  <span>Give & Ask</span>
		  <i class="fa fa-angle-left pull-right"></i>
	      </a>
	       <ul class="treeview-menu" id="giveAskMember">
		  <li id='layout-giveaskmember'><a href="<?php echo $this->url('admin-giveask', array('action' => 'index'));?>"><i class="fa fa-angle-double-right "></i><span>Add Give & Ask</span></a></li>
		  <li id='layout-giveaskmember'><a href="<?php echo $this->url('admin-giveask', array('action' => 'member'));?>"><i class="fa fa-angle-double-right "></i><span>Member Give & Ask</span></a></li>
		  <li id='layout-giveasksearch'><a href="<?php echo $this->url('admin-giveask', array('action' => 'search'));?>"><i class="fa fa-angle-double-right "></i><span>Search Give & Ask</span></a></li>
	       </ul>
	</li>
    <li class="treeview" id="trafficLights">
	    <a href="javascript:void(0);">
		<i class="fa fa-cogs"></i>
		<span>Traffic Lights</span>
		<i class="fa fa-angle-left pull-right"></i>
	    </a>
	     <ul class="treeview-menu" id="admin">
		<li id='layout-traffic'><a href="<?php echo $this->url('admin-traffic-lights', array('action' => 'green-guide'));?>"><i class="fa fa-angle-double-right "></i><span>Green Guide</span></a></li>
		<li id='layout-traffic'><a href="<?php echo $this->url('admin-traffic-lights', array('action' => 'upload-palms'));?>"><i class="fa fa-angle-double-right "></i><span>Upload PALMS</span></a></li>
		<li id='layout-traffic'><a href="<?php echo $this->url('admin-traffic-lights', array('action' => 'upload-training'));?>"><i class="fa fa-angle-double-right "></i><span>Upload Training</span></a></li>
	     </ul>
	</li>
	<li class="treeview" id="giveAsk">
	      <a href="javascript:void(0);">
		  <i class="fa fa-database"></i>
		  <span>Push Notification</span>
		  <i class="fa fa-angle-left pull-right"></i>
	      </a>
	       <ul class="treeview-menu" id="notification">
		  <li id='layout-notification'><a href="<?php echo $this->url('admin-notification', array('action' => 'index'));?>"><i class="fa fa-angle-double-right "></i><span>Notification</span></a></li>
		  <li id='layout-user-notification'><a href="<?php echo $this->url('admin-notification', array('action' => 'user-notification'));?>"><i class="fa fa-angle-double-right "></i><span>User Notification</span></a></li>
	       </ul>
	</li>
	<li class="treeview" id="accounts">
	    <a href="javascript:void(0);">
		<i class="fa fa-book"></i>
		<span>Accounts</span>
		<i class="fa fa-angle-left pull-right"></i>
	    </a>
	     <ul class="treeview-menu">
		<li id='layout-accounts'><a href="<?php echo $this->url('admin-accounts', array('action' => 'subscription'));?>"><i class="fa fa-angle-double-right "></i><span>Subscription</span></a></li>
		<li id='layout-update-transaction'><a href="<?php echo $this->url('admin-accounts', array('action' => 'update-transaction'));?>"><i class="fa fa-angle-double-right "></i><span>Update Transaction</span></a></li>
		<li id='layout-accounts-transaction'><a href="<?php echo $this->url('admin-accounts', array('action' => 'transaction'));?>"><i class="fa fa-angle-double-right "></i><span>View Transaction</span></a></li>
		<li id='layout-accounts-heads'><a href="<?php echo $this->url('admin-accounts', array('action' => 'view-heads'));?>"><i class="fa fa-angle-double-right "></i><span>Account Heads</span></a></li>
	     </ul>
	</li>
	<li class="treeview" id="accounts">
	    <a href="javascript:void(0);">
		<i class="fa fa-book"></i>
		<span>Mail Template</span>
		<i class="fa fa-angle-left pull-right"></i>
	    </a>
	     <ul class="treeview-menu">
		<li id='layout-forgot-password'><a href='/admin/mail-template/index/forgot-password' title='Forgot password'><i class='fa fa-angle-double-right'></i>Forgot Password</a></li>
		<li id='layout-change-password'><a href='/admin/mail-template/index/change-password' title='Change password'><i class='fa fa-angle-double-right'></i>Change Password</a></li>
	     </ul>
	</li>
	
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

    <?php echo $this->content; ?>
    <?php echo (isset($this->aclError) ? $this->aclError : ""); ?>
  
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    
    <strong>Copyright &copy; 2014-2016 <a href="http://deforay.com">Deforay</a>.</strong> All rights
    reserved.
  </footer>


</div>
<!-- ./wrapper -->


<!-- Bootstrap 3.3.6 -->
<script src="<?php echo $this->basePath() . '/assets/js/bootstrap.min.js'?>"></script>
<!-- DataTables -->
<script src="<?php echo $this->basePath() . '/assets/plugins/datatables/jquery.dataTables.min.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/plugins/datatables/dataTables.bootstrap.min.js' ?>"></script>

<!-- FastClick -->
<script src="<?php echo $this->basePath() . '/assets/plugins/fastclick/fastclick.js' ?>"></script>
<!-- AdminLTE App -->
<script src="<?php echo $this->basePath() . '/assets/js/app.min.js' ?>"></script>
<!-- AdminLTE for demo purposes -->
<script src="<?php echo $this->basePath() . '/assets/js/deforayValidation.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/js/jquery.blockUI.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/js/select2.js'; ?>"></script>
<!-- page script -->
<script>
  $(function () {
    <?php
            if (isset($container->alertMsg) && $container->alertMsg != "") {
                ?>
                alert("<?php echo $container->alertMsg; ?>");
                <?php
                $container->alertMsg = "";
                unset($container->alertMsg);
            }
    ?>
    
  });
  jQuery(".checkNum").keydown(function (e) {
	      // Allow: backspace, delete, tab, escape, enter and .
	      if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
		       // Allow: Ctrl+A
		      (e.keyCode == 65 && e.ctrlKey === true) || 
		       // Allow: home, end, left, right
		      (e.keyCode >= 35 && e.keyCode <= 39)) {
			       // let it happen, don't do anything
			       return;
	      }
	      // Ensure that it is a number and stop the keypress
	      if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
		      e.preventDefault();
	      }
      });
</script>
</body>
</html>
