<?php
use Zend\Session\Container;
$alertContainer = new Container('alert');
$loginContainer = new Container('employee');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="Dream">
    <title>DREAM</title>
    <link rel="shortcut icon" type="image/x-icon" href="">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="<?php echo $this->basePath() .'/assets/css/material-design-iconic-font.css' ?>">
    <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() .'/assets/css/jquery.dataTables.min.css' ?>"  media="screen"/>
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() .'/assets/css/mara.min.css' ?>"  media="screen"/>
    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/css/prism.css' ?>"/>
    <style>
        .wrapper main {
            margin-bottom:0px !important;
            padding-bottom:0px !important;
        }
        .classic-breadcrumbs{
            padding-top:14px !important;
        }
        .classic-breadcrumbs a:last-child {
          color:#333;
        }
    </style>
    <script  src="<?php echo $this->basePath() .'/assets/js/jquery-2.1.1.min.js' ?>"></script>
</head>
<body>
<!--Page load animation-->
<div class="page-loader-container"><div class="dizzy-gillespie"></div></div>
<div class="wrapper vertical-sidebar" id="full-page">
    <header id="header">
        <div class="navbar">
            <nav>
                <a href="#" data-activates="nav-mobile" class="button-collapse top-nav full waves-effect waves-light"><i class="material-icons">menu</i></a>
                <div class="nav-wrapper">
                    <ul class="left">
                        <li>
                            <a href="<?php echo $this->url('home'); ?>" class="brand-logo"><h4 class="" style="font-family: BaronFont;margin: 1.192rem 0 .912rem 0;">DREAM</h4></a>
                        </li>
                    </ul>
                    <div class="search-top-bar hide-on-med-and-down">
                        <input type="search" id="search" autocomplete="false" class="autocomplete search-top-bar-input z-depth-2" name="search-state" placeholder="Search">
                        <i class="material-icons zmdi zmdi-search"></i>
                    </div>
                    <ul class="right hide-on-med-and-down">
                        <li>
                            <a class="dropdown-button drop-down-profile relative-item" href="#" data-activates="dropdown3" data-beloworigin="true"><span class="profile-img-ribbon"></span>Hi <?php echo ucwords(substr($loginContainer->userName,0,6)); ?> <?php (strlen($loginContainer->userName)>6)?'..':''; ?><i class="zmdi zmdi-caret-down drop-down-icon"></i></a><ul id="dropdown3" class="create-dropdown dropdown-content">
                                <li><a href="<?php echo $this->url('log-out'); ?>"><i class="material-icons dp48">input</i>Logout</a></li>
                            </ul>
                            
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <aside class="sidebar-left">
        <ul class="side-nav fixed clearfix left" id="nav-mobile" style="transform: translateX(0%);">
            <li>
                <ul class="collapsible" data-collapsible="accordion">
                    <li class="dashboardMenu" class="menuAll">
                         <a href="<?php echo $this->url('home'); ?>" class="collapsible-header dashboardMenu menuAll"><i class="zmdi zmdi-palette zmdi-hc-fw"></i> Dashboard</a>
                    </li>
                    <li id="manageMenu" class="menuAll">
                        <div class="collapsible-header waves-effect manageMenu"><i class="zmdi zmdi-apps zmdi-hc-fw"></i> Manage <i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i></div>
                        <div class="collapsible-body collapsibleAll collapsibleManageMenu" style="">
                            <ul>
                                <?php
                                if($loginContainer->roleCode =='CSC'){
                                ?>
                                    <li class="countryMenu menuAll">
                                        <a class="countryMenu menuAll" href="<?php echo $this->url('country');?>">Countries</a>
                                    </li>
                                <?php } ?>
                                <li class="employeeMenu menuAll">
                                    <a class="employeeMenu menuAll" href="<?php echo $this->url('employee');?>">Employees</a>
                                </li>
                                <?php
                                if($loginContainer->roleCode =='CSC' || $loginContainer->roleCode =='CC' || $loginContainer->roleCode =='LS'){
                                ?>
                                    <li class="facilityMenu menuAll">
                                        <a class="facilityMenu menuAll" href="<?php echo $this->url('facility');?>">Facilities/Labs</a>
                                    </li>
                                    <li class="ancSiteMenu menuAll">
                                        <a class="ancSiteMenu menuAll" href="<?php echo $this->url('anc-site');?>">ANC Sites</a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </div>
                    </li>
                    <li class="dataCollectionMenu" class="menuAll">
                        <a href="<?php echo $this->url('data-collection'); ?>" class="dataCollectionMenu menuAll collapsible-header"><i class="zmdi zmdi-view-list zmdi-hc-fw"></i> Data Collection</a>
                    </li>
                </ul>
            </li>
        </ul>
    </aside>
    <main id="content">
    <?php
      echo $this->content;
    ?>
    </main>
    <footer>
        <div class="row margin">
            <div class="row">
                <div class="col s12 m12 l12">
                    <div class="foot4" style="padding:0;">
                      <p class="copy">©Copyright 2016 Dream - All Rights Reserved</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/materialize.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery.dataTables.min.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/mara.min.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/prism.min.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/deforayValidation.js' ?>"></script>
<script>
    $(function () {
        ol();
        //set active link
        str=$(location).attr('pathname');
        splitsUrl=str.split("/",4);
        //console.log(splitsUrl);
        $(".menuAll").removeClass("active");
        $("#manageMenu").removeClass("active");
        $(".collapsibleAll").css("display","none");
        if(splitsUrl[1]=='role'){
          $("#manageMenu").addClass("active");
          $(".collapsibleManageMenu").css("display","block");
          $(".roleMenu").addClass("active");
        }else if(splitsUrl[1]=='country'){
          $("#manageMenu").addClass("active");
          $(".collapsibleManageMenu").css("display","block");
          $(".countryMenu").addClass("active");
        }else if(splitsUrl[1]=='employee'){
          $("#manageMenu").addClass("active");
          $(".collapsibleManageMenu").css("display","block");
          $(".employeeMenu").addClass("active");
        }else if(splitsUrl[1]=='facility'){
          $("#manageMenu").addClass("active");
          $(".collapsibleManageMenu").css("display","block");
          $(".facilityMenu").addClass("active");
        }else if(splitsUrl[1]=='anc-site'){
          $("#manageMenu").addClass("active");
          $(".collapsibleManageMenu").css("display","block");
          $(".ancSiteMenu").addClass("active");
        }else if(splitsUrl[1]=='data-collection'){
          $(".collapsibleManageMenu").css("display","none");
          $(".dataCollectionMenu").addClass("active");
        }else{
            $(".dashboardMenu").addClass("active");
        }
    });
    
    $(window).load(function() {
        $('.zmdi-search').removeClass('active');
    });
    
    $(document).ready(function(){
        <?php
        if (isset($alertContainer->msg) && $alertContainer->msg != "") {
            ?>
               alert("<?php echo $alertContainer->msg; ?>");
            <?php
            $alertContainer->msg = "";
            unset($alertContainer->msg);
        }
        ?>
            
        $('.material-select').material_select();
    });
</script>
<script>
    $('.button-collapse').sideNav({
        menuWidth: 240, // Default is 240
        edge: 'left', // Choose the horizontal origin
        closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
    });
    $('.collapsible').collapsible();
    $('.drop-down-profile').dropdown({
        inDuration: 300,
        outDuration: 225,
        constrain_width: false, // Does not change width of dropdown to that of the activator
        hover: true, // Activate on hover
        gutter: 0, // Spacing from edge
        belowOrigin: true, // Displays dropdown below the button
        alignment: 'left' // Displays dropdown with edge aligned to the left of button
    });
</script>
</body>
</html>