<?php
use Zend\Session\Container;
$alertContainer = new Container('alert');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="Dream">
    <title>DREAM</title>
    <link rel="shortcut icon" type="image/x-icon" href="">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="<?php echo $this->basePath() .'/assets/css/material-design-iconic-font.css' ?>">
    <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() .'/assets/css/jquery.dataTables.min.css' ?>"  media="screen"/>
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="<?php echo $this->basePath() .'/assets/css/mara.min.css' ?>"  media="screen"/>
    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/css/prism.css' ?>"/>
    <style>
        .wrapper main {
            margin-bottom:0px !important;
        }
    </style>
    <script  src="<?php echo $this->basePath() .'/assets/js/jquery-2.1.1.min.js' ?>"></script>
</head>
<body>
<!--Page load animation-->
<div class="page-loader-container"><div class="dizzy-gillespie"></div></div>
<div class="wrapper vertical-sidebar" id="full-page">
    <header id="header">
        <div class="navbar">
            <nav>
                <a href="#" data-activates="nav-mobile" class="button-collapse top-nav full waves-effect waves-light"><i class="material-icons">menu</i></a>
                <div class="nav-wrapper">
                    <ul class="left">
                        <li>
                            <a href="<?php echo $this->url('home'); ?>" class="brand-logo"><img src="<?php echo $this->basePath() .'/assets/images/logo.png' ?>" alt="MARA"></a>
                        </li>
                    </ul>
                    <div class="search-top-bar hide-on-med-and-down">
                        <input type="search" id="search" autocomplete="false" class="autocomplete search-top-bar-input z-depth-2" name="search-state" placeholder="Search">
                        <i class="material-icons zmdi zmdi-search"></i>
                        
                    <ul class="autocomplete-results hide"><li class="result"><span>Alabama</span></li><li class="result"><span>Alaska</span></li><li class="result"><span>Arizona</span></li><li class="result"><span>Arkansas</span></li><li class="result"><span>California</span></li><li class="result"><span>Colorado</span></li><li class="result"><span>Connecticut</span></li><li class="result"><span>District of Columbia</span></li><li class="result"><span>Delaware</span></li><li class="result"><span>Florida</span></li><li class="result"><span>Georgia</span></li><li class="result"><span>Hawaii</span></li><li class="result"><span>Idaho</span></li><li class="result"><span>Indiana</span></li><li class="result"><span>Iowa</span></li><li class="result"><span>Kansas</span></li><li class="result"><span>Kentucky</span></li><li class="result"><span>Louisiana</span></li><li class="result"><span>Maine</span></li></ul></div>
                    <ul class="right hide-on-med-and-down">
                        <li>
                            <a class="dropdown-button drop-down-profile relative-item" href="#" data-activates="dropdown3" data-beloworigin="true"><span class="profile-img-ribbon"></span><img class="responsive-img profile-img" src="<?php echo $this->basePath() .'/assets/images/user.png' ?>" alt="john"><i class="zmdi zmdi-caret-down drop-down-icon"></i></a><ul id="dropdown3" class="create-dropdown dropdown-content">
                                <li><a href="#"><i class="zmdi zmdi-account-circle"></i>Profile</a></li>
                                <li><a href="<?php echo $this->url('log-out'); ?>"><i class="material-icons dp48">input</i>Logout</a></li>
                            </ul>
                            
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <aside class="sidebar-left">
        <ul class="side-nav fixed clearfix left" id="nav-mobile" style="transform: translateX(0%);">
            <li>
                <ul class="collapsible" data-collapsible="accordion">
                     <li id="dashboardMenu" class="menuAll">
                        <div class="collapsible-header waves-effect">
                            <i class="zmdi zmdi-palette zmdi-hc-fw"></i><a href="<?php echo $this->url('home'); ?>">Dashboard</a>
                        </div>
                     </li>
                    <li id="manageMenu" class="menuAll">
                        <div class="collapsible-header waves-effect"><i class="zmdi zmdi-apps zmdi-hc-fw"></i>Manage <i class="zmdi zmdi-chevron-down"></i><i class="zmdi zmdi-chevron-up"></i></div>
                        <div class="collapsible-body" style="">
                            <ul>
                                <li class="roleMenu menuAll">
                                    <a class="roleMenu menuAll" href="<?php echo $this->url('role');?>">Role</a>
                                </li>
                                <li class="employeeMenu menuAll">
                                    <a class="employeeMenu menuAll" href="#">Employee</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </aside>
    <main id="content">
    <?php
      echo $this->content;
    ?>
    </main>
    <footer>
        <div class="row margin">
            <div class="row">
                <div class="col s12 m12 l12">
                    <p class="copy">©Copyright 2016 Dream - All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/materialize.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery.dataTables.min.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/prism.min.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/mara.min.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/deforayValidation.js' ?>"></script>
<script>
    $(function () {
        ol();
        //set active link
        str=$(location).attr('pathname');
        splitsUrl=str.split("/",4);
        console.log(splitsUrl);
        $(".menuAll").removeClass("active");
        if(splitsUrl[1]=='role'){
          $("#manageMenu").addClass("active");
          $(".roleMenu").addClass("active");
        }else if(splitsUrl[1]=='employee'){
          $("#manageMenu").addClass("active");
          $(".employeeMenu").addClass("active");
        }else{
            $("#dashboardMenu").addClass("active");
        }
    });
    $(document).ready(function(){
        <?php
        if (isset($alertContainer->msg) && $alertContainer->msg != "") {
            ?>
               alert("<?php echo $alertContainer->msg; ?>");
            <?php
            $alertContainer->msg = "";
            unset($alertContainer->msg);
        }
        ?>
            
        $('.material-select').material_select();
        $.curCSS = function (element, attrib, val) {
            $(element).css(attrib, val);
        };
        $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 15, // Creates a dropdown of 15 years to control year
            format: 'dd/mm/yyyy'
        });
    });
</script>
<script>
    $('.button-collapse').sideNav({
        menuWidth: 240, // Default is 240
        edge: 'left', // Choose the horizontal origin
        closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
    });
    $('.collapsible').collapsible();
    $('.notif-btn').dropdown({
        inDuration: 300,
        outDuration: 225,
        constrain_width: false, // Does not change width of dropdown to that of the activator
        hover: true, // Activate on hover
        gutter: 0, // Spacing from edge
        belowOrigin: true, // Displays dropdown below the button
        alignment: 'left' // Displays dropdown with edge aligned to the left of button
    });
    $('.drop-down-profile').dropdown({
        inDuration: 300,
        outDuration: 225,
        constrain_width: false, // Does not change width of dropdown to that of the activator
        hover: true, // Activate on hover
        gutter: 0, // Spacing from edge
        belowOrigin: true, // Displays dropdown below the button
        alignment: 'left' // Displays dropdown with edge aligned to the left of button
    });

    // autocomplete simulation
    var countries = [{value: "Alabama"}, {value: "Alaska"}, { value: "Arizona"}, {value: "Arkansas"}, {value: "California"},
        {value: "Colorado"}, {value: "Connecticut"}, {value: "District of Columbia"}, {value: "Delaware"}, {value: "Florida"},
        {value: "Georgia"}, {value: "Hawaii"}, {value: "Idaho"}, { value: "Indiana"}, {value: "Iowa"}, {value: "Kansas"}, {value: "Kentucky"},
        {value: "Louisiana"}, {value: "Maine"}
    ];
    var input = $('.search-top-bar #search');
    if (input.hasClass('autocomplete')) {
        var inputDiv = input.closest('div');
        var searchHtml = '<ul class="autocomplete-results hide">';
        for (var i = 0; i < countries.length; i++) {
            searchHtml += '<li class="result"><span>' + countries[i]['value'] + '</span></li>';
        }
        searchHtml += '</ul>';
        inputDiv.append(searchHtml);
        input.on('keyup', input, function() {
            var $val = input.val().trim(),
             $select = $('.autocomplete-results');
            $select.css('width',input.width());
            if ($val != '') {
                $select.children('li').addClass('hide');
                $select.children('li').filter(function() {
                    $select.removeClass('hide');
                    var check = true;
                    for (var i in $val) {
                        if ($val[i].toLowerCase() !== $(this).text().toLowerCase()[i])
                            check = false;
                    }
                    return check ? $(this).text().toLowerCase().indexOf($val.toLowerCase()) !== -1 : false;
                }).removeClass('hide');
            } else {
                $select.children('li').addClass('hide');
            }
        });
        $('.result').click(function() {
            input.val($(this).text().trim());
            $('.result').addClass('hide');
        });
        $("#search-hover").click(function(e){
            $("#dropdown2").hide();
            $("#search").trigger("focus");
        });
    }
</script>
<script>
    root();
    $('.button-collapse').sideNav({
        menuWidth: 240, // Default is 240
        edge: typeof ThemeSettings != "undefined" && ThemeSettings.getCookie('reading-direction') == 'rtl' ? 'right' :'left', // Choose the horizontal origin
        closeOnClick: false // Closes side-nav on <a> clicks, useful for Angular/Meteor
    });
    $('.collapsible').collapsible();
</script>
</body>
</html>