<?php
use Zend\Session\Container;
$alertContainer = new Container('alert');
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>BNI Dollars</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link href="<?php echo $this->basePath() . '/assets/css/bootstrap.min.css'?>" rel="stylesheet">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  
  <!-- Theme style -->
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/AdminLTE.min.css' ?>">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/skins/_all-skins.min.css' ?>">
  <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/css/deforayModal.css';?>">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <!-- jQuery 2.2.3 -->
<script src="<?php echo $this->basePath() . '/assets/plugins/jQuery/jquery-2.2.3.min.js' ?>"></script>
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>

</head>
<body class="container">
<?php echo $this->content; ?>
<div id="dDiv" class="dialog"> 
            <div style="text-align:center"><span onclick="closeModal();" style="float:right;clear:both;" class="closeModal"></span></div> 
            <iframe id="dFrame" src="" style="border:none;" scrolling='yes' marginwidth='0' marginheight='0' frameborder='0' vspace='0' hspace='0' >some problem</iframe> 
        </div>
<!-- Bootstrap 3.3.6 -->
<script src="<?php echo $this->basePath() . '/assets/js/bootstrap.min.js'?>"></script>

<!-- AdminLTE App -->
<script src="<?php echo $this->basePath() . '/assets/js/app.min.js' ?>"></script>
<!-- AdminLTE for demo purposes -->
<script src="<?php echo $this->basePath() . '/assets/js/deforayValidation.js'; ?>"></script>

<script src="<?php echo $this->basePath() . '/assets/js/backstretch.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/assets/js/deforayModal.js'; ?>"></script>
<!-- page script -->
<script>
  $(document).ready(function(e) {
    <?php
            if (isset($alertContainer->alertMsg) && $alertContainer->alertMsg != "") {
                ?>
                alert("<?php echo $alertContainer->alertMsg; ?>");
                <?php
                $alertContainer->alertMsg = "";
                unset($alertContainer->alertMsg);
            }
    ?>
    $.backstretch([
        "<?php echo $this->basePath() . '/assets/img/'; ?>all-pages-background.jpg"
    ]);
    
  });
  function showModal(url, w, h) {
            showdefModal('dDiv', w, h);
            document.getElementById('dFrame').style.height = h + 'px';
            document.getElementById('dFrame').style.width = w + 'px';
            document.getElementById('dFrame').src = url;
        }
        function closeModal() {
            document.getElementById('dFrame').src = "";
            hidedefModal('dDiv');
        }
</script>
</body>
</html>
