<?php
use Zend\Session\Container;
$loginContainer = new Container('user');
if(isset($countryId) && trim($countryId)!=''){
    $link = "/user/".base64_encode($countryId);
}else{
    $countryId = '';
    $link = "/user";
}
?>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Add User</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="<?php echo $this->url('user'); ?>" class="breadcrumb">Users</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Add User</a>
        </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="addUserForm" name="addUserForm" method="post" action="<?php echo $this->url('add-user'); ?>">
        <div class="card">
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">person_pin</i>
                        <input id="fullName" name="fullName" type="text" class="validate isRequired" title="Please enter full name">
                        <label for="fullName" class="">Full Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">code</i>
                        <input id="userCode" name="userCode" type="text" class="validate isRequired" title="Please enter user code" onblur="checkNameValidation('user', 'user_code', this, null,'The user code that you entered already exist. Please enter different code.')">
                        <label for="userCode" class="">User Code *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">power_settings_new</i>
                        <input id="userName" name="userName" type="text" class="validate isRequired" title="Please enter user name" onblur="checkNameValidation('user', 'user_name', this, null,'The user name that you entered already exist. Please enter different name.')">
                        <label for="userName" class="">User Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">vpn_key</i>
                        <input id="password" name="password" type="password" class="validate isRequired" title="Please enter password">
                        <label for="password" class="">Password *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">vpn_key</i>
                        <input id="confirmPassword" name="password" type="password" class="validate isRequired confirmPassword" title="Please check that your password and confirm password are same">
                        <label for="password" class="">Confirm Password *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">done</i>
                        <select class="material-select isRequired" id="role" name="role" title="Please select user role" onchange="checkRole(this);">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($roleData as $role){
                                ?>
                                <option value="<?php echo base64_encode($role['role_id']);?>"><?php echo ucwords($role['role_name']);?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <label for="role" class="">User Role *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">email</i>
                        <input id="email" name="email" type="text" class="validate isEmail isRequired" title="Please enter email-id" onblur="checkNameValidation('user', 'email', this, null,'The user email that you entered already exist. Please enter different email id.')">
                        <label for="email" class="">Email *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="mobile" name="mobile" type="text" class="validate isRequired" title="Please enter contact number" onblur="checkNameValidation('user', 'mobile', this, null,'The user mobile no. that you entered already exist. Please enter different mobile no');">
                        <label for="mobile" class="">Contact Number *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="altContact" name="altContact" type="text" class="validate" title="Please enter contact number">
                        <label for="altContact" class="">Alternate Contact</label>
                    </div>
                </div>
                <?php
                if(trim($countryId) > 0){
                ?>
                    <div class="col s6" id="countrySingle">
                        <div class="input-field col m10 s10">
                            <i class="material-icons prefix">room</i>
                            <select class="material-select country" id="country" name="country[]" title="Please select country">
                                <option value=""> -- Select -- </option>
                                <?php
                                foreach($countries as $country){
                                    ?>
                                    <option value="<?php echo base64_encode($country['country_id']);?>" <?php echo($countryId ==$country['country_id'])?'selected="selected"':''; ?>><?php echo ucwords($country['country_name']);?></option>
                                    <?php
                                }
                                ?>
                            </select>
                            <label for="country" class="">Country *</label>
                        </div>
                    </div>
                    <div class="col s6" id="countryMultiple" style="display:none;">
                        <div class="input-field col m10 s10">
                            <i class="material-icons prefix">room</i>
                            <select class="material-select countryMulti" id="countryMulti" name="country[]" multiple="multiple" title="Please select country">
                                <?php
                                foreach($countries as $country){
                                    ?>
                                    <option value="<?php echo base64_encode($country['country_id']);?>" <?php echo($countryId ==$country['country_id'])?'selected="selected"':''; ?>><?php echo ucwords($country['country_name']);?></option>
                                    <?php
                                }
                                ?>
                            </select>
                            <label for="country" class="">Country *</label>
                        </div>
                    </div>
                <?php } ?>
            </div>
            <div class="col s12">
                <input type="hidden" name="chosenCountryId" value="<?php echo $link; ?>"/>
                <a href="<?php echo $link; ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addUser();">ADD</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script>
    duplicateName = true;
    function addUser(){
        flag = deforayValidator.init({
               formId: 'addUserForm'
        });
        
        if(flag){
            if(duplicateName){
            if($('#country').length  >0 || $('#countryMulti').length >0){
                var country = $("#country").val();
                var countryMulti = $("#countryMulti").val();
                if((country=='' || country==null) && (countryMulti=='' || countryMulti==null)){
                    alert("Please choose country");
                    return false;
                }
            }
            document.getElementById('addUserForm').submit();
        }
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if(checkValue!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
    
    function checkRole(obj){
        if(atob(obj.value)=='2'){
            $("#country").val('');
            $("#countrySingle").hide();
            $("#countryMultiple").show();
        }else{
            $("#countryMulti").val('');
            $("#countryMultiple").hide();
            $("#countrySingle").show();
        }
    }
</script>