<?php
if(trim($countryId)!=''){
    $link = "/user/".base64_encode($countryId);
}else{
    $link = "/user";
}
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/css/multiple-select.css' ?>"/>
<style>
    div.ms-drop ul li label{
	font-size:13px !important;
    }
    div.ms-drop ul li label input[type=checkbox]{
	position:static !important;
	opacity:1 !important;
	margin-right: 4px !important;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Add User</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="<?php echo $this->url('user'); ?>" class="breadcrumb">Users</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Add User</a>
        </div>
    </div>
    <div class="row content-container" style="padding: 0 20px;">
        <form id="addUserForm" name="addUserForm" method="post" action="<?php echo $this->url('add-user'); ?>">
        <div class="card">
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">person_pin</i>
                        <input id="fullName" name="fullName" type="text" class="validate isRequired" title="Please enter full name">
                        <label for="fullName" class="">Full Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">power_settings_new</i>
                        <input id="userName" name="userName" type="text" class="validate isRequired" title="Please enter user name" onblur="checkNameValidation('user', 'user_name', this, null,'The user name that you entered already exist. Please enter different name')">
                        <label for="userName" class="">User Name *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">vpn_key</i>
                        <input id="password" name="password" type="password" class="validate isRequired" title="Please enter password">
                        <label for="password" class="">Password *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">vpn_key</i>
                        <input id="confirmPassword" name="password" type="password" class="validate isRequired confirmPassword" title="Please check that your password and confirm password are same">
                        <label for="password" class="">Confirm Password *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">done</i>
                        <select class="material-select isRequired" id="role" name="role" title="Please select user role" onchange="checkUserRole(this.value);">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($roleData as $role){
                                ?>
                                <option value="<?php echo base64_encode($role['role_id']);?>"><?php echo ucwords($role['role_name']);?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <label for="role" class="">User Role *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">email</i>
                        <input id="email" name="email" type="text" class="validate isEmail isRequired" title="Please enter email-id" onblur="checkNameValidation('user', 'email', this, null,'The email id that you entered already exist. Please enter different email id')">
                        <label for="email" class="">Email *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="mobile" name="mobile" type="text" class="validate checkNum isNumeric isRequired" title="Please enter contact number">
                        <label for="mobile" class="">Contact Number *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="altContact" name="altContact" type="text" class="validate checkNum isNumeric" title="Please enter alternate contact number">
                        <label for="altContact" class="">Alternate Contact</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-padding col m10 s10">
                        Has View Only Access ? *<br>
                        <input id="hasViewOnlyAccessYes" class="with-gap isRequired" name="hasViewOnlyAccess" value="yes" type="radio">
                        <label for="hasViewOnlyAccessYes">Yes </label>&nbsp;
                        <input id="hasViewOnlyAccessYesNo" class="with-gap isRequired" name="hasViewOnlyAccess" value="no" type="radio" checked>
                        <label for="hasViewOnlyAccessYesNo">No </label>
		    </div>
                </div>
                <?php
                if($countryId >0){
                ?>
                    <div class="col s6" id="countrySingle">
                        <div class="input-field col m10 s10">
                            <i class="material-icons prefix">room</i>
                            <select class="material-select country" id="country" name="country[]" title="Please select country">
                                <option value=""> -- Select -- </option>
                                <?php
                                foreach($countries as $country){
                                    ?>
                                    <option value="<?php echo base64_encode($country['country_id']);?>" <?php echo($countryId == $country['country_id'])?'selected="selected"':''; ?>><?php echo ucwords($country['country_name']);?></option>
                                    <?php
                                }
                                ?>
                            </select>
                            <label for="country" class="">Country *</label>
                        </div>
                    </div>
                    <div class="col s6" id="countryMultiple" style="display:none;">
                        <div class="input-field col m10 s10">
                            <i class="material-icons prefix">room</i>
                            <select class="material-select countryMulti" id="countryMulti" name="countryMulti[]" multiple="multiple" title="Please select country">
                                <option value="" selected="selected" disabled> -- Select -- </option>
                                <?php
                                foreach($allCountries as $allCountry){
                                    ?>
                                    <option value="<?php echo base64_encode($allCountry['country_id']);?>" <?php echo($countryId == $allCountry['country_id'])?'selected="selected"':''; ?>><?php echo ucwords($allCountry['country_name']);?></option>
                                    <?php
                                }
                                ?>
                            </select>
                            <label for="countryMulti" class="">Country *</label>
                        </div>
                    </div>
                <?php } else { ?>
                    <div class="col s6">
                        <div class="input-field col m10 s10">
                            <textarea id="comments" name="comments" class="materialize-textarea"></textarea>
                            <label for="comments">Comments</label>
                        </div>
                    </div>
                <?php } ?>
            </div>
            <div class="row clinicanSection" style="display:none;padding-bottom:20px;">
                <div class="col s6">
                    <div class="input-padding col m10 s10">
                        Has Data Reporting Access ? *<br>
                        <input id="hasDataReportingAccessYes" class="with-gap isRequired" name="hasDataReportingAccess" value="yes" type="radio">
                        <label for="hasDataReportingAccessYes">Yes </label>&nbsp;
                        <input id="hasDataReportingAccessNo" class="with-gap isRequired" name="hasDataReportingAccess" value="no" type="radio" checked>
                        <label for="hasDataReportingAccessNo">No </label>
		    </div>
                </div>
                <div class="col s6">
                    <div class="input-padding col m10 s10">
                        Has Print Report Access ? *<br>
                        <input id="hasPrintReportAccessYes" class="with-gap isRequired" name="hasPrintReportAccess" value="yes" type="radio">
                        <label for="hasPrintReportAccessYes">Yes </label>&nbsp;
                        <input id="hasPrintReportAccessNo" class="with-gap isRequired" name="hasPrintReportAccess" value="no" type="radio" checked>
                        <label for="hasPrintReportAccessNo">No </label>
		    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6 clinicanSection" style="display:none;">
		    <div class="col m10 s10">
		    <span>ANC site name *</span>
		    <select id="ancSite" name="ancSite[]" multiple title="Please select ANC site">
			<?php
			foreach($ancSites as $anc){
			    ?>
			    <option value="<?php echo base64_encode($anc['anc_site_id']);?>"><?php echo ucwords($anc['anc_site_name']);?></option>
			    <?php
			}
			?>
		    </select>
		    </div>
                </div>
                <div class="col s6 supervisorDeoSection" style="display:none;">
                    <div class="col m10 s10">
                        <span>Lab site name *</span>
                        <select id="lab" name="lab[]" multiple title="Please select lab site name">
                            <?php
                            foreach($facilities as $facility){
                                ?>
                                <option value="<?php echo base64_encode($facility['facility_id']);?>"><?php echo ucwords($facility['facility_name']);?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>
                </div>
                <?php
                if($countryId > 0){
                ?>
                    <div class="col s6">
                        <div class="input-field col m10 s10">
                            <textarea id="comments" name="comments" class="materialize-textarea"></textarea>
                            <label for="comments">Comments</label>
                        </div>
                    </div>
                <?php } ?>
            </div>
            <div class="col s12">
                <input type="hidden" name="redirectUrl" value="<?php echo $link; ?>"/>
                <a href="<?php echo $link; ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addUser();">ADD</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/multiple-select.js' ?>"></script>
<script>
    $(document).ready(function() {
	$("#ancSite").multipleSelect({
	    placeholder: "Select ANC",
	    width: '100%',
            filter: true
        });
	$("#lab").multipleSelect({
	    placeholder: "Select Lab",
	    width: '100%',
            filter: true
        });
    });
    
    duplicateName = true;
    function addUser(){
        flag = deforayValidator.init({
            formId: 'addUserForm'
        });
        
        if(flag){
            if(duplicateName){
                var role = $('#role').val();
                if($('#country').length  > 0 || $('#countryMulti').length > 0){
                    if(base64_decode(role) == 3 || base64_decode(role) == 4 || base64_decode(role) == 5){
                       var country = $("#country").val(); 
                    }else if(base64_decode(role) == 2) {
                       var country = $("#countryMulti").val();
                    }
                    if((country == null || $.trim(country) == '')){
                        alert("Please choose country");
                        return false;
                    }
                }
                if(base64_decode(role) == 3 || base64_decode(role) == 4){
                   if($('#lab').val() == null){ alert("Please select lab site name"); return false; }
                }else if(base64_decode(role) == 5){
                   if($('#ancSite').val() == null){ alert("Please select ANC site"); return false; }
                }
              document.getElementById('addUserForm').submit();
            }
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if($.trim(checkValue)!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
    
    function checkUserRole(val){
        if(atob(val)=='2'){
            $("#country").val('');
            $("#countrySingle").hide();
            $("#countryMultiple").show();
        }else{
            $("#countryMulti").val('');
            $("#countryMultiple").hide();
            $("#countrySingle").show();
        }
    }
    
    $('#role').on('change',function(e){
       var role = $('#role').val();
       if(base64_decode(role) == 3 || base64_decode(role) == 4){
          $('.clinicanSection').hide();
          $('.supervisorDeoSection').show();
       }else if(base64_decode(role)== 5){
          $('.supervisorDeoSection').hide();
          $('.clinicanSection').show();
       }else{
         $('.clinicanSection').hide();
         $('.supervisorDeoSection').hide();
       }
    });
</script>