<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Change Password</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">My Account</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Change Password</a>
        </div>
    </div>
    <div class="row content-container">
        <form id="changePasswordForm" name="changePasswordForm" method="post" action="<?php echo $this->url('change-password'); ?>">
            <p style="text-align:center;">Update your password by providing your current password and choosing a new password</p>
            <div class="valign-wrapper">
                <div class="row">
                    <div class="col m12 s12">
                        <div class="input-field col m12 s12">
                            <input id="currentPassword" name="currentPassword" type="password" class="validate isRequired" title="Please enter your password">
                            <label for="currentPassword" class="">Current Password *</label>
                        </div>
                    </div>
                    <div class="col m12 s12">
                        <div class="input-field col m12 s12">
                            <input id="newPassword" name="newPassword" type="password" class="validate isRequired" title="Please enter new password" readonly>
                            <label for="newPassword" class="">New Password *</label>
                        </div>
                    </div>
                    <div class="col m12 s12" style="text-align:center;">
                      <a class="waves-effect waves-ripple white black-text btn text-bold" href="javascript:void(0);" onclick="changeAccountPassword();">Change </a>
                    </div>
                    <div class="col m12 s12" style="font-size:13px;">
                        <span style="font-weight:800;text-decoration:underline;">Password guidelines</span><br>When choosing password, consider the following:<ol style="margin-top:6px;"><li>Password must contain at least eight (8)characters</li><li>One or more of each of the following<ul style="padding-left:2%;"><li style="list-style:circle;">number (0 through 9)</li><li style="list-style:circle;">special character (such as !, $, #, %)</li><li style="list-style:circle;">alphabet (A through Z (or) a through z)</li></li></ul></ol>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $('#currentPassword').change('input',function(e){
        if ($(this).val()!= '') {
            $.post("<?php echo $this->url('check-account-password'); ?>", {password: $(this).val()},
            function(data) {
                if(data == "undefined" || data == null || data == "" || data == 0){
                    alert('Invalid password');
                    $('#currentPassword').val('');
                    $('#currentPassword').css('border-bottom','1px solid #ec407a');
                    $('#currentPassword').css('box-shadow','0 1px 0 0 #ec407a');
                    $('#newPassword').attr('readonly',true);
                }else{
                    $('#currentPassword').css('border-bottom','1px solid #4CAF50');
                    $('#currentPassword').css('box-shadow','0 1px 0 0 #4CAF50');
                    $('#newPassword').attr('readonly',false);
                    $('#newPassword').focus();
                }
            });
        }
    });
    
    $('#newPassword').change('input',function(e){
        if ($(this).val()!= '' && $(this).val() == $('#currentPassword').val()) {
            alert('New password can not be same as old password');
            $('#newPassword').val('');
            $('#newPassword').css('border-bottom','1px solid #ec407a');
            $('#newPassword').css('box-shadow','0 1px 0 0 #ec407a');
        }
    });
    
    function changeAccountPassword(){
        flag = deforayValidator.init({
            formId: 'changePasswordForm'
        });
        
        if(flag){
            document.getElementById('changePasswordForm').submit();
        }
    }
</script>