<?php
$config = new \Zend\Config\Reader\Ini();
$configResult = $config->fromFile(CONFIG_PATH . '/custom.config.ini');
?>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Change Password</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">My Account</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Change Password</a>
        </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="changePasswordForm" name="changePasswordForm" method="post" action="<?php echo $this->url('change-password'); ?>">
            <p style="text-align:center;">Easily update your password by providing your current password and choosing a new password.</p>
            <div class="valign-wrapper">
                <div class="row">
                    <div class="col s10">
                        <div class="input-field col m12 s12">
                            <input id="currentPassword" name="currentPassword" type="password" class="validate isRequired" data-pwd="<?php echo $row[0]['password']; ?>" title="Please enter your password">
                            <label for="currentPassword" class="">Password *</label>
                        </div>
                    </div>
                    <div class="col s10">
                        <div class="input-field col m12 s12">
                            <input id="newPassword" name="newPassword" type="password" class="validate isRequired" title="Please enter new password">
                            <label for="newPassword" class="">New Password *</label>
                        </div>
                    </div>
                    <div class="col s10" style="text-align:center;">
                      <a class="waves-effect waves-ripple white black-text btn text-bold" href="javascript:void(0);" onclick="changeAccountPassword();">Change </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $('#currentPassword').change('input',function(e){
        if ($(this).val()!= '') {
            if($(this).data('pwd') == $().crypt({method:"sha1",source:$(this).val()+'<?php echo $configResult["password"]["salt"]; ?>'})){
                $('#currentPassword').attr('readonly',true);
                $('#currentPassword').css('border','none');
                $('#currentPassword').css('box-shadow','none');
                $('#newPassword').focus();
            }else{
                alert('Please enter the correct password..');
                $('#currentPassword').val('');
                //location.reload();
            }
        }
    });
    
    function changeAccountPassword(){
        flag = deforayValidator.init({
            formId: 'changePasswordForm'
        });
        
        if(flag){
            document.getElementById('changePasswordForm').submit();
        }
    }
</script>