<?php
if(isset($countryId) && trim($countryId)!=''){
    $link = "/user/".base64_encode($countryId);
}else{
    $link = "/user";
}
$userCountry = '';
$userCountryList = array();
if(count($row['userCountries'])>0){
    if($row->role!= 2){
        $userCountry = $row['userCountries'][0]['country_id'];
    }else{
        foreach($row['userCountries'] as $userCountries){
            $userCountryList[] = $userCountries['country_id'];
        }
    }
}
$ancList = array();
if(count($row['userClinics'])>0){
    foreach($row['userClinics'] as $userClinic){
        $ancList[] = $userClinic['clinic_id'];
    }
}
$laboratoryList = array();
if(count($row['userLaboratories'])>0){
    foreach($row['userLaboratories'] as $userlaboratory){
        $laboratoryList[] = $userlaboratory['laboratory_id'];
    }
}
?>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Edit User</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="<?php echo $link; ?>" class="breadcrumb">Users</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Edit User</a>
        </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="editUserForm" name="editUserForm" method="post" action="<?php echo $this->url('edit-user'); ?>">
        <div class="card">
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">person_pin</i>
                        <input id="fullName" name="fullName" type="text" class="validate isRequired" title="Please enter full name" value="<?php echo $row->full_name;?>">
                        <label for="fullName" class="">Full Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">power_settings_new</i>
                        <input id="userName" name="userName" type="text" class="validate isRequired" title="Please enter user name" value="<?php echo $row->user_name;?>" onblur="checkNameValidation('user', 'user_name', this, '<?php echo "user_id##" .$row->user_id; ?>','The user name that you entered already exist. Please enter different name')">
                        <label for="userName" class="">User Name *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">vpn_key</i>
                        <input id="password" name="password" type="password" class="validate" title="Please enter password">
                        <label for="password" class="">Password </label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">vpn_key</i>
                        <input id="confirmPassword" name="password" type="password" class="validate confirmPassword" title="Please check that your password and confirm password are same">
                        <label for="password" class="">Confirm Password </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">done</i>
                        <select class="material-select isRequired" id="role" name="role" title="Please select user role" onchange="checkUserRole(this.value);">
                            <option value="">-- Select --</option>
                            <?php
                            foreach($roleData as $role){
                                ?>
                                <option value="<?php echo base64_encode($role['role_id']);?>"<?php echo ($row->role == $role['role_id']) ? " selected='selected'" : ""; ?>><?php echo ucwords($role['role_name']);?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <label for="role" class="">User Role *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">email</i>
                        <input id="email" name="email" type="text" class="validate isEmail isRequired" title="Please enter email-id" value="<?php echo $row->email;?>" onblur="checkNameValidation('user', 'email', this, '<?php echo "user_id##" .$row->user_id; ?>','The email id that you entered already exist. Please enter different email id')">
                        <label for="email" class="">Email *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="mobile" name="mobile" type="text" class="validate checkNum isNumeric isRequired" title="Please enter contact number" value="<?php echo $row->mobile;?>" onblur="checkNameValidation('user', 'mobile', this, '<?php echo "user_id##" .$row->user_id; ?>','The mobile/phone no. that you entered already exist. Please enter different mobile/phone no.')">
                        <label for="mobile" class="">Contact Number *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="altContact" name="altContact" type="text" class="validate checkNum isNumeric" title="Please enter alternate contact number" value="<?php echo $row->alt_contact;?>">
                        <label for="altContact" class="">Alternate Contact</label>
                    </div>
                </div>
            </div>
            <?php if($countryId >0){ ?>
                <div class="row">
                    <div class="col s6">
                        <div class="input-padding col m10 s10">
                            Has View Only Access ? *<br>
                            <input id="hasViewOnlyAccessYes" class="with-gap isRequired" name="hasViewOnlyAccess" value="yes" type="radio" <?php echo ($row->has_view_only_access == 'yes') ? " checked='checked'" : ""; ?>>
                            <label for="hasViewOnlyAccessYes">Yes </label>&nbsp;
                            <input id="hasViewOnlyAccessYesNo" class="with-gap isRequired" name="hasViewOnlyAccess" value="no" type="radio" <?php echo ($row->has_view_only_access == 'no') ? " checked='checked'" : ""; ?>>
                            <label for="hasViewOnlyAccessYesNo">No </label>
                        </div>
                    </div>
                    <div class="col s6" id="countrySingle">
                        <div class="input-field col m10 s10">
                            <i class="material-icons prefix">room</i>
                            <select class="material-select country" id="country" name="country[]" title="Please select country">
                                <option value=""> -- Select -- </option>
                                <?php
                                foreach($countries as $country){
                                    ?>
                                    <option value="<?php echo base64_encode($country['country_id']);?>" <?php echo ($country['country_id'] == $userCountry)? "selected=selected" : ""; ?>><?php echo ucwords($country['country_name']);?></option>
                                    <?php
                                }
                                ?>
                            </select>
                            <label for="country" class="">Country *</label>
                        </div>
                    </div>
                    <div class="col s6" id="countryMultiple">
                        <div class="input-field col m10 s10">
                            <i class="material-icons prefix">room</i>
                            <select class="material-select countryMulti" id="countryMulti" name="countryMulti[]" multiple="multiple" title="Please select country" >
                                <?php
                                foreach($allCountries as $allCountry){
                                    ?>
                                    <option value="<?php echo base64_encode($allCountry['country_id']);?>" <?php echo in_array($allCountry['country_id'], $userCountryList) ? "selected=selected" : ""; ?>><?php echo ucwords($allCountry['country_name']);?></option>
                                    <?php
                                }
                                ?>
                            </select>
                            <label for="countryMulti" class="">Country *</label>
                        </div>
                    </div>
                </div>
                <div class="row clinicanSection" style="<?php echo($row->role == 5)?'':'display:none;'; ?>">
                    <div class="col s6">
                        <div class="input-padding col m10 s10">
                            Has Data Reporting Access ? *<br>
                            <input id="hasDataReportingAccessYes" class="with-gap isRequired" name="hasDataReportingAccess" value="yes" type="radio" <?php echo(isset($row->has_data_reporting_access) && $row->has_data_reporting_access == 'yes')?'checked="checked"':''; ?>>
                            <label for="hasDataReportingAccessYes">Yes </label>&nbsp;
                            <input id="hasDataReportingAccessNo" class="with-gap isRequired" name="hasDataReportingAccess" value="no" type="radio" <?php echo(isset($row->has_data_reporting_access) && $row->has_data_reporting_access == 'no')?'checked="checked"':''; ?> <?php echo($row->has_data_reporting_access == '' || $row->has_data_reporting_access == NULL)?'checked="checked"':''; ?>>
                            <label for="hasDataReportingAccessNo">No </label>
                        </div>
                    </div>
                    <div class="col s6">
                        <div class="input-padding col m10 s10">
                            Has Print Report Access ? *<br>
                            <input id="hasPrintReportAccessYes" class="with-gap isRequired" name="hasPrintReportAccess" value="yes" type="radio" <?php echo(isset($row->has_print_report_access) && $row->has_print_report_access == 'yes')?'checked="checked"':''; ?>>
                            <label for="hasPrintReportAccessYes">Yes </label>&nbsp;
                            <input id="hasPrintReportAccessNo" class="with-gap isRequired" name="hasPrintReportAccess" value="no" type="radio" <?php echo(isset($row->has_print_report_access) && $row->has_print_report_access == 'no')?'checked="checked"':''; ?> <?php echo($row->has_print_report_access == '' || $row->has_print_report_access == NULL)?'checked="checked"':''; ?>>
                            <label for="hasPrintReportAccessNo">No </label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col s6 clinicanSection" style="<?php echo($row->role == 5)?'':'display:none;'; ?>">
                        <div class="input-field col m10 s10">
                            <i class="material-icons prefix">done</i>
                            <select class="material-select <?php echo($row->role == 5)?'isRequired':''; ?>" id="ancSite" name="ancSite[]" multiple title="Please select ANC site">
                                <?php
                                foreach($ancSites as $anc){
                                    ?>
                                    <option value="<?php echo base64_encode($anc['anc_site_id']);?>" <?php echo in_array($anc['anc_site_id'], $ancList) ? "selected=selected" : ""; ?>><?php echo ucwords($anc['anc_site_name']);?></option>
                                    <?php
                                }
                                ?>
                            </select>
                            <label for="ancSite" class="">ANC site name *</label>
                        </div>
                    </div>
                    <div class="col s6 supervisorDeoSection" style="<?php echo($row->role == 3 || $row->role == 4)?'':'display:none;'; ?>">
                        <div class="input-field col m10 s10">
                            <i class="material-icons prefix">done</i>
                            <select class="material-select <?php echo($row->role == 3 || $row->role == 4)?'isRequired':''; ?>" id="lab" name="lab[]" multiple title="Please select lab site name">
                                <?php
                                foreach($facilities as $facility){
                                    ?>
                                    <option value="<?php echo base64_encode($facility['facility_id']);?>" <?php echo in_array($facility['facility_id'], $laboratoryList) ? "selected=selected" : ""; ?>><?php echo ucwords($facility['facility_name']);?></option>
                                    <?php
                                }
                                ?>
                            </select>
                            <label for="lab" class="">Lab site name *</label>
                        </div>
                    </div>
                    <div class="col s6">
                        <div class="input-field col m10 s10">
                            <i class="material-icons prefix">done</i>
                            <select class="material-select" id="status" name="status" title="Please select user status">
                                <option value="active" <?php echo ($row->status == 'active') ? " selected='selected'" : ""; ?>>Active</option>
                                <option value="inactive" <?php echo ($row->status == 'inactive') ? " selected='selected'" : ""; ?>>Inactive</option>
                            </select>
                            <label for="status" class="">User Status *</label>
                        </div>
                    </div>
                    <div class="col s6">
                        <div class="input-field col m10 s10">
                            <textarea id="comments" name="comments" class="materialize-textarea"><?php echo $row->comments; ?></textarea>
                            <label for="comments">Comments</label>
                        </div>
                    </div>
                </div>
            <?php } else { ?>
                <div class="row">
                    <div class="col s6">
                        <div class="input-padding col m10 s10">
                            Has View Only Access ? *<br>
                            <input id="hasViewOnlyAccessYes" class="with-gap isRequired" name="hasViewOnlyAccess" value="yes" type="radio" <?php echo ($row->has_view_only_access == 'yes') ? " checked='checked'" : ""; ?>>
                            <label for="hasViewOnlyAccessYes">Yes </label>&nbsp;
                            <input id="hasViewOnlyAccessYesNo" class="with-gap isRequired" name="hasViewOnlyAccess" value="no" type="radio" <?php echo ($row->has_view_only_access == 'no') ? " checked='checked'" : ""; ?>>
                            <label for="hasViewOnlyAccessYesNo">No </label>
                        </div>
                    </div>
                    <div class="col s6">
                        <div class="input-field col m10 s10">
                            <i class="material-icons prefix">done</i>
                            <select class="material-select" id="status" name="status" title="Please select user status">
                                <option value="active" <?php echo ($row->status == 'active') ? " selected='selected'" : ""; ?>>Active</option>
                                <option value="inactive" <?php echo ($row->status == 'inactive') ? " selected='selected'" : ""; ?>>Inactive</option>
                            </select>
                            <label for="status" class="">User Status *</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col s6">
                        <div class="input-field col m10 s10">
                            <textarea id="comments" name="comments" class="materialize-textarea"><?php echo $row->comments; ?></textarea>
                            <label for="comments">Comments</label>
                        </div>
                    </div>
                </div>
            <?php } ?>
            <div class="col s12">
                <input type="hidden" name="redirectUrl" value="<?php echo $link; ?>"/>
                <input id="userId" name="userId" type="hidden" value="<?php echo base64_encode($row->user_id);?>"/>
                <a href="<?php echo $link; ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" onclick="editUser();" class="waves-effect waves-light btn-small white-text pink margin-bottom-10">UPDATE</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script>
    duplicateName = true;
    function editUser(){
        flag = deforayValidator.init({
            formId: 'editUserForm'
        });
        
        if(flag){
            if(duplicateName){
                if($('#country').length  >0 || $('#countryMulti').length >0){
                    var role = $('#role').val();
                    if(base64_decode(role) == 3 || base64_decode(role) == 4 || base64_decode(role) == 5){
                       country = $("#country").val(); 
                    }else if(base64_decode(role) == 2) {
                       country = $("#countryMulti").val();
                    }
                    if((country == null || $.trim(country) == '')){
                        alert("Please choose country");
                        return false;
                    }
                }
              document.getElementById('editUserForm').submit();
            }
        }
    }
    
    $(document).ready(function() {
        checkUserRole('<?php echo base64_encode($row->role);?>');
    });
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if($.trim(checkValue)!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
    
    function checkUserRole(val){
        if(atob(val)=='2'){
            $("#country").val('');
            $("#countrySingle").hide();
            $("#countryMultiple").show();
        }else{
            //$("#countryMulti").val('');
            $("#countryMultiple").hide();
            $("#countrySingle").show();
        }
    }
    
    $('#role').on('change',function(e){
       var role = $('#role').val();
       if(base64_decode(role)== 3 || base64_decode(role)== 4){
          $('.clinicanSection').hide();
          $('#ancSite').removeClass('isRequired');
          $('.supervisorDeoSection').show();
          if($('#lab').val() == null || $('#lab').val() == ''){ $('#editUserForm .supervisorDeoSection .select-dropdown').val(''); }
          $('#lab').addClass('isRequired');
       }else if(base64_decode(role)== 5){
          $('.supervisorDeoSection').hide();
          $('#lab').removeClass('isRequired');
          $('.clinicanSection').show();
          if($('#ancSite').val() == null || $('#ancSite').val() == ''){ $('#editUserForm .clinicanSection .select-dropdown').val(''); }
          $('#ancSite').addClass('isRequired');
       }else{
         $('.clinicanSection').hide();
         $('.supervisorDeoSection').hide();
         $('#ancSite').removeClass('isRequired');
         $('#lab').removeClass('isRequired');
       }
    });
</script>