<?php
$country = array();
foreach($row['country'] as $countryListId){
    $countryList[] = $countryListId['country_id'];
}
$row = $row[0];
?>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Edit User</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="<?php echo $this->url('user'); ?>" class="breadcrumb">Users</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Edit User</a>
        </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="editUserForm" name="editUserForm" method="post" action="<?php echo $this->url('edit-user'); ?>">
        <div class="card">
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">person_pin</i>
                        <input id="fullName" name="fullName" type="text" class="validate isRequired" title="Please enter full name" value="<?php echo $row->full_name;?>">
                        <label for="fullName" class="">Full Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">code</i>
                        <input id="userCode" name="userCode" type="text" class="validate isRequired" title="Please enter user code" value="<?php echo $row->user_code;?>" onblur="checkNameValidation('user', 'user_code', this, '<?php echo "user_id##" .$row->user_id; ?>','The user code that you entered already exist. Please enter different code.')">
                        <label for="userCode" class="">User Code *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">power_settings_new</i>
                        <input id="userName" name="userName" type="text" class="validate isRequired" title="Please enter user name" value="<?php echo $row->user_name;?>" onblur="checkNameValidation('user', 'user_name', this, '<?php echo "user_id##" .$row->user_id; ?>','The user name that you entered already exist. Please enter different name.')">
                        <label for="userName" class="">User Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">vpn_key</i>
                        <input id="password" name="password" type="password" class="validate" title="Please enter password">
                        <label for="password" class="">Password *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">vpn_key</i>
                        <input id="confirmPassword" name="password" type="password" class="validate confirmPassword" title="Please check that your password and confirm password are same">
                        <label for="password" class="">Confirm Password *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">done</i>
                        <select class="material-select isRequired" id="role" name="role" title="Please select user role" onchange="showMultipleCountry(this.value);">
                            <option value="">-- Select --</option>
                            <?php
                            foreach($roleData as $role){
                                ?>
                                <option value="<?php echo base64_encode($role['role_id']);?>"<?php echo ($row->role == $role['role_id']) ? " selected='selected'" : ""; ?>><?php echo ucwords($role['role_name']);?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <label for="role" class="">User Role *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">email</i>
                        <input id="email" name="email" type="text" class="validate isEmail isRequired" title="Please enter email-id" value="<?php echo $row->email;?>" onblur="checkNameValidation('user', 'email', this, '<?php echo "user_id##" .$row->user_id; ?>','The user email that you entered already exist. Please enter different email.')">
                        <label for="email" class="">Email *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="mobile" name="mobile" type="text" class="validate isRequired" title="Please enter contact number" value="<?php echo $row->mobile;?>" onblur="checkNameValidation('user', 'mobile', this, '<?php echo "user_id##" .$row->user_id; ?>','The user mobile no. that you entered already exist. Please enter different mobile no.')">
                        <label for="mobile" class="">Contact Number *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="altContact" name="altContact" type="text" class="validate" title="Please enter contact number" value="<?php echo $row->alt_contact;?>">
                        <label for="altContact" class="">Alternate Contact</label>
                    </div>
                </div>
                <div class="col s6" id="countryData">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">room</i>
                        <select class="material-select country" id="country" name="country[]" title="Please select country">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($countries as $country){
                                ?>
                                <option value="<?php echo base64_encode($country['country_id']);?>" <?php echo in_array($country['country_id'], $countryList) ? "selected=selected" : ""; ?>><?php echo ucwords($country['country_name']);?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <label for="country" class="">Country *</label>
                    </div>
                </div>
                 <div class="col s6" id="countryData1" style="display:none;">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">room</i>
                        <select class="material-select country1" id="country1" name="country[]" multiple="multiple" title="Please select country" >
                            <?php
                            foreach($countries as $country){
                                ?>
                                <option value="<?php echo base64_encode($country['country_id']);?>" <?php echo in_array($country['country_id'], $countryList) ? "selected=selected" : ""; ?>><?php echo ucwords($country['country_name']);?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <label for="country" class="">Country *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">done</i>
                        <select class="material-select" id="status" name="status" title="Please select user status">
                            <option value="active" <?php echo ($row->status == 'active') ? " selected='selected'" : ""; ?>>Active</option>
                            <option value="inactive" <?php echo ($row->status == 'inactive') ? " selected='selected'" : ""; ?>>Inactive</option>
                        </select>
                        <label for="status" class="">User Status *</label>
                    </div>
                </div>
            </div>
            <div class="col s12">
                <?php
                if($countryId!='')
                {
                    $link = "/user/".base64_encode($countryId);
                }else{
                    $link = "/user";
                }
                ?>
                <input type="hidden" name="chosenCountryId" value="<?php echo $link; ?>"/>
                <input id="userId" name="userId" type="hidden" value="<?php echo base64_encode($row->user_id);?>"/>
                <a href="<?php echo $link; ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" onclick="editUser();" class="waves-effect waves-light btn-small white-text pink margin-bottom-10">UPDATE</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script>
    duplicateName = true;
    function editUser(){
        flag = deforayValidator.init({
               formId: 'editUserForm'
        });
        
        if(flag){
            if(duplicateName){
            var cntry = $("#country").val();
            var cntry1 = $("#country1").val();
            if((cntry=='' || cntry==null) && (cntry1=='' || cntry1==null))
            {
                alert("Please Choose country.");
                return false;
            }
            document.getElementById('editUserForm').submit();
        }
        }
    }
    $(document).ready(function() {
        showMultipleCountry('<?php echo base64_encode($row->role);?>');
    });
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if(checkValue!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
    function showMultipleCountry(value)
    {
        if(atob(value)=='2'){
            $("#country").val('');
            $("#countryData").hide();
            $("#countryData1").show();
        }else{
            $("#country1").val('');
            $("#countryData1").hide();
            $("#countryData").show();
        }
    }
</script>