<?php
use Zend\Session\Container;
$loginContainer = new Container('user');
if(!isset($countryId)){
    $countryId = '';
}
?>
<style>
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        background-color: #eaeaea;
        border-bottom: 1px solid #ccc;
        padding: 10px 20px;
    }
    pre {
        max-height: 596px;
    }
    table.dataTable tbody td {
        padding: 8px 18px;
    }
    @media only screen and (max-width: 1024px){
	table.dataTable.display tbody tr:first-child td {
	    border-top: 1px solid #ddd;
        }
	table.dataTable tbody td {
	    padding: 6px 18px;
	}
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        left: -184px;
    }
    #userDataTable_wrapper{
	overflow-x:scroll;
    }
    .select-wrapper{
	width:100%;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Users</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Users</a>
       </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <div class="col l12 m12 s12">
            <div class="card card-default table-height">
                <div class="card-header dataTable-header"><i class="zmdi zmdi-filter-list"></i> User List
		<?php
		if($loginContainer->hasViewOnlyAccess!= 'yes' && ($loginContainer->roleCode!= 'LDEO' && $loginContainer->roleCode!= 'ANCSC')) {
		?>
		  <span style="float:right;"><a class="custom-add-btn" href="/user/add/<?php echo base64_encode($countryId); ?>"><i class="zmdi zmdi-plus"></i> Add User</a></span>
		<?php } ?>
                </div>
                <div class="card-content clearfix">
                    <table id="userDataTable" class="responsive-table display dataTable">
                        <thead>
                            <tr>
                                <th>Full Name</th>
				<?php
				if(trim($countryId)!= ''){
				?>
                                  <th>Role</th>
				<?php } ?>
				<th>User Name</th>
                                <th>Email</th>
                                <th>Mobile</th>
                                <th>Access</th>
                                <th>Status</th>
                                <th>Last Login</th>
				<?php
				if($loginContainer->hasViewOnlyAccess!= 'yes') {
				?>
                                   <th style="width:80px !important;">Action</th>
				<?php } ?>
                            </tr>
                        </thead>
			<tfoot>
                             <tr>
                                <th>Full Name</th>
				<?php
				if(trim($countryId)!= ''){
				?>
                                  <th>Role</th>
				<?php } ?>
				<th>User Name</th>
                                <th>Email</th>
                                <th>Mobile</th>
				<th>Access</th>
                                <th>Status</th>
                                <th>Last Login</th>
				<?php
				if($loginContainer->hasViewOnlyAccess!= 'yes') {
				?>
                                  <th>Action</th>
				<?php } ?>
                            </tr>
                        </tfoot>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
       oTable = $("#userDataTable").DataTable({
	"lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
	"iDisplayLength": 25,
        "bProcessing": true,
        "bServerSide": true,
         "aoColumns": [
		{"sClass":"left"},
		<?php
		if(trim($countryId)!= ''){
		?>
		  {"sClass":"left"},
		<?php } ?>
		{"sClass":"left"},
		{"sClass":"left"},
		{"sClass":"left"},
		{"sClass":"left"},
		{"sClass":"left"},
		{"sClass":"center"},
		<?php
		if($loginContainer->hasViewOnlyAccess!= 'yes') {
		?>
		  {"sClass":"center","bSortable":false}
		<?php } ?>
            ],
        "sAjaxSource": "<?php echo $this->url('user',array('action' => 'index')); ?>",
         "fnServerData": function ( sSource, aoData, fnCallback ) {
	    aoData.push({"name": "countryId", "value": '<?php echo $countryId; ?>'});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
       });
       
       $('.dataTables_filter').empty(); // clears the content generated
       $('.dataTables_filter').append(
                "<div class='input-field col s6 search-div right' style='width: 250px'>" +
                "    <i class='material-icons search-icon'>search</i> "+
                "    <input id='search-items' type='text' class='validate' />" +
                "    <label for='icon_prefix' class='search-label'>Search</label>   "+
                "</div>");
       $(document).on('keyup', "input[type='text']", function(){
                    var oTable = $('.dataTable').dataTable();
                    oTable.fnFilter($(this).val());
                });
    });
</script>