<div id="page-content">
    <div class="row section-header">
        <h4 class="page-title">Add Role</h4>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="addRoleForm" name="addRoleForm" method="post" action="<?php echo $this->url('role',array('action'=>'add')); ?>">
        <div class="card">
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <input id="roleName" name="roleName" type="text" class="validate isRequired" title="Please enter role name">
                        <label for="roleName" class="">Role Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <input id="normal" name="roleCode" type="text" class="validate isRequired" title="Please enter role code">
                        <label for="roleCode" class="">Role Code *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-padding col m6 s6">
                        Has Global Access?<br>
                         <input class="with-gap" name="hGA" type="radio" id="hGAYes" value="yes"/>
                         <label for="hGAYes">Yes </label>
                         <input class="with-gap" name="hGA" type="radio" id="hGANo" value="no" checked />
                         <label for="hGANo">No </label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <textarea id="roleDescription" name="roleDescription" class="materialize-textarea"></textarea>
                        <label for="roleDescription">Role Description</label>
                    </div>
                </div>
            </div>
            
            <div class="col s12">
                <a href="javascript:void(0);" class="btn" onclick="addRole();">Add</a>&nbsp;&nbsp;
                <a href="<?php echo $this->url('role'); ?>">Cancel</a>
            </div>
        </div>
        </form>
    </div>
</div>
<script>
    function addRole(){
        flag = deforayValidator.init({
               formId: 'addRoleForm'
        });
        
        if(flag){
            document.getElementById('addRoleForm').submit();
        }
    }
</script>