<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Add Role</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="<?php echo $this->url('role'); ?>" class="breadcrumb">Roles</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Add Role</a>
        </div>
    </div>
    <div class="row content-container" style="padding: 0 20px;">
        <form id="addRoleForm" name="addRoleForm" method="post" action="<?php echo $this->url('role',array('action'=>'add')); ?>">
        <div class="card">
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <input id="roleName" name="roleName" type="text" class="validate isRequired" title="Please enter role name" onblur="checkNameValidation('role', 'role_name', this, null,'The role name that you entered already exist. Please enter different name')">
                        <label for="roleName" class="">Role Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <input id="roleCode" name="roleCode" type="text" class="validate isRequired" title="Please enter role code" onblur="checkNameValidation('role', 'role_code', this, null,'The role code that you entered already exist. Please enter different code')">
                        <label for="roleCode" class="">Role Code *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <textarea id="roleDescription" name="roleDescription" class="materialize-textarea"></textarea>
                        <label for="roleDescription">Role Description</label>
                    </div>
                </div>
            </div>
            
            <div class="col s12">
                <a href="<?php echo $this->url('role'); ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addRole();">ADD</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script>
    function addRole(){
        flag = deforayValidator.init({
            formId: 'addRoleForm'
        });
        
        if(flag){
            document.getElementById('addRoleForm').submit();
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if($.trim(checkValue)!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
</script>