<style>
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        background-color: #eaeaea;
        border-bottom: 1px solid #ccc;
        padding: 10px 20px;
    }
    table.dataTable tbody td {
        padding: 8px 18px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        left: -184px;

    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Roles</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Roles</a>
       </div>
    </div>
    <div class="row content-container">
        <div class="col l12 m12 s12">
            <div class="card card-default table-height">
                <div class="card-header dataTable-header"><i class="zmdi zmdi-filter-list"></i> Role List
                 <span style="float:right;"><a class="custom-add-btn" href="<?php echo $this->url('role',array('action' => 'add')); ?>"><i class="zmdi zmdi-plus"></i> Add Role</a></span>
                </div>
                <div class="card-content clearfix">
                    <table id="roleDataTable"  class="responsive-table display dataTable">
                        <thead>
                            <tr>
                                <th>Role Name</th>
                                <th>Role Code</th>
                                <th>Role Description</th>
                                <th>Role Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Role Name</th>
                                <th>Role Code</th>
                                <th>Role Description</th>
                                <th>Role Status</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $("#roleDataTable").dataTable( {
        "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
        "iDisplayLength": 25,
        "bProcessing": true,
        "bServerSide": true,
         "aoColumns": [
            {"sClass":"center"},
            {"sClass":"center"},
            {"sClass":"center"},
            {"sClass":"center"},
            {"sClass":"center","bSortable":false}
        ],
        "sAjaxSource": "<?php echo $this->url('role',array('action' => 'index')); ?>",
         "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
      } );
      $('.dataTables_filter').empty(); // clears the content generated
      $('.dataTables_filter').append(
                "<div class='input-field col s6 search-div right' style='width: 250px'>" +
                "    <i class='material-icons search-icon'>search</i> "+
                "    <input id='search-items' type='text' class='validate' />" +
                "    <label for='icon_prefix' class='search-label'>Search</label>   "+
                "</div>");
      $(document).on('keyup', "input[type='text']", function(){
           oTable.search($(this).val()).draw();
      });
    });
</script>