<?php
use Zend\Session\Container;
$alertContainer = new Container('alert');
?>
<div id="page-content">
    <div class="row section-header">
        <h4 class="page-title">Roles</h4>
    </div>
    <div class="row dashboard-wrapper content-container">
        <div class="col l12 m12 s12">
            <div class="card card-default table-height">
                <div class="card-header dataTable-header">Role List <span style="float:right;"><a href="<?php echo $this->url('role',array('action'=>'add')); ?>">Add Role</a></span></div>
                <div class="card-content clearfix">
                    <table id="roleDataTable"  class="responsive-table display dataTable">
                        <thead>
                            <tr>
                                <th>Role Nmae</th>
                                <th>Role Code</th>
                                <th>Has Global Access</th>
                                <th>Role Description</th>
                                <th>Role Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $("#roleDataTable").dataTable( {
        "bProcessing": true,
        "bServerSide": true,
         "aoColumns": [
            {"sClass":"center"},
            {"sClass":"center"},
            {"sClass":"center"},
            {"sClass":"center"},
            {"sClass":"center"},
            {"sClass":"center","bSortable":false}
        ],
        "sAjaxSource": "<?php echo $this->url('role',array('action' => 'index')); ?>",
         "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
      } );
    });
</script>