<?php
if(trim($countryId)!= ''){
    $link = "/anc-site/".base64_encode($countryId);
}else{
    $link = "/anc-site";
}
?>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Add ANC Site</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="<?php echo $this->url('anc-site'); ?>" class="breadcrumb">ANC Sites</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Add ANC Site</a>
        </div>
    </div>
    <div class="row content-container" style="padding: 0 20px;">
        <form id="addAncSiteForm" name="addAncSiteForm" method="post" action="<?php echo $this->url('add-anc-site',array('action'=>'add')); ?>">
        <div class="card">
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">person_pin</i>
                        <input id="ancSiteName" name="ancSiteName" type="text" class="validate isRequired" title="Please enter ANC site name">
                        <label for="ancSiteName" class="">ANC Site Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">code</i>
                        <input id="ancSiteCode" name="ancSiteCode" type="text" class="validate isRequired" title="Please enter ANC site code" onblur="checkNameValidation('anc_site', 'anc_site_code', this, null,'The anc site code that you entered already exist. Please enter different code')" autofocus>
                        <label for="ancSiteCode" class="">ANC Site Code *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">done</i>
                        <select class="material-select isRequired" id="ancSiteType" name="ancSiteType" title="Please select facility type">
                            <?php
                            foreach($facilityTypes as $facilityType){
                                if($facilityType['facility_type_id']== 1){
                                ?>
                                  <option value="<?php echo base64_encode($facilityType['facility_type_id']);?>"><?php echo ucwords($facilityType['facility_type_name']);?></option>
                                <?php
                                }
                            }
                            ?>
                        </select>
                        <label for="ancSiteType" class="">Facility Type *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">email</i>
                        <input id="email" name="email" type="text" class="validate isRequired" placeholder="eg-user1@gmail.com,user2@gmail.com" title="Please enter email-id" onblur="validateMultipleEmailsCommaSeparated(this);" keyup="validateMultipleEmailsCommaSeparated(this);">
                        <label for="email" class="">Email(s) *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">contacts</i>
                        <input id="contactPerson" name="contactPerson" type="text" class="validate isRequired" title="Please enter contact person name">
                        <label for="contactPerson" class="">Contact Person *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="mobile" name="mobile" type="text" class="validate checkNum isNumeric isRequired" title="Please enter contact number" onblur="checkNameValidation('anc_site', 'phone_number', this, null,'The contact no. that you entered already exist. Please enter different contact no');">
                        <label for="mobile" class="">Contact Number *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">room</i>
                        <select class="material-select isRequired" id="country" name="country" title="Please select country">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($countries as $country){
                                ?>
                                <option value="<?php echo base64_encode($country['country_id']);?>" <?php echo($countryId ==$country['country_id'])?'selected="selected"':''; ?>><?php echo ucwords($country['country_name']);?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <label for="country" class="">Country *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10 ajaxProvince">
                        <i class="material-icons prefix">room</i>
                        <select class="material-select validate isRequired" id="province" name="province" title="Please select province" onchange="checkProvince(this.value);">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($provinces as $province){
                                ?>
                                <option value="<?php echo base64_encode($province['location_id']);?>"><?php echo ucwords($province['location_name']);?></option>
                                <?php
                            }
                            ?>
                            <option value="other">Other</option>
                        </select>
                        <label for="province" class="" style="transform:translateY(0%);">Province *</label>
                        <input type="text" id="provinceNew" name="provinceNew" placeholder="Enter Province" title="Please enter province name" class="validate" style="display:none;"/>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10 ajaxDistrict">
                        <i class="material-icons prefix">room</i>
                        <select class="material-select validate isRequired" id="district" name="district" title="Please select district" onchange="checkDistrict(this.value);">
                            <option value=""> -- Select -- </option>
                            <option value="other">Other</option>
                        </select>
                        <label for="district" class="" style="transform:translateY(0%);">District *</label>
                        <input type="text" id="districtNew" name="districtNew" placeholder="Enter District" title="Please enter district name" class="validate" style="display:none;"/>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <textarea id="address" name="address" class="materialize-textarea"></textarea>
                        <label for="address">Address</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">navigation</i>
                        <input id="latitude" name="latitude" type="text" class="validate" title="Please enter latitude" onblur="validateLatitudeLongitude(this,'latitude');" keyup="validateLatitudeLongitude(this,'latitude');">
                        <label for="latitude" class="">Latitude </label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">navigation</i>
                        <input id="longitude" name="longitude" type="text" class="validate" title="Please enter longitude" onblur="validateLatitudeLongitude(this,'longitude');" keyup="validateLatitudeLongitude(this,'longitude');">
                        <label for="longitude" class="">Longitude </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <textarea id="comments" name="comments" class="materialize-textarea"></textarea>
                        <label for="comments">Comments</label>
                    </div>
                </div>
            </div>
            <div class="col s12">
                <input type="hidden" name="redirectUrl" value="<?php echo $link; ?>"/>
                <a href="<?php echo $link; ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addFacility();">ADD</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script>
    function checkProvince(val){
        if(val == 'other'){
            $('#provinceNew').show();
            $('#provinceNew').addClass('isRequired');
        }else{
            $('#provinceNew').hide();
            $('#provinceNew').val('');
            $('#provinceNew').removeClass('isRequired');
        }
        getProvinceDistricts(val);
    }
    
    function checkDistrict(val){
       if(val == 'other'){
            $('#districtNew').show();
            $('#districtNew').addClass('isRequired');
        }else{
            $('#districtNew').hide();
            $('#districtNew').val('');
            $('#districtNew').removeClass('isRequired');
        }  
    }
    
    $('#country').on('change',function(){
        $.post("<?php echo $this->url('country', array('action' => 'get-country-provinces')); ?>", {country: this.value},
        function(data) {
            $('.ajaxProvince').html(data);
            $('#province').material_select();
            $('div').removeClass('isRequired');
        });
    });
    
    function getProvinceDistricts(val){
        if(val!= 'other'){
            $.post("<?php echo $this->url('country', array('action' => 'get-province-districts')); ?>", {province: val},
            function(data) {
                $('.ajaxDistrict').html(data);
                $('#district').material_select();
                $('div').removeClass('isRequired');
            });
        }else{
            $districts = '';
            $districts+= '<i class="material-icons prefix">room</i>';
            $districts+='<select class="material-select validate isRequired" id="district" name="district" title="Please select district" onchange="checkDistrict(this.value);"><option value=""> -- Select -- </option><option value="other">Other</option></select>';
            $districts+='<label for="district" class="">District *</label>';
            $districts+='<input type="text" id="districtNew" name="districtNew" placeholder="Enter District" title="Please enter district name" class="validate" style="display:none;"/>';
            $('.ajaxDistrict').html($districts);
            $('#district').material_select();
            $('div').removeClass('isRequired');
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if($.trim(checkValue)!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
    
    duplicateName = true;
    function addFacility(){
        flag = deforayValidator.init({
            formId: 'addAncSiteForm'
        });
        
        if(flag){
            document.getElementById('addAncSiteForm').submit();
        }
    }
</script>