<?php
if(isset($countryId) && trim($countryId)!=''){
    $link = "/anc-site/".base64_encode($countryId);
}else{
    $link = "/anc-site";
}
?>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Edit ANC Site</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="<?php echo $this->url('anc-site'); ?>" class="breadcrumb">ANC Sites</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Edit ANC Site</a>
        </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="editAncSiteForm" name="editAncSiteForm" method="post" action="<?php echo $this->url('edit-anc-site',array('action'=>'edit')); ?>">
        <div class="card">
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">person_pin</i>
                        <input id="ancSiteName" name="ancSiteName" type="text" class="validate isRequired" title="Please enter ANC site name" value="<?php echo $row->anc_site_name; ?>">
                        <label for="ancSiteName" class="">ANC Site Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">code</i>
                        <input id="ancSiteCode" name="ancSiteCode" type="text" class="validate isRequired" title="Please enter ANC site code" value="<?php echo $row->anc_site_code; ?>" onblur="checkNameValidation('anc_site', 'anc_site_code', this, '<?php echo "anc_site_id##" .$row->anc_site_id; ?>','The anc site code that you entered already exist. Please enter different code.')">
                        <label for="ancSiteCode" class="">ANC Site Code *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">done</i>
                        <select class="material-select isRequired" id="ancSiteType" name="ancSiteType" title="Please select ANC site type">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($facilityTypes as $facilityType){
                                ?>
                                <option value="<?php echo base64_encode($facilityType['facility_type_id']);?>" <?php echo($row->anc_site_type == $facilityType['facility_type_id'])?'selected="selected"':''; ?>><?php echo ucwords($facilityType['facility_type_name']);?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <label for="facilityType" class="">ANC Site Type *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">email</i>
                        <input id="email" name="email" type="text" class="validate isEmail isRequired" title="Please enter email-id" value="<?php echo $row->email; ?>" onblur="checkNameValidation('anc_site', 'email', this, '<?php echo "anc_site_id##" .$row->anc_site_id; ?>','The anc site email that you entered already exist. Please enter different email id.')">
                        <label for="email" class="">Email *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">contacts</i>
                        <input id="contactPerson" name="contactPerson" type="text" class="validate isRequired" title="Please enter contact person name" value="<?php echo $row->contact_person; ?>">
                        <label for="contactPerson" class="">Contact Person *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="mobile" name="mobile" type="text" class="validate isRequired" title="Please enter contact number" value="<?php echo $row->phone_number; ?>" onblur="checkNameValidation('anc_site', 'phone_number', this, '<?php echo "anc_site_id##" .$row->anc_site_id; ?>','The contact no. that you entered already exist. Please enter different contact no.')">
                        <label for="mobile" class="">Contact Number *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                 <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">room</i>
                        <select class="material-select isRequired" id="country" name="country" title="Please select country">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($countries as $country){
                                ?>
                                <option value="<?php echo base64_encode($country['country_id']);?>" <?php echo($row->country == $country['country_id'])?'selected="selected"':''; ?>><?php echo ucwords($country['country_name']);?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <label for="country" class="">Country *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <textarea id="address" name="address" class="materialize-textarea"><?php echo $row->address; ?></textarea>
                        <label for="address">Address</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">navigation</i>
                        <input id="latitude" name="latitude" type="text" class="validate" title="Please enter latitude" value="<?php echo $row->latitude; ?>">
                        <label for="latitude" class="">Latitude </label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <i class="material-icons prefix">navigation</i>
                        <input id="longitude" name="longitude" type="text" class="validate" title="Please enter longitude" value="<?php echo $row->longitude; ?>">
                        <label for="longitude" class="">Longitude </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <select id="ancSiteStatus" name="ancSiteStatus" class="material-select">
                            <option value="active" <?php echo($row->status == "active")?'selected="selected"':'';  ?>>Active</option>
                            <option value="inactive" <?php echo($row->status == "inactive")?'selected="selected"':'';  ?>>Inactive</option>
                        </select>
                        <label for="ancSiteStatus" class="">ANC Site Status</label>
                    </div>
                </div>
            </div>
            <div class="col s12">
                <input type="hidden" name="chosenCountryId" value="<?php echo $link; ?>"/>
                <input id="ancSiteId" name="ancSiteId" type="hidden" value="<?php echo base64_encode($row->anc_site_id); ?>"/>
                <a href="<?php echo $link; ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addFacility();">UPDATE</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script>
    duplicateName = true;
    function addFacility(){
        flag = deforayValidator.init({
            formId: 'editAncSiteForm'
        });
        
        if(flag){
            document.getElementById('editAncSiteForm').submit();
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if(checkValue!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
</script>