<?php
use Zend\Session\Container;
$loginContainer = new Container('user');
if(!isset($countryId)){
    $countryId = '';
}
?>
<style>
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        background-color: #eaeaea;
        border-bottom: 1px solid #ccc;
        padding: 10px 20px;
    }
    pre {
        max-height: 596px;
    }
    table.dataTable tbody td {
        padding: 8px 18px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        left: -184px;
    }
    .select-wrapper{
	width:100%;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">ANC Sites</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">ANC Sites</a>
       </div>
    </div>
    <?php
    if(trim($countryId)== ''){
    ?>
	<div class="row">
	    <div class="col l12 m12 s12">
		<table style="width:100%;">
		    <tr>
			<td style="width:30%;text-align:right;"><h6><strong>Country</strong></h6></td>
			<td style="text-align:left;">
			    <select class="material-select" id="country" name="country" title="Please select country" style="width:40% !important;">
				<option value="">All</option>
				<?php
				foreach($countries as $country){
				    ?>
				    <option value="<?php echo base64_encode($country['country_id']);?>"><?php echo ucwords($country['country_name']);?></option>
				    <?php
				}
				?>
			    </select>
			</td>
			<td style="width:40%;text-align:left;"><a href="javascript:void(0);" onclick="searchAncSite();" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a></td>
		    </tr>
		</table>
	    </div>
	</div>
    <?php } ?>
    <div class="row dashboard-wrapper content-container">
        <div class="col l12 m12 s12">
            <div class="card card-default table-height">
                <div class="card-header dataTable-header"><i class="zmdi zmdi-filter-list"></i> ANC Site List
		<?php
		if($loginContainer->hasViewOnlyAccess!= 'yes') {
		?>
		  <span style="float:right;"><a class="custom-add-btn" href="/anc-site/add/<?php echo base64_encode($countryId); ?>"><i class="zmdi zmdi-plus"></i> Add ANC Site</a></span>
		<?php } ?>
                </div>
                <div class="card-content clearfix">
                    <table id="ancSiteDataTable" class="responsive-table display dataTable">
                        <thead>
                            <tr>
                                <th>ANC Site Name</th>
                                <th>ANC Site Code</th>
                                <th>Facility Type</th>
                                <th>Email</th>
                                <th>Phone Number</th>
				<?php
                                if($loginContainer->roleCode =='CSC' && trim($countryId)== ''){
                                ?>
                                  <th>Country</th>
				<?php } ?>
                                <th>Status</th>
				<?php
				if($loginContainer->hasViewOnlyAccess!= 'yes') {
				?>
                                  <th>Action</th>
				<?php } ?>
                            </tr>
                        </thead>
			<tfoot>
                            <tr>
                                <th>ANC Site Name</th>
				<th>ANC Site Code</th>
                                <th>Facility Type</th>
                                <th>Email</th>
                                <th>Phone Number</th>
				<?php
                                if($loginContainer->roleCode =='CSC' && trim($countryId)== ''){
                                ?>
                                  <th>Country</th>
				<?php } ?>
                                <th>Status</th>
				<?php
				if($loginContainer->hasViewOnlyAccess!= 'yes') {
				?>
                                  <th>Action</th>
				<?php } ?>
                            </tr>
                        </tfoot>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
       oTable = $("#ancSiteDataTable").DataTable({
	"lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
	"iDisplayLength": 25,
        "bProcessing": true,
        "bServerSide": true,
         "aoColumns": [
		{"sClass":"left"},
		{"sClass":"left"},
		{"sClass":"left"},
		{"sClass":"left"},
		{"sClass":"left"},
		<?php
		if($loginContainer->roleCode =='CSC' && trim($countryId)== ''){
		?>
		  {"sClass":"left"},
		<?php } ?>
		{"sClass":"left"},
		<?php
		if($loginContainer->hasViewOnlyAccess!= 'yes') {
		?>
		  {"sClass":"center","bSortable":false}
		<?php } ?>
            ],
        "sAjaxSource": "<?php echo $this->url('anc-site',array('action' => 'index')); ?>",
         "fnServerData": function ( sSource, aoData, fnCallback ) {
	    aoData.push({"name": "country", "value": $("#country").val()});
	    aoData.push({"name": "countryId", "value": '<?php echo $countryId; ?>'});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
       });
       
       $('.dataTables_filter').empty(); // clears the content generated
       $('.dataTables_filter').append(
                "<div class='input-field col s6 search-div right' style='width: 250px'>" +
                "    <i class='material-icons search-icon'>search</i> "+
                "    <input id='search-items' type='text' class='validate' />" +
                "    <label for='icon_prefix' class='search-label'>Search</label>   "+
                "</div>");
       $(document).on('keyup', "input[type='text']", function(){
                    var oTable = $('.dataTable').dataTable();
                    oTable.fnFilter($(this).val());
                });
    });
    
    function searchAncSite(){
	oTable.draw();
    }
</script>