<style>
    .infocus{border: none;}
</style>
<div id="page-content">
    <div class="row section-header">
        <h4 class="page-title">Add Employee</h4>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="addEmployeeForm" name="addEmployeeForm" method="post" action="<?php echo $this->url('employee',array('action'=>'add')); ?>">
        <div class="card">
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">person_pin</i>
                        <input id="employeeName" name="employeeName" type="text" class="validate isRequired" title="Please enter employee name">
                        <label for="employeeName" class="">Employee Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">code</i>
                        <input id="employeeCode" name="employeeCode" type="text" class="validate isRequired" title="Please enter employee code"  onblur="checkNameValidation('employee', 'employee_code', this, null,'The employee code that you entered already exist. Please enter different code.')">
                        <label for="employeeCode" class="">Employee Code *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">done_all</i>
                        <select class="material-select" id="role" name="role" class="isRequired" title="Please select employee role">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($roleData as $role){
                                ?>
                                <option value="<?php echo base64_encode($role['role_id']);?>"><?php echo $role['role_name'];?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <label for="role" class="">Employee Role *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">email</i>
                        <input id="email" name="email" type="text" class="validate isEmail isRequired" title="Please enter email-id" onblur="checkNameValidation('employee', 'email', this, null,'The employee email that you entered already exist. Please enter different email id.')">
                        <label for="email" class="">Email *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="mobile" name="mobile" type="text" class="validate isRequired" title="Please enter contact number" onblur="checkNameValidation('employee', 'mobile', this, null,'The employee mobile no. that you entered already exist. Please enter different mobile no')">
                        <label for="mobile" class="">Contact Number *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="altContact" name="altContact" type="text" class="validate" title="Please enter contact number">
                        <label for="altContact" class="">Alternate Contact</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">vpn_key</i>
                        <input id="password" name="password" type="password" class="validate isRequired" title="Please enter password">
                        <label for="password" class="">Password *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">vpn_key</i>
                        <input id="confirmPassword" name="password" type="password" class="validate isRequired confirmPassword" title="Please check your password and confirm password are same">
                        <label for="password" class="">Confirm Password *</label>
                    </div>
                </div>
            </div>
            <div class="col s6">
                <a href="<?php echo $this->url('employee'); ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addEmployee();">ADD</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script>
    duplicateName = true;
    function addEmployee(){
        flag = deforayValidator.init({
               formId: 'addEmployeeForm'
        });
        
        if(flag){
            document.getElementById('addEmployeeForm').submit();
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if(checkValue!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
</script>