<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Edit Employee</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="<?php echo $this->url('employee'); ?>" class="breadcrumb">Employees</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Edit Employee</a>
        </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="editEmployeeForm" name="editEmployeeForm" method="post" action="<?php echo $this->url('employee',array('action'=>'edit')); ?>">
        <div class="card">
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">person_pin</i>
                        <input id="employeeName" name="employeeName" type="text" class="validate isRequired" title="Please enter employee name" value="<?php echo $empResult->employee_name;?>">
                        <label for="employeeName" class="">Employee Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">code</i>
                        <input id="employeeCode" name="employeeCode" type="text" class="validate isRequired" title="Please enter employee code" value="<?php echo $empResult->employee_code;?>" onblur="checkNameValidation('employee', 'employee_code', this, '<?php echo "employee_id##" .$empResult->employee_id; ?>','The employee code that you entered already exist. Please enter different code.')">
                        <label for="employeeCode" class="">Employee Code *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">power_settings_new</i>
                        <input id="userName" name="userName" type="text" class="validate isRequired" title="Please enter user name" value="<?php echo $empResult->user_name;?>" onblur="checkNameValidation('employee', 'user_name', this, '<?php echo "employee_id##" .$empResult->employee_id; ?>','The user name that you entered already exist. Please enter different name.')">
                        <label for="userName" class="">User Name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">vpn_key</i>
                        <input id="password" name="password" type="password" class="validate" title="Please enter password">
                        <label for="password" class="">Password *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">vpn_key</i>
                        <input id="confirmPassword" name="password" type="password" class="validate confirmPassword" title="Please check your password and confirm password are same">
                        <label for="password" class="">Confirm Password *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">done</i>
                        <select class="material-select" id="role" name="role" class="isRequired" title="Please select employee role">
                            <option value="">-- Select --</option>
                            <?php
                            foreach($roleData as $role){
                                ?>
                                <option value="<?php echo base64_encode($role['role_id']);?>"<?php echo ($empResult->role == $role['role_id']) ? " selected='selected'" : ""; ?>><?php echo ucwords($role['role_name']);?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <label for="role" class="">Employee Role *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">email</i>
                        <input id="email" name="email" type="text" class="validate isEmail isRequired" title="Please enter email-id" value="<?php echo $empResult->email;?>" onblur="checkNameValidation('employee', 'email', this, '<?php echo "employee_id##" .$empResult->employee_id; ?>','The employee email that you entered already exist. Please enter different email.')">
                        <label for="email" class="">Email *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="mobile" name="mobile" type="text" class="validate isRequired" title="Please enter contact number" value="<?php echo $empResult->mobile;?>" onblur="checkNameValidation('employee', 'mobile', this, '<?php echo "employee_id##" .$empResult->employee_id; ?>','The employee mobile no. that you entered already exist. Please enter different mobile no.')">
                        <label for="mobile" class="">Contact Number *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">stay_primary_portrait</i>
                        <input id="altContact" name="altContact" type="text" class="validate" title="Please enter contact number" value="<?php echo $empResult->alt_contact;?>">
                        <label for="altContact" class="">Alternate Contact</label>
                    </div>
                </div>
                <div class="col s6">
                     <div class="input-field col m6 s6">
                        <i class="material-icons prefix">room</i>
                        <select class="material-select" id="country" name="country" class="validate isRequired" title="Please select country">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($countries as $country){
                                ?>
                                <option value="<?php echo base64_encode($country['country_id']);?>" <?php echo ($empResult->country == $country['country_id']) ? "selected='selected'" : ""; ?>><?php echo ucwords($country['country_name']);?></option>
                                <?php
                            }
                            ?>
                        </select>
                        <label for="country" class="">Country *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m6 s6">
                        <i class="material-icons prefix">done</i>
                        <select class="material-select" id="status" name="status" title="Please select employee status">
                            <option value="active" <?php echo ($empResult->status == 'active') ? " selected='selected'" : ""; ?>>Active</option>
                            <option value="inactive" <?php echo ($empResult->status == 'inactive') ? " selected='selected'" : ""; ?>>Inactive</option>
                        </select>
                        <label for="status" class="">Employee Status *</label>
                    </div>
                </div>
            </div>
            <div class="col s6">
                <input id="employeeId" name="employeeId" type="hidden" value="<?php echo base64_encode($empResult->employee_id);?>"/>
                <a href="<?php echo $this->url('employee'); ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" onclick="editEmployee();" class="waves-effect waves-light btn-small white-text pink margin-bottom-10">UPDATE</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script>
    duplicateName = true;
    function editEmployee(){
        flag = deforayValidator.init({
               formId: 'editEmployeeForm'
        });
        
        if(flag){
            document.getElementById('editEmployeeForm').submit();
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if(checkValue!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
</script>