<?php
$editAction = '{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center","bSortable":false}';
?>
<div id="page-content">
    <div class="row section-header">
        <div class="page-title">
	    <span style="font-size: 34px;font-weight:400;">Employees</span>
	    <a style="float: right;margin-right: 2%;" href="<?php echo $this->url('employee',array('action' => 'add')); ?>" class="waves-effect waves-light btn-small white-text pink margin-bottom-10">ADD EMPLOYEE</a>
	</div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <div class="col l12 m12 s12">
            <div class="card card-default table-height">
                <div class="card-header dataTable-header">
                    Employee List
                </div>
                <div class="card-content clearfix">
                    <table id="employeeDataTable"  class="responsive-table display dataTable">
                        <thead>
                            <tr>
                                <th>Employee Name</th>
                                <th>Role</th>
                                <th>Email</th>
                                <th>Mobile</th>
                                <th>Status</th>
                                <th>Added On</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
       $("#employeeDataTable").DataTable({
        "bProcessing": true,
        "bServerSide": true,
         "aoColumns": [
		<?php echo $editAction;?>
            ],
        "sAjaxSource": "<?php echo $this->url('employee',array('action' => 'index')); ?>",
         "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
       });
    });
</script>