<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Add Data Reporting</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="<?php echo $this->url('data-collection'); ?>" class="breadcrumb">Data Reporting</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Add Data Reporting</a>
        </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="addDataReportingForm" name="addDataReportingForm" method="post" action="<?php echo $this->url('data-collection',array('action'=>'add')); ?>">
        <div class="card">
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <input id="surveillanceId" name="surveillanceId" type="text" class="validate isRequired" title="Please enter surveillance ID" onblur="checkNameValidation('data_collection', 'surveillance_id', this, null,'The surveillance id that you entered already exist. Please enter different id.');">
                        <label for="surveillanceId" class="">Surveillance ID *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <input id="specimenCollectedDate" name="specimenCollectedDate" type="text" class="validate datepicker" title="Please enter specimen collected date">
                        <label for="specimenCollectedDate" class="">Specimen Collected Date </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <select id="ancSite" name="ancSite" class="material-select isRequired" title="Please select ANC site">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($ancSites as $ancSite){
                            ?>
                              <option data-anc-site-code="<?php echo $ancSite['anc_site_code']; ?>" value="<?php echo base64_encode($ancSite['anc_site_id']); ?>"><?php echo ucwords($ancSite['anc_site_name']); ?></option>
                            <?php } ?>
                        </select>
                        <label for="ancSite">ANC site name *</label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <input id="ancSiteCode" name="ancSiteCode" type="text" class="validate isRequired" title="Please enter ANC site code">
                        <label for="ancSiteCode" class="">ANC site code * </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <input id="ancPatientId" name="ancPatientId" type="text" class="validate isRequired" title="Please enter ANC patient ID">
                        <label for="ancPatientId" class="">ANC Patient ID * </label>
                    </div>
                </div>
                 <div class="col s6">
                    <div class="input-field col m10 s10">
                        <input id="age" name="age" type="text" class="validate checkNum" title="Please enter age">
                        <label for="age" class="">Age </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <input id="specimenPickedUpDateAtAnc" name="specimenPickedUpDateAtAnc" type="text" class="validate datepicker" title="Please enter specimen picked up date at anc">
                        <label for="specimenPickedUpDateAtAnc" class="">Specimen Picked Up Date at ANC </label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <select id="lab" name="lab" class="material-select isRequired" title="Please select lab site code/name">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($facilities as $facility){
                            ?>
                              <option value="<?php echo base64_encode($facility['facility_id']); ?>"><?php echo $facility['facility_code'].' - '.ucwords($facility['facility_name']); ?></option>
                            <?php } ?>
                        </select>
                        <label for="lab">Lab site code/name *</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <input id="labSpecimenId" name="labSpecimenId" type="text" class="validate" title="Please enter lab specimen ID">
                        <label for="labSpecimenId" class="">Lab Specimen ID </label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <input id="dateOfReceiptAtCentralLab" name="dateOfReceiptAtCentralLab" type="text" class="validate datepicker" title="Please enter date of receipt at central lab">
                        <label for="dateOfReceiptAtCentralLab" class="">Date of Receipt at Central Lab </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <select id="rejectionReason" name="rejectionReason" class="material-select" title="Please select rejection code">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($rejectionReasons as $rejection){
                            ?>
                              <option value="<?php echo base64_encode($rejection['rejection_reason_id']); ?>"><?php echo $rejection['rejection_code']; ?></option>
                            <?php } ?>
                        </select>
                        <label for="rejectionReason">Specimen Rejection Code </label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <input id="finalLagAvidityOdn" name="finalLagAvidityOdn" type="text" class="validate" title="Please enter final LAg avidity ODn">
                        <label for="finalLagAvidityOdn" class="">Final LAg Avidity ODn </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-padding col m10 s10">
                      LAg Avidity Result<br>
                      <input id="lagAvidityResultRecent" class="with-gap" name="lagAvidityResult" type="radio" value="r"/>
                     <label for="lagAvidityResultRecent">R </label>&nbsp;
                     <input id="lagAvidityResultLongTerm" class="with-gap" name="lagAvidityResult" type="radio" value="lt"/>
                     <label for="lagAvidityResultLongTerm">LT </label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <input id="hivRna" name="hivRna" type="text" class="validate" title="Please enter HIV RNA">
                        <label for="hivRna" class="">HIV RNA (copies/ml) </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-padding col m10 s10">
                      HIV RNA >= 1,000 (copies/ml)<br>
                      <input id="hivRnaGT1000Yes" class="with-gap" name="hivRnaGT1000" type="radio" value="yes"/>
                     <label for="hivRnaGT1000Yes">Yes </label>&nbsp;
                     <input id="hivRnaGT1000No" class="with-gap" name="hivRnaGT1000" type="radio" value="no"/>
                     <label for="hivRnaGT1000No">No </label>
                    </div>
                </div>
                <div class="col s6">
                    <div class="input-padding col m10 s10">
                      Recent Infection (LAg-R & RNA >= 1,000)<br>
                      <input id="recentInfectionYes" class="with-gap" name="recentInfection" type="radio" value="yes"/>
                     <label for="recentInfectionYes">Yes </label>&nbsp;
                     <input id="recentInfectionNo" class="with-gap" name="recentInfection" type="radio" value="no"/>
                     <label for="recentInfectionNo">No </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    <div class="input-field col m10 s10">
                        <input id="dateOfResultDispatchedToClinic" name="dateOfResultDispatchedToClinic" type="text" class="validate datepicker" title="Please enter date of result dispatched to clinic">
                        <label for="dateOfResultDispatchedToClinic" class="">Date of Result Dispatched to Clinic </label>
                    </div>
                </div>
                <div class="col s6">
                   <div class="input-padding col m10 s10">
                      Asante Rapid Recency Assay<br>
                      <input id="asanteRapidRecencyAssayP" class="with-gap" name="asanteRapidRecencyAssay" type="radio" value="p"/>
                      <label for="asanteRapidRecencyAssayP" style="padding-left:22px !important;">P </label>&nbsp;
                      <input id="asanteRapidRecencyAssayN" class="with-gap" name="asanteRapidRecencyAssay" type="radio" value="n"/>
                      <label for="asanteRapidRecencyAssayN" style="padding-left:22px !important;">N </label>
                      <input id="asanteRapidRecencyAssayR" class="with-gap" name="asanteRapidRecencyAssay" type="radio" value="r"/>
                      <label for="asanteRapidRecencyAssayR" style="padding-left:22px !important;">R </label>&nbsp;
                      <input id="asanteRapidRecencyAssayLT" class="with-gap" name="asanteRapidRecencyAssay" type="radio" value="lt"/>
                      <label for="asanteRapidRecencyAssayLT" style="padding-left:22px !important;">LT </label>
                    </div>
                </div>
            </div>
            <div class="col s12">
                <a href="<?php echo $this->url('data-collection'); ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addDataReporting();">ADD</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script>
    $(document).ready(function(){
       $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 15, // Creates a dropdown of 15 years to control year
            format: 'dd/mm/yyyy'
        });
    });
    
    $('#ancSite').on('change', function() {
        $('label[for=ancSiteCode]').css({"transform": "translateY(-140%)"});
        $("#ancSiteCode").val($('#ancSite option:selected').data('anc-site-code'));
    });
    
    $('#hivRna').on('change', function() {
        if($.trim($('#hivRna').val())!= '' && parseInt($('#hivRna').val()) >= 1000){
            $('#hivRnaGT1000Yes').prop('checked',true);
            $('#hivRnaGT1000No').prop('checked',false);
            if($('#lagAvidityResultRecent').is(":checked")){
                $('#recentInfectionYes').prop('checked',true);
            }
        }else if($.trim($('#hivRna').val())!= '' && parseInt($('#hivRna').val()) < 1000){
            $('#hivRnaGT1000No').prop('checked',true);
            $('#hivRnaGT1000Yes').prop('checked',false);
            $('#recentInfectionNo').prop('checked',true);
        }else{
            $('#hivRnaGT1000Yes').prop('checked',false);
            $('#hivRnaGT1000No').prop('checked',false);
            $('#recentInfectionYes').prop('checked',false);
            $('#recentInfectionNo').prop('checked',false);
        }
    });
    
    $('input[type=radio][name=lagAvidityResult]').change(function() {
        if(this.value == 'r'){
            if($.trim($('#hivRna').val())!= '' && parseInt($('#hivRna').val()) >= 1000){
                $('#recentInfectionYes').prop('checked',true);
            }
        }else if(this.value == 'lt'){
            $('#recentInfectionNo').prop('checked',true);
        }
    });
    
    function addDataReporting(){
        flag = deforayValidator.init({
            formId: 'addDataReportingForm'
        });
        
        if(flag){
            document.getElementById('addDataReportingForm').submit();
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if(checkValue!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
</script>