<?php
use Application\Service\CommonService;
$common = new CommonService();
if(isset($countryId) && trim($countryId)!=''){
    $link = "/data-collection/".base64_encode($countryId);
}else{
    $link = "/data-collection";
}
$specimenCollectedDate = '';
if(isset($row->specimen_collected_date) && trim($row->specimen_collected_date)!= '' && $row->specimen_collected_date!= '0000-00-00'){
    $specimenCollectedDate = $common->viewDateFormat($row->specimen_collected_date);
}
$specimenPickedUpDateAtAnc = '';
if(isset($row->specimen_picked_up_date_at_anc) && trim($row->specimen_picked_up_date_at_anc)!= '' && $row->specimen_picked_up_date_at_anc!= '0000-00-00'){
    $specimenPickedUpDateAtAnc = $common->viewDateFormat($row->specimen_picked_up_date_at_anc);
}
$patientDOB = '';
if(isset($row->patient_dob) && trim($row->patient_dob)!= '' && $row->patient_dob!= '0000-00-00'){
    $patientDOB = $common->viewDateFormat($row->patient_dob);
}
$receiptDateAtCentralLab = '';
if(isset($row->receipt_date_at_central_lab) && trim($row->receipt_date_at_central_lab)!= '' && $row->receipt_date_at_central_lab!= '0000-00-00'){
    $receiptDateAtCentralLab = $common->viewDateFormat($row->receipt_date_at_central_lab);
}
$testCompletionDate = '';
if(isset($row->date_of_test_completion) && trim($row->date_of_test_completion)!= '' && $row->date_of_test_completion!= '0000-00-00'){
    $testCompletionDate = $common->viewDateFormat($row->date_of_test_completion);
}
$resultDispatchedDateToClinic = '';
if(isset($row->result_dispatched_date_to_clinic) && trim($row->result_dispatched_date_to_clinic)!= '' && $row->result_dispatched_date_to_clinic!= '0000-00-00'){
    $resultDispatchedDateToClinic = $common->viewDateFormat($row->result_dispatched_date_to_clinic);
}
$lAgAvidityResult = '';
if(trim($row->lag_avidity_result)!= '' && $row->lag_avidity_result == 'lt'){
    $lAgAvidityResult = 'Long Term';
}else if(trim($row->lag_avidity_result)!= '' && $row->lag_avidity_result == 'r'){
    $lAgAvidityResult = 'Recent';
}
$hIVRNAResult = '';
if(trim($row->hiv_rna_gt_1000)!= '' && $row->hiv_rna_gt_1000 =='yes'){
    $hIVRNAResult = 'High Viral Load';
}else if(trim($row->hiv_rna_gt_1000)!= '' && $row->hiv_rna_gt_1000 =='no'){
    $hIVRNAResult = 'Low Viral Load';
}
$asanteRapidRecencyAssy = explode('/',$row->asante_rapid_recency_assy);
$asanteRapidRecencyAssayPn = '';
$asanteRapidRecencyAssayRlt = '';
if(isset($asanteRapidRecencyAssy[0]) && trim($asanteRapidRecencyAssy[0])!= ''){
    $asanteRapidRecencyAssayPn = $asanteRapidRecencyAssy[0];
}if(isset($asanteRapidRecencyAssy[1]) && trim($asanteRapidRecencyAssy[1])!= ''){
    $asanteRapidRecencyAssayRlt = $asanteRapidRecencyAssy[1];
}
?>
<style>
    #box-1{
	float:left;
	width:44%;
	border:2px dotted #333;
        margin-top:8px !important;
    }
    #box-breaker{
	float:left;
	width:12%;
	font-size:40px;
	text-align:center;
    }
    #box-2{
	float:left;
	width:44%;
	border:2px dotted #333;
        margin-top:8px !important;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Edit Lab Data Reporting</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="<?php echo $link; ?>" class="breadcrumb">Lab Data Reporting</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Edit Lab Data Reporting</a>
        </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="editDataReportingForm" name="editDataReportingForm" method="post" action="<?php echo $this->url('edit-data-collection'); ?>">
        <div class="card">
            <fieldset style="border-color:#88C542;border-style: solid;">
               <legend>SURVEILLANCE INFORMATION (<span id="serialNo"><?php echo $row->surveillance_id; ?></span>)</legend>
                <div class="row" style="margin-bottom:0;">
		    <div class="col s4">
			<div class="input-field col m12 s12">
			    <input id="studyId" name="studyId" type="text" class="validate isRequired" title="Please enter study ID" value="<?php echo $row->study_id; ?>" onblur="checkNameValidation('data_collection', 'study_id', this, '<?php echo "data_collection_id##" .$row->data_collection_id; ?>','The study id that you entered already exist. Please enter different id');">
			    <label for="studyId" class="">Study ID *</label>
			</div>
		    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <input id="specimenCollectedDate" name="specimenCollectedDate" type="text" class="validate datepicker" title="Please enter specimen collected date" value="<?php echo $specimenCollectedDate; ?>">
                            <label for="specimenCollectedDate" class="">Date Specimen Collected </label>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <select id="ancSite" name="ancSite" class="material-select isRequired" title="Please select ANC site">
                                <option value=""> -- Select -- </option>
                                <?php
                                foreach($ancSites as $ancSite){
                                ?>
                                  <option data-anc-site-code="<?php echo $ancSite['anc_site_code']; ?>" value="<?php echo base64_encode($ancSite['anc_site_id']); ?>" <?php echo($row->anc_site == $ancSite['anc_site_id'])?'selected="selected"':''; ?>><?php echo $ancSite['anc_site_code'].' - '.ucwords($ancSite['anc_site_name']); ?></option>
                                <?php } ?>
                            </select>
                            <label for="ancSite">ANC site name *</label>
                        </div>
                    </div>
                </div>
		<div class="row" style="margin-bottom:0;">
		    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <input id="specimenPickedUpDateAtAnc" name="specimenPickedUpDateAtAnc" type="text" class="validate datepicker" title="Please enter specimen picked up date at anc" value="<?php echo $specimenPickedUpDateAtAnc; ?>">
                            <label for="specimenPickedUpDateAtAnc" class="">Date Specimen Picked Up at ANC </label>
                        </div>
                    </div>
		</div>
            </fieldset>
	    <fieldset style="border-color:#ff9800;border-style: solid;">
                <legend>PATIENT INFORMATION</legend>
                <div class="row" style="margin-bottom:0;">
                    <div class="col s4">
                        <div class="input-field col m12 s12" style="margin-top:0.5rem;">
                            <input id="ancPatientId" name="ancPatientId" type="text" class="validate isRequired" title="Please enter ANC patient ID" value="<?php echo $row['anc_patient_id']; ?>">
                            <label for="ancPatientId" class="">ANC Patient ID * </label>
                        </div>
                    </div>
		    <div class="col s4">
			    <div class="input-field col m12 s12" style="margin-top:0.5rem;">
			    <input id="artPatientId" name="artPatientId" type="text" class="validate" title="Please enter ART number" value="<?php echo $row['art_patient_id'];?>">
			    <label for="artPatientId" class="">ART Number </label>
			    </div>
		    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12" style="margin-top:0.5rem;">
                            <input id="encAncPatientId" name="encAncPatientId" type="text" value="<?php echo $row['enc_anc_patient_id']; ?>" readonly>
                            <label for="encAncPatientId">Enc. Patient ID *</label>
                        </div>
                    </div>
                </div>
		<div class="row" style="margin-bottom:0;">
		    <div class="col s4">
			    <div class="input-field col m12 s12" style="margin-top:0.5rem;">
			    <input id="dob" name="dob" type="text" class="validate datepicker isRequired" title="Please enter DOB" value="<?php echo $patientDOB;?>" onchange="getDateOfBirth()">
			    <label for="dob" class="">DOB *</label>
			    </div>
		    </div>
		    <div class="col s4">
			<div class="input-field col m12 s12" style="margin-top:0.5rem;">
			    <input id="age" name="age" type="text" class="validate checkNum isRequired" title="Please enter patient age" value="<?php echo $row['age']; ?>">
			    <label for="age" class="">Age *</label>
			</div>
		    </div>
		    <div class="col s4">
			<div class="input-field col m12 s12" style="margin-top:0.5rem;">
			    <input id="gestationalAge" name="gestationalAge" type="text" class="checkNum validate" title="Please enter gestational age" value="<?php echo $row['gestational_age']; ?>">
			    <label for="gestationalAge" class="">Gestational Age </label>
			</div>
	            </div>
		</div>
            </fieldset>
            <fieldset style="border-color:#2196F3 ;border-style: solid;">
               <legend>LABORATORY INFORMATION</legend>
                <div class="row" style="margin-bottom:0;">
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <select id="lab" name="lab" class="material-select isRequired" title="Please select lab site code/name">
                                <option value=""> -- Select -- </option>
                                <?php
                                foreach($facilities as $facility){
                                ?>
                                  <option value="<?php echo base64_encode($facility['facility_id']); ?>" <?php echo($row->lab == $facility['facility_id'])?'selected="selected"':''; ?>><?php echo $facility['facility_code'].' - '.ucwords($facility['facility_name']); ?></option>
                                <?php } ?>
                            </select>
                            <label for="lab">Lab site code/name *</label>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <input id="labSpecimenId" name="labSpecimenId" type="text" class="validate isRequired" title="Please enter lab specimen ID" value="<?php echo $row->lab_specimen_id; ?>">
                            <label for="labSpecimenId" class="">Lab Specimen ID *</label>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <select id="rejectionReason" name="rejectionReason" class="material-select" title="Please select rejection code">
                                <option value=""> -- Select -- </option>
                                <?php
                                foreach($rejectionReasons as $rejection){
                                ?>
                                  <option value="<?php echo base64_encode($rejection['rejection_reason_id']); ?>" <?php echo(isset($row->rejection_reason) && $row->rejection_reason == $rejection['rejection_reason_id'])?'selected="selected"':''; ?>><?php echo $rejection['rejection_code']." - ".$rejection['rejection_reason']; ?></option>
                                <?php } ?>
                            </select>
                            <label for="rejectionReason">Specimen Rejection Code </label>
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-bottom:0;">
                    <div class="col s4">
                        <div class="input-field col m12 s12" style="margin-top:0;">
                            <input id="dateOfReceiptAtCentralLab" name="dateOfReceiptAtCentralLab" type="text" class="validate datepicker" title="Please enter date of receipt at central lab" value="<?php echo $receiptDateAtCentralLab; ?>">
                            <label for="dateOfReceiptAtCentralLab" class="">Date of Receipt at Central Lab </label>
                        </div>
                    </div>
                    <div class="col s4">
			<div class="input-field col m12 s12" style="margin-top:0;">
			    <input id="dateOfTestCompletion" name="dateOfTestCompletion" type="text" class="validate datepicker" title="Please enter date of test completion" value="<?php echo $testCompletionDate; ?>">
			    <label for="dateOfTestCompletion" class="">Date of Test Completion </label>
			</div>
		    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12" style="margin-top:0;">
                            <input id="dateOfResultDispatchedToClinic" name="dateOfResultDispatchedToClinic" type="text" class="validate datepicker" title="Please enter date of result dispatched to clinic" value="<?php echo $resultDispatchedDateToClinic; ?>">
                            <label for="dateOfResultDispatchedToClinic" class="">Date of Result Dispatched to Clinic </label>
                        </div>
                    </div>
                </div>
		<div class="row" style="margin-bottom:0;">
		    <div class="col s4">
		       <div class="input-field col m12 s12">
			   <select id="specimenType" name="specimenType" class="material-select" title="Please select speciment type">
				   <option value=""> -- Select -- </option>
				   <option value="1"<?php echo(isset($row->specimen_type) && $row->specimen_type == 1)?'selected="selected"':''; ?>>Venous</option>
				   <option value="2"<?php echo(isset($row->specimen_type) && $row->specimen_type == 2)?'selected="selected"':''; ?>>Plasma</option>
				   <option value="3"<?php echo(isset($row->specimen_type) && $row->specimen_type == 3)?'selected="selected"':''; ?>>DBS</option>
			   </select>
			   <label for="specimenType">Specimen Type </label>
		       </div>
		    </div>
	        </div>
            </fieldset>
            <fieldset style="border-color:#F44336;border-style: solid;">
                <legend>TEST RESULT</legend>
                <div class="row" style="margin-bottom:0;">
                    <div class="col s4">
                        <div class="input-field col m12 s12" style="margin-top:0.5rem;">
                            <input id="finalLagAvidityOdn" name="finalLagAvidityOdn" type="text" class="validate checkNum isRequired" title="Please enter final LAg avidity ODn" value="<?php echo $row->final_lag_avidity_odn; ?>">
                            <label for="finalLagAvidityOdn" class="">Final LAg Avidity ODn *</label>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12" style="margin-top:0.5rem;">
                            <input id="hivRna" name="hivRna" type="text" class="validate checkNum <?php echo($row->final_lag_avidity_odn > 2)?'':'isRequired'; ?>" title="Please enter HIV RNA" value="<?php echo $row->hiv_rna; ?>">
                            <label for="hivRna" class="">HIV RNA (copies/ml) <?php echo($row->final_lag_avidity_odn > 2)?'':'*'; ?></label>
                        </div>
                    </div>
                    <div class="col s4">
                        <a class="modal-trigger waves-effect waves-light product-panel-trigger" href="#panel">Click here to view the algorithm of lab data reporting</a>
                    </div>
                </div>
                <div class="row prePopulateSection" style="background-color:#ff69b4;color:#fff;border-radius:30px;margin-bottom:10px;">
                    <div class="col s4">
                        <div class="input-padding col m10 s10 prePopulateAvidity">
                          <strong>LAg Avidity Result</strong> <br>
                           <label for="lagAvidityResult" style="font-size:13px;color:#fff;"><?php echo $lAgAvidityResult; ?></label>
                          <input id="lagAvidityResultRecent" class="with-gap" name="lagAvidityResult" type="radio" <?php echo($row->lag_avidity_result == 'r')?'checked="checked"':''; ?> value="r" onclick="this.checked = false;" style="pointer-events:none !important;display:none;"/>
                          <label for="lagAvidityResultRecent" style="pointer-events:none !important;display:none;">R </label>&nbsp;
                          <input id="lagAvidityResultLongTerm" class="with-gap" name="lagAvidityResult" type="radio" <?php echo($row->lag_avidity_result == 'lt')?'checked="checked"':''; ?> value="lt" onclick="this.checked = false;" style="pointer-events:none !important;display:none;"/>
                          <label for="lagAvidityResultLongTerm" style="pointer-events:none !important;display:none;">LT </label>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-padding col m10 s10 prePopulateHIVRNA">
                          <strong>HIV RNA >= 1000 (copies/ml)</strong><br>
                           <label for="hivRnaGT1000" style="font-size:13px;color:#fff;"><?php echo $hIVRNAResult; ?></label>
                          <input id="hivRnaGT1000Yes" class="with-gap" name="hivRnaGT1000" type="radio" <?php echo($row->hiv_rna_gt_1000 == 'yes')?'checked="checked"':''; ?> value="yes" onclick="this.checked = false;" style="pointer-events:none !important;display:none;"/>
                          <label for="hivRnaGT1000Yes" style="pointer-events:none !important;display:none;">Yes </label>&nbsp;
                          <input id="hivRnaGT1000No" class="with-gap" name="hivRnaGT1000" type="radio" <?php echo($row->hiv_rna_gt_1000 == 'no')?'checked="checked"':''; ?> value="no" onclick="this.checked = false;" style="pointer-events:none !important;display:none;"/>
                          <label for="hivRnaGT1000No" style="pointer-events:none !important;display:none;">No </label>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-padding col m12 s12 prePopulateRecentInfection">
                          <strong>Recent Infection (LAg-R & RNA >= 1000)</strong><br>
                          <label for="recentInfection" style="font-size:13px;color:#fff;"><?php echo ucwords($row->recent_infection); ?></label>
                          <input id="recentInfectionYes" class="with-gap" name="recentInfection" type="radio" <?php echo($row->recent_infection == 'yes')?'checked="checked"':''; ?> value="yes" onclick="this.checked = false;" style="pointer-events:none !important;display:none;"/>
                          <label for="recentInfectionYes" style="pointer-events:none !important;display:none;">Yes </label>&nbsp;
                          <input id="recentInfectionNo" class="with-gap" name="recentInfection" type="radio" <?php echo($row->recent_infection == 'no')?'checked="checked"':''; ?> value="no" onclick="this.checked = false;" style="pointer-events:none !important;display:none;"/>
                          <label for="recentInfectionNo" style="pointer-events:none !important;display:none;">No </label>
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-bottom:10px;">
                    <div class="col s5">
                       <div class="input-padding col m12 s12">
                          Rapid Recency Assay (Eg. Assante)<br>
                          <div id="box-1">
                            <input id="asanteRapidRecencyAssayP" class="with-gap" name="asanteRapidRecencyAssayPn" type="radio" <?php echo($asanteRapidRecencyAssayPn == 'p')?'checked="checked"':''; ?> value="p"/>
                            <label for="asanteRapidRecencyAssayP">Positive </label><br>
                            <input id="asanteRapidRecencyAssayN" class="with-gap" name="asanteRapidRecencyAssayPn" type="radio" <?php echo($asanteRapidRecencyAssayPn == 'n')?'checked="checked"':''; ?> value="n"/>
                            <label for="asanteRapidRecencyAssayN">Negative </label><br>
			    <input type="text" class="checkNum" id="readerValue1" name="readerValue1" placeholder="Reader Value"/>
                          </div>
                          <div id="box-breaker" style="<?php echo($asanteRapidRecencyAssayPn == 'n')?'visibility:hidden;':''; ?>">&rArr;</div>
                          <div id="box-2" style="<?php echo($asanteRapidRecencyAssayPn == 'n')?'visibility:hidden;':''; ?>">
                            <input id="asanteRapidRecencyAssayR" class="with-gap asanteRapidRecencyAssayRlt" name="asanteRapidRecencyAssayRlt" type="radio" <?php echo($asanteRapidRecencyAssayRlt == 'r')?'checked="checked"':''; ?> value="r"/>
                            <label for="asanteRapidRecencyAssayR" class="asanteRapidRecencyAssayRlt">Recent </label><br>
                            <input id="asanteRapidRecencyAssayLt" class="with-gap asanteRapidRecencyAssayRlt" name="asanteRapidRecencyAssayRlt" type="radio" <?php echo($asanteRapidRecencyAssayRlt == 'lt')?'checked="checked"':''; ?> value="lt"/>
                            <label for="asanteRapidRecencyAssayLt" class="asanteRapidRecencyAssayRlt">Long Term </label><br>
			    <input type="text" class="checkNum" id="readerValue2" name="readerValue2" placeholder="Reader Value"/>
                          </div>
                        </div>
                    </div>
		    <div class="col s3">
                        <div class="input-field col m12 s12" style="margin-top:0.5rem;">
                            <input id="hivRnaNew" name="hivRnaNew" type="text" class="validate checkNum <?php echo($row->final_lag_avidity_odn > 2)?'':'isRequired'; ?>" title="Please enter HIV RNA" value="<?php echo $row->hiv_rna; ?>">
                            <label for="hivRnaNew" class="">HIV RNA (copies/ml) <?php echo($row->final_lag_avidity_odn > 2)?'':'*'; ?></label>
                        </div>
		    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <textarea id="comments" name="comments" class="materialize-textarea"><?php echo $row->comments; ?></textarea>
                            <label for="comments">Comments</label>
                        </div>
                    </div>
                </div>
		<!--<div class="row" style="margin-bottom:0;">
		    <div class="col s3">
                        <div class="input-field col m12 s12">
                            <select id="status" name="status" class="material-select" title="Please select status">
                                < ?php
                                foreach($allTestStatus as $testStatus){
                                ?>
                                  <option value="< ?php echo base64_encode($testStatus['test_status_id']); ?>" < ?php echo($row->status == $testStatus['test_status_id'])?'selected="selected"':''; ?>>< ?php echo ucwords($testStatus['test_status_name']); ?></option>
                                < ?php } ?>
                            </select>
                            <label for="status">Status </label>
                        </div>
                    </div>
		</div>-->
            </fieldset>
            <div class="col s12" style="margin-top:20px;">
                <input type="hidden" name="redirectUrl" value="<?php echo $link; ?>"/>
                <input type="hidden" name="chosenCountry" value="<?php echo $row->country; ?>"/>
                <input type="hidden" name="prevStatus" value="<?php echo $row->status; ?>"/>
		<input type="hidden" name="surveillanceId" id="surveillanceId" value="<?php echo $row->surveillance_id; ?>"/>
		<input type="hidden" name="formStatus" id="formStatus" value="<?php echo $row->status; ?>"/>
                <input id="dataCollectionId" name="dataCollectionId" type="hidden" value="<?php echo base64_encode($row->data_collection_id); ?>"/>
                <a href="<?php echo $link; ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="updateDataReporting();">UPDATE</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/moment.min.js' ?>"></script>
<script>
    $(document).ready(function(){
       $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 15, // Creates a dropdown of 15 years to control year
            format: 'dd/mm/yyyy',
            max: new Date('Today'),
            onSet: function(e){
		validateDataReportingDates();
	    }
        });
    });
    
    $('#hivRnaNew').on('keyup', function() {
	 $('label[for="hivRnaNew"]').css("transform", "translateY(-140%)"); 
        if($.trim($('#hivRnaNew').val())!= ''){
	   $('label[for="hivRna"]').css("transform", "translateY(-140%)");  
	   $('#hivRna').val($('#hivRnaNew').val());
	}else{
	   $('label[for="hivRna"]').css("transform", "translateY(0%)");  
	   $('label[for="hivRnaNew"]').css("transform", "translateY(0%)");  
	   $('#hivRna').val('');
	}
	populateResult('');
    });
    
    $('#hivRna').on('keyup', function() {
	$('label[for="hivRna"]').css("transform", "translateY(-140%)"); 
        if($.trim($('#hivRna').val())!= ''){
	   $('label[for="hivRnaNew"]').css("transform", "translateY(-140%)"); 
	   $('#hivRnaNew').val($('#hivRna').val());
	}else{
	   $('label[for="hivRnaNew"]').css("transform", "translateY(0%)");
	   $('label[for="hivRna"]').css("transform", "translateY(0%)");
	   $('#hivRnaNew').val('');
	}
	populateResult('');
    });
    
    //For Pre-populate Result
    $('#finalLagAvidityOdn').on('keyup', function() {
	populateResult('');
    });
    
    function populateResult(fromSource){
	if($.trim($('#finalLagAvidityOdn').val())== '' && $.trim($('#hivRna').val())== ''){
	    $('#hivRna,#hivRnaNew').addClass('isRequired');
	    $('label[for="hivRna"]').html('HIV RNA (copies/ml) *');
	    $('label[for="hivRnaNew"]').html('HIV RNA (copies/ml) *');
	    $('.prePopulateAvidity').css('visibility','hidden');
	    $('.prePopulateHIVRNA').css('visibility','hidden');
	    $('.prePopulateRecentInfection').css('visibility','hidden');
	    $('#lagAvidityResultRecent').prop('checked',false);
            $('#lagAvidityResultLongTerm').prop('checked',false);
	    $('#hivRnaGT1000Yes').prop('checked',false);
	    $('#hivRnaGT1000No').prop('checked',false);
	    $('#recentInfectionYes').prop('checked',false);
	    $('#recentInfectionNo').prop('checked',false);
	    $('label[for="lagAvidityResult"]').html('');
	    $('label[for="hivRnaGT1000"]').html('');
	    $('label[for="recentInfection"]').html('');
	}else{
	    if(parseFloat($('#finalLagAvidityOdn').val()) >2){
		$('#hivRna,#hivRnaNew').removeClass('isRequired');
		$('label[for="hivRna"]').html('HIV RNA (copies/ml)');
		$('label[for="hivRnaNew"]').html('HIV RNA (copies/ml)');
	        $('.prePopulateAvidity').css('visibility','visible');
	        $('label[for="lagAvidityResult"]').html('Long Term (Final ODn > 2.0)');
                $('#lagAvidityResultLongTerm').prop('checked',true);
	    }else if(parseFloat($('#finalLagAvidityOdn').val()) <= 2){
		$('#hivRna,#hivRnaNew').addClass('isRequired');
		$('label[for="hivRna"]').html('HIV RNA (copies/ml) *');
		$('label[for="hivRnaNew"]').html('HIV RNA (copies/ml) *');
		if(parseInt($('#hivRna').val()) < 1000){
	            $('.prePopulateAvidity').css('visibility','visible');
		    $('label[for="lagAvidityResult"]').html('Long Term (Final ODn <= 2.0 and HIV RNA < 1000 cp/mL)');
		    $('#lagAvidityResultLongTerm').prop('checked',true);
		}else if(parseInt($('#hivRna').val()) >= 1000){
	            $('.prePopulateAvidity').css('visibility','visible');
		    $('label[for="lagAvidityResult"]').html('Recent (Final ODn <= 2.0 and HIV RNA >= 1000 cp/mL)');
		    $('#lagAvidityResultRecent').prop('checked',true);
		}else{
	            $('.prePopulateAvidity').css('visibility','visible');
		    $('label[for="lagAvidityResult"]').html('Recent (Final ODn <= 2.0)');
		    $('#lagAvidityResultRecent').prop('checked',true);
		}
	    }else{
		$('#hivRna,#hivRnaNew').addClass('isRequired');
		$('label[for="hivRna"]').html('HIV RNA (copies/ml) *');
		$('label[for="hivRnaNew"]').html('HIV RNA (copies/ml) *');
		$('.prePopulateAvidity').css('visibility','hidden');
		$('label[for="lagAvidityResult"]').html('');
		$('#lagAvidityResultRecent').prop('checked',false);
		$('#lagAvidityResultLongTerm').prop('checked',false);
	    }
	    //Gt1000
	    if(parseInt($('#hivRna').val()) >= 1000){
		$('.prePopulateHIVRNA').css('visibility','visible');
		$('label[for="hivRnaGT1000"]').html('High Viral Load (>= 1000 cp/mL)');
		$('#hivRnaGT1000Yes').prop('checked',true);
	    }else if(parseInt($('#hivRna').val()) < 1000){
		$('.prePopulateHIVRNA').css('visibility','visible');
		$('label[for="hivRnaGT1000"]').html('Low Viral Load (< 1000 cp/mL)');
		$('#hivRnaGT1000No').prop('checked',true);
	    }else{
		$('.prePopulateHIVRNA').css('visibility','hidden');
		$('label[for="hivRnaGT1000"]').html('');
		$('#hivRnaGT1000Yes').prop('checked',false);
		$('#hivRnaGT1000No').prop('checked',false);
	    }
		
	    //Recent infection
	    if($('#lagAvidityResultRecent').is(':checked') && $('#hivRnaGT1000Yes').is(':checked')) {
		$('label[for="recentInfection"]').html('Yes');
		$('#recentInfectionYes').prop('checked',true);
	    }else{
		$('label[for="recentInfection"]').html('No');
		$('#recentInfectionNo').prop('checked',true);
	    }
	    //Showing result section
	    if($('#finalLagAvidityOdn').val()!= '' && $('#finalLagAvidityOdn').val() > 2){
	       $('.prePopulateRecentInfection').css('visibility','visible');
	    }else if($('#finalLagAvidityOdn').val()!= '' && $('#finalLagAvidityOdn').val() <= 2){
	       if($('#hivRna').val() == ''){
		  $('.prePopulateRecentInfection').css('visibility','hidden');
	       }else{
		  $('.prePopulateRecentInfection').css('visibility','visible');
	       }
	    }else{
	       $('.prePopulateRecentInfection').css('visibility','hidden');
	    }
	}
    }
    
    $('input[type=radio][name=asanteRapidRecencyAssayPn]').change(function() {
	if(this.value == 'p') {
	    $('#box-2,#box-breaker').css('visibility','visible');
	}else if(this.value == 'n'){
	    $('#box-2,#box-breaker').css('visibility','hidden');
	    $('#asanteRapidRecencyAssayLt').prop('checked',false);
	    $('#asanteRapidRecencyAssayR').prop('checked',false);
	}
    });
    
    function validateDataReportingDates(){
	var specimenCollectedDate = $('#specimenCollectedDate').val();
	var specimenPickedUpDateAtAnc = $('#specimenPickedUpDateAtAnc').val();
	var dateOfReceiptAtcentralLab = $('#dateOfReceiptAtCentralLab').val();
	var dateOfTestCompletion = $('#dateOfTestCompletion').val();
	var dateOfResultDispatchedToClinic = $('#dateOfResultDispatchedToClinic').val();
	splitSpecimenCollectedDate = specimenCollectedDate.split('/');
	splitSpecimenPickedUpDateAtAnc = specimenPickedUpDateAtAnc.split('/');
	splitReceiptAtCentralLabDate = dateOfReceiptAtcentralLab.split('/');
	splitTestCompletionDate = dateOfTestCompletion.split('/');
	splitResultDispatchedToClinicDate = dateOfResultDispatchedToClinic.split('/');
	specimenCollectedDate = splitSpecimenCollectedDate[2]+'-'+splitSpecimenCollectedDate[1]+'-'+splitSpecimenCollectedDate[0];
	specimenPickedUpDateAtAnc = splitSpecimenPickedUpDateAtAnc[2]+'-'+splitSpecimenPickedUpDateAtAnc[1]+'-'+splitSpecimenPickedUpDateAtAnc[0];
	dateOfReceiptAtcentralLab = splitReceiptAtCentralLabDate[2]+'-'+splitReceiptAtCentralLabDate[1]+'-'+splitReceiptAtCentralLabDate[0];
	dateOfTestCompletion = splitTestCompletionDate[2]+'-'+splitTestCompletionDate[1]+'-'+splitTestCompletionDate[0];
	dateOfResultDispatchedToClinic = splitResultDispatchedToClinicDate[2]+'-'+splitResultDispatchedToClinicDate[1]+'-'+splitResultDispatchedToClinicDate[0];
	//Check specimen coll./specimen picked up date at mnc
	if($.trim(specimenCollectedDate)!= '' && $.trim(specimenPickedUpDateAtAnc)!= ''){
	    if(moment(specimenCollectedDate).isAfter(specimenPickedUpDateAtAnc)) {
		alert('Specimen picked up date at anc could not be earlier than specimen collection date!');
		$('#specimenPickedUpDateAtAnc').val('');
	    }
	}
	//specimen picked up date at anc/receipt at central lab
	if($.trim(specimenPickedUpDateAtAnc)!= '' && $.trim(dateOfReceiptAtcentralLab)!= ''){
	    if(moment(specimenPickedUpDateAtAnc).isAfter(dateOfReceiptAtcentralLab)) {
		alert('Date of receipt at central lab could not be earlier than specimen picked up date!');
		$('#dateOfReceiptAtCentralLab').val('');
	    }
	}
	//receipt at central lab/test completion
	if($.trim(dateOfReceiptAtcentralLab)!= '' && $.trim(dateOfTestCompletion)!= ''){
	    if(moment(dateOfReceiptAtcentralLab).isAfter(dateOfTestCompletion)) {
		alert('Test completion date could not be earlier than date of receipt at central lab!');
		$('#dateOfTestCompletion').val('');
	    }
	}
	//Check test completion/result dispatched to clinic
	if($.trim(dateOfTestCompletion)!= '' && $.trim(dateOfResultDispatchedToClinic)!= ''){
	    if(moment(dateOfTestCompletion).isAfter(dateOfResultDispatchedToClinic)) {
		alert('Date of result dispatched to clinic could not be earlier than test completion date!');
		$('#dateOfResultDispatchedToClinic').val('');
	    }
	}
    }
    
    function updateDataReporting(){
        flag = deforayValidator.init({
            formId: 'editDataReportingForm'
        });
        
        if(flag){
	    if ($("#asanteRapidRecencyAssayP").is(":checked") && $("input[type=radio][name=asanteRapidRecencyAssayPn]").prop("checked")) {
	    $("#formStatus").val(1);
	    }else if ($("#asanteRapidRecencyAssayN").is(":checked")) {
		$("#formStatus").val(1);
	    }else{
		$("#formStatus").val(4);
	    }
	    $("form#editDataReportingForm :input").each(function(){
		if ($(this).val()=='' && $(this)[0]['id']!='' && $(this)[0]['id']!='readerValue1' && $(this)[0]['id']!='readerValue2') {
		    $("#formStatus").val(4);
		}
	    });
	    if($("#prevStatus").val()==2 && $("#formStatus").val()==1){
		$("#formStatus").val(2);
	    }
            document.getElementById('editDataReportingForm').submit();
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if(checkValue!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
    
    $('#ancPatientId').on('keyup',function(){
	if(this.value == ''){
	   $('label[for="encAncPatientId"]').css("transform", "translateY(0%)");
	   $('#encAncPatientId').val('');
	}else{
	   $('label[for="encAncPatientId"]').css("transform", "translateY(-140%)");
	   $.post("<?php echo $this->url('rot47'); ?>", {pId: this.value},
	    function(data) {
		$('#encAncPatientId').val(data);
	    });
	}
    });
    
    function getDateOfBirth(){
      var today = new Date();
      var dob = $("#dob").val();
      if($.trim(dob) == ""){
        $("#age").val("");
        return false;
      }
      
      var dd = today.getDate();
      var mm = today.getMonth();
      var yyyy = today.getFullYear();
      if(dd<10) {
        dd='0'+dd
      }
      if(mm<10) {
       mm='0'+mm
      }
      
      splitDob = dob.split("/");
      var dobDate = new Date(splitDob[1] + splitDob[2]+", "+splitDob[0]);
      var monthDigit = dobDate.getMonth();
      var dobYear = splitDob[2];
      var dobMonth = isNaN(monthDigit) ? 0 : (monthDigit);
      dobMonth = (dobMonth<10) ? '0'+dobMonth: dobMonth;
      var dobDate = (splitDob[0]<10) ? '0'+splitDob[0]: splitDob[0];
      
      var date1 = new Date(yyyy,mm,dd);
      var date2 = new Date(dobYear,dobMonth,dobDate);
      var diff = new Date(date1.getTime() - date2.getTime());
      if((diff.getUTCFullYear() - 1970) == 0){
        $("#age").val(diff.getUTCMonth()); // Gives month count of difference
		$('label[for="age"]').css("transform", "translateY(-140%)"); 
      }else{
		$('label[for="age"]').css("transform", "translateY(-140%)"); 
        $("#age").val((diff.getUTCFullYear() - 1970)); // Gives difference as year
      }
    }
</script>
