<?php
use Zend\Session\Container;
$loginContainer = new Container('employee');
?>
<style>
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        background-color: #eaeaea;
        border-bottom: 1px solid #ccc;
        padding: 10px 20px;
    }
    pre {
        max-height: 596px;
    }
    table.dataTable tbody td {
        padding: 8px 18px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        /*left: -184px*/

    }
	#dataCollectionDataTable_wrapper{
		overflow-x:scroll;
	}
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Data Collections</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Data Collections</a>
       </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <div class="col l12 m12 s12">
            <div class="card card-default table-height">
                <div class="card-header dataTable-header"><i class="zmdi zmdi-filter-list"></i> Data Collection List
		        <span style="float:right;"><a href="<?php echo $this->url('data-collection',array('action' => 'add')); ?>" style="color:#fff;"><i class="zmdi zmdi-plus-circle-o"></i> Add Data Collection</a></span>
                </div>
                <div class="card-content clearfix">
                    <table id="dataCollectionDataTable" class="responsive-table display dataTable">
                        <thead>
                            <tr>
                                <th>Surveillance ID</th>
                                <th>Specimen Collected Date</th>
				                <th>ANC site</th>
                                <th>ANC Patient ID</th>
                                <th>Specimen Picked Up Date at ANC</th>
                                <th>Lab site</th>
                                <th>Lab Specimen ID</th>
								<?php
                                if($loginContainer->roleCode =='CSC'){
                                ?>
                                  <th>Country</th>
								<?php } ?>
								<th>Status</th>
                                <th style="width:170px !important;">Action</th>
                            </tr>
                        </thead>
			            <tfoot>
                            <tr>
                                <th>Employee Name</th>
                                <th>Specimen Collected Date</th>
				                <th>ANC site</th>
                                <th>ANC Patient ID</th>
				                <th>Specimen Picked Up Date at ANC</th>
                                <th>Lab site</th>
                                <th>Lab Specimen ID</th>
								<?php
                                if($loginContainer->roleCode =='CSC'){
                                ?>
                                  <th>Country</th>
								<?php } ?>
								<th>Status</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
       oTable = $("#dataCollectionDataTable").DataTable({
        "bProcessing": true,
        "bServerSide": true,
         "aoColumns": [
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		<?php
		if($loginContainer->roleCode =='CSC'){
		?>
		  {"sClass":"center"},
		<?php } ?>
		{"sClass":"center"},
		{"sClass":"center","bSortable":false}
            ],
        "sAjaxSource": "<?php echo $this->url('data-collection',array('action' => 'index')); ?>",
         "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
       });
       
       $('.dataTables_filter').empty(); // clears the content generated
       $('.dataTables_filter').append(
                "<div class='input-field col s6 search-div right' style='width: 250px'>" +
                "    <i class='material-icons search-icon'>search</i> "+
                "    <input id='search-items' type='text' class='validate' />" +
                "    <label for='icon_prefix' class='search-label'>Search</label>   "+
                "</div>");
       $(document).on('keyup', "input[type='text']", function(){
                    var oTable = $('.dataTable').dataTable();
                    oTable.fnFilter($(this).val());
                });
    });
	
	function lockDataCollection(ID){
		 var conf = confirm("Are you sure you want to lock this data collection..?");
            if(conf){
                $.post("<?php echo $this->url('data-collection',array('action'=>'lock')); ?>", {dataCollectionId:ID},
                    function(data){
                        if($.trim(data) == 0 || $.trim(data) == ''){
                          alert("OOPS..");
                        }else{
                          oTable.draw();
                        }
                    });
            }
	}
	
	function unlockDataCollection(ID){
		 var conf = confirm("Are you sure you want to unlock this data collection..?");
            if(conf){
                $.post("<?php echo $this->url('data-collection',array('action'=>'unlock')); ?>", {dataCollectionId:ID},
                    function(data){
                        if($.trim(data) == 0 || $.trim(data) == ''){
                          alert("OOPS..");
                        }else{
                          oTable.draw();
                        }
                    });
            }
	}
	
	function requestToUnlock(ID){
		 var conf = confirm("Are you sure you want to send request for unlock this data collection..?");
            if(conf){
                $.post("<?php echo $this->url('data-collection',array('action'=>'send-request')); ?>", {dataCollectionId:ID},
                    function(data){
                        if($.trim(data) == 0 || $.trim(data) == ''){
                          alert("OOPS..");
                        }else{
                          oTable.draw();
                        }
                    });
            }
	}
</script>