<?php
use Zend\Session\Container;
$loginContainer = new Container('user');
if(!isset($countryId) || trim($countryId)== ''){
    $countryId = '';
    $link = "/data-collection";
}else{
    $link = "/data-collection/".base64_encode($countryId);
}
?>
<style>
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        background-color: #eaeaea;
        border-bottom: 1px solid #ccc;
        padding: 10px 20px;
    }
    pre {
        max-height: 596px;
    }
    table.dataTable tbody td {
        padding: 8px 18px;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        /*left: -184px*/

    }
    #dataCollectionDataTable_wrapper{
	overflow-x:scroll;
    }
    .dataTables_wrapper{
	overflow-x: scroll;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Data Reporting</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Data Reporting</a>
       </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <form id="addDataReportingForm" name="addDataReportingForm" method="post" action="<?php echo $this->url('add-data-collection',array('action'=>'add')); ?>">
        <div class="card">
            <div class="row">
                <div class="col s4">
                    <div class="input-field col m10 s10">
                        <input id="surveillanceId" name="surveillanceId" type="text" class="validate isRequired" title="Please enter surveillance ID" onblur="checkNameValidation('data_collection', 'surveillance_id', this, null,'The surveillance id that you entered already exist. Please enter different id.');">
                        <label for="surveillanceId" class="">Surveillance ID *</label>
                    </div>
                </div>
                <div class="col s4">
                    <div class="input-field col m10 s10">
                        <input id="specimenCollectedDate" name="specimenCollectedDate" type="text" class="validate datepicker" title="Please enter specimen collected date">
                        <label for="specimenCollectedDate" class="">Specimen Collected Date </label>
                    </div>
                </div>
		<div class="col s4">
                    <div class="input-field col m10 s10">
                        <select id="ancSite" name="ancSite" class="material-select isRequired" title="Please select ANC site">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($ancSites as $ancSite){
                            ?>
                              <option data-anc-site-code="<?php echo $ancSite['anc_site_code']; ?>" value="<?php echo base64_encode($ancSite['anc_site_id']); ?>"><?php echo $ancSite['anc_site_code'].' - '.ucwords($ancSite['anc_site_name']); ?></option>
                            <?php } ?>
                        </select>
                        <label for="ancSite">ANC site name *</label>
                    </div>
                </div>
            </div>
            <div class="row">
		<div class="col s4">
                    <div class="input-field col m10 s10">
                        <input id="ancPatientId" name="ancPatientId" type="text" class="validate isRequired" title="Please enter ANC patient ID">
                        <label for="ancPatientId" class="">ANC Patient ID * </label>
                    </div>
                </div>
                 <div class="col s4">
                    <div class="input-field col m10 s10">
                        <input id="age" name="age" type="text" class="validate checkNum" title="Please enter age">
                        <label for="age" class="">Age </label>
                    </div>
                </div>
		<div class="col s4">
                    <div class="input-field col m10 s10">
                        <input id="specimenPickedUpDateAtAnc" name="specimenPickedUpDateAtAnc" type="text" class="validate datepicker" title="Please enter specimen picked up date at anc">
                        <label for="specimenPickedUpDateAtAnc" class="">Specimen Picked Up Date at ANC </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s4">
                    <div class="input-field col m10 s10">
                        <select id="lab" name="lab" class="material-select isRequired" title="Please select lab site code/name">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($facilities as $facility){
                            ?>
                              <option value="<?php echo base64_encode($facility['facility_id']); ?>"><?php echo $facility['facility_code'].' - '.ucwords($facility['facility_name']); ?></option>
                            <?php } ?>
                        </select>
                        <label for="lab">Lab site code/name *</label>
                    </div>
                </div>
		<div class="col s4">
                    <div class="input-field col m10 s10">
                        <input id="labSpecimenId" name="labSpecimenId" type="text" class="validate" title="Please enter lab specimen ID">
                        <label for="labSpecimenId" class="">Lab Specimen ID </label>
                    </div>
                </div>
		<div class="col s4">
                    <div class="input-field col m10 s10">
                        <input id="dateOfReceiptAtCentralLab" name="dateOfReceiptAtCentralLab" type="text" class="validate datepicker" title="Please enter date of receipt at central lab">
                        <label for="dateOfReceiptAtCentralLab" class="">Date of Receipt at Central Lab </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s4">
                    <div class="input-field col m10 s10">
                        <select id="rejectionReason" name="rejectionReason" class="material-select" title="Please select rejection code">
                            <option value=""> -- Select -- </option>
                            <?php
                            foreach($rejectionReasons as $rejection){
                            ?>
                              <option value="<?php echo base64_encode($rejection['rejection_reason_id']); ?>"><?php echo $rejection['rejection_code']; ?></option>
                            <?php } ?>
                        </select>
                        <label for="rejectionReason">Specimen Rejection Code </label>
                    </div>
                </div>
                <div class="col s4">
                    <div class="input-field col m10 s10">
                        <input id="finalLagAvidityOdn" name="finalLagAvidityOdn" type="text" class="validate" title="Please enter final LAg avidity ODn">
                        <label for="finalLagAvidityOdn" class="">Final LAg Avidity ODn </label>
                    </div>
                </div>
		<div class="col s4">
                    <div class="input-padding col m10 s10">
                      LAg Avidity Result<br>
                      <input id="lagAvidityResultRecent" class="with-gap" name="lagAvidityResult" type="radio" value="r"/>
                     <label for="lagAvidityResultRecent">R </label>&nbsp;
                     <input id="lagAvidityResultLongTerm" class="with-gap" name="lagAvidityResult" type="radio" value="lt"/>
                     <label for="lagAvidityResultLongTerm">LT </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s4">
                    <div class="input-field col m10 s10">
                        <input id="hivRna" name="hivRna" type="text" class="validate" title="Please enter HIV RNA">
                        <label for="hivRna" class="">HIV RNA (copies/ml) </label>
                    </div>
                </div>
		<div class="col s4">
                    <div class="input-padding col m10 s10">
                      HIV RNA >= 1,000 (copies/ml)<br>
                      <input id="hivRnaGT1000Yes" class="with-gap" name="hivRnaGT1000" type="radio" value="yes"/>
                     <label for="hivRnaGT1000Yes">Yes </label>&nbsp;
                     <input id="hivRnaGT1000No" class="with-gap" name="hivRnaGT1000" type="radio" value="no"/>
                     <label for="hivRnaGT1000No">No </label>
                    </div>
                </div>
		<div class="col s4">
                    <div class="input-padding col m10 s10">
                      Recent Infection <br>(LAg-R & RNA >= 1,000)<br>
                      <input id="recentInfectionYes" class="with-gap" name="recentInfection" type="radio" value="yes"/>
                     <label for="recentInfectionYes">Yes </label>&nbsp;
                     <input id="recentInfectionNo" class="with-gap" name="recentInfection" type="radio" value="no"/>
                     <label for="recentInfectionNo">No </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s4">
                    <div class="input-field col m10 s10">
                        <input id="dateOfResultDispatchedToClinic" name="dateOfResultDispatchedToClinic" type="text" class="validate datepicker" title="Please enter date of result dispatched to clinic">
                        <label for="dateOfResultDispatchedToClinic" class="">Date of Result Dispatched to Clinic </label>
                    </div>
                </div>
                <div class="col s4">
                   <div class="input-padding col m10 s10">
                      Asante Rapid Recency Assay<br>
                      <input id="asanteRapidRecencyAssayP" class="with-gap" name="asanteRapidRecencyAssay" type="radio" value="p"/>
                      <label for="asanteRapidRecencyAssayP" style="padding-left:22px !important;">P </label>&nbsp;
                      <input id="asanteRapidRecencyAssayN" class="with-gap" name="asanteRapidRecencyAssay" type="radio" value="n"/>
                      <label for="asanteRapidRecencyAssayN" style="padding-left:22px !important;">N </label>
                      <input id="asanteRapidRecencyAssayR" class="with-gap" name="asanteRapidRecencyAssay" type="radio" value="r"/>
                      <label for="asanteRapidRecencyAssayR" style="padding-left:22px !important;">R </label>&nbsp;
                      <input id="asanteRapidRecencyAssayLT" class="with-gap" name="asanteRapidRecencyAssay" type="radio" value="lt"/>
                      <label for="asanteRapidRecencyAssayLT" style="padding-left:22px !important;">LT </label>
                    </div>
                </div>
            </div>
            <div class="col s12">
		<input type="hidden" name="chosenCountry" id="chosenCountry" value="<?php echo base64_encode($countryId);?>"/>
		<input type="hidden" name="chosenCountryId" id="chosenCountryId" value="<?php echo $link;?>"/>
                <a href="<?php echo $link;?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Cancel</a>
                <a href="javascript:void(0);" class="waves-effect waves-light btn-small white-text pink margin-bottom-10" onclick="addDataReporting();">ADD</a>&nbsp;&nbsp;
            </div>
        </div>
        </form>
    </div>
    <div class="row dashboard-wrapper content-container">
        <div class="col l12 m12 s12">
	    
            <div class="card card-default table-height">
                <div class="card-header dataTable-header"><i class="zmdi zmdi-filter-list"></i> Data Reporting List
		<a href="javascript:void(0)" class="waves-effect waves-light btn-small btn white-text custom-btn " onclick="$('#showhide').fadeToggle();return false;"><span>Manage Columns</span></a>
		<span style="display: none;position:absolute;z-index: 9999 !important;color:#333;font-size:12px;font-weight:bold;padding: 5px 0px 5px 5px;height: 250px;overflow-y: scroll;" id="showhide">
		<div class="row" style="background:#e0e0e0;float: right !important;padding: 15px;">
		    <div class="col-md-12" >
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="0" id="iCol0" data-showhide="surveillance_id" class="showhideCheckBox" /> <label for="iCol0">Surveillance ID</label>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="1" id="iCol1" data-showhide="specimen_collected_date" class="showhideCheckBox"  /> <label for="iCol1">Specimen Collected Date</label>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="2" id="iCol2" data-showhide="anc_site_name" class="showhideCheckBox"  /> <label for="iCol2">ANC site</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="3" id="iCol3" data-showhide="anc_patient_id" class="showhideCheckBox"  /> <label for="iCol3">ANC Patient ID</label>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="4" id="iCol4" data-showhide="age" class="showhideCheckBox" /> <label for="iCol4">Age</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="5" id="iCol5" data-showhide="facility_name" class="showhideCheckBox" /> <label for="iCol5">Facility Name</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="6" id="iCol6" data-showhide="specimen_picked_up_date_at_anc" class="showhideCheckBox" /> <label for="iCol6">specimen Picked Date</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="7" id="iCol7" data-showhide="lab_specimen_id" class="showhideCheckBox" /> <label for="iCol7">specimen ID</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="8" id="iCol8" data-showhide="receipt_date_at_central_lab" class="showhideCheckBox" /> <label for="iCol8">Receipt Date Central Date</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="9" id="iCol9" data-showhide="rejection_code" class="showhideCheckBox" /> <label for="iCol9">Rejection Code</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="10" id="iCol10" data-showhide="final_lag_avidity_odn" class="showhideCheckBox" /> <label for="iCol10">Final Avidity Result</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="11" id="iCol11" data-showhide="lag_avidity_result" class="showhideCheckBox" /> <label for="iCol11">Lag Avidity Result</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="12" id="iCol12" data-showhide="hiv_rna" class="showhideCheckBox" /> <label for="iCol12">Hiv RNA</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="13" id="iCol13" data-showhide="hiv_rna_gt_1000" class="showhideCheckBox" /> <label for="iCol13">Hiv RNA 1000/label> <br>
			</div>
			
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="14" id="iCol14" data-showhide="recent_infection" class="showhideCheckBox" /> <label for="iCol14">Recent Infection</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="15" id="iCol15" data-showhide="result_dispatched_date_to_clinic" class="showhideCheckBox" /> <label for="iCol15">Result Dispatch Date</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="16" id="iCol16" data-showhide="asante_rapid_recency_assy" class="showhideCheckBox" /> <label for="iCol16">asante_rapid_recency_assy</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="17" id="iCol17" data-showhide="result_mail_sent" class="showhideCheckBox" /> <label for="iCol17">Result Mail</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="18" id="iCol18" data-showhide="test_status_name" class="showhideCheckBox" /> <label for="iCol18">Test Status</label> <br>
			</div>
			<div class="col-md-3">
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="19" id="iCol19" data-showhide="added_on" class="showhideCheckBox" /> <label for="iCol19">Added On</label> <br>
			</div>
			<div class="col-md-3">
			    <input type="hidden" id = "countColumn" value="20"/>
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="20" id="iCol20" data-showhide="user_name" class="showhideCheckBox" /> <label for="iCol20">Added by</label> <br>
			</div>
			<?php
			if($loginContainer->roleCode =='CSC' && trim($countryId)== ''){
			?>
			<div class="col-md-3">
			    <input type="hidden" id = "countColumn" value="21"/>
				<input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="21" id="iCol21" data-showhide="country_name" class="showhideCheckBox" /> <label for="iCol21">Country Name</label> <br>
			</div>
			<?php } ?>
		    </div>
		</div>
		</span>
		</div>
                <div class="card-content clearfix">
                    <table id="dataReportingDataTable" class="responsive-table display dataTable">
                        <thead>
                            <tr>
                                <th>Surveillance ID</th>
                                <th>Specimen Collected Date</th>
				<th>ANC site</th>
				<th>ANC Patient ID</th>
                                <th>Age</th>
				<th>Facility Name</th>
                                <th>Specimen Picked Date</th>
                                <th>specimen ID</th>
				<th>Receipt Date Central Date</th>
				<th>Rejection Code</th>
				<th>Final Lag Avidity</th>
                                <th>Lag Avidity Result</th>
				<th>Hiv RNA</th>
                                <th>Hiv RNA 1000</th>
				<th>Recent Infection</th>
				<th>Result Dispatch Date</th>
                                <th>asante_rapid_recency_assy</th>
				<th>Result Mail</th>
                                <th>Test Status</th>
                                <th>Added On</th>
                                <th>Added by</th>
				<?php
                                if($loginContainer->roleCode =='CSC' && trim($countryId)== ''){
                                ?>
                                 <th>Country</th>
				<?php } ?>
                                <th style="width:120px !important;">Action</th>
                            </tr>
                        </thead>
			<tfoot>
                            <tr>
                                <th>Surveillance ID</th>
                                <th>Specimen Collected Date</th>
				<th>ANC site</th>
				<th>ANC Patient ID</th>
                                <th>Age</th>
                                <th>Facility Name</th>
                                <th>Specimen Picked Date</th>
                                <th>lab_specimen_id</th>
                                <th>Receipt Date Central Date</th>
                                <th>Rejection Code</th>
                                <th>Final Lag Avidity</th>
                                <th>Lag Avidity Result</th>
                                <th>Hiv RNA</th>
                                <th>Hiv RNA 1000</th>
                                <th>Recent Infection</th>
                                <th>Result Dispatch Date</th>
                                <th>asante_rapid_recency_assy</th>
                                <th>Result Mail</th>
                                <th>Test Status</th>
                                <th>Added On</th>
                                <th>Added by</th>
				<?php
                                if($loginContainer->roleCode =='CSC' && trim($countryId)== ''){
                                ?>
                                 <th>Country</th>
				<?php } ?>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var oTable = null;
    $(document).ready(function() {
	$("#showhide").hide();
       oTable = $('#dataReportingDataTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
	    "bStateSave" : true,
            "aoColumns": [
                {"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		{"sClass":"center"},
		<?php
		if($loginContainer->roleCode =='CSC' && trim($countryId)== ''){
		?>
		  {"sClass":"center"},
		<?php } ?>
		{"sClass":"center","bSortable":false}
            ],
            "aaSorting": [[1, "desc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('data-collection',array('action' => 'index')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                aoData.push({"name": "countryId", "value": '<?php echo $countryId; ?>'});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
       
       $("#showhide").hover(function(){}, function(){$(this).fadeOut('slow')});
        for(colNo=0;colNo <=$("#countColumn").val();colNo++){
            $("#iCol"+colNo).attr("checked",oTable.fnSettings().aoColumns[parseInt(colNo)].bVisible);
            if(oTable.fnSettings().aoColumns[colNo].bVisible){
                $("#iCol"+colNo+"-sort").show();    
            }else{
                $("#iCol"+colNo+"-sort").hide();    
            }
        }
       
       $('.dataTables_filter').empty(); // clears the content generated
       $('.dataTables_filter').append(
                "<div class='input-field col s6 search-div right' style='width: 250px'>" +
                "    <i class='material-icons search-icon'>search</i> "+
                "    <input id='search-items' type='text' class='validate' />" +
                "    <label for='icon_prefix' class='search-label'>Search</label>   "+
                "</div>");
       $(document).on('keyup', "input[type='text']", function(){
                    var oTable = $('.dataTable').dataTable();
                    oTable.fnFilter($(this).val());
                });
    });
    function fnShowHide(iCol){
        var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
        oTable.fnSetColumnVis( iCol, bVis ? false : true );
    }
	
    function lockDataCollection(ID){
	var conf = confirm("Are you sure you want to lock this data report..?");
	if(conf){
	    $.post("<?php echo $this->url('lock-data-collection'); ?>", {dataCollectionId:ID},
		function(data){
		    if($.trim(data) == 0 || $.trim(data) == ''){
		      alert("OOPS..");
		    }else{
		      oTable.draw();
		    }
		});
	}
    }
    
    function unlockDataCollection(ID){
	var conf = confirm("Are you sure you want to unlock this data report..?");
	if(conf){
	    $.post("<?php echo $this->url('unlock-data-collection'); ?>", {dataCollectionId:ID},
		function(data){
		    if($.trim(data) == 0 || $.trim(data) == ''){
		      alert("OOPS..");
		    }else{
		      oTable.draw();
		    }
		});
	}
    }
    
    function requestToUnlock(ID){
	var conf = confirm("Are you sure you want to send request to unlock this data report..?");
	if(conf){
	    $.post("<?php echo $this->url('data-collection',array('action'=>'send-request')); ?>", {dataCollectionId:ID},
		function(data){
		    if($.trim(data) == 0 || $.trim(data) == ''){
		      alert("OOPS..");
		    }else{
		      oTable.draw();
		    }
		});
	}
    }
    
    function searchDataCollectionData(){
       oTable.draw();
    }
	
    $(document).ready(function(){
       $('.datepicker').pickadate({
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 15, // Creates a dropdown of 15 years to control year
            format: 'dd/mm/yyyy'
        });
    });
    
    $('#hivRna').on('change', function() {
        if($.trim($('#hivRna').val())!= '' && parseInt($('#hivRna').val()) >= 1000){
            $('#hivRnaGT1000Yes').prop('checked',true);
            $('#hivRnaGT1000No').prop('checked',false);
            if($('#lagAvidityResultRecent').is(":checked")){
                $('#recentInfectionYes').prop('checked',true);
            }
        }else if($.trim($('#hivRna').val())!= '' && parseInt($('#hivRna').val()) < 1000){
            $('#hivRnaGT1000No').prop('checked',true);
            $('#hivRnaGT1000Yes').prop('checked',false);
            $('#recentInfectionNo').prop('checked',true);
        }else{
            $('#hivRnaGT1000Yes').prop('checked',false);
            $('#hivRnaGT1000No').prop('checked',false);
            $('#recentInfectionYes').prop('checked',false);
            $('#recentInfectionNo').prop('checked',false);
        }
    });
    
    $('input[type=radio][name=lagAvidityResult]').change(function() {
        if(this.value == 'r'){
            if($.trim($('#hivRna').val())!= '' && parseInt($('#hivRna').val()) >= 1000){
                $('#recentInfectionYes').prop('checked',true);
            }
        }else if(this.value == 'lt'){
            $('#recentInfectionNo').prop('checked',true);
        }
    });
    
    function addDataReporting(){
        flag = deforayValidator.init({
            formId: 'addDataReportingForm'
        });
        
        if(flag){
            document.getElementById('addDataReportingForm').submit();
        }
    }
    
    function checkNameValidation(tableName, fieldName, obj, fnct, msg){
        checkValue = document.getElementById(obj.id).value;
        if(checkValue!=''){
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, fnct: fnct},
            function(data) {
                if (data > 0){
                    alert(msg);
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                }else {
                    duplicateName = true;
                }
            });
        }
    }
</script>