<?php
use Application\Service\CommonService;
$common = new CommonService();
if(isset($countryId) && trim($countryId)!=''){
    $link = "/data-collection/".base64_encode($countryId);
}else{
    $link = "/data-collection";
}
$specimenCollectedDate = '';
if(isset($row->specimen_collected_date) && trim($row->specimen_collected_date)!= '' && $row->specimen_collected_date!= '0000-00-00'){
    $specimenCollectedDate = $common->viewDateFormat($row->specimen_collected_date);
}
$specimenPickedUpDateAtAnc = '';
if(isset($row->specimen_picked_up_date_at_anc) && trim($row->specimen_picked_up_date_at_anc)!= '' && $row->specimen_picked_up_date_at_anc!= '0000-00-00'){
    $specimenPickedUpDateAtAnc = $common->viewDateFormat($row->specimen_picked_up_date_at_anc);
}
$receiptDateAtCentralLab = '';
if(isset($row->receipt_date_at_central_lab) && trim($row->receipt_date_at_central_lab)!= '' && $row->receipt_date_at_central_lab!= '0000-00-00'){
    $receiptDateAtCentralLab = $common->viewDateFormat($row->receipt_date_at_central_lab);
}
$testCompletionDate = '';
if(isset($row->date_of_test_completion) && trim($row->date_of_test_completion)!= '' && $row->date_of_test_completion!= '0000-00-00'){
    $testCompletionDate = $common->viewDateFormat($row->date_of_test_completion);
}
$resultDispatchedDateToClinic = '';
if(isset($row->result_dispatched_date_to_clinic) && trim($row->result_dispatched_date_to_clinic)!= '' && $row->result_dispatched_date_to_clinic!= '0000-00-00'){
    $resultDispatchedDateToClinic = $common->viewDateFormat($row->result_dispatched_date_to_clinic);
}
$lAgAvidityResult = '';
if(trim($row->lag_avidity_result)!= '' && $row->lag_avidity_result == 'lt'){
    $lAgAvidityResult = 'Long Term';
}else if(trim($row->lag_avidity_result)!= '' && $row->lag_avidity_result == 'r'){
    $lAgAvidityResult = 'Recent';
}
$hIVRNAResult = '';
if(trim($row->hiv_rna_gt_1000)!= '' && $row->hiv_rna_gt_1000 =='yes'){
    $hIVRNAResult = 'High Viral Load';
}else if(trim($row->hiv_rna_gt_1000)!= '' && $row->hiv_rna_gt_1000 =='no'){
    $hIVRNAResult = 'Low Viral Load';
}
$asanteRapidRecencyAssay = '';
if(trim($row->asante_rapid_recency_assy)!= '' && $row->asante_rapid_recency_assy =='p/'){
    $asanteRapidRecencyAssay = 'Positive';
}else if(trim($row->asante_rapid_recency_assy)!= '' && $row->asante_rapid_recency_assy =='n/'){
    $asanteRapidRecencyAssay = 'Negative';
}else if(trim($row->asante_rapid_recency_assy)!= '' && $row->asante_rapid_recency_assy =='p/lt'){
    $asanteRapidRecencyAssay = 'Positive/Long Term';
}else if(trim($row->asante_rapid_recency_assy)!= '' && $row->asante_rapid_recency_assy =='n/lt'){
    $asanteRapidRecencyAssay = 'Negative/Long Term';
}else if(trim($row->asante_rapid_recency_assy)!= '' && $row->asante_rapid_recency_assy =='n/r'){
    $asanteRapidRecencyAssay = 'Negative/Recent';
}else if(trim($row->asante_rapid_recency_assy)!= '' && $row->asante_rapid_recency_assy =='p/r'){
    $asanteRapidRecencyAssay = 'Positive/Recent';
}
?>
<style>
    .data-collection-view .row{
        margin-bottom:0 !important;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Lab Data Reporting View</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="<?php echo $link; ?>" class="breadcrumb">Lab Data Reporting</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Lab Data Reporting View</a>
        </div>
    </div>
    <div class="row dashboard-wrapper content-container">
        <div class="data-collection-view card">
            <fieldset style="border-color:#88C542;border-style: solid;">
               <legend>SURVEILLANCE INFORMATION</legend>
                <div class="row">
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <label for="surveillanceId" class="">Surveillance ID </label><br>
                            <p><?php echo $row->surveillance_id; ?></p>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <label for="specimenCollectedDate" class="">Specimen Collected Date </label><br>
                            <p><?php echo $specimenCollectedDate; ?></p>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <label for="ancSite">ANC site name </label><br>
                            <p><?php echo $row->anc_site_code.' - '.ucwords($row->anc_site_name); ?></p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <label for="specimenPickedUpDateAtAnc" class="">Specimen Picked Up Date at ANC </label><br>
                            <p><?php echo $specimenPickedUpDateAtAnc; ?></p>
                        </div>
                    </div>
                </div>
            </fieldset>
            <fieldset style="border-color:#2196F3 ;border-style: solid;">
               <legend>LABORATORY INFORMATION</legend>
               <div class="row">
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <label for="lab">Lab site code/name </label><br>
                             <p><?php echo $row->facility_code.' - '.ucwords($row->facility_name); ?></p>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <label for="labSpecimenId" class="">Lab Specimen ID </label><br>
                            <p><?php echo $row->lab_specimen_id; ?></p>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <label for="rejectionReason">Specimen Rejection Code </label><br>
                            <p><?php if(isset($row->rejection_code)){ echo $row->rejection_code; } ?></p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <label for="dateOfReceiptAtCentralLab" class="">Date of Receipt at Central Lab </label><br>
                            <p><?php echo $receiptDateAtCentralLab; ?></p>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <label for="dateOfTestCompletion" class="">Date of Test Completion </label><br>
                            <p><?php echo $testCompletionDate; ?></p>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <label for="dateOfResultDispatchedToClinic" class="">Date of Result Dispatched to Clinic </label><br>
                            <p><?php echo $resultDispatchedDateToClinic; ?></p>
                        </div>
                    </div>
                </div>
            </fieldset>
            <fieldset style="border-color:#ff9800;border-style: solid;">
               <legend>PATIENT INFORMATION</legend>
                <div class="row">
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <label for="ancPatientId" class="">ANC Patient ID </label><br>
                            <p><?php echo $row->anc_patient_id; ?></p>
                        </div>
                    </div>
                     <div class="col s4">
                        <div class="input-field col m12 s12">
                            <label for="age" class="">Age </label><br>
                            <p><?php echo $row->age; ?></p>
                        </div>
                    </div>
                </div>
            </fieldset>
            <fieldset style="border-color:#F44336;border-style: solid;">
               <legend>TEST RESULT</legend>
                <div class="row" style="margin-bottom:0;">
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <label for="finalLagAvidityOdn" class="">Final LAg Avidity ODn </label><br>
                            <p><?php echo $row->final_lag_avidity_odn; ?></p>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                            <label for="hivRna" class="">HIV RNA (copies/ml) </label><br>
                            <p><?php echo $row->hiv_rna; ?></p>
                        </div>
                    </div>
                </div>
                <div class="row" style="background-color:#ff69b4;border-radius:30px;">
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                          <label for="lagAvidityResult" class="" style="color:#fff;"><strong>LAg Avidity Result</strong> </label><br>
                          <p style="font-size:13px;color:#fff;"><?php echo $lAgAvidityResult; ?></p>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                          <label for="hivRnaGT1000" class="" style="color:#fff;"><strong>HIV RNA >= 1,000 (copies/ml)</strong> </label><br>
                          <p style="font-size:13px;color:#fff;"><?php echo $hIVRNAResult; ?></p>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                          <label for="recentInfection" class="" style="color:#fff;"><strong>Recent Infection <br>(LAg-R & RNA >= 1,000)</strong> </label><br><br>
                          <p style="font-size:13px;color:#fff;"><?php echo ucfirst($row->recent_infection); ?></p>
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-bottom:20px !important;">
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                          <label for="asanteRapidRecencyAssay" class="">Rapid Recency Assay (Eg. Assante) </label><br>
                          <p><?php echo $asanteRapidRecencyAssay; ?></p>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                          <label for="comments" class=""> Comments </label><br>
                          <p><?php echo ucfirst($row->comments); ?></p>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="input-field col m12 s12">
                          <label for="status" class=""> Status </label><br>
                          <p><?php echo ucwords($row->test_status_name); ?></p>
                        </div>
                    </div>
                </div>
            </fieldset>
            <div class="col s12" style="margin-top:20px;">
                <a href="<?php echo $link; ?>" class="waves-effect waves-light btn-small btn pink-text custom-btn custom-btn-pink margin-bottom-10">Go back </a>
            </div>
        </div>
    </div>
</div>