<?php
use Zend\Session\Container;
$loginContainer = new Container('user');
$manage_columns = $this->GetManageColumns();
$sor_Columns = array();
if(isset($manage_columns) && isset($manage_columns->study_overview) && trim($manage_columns->study_overview)!= ''){
    $sor_Columns = json_decode($manage_columns->study_overview,true);
}
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/daterangepicker/daterangepicker.css' ?>"/>
<style>
    .ranges{display: none;}
    .daterangepicker .ranges{
        width: 190px;
    }
    @font-face {
        font-family: 'Glyphicons Halflings';
        src: url('../assets/fonts/glyphicons-halflings-regular.eot');
        src: url('../assets/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../assets/fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../assets/fonts/glyphicons-halflings-regular.woff') format('woff'), url('../assets/fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../assets/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
    }
    .glyphicon {
      position: relative;
      top: 1px;
      display: inline-block;
      font-family: 'Glyphicons Halflings';
      font-style: normal;
      font-weight: normal;
      line-height: 1;
    
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }
    .glyphicon-arrow-left:before {
      content: "\e091";
    }
    .glyphicon-arrow-right:before {
      content: "\e092";
    }
    .glyphicon-arrow-up:before {
      content: "\e093";
    }
    .glyphicon-arrow-down:before {
      content: "\e094";
    }
    *{
      -webkit-box-sizing: border-box;
         -moz-box-sizing: border-box;
              box-sizing: border-box;
    }
    *:before,
    *:after {
      -webkit-box-sizing: border-box;
         -moz-box-sizing: border-box;
              box-sizing: border-box;
    }
    /*.left{float: right !important;}*/
    #ms-dataCollection{
        width:100%;
    }
    .card-header{
        background-color:#ff69b4;
    }
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        padding: 10px 20px;
    }
    table th,table td{
        text-align:center;
    }
    .select-wrapper{
	width:100%;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        left: -184px;
    }
    .select-wrapper{
	width:100%;
    }
    .dataTable_noWrap{
	white-space: nowrap;
        overflow: hidden;
    }
    table.dataTable tbody td{
	padding:4px 4px 4px 4px;
    }
    @media only screen and (max-width: 1024px){
	table.dataTable.display tbody tr:first-child td {
	    border-top: 1px solid #ddd;
        }
	table.dataTable tbody td {
	    padding: 6px 4px 6px 4px;
	}
    }
    .redTxt{
	color:#F44336 !important;
    }
    .yellowTxt,.remove_sorting_1_style{
	background-color:#FFFF00 !important;
    }
    table.dataTable.display tbody tr.yellowTxt > .sorting_1{
	background-color:#FFFF00 !important;
    }

    table.dataTable thead th, table.dataTable thead td,
    table.dataTable tfoot th, table.dataTable tfoot td{
	text-align:center;
    }

    table.dataTable thead th, table.dataTable thead td,
    table.dataTable tfoot th, table.dataTable tfoot td,
    table.dataTable.row-border tbody th, 
    table.dataTable.row-border tbody td, 
    table.dataTable.display tbody th, 
    table.dataTable.display tbody td{
      border: 1px solid #eeeeef;
    }
    .labBorder-left{
        border-left:1px solid #888 !important;
    }
    .labBorder-right{
        border-right:1px solid #888 !important;
    }
    .labBorder-top{
        border-top:1px solid #888 !important;
    }
    .labBorder-bottom{
        border-bottom:1px solid #888 !important;
    }
    #double-scroll{
	width: 100%;
    }
    .suwala-doubleScroll-scroll-wrapper{
	padding-left:58% !important;
    }
</style>
<div id="page-content">
    <div class="row section-header">
	<div class="col m6 s12 left-align" style="font-size: 34px;font-weight:400;">Study Overview Report (<?php echo (isset($countryInfo->country_name) && trim($countryInfo->country_name)!= '')?ucwords($countryInfo->country_name):'#'; ?>)</div>
        <div class="col m6 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">Study Overview Report</a>
        </div>
    </div>
    <div id="showhide" class="row" style="display: none;position:absolute;z-index: 9999 !important;color:#333;font-size:12px;font-weight:bold;padding: 5px 0px 5px 5px;height:auto;background:#e0e0e0;">
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="0" id="iCol0" data-showhide="location_name" data-label="Lab Province/State" class="showhideCheckBox" /> <label for="iCol0">Lab Province/<br>State</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="1" id="iCol1" data-showhide="patient_barcode_id" data-label="Patient Barcode ID" class="showhideCheckBox" /> <label for="iCol1">Patient <br>Barcode ID</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="2" id="iCol2" data-showhide="specimen_collected_date" data-label="Specimen Collected Date" class="showhideCheckBox" /> <label for="iCol2">Specimen <br>Collection Date</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="3" id="iCol3" data-showhide="anc_site_name" data-label="ANC Site" class="showhideCheckBox" /> <label for="iCol3">ANC Site</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="4" id="iCol4" data-showhide="specimen_picked_up_date_at_anc" data-label="Specimen Pick Up Date at ANC" class="showhideCheckBox" /> <label for="iCol4">Specimen <br>Pick Up Date <br>at ANC</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="5" id="iCol5" data-showhide="specimen_type" data-label="Specimen Type" class="showhideCheckBox" /> <label for="iCol5">Specimen Type</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="6" id="iCol6" data-showhide="anc_patient_id" data-label="ANC Patient ID" class="showhideCheckBox" /> <label for="iCol6">ANC <br>Patient ID</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="7" id="iCol7" data-showhide="art_patient_id" data-label="ART Number" class="showhideCheckBox" /> <label for="iCol7">ART Number</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="8" id="iCol8" data-showhide="patient_dob" data-label="DOB" class="showhideCheckBox" /> <label for="iCol8">DOB</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="9" id="iCol9" data-showhide="age" data-label="Age" class="showhideCheckBox" /> <label for="iCol9">Age</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="10" id="iCol10" data-showhide="gestational_age" data-label="Gestation Age (Weeks)" class="showhideCheckBox" /> <label for="iCol10">Gestation <br>Age (Weeks)</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="11" id="iCol11" data-showhide="facility_name" data-label="Lab/Facility" class="showhideCheckBox" /> <label for="iCol11">Lab/Facility</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="12" id="iCol12" data-showhide="rejection_reason" data-label="Rejection Reason" class="showhideCheckBox" /> <label for="iCol12">Rejection Reason</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="13" id="iCol13" data-showhide="receipt_date_at_central_lab" data-label="Receipt Date at Lab" class="showhideCheckBox" /> <label for="iCol13">Receipt Date <br>at Lab</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="14" id="iCol14" data-showhide="lab_tech_name" data-label="Lab Tech. Name/ID" class="showhideCheckBox" /> <label for="iCol14">Lab Tech. <br>Name/ID</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="15" id="iCol15" data-showhide="date_of_test_completion" data-label="Date of Test Completion" class="showhideCheckBox" /> <label for="iCol15">Date of Test <br>Completion</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="16" id="iCol16" data-showhide="result_dispatched_date_to_clinic" data-label="Result Dispatched Date to Clinic" class="showhideCheckBox" /> <label for="iCol16">Result <br>Dispatched Date <br>to Clinic</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="17" id="iCol17" data-showhide="final_lag_avidity_odn" data-label="LAg Avidity" class="showhideCheckBox" /> <label for="iCol17">LAg Avidity</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="18" id="iCol18" data-showhide="lag_avidity_result" data-label="LAg Recency Assay" class="showhideCheckBox" /> <label for="iCol18">LAg Recency <br>Assay</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="19" id="iCol19" data-showhide="hiv_rna" data-label="HIV RNA (cp/ml)" class="showhideCheckBox" /> <label for="iCol19">HIV RNA(cp/ml)</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="20" id="iCol20" data-showhide="recent_infection" data-label="Recent Infection" class="showhideCheckBox" /> <label for="iCol20">Recent Infection</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="21" id="iCol21" data-showhide="asante_rapid_recency_assy_rrdt" data-label="Lab Positive Verification Line (Visual)" class="showhideCheckBox" /> <label for="iCol21">Lab Positive <br>Verification <br>Line(Visual)</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="22" id="iCol22" data-showhide="asante_rapid_recency_assy_rrr" data-label="Lab Long Term Line (Visual)" class="showhideCheckBox" /> <label for="iCol22">Lab Long Term<br>Line(Visual)</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="23" id="iCol23" data-showhide="HIV_diagnostic_line" data-label="ANC Positive Verification Line" class="showhideCheckBox" /> <label for="iCol23">ANC Positive <br>Verification <br>Line(Visual)</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="24" id="iCol24" data-showhide="recency_line" data-label="ANC Long Term Line" class="showhideCheckBox" /> <label for="iCol24">ANC Long Term <br>Line</label>
	</div>
	<div class="col m3">
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="25" id="iCol25" data-showhide="test_status_name" data-label="Lab Data Status" class="showhideCheckBox" /> <label for="iCol25">Lab Data <br>Status</label>
	</div>
	<div class="col m3">
	    <input type="hidden" id="countColumn" value="26"/>
	    <input type="checkbox" onclick="javascript:fnShowHide(this.value);" value="26" id="iCol26" data-showhide="assessment_id" data-label="Behaviour Data Recorded" class="showhideCheckBox" /> <label for="iCol26">Behaviour Data <br>Recorded</label>
	</div>
    </div>
    <div class="row" style="max-width:1109px;">
	<form id="overviewFilter" action="#">
	    <div class="row">
		<div class="col s4">
		    <div class="input-field col m12 s12">
			<input id="specimenCollectedDate" name="specimenCollectedDate" type="text" class="" title="Please enter specimen collected date" onclick="selectSampleCollectionDate();" readonly>
			<label for="specimenCollectedDate">Specimen Collected Date </label>
		    </div>
		</div>
		<div class="col s4">
		    <div class="input-field col m12 s12">
			<input id="sampleTestedDate" name="sampleTestedDate" type="text" class="" title="Please enter sample tested date" onclick="selectSampleTestedDate();" readonly>
			<label for="sampleTestedDate">Specimen Tested Date </label>
		    </div>
		</div>
		<div class="col s4">
		    <div class="input-field col m12 s12">
			<select class="material-select" id="province" name="province" title="Please select province">
			    <option value=""> All Provinces </option>
			    <?php foreach($provinces as $province) { ?>
			       <option value="<?php echo base64_encode($province['location_id']); ?>"><?php echo ucwords($province['location_name']); ?></option>
			    <?php } ?>
			</select>
			<label for="province">Province </label>
		    </div>
		</div>
	    </div>
	    <div class="row">
		<div class="col s4">
		    <div class="input-field col m12 s12">
			<select class="material-select" id="specimenType" name="specimenType[]" multiple="multiple" title="Please select speciment type">
			    <option value="" disabled selected> All Sample Types </option>
			    <option value="1">Venous</option>
			    <option value="2">Plasma</option>
			    <option value="3">DBS</option>
			</select>
			<label for="specimenType">Sample Type </label>
		    </div>
		</div>
		<div class="col s4">
		    <div class="input-field col m12 s12">
			<select class="material-select" id="finalLagAvidityOdn" name="finalLagAvidityOdn" title="Please select LAg avidity odn">
			    <option value=""> -- Select -- </option>
			    <option value="lt2"> <=2 </option>
			    <option value="gt2"> >2 </option>
			</select>
			<label for="LAg">LAg Avidity ODn </label>
		    </div>
		</div>
		<div class="col s4">
		    <div class="input-field col m12 s12">
			<select class="material-select" id="hivRna" name="hivRna" title="Please select HIV rna value">
			    <option value=""> -- Select -- </option>
			    <option value="lte1000"> <=1000 </option>
			    <option value="gt1000"> >1000 </option>
			</select>
			<label for="hivRna">Viral Load </label>
		    </div>
		</div>
	    </div>
	    <div class="row">
		<div class="col s4">
		    <div class="input-field col m12 s12">
			<select class="material-select" id="asanteRapidRecencyAssayRlt" name="asanteRapidRecencyAssayRlt">
			    <option value=""> -- Select -- </option>
			    <option value="recent"> Recent </option>
			    <option value="long term"> Long Term </option>
			</select>
			<label for="asanteRapidRecencyAssayRlt">Rapid Recency Assay </label>
		    </div>
		</div>
	    </div>
	    <div class="col l12 m12 s12" style="text-align:center;">
		<a href="javascript:void(0);" onclick="clearSearchFields();" class="waves-effect waves-light btn-small btn red-text custom-btn custom-btn-red"><i class="zmdi zmdi-refresh"></i> Reset Filters</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="searchStudyOverviewData();" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="extractOverviewData();" class="waves-effect waves-light btn-small btn green-text custom-btn custom-btn-green"><i class="zmdi zmdi-collection-text"></i> Export Excel</a>
	    </div>
	</form>
    </div>
    <div class="row content-container">
	<div class="col l12 m12 s12">
	    <div class="card card-default">
		<div class="card-header white-text"><i class="zmdi zmdi-filter-list"></i> Study Overview
		    <span style="float:right;"><a href="javascript:void(0)" onclick="$('#showhide').fadeToggle();return false;" style="color:#fff;"><i class="zmdi zmdi-plus-circle-o-duplicate"></i> Manage Columns</a></span>
		</div>
		<div id="double-scroll" class="card-content clearfix">
		    <table id="studyOverviewDataTable" class="responsive-table display dataTable">
			<thead>
			<tr>
			    <th colspan="15" style="border-top:none;border-left:none;"></th>
			    <th colspan="8" style="background:#ffffee;" class="labBorder-top labBorder-right labBorder-left">LAB RESULTS</th>
			    <th colspan="2" style="background:#ffffee;">ANC RESULTS</th>
			    <th colspan="2" style="border-top:none;border-left:none;"></th>
			</tr>
			<tr>
			    <th>Lab<br>Province/<br>State</th>
			    <th>Patient<br>Barcode<br>ID</th>
			    <th>Specimen<br>Collection<br>Date</th>
			    <th>ANC Site</th>
			    <th>Specimen <br>Pick Up Date <br>at ANC</th>
			    <th>Specimen Type</th>
			    <th>ANC <br>Patient ID</th>
			    <th>ART Number</th>
			    <th>DOB</th>
			    <th>Age</th>
			    <th>Gestation <br>Age (Weeks)</th>
			    <th>Lab/Facility</th>
			    <th>Rejection<br>Reason</th>
			    <th>Receipt Date <br>at Lab</th>
			    <th>Lab Tech.<br>Name/ID</th>
			    <th>Date of <br>Test <br>Completion</th>
			    <th>Result <br>Dispatched<br>Date to Clinic</th>
			    <th>LAg Avidity</th>
			    <th>LAg<br>Recency<br>Assay</th>
			    <th>HIV RNA<br>(cp/ml)</th>
			    <!--<th>HIV RNA > 1000</th>-->
			    <th>Recent<br>Infection</th>
			    <th>Lab Positive<br>Verification<br>Line<br>(Visual)</th>
			    <th>Lab Long<br>Term Line<br>(Visual)</th>
			    <th>ANC Positive<br>Verification<br>Line</th>
			    <th>ANC Long<br>Term Line</th>
			    <th>Lab<br>Data<br>Status</th>
			    <th>Behaviour<br>Data<br>Recorded</th>
			</tr>
			</thead>
			<tfoot>
			<tr>
			    <th>Lab<br>Province/<br>State</th>
			    <th>Patient<br>Barcode<br>ID</th>
			    <th>Specimen<br>Collection<br>Date</th>
			    <th>ANC Site</th>
			    <th>Specimen <br>Pick Up Date <br>at ANC</th>
			    <th>Specimen Type</th>
			    <th>ANC <br>Patient ID</th>
			    <th>ART Number</th>
			    <th>DOB</th>
			    <th>Age</th>
			    <th>Gestation <br>Age (Weeks)</th>
			    <th>Lab/Facility</th>
			    <th>Rejection<br>Reason</th>
			    <th>Receipt Date <br>at Lab</th>
			    <th>Lab Tech.<br>Name/ID</th>
			    <th class="labBorder-bottom">Date of <br>Test <br>Completion</th>
			    <th class="labBorder-bottom">Result <br>Dispatched<br>Date to Clinic</th>
			    <th class="labBorder-bottom">LAg Avidity</th>
			    <th class="labBorder-bottom">LAg<br>Recency<br>Assay</th>
			    <th class="labBorder-bottom">HIV RNA<br>(cp/ml)</th>
			    <!--<th class="labBorder-bottom">HIV RNA > 1000</th>-->
			    <th class="labBorder-bottom">Recent<br>Infection</th>
			    <th class="labBorder-bottom">Lab Positive<br>Verification<br>Line<br>(Visual)</th>
			    <th class="labBorder-bottom">Lab Long<br>Term Line<br>(Visual)</th>
			    <th>ANC Positive<br>Verification<br>Line</th>
			    <th>ANC Long<br>Term Line</th>
			    <th>Lab<br>Data<br>Status</th>
			    <th>Behaviour<br>Data<br>Recorded</th>
			</tr>
			</tfoot>
			<tbody>
			</tbody>
		    </table>
		</div>
	    </div>
	</div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery-ui.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery.doubleScroll.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/daterangepicker/daterangepicker.js' ?>"></script>
<script>
    var manageColumns = [];
    $(document).ready(function(){
       $('#double-scroll').doubleScroll();
       $('.suwala-doubleScroll-scroll-wrapper').css('width','');
       oTable = $('#studyOverviewDataTable').dataTable({
	    "autoWidth": false,
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
	    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
	    "iDisplayLength": 25,
            "aoColumns": [
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"labBorder-left dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"labBorder-right dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap"},
		{"sClass":"dataTable_noWrap","bSortable":false}
            ],
	    "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
		var LAgAssay = aData[18];
		var labHIVVerificationClassification = aData[21];
		var labHIVRecencyClassification = aData[22];
		var ancHIVVerificationClassification = aData[23].replace("-", "");
		var ancHIVRecencyClassification = aData[24].replace("-", "");
		recencyMismatch = false;
		if($.trim(LAgAssay)!= '' && $.trim(labHIVRecencyClassification)!= '' && $.trim(ancHIVRecencyClassification)!= ''){
		    if((LAgAssay == 'Recent' && labHIVRecencyClassification == 'Absent') && (labHIVRecencyClassification == ancHIVRecencyClassification)){
			recencyMismatch = false;
		    }else if((LAgAssay == 'Long Term' && labHIVRecencyClassification == 'Present') && (labHIVRecencyClassification == ancHIVRecencyClassification)){
		       recencyMismatch = false;
		    }else{
			recencyMismatch = true;
		    }
		}
		if($.trim(aData[25].replace(/<\/?[^>]+(>|$)/g, "")) == "Incomplete"){
		    $("td:eq(3)", nRow).addClass("remove_sorting_1_style");
		    $(nRow).addClass("yellowTxt");
		}else if(aData[21] =='Absent' || (aData[18] == 'Long Term' && aData[22] == 'Absent') || (aData[18] == 'Recent' && aData[22] == 'Present') || recencyMismatch === true){
		    $(nRow).addClass("redTxt");
		}
	    },
            "aaSorting": [[2, "desc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('study-overview-report'); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
		aoData.push({"name": "country", "value": '<?php echo $countryInfo->country_id; ?>' });
		aoData.push({"name": "sampleCollectedDate", "value": $('#specimenCollectedDate').val()});
		aoData.push({"name": "sampleTestedDate", "value": $('#sampleTestedDate').val()});
		aoData.push({"name": "province", "value": $('#province').val()});
		aoData.push({"name": "specimenType", "value": $('#specimenType').val()});
		aoData.push({"name": "finalLagAvidityOdn", "value": $('#finalLagAvidityOdn').val()});
		aoData.push({"name": "hivRna", "value": $('#hivRna').val()});
		aoData.push({"name": "asanteRapidRecencyAssayRlt", "value": $('#asanteRapidRecencyAssayRlt').val()});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
       
        $("#showhide").hover(function(){}, function(){$(this).fadeOut('slow')});
       <?php if(count($sor_Columns) >0){
	    for($col=0;$col<count($sor_Columns);$col++){ ?>
	      var colNo = '<?php echo $col; ?>';
	      var data_All = {
		  'data_Column':'<?php echo $sor_Columns[$col]['data_Column']; ?>',
		  'data_Label':'<?php echo $sor_Columns[$col]['data_Label']; ?>',
		  'data_Visible':'<?php echo $sor_Columns[$col]['data_Visible']; ?>'
		  };

	      if(data_All.data_Visible == '1'){
		  $("#iCol"+colNo).attr("checked",oTable.fnSettings().aoColumns[parseInt(colNo)].bVisible);
	      }else{
		  var bVis = oTable.fnSettings().aoColumns[colNo].bVisible;
		  oTable.fnSetColumnVis( colNo, bVis ? false : true );
	      }
	      manageColumns.push(data_All);
	<?php } } else { ?>
            for(colNo=0;colNo <= $("#countColumn").val();colNo++){
		$("#iCol"+colNo).attr("checked",oTable.fnSettings().aoColumns[parseInt(colNo)].bVisible);
		var data_All = {
		    'data_Column':$("#iCol"+colNo).attr('data-showhide'),
		    'data_Label':$("#iCol"+colNo).attr('data-label'),
		    'data_Visible':1
		    };
		manageColumns.push(data_All);
	    }
	<?php } ?>
	//console.log(manageColumns);
        $('.dataTables_filter').empty(); // clears the content generated
        $('.dataTables_filter').append(
                "<div class='input-field col s6 search-div right' style='width: 250px'>" +
                "    <i class='material-icons search-icon'>search</i> "+
                "    <input id='search-items' type='text' class='validate' />" +
                "    <label for='icon_prefix' class='search-label'>Search</label>   "+
                "</div>");
        $(document).on('keyup', "input[type='text']", function(){
                    var oTable = $('.dataTable').dataTable();
                    oTable.fnFilter($(this).val());
                });
        selectSampleCollectionDate();
        selectSampleTestedDate();
    });
    
    function selectSampleCollectionDate(){
        $(".ranges").show();
        $(".left").css({"float":"none !important"});
        $('#specimenCollectedDate').daterangepicker({
            format: 'DD-MMM-YYYY',
	    separator: ' to ',
            maxDate: moment(),
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                'Last 7 Days': [moment().subtract('days', 6), moment()],
                'Last 30 Days': [moment().subtract('days', 29), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
            },
        },function(start, end) {
            startDate = start.format('YYYY-MM-DD');
            endDate = end.format('YYYY-MM-DD');
            $('label[for="specimenCollectedDate"]').css("transform", "translateY(-140%)");
        });
        $('.applyBtn').addClass('waves-effect waves-light btn-small white-text blue margin-bottom-10');
        $('.cancelBtn').addClass('waves-effect waves-light btn-small btn blue-text custom-btn custom-btn-blue margin-bottom-10');
    }
    
    function selectSampleTestedDate(){
        $(".ranges").show();
        $(".left").css({"float":"none !important"});
        $('#sampleTestedDate').daterangepicker({
            format: 'DD-MMM-YYYY',
	    separator: ' to ',
            maxDate: moment(),
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                'Last 7 Days': [moment().subtract('days', 6), moment()],
                'Last 30 Days': [moment().subtract('days', 29), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
            },
        },function(start, end) {
            startDate = start.format('YYYY-MM-DD');
            endDate = end.format('YYYY-MM-DD');
            $('label[for="sampleTestedDate"]').css("transform", "translateY(-140%)");
        });
        $('.applyBtn').addClass('waves-effect waves-light btn-small white-text blue margin-bottom-10');
        $('.cancelBtn').addClass('waves-effect waves-light btn-small btn blue-text custom-btn custom-btn-blue margin-bottom-10');
    }
    
    function searchStudyOverviewData(){
        oTable.fnDraw(false);
    }
    
    function clearSearchFields(){
       $('#overviewFilter')[0].reset();
       searchStudyOverviewData();
    }
    
    function fnShowHide(iCol){
        var bVis = oTable.fnSettings().aoColumns[iCol].bVisible;
        oTable.fnSetColumnVis( iCol, bVis ? false : true );
	var col_Name = $("#iCol"+iCol).attr('data-showhide');
	for(var columns in manageColumns){
	    for (var prop in manageColumns[columns]) {
		if(manageColumns[columns][prop] == col_Name){
		    if($("#iCol"+iCol).is(':checked')){
		      manageColumns[columns]['data_Visible'] = 1;
		    }else{
		      manageColumns[columns]['data_Visible'] = 0;
		    }
		}
	    }
	}
	manageSORColumns();
    }
    
    function manageSORColumns(){
	$.post("<?php echo $this->url('common',array('action'=>'manage-columns')); ?>", {tblColumns:manageColumns,frmSrc:'study_overview'},
	function(data){
	});
    }
    
    function extractOverviewData(){
        $.blockUI();
	$.post("<?php echo $this->url('export-study-overview'); ?>", { },
	function(data){
	    if(data == "" || data == null || data == undefined){
		alert('Error-Oops, Unable to generate excel');
		$.unblockUI();
	    }else{
		$.unblockUI();
		window.open("/temporary/"+data, "_blank");
	    }
	});
    }
</script>