<?php
if(count($response) >0){
    $samplesReceivedArray = array();
    $samplesIncompleteArray = array();
    $samplesTestedArray = array();
    $samplesFinalizedArray = array();
    $noofLAgRecentArray = array();
    $noofLabRecencyAssayRecentArray = array();
    $assessmentsArray = array();
    $noofANCRecencyTestRecentArray = array();
    foreach($response as $country){
        $assessments = 0;
        $noofANCRecencyTest = 0;
        if(isset($country[$country['monthName'].' - '.$country['year']])){
          $assessments = (isset($country[$country['monthName'].' - '.$country['year']]->assessments))?$country[$country['monthName'].' - '.$country['year']]->assessments:0;
          $noofANCRecencyTestRecent = (isset($country[$country['monthName'].' - '.$country['year']]->noofANCRecencyTestRecent))?$country[$country['monthName'].' - '.$country['year']]->noofANCRecencyTestRecent:0;
        }
        $samplesReceivedArray[] = $country['totalSample'];
        $samplesIncompleteArray[] = $country['samplesIncomplete'];
        $samplesTestedArray[] = $country['samplesTested'];
        $samplesFinalizedArray[] = $country['samplesFinalized'];
        $noofLAgRecentArray[] = $country['noofLAgRecent'];
        $noofLabRecencyAssayRecentArray[] = $country['noofLabRecencyAssayRecent'];
        $assessmentsArray[] = $assessments;
        $noofANCRecencyTestRecentArray[] = $noofANCRecencyTestRecent;
?>
    <tr>
        <td><?php echo $country['monthName'].' - '.$country['year']; ?></td>
        <td><?php echo ucwords($country['country_name']); ?></td>
        <td><?php echo ($country['totalSample'] >0)?'<a href="/data-collection/' . base64_encode($country['country_id']) . '?type=received&country='.base64_encode($country['country_id']).'&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$country['totalSample'].'</a>':0; ?></td>
        <td><?php echo ($country['samplesIncomplete'] >0)?'<a href="/data-collection/' . base64_encode($country['country_id']) . '?type=incomplete&country='.base64_encode($country['country_id']).'&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$country['samplesIncomplete'].'</a>':0; ?></td>
        <td><?php echo ($country['samplesTested'] >0)?'<a href="/data-collection/' . base64_encode($country['country_id']) . '?type=tested&country='.base64_encode($country['country_id']).'&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$country['samplesTested'].'</a>':0; ?></td>
        <td><?php echo ($country['samplesFinalized'] >0)?'<a href="/data-collection/' . base64_encode($country['country_id']) . '?type=finalized&country='.base64_encode($country['country_id']).'&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$country['samplesFinalized'].'</a>':0; ?></td>
        <td class="labBorder-left"><?php echo ($country['noofLAgRecent'] >0)?'<a href="/data-collection/' . base64_encode($country['country_id']) . '?type=LAg-rececnt&country='.base64_encode($country['country_id']).'&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$country['noofLAgRecent'].'</a>':0; ?></td>
        <td class="labBorder-right"><?php echo ($country['noofLabRecencyAssayRecent'] >0)?'<a href="/data-collection/' . base64_encode($country['country_id']) . '?type=lab-rr-recent&country='.base64_encode($country['country_id']).'&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$country['noofLabRecencyAssayRecent'].'</a>':0; ?></td>
        <td><?php echo ($assessments >0)?'<a href="/clinic/risk-assessment/' . base64_encode($country['country_id']) . '?type=assessment&country='.base64_encode($country['country_id']).'&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$assessments.'</a>':0; ?></td>
        <td><?php echo ($noofANCRecencyTestRecent >0)?'<a href="/clinic/risk-assessment/' . base64_encode($country['country_id']) . '?type=anc-rr-recent&country='.base64_encode($country['country_id']).'&date='.$country['monthName'].'/'.$country['year'].'" target="_blank" title="View">'.$noofANCRecencyTestRecent.'</a>':0; ?></td>
    </tr>
<?php } ?>
    <tr>
        <td colspan="2" class="total_row">Total</td>
        <td class="total_row"><?php echo array_sum($samplesReceivedArray); ?></td>
        <td class="total_row"><?php echo array_sum($samplesIncompleteArray); ?></td>
        <td class="total_row"><?php echo array_sum($samplesTestedArray); ?></td>
        <td class="total_row"><?php echo array_sum($samplesFinalizedArray); ?></td>
        <td class="total_row labBorder-left labBorder-bottom"><?php echo array_sum($noofLAgRecentArray); ?></td>
        <td class="total_row labBorder-right labBorder-bottom"><?php echo array_sum($noofLabRecencyAssayRecentArray); ?></td>
        <td class="total_row"><?php echo array_sum($assessmentsArray); ?></td>
        <td class="total_row"><?php echo array_sum($noofANCRecencyTestRecentArray); ?></td>
    </tr>
<?php } else { ?>
    <tr>
        <td colspan="10">No data available..</td>
    </tr>
<?php } ?>