<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/css/jquery-ui.css' ?>"/>
<style>
    .card-header{
        background-color:#ff69b4;
    }
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        padding: 10px 20px;
    }
    table th,table td{
        text-align:center;
    }
    tbody tr td {
        border-top: 1px solid #ddd;
    }
    #dashboardTable_wrapper{
	overflow-x:scroll;
    }
    .ui-datepicker-calendar {
       display: none;
    }
    .ui-datepicker-month,.ui-datepicker-year{
       display:block;
       display:inline-block;
    }
    .ui-datepicker-title select{
	padding:0;
	height:1.5rem;
    }
    .total_row{
	font-size:15px !important;
	font-weight:800 !important;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <h4 class="page-title">Dashboard</h4>
    </div>
    <div class="row" style="max-width:1109px;">
        <form id="dashboardFilter" action="#">
            <div class="col l12 m12 s12">
                <div class="col l1 m1 s1" style="visibility:hidden;">--COLUMN START--</div>
                <div class="col l5 m5 s5" style="text-align:center;"><strong>Choose Month/Year </strong> <input type="text" class="monthYear" id="reportingMonthYear" name="reportingMonthYear" placeholder="Month and Year" title="Please select month and year" value="<?php echo date('M/Y'); ?>" readonly/></div>
		<div class="col l5 m5 s5" style="text-align:center;"><strong>Countries </strong> <select class="material-select" id="country" name="country" title="Please select country"><option value=""> -- Select -- </option><?php foreach($countries as $country) { ?><option value="<?php echo base64_encode($country['country_id']); ?>"><?php echo ucwords($country['country_name']); ?></option><?php } ?></select></div>
                <div class="col l1 m1 s1" style="visibility:hidden;">--COLUMN END--</div>
            </div>
            <div class="col l12 m12 s12" style="text-align:center;margin-bottom:20px;">
                <a href="javascript:void(0);" onclick="clearSearchFields();" class="waves-effect waves-light btn-small btn red-text custom-btn custom-btn-red"><i class="zmdi zmdi-refresh"></i> Reset</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="searchDashboardData('search');" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="extractDashboardData();" class="waves-effect waves-light btn-small btn green-text custom-btn custom-btn-green"><i class="zmdi zmdi-collection-text"></i> Export Excel</a>
            </div>
        </form>
    </div>
    <div class="row">
        <div class="col s12">
            <div class="card card-default">
                <div class="card-header white-text">
                    Lab Data Reporting/Completed Forms
                </div>
                <div class="card-content clearfix">
                    <table id="dashboardTable" class="responsive-table display">
                        <thead>
                        <tr>
			    <th>Month - Year</th>
                            <th>Name of the Country</th>
                            <th>Samples Received</th>
			    <th>Samples Incomplete</th>
                            <th>Samples Tested</th>
                            <th>Samples Locked for Editing</th>
                            <th>Lab LAg Recent</th>
                            <th>Lab Asante Recent</th>
                            <th>No. of Risk Questionnaires</th>
                            <th>ANC Asante Recent</th>
                        </tr>
                        </thead>
                        <tbody id="dashboardDetails"></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery-ui.js' ?>"></script>
<script>
    $(document).ready(function(){
        $('#reportingMonthYear').datepicker({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'M/yy',
            maxDate: 'Today',
            beforeShow : function(input, inst) {
                tmp = $('#reportingMonthYear').val().split('/');
                var dat = new Date('1 ' + tmp[0] + ' 1969');
                $('#reportingMonthYear').datepicker('option','defaultDate',new Date(tmp[1],parseInt(dat.getMonth()-1)+parseInt(1),1));
                $('#reportingMonthYear').datepicker('setDate', new Date(tmp[1], parseInt(dat.getMonth()-1)+parseInt(1), 1));
            },
            onClose: function(dateText, inst) {
                var month=$("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $('#reportingMonthYear').datepicker('setDate', new Date(year, month, 1));
            }
       });
       searchDashboardData('load');
    });
    
    function searchDashboardData(frmSrc){
        var country = $('#country').val();
        var reportingMonthYear = $('#reportingMonthYear').val();
        if(frmSrc!= 'load') { $.blockUI(); }
        $.post("<?php echo $this->url('get-dashboard-details'); ?>", {country:country,reportingMonthYear: reportingMonthYear},
        function(data) {
            if(frmSrc!= 'load') { $.unblockUI(); }
            $('#dashboardDetails').html(data);
        });
    }
    
    function clearSearchFields(){
       $('#dashboardFilter')[0].reset();
        searchDashboardData('reset');
    }
    
    function extractDashboardData(){
	$.blockUI();
	$.post("<?php echo $this->url('export-dashboard-data'); ?>", { },
	function(data){
	    if(data == "" || data == null || data == undefined){
		alert('OOPS..Unable to generate excel.');
		$.unblockUI();
	    }else{
		$.unblockUI();
		window.open("/temporary/"+data, "_blank");
	    }
	});
    }
</script>