<?php
use Zend\Session\Container;
$loginContainer = new Container('user');
?>
<style>
    .card-header{
        background-color:#ff69b4;
    }
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        padding: 10px 20px;
    }
    table th,table td{
        text-align:center;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <h4 class="page-title">Dashboard</h4>
    </div>
    <?php
    if($loginContainer->roleCode == 'CSC'){
    ?>
        <div class="row">
            <div class="col s12">
                <div class="card card-default">
                    <div class="card-header white-text">
                        Lab Data Reporting / Completed Forms
                    </div>
                    <div class="card-content clearfix">
                        <table class="responsive-table striped">
                            <thead>
                            <tr>
                                <th>Name of the Country</th>
                                <th>No. of Lab Tests</th>
                                <th>No. of Risk Questionnaires</th>
                                <th>No. of Complete Forms</th>
                                <th>Month - Year</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            if(count($row) >0){
                                foreach($row as $country){
                            ?>
                                <tr>
                                    <td><?php echo ucwords($country['country_name']); ?></td>
                                    <td><?php echo $country['totalDataPoints']; ?></td>
                                    <td><?php echo (isset($country['assessments']))?$country['assessments']:0; ?></td>
                                    <td><?php echo $country['dataPointFinalized']; ?></td>
                                    <td><?php echo $country['month'].' - '.$country['year']; ?></td>
                                </tr>
                            <?php } } else { ?>
                                <tr>
                                    <td colspan="5">No data available..</td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    <?php } else { ?>
        <div class="row">
            <div class="col l12 m12 s12">
                Coming Soon..
            </div>
        </div>
    <?php } ?>
</div>