<style>
    .card-header{
        background-color:#ff69b4;
    }
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        padding: 10px 20px;
    }
    table th,table td{
        text-align:center;
    }
    tbody tr td {
        border-top: 1px solid #ddd;
    }
    #dashboardTable_wrapper{
	overflow-x:scroll;
    }
</style>
<div id="page-content">
    <div class="row section-header">
        <h4 class="page-title">Dashboard</h4>
    </div>
    <div class="row">
        <div class="col s12">
            <div class="card card-default">
                <div class="card-header white-text">
                    Lab Data Reporting/Completed Forms
                </div>
                <div class="card-content clearfix">
                    <table id="dashboardTable" class="responsive-table display">
                        <thead>
                        <tr>
                            <th>Name of the Country</th>
                            <th>Samples Received</th>
                            <th>Samples Tested</th>
                            <th>Samples Finalized</th>
			    <th>No. of LAg Recent</th>
			    <th>No. of Recency Assay Recent</th>
			    <th>No. of Risk Questionnaires</th>
			    <th>No. of ANC Recency Test</th>
                            <th>Month - Year</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        if(count($row) >0){
                            foreach($row as $country){
                        ?>
                            <tr>
                                <td><?php echo ucwords($country['country_name']); ?></td>
                                <td><?php echo ($country['totalSample'] >0)?'<a href="/data-collection/' . base64_encode($country['country_id']) . '?type=s-received&date='.$country['month'].'/'.$country['year'].'" target="_blank" title="View">'.$country['totalSample'].'</a>':0; ?></td>
                                <td><?php echo ($country['sampleTested'] >0)?'<a href="/data-collection/' . base64_encode($country['country_id']) . '?type=s-tested&date='.$country['month'].'/'.$country['year'].'" target="_blank" title="View">'.$country['sampleTested'].'</a>':0; ?></td>
                                <td><?php echo ($country['sampleFinalized'] >0)?'<a href="/data-collection/' . base64_encode($country['country_id']) . '?type=s-finalized&date='.$country['month'].'/'.$country['year'].'" target="_blank" title="View">'.$country['sampleFinalized'].'</a>':0; ?></td>
                                <td><?php echo ($country['noofLAgRecent'] >0)?'<a href="/data-collection/' . base64_encode($country['country_id']) . '?type=no-of-lag-rececnt&date='.$country['month'].'/'.$country['year'].'" target="_blank" title="View">'.$country['noofLAgRecent'].'</a>':0; ?></td>
                                <td><?php echo ($country['noofRecencyAssayRecent'] >0)?'<a href="/data-collection/' . base64_encode($country['country_id']) . '?type=no-of-recency-assay-recent&date='.$country['month'].'/'.$country['year'].'" target="_blank" title="View">'.$country['noofRecencyAssayRecent'].'</a>':0; ?></td>
                                <td><?php echo (isset($country['assessments']) && $country['assessments'] >0)?'<a href="/clinic/risk-assessment/' . base64_encode($country['country_id']) . '?type=assessment&date='.$country['month'].'/'.$country['year'].'" target="_blank" title="View">'.$country['assessments'].'</a>':0; ?></td>
                                <td><?php echo (isset($country['noofANCRecencyTest']) && $country['noofANCRecencyTest'] >0)?'<a href="/clinic/risk-assessment/' . base64_encode($country['country_id']) . '?type=no-of-anc-recency-test&date='.$country['month'].'/'.$country['year'].'" target="_blank" title="View">'.$country['noofANCRecencyTest'].'</a>':0; ?></td>
                                <td><?php echo $country['month'].' - '.$country['year']; ?></td>
                            </tr>
                        <?php } } else { ?>
                            <tr>
                                <td colspan="9">No data available..</td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>