<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/daterangepicker/daterangepicker.css' ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() .'/assets/css/chosen.min.css' ?>"/>
<style>
    .ranges{display: none;}
    .daterangepicker .ranges{
        width: 190px;
    }
    @font-face {
        font-family: 'Glyphicons Halflings';
        src: url('../assets/fonts/glyphicons-halflings-regular.eot');
        src: url('../assets/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../assets/fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../assets/fonts/glyphicons-halflings-regular.woff') format('woff'), url('../assets/fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../assets/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
    }
    .glyphicon {
      position: relative;
      top: 1px;
      display: inline-block;
      font-family: 'Glyphicons Halflings';
      font-style: normal;
      font-weight: normal;
      line-height: 1;
    
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }
    .glyphicon-arrow-left:before {
      content: "\e091";
    }
    .glyphicon-arrow-right:before {
      content: "\e092";
    }
    .glyphicon-arrow-up:before {
      content: "\e093";
    }
    .glyphicon-arrow-down:before {
      content: "\e094";
    }
    *{
      -webkit-box-sizing: border-box;
         -moz-box-sizing: border-box;
              box-sizing: border-box;
    }
    *:before,
    *:after {
      -webkit-box-sizing: border-box;
         -moz-box-sizing: border-box;
              box-sizing: border-box;
    }
    /*.left{float: right !important;}*/
    .card-header{
        background-color:#ff69b4;
    }
    .card-default {
        border: 1px solid #eaeaea;
    }
    .card-default .card-header {
        padding: 10px 20px;
    }
    table th,table td{
        text-align:center;
    }
    .select-wrapper{
	width:100%;
    }
    #search-items{
        display: inline-block;
        background: transparent none repeat scroll 0 0;
        font-size: 16px;
        line-height: 40px;
        height: 40px;
        color: black;
        transition: border-color 0.3s ease 0s;
    }
    .search-div i{
        display: inline-block;
        position: absolute;
        bottom: 20px;
        margin-left: -24px;
        color: #000000;
    }
    .search-div label {
        margin-left: 0;
        left: -184px;
    }
    .select-wrapper{
	width:100%;
    }
    .dataTable_noWrap{
	white-space: nowrap;
        overflow: hidden;
    }
    .left_Align{
	text-align:left;
    }
    table.dataTable tbody td{
	padding:4px 4px 4px 4px;
    }
    @media only screen and (max-width: 1024px){
	table.dataTable.display tbody tr:first-child td {
	    border-top: 1px solid #ddd;
        }
	table.dataTable tbody td {
	    padding: 6px 4px 6px 4px;
	}
    }

    table.dataTable thead th, table.dataTable thead td,
    table.dataTable tfoot th, table.dataTable tfoot td{
	text-align:center;
    }

    table.dataTable thead th, table.dataTable thead td,
    table.dataTable tfoot th, table.dataTable tfoot td,
    table.dataTable.row-border tbody th, 
    table.dataTable.row-border tbody td, 
    table.dataTable.display tbody th, 
    table.dataTable.display tbody td{
      border: 1px solid #eeeeef;
    }
    div.ms-drop ul li label{
	font-size:13px !important;
    }
    div.ms-drop ul li label input[type=checkbox],div.ms-drop ul li label{
	position:static !important;
	opacity:1 !important;
	margin-right: 4px !important;
    }
    .chosen-container-single .chosen-search input[type="text"]{
	padding:4px 0px 4px 0px !important;
    }
    #odkSupervisoryAuditDataTable_wrapper{
	overflow-x:scroll;
    }
</style>
<div id="page-content">
    <div class="row section-header">
	<div class="col m7 s12 left-align" style="font-size: 34px;font-weight:400;">ODK Supervisory Audit (<?php echo (isset($countryInfo->country_name) && trim($countryInfo->country_name)!= '')?ucwords($countryInfo->country_name):'#'; ?>)</div>
        <div class="col m5 s12 classic-breadcrumbs right-align">
            <a href="<?php echo $this->url('home'); ?>" class="breadcrumb">Home</a>
            <a href="javascript:void(0);" class="breadcrumb" style="cursor:default;">ODK Supervisory Audit</a>
        </div>
    </div>
    <div class="row" style="max-width:1109px;">
	<form id="odkSupervisoryAuditFilter" action="#">
	    <div class="row">
		<div class="col s6">
		    <div class="input-field col m12 s12">
			<input id="dateRange" name="dateRange" type="text" title="Please enter date" onclick="selectDate();" readonly>
			<label for="dateRange">Date Range </label>
		    </div>
		</div>
		<div class="col s6">
		    <div class="input-field col m12 s12">
			<span style="color:#9e9e9e;">Provinces </span>
			<select id="province" name="province" title="Please select province">
			    <option value="">--Select--</option>
                            <?php
                            if(isset($provinceList) && count($provinceList) > 0){
                                foreach($provinceList as $province){
                            ?>
                               <option value="<?php echo strtolower($province['location_name']); ?>"><?php echo ucwords($province['location_name']); ?></option>
                            <?php } } ?>
			</select>
		    </div>
		</div>
	    </div>
	    <div class="col l12 m12 s12" style="text-align:center;">
		<a href="javascript:void(0);" onclick="clearSearchFields();" class="waves-effect waves-light btn-small btn red-text custom-btn custom-btn-red"><i class="zmdi zmdi-refresh"></i> Reset Filters</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="searchOdkSupervisoryData();" class="waves-effect waves-light btn-small btn black-text custom-btn custom-btn-black"><i class="zmdi zmdi-search"></i> Search</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="javascript:void(0);" onclick="extractOdkSupervisoryData();" class="waves-effect waves-light btn-small btn green-text custom-btn custom-btn-green"><i class="zmdi zmdi-collection-text"></i> Export Excel</a>
	    </div>
	</form>
    </div>
    <div class="row content-container">
	<div class="col l12 m12 s12">
	    <div class="card card-default">
		<div class="card-header white-text"><i class="zmdi zmdi-filter-list"></i>ODK Supervisory Audit List </div>
		<div class="card-content clearfix">
		    <table id="odkSupervisoryAuditDataTable" class="responsive-table display dataTable">
			<thead>
			<tr>
			    <th rowspan="2">Clinic ID</th>
			    <th rowspan="2">Clinic name</th>
			    <th rowspan="2">Number of visits to clinic</th>
                            <th rowspan="2">Reporting Period</th>
                            <th rowspan="2">Support Visit Date</th>
                            <th rowspan="2">Number of women who declined to participate in this reporting period</th>
                            <th colspan="6">Reasons for refusal in this reporting period</th>
                            <th rowspan="2">Number of eligible women who were not invited to participate in this reporting period</th>
                            <th rowspan="2">Number of ineligible women who were enrolled in this reporting period</th>
                            <th rowspan="2">DC Assessment - Screening</th>
                            <th rowspan="2">DC Assessment - Informed Consent</th>
                            <th rowspan="2">DC Assessment - Blood Collection</th>
                            <th rowspan="2">DC Assessment - Packaging and Storage</th>
                            <th rowspan="2">DC Assessment - Return of Results</th>
			</tr>
                        <tr>
                            <th>Do not have time to participate in study</th>
                            <th>Not interested in this study</th>
                            <th>Fear of needles or blood draw</th>
                            <th>Religious objection to blood draw</th>
                            <th>Need partner permission to participate</th>
                            <th>Other</th>
                        </tr>
			</thead>
			<tfoot>
                        <tr>
			    <th rowspan="2">Clinic ID</th>
			    <th rowspan="2">Clinic name</th>
			    <th rowspan="2">Number of visits to clinic</th>
                            <th rowspan="2">Reporting Period</th>
                            <th rowspan="2">Support Visit Date</th>
                            <th rowspan="2">Number of women who declined to participate in this reporting period</th>
                            <th colspan="6">Reasons for refusal in this reporting period</th>
                            <th rowspan="2">Number of eligible women who were not invited to participate in this reporting period</th>
                            <th rowspan="2">Number of ineligible women who were enrolled in this reporting period</th>
                            <th rowspan="2">DC Assessment - Screening</th>
                            <th rowspan="2">DC Assessment - Informed Consent</th>
                            <th rowspan="2">DC Assessment - Blood Collection</th>
                            <th rowspan="2">DC Assessment - Packaging and Storage</th>
                            <th rowspan="2">DC Assessment - Return of Results</th>
			</tr>
                        <tr>
                            <th>Do not have time to participate in study</th>
                            <th>Not interested in this study</th>
                            <th>Fear of needles or blood draw</th>
                            <th>Religious objection to blood draw</th>
                            <th>Need partner permission to participate</th>
                            <th>Other</th>
                        </tr>
			</tfoot>
			<tbody>
			</tbody>
		    </table>
		</div>
	    </div>
	</div>
    </div>
</div>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/jquery-ui.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/daterangepicker/daterangepicker.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() .'/assets/js/chosen.jquery.js' ?>"></script>
<script>
    oTable = null;
    $(document).ready(function(){
        $("#province").chosen({
	    placeholder_text_single:"Select Province", 
	    width:"100%"
	});
       oTable = $('#odkSupervisoryAuditDataTable').dataTable({
	    "autoWidth": false,
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
	    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
	    "iDisplayLength": 25,
            "aoColumns": [
		{"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"},
                {"sClass":"dataTable_noWrap left_Align"}
            ],
            "aaSorting": [[1, "asc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url('odk-supervisory-audit'); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
		aoData.push({"name": "dateRange", "value": $('#dateRange').val()});
		aoData.push({"name": "province", "value": $('#province').val()});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
       
        $('.dataTables_filter').empty(); // clears the content generated
        $('.dataTables_filter').append(
                "<div class='input-field col s6 search-div right' style='width: 250px'>" +
                "    <i class='material-icons search-icon'>search</i> "+
                "    <input id='search-items' type='text' class='validate' />" +
                "    <label for='icon_prefix' class='search-label'>Search</label>   "+
                "</div>");
        $(document).on('keyup', "input[type='text']", function(){
	    oTable.fnFilter($(this).val());
	});
        selectDate();
    });
    
    function selectDate(){
        $(".ranges").show();
        $(".left").css({"float":"none !important"});
        $('#dateRange').daterangepicker({
            format: 'DD-MMM-YYYY',
	    separator: ' to ',
            maxDate: moment(),
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                'Last 7 Days': [moment().subtract('days', 6), moment()],
                'Last 30 Days': [moment().subtract('days', 29), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
            },
        },function(start, end) {
            startDate = start.format('YYYY-MM-DD');
            endDate = end.format('YYYY-MM-DD');
            $('label[for="dateRange"]').css("transform", "translateY(-140%)");
        });
        $('.applyBtn').addClass('waves-effect waves-light btn-small white-text blue margin-bottom-10');
        $('.cancelBtn').addClass('waves-effect waves-light btn-small btn blue-text custom-btn custom-btn-blue margin-bottom-10');
    }
    
    function searchOdkSupervisoryData(){
        oTable.fnDraw(false);
    }
    
    function clearSearchFields(){
       $('#odkSupervisoryAuditFilter')[0].reset();
       $("#province").val('').trigger("chosen:updated");
       $('label[for="dateRange"]').css("transform", "translateY(0%)");
       searchOdkSupervisoryData();
    }
</script>